// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emailplus.proxies;

public class EmailAccount
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject emailAccountMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EmailPlus.EmailAccount";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Description("Description"),
		UserName("UserName"),
		PassWord("PassWord"),
		EmailAddress("EmailAddress"),
		IsDefaultSendWithReply("IsDefaultSendWithReply"),
		IsDefaultSendNoReply("IsDefaultSendNoReply"),
		IsReceive("IsReceive"),
		DeleteBehaviour("DeleteBehaviour"),
		AccountType("AccountType"),
		ReplyTo("ReplyTo"),
		EncryptedPassword("EncryptedPassword"),
		EmailAccount_EmailSettings("EmailPlus.EmailAccount_EmailSettings"),
		IncomingMessageTrigger_EmailAccount("EmailPlus.IncomingMessageTrigger_EmailAccount");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EmailAccount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "EmailPlus.EmailAccount"));
	}

	protected EmailAccount(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject emailAccountMendixObject)
	{
		if (emailAccountMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("EmailPlus.EmailAccount", emailAccountMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a EmailPlus.EmailAccount");

		this.emailAccountMendixObject = emailAccountMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'EmailAccount.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static emailplus.proxies.EmailAccount initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return emailplus.proxies.EmailAccount.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static emailplus.proxies.EmailAccount initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new emailplus.proxies.EmailAccount(context, mendixObject);
	}

	public static emailplus.proxies.EmailAccount load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return emailplus.proxies.EmailAccount.initialize(context, mendixObject);
	}

	public static java.util.List<emailplus.proxies.EmailAccount> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<emailplus.proxies.EmailAccount> result = new java.util.ArrayList<emailplus.proxies.EmailAccount>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//EmailPlus.EmailAccount" + xpathConstraint))
			result.add(emailplus.proxies.EmailAccount.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of UserName
	 */
	public final java.lang.String getUserName()
	{
		return getUserName(getContext());
	}

	/**
	 * @param context
	 * @return value of UserName
	 */
	public final java.lang.String getUserName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserName.toString());
	}

	/**
	 * Set value of UserName
	 * @param username
	 */
	public final void setUserName(java.lang.String username)
	{
		setUserName(getContext(), username);
	}

	/**
	 * Set value of UserName
	 * @param context
	 * @param username
	 */
	public final void setUserName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.UserName.toString(), username);
	}

	/**
	 * @return value of PassWord
	 */
	public final java.lang.String getPassWord()
	{
		return getPassWord(getContext());
	}

	/**
	 * @param context
	 * @return value of PassWord
	 */
	public final java.lang.String getPassWord(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PassWord.toString());
	}

	/**
	 * Set value of PassWord
	 * @param password
	 */
	public final void setPassWord(java.lang.String password)
	{
		setPassWord(getContext(), password);
	}

	/**
	 * Set value of PassWord
	 * @param context
	 * @param password
	 */
	public final void setPassWord(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String password)
	{
		getMendixObject().setValue(context, MemberNames.PassWord.toString(), password);
	}

	/**
	 * @return value of EmailAddress
	 */
	public final java.lang.String getEmailAddress()
	{
		return getEmailAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailAddress
	 */
	public final java.lang.String getEmailAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmailAddress.toString());
	}

	/**
	 * Set value of EmailAddress
	 * @param emailaddress
	 */
	public final void setEmailAddress(java.lang.String emailaddress)
	{
		setEmailAddress(getContext(), emailaddress);
	}

	/**
	 * Set value of EmailAddress
	 * @param context
	 * @param emailaddress
	 */
	public final void setEmailAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emailaddress)
	{
		getMendixObject().setValue(context, MemberNames.EmailAddress.toString(), emailaddress);
	}

	/**
	 * @return value of IsDefaultSendWithReply
	 */
	public final java.lang.Boolean getIsDefaultSendWithReply()
	{
		return getIsDefaultSendWithReply(getContext());
	}

	/**
	 * @param context
	 * @return value of IsDefaultSendWithReply
	 */
	public final java.lang.Boolean getIsDefaultSendWithReply(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsDefaultSendWithReply.toString());
	}

	/**
	 * Set value of IsDefaultSendWithReply
	 * @param isdefaultsendwithreply
	 */
	public final void setIsDefaultSendWithReply(java.lang.Boolean isdefaultsendwithreply)
	{
		setIsDefaultSendWithReply(getContext(), isdefaultsendwithreply);
	}

	/**
	 * Set value of IsDefaultSendWithReply
	 * @param context
	 * @param isdefaultsendwithreply
	 */
	public final void setIsDefaultSendWithReply(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isdefaultsendwithreply)
	{
		getMendixObject().setValue(context, MemberNames.IsDefaultSendWithReply.toString(), isdefaultsendwithreply);
	}

	/**
	 * @return value of IsDefaultSendNoReply
	 */
	public final java.lang.Boolean getIsDefaultSendNoReply()
	{
		return getIsDefaultSendNoReply(getContext());
	}

	/**
	 * @param context
	 * @return value of IsDefaultSendNoReply
	 */
	public final java.lang.Boolean getIsDefaultSendNoReply(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsDefaultSendNoReply.toString());
	}

	/**
	 * Set value of IsDefaultSendNoReply
	 * @param isdefaultsendnoreply
	 */
	public final void setIsDefaultSendNoReply(java.lang.Boolean isdefaultsendnoreply)
	{
		setIsDefaultSendNoReply(getContext(), isdefaultsendnoreply);
	}

	/**
	 * Set value of IsDefaultSendNoReply
	 * @param context
	 * @param isdefaultsendnoreply
	 */
	public final void setIsDefaultSendNoReply(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isdefaultsendnoreply)
	{
		getMendixObject().setValue(context, MemberNames.IsDefaultSendNoReply.toString(), isdefaultsendnoreply);
	}

	/**
	 * @return value of IsReceive
	 */
	public final java.lang.Boolean getIsReceive()
	{
		return getIsReceive(getContext());
	}

	/**
	 * @param context
	 * @return value of IsReceive
	 */
	public final java.lang.Boolean getIsReceive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsReceive.toString());
	}

	/**
	 * Set value of IsReceive
	 * @param isreceive
	 */
	public final void setIsReceive(java.lang.Boolean isreceive)
	{
		setIsReceive(getContext(), isreceive);
	}

	/**
	 * Set value of IsReceive
	 * @param context
	 * @param isreceive
	 */
	public final void setIsReceive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isreceive)
	{
		getMendixObject().setValue(context, MemberNames.IsReceive.toString(), isreceive);
	}

	/**
	 * Set value of DeleteBehaviour
	 * @param deletebehaviour
	 */
	public final emailplus.proxies.DeleteBehaviourPop3 getDeleteBehaviour()
	{
		return getDeleteBehaviour(getContext());
	}

	/**
	 * @param context
	 * @return value of DeleteBehaviour
	 */
	public final emailplus.proxies.DeleteBehaviourPop3 getDeleteBehaviour(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.DeleteBehaviour.toString());
		if (obj == null)
			return null;

		return emailplus.proxies.DeleteBehaviourPop3.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of DeleteBehaviour
	 * @param deletebehaviour
	 */
	public final void setDeleteBehaviour(emailplus.proxies.DeleteBehaviourPop3 deletebehaviour)
	{
		setDeleteBehaviour(getContext(), deletebehaviour);
	}

	/**
	 * Set value of DeleteBehaviour
	 * @param context
	 * @param deletebehaviour
	 */
	public final void setDeleteBehaviour(com.mendix.systemwideinterfaces.core.IContext context, emailplus.proxies.DeleteBehaviourPop3 deletebehaviour)
	{
		if (deletebehaviour != null)
			getMendixObject().setValue(context, MemberNames.DeleteBehaviour.toString(), deletebehaviour.toString());
		else
			getMendixObject().setValue(context, MemberNames.DeleteBehaviour.toString(), null);
	}

	/**
	 * Set value of AccountType
	 * @param accounttype
	 */
	public final emailplus.proxies.EmailSendReceiveBothEnum getAccountType()
	{
		return getAccountType(getContext());
	}

	/**
	 * @param context
	 * @return value of AccountType
	 */
	public final emailplus.proxies.EmailSendReceiveBothEnum getAccountType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.AccountType.toString());
		if (obj == null)
			return null;

		return emailplus.proxies.EmailSendReceiveBothEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of AccountType
	 * @param accounttype
	 */
	public final void setAccountType(emailplus.proxies.EmailSendReceiveBothEnum accounttype)
	{
		setAccountType(getContext(), accounttype);
	}

	/**
	 * Set value of AccountType
	 * @param context
	 * @param accounttype
	 */
	public final void setAccountType(com.mendix.systemwideinterfaces.core.IContext context, emailplus.proxies.EmailSendReceiveBothEnum accounttype)
	{
		if (accounttype != null)
			getMendixObject().setValue(context, MemberNames.AccountType.toString(), accounttype.toString());
		else
			getMendixObject().setValue(context, MemberNames.AccountType.toString(), null);
	}

	/**
	 * @return value of ReplyTo
	 */
	public final java.lang.String getReplyTo()
	{
		return getReplyTo(getContext());
	}

	/**
	 * @param context
	 * @return value of ReplyTo
	 */
	public final java.lang.String getReplyTo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReplyTo.toString());
	}

	/**
	 * Set value of ReplyTo
	 * @param replyto
	 */
	public final void setReplyTo(java.lang.String replyto)
	{
		setReplyTo(getContext(), replyto);
	}

	/**
	 * Set value of ReplyTo
	 * @param context
	 * @param replyto
	 */
	public final void setReplyTo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String replyto)
	{
		getMendixObject().setValue(context, MemberNames.ReplyTo.toString(), replyto);
	}

	/**
	 * @return value of EncryptedPassword
	 */
	public final java.lang.String getEncryptedPassword()
	{
		return getEncryptedPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of EncryptedPassword
	 */
	public final java.lang.String getEncryptedPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EncryptedPassword.toString());
	}

	/**
	 * Set value of EncryptedPassword
	 * @param encryptedpassword
	 */
	public final void setEncryptedPassword(java.lang.String encryptedpassword)
	{
		setEncryptedPassword(getContext(), encryptedpassword);
	}

	/**
	 * Set value of EncryptedPassword
	 * @param context
	 * @param encryptedpassword
	 */
	public final void setEncryptedPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String encryptedpassword)
	{
		getMendixObject().setValue(context, MemberNames.EncryptedPassword.toString(), encryptedpassword);
	}

	/**
	 * @return value of EmailAccount_EmailSettings
	 */
	public final emailplus.proxies.EmailSettings getEmailAccount_EmailSettings() throws com.mendix.core.CoreException
	{
		return getEmailAccount_EmailSettings(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailAccount_EmailSettings
	 */
	public final emailplus.proxies.EmailSettings getEmailAccount_EmailSettings(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emailplus.proxies.EmailSettings result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EmailAccount_EmailSettings.toString());
		if (identifier != null)
			result = emailplus.proxies.EmailSettings.load(context, identifier);
		return result;
	}

	/**
	 * Set value of EmailAccount_EmailSettings
	 * @param emailaccount_emailsettings
	 */
	public final void setEmailAccount_EmailSettings(emailplus.proxies.EmailSettings emailaccount_emailsettings)
	{
		setEmailAccount_EmailSettings(getContext(), emailaccount_emailsettings);
	}

	/**
	 * Set value of EmailAccount_EmailSettings
	 * @param context
	 * @param emailaccount_emailsettings
	 */
	public final void setEmailAccount_EmailSettings(com.mendix.systemwideinterfaces.core.IContext context, emailplus.proxies.EmailSettings emailaccount_emailsettings)
	{
		if (emailaccount_emailsettings == null)
			getMendixObject().setValue(context, MemberNames.EmailAccount_EmailSettings.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.EmailAccount_EmailSettings.toString(), emailaccount_emailsettings.getMendixObject().getId());
	}

	/**
	 * @return value of IncomingMessageTrigger_EmailAccount
	 */
	public final emailplus.proxies.IncomingMessageTrigger getIncomingMessageTrigger_EmailAccount() throws com.mendix.core.CoreException
	{
		return getIncomingMessageTrigger_EmailAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of IncomingMessageTrigger_EmailAccount
	 */
	public final emailplus.proxies.IncomingMessageTrigger getIncomingMessageTrigger_EmailAccount(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emailplus.proxies.IncomingMessageTrigger result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.IncomingMessageTrigger_EmailAccount.toString());
		if (identifier != null)
			result = emailplus.proxies.IncomingMessageTrigger.load(context, identifier);
		return result;
	}

	/**
	 * Set value of IncomingMessageTrigger_EmailAccount
	 * @param incomingmessagetrigger_emailaccount
	 */
	public final void setIncomingMessageTrigger_EmailAccount(emailplus.proxies.IncomingMessageTrigger incomingmessagetrigger_emailaccount)
	{
		setIncomingMessageTrigger_EmailAccount(getContext(), incomingmessagetrigger_emailaccount);
	}

	/**
	 * Set value of IncomingMessageTrigger_EmailAccount
	 * @param context
	 * @param incomingmessagetrigger_emailaccount
	 */
	public final void setIncomingMessageTrigger_EmailAccount(com.mendix.systemwideinterfaces.core.IContext context, emailplus.proxies.IncomingMessageTrigger incomingmessagetrigger_emailaccount)
	{
		if (incomingmessagetrigger_emailaccount == null)
			getMendixObject().setValue(context, MemberNames.IncomingMessageTrigger_EmailAccount.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.IncomingMessageTrigger_EmailAccount.toString(), incomingmessagetrigger_emailaccount.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return emailAccountMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emailplus.proxies.EmailAccount that = (emailplus.proxies.EmailAccount) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "EmailPlus.EmailAccount";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
