// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mendix.actions;

import java.util.List;
import com.mendix.core.Core;
import com.mendix.core.conf.Configuration;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class GetAdminUser extends CustomJavaAction<IMendixObject>
{
	public GetAdminUser(IContext context)
	{
		super(context);
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		Configuration configuration = Core.getConfiguration();
		String adminUser = configuration.getAdminUserName();
		if (adminUser==null) return null;
		List<IMendixObject> iMendixObjects = Core.retrieveXPathQuery(this.getContext(), "\\System.User[Name='"+adminUser+"'");
		if (iMendixObjects==null || iMendixObjects.size()==0) return null;
		return iMendixObjects.get(0);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetAdminUser";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
