// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package interfacerelations.proxies;

public class OutgoingRelationsConfirmationExpertDesk extends interfaceshared.proxies.AuditableEntity
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "InterfaceRelations.OutgoingRelationsConfirmationExpertDesk";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ConfirmationMessageID("ConfirmationMessageID"),
		MessageID("MessageID"),
		InterfaceName("InterfaceName"),
		RelationsResponseContainerExpertDesk_OutgoingRelationsConfirmationExpertDesk("InterfaceRelations.RelationsResponseContainerExpertDesk_OutgoingRelationsConfirmationExpertDesk"),
		OutgoingRelationsConfirmationExpertDesk_OutgoingRelationsConfirmationMessageExpertDesk("InterfaceRelations.OutgoingRelationsConfirmationExpertDesk_OutgoingRelationsConfirmationMessageExpertDesk");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OutgoingRelationsConfirmationExpertDesk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "InterfaceRelations.OutgoingRelationsConfirmationExpertDesk"));
	}

	protected OutgoingRelationsConfirmationExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject outgoingRelationsConfirmationExpertDeskMendixObject)
	{
		super(context, outgoingRelationsConfirmationExpertDeskMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("InterfaceRelations.OutgoingRelationsConfirmationExpertDesk", outgoingRelationsConfirmationExpertDeskMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a InterfaceRelations.OutgoingRelationsConfirmationExpertDesk");
	}

	/**
	 * @deprecated Use 'OutgoingRelationsConfirmationExpertDesk.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static interfacerelations.proxies.OutgoingRelationsConfirmationExpertDesk initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return interfacerelations.proxies.OutgoingRelationsConfirmationExpertDesk.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static interfacerelations.proxies.OutgoingRelationsConfirmationExpertDesk initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new interfacerelations.proxies.OutgoingRelationsConfirmationExpertDesk(context, mendixObject);
	}

	public static interfacerelations.proxies.OutgoingRelationsConfirmationExpertDesk load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return interfacerelations.proxies.OutgoingRelationsConfirmationExpertDesk.initialize(context, mendixObject);
	}

	public static java.util.List<interfacerelations.proxies.OutgoingRelationsConfirmationExpertDesk> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<interfacerelations.proxies.OutgoingRelationsConfirmationExpertDesk> result = new java.util.ArrayList<interfacerelations.proxies.OutgoingRelationsConfirmationExpertDesk>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//InterfaceRelations.OutgoingRelationsConfirmationExpertDesk" + xpathConstraint))
			result.add(interfacerelations.proxies.OutgoingRelationsConfirmationExpertDesk.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of ConfirmationMessageID
	 */
	public final java.lang.String getConfirmationMessageID()
	{
		return getConfirmationMessageID(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfirmationMessageID
	 */
	public final java.lang.String getConfirmationMessageID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ConfirmationMessageID.toString());
	}

	/**
	 * Set value of ConfirmationMessageID
	 * @param confirmationmessageid
	 */
	public final void setConfirmationMessageID(java.lang.String confirmationmessageid)
	{
		setConfirmationMessageID(getContext(), confirmationmessageid);
	}

	/**
	 * Set value of ConfirmationMessageID
	 * @param context
	 * @param confirmationmessageid
	 */
	public final void setConfirmationMessageID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String confirmationmessageid)
	{
		getMendixObject().setValue(context, MemberNames.ConfirmationMessageID.toString(), confirmationmessageid);
	}

	/**
	 * @return value of MessageID
	 */
	public final java.lang.String getMessageID()
	{
		return getMessageID(getContext());
	}

	/**
	 * @param context
	 * @return value of MessageID
	 */
	public final java.lang.String getMessageID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MessageID.toString());
	}

	/**
	 * Set value of MessageID
	 * @param messageid
	 */
	public final void setMessageID(java.lang.String messageid)
	{
		setMessageID(getContext(), messageid);
	}

	/**
	 * Set value of MessageID
	 * @param context
	 * @param messageid
	 */
	public final void setMessageID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String messageid)
	{
		getMendixObject().setValue(context, MemberNames.MessageID.toString(), messageid);
	}

	/**
	 * @return value of InterfaceName
	 */
	public final java.lang.String getInterfaceName()
	{
		return getInterfaceName(getContext());
	}

	/**
	 * @param context
	 * @return value of InterfaceName
	 */
	public final java.lang.String getInterfaceName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InterfaceName.toString());
	}

	/**
	 * Set value of InterfaceName
	 * @param interfacename
	 */
	public final void setInterfaceName(java.lang.String interfacename)
	{
		setInterfaceName(getContext(), interfacename);
	}

	/**
	 * Set value of InterfaceName
	 * @param context
	 * @param interfacename
	 */
	public final void setInterfaceName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String interfacename)
	{
		getMendixObject().setValue(context, MemberNames.InterfaceName.toString(), interfacename);
	}

	/**
	 * @return value of RelationsResponseContainerExpertDesk_OutgoingRelationsConfirmationExpertDesk
	 */
	public final interfacerelations.proxies.RelationsResponseContainerExpertDesk getRelationsResponseContainerExpertDesk_OutgoingRelationsConfirmationExpertDesk() throws com.mendix.core.CoreException
	{
		return getRelationsResponseContainerExpertDesk_OutgoingRelationsConfirmationExpertDesk(getContext());
	}

	/**
	 * @param context
	 * @return value of RelationsResponseContainerExpertDesk_OutgoingRelationsConfirmationExpertDesk
	 */
	public final interfacerelations.proxies.RelationsResponseContainerExpertDesk getRelationsResponseContainerExpertDesk_OutgoingRelationsConfirmationExpertDesk(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacerelations.proxies.RelationsResponseContainerExpertDesk result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RelationsResponseContainerExpertDesk_OutgoingRelationsConfirmationExpertDesk.toString());
		if (identifier != null)
			result = interfacerelations.proxies.RelationsResponseContainerExpertDesk.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RelationsResponseContainerExpertDesk_OutgoingRelationsConfirmationExpertDesk
	 * @param relationsresponsecontainerexpertdesk_outgoingrelationsconfirmationexpertdesk
	 */
	public final void setRelationsResponseContainerExpertDesk_OutgoingRelationsConfirmationExpertDesk(interfacerelations.proxies.RelationsResponseContainerExpertDesk relationsresponsecontainerexpertdesk_outgoingrelationsconfirmationexpertdesk)
	{
		setRelationsResponseContainerExpertDesk_OutgoingRelationsConfirmationExpertDesk(getContext(), relationsresponsecontainerexpertdesk_outgoingrelationsconfirmationexpertdesk);
	}

	/**
	 * Set value of RelationsResponseContainerExpertDesk_OutgoingRelationsConfirmationExpertDesk
	 * @param context
	 * @param relationsresponsecontainerexpertdesk_outgoingrelationsconfirmationexpertdesk
	 */
	public final void setRelationsResponseContainerExpertDesk_OutgoingRelationsConfirmationExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, interfacerelations.proxies.RelationsResponseContainerExpertDesk relationsresponsecontainerexpertdesk_outgoingrelationsconfirmationexpertdesk)
	{
		if (relationsresponsecontainerexpertdesk_outgoingrelationsconfirmationexpertdesk == null)
			getMendixObject().setValue(context, MemberNames.RelationsResponseContainerExpertDesk_OutgoingRelationsConfirmationExpertDesk.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RelationsResponseContainerExpertDesk_OutgoingRelationsConfirmationExpertDesk.toString(), relationsresponsecontainerexpertdesk_outgoingrelationsconfirmationexpertdesk.getMendixObject().getId());
	}

	/**
	 * @return value of OutgoingRelationsConfirmationExpertDesk_OutgoingRelationsConfirmationMessageExpertDesk
	 */
	public final interfacerelations.proxies.OutgoingRelationsConfirmationMessageExpertDesk getOutgoingRelationsConfirmationExpertDesk_OutgoingRelationsConfirmationMessageExpertDesk() throws com.mendix.core.CoreException
	{
		return getOutgoingRelationsConfirmationExpertDesk_OutgoingRelationsConfirmationMessageExpertDesk(getContext());
	}

	/**
	 * @param context
	 * @return value of OutgoingRelationsConfirmationExpertDesk_OutgoingRelationsConfirmationMessageExpertDesk
	 */
	public final interfacerelations.proxies.OutgoingRelationsConfirmationMessageExpertDesk getOutgoingRelationsConfirmationExpertDesk_OutgoingRelationsConfirmationMessageExpertDesk(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacerelations.proxies.OutgoingRelationsConfirmationMessageExpertDesk result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OutgoingRelationsConfirmationExpertDesk_OutgoingRelationsConfirmationMessageExpertDesk.toString());
		if (identifier != null)
			result = interfacerelations.proxies.OutgoingRelationsConfirmationMessageExpertDesk.load(context, identifier);
		return result;
	}

	/**
	 * Set value of OutgoingRelationsConfirmationExpertDesk_OutgoingRelationsConfirmationMessageExpertDesk
	 * @param outgoingrelationsconfirmationexpertdesk_outgoingrelationsconfirmationmessageexpertdesk
	 */
	public final void setOutgoingRelationsConfirmationExpertDesk_OutgoingRelationsConfirmationMessageExpertDesk(interfacerelations.proxies.OutgoingRelationsConfirmationMessageExpertDesk outgoingrelationsconfirmationexpertdesk_outgoingrelationsconfirmationmessageexpertdesk)
	{
		setOutgoingRelationsConfirmationExpertDesk_OutgoingRelationsConfirmationMessageExpertDesk(getContext(), outgoingrelationsconfirmationexpertdesk_outgoingrelationsconfirmationmessageexpertdesk);
	}

	/**
	 * Set value of OutgoingRelationsConfirmationExpertDesk_OutgoingRelationsConfirmationMessageExpertDesk
	 * @param context
	 * @param outgoingrelationsconfirmationexpertdesk_outgoingrelationsconfirmationmessageexpertdesk
	 */
	public final void setOutgoingRelationsConfirmationExpertDesk_OutgoingRelationsConfirmationMessageExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, interfacerelations.proxies.OutgoingRelationsConfirmationMessageExpertDesk outgoingrelationsconfirmationexpertdesk_outgoingrelationsconfirmationmessageexpertdesk)
	{
		if (outgoingrelationsconfirmationexpertdesk_outgoingrelationsconfirmationmessageexpertdesk == null)
			getMendixObject().setValue(context, MemberNames.OutgoingRelationsConfirmationExpertDesk_OutgoingRelationsConfirmationMessageExpertDesk.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.OutgoingRelationsConfirmationExpertDesk_OutgoingRelationsConfirmationMessageExpertDesk.toString(), outgoingrelationsconfirmationexpertdesk_outgoingrelationsconfirmationmessageexpertdesk.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final interfacerelations.proxies.OutgoingRelationsConfirmationExpertDesk that = (interfacerelations.proxies.OutgoingRelationsConfirmationExpertDesk) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "InterfaceRelations.OutgoingRelationsConfirmationExpertDesk";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
