// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package interfacerelations.proxies;

public class Relation extends interfaceshared.proxies.AuditableEntity
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "InterfaceRelations.Relation";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RelationGUID("RelationGUID"),
		ChildExternalReferenceID("ChildExternalReferenceID"),
		ChildInternalReferenceID("ChildInternalReferenceID"),
		ParentExternalReferenceID("ParentExternalReferenceID"),
		ParentInternalReferenceID("ParentInternalReferenceID"),
		Operation("Operation"),
		RelationType("RelationType"),
		SolveChildOnSolve("SolveChildOnSolve"),
		SolveParentOnSolve("SolveParentOnSolve"),
		CloseChildOnClose("CloseChildOnClose"),
		CloseParentOnClose("CloseParentOnClose"),
		NotifyChildOnSolve("NotifyChildOnSolve"),
		NotifyParentOnSolve("NotifyParentOnSolve"),
		NotifyChildOnClose("NotifyChildOnClose"),
		NotifyParentOnClose("NotifyParentOnClose"),
		AutomaticActions("AutomaticActions"),
		IsLinkedFromParent("IsLinkedFromParent"),
		IsLinkedFromChild("IsLinkedFromChild"),
		RelationResponse_Relation("InterfaceRelations.RelationResponse_Relation"),
		Relation_IncomingRelations("InterfaceRelations.Relation_IncomingRelations"),
		RelationResponseGUID_RelationsContainerExpertDesk("InterfaceRelations.RelationResponseGUID_RelationsContainerExpertDesk"),
		Relation_RelationsContainerExpertDesk("InterfaceRelations.Relation_RelationsContainerExpertDesk"),
		Relation_IncomingRequest("InterfaceRelations.Relation_IncomingRequest"),
		Relation_TicketRelations("InterfaceRelations.Relation_TicketRelations"),
		Relation_ParentRequest("InterfaceRelations.Relation_ParentRequest"),
		Relation_ChildRequest("InterfaceRelations.Relation_ChildRequest");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Relation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "InterfaceRelations.Relation"));
	}

	protected Relation(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject relationMendixObject)
	{
		super(context, relationMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("InterfaceRelations.Relation", relationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a InterfaceRelations.Relation");
	}

	/**
	 * @deprecated Use 'Relation.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static interfacerelations.proxies.Relation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return interfacerelations.proxies.Relation.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static interfacerelations.proxies.Relation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new interfacerelations.proxies.Relation(context, mendixObject);
	}

	public static interfacerelations.proxies.Relation load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return interfacerelations.proxies.Relation.initialize(context, mendixObject);
	}

	public static java.util.List<interfacerelations.proxies.Relation> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<interfacerelations.proxies.Relation> result = new java.util.ArrayList<interfacerelations.proxies.Relation>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//InterfaceRelations.Relation" + xpathConstraint))
			result.add(interfacerelations.proxies.Relation.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of RelationGUID
	 */
	public final java.lang.String getRelationGUID()
	{
		return getRelationGUID(getContext());
	}

	/**
	 * @param context
	 * @return value of RelationGUID
	 */
	public final java.lang.String getRelationGUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RelationGUID.toString());
	}

	/**
	 * Set value of RelationGUID
	 * @param relationguid
	 */
	public final void setRelationGUID(java.lang.String relationguid)
	{
		setRelationGUID(getContext(), relationguid);
	}

	/**
	 * Set value of RelationGUID
	 * @param context
	 * @param relationguid
	 */
	public final void setRelationGUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String relationguid)
	{
		getMendixObject().setValue(context, MemberNames.RelationGUID.toString(), relationguid);
	}

	/**
	 * @return value of ChildExternalReferenceID
	 */
	public final java.lang.String getChildExternalReferenceID()
	{
		return getChildExternalReferenceID(getContext());
	}

	/**
	 * @param context
	 * @return value of ChildExternalReferenceID
	 */
	public final java.lang.String getChildExternalReferenceID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ChildExternalReferenceID.toString());
	}

	/**
	 * Set value of ChildExternalReferenceID
	 * @param childexternalreferenceid
	 */
	public final void setChildExternalReferenceID(java.lang.String childexternalreferenceid)
	{
		setChildExternalReferenceID(getContext(), childexternalreferenceid);
	}

	/**
	 * Set value of ChildExternalReferenceID
	 * @param context
	 * @param childexternalreferenceid
	 */
	public final void setChildExternalReferenceID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String childexternalreferenceid)
	{
		getMendixObject().setValue(context, MemberNames.ChildExternalReferenceID.toString(), childexternalreferenceid);
	}

	/**
	 * @return value of ChildInternalReferenceID
	 */
	public final java.lang.String getChildInternalReferenceID()
	{
		return getChildInternalReferenceID(getContext());
	}

	/**
	 * @param context
	 * @return value of ChildInternalReferenceID
	 */
	public final java.lang.String getChildInternalReferenceID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ChildInternalReferenceID.toString());
	}

	/**
	 * Set value of ChildInternalReferenceID
	 * @param childinternalreferenceid
	 */
	public final void setChildInternalReferenceID(java.lang.String childinternalreferenceid)
	{
		setChildInternalReferenceID(getContext(), childinternalreferenceid);
	}

	/**
	 * Set value of ChildInternalReferenceID
	 * @param context
	 * @param childinternalreferenceid
	 */
	public final void setChildInternalReferenceID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String childinternalreferenceid)
	{
		getMendixObject().setValue(context, MemberNames.ChildInternalReferenceID.toString(), childinternalreferenceid);
	}

	/**
	 * @return value of ParentExternalReferenceID
	 */
	public final java.lang.String getParentExternalReferenceID()
	{
		return getParentExternalReferenceID(getContext());
	}

	/**
	 * @param context
	 * @return value of ParentExternalReferenceID
	 */
	public final java.lang.String getParentExternalReferenceID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ParentExternalReferenceID.toString());
	}

	/**
	 * Set value of ParentExternalReferenceID
	 * @param parentexternalreferenceid
	 */
	public final void setParentExternalReferenceID(java.lang.String parentexternalreferenceid)
	{
		setParentExternalReferenceID(getContext(), parentexternalreferenceid);
	}

	/**
	 * Set value of ParentExternalReferenceID
	 * @param context
	 * @param parentexternalreferenceid
	 */
	public final void setParentExternalReferenceID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parentexternalreferenceid)
	{
		getMendixObject().setValue(context, MemberNames.ParentExternalReferenceID.toString(), parentexternalreferenceid);
	}

	/**
	 * @return value of ParentInternalReferenceID
	 */
	public final java.lang.String getParentInternalReferenceID()
	{
		return getParentInternalReferenceID(getContext());
	}

	/**
	 * @param context
	 * @return value of ParentInternalReferenceID
	 */
	public final java.lang.String getParentInternalReferenceID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ParentInternalReferenceID.toString());
	}

	/**
	 * Set value of ParentInternalReferenceID
	 * @param parentinternalreferenceid
	 */
	public final void setParentInternalReferenceID(java.lang.String parentinternalreferenceid)
	{
		setParentInternalReferenceID(getContext(), parentinternalreferenceid);
	}

	/**
	 * Set value of ParentInternalReferenceID
	 * @param context
	 * @param parentinternalreferenceid
	 */
	public final void setParentInternalReferenceID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parentinternalreferenceid)
	{
		getMendixObject().setValue(context, MemberNames.ParentInternalReferenceID.toString(), parentinternalreferenceid);
	}

	/**
	 * Set value of Operation
	 * @param operation
	 */
	public final interfaceshared.proxies.AddUpdateDeleteOperation getOperation()
	{
		return getOperation(getContext());
	}

	/**
	 * @param context
	 * @return value of Operation
	 */
	public final interfaceshared.proxies.AddUpdateDeleteOperation getOperation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Operation.toString());
		if (obj == null)
			return null;

		return interfaceshared.proxies.AddUpdateDeleteOperation.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Operation
	 * @param operation
	 */
	public final void setOperation(interfaceshared.proxies.AddUpdateDeleteOperation operation)
	{
		setOperation(getContext(), operation);
	}

	/**
	 * Set value of Operation
	 * @param context
	 * @param operation
	 */
	public final void setOperation(com.mendix.systemwideinterfaces.core.IContext context, interfaceshared.proxies.AddUpdateDeleteOperation operation)
	{
		if (operation != null)
			getMendixObject().setValue(context, MemberNames.Operation.toString(), operation.toString());
		else
			getMendixObject().setValue(context, MemberNames.Operation.toString(), null);
	}

	/**
	 * Set value of RelationType
	 * @param relationtype
	 */
	public final process.proxies.RelationTypes getRelationType()
	{
		return getRelationType(getContext());
	}

	/**
	 * @param context
	 * @return value of RelationType
	 */
	public final process.proxies.RelationTypes getRelationType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.RelationType.toString());
		if (obj == null)
			return null;

		return process.proxies.RelationTypes.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of RelationType
	 * @param relationtype
	 */
	public final void setRelationType(process.proxies.RelationTypes relationtype)
	{
		setRelationType(getContext(), relationtype);
	}

	/**
	 * Set value of RelationType
	 * @param context
	 * @param relationtype
	 */
	public final void setRelationType(com.mendix.systemwideinterfaces.core.IContext context, process.proxies.RelationTypes relationtype)
	{
		if (relationtype != null)
			getMendixObject().setValue(context, MemberNames.RelationType.toString(), relationtype.toString());
		else
			getMendixObject().setValue(context, MemberNames.RelationType.toString(), null);
	}

	/**
	 * @return value of SolveChildOnSolve
	 */
	public final java.lang.Boolean getSolveChildOnSolve()
	{
		return getSolveChildOnSolve(getContext());
	}

	/**
	 * @param context
	 * @return value of SolveChildOnSolve
	 */
	public final java.lang.Boolean getSolveChildOnSolve(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SolveChildOnSolve.toString());
	}

	/**
	 * Set value of SolveChildOnSolve
	 * @param solvechildonsolve
	 */
	public final void setSolveChildOnSolve(java.lang.Boolean solvechildonsolve)
	{
		setSolveChildOnSolve(getContext(), solvechildonsolve);
	}

	/**
	 * Set value of SolveChildOnSolve
	 * @param context
	 * @param solvechildonsolve
	 */
	public final void setSolveChildOnSolve(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean solvechildonsolve)
	{
		getMendixObject().setValue(context, MemberNames.SolveChildOnSolve.toString(), solvechildonsolve);
	}

	/**
	 * @return value of SolveParentOnSolve
	 */
	public final java.lang.Boolean getSolveParentOnSolve()
	{
		return getSolveParentOnSolve(getContext());
	}

	/**
	 * @param context
	 * @return value of SolveParentOnSolve
	 */
	public final java.lang.Boolean getSolveParentOnSolve(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SolveParentOnSolve.toString());
	}

	/**
	 * Set value of SolveParentOnSolve
	 * @param solveparentonsolve
	 */
	public final void setSolveParentOnSolve(java.lang.Boolean solveparentonsolve)
	{
		setSolveParentOnSolve(getContext(), solveparentonsolve);
	}

	/**
	 * Set value of SolveParentOnSolve
	 * @param context
	 * @param solveparentonsolve
	 */
	public final void setSolveParentOnSolve(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean solveparentonsolve)
	{
		getMendixObject().setValue(context, MemberNames.SolveParentOnSolve.toString(), solveparentonsolve);
	}

	/**
	 * @return value of CloseChildOnClose
	 */
	public final java.lang.Boolean getCloseChildOnClose()
	{
		return getCloseChildOnClose(getContext());
	}

	/**
	 * @param context
	 * @return value of CloseChildOnClose
	 */
	public final java.lang.Boolean getCloseChildOnClose(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CloseChildOnClose.toString());
	}

	/**
	 * Set value of CloseChildOnClose
	 * @param closechildonclose
	 */
	public final void setCloseChildOnClose(java.lang.Boolean closechildonclose)
	{
		setCloseChildOnClose(getContext(), closechildonclose);
	}

	/**
	 * Set value of CloseChildOnClose
	 * @param context
	 * @param closechildonclose
	 */
	public final void setCloseChildOnClose(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean closechildonclose)
	{
		getMendixObject().setValue(context, MemberNames.CloseChildOnClose.toString(), closechildonclose);
	}

	/**
	 * @return value of CloseParentOnClose
	 */
	public final java.lang.Boolean getCloseParentOnClose()
	{
		return getCloseParentOnClose(getContext());
	}

	/**
	 * @param context
	 * @return value of CloseParentOnClose
	 */
	public final java.lang.Boolean getCloseParentOnClose(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CloseParentOnClose.toString());
	}

	/**
	 * Set value of CloseParentOnClose
	 * @param closeparentonclose
	 */
	public final void setCloseParentOnClose(java.lang.Boolean closeparentonclose)
	{
		setCloseParentOnClose(getContext(), closeparentonclose);
	}

	/**
	 * Set value of CloseParentOnClose
	 * @param context
	 * @param closeparentonclose
	 */
	public final void setCloseParentOnClose(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean closeparentonclose)
	{
		getMendixObject().setValue(context, MemberNames.CloseParentOnClose.toString(), closeparentonclose);
	}

	/**
	 * @return value of NotifyChildOnSolve
	 */
	public final java.lang.Boolean getNotifyChildOnSolve()
	{
		return getNotifyChildOnSolve(getContext());
	}

	/**
	 * @param context
	 * @return value of NotifyChildOnSolve
	 */
	public final java.lang.Boolean getNotifyChildOnSolve(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.NotifyChildOnSolve.toString());
	}

	/**
	 * Set value of NotifyChildOnSolve
	 * @param notifychildonsolve
	 */
	public final void setNotifyChildOnSolve(java.lang.Boolean notifychildonsolve)
	{
		setNotifyChildOnSolve(getContext(), notifychildonsolve);
	}

	/**
	 * Set value of NotifyChildOnSolve
	 * @param context
	 * @param notifychildonsolve
	 */
	public final void setNotifyChildOnSolve(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean notifychildonsolve)
	{
		getMendixObject().setValue(context, MemberNames.NotifyChildOnSolve.toString(), notifychildonsolve);
	}

	/**
	 * @return value of NotifyParentOnSolve
	 */
	public final java.lang.Boolean getNotifyParentOnSolve()
	{
		return getNotifyParentOnSolve(getContext());
	}

	/**
	 * @param context
	 * @return value of NotifyParentOnSolve
	 */
	public final java.lang.Boolean getNotifyParentOnSolve(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.NotifyParentOnSolve.toString());
	}

	/**
	 * Set value of NotifyParentOnSolve
	 * @param notifyparentonsolve
	 */
	public final void setNotifyParentOnSolve(java.lang.Boolean notifyparentonsolve)
	{
		setNotifyParentOnSolve(getContext(), notifyparentonsolve);
	}

	/**
	 * Set value of NotifyParentOnSolve
	 * @param context
	 * @param notifyparentonsolve
	 */
	public final void setNotifyParentOnSolve(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean notifyparentonsolve)
	{
		getMendixObject().setValue(context, MemberNames.NotifyParentOnSolve.toString(), notifyparentonsolve);
	}

	/**
	 * @return value of NotifyChildOnClose
	 */
	public final java.lang.Boolean getNotifyChildOnClose()
	{
		return getNotifyChildOnClose(getContext());
	}

	/**
	 * @param context
	 * @return value of NotifyChildOnClose
	 */
	public final java.lang.Boolean getNotifyChildOnClose(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.NotifyChildOnClose.toString());
	}

	/**
	 * Set value of NotifyChildOnClose
	 * @param notifychildonclose
	 */
	public final void setNotifyChildOnClose(java.lang.Boolean notifychildonclose)
	{
		setNotifyChildOnClose(getContext(), notifychildonclose);
	}

	/**
	 * Set value of NotifyChildOnClose
	 * @param context
	 * @param notifychildonclose
	 */
	public final void setNotifyChildOnClose(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean notifychildonclose)
	{
		getMendixObject().setValue(context, MemberNames.NotifyChildOnClose.toString(), notifychildonclose);
	}

	/**
	 * @return value of NotifyParentOnClose
	 */
	public final java.lang.Boolean getNotifyParentOnClose()
	{
		return getNotifyParentOnClose(getContext());
	}

	/**
	 * @param context
	 * @return value of NotifyParentOnClose
	 */
	public final java.lang.Boolean getNotifyParentOnClose(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.NotifyParentOnClose.toString());
	}

	/**
	 * Set value of NotifyParentOnClose
	 * @param notifyparentonclose
	 */
	public final void setNotifyParentOnClose(java.lang.Boolean notifyparentonclose)
	{
		setNotifyParentOnClose(getContext(), notifyparentonclose);
	}

	/**
	 * Set value of NotifyParentOnClose
	 * @param context
	 * @param notifyparentonclose
	 */
	public final void setNotifyParentOnClose(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean notifyparentonclose)
	{
		getMendixObject().setValue(context, MemberNames.NotifyParentOnClose.toString(), notifyparentonclose);
	}

	/**
	 * @return value of AutomaticActions
	 */
	public final java.lang.Boolean getAutomaticActions()
	{
		return getAutomaticActions(getContext());
	}

	/**
	 * @param context
	 * @return value of AutomaticActions
	 */
	public final java.lang.Boolean getAutomaticActions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AutomaticActions.toString());
	}

	/**
	 * Set value of AutomaticActions
	 * @param automaticactions
	 */
	public final void setAutomaticActions(java.lang.Boolean automaticactions)
	{
		setAutomaticActions(getContext(), automaticactions);
	}

	/**
	 * Set value of AutomaticActions
	 * @param context
	 * @param automaticactions
	 */
	public final void setAutomaticActions(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean automaticactions)
	{
		getMendixObject().setValue(context, MemberNames.AutomaticActions.toString(), automaticactions);
	}

	/**
	 * @return value of IsLinkedFromParent
	 */
	public final java.lang.Boolean getIsLinkedFromParent()
	{
		return getIsLinkedFromParent(getContext());
	}

	/**
	 * @param context
	 * @return value of IsLinkedFromParent
	 */
	public final java.lang.Boolean getIsLinkedFromParent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsLinkedFromParent.toString());
	}

	/**
	 * Set value of IsLinkedFromParent
	 * @param islinkedfromparent
	 */
	public final void setIsLinkedFromParent(java.lang.Boolean islinkedfromparent)
	{
		setIsLinkedFromParent(getContext(), islinkedfromparent);
	}

	/**
	 * Set value of IsLinkedFromParent
	 * @param context
	 * @param islinkedfromparent
	 */
	public final void setIsLinkedFromParent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean islinkedfromparent)
	{
		getMendixObject().setValue(context, MemberNames.IsLinkedFromParent.toString(), islinkedfromparent);
	}

	/**
	 * @return value of IsLinkedFromChild
	 */
	public final java.lang.Boolean getIsLinkedFromChild()
	{
		return getIsLinkedFromChild(getContext());
	}

	/**
	 * @param context
	 * @return value of IsLinkedFromChild
	 */
	public final java.lang.Boolean getIsLinkedFromChild(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsLinkedFromChild.toString());
	}

	/**
	 * Set value of IsLinkedFromChild
	 * @param islinkedfromchild
	 */
	public final void setIsLinkedFromChild(java.lang.Boolean islinkedfromchild)
	{
		setIsLinkedFromChild(getContext(), islinkedfromchild);
	}

	/**
	 * Set value of IsLinkedFromChild
	 * @param context
	 * @param islinkedfromchild
	 */
	public final void setIsLinkedFromChild(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean islinkedfromchild)
	{
		getMendixObject().setValue(context, MemberNames.IsLinkedFromChild.toString(), islinkedfromchild);
	}

	/**
	 * @return value of RelationResponse_Relation
	 */
	public final interfacerelations.proxies.RelationResponse getRelationResponse_Relation() throws com.mendix.core.CoreException
	{
		return getRelationResponse_Relation(getContext());
	}

	/**
	 * @param context
	 * @return value of RelationResponse_Relation
	 */
	public final interfacerelations.proxies.RelationResponse getRelationResponse_Relation(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacerelations.proxies.RelationResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RelationResponse_Relation.toString());
		if (identifier != null)
			result = interfacerelations.proxies.RelationResponse.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RelationResponse_Relation
	 * @param relationresponse_relation
	 */
	public final void setRelationResponse_Relation(interfacerelations.proxies.RelationResponse relationresponse_relation)
	{
		setRelationResponse_Relation(getContext(), relationresponse_relation);
	}

	/**
	 * Set value of RelationResponse_Relation
	 * @param context
	 * @param relationresponse_relation
	 */
	public final void setRelationResponse_Relation(com.mendix.systemwideinterfaces.core.IContext context, interfacerelations.proxies.RelationResponse relationresponse_relation)
	{
		if (relationresponse_relation == null)
			getMendixObject().setValue(context, MemberNames.RelationResponse_Relation.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RelationResponse_Relation.toString(), relationresponse_relation.getMendixObject().getId());
	}

	/**
	 * @return value of Relation_IncomingRelations
	 */
	public final interfacerelations.proxies.IncomingRelations getRelation_IncomingRelations() throws com.mendix.core.CoreException
	{
		return getRelation_IncomingRelations(getContext());
	}

	/**
	 * @param context
	 * @return value of Relation_IncomingRelations
	 */
	public final interfacerelations.proxies.IncomingRelations getRelation_IncomingRelations(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacerelations.proxies.IncomingRelations result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Relation_IncomingRelations.toString());
		if (identifier != null)
			result = interfacerelations.proxies.IncomingRelations.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Relation_IncomingRelations
	 * @param relation_incomingrelations
	 */
	public final void setRelation_IncomingRelations(interfacerelations.proxies.IncomingRelations relation_incomingrelations)
	{
		setRelation_IncomingRelations(getContext(), relation_incomingrelations);
	}

	/**
	 * Set value of Relation_IncomingRelations
	 * @param context
	 * @param relation_incomingrelations
	 */
	public final void setRelation_IncomingRelations(com.mendix.systemwideinterfaces.core.IContext context, interfacerelations.proxies.IncomingRelations relation_incomingrelations)
	{
		if (relation_incomingrelations == null)
			getMendixObject().setValue(context, MemberNames.Relation_IncomingRelations.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Relation_IncomingRelations.toString(), relation_incomingrelations.getMendixObject().getId());
	}

	/**
	 * @return value of RelationResponseGUID_RelationsContainerExpertDesk
	 */
	public final interfacerelations.proxies.RelationsContainerExpertDesk getRelationResponseGUID_RelationsContainerExpertDesk() throws com.mendix.core.CoreException
	{
		return getRelationResponseGUID_RelationsContainerExpertDesk(getContext());
	}

	/**
	 * @param context
	 * @return value of RelationResponseGUID_RelationsContainerExpertDesk
	 */
	public final interfacerelations.proxies.RelationsContainerExpertDesk getRelationResponseGUID_RelationsContainerExpertDesk(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacerelations.proxies.RelationsContainerExpertDesk result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RelationResponseGUID_RelationsContainerExpertDesk.toString());
		if (identifier != null)
			result = interfacerelations.proxies.RelationsContainerExpertDesk.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RelationResponseGUID_RelationsContainerExpertDesk
	 * @param relationresponseguid_relationscontainerexpertdesk
	 */
	public final void setRelationResponseGUID_RelationsContainerExpertDesk(interfacerelations.proxies.RelationsContainerExpertDesk relationresponseguid_relationscontainerexpertdesk)
	{
		setRelationResponseGUID_RelationsContainerExpertDesk(getContext(), relationresponseguid_relationscontainerexpertdesk);
	}

	/**
	 * Set value of RelationResponseGUID_RelationsContainerExpertDesk
	 * @param context
	 * @param relationresponseguid_relationscontainerexpertdesk
	 */
	public final void setRelationResponseGUID_RelationsContainerExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, interfacerelations.proxies.RelationsContainerExpertDesk relationresponseguid_relationscontainerexpertdesk)
	{
		if (relationresponseguid_relationscontainerexpertdesk == null)
			getMendixObject().setValue(context, MemberNames.RelationResponseGUID_RelationsContainerExpertDesk.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RelationResponseGUID_RelationsContainerExpertDesk.toString(), relationresponseguid_relationscontainerexpertdesk.getMendixObject().getId());
	}

	/**
	 * @return value of Relation_RelationsContainerExpertDesk
	 */
	public final interfacerelations.proxies.RelationsContainerExpertDesk getRelation_RelationsContainerExpertDesk() throws com.mendix.core.CoreException
	{
		return getRelation_RelationsContainerExpertDesk(getContext());
	}

	/**
	 * @param context
	 * @return value of Relation_RelationsContainerExpertDesk
	 */
	public final interfacerelations.proxies.RelationsContainerExpertDesk getRelation_RelationsContainerExpertDesk(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacerelations.proxies.RelationsContainerExpertDesk result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Relation_RelationsContainerExpertDesk.toString());
		if (identifier != null)
			result = interfacerelations.proxies.RelationsContainerExpertDesk.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Relation_RelationsContainerExpertDesk
	 * @param relation_relationscontainerexpertdesk
	 */
	public final void setRelation_RelationsContainerExpertDesk(interfacerelations.proxies.RelationsContainerExpertDesk relation_relationscontainerexpertdesk)
	{
		setRelation_RelationsContainerExpertDesk(getContext(), relation_relationscontainerexpertdesk);
	}

	/**
	 * Set value of Relation_RelationsContainerExpertDesk
	 * @param context
	 * @param relation_relationscontainerexpertdesk
	 */
	public final void setRelation_RelationsContainerExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, interfacerelations.proxies.RelationsContainerExpertDesk relation_relationscontainerexpertdesk)
	{
		if (relation_relationscontainerexpertdesk == null)
			getMendixObject().setValue(context, MemberNames.Relation_RelationsContainerExpertDesk.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Relation_RelationsContainerExpertDesk.toString(), relation_relationscontainerexpertdesk.getMendixObject().getId());
	}

	/**
	 * @return value of Relation_IncomingRequest
	 */
	public final interfacerequests.proxies.IncomingRequest getRelation_IncomingRequest() throws com.mendix.core.CoreException
	{
		return getRelation_IncomingRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of Relation_IncomingRequest
	 */
	public final interfacerequests.proxies.IncomingRequest getRelation_IncomingRequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacerequests.proxies.IncomingRequest result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Relation_IncomingRequest.toString());
		if (identifier != null)
			result = interfacerequests.proxies.IncomingRequest.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Relation_IncomingRequest
	 * @param relation_incomingrequest
	 */
	public final void setRelation_IncomingRequest(interfacerequests.proxies.IncomingRequest relation_incomingrequest)
	{
		setRelation_IncomingRequest(getContext(), relation_incomingrequest);
	}

	/**
	 * Set value of Relation_IncomingRequest
	 * @param context
	 * @param relation_incomingrequest
	 */
	public final void setRelation_IncomingRequest(com.mendix.systemwideinterfaces.core.IContext context, interfacerequests.proxies.IncomingRequest relation_incomingrequest)
	{
		if (relation_incomingrequest == null)
			getMendixObject().setValue(context, MemberNames.Relation_IncomingRequest.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Relation_IncomingRequest.toString(), relation_incomingrequest.getMendixObject().getId());
	}

	/**
	 * @return value of Relation_TicketRelations
	 */
	public final process.proxies.TicketRelations getRelation_TicketRelations() throws com.mendix.core.CoreException
	{
		return getRelation_TicketRelations(getContext());
	}

	/**
	 * @param context
	 * @return value of Relation_TicketRelations
	 */
	public final process.proxies.TicketRelations getRelation_TicketRelations(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		process.proxies.TicketRelations result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Relation_TicketRelations.toString());
		if (identifier != null)
			result = process.proxies.TicketRelations.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Relation_TicketRelations
	 * @param relation_ticketrelations
	 */
	public final void setRelation_TicketRelations(process.proxies.TicketRelations relation_ticketrelations)
	{
		setRelation_TicketRelations(getContext(), relation_ticketrelations);
	}

	/**
	 * Set value of Relation_TicketRelations
	 * @param context
	 * @param relation_ticketrelations
	 */
	public final void setRelation_TicketRelations(com.mendix.systemwideinterfaces.core.IContext context, process.proxies.TicketRelations relation_ticketrelations)
	{
		if (relation_ticketrelations == null)
			getMendixObject().setValue(context, MemberNames.Relation_TicketRelations.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Relation_TicketRelations.toString(), relation_ticketrelations.getMendixObject().getId());
	}

	/**
	 * @return value of Relation_ParentRequest
	 */
	public final process.proxies.Request getRelation_ParentRequest() throws com.mendix.core.CoreException
	{
		return getRelation_ParentRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of Relation_ParentRequest
	 */
	public final process.proxies.Request getRelation_ParentRequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		process.proxies.Request result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Relation_ParentRequest.toString());
		if (identifier != null)
			result = process.proxies.Request.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Relation_ParentRequest
	 * @param relation_parentrequest
	 */
	public final void setRelation_ParentRequest(process.proxies.Request relation_parentrequest)
	{
		setRelation_ParentRequest(getContext(), relation_parentrequest);
	}

	/**
	 * Set value of Relation_ParentRequest
	 * @param context
	 * @param relation_parentrequest
	 */
	public final void setRelation_ParentRequest(com.mendix.systemwideinterfaces.core.IContext context, process.proxies.Request relation_parentrequest)
	{
		if (relation_parentrequest == null)
			getMendixObject().setValue(context, MemberNames.Relation_ParentRequest.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Relation_ParentRequest.toString(), relation_parentrequest.getMendixObject().getId());
	}

	/**
	 * @return value of Relation_ChildRequest
	 */
	public final process.proxies.Request getRelation_ChildRequest() throws com.mendix.core.CoreException
	{
		return getRelation_ChildRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of Relation_ChildRequest
	 */
	public final process.proxies.Request getRelation_ChildRequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		process.proxies.Request result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Relation_ChildRequest.toString());
		if (identifier != null)
			result = process.proxies.Request.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Relation_ChildRequest
	 * @param relation_childrequest
	 */
	public final void setRelation_ChildRequest(process.proxies.Request relation_childrequest)
	{
		setRelation_ChildRequest(getContext(), relation_childrequest);
	}

	/**
	 * Set value of Relation_ChildRequest
	 * @param context
	 * @param relation_childrequest
	 */
	public final void setRelation_ChildRequest(com.mendix.systemwideinterfaces.core.IContext context, process.proxies.Request relation_childrequest)
	{
		if (relation_childrequest == null)
			getMendixObject().setValue(context, MemberNames.Relation_ChildRequest.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Relation_ChildRequest.toString(), relation_childrequest.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final interfacerelations.proxies.Relation that = (interfacerelations.proxies.Relation) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "InterfaceRelations.Relation";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
