// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nap.proxies;

public enum Contact_Types
{
	Telephone(new java.lang.String[][] { new java.lang.String[] { "en_US", "Telephone" }, new java.lang.String[] { "nl_NL", "Telefoon" }, new java.lang.String[] { "de_DE", "Telefon " } }),
	Email(new java.lang.String[][] { new java.lang.String[] { "en_US", "Email" }, new java.lang.String[] { "nl_NL", "E-mail" }, new java.lang.String[] { "de_DE", "E-Mail " } }),
	Fax(new java.lang.String[][] { new java.lang.String[] { "en_US", "Fax" }, new java.lang.String[] { "nl_NL", "Fax" }, new java.lang.String[] { "de_DE", "Fax" } }),
	Mobile(new java.lang.String[][] { new java.lang.String[] { "en_US", "Mobile" }, new java.lang.String[] { "nl_NL", "Mobiel" }, new java.lang.String[] { "de_DE", "Mobil" } }),
	Website(new java.lang.String[][] { new java.lang.String[] { "en_US", "Website" }, new java.lang.String[] { "nl_NL", "Website" }, new java.lang.String[] { "de_DE", "Webseite" } }),
	Twitter_Account(new java.lang.String[][] { new java.lang.String[] { "en_US", "Twitter Account" }, new java.lang.String[] { "nl_NL", "Twitter Account" }, new java.lang.String[] { "de_DE", "Twitter-Account" } }),
	Other(new java.lang.String[][] { new java.lang.String[] { "en_US", "Other" }, new java.lang.String[] { "nl_NL", "Overig" }, new java.lang.String[] { "de_DE", "Andere " } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Contact_Types(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
