// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nap.proxies;

/**
 * Field LDAPID has become decrepit in version 9.5, it has been replaced by the InterfaceGUID field.
 */
public class Location extends googlemaps.proxies.Location
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NAP.Location";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		LocationName("LocationName"),
		Country("Country"),
		Zipcode("Zipcode"),
		City("City"),
		Street("Street"),
		HouseNumber("HouseNumber"),
		HouseNumberExtension("HouseNumberExtension"),
		LocationStatus("LocationStatus"),
		XXLDAPID("XXLDAPID"),
		InterfaceGUID("InterfaceGUID"),
		Address("Address"),
		UU95_Latitude("UU95_Latitude"),
		UU95_Longitude("UU95_Longitude"),
		UU95_MarkerAttribute("UU95_MarkerAttribute"),
		Person_Location_ForCancel("NAP.Person_Location_ForCancel"),
		Location_DataAccess("NAP.Location_DataAccess"),
		Location_InitiatingInterfaceConfiguration("NAP.Location_InitiatingInterfaceConfiguration"),
		Location_InitiatingLDAPImportType("NAP.Location_InitiatingLDAPImportType"),
		Location_ParentInterfaceProcessingPart("NAP.Location_ParentInterfaceProcessingPart");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Location(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "NAP.Location"));
	}

	protected Location(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject locationMendixObject)
	{
		super(context, locationMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("NAP.Location", locationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a NAP.Location");
	}

	/**
	 * @deprecated Use 'Location.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static nap.proxies.Location initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return nap.proxies.Location.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static nap.proxies.Location initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nap.proxies.Location(context, mendixObject);
	}

	public static nap.proxies.Location load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nap.proxies.Location.initialize(context, mendixObject);
	}

	public static java.util.List<nap.proxies.Location> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<nap.proxies.Location> result = new java.util.ArrayList<nap.proxies.Location>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//NAP.Location" + xpathConstraint))
			result.add(nap.proxies.Location.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of LocationName
	 */
	public final java.lang.String getLocationName()
	{
		return getLocationName(getContext());
	}

	/**
	 * @param context
	 * @return value of LocationName
	 */
	public final java.lang.String getLocationName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LocationName.toString());
	}

	/**
	 * Set value of LocationName
	 * @param locationname
	 */
	public final void setLocationName(java.lang.String locationname)
	{
		setLocationName(getContext(), locationname);
	}

	/**
	 * Set value of LocationName
	 * @param context
	 * @param locationname
	 */
	public final void setLocationName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String locationname)
	{
		getMendixObject().setValue(context, MemberNames.LocationName.toString(), locationname);
	}

	/**
	 * Set value of Country
	 * @param country
	 */
	public final nap.proxies.Countries getCountry()
	{
		return getCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of Country
	 */
	public final nap.proxies.Countries getCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Country.toString());
		if (obj == null)
			return null;

		return nap.proxies.Countries.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Country
	 * @param country
	 */
	public final void setCountry(nap.proxies.Countries country)
	{
		setCountry(getContext(), country);
	}

	/**
	 * Set value of Country
	 * @param context
	 * @param country
	 */
	public final void setCountry(com.mendix.systemwideinterfaces.core.IContext context, nap.proxies.Countries country)
	{
		if (country != null)
			getMendixObject().setValue(context, MemberNames.Country.toString(), country.toString());
		else
			getMendixObject().setValue(context, MemberNames.Country.toString(), null);
	}

	/**
	 * @return value of Zipcode
	 */
	public final java.lang.String getZipcode()
	{
		return getZipcode(getContext());
	}

	/**
	 * @param context
	 * @return value of Zipcode
	 */
	public final java.lang.String getZipcode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Zipcode.toString());
	}

	/**
	 * Set value of Zipcode
	 * @param zipcode
	 */
	public final void setZipcode(java.lang.String zipcode)
	{
		setZipcode(getContext(), zipcode);
	}

	/**
	 * Set value of Zipcode
	 * @param context
	 * @param zipcode
	 */
	public final void setZipcode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String zipcode)
	{
		getMendixObject().setValue(context, MemberNames.Zipcode.toString(), zipcode);
	}

	/**
	 * @return value of City
	 */
	public final java.lang.String getCity()
	{
		return getCity(getContext());
	}

	/**
	 * @param context
	 * @return value of City
	 */
	public final java.lang.String getCity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.City.toString());
	}

	/**
	 * Set value of City
	 * @param city
	 */
	public final void setCity(java.lang.String city)
	{
		setCity(getContext(), city);
	}

	/**
	 * Set value of City
	 * @param context
	 * @param city
	 */
	public final void setCity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String city)
	{
		getMendixObject().setValue(context, MemberNames.City.toString(), city);
	}

	/**
	 * @return value of Street
	 */
	public final java.lang.String getStreet()
	{
		return getStreet(getContext());
	}

	/**
	 * @param context
	 * @return value of Street
	 */
	public final java.lang.String getStreet(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Street.toString());
	}

	/**
	 * Set value of Street
	 * @param street
	 */
	public final void setStreet(java.lang.String street)
	{
		setStreet(getContext(), street);
	}

	/**
	 * Set value of Street
	 * @param context
	 * @param street
	 */
	public final void setStreet(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String street)
	{
		getMendixObject().setValue(context, MemberNames.Street.toString(), street);
	}

	/**
	 * @return value of HouseNumber
	 */
	public final java.lang.Integer getHouseNumber()
	{
		return getHouseNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of HouseNumber
	 */
	public final java.lang.Integer getHouseNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.HouseNumber.toString());
	}

	/**
	 * Set value of HouseNumber
	 * @param housenumber
	 */
	public final void setHouseNumber(java.lang.Integer housenumber)
	{
		setHouseNumber(getContext(), housenumber);
	}

	/**
	 * Set value of HouseNumber
	 * @param context
	 * @param housenumber
	 */
	public final void setHouseNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer housenumber)
	{
		getMendixObject().setValue(context, MemberNames.HouseNumber.toString(), housenumber);
	}

	/**
	 * @return value of HouseNumberExtension
	 */
	public final java.lang.String getHouseNumberExtension()
	{
		return getHouseNumberExtension(getContext());
	}

	/**
	 * @param context
	 * @return value of HouseNumberExtension
	 */
	public final java.lang.String getHouseNumberExtension(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HouseNumberExtension.toString());
	}

	/**
	 * Set value of HouseNumberExtension
	 * @param housenumberextension
	 */
	public final void setHouseNumberExtension(java.lang.String housenumberextension)
	{
		setHouseNumberExtension(getContext(), housenumberextension);
	}

	/**
	 * Set value of HouseNumberExtension
	 * @param context
	 * @param housenumberextension
	 */
	public final void setHouseNumberExtension(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String housenumberextension)
	{
		getMendixObject().setValue(context, MemberNames.HouseNumberExtension.toString(), housenumberextension);
	}

	/**
	 * Set value of LocationStatus
	 * @param locationstatus
	 */
	public final nap.proxies.NAP_Status getLocationStatus()
	{
		return getLocationStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of LocationStatus
	 */
	public final nap.proxies.NAP_Status getLocationStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.LocationStatus.toString());
		if (obj == null)
			return null;

		return nap.proxies.NAP_Status.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of LocationStatus
	 * @param locationstatus
	 */
	public final void setLocationStatus(nap.proxies.NAP_Status locationstatus)
	{
		setLocationStatus(getContext(), locationstatus);
	}

	/**
	 * Set value of LocationStatus
	 * @param context
	 * @param locationstatus
	 */
	public final void setLocationStatus(com.mendix.systemwideinterfaces.core.IContext context, nap.proxies.NAP_Status locationstatus)
	{
		if (locationstatus != null)
			getMendixObject().setValue(context, MemberNames.LocationStatus.toString(), locationstatus.toString());
		else
			getMendixObject().setValue(context, MemberNames.LocationStatus.toString(), null);
	}

	/**
	 * @return value of XXLDAPID
	 */
	public final java.lang.String getXXLDAPID()
	{
		return getXXLDAPID(getContext());
	}

	/**
	 * @param context
	 * @return value of XXLDAPID
	 */
	public final java.lang.String getXXLDAPID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.XXLDAPID.toString());
	}

	/**
	 * Set value of XXLDAPID
	 * @param xxldapid
	 */
	public final void setXXLDAPID(java.lang.String xxldapid)
	{
		setXXLDAPID(getContext(), xxldapid);
	}

	/**
	 * Set value of XXLDAPID
	 * @param context
	 * @param xxldapid
	 */
	public final void setXXLDAPID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xxldapid)
	{
		getMendixObject().setValue(context, MemberNames.XXLDAPID.toString(), xxldapid);
	}

	/**
	 * @return value of InterfaceGUID
	 */
	public final java.lang.String getInterfaceGUID()
	{
		return getInterfaceGUID(getContext());
	}

	/**
	 * @param context
	 * @return value of InterfaceGUID
	 */
	public final java.lang.String getInterfaceGUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InterfaceGUID.toString());
	}

	/**
	 * Set value of InterfaceGUID
	 * @param interfaceguid
	 */
	public final void setInterfaceGUID(java.lang.String interfaceguid)
	{
		setInterfaceGUID(getContext(), interfaceguid);
	}

	/**
	 * Set value of InterfaceGUID
	 * @param context
	 * @param interfaceguid
	 */
	public final void setInterfaceGUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String interfaceguid)
	{
		getMendixObject().setValue(context, MemberNames.InterfaceGUID.toString(), interfaceguid);
	}

	/**
	 * @return value of Person_Location_ForCancel
	 */
	public final java.util.List<nap.proxies.Person> getPerson_Location_ForCancel() throws com.mendix.core.CoreException
	{
		return getPerson_Location_ForCancel(getContext());
	}

	/**
	 * @param context
	 * @return value of Person_Location_ForCancel
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<nap.proxies.Person> getPerson_Location_ForCancel(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<nap.proxies.Person> result = new java.util.ArrayList<nap.proxies.Person>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Person_Location_ForCancel.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(nap.proxies.Person.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Person_Location_ForCancel
	 * @param person_location_forcancel
	 */
	public final void setPerson_Location_ForCancel(java.util.List<nap.proxies.Person> person_location_forcancel)
	{
		setPerson_Location_ForCancel(getContext(), person_location_forcancel);
	}

	/**
	 * Set value of Person_Location_ForCancel
	 * @param context
	 * @param person_location_forcancel
	 */
	public final void setPerson_Location_ForCancel(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<nap.proxies.Person> person_location_forcancel)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (nap.proxies.Person proxyObject : person_location_forcancel)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Person_Location_ForCancel.toString(), identifiers);
	}

	/**
	 * @return value of Location_DataAccess
	 */
	public final java.util.List<da.proxies.Label> getLocation_DataAccess() throws com.mendix.core.CoreException
	{
		return getLocation_DataAccess(getContext());
	}

	/**
	 * @param context
	 * @return value of Location_DataAccess
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<da.proxies.Label> getLocation_DataAccess(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<da.proxies.Label> result = new java.util.ArrayList<da.proxies.Label>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Location_DataAccess.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(da.proxies.Label.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Location_DataAccess
	 * @param location_dataaccess
	 */
	public final void setLocation_DataAccess(java.util.List<da.proxies.Label> location_dataaccess)
	{
		setLocation_DataAccess(getContext(), location_dataaccess);
	}

	/**
	 * Set value of Location_DataAccess
	 * @param context
	 * @param location_dataaccess
	 */
	public final void setLocation_DataAccess(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<da.proxies.Label> location_dataaccess)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (da.proxies.Label proxyObject : location_dataaccess)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Location_DataAccess.toString(), identifiers);
	}

	/**
	 * @return value of Location_InitiatingInterfaceConfiguration
	 */
	public final interfaceconfiguration.proxies.InterfaceConfiguration getLocation_InitiatingInterfaceConfiguration() throws com.mendix.core.CoreException
	{
		return getLocation_InitiatingInterfaceConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of Location_InitiatingInterfaceConfiguration
	 */
	public final interfaceconfiguration.proxies.InterfaceConfiguration getLocation_InitiatingInterfaceConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceconfiguration.proxies.InterfaceConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Location_InitiatingInterfaceConfiguration.toString());
		if (identifier != null)
			result = interfaceconfiguration.proxies.InterfaceConfiguration.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Location_InitiatingInterfaceConfiguration
	 * @param location_initiatinginterfaceconfiguration
	 */
	public final void setLocation_InitiatingInterfaceConfiguration(interfaceconfiguration.proxies.InterfaceConfiguration location_initiatinginterfaceconfiguration)
	{
		setLocation_InitiatingInterfaceConfiguration(getContext(), location_initiatinginterfaceconfiguration);
	}

	/**
	 * Set value of Location_InitiatingInterfaceConfiguration
	 * @param context
	 * @param location_initiatinginterfaceconfiguration
	 */
	public final void setLocation_InitiatingInterfaceConfiguration(com.mendix.systemwideinterfaces.core.IContext context, interfaceconfiguration.proxies.InterfaceConfiguration location_initiatinginterfaceconfiguration)
	{
		if (location_initiatinginterfaceconfiguration == null)
			getMendixObject().setValue(context, MemberNames.Location_InitiatingInterfaceConfiguration.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Location_InitiatingInterfaceConfiguration.toString(), location_initiatinginterfaceconfiguration.getMendixObject().getId());
	}

	/**
	 * @return value of Location_InitiatingLDAPImportType
	 */
	public final interfaceconfiguration.proxies.LDAPImportType getLocation_InitiatingLDAPImportType() throws com.mendix.core.CoreException
	{
		return getLocation_InitiatingLDAPImportType(getContext());
	}

	/**
	 * @param context
	 * @return value of Location_InitiatingLDAPImportType
	 */
	public final interfaceconfiguration.proxies.LDAPImportType getLocation_InitiatingLDAPImportType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceconfiguration.proxies.LDAPImportType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Location_InitiatingLDAPImportType.toString());
		if (identifier != null)
			result = interfaceconfiguration.proxies.LDAPImportType.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Location_InitiatingLDAPImportType
	 * @param location_initiatingldapimporttype
	 */
	public final void setLocation_InitiatingLDAPImportType(interfaceconfiguration.proxies.LDAPImportType location_initiatingldapimporttype)
	{
		setLocation_InitiatingLDAPImportType(getContext(), location_initiatingldapimporttype);
	}

	/**
	 * Set value of Location_InitiatingLDAPImportType
	 * @param context
	 * @param location_initiatingldapimporttype
	 */
	public final void setLocation_InitiatingLDAPImportType(com.mendix.systemwideinterfaces.core.IContext context, interfaceconfiguration.proxies.LDAPImportType location_initiatingldapimporttype)
	{
		if (location_initiatingldapimporttype == null)
			getMendixObject().setValue(context, MemberNames.Location_InitiatingLDAPImportType.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Location_InitiatingLDAPImportType.toString(), location_initiatingldapimporttype.getMendixObject().getId());
	}

	/**
	 * @return value of Location_ParentInterfaceProcessingPart
	 */
	public final interfaceshared.proxies.ProcessingPart getLocation_ParentInterfaceProcessingPart() throws com.mendix.core.CoreException
	{
		return getLocation_ParentInterfaceProcessingPart(getContext());
	}

	/**
	 * @param context
	 * @return value of Location_ParentInterfaceProcessingPart
	 */
	public final interfaceshared.proxies.ProcessingPart getLocation_ParentInterfaceProcessingPart(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceshared.proxies.ProcessingPart result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Location_ParentInterfaceProcessingPart.toString());
		if (identifier != null)
			result = interfaceshared.proxies.ProcessingPart.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Location_ParentInterfaceProcessingPart
	 * @param location_parentinterfaceprocessingpart
	 */
	public final void setLocation_ParentInterfaceProcessingPart(interfaceshared.proxies.ProcessingPart location_parentinterfaceprocessingpart)
	{
		setLocation_ParentInterfaceProcessingPart(getContext(), location_parentinterfaceprocessingpart);
	}

	/**
	 * Set value of Location_ParentInterfaceProcessingPart
	 * @param context
	 * @param location_parentinterfaceprocessingpart
	 */
	public final void setLocation_ParentInterfaceProcessingPart(com.mendix.systemwideinterfaces.core.IContext context, interfaceshared.proxies.ProcessingPart location_parentinterfaceprocessingpart)
	{
		if (location_parentinterfaceprocessingpart == null)
			getMendixObject().setValue(context, MemberNames.Location_ParentInterfaceProcessingPart.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Location_ParentInterfaceProcessingPart.toString(), location_parentinterfaceprocessingpart.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nap.proxies.Location that = (nap.proxies.Location) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "NAP.Location";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
