// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sdemigration.proxies;

public class AttachmentICT extends sdemigration.proxies.SDEObject
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SDEMigration.AttachmentICT";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Sequence("Sequence"),
		Filename("Filename"),
		FileBlob("FileBlob"),
		FileBlobFormatted("FileBlobFormatted"),
		Filesize("Filesize"),
		Seq_Change("Seq_Change"),
		Seq_Incident("Seq_Incident"),
		Seq_ConfigurationItem("Seq_ConfigurationItem"),
		WONumber("WONumber"),
		Inactive("Inactive"),
		processed("processed"),
		SDEObject_MigrationItemRun("SDEMigration.SDEObject_MigrationItemRun"),
		IncomingRequest_SDEObject("InterfaceRequests.IncomingRequest_SDEObject");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AttachmentICT(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SDEMigration.AttachmentICT"));
	}

	protected AttachmentICT(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject attachmentICTMendixObject)
	{
		super(context, attachmentICTMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("SDEMigration.AttachmentICT", attachmentICTMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SDEMigration.AttachmentICT");
	}

	/**
	 * @deprecated Use 'AttachmentICT.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static sdemigration.proxies.AttachmentICT initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sdemigration.proxies.AttachmentICT.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static sdemigration.proxies.AttachmentICT initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sdemigration.proxies.AttachmentICT(context, mendixObject);
	}

	public static sdemigration.proxies.AttachmentICT load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sdemigration.proxies.AttachmentICT.initialize(context, mendixObject);
	}

	public static java.util.List<sdemigration.proxies.AttachmentICT> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<sdemigration.proxies.AttachmentICT> result = new java.util.ArrayList<sdemigration.proxies.AttachmentICT>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//SDEMigration.AttachmentICT" + xpathConstraint))
			result.add(sdemigration.proxies.AttachmentICT.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Sequence
	 */
	public final java.lang.String getSequence()
	{
		return getSequence(getContext());
	}

	/**
	 * @param context
	 * @return value of Sequence
	 */
	public final java.lang.String getSequence(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sequence.toString());
	}

	/**
	 * Set value of Sequence
	 * @param sequence
	 */
	public final void setSequence(java.lang.String sequence)
	{
		setSequence(getContext(), sequence);
	}

	/**
	 * Set value of Sequence
	 * @param context
	 * @param sequence
	 */
	public final void setSequence(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sequence)
	{
		getMendixObject().setValue(context, MemberNames.Sequence.toString(), sequence);
	}

	/**
	 * @return value of Filename
	 */
	public final java.lang.String getFilename()
	{
		return getFilename(getContext());
	}

	/**
	 * @param context
	 * @return value of Filename
	 */
	public final java.lang.String getFilename(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Filename.toString());
	}

	/**
	 * Set value of Filename
	 * @param filename
	 */
	public final void setFilename(java.lang.String filename)
	{
		setFilename(getContext(), filename);
	}

	/**
	 * Set value of Filename
	 * @param context
	 * @param filename
	 */
	public final void setFilename(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String filename)
	{
		getMendixObject().setValue(context, MemberNames.Filename.toString(), filename);
	}

	/**
	 * @return value of FileBlob
	 */
	public final java.lang.String getFileBlob()
	{
		return getFileBlob(getContext());
	}

	/**
	 * @param context
	 * @return value of FileBlob
	 */
	public final java.lang.String getFileBlob(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FileBlob.toString());
	}

	/**
	 * Set value of FileBlob
	 * @param fileblob
	 */
	public final void setFileBlob(java.lang.String fileblob)
	{
		setFileBlob(getContext(), fileblob);
	}

	/**
	 * Set value of FileBlob
	 * @param context
	 * @param fileblob
	 */
	public final void setFileBlob(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fileblob)
	{
		getMendixObject().setValue(context, MemberNames.FileBlob.toString(), fileblob);
	}

	/**
	 * @return value of FileBlobFormatted
	 */
	public final java.lang.String getFileBlobFormatted()
	{
		return getFileBlobFormatted(getContext());
	}

	/**
	 * @param context
	 * @return value of FileBlobFormatted
	 */
	public final java.lang.String getFileBlobFormatted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FileBlobFormatted.toString());
	}

	/**
	 * Set value of FileBlobFormatted
	 * @param fileblobformatted
	 */
	public final void setFileBlobFormatted(java.lang.String fileblobformatted)
	{
		setFileBlobFormatted(getContext(), fileblobformatted);
	}

	/**
	 * Set value of FileBlobFormatted
	 * @param context
	 * @param fileblobformatted
	 */
	public final void setFileBlobFormatted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fileblobformatted)
	{
		getMendixObject().setValue(context, MemberNames.FileBlobFormatted.toString(), fileblobformatted);
	}

	/**
	 * @return value of Filesize
	 */
	public final java.lang.String getFilesize()
	{
		return getFilesize(getContext());
	}

	/**
	 * @param context
	 * @return value of Filesize
	 */
	public final java.lang.String getFilesize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Filesize.toString());
	}

	/**
	 * Set value of Filesize
	 * @param filesize
	 */
	public final void setFilesize(java.lang.String filesize)
	{
		setFilesize(getContext(), filesize);
	}

	/**
	 * Set value of Filesize
	 * @param context
	 * @param filesize
	 */
	public final void setFilesize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String filesize)
	{
		getMendixObject().setValue(context, MemberNames.Filesize.toString(), filesize);
	}

	/**
	 * @return value of Seq_Change
	 */
	public final java.lang.String getSeq_Change()
	{
		return getSeq_Change(getContext());
	}

	/**
	 * @param context
	 * @return value of Seq_Change
	 */
	public final java.lang.String getSeq_Change(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Seq_Change.toString());
	}

	/**
	 * Set value of Seq_Change
	 * @param seq_change
	 */
	public final void setSeq_Change(java.lang.String seq_change)
	{
		setSeq_Change(getContext(), seq_change);
	}

	/**
	 * Set value of Seq_Change
	 * @param context
	 * @param seq_change
	 */
	public final void setSeq_Change(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String seq_change)
	{
		getMendixObject().setValue(context, MemberNames.Seq_Change.toString(), seq_change);
	}

	/**
	 * @return value of Seq_Incident
	 */
	public final java.lang.String getSeq_Incident()
	{
		return getSeq_Incident(getContext());
	}

	/**
	 * @param context
	 * @return value of Seq_Incident
	 */
	public final java.lang.String getSeq_Incident(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Seq_Incident.toString());
	}

	/**
	 * Set value of Seq_Incident
	 * @param seq_incident
	 */
	public final void setSeq_Incident(java.lang.String seq_incident)
	{
		setSeq_Incident(getContext(), seq_incident);
	}

	/**
	 * Set value of Seq_Incident
	 * @param context
	 * @param seq_incident
	 */
	public final void setSeq_Incident(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String seq_incident)
	{
		getMendixObject().setValue(context, MemberNames.Seq_Incident.toString(), seq_incident);
	}

	/**
	 * @return value of Seq_ConfigurationItem
	 */
	public final java.lang.String getSeq_ConfigurationItem()
	{
		return getSeq_ConfigurationItem(getContext());
	}

	/**
	 * @param context
	 * @return value of Seq_ConfigurationItem
	 */
	public final java.lang.String getSeq_ConfigurationItem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Seq_ConfigurationItem.toString());
	}

	/**
	 * Set value of Seq_ConfigurationItem
	 * @param seq_configurationitem
	 */
	public final void setSeq_ConfigurationItem(java.lang.String seq_configurationitem)
	{
		setSeq_ConfigurationItem(getContext(), seq_configurationitem);
	}

	/**
	 * Set value of Seq_ConfigurationItem
	 * @param context
	 * @param seq_configurationitem
	 */
	public final void setSeq_ConfigurationItem(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String seq_configurationitem)
	{
		getMendixObject().setValue(context, MemberNames.Seq_ConfigurationItem.toString(), seq_configurationitem);
	}

	/**
	 * @return value of WONumber
	 */
	public final java.lang.String getWONumber()
	{
		return getWONumber(getContext());
	}

	/**
	 * @param context
	 * @return value of WONumber
	 */
	public final java.lang.String getWONumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WONumber.toString());
	}

	/**
	 * Set value of WONumber
	 * @param wonumber
	 */
	public final void setWONumber(java.lang.String wonumber)
	{
		setWONumber(getContext(), wonumber);
	}

	/**
	 * Set value of WONumber
	 * @param context
	 * @param wonumber
	 */
	public final void setWONumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String wonumber)
	{
		getMendixObject().setValue(context, MemberNames.WONumber.toString(), wonumber);
	}

	/**
	 * @return value of Inactive
	 */
	public final java.lang.Boolean getInactive()
	{
		return getInactive(getContext());
	}

	/**
	 * @param context
	 * @return value of Inactive
	 */
	public final java.lang.Boolean getInactive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Inactive.toString());
	}

	/**
	 * Set value of Inactive
	 * @param inactive
	 */
	public final void setInactive(java.lang.Boolean inactive)
	{
		setInactive(getContext(), inactive);
	}

	/**
	 * Set value of Inactive
	 * @param context
	 * @param inactive
	 */
	public final void setInactive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean inactive)
	{
		getMendixObject().setValue(context, MemberNames.Inactive.toString(), inactive);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sdemigration.proxies.AttachmentICT that = (sdemigration.proxies.AttachmentICT) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SDEMigration.AttachmentICT";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
