// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sdemigration.proxies;

public class CIType extends sdemigration.proxies.SDEObject
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SDEMigration.CIType";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Sequence("Sequence"),
		CIType("CIType"),
		Description("Description"),
		AlternateCIType("AlternateCIType"),
		Manufacturer("Manufacturer"),
		ParentCICategoryID("ParentCICategoryID"),
		CICategoryID("CICategoryID"),
		Version("Version"),
		SupposedSystem("SupposedSystem"),
		TrackAsset("TrackAsset"),
		Approved("Approved"),
		Taxable("Taxable"),
		TrackSerial("TrackSerial"),
		TrackVersion("TrackVersion"),
		CanhaveComponents("CanhaveComponents"),
		MinimumOnStock("MinimumOnStock"),
		TargetValue("TargetValue"),
		MTBF("MTBF"),
		SalesVendorID("SalesVendorID"),
		SalesVendorDescription("SalesVendorDescription"),
		ServiceVendorID("ServiceVendorID"),
		Note("Note"),
		ObsolescenceDate("ObsolescenceDate"),
		EndOfServiceDate("EndOfServiceDate"),
		EndOfServiceNote("EndOfServiceNote"),
		Picture("Picture"),
		Inactive("Inactive"),
		processed("processed"),
		SDEObject_MigrationItemRun("SDEMigration.SDEObject_MigrationItemRun"),
		IncomingRequest_SDEObject("InterfaceRequests.IncomingRequest_SDEObject");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CIType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SDEMigration.CIType"));
	}

	protected CIType(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cITypeMendixObject)
	{
		super(context, cITypeMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("SDEMigration.CIType", cITypeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SDEMigration.CIType");
	}

	/**
	 * @deprecated Use 'CIType.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static sdemigration.proxies.CIType initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sdemigration.proxies.CIType.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static sdemigration.proxies.CIType initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sdemigration.proxies.CIType(context, mendixObject);
	}

	public static sdemigration.proxies.CIType load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sdemigration.proxies.CIType.initialize(context, mendixObject);
	}

	public static java.util.List<sdemigration.proxies.CIType> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<sdemigration.proxies.CIType> result = new java.util.ArrayList<sdemigration.proxies.CIType>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//SDEMigration.CIType" + xpathConstraint))
			result.add(sdemigration.proxies.CIType.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Sequence
	 */
	public final java.lang.String getSequence()
	{
		return getSequence(getContext());
	}

	/**
	 * @param context
	 * @return value of Sequence
	 */
	public final java.lang.String getSequence(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sequence.toString());
	}

	/**
	 * Set value of Sequence
	 * @param sequence
	 */
	public final void setSequence(java.lang.String sequence)
	{
		setSequence(getContext(), sequence);
	}

	/**
	 * Set value of Sequence
	 * @param context
	 * @param sequence
	 */
	public final void setSequence(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sequence)
	{
		getMendixObject().setValue(context, MemberNames.Sequence.toString(), sequence);
	}

	/**
	 * @return value of CIType
	 */
	public final java.lang.String getCIType()
	{
		return getCIType(getContext());
	}

	/**
	 * @param context
	 * @return value of CIType
	 */
	public final java.lang.String getCIType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CIType.toString());
	}

	/**
	 * Set value of CIType
	 * @param citype
	 */
	public final void setCIType(java.lang.String citype)
	{
		setCIType(getContext(), citype);
	}

	/**
	 * Set value of CIType
	 * @param context
	 * @param citype
	 */
	public final void setCIType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String citype)
	{
		getMendixObject().setValue(context, MemberNames.CIType.toString(), citype);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of AlternateCIType
	 */
	public final java.lang.String getAlternateCIType()
	{
		return getAlternateCIType(getContext());
	}

	/**
	 * @param context
	 * @return value of AlternateCIType
	 */
	public final java.lang.String getAlternateCIType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AlternateCIType.toString());
	}

	/**
	 * Set value of AlternateCIType
	 * @param alternatecitype
	 */
	public final void setAlternateCIType(java.lang.String alternatecitype)
	{
		setAlternateCIType(getContext(), alternatecitype);
	}

	/**
	 * Set value of AlternateCIType
	 * @param context
	 * @param alternatecitype
	 */
	public final void setAlternateCIType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String alternatecitype)
	{
		getMendixObject().setValue(context, MemberNames.AlternateCIType.toString(), alternatecitype);
	}

	/**
	 * @return value of Manufacturer
	 */
	public final java.lang.String getManufacturer()
	{
		return getManufacturer(getContext());
	}

	/**
	 * @param context
	 * @return value of Manufacturer
	 */
	public final java.lang.String getManufacturer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Manufacturer.toString());
	}

	/**
	 * Set value of Manufacturer
	 * @param manufacturer
	 */
	public final void setManufacturer(java.lang.String manufacturer)
	{
		setManufacturer(getContext(), manufacturer);
	}

	/**
	 * Set value of Manufacturer
	 * @param context
	 * @param manufacturer
	 */
	public final void setManufacturer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String manufacturer)
	{
		getMendixObject().setValue(context, MemberNames.Manufacturer.toString(), manufacturer);
	}

	/**
	 * @return value of ParentCICategoryID
	 */
	public final java.lang.String getParentCICategoryID()
	{
		return getParentCICategoryID(getContext());
	}

	/**
	 * @param context
	 * @return value of ParentCICategoryID
	 */
	public final java.lang.String getParentCICategoryID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ParentCICategoryID.toString());
	}

	/**
	 * Set value of ParentCICategoryID
	 * @param parentcicategoryid
	 */
	public final void setParentCICategoryID(java.lang.String parentcicategoryid)
	{
		setParentCICategoryID(getContext(), parentcicategoryid);
	}

	/**
	 * Set value of ParentCICategoryID
	 * @param context
	 * @param parentcicategoryid
	 */
	public final void setParentCICategoryID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parentcicategoryid)
	{
		getMendixObject().setValue(context, MemberNames.ParentCICategoryID.toString(), parentcicategoryid);
	}

	/**
	 * @return value of CICategoryID
	 */
	public final java.lang.String getCICategoryID()
	{
		return getCICategoryID(getContext());
	}

	/**
	 * @param context
	 * @return value of CICategoryID
	 */
	public final java.lang.String getCICategoryID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CICategoryID.toString());
	}

	/**
	 * Set value of CICategoryID
	 * @param cicategoryid
	 */
	public final void setCICategoryID(java.lang.String cicategoryid)
	{
		setCICategoryID(getContext(), cicategoryid);
	}

	/**
	 * Set value of CICategoryID
	 * @param context
	 * @param cicategoryid
	 */
	public final void setCICategoryID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cicategoryid)
	{
		getMendixObject().setValue(context, MemberNames.CICategoryID.toString(), cicategoryid);
	}

	/**
	 * @return value of Version
	 */
	public final java.lang.String getVersion()
	{
		return getVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of Version
	 */
	public final java.lang.String getVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Version.toString());
	}

	/**
	 * Set value of Version
	 * @param version
	 */
	public final void setVersion(java.lang.String version)
	{
		setVersion(getContext(), version);
	}

	/**
	 * Set value of Version
	 * @param context
	 * @param version
	 */
	public final void setVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String version)
	{
		getMendixObject().setValue(context, MemberNames.Version.toString(), version);
	}

	/**
	 * @return value of SupposedSystem
	 */
	public final java.lang.String getSupposedSystem()
	{
		return getSupposedSystem(getContext());
	}

	/**
	 * @param context
	 * @return value of SupposedSystem
	 */
	public final java.lang.String getSupposedSystem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SupposedSystem.toString());
	}

	/**
	 * Set value of SupposedSystem
	 * @param supposedsystem
	 */
	public final void setSupposedSystem(java.lang.String supposedsystem)
	{
		setSupposedSystem(getContext(), supposedsystem);
	}

	/**
	 * Set value of SupposedSystem
	 * @param context
	 * @param supposedsystem
	 */
	public final void setSupposedSystem(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String supposedsystem)
	{
		getMendixObject().setValue(context, MemberNames.SupposedSystem.toString(), supposedsystem);
	}

	/**
	 * @return value of TrackAsset
	 */
	public final java.lang.String getTrackAsset()
	{
		return getTrackAsset(getContext());
	}

	/**
	 * @param context
	 * @return value of TrackAsset
	 */
	public final java.lang.String getTrackAsset(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TrackAsset.toString());
	}

	/**
	 * Set value of TrackAsset
	 * @param trackasset
	 */
	public final void setTrackAsset(java.lang.String trackasset)
	{
		setTrackAsset(getContext(), trackasset);
	}

	/**
	 * Set value of TrackAsset
	 * @param context
	 * @param trackasset
	 */
	public final void setTrackAsset(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String trackasset)
	{
		getMendixObject().setValue(context, MemberNames.TrackAsset.toString(), trackasset);
	}

	/**
	 * @return value of Approved
	 */
	public final java.lang.String getApproved()
	{
		return getApproved(getContext());
	}

	/**
	 * @param context
	 * @return value of Approved
	 */
	public final java.lang.String getApproved(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Approved.toString());
	}

	/**
	 * Set value of Approved
	 * @param approved
	 */
	public final void setApproved(java.lang.String approved)
	{
		setApproved(getContext(), approved);
	}

	/**
	 * Set value of Approved
	 * @param context
	 * @param approved
	 */
	public final void setApproved(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String approved)
	{
		getMendixObject().setValue(context, MemberNames.Approved.toString(), approved);
	}

	/**
	 * @return value of Taxable
	 */
	public final java.lang.String getTaxable()
	{
		return getTaxable(getContext());
	}

	/**
	 * @param context
	 * @return value of Taxable
	 */
	public final java.lang.String getTaxable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Taxable.toString());
	}

	/**
	 * Set value of Taxable
	 * @param taxable
	 */
	public final void setTaxable(java.lang.String taxable)
	{
		setTaxable(getContext(), taxable);
	}

	/**
	 * Set value of Taxable
	 * @param context
	 * @param taxable
	 */
	public final void setTaxable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String taxable)
	{
		getMendixObject().setValue(context, MemberNames.Taxable.toString(), taxable);
	}

	/**
	 * @return value of TrackSerial
	 */
	public final java.lang.String getTrackSerial()
	{
		return getTrackSerial(getContext());
	}

	/**
	 * @param context
	 * @return value of TrackSerial
	 */
	public final java.lang.String getTrackSerial(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TrackSerial.toString());
	}

	/**
	 * Set value of TrackSerial
	 * @param trackserial
	 */
	public final void setTrackSerial(java.lang.String trackserial)
	{
		setTrackSerial(getContext(), trackserial);
	}

	/**
	 * Set value of TrackSerial
	 * @param context
	 * @param trackserial
	 */
	public final void setTrackSerial(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String trackserial)
	{
		getMendixObject().setValue(context, MemberNames.TrackSerial.toString(), trackserial);
	}

	/**
	 * @return value of TrackVersion
	 */
	public final java.lang.String getTrackVersion()
	{
		return getTrackVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of TrackVersion
	 */
	public final java.lang.String getTrackVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TrackVersion.toString());
	}

	/**
	 * Set value of TrackVersion
	 * @param trackversion
	 */
	public final void setTrackVersion(java.lang.String trackversion)
	{
		setTrackVersion(getContext(), trackversion);
	}

	/**
	 * Set value of TrackVersion
	 * @param context
	 * @param trackversion
	 */
	public final void setTrackVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String trackversion)
	{
		getMendixObject().setValue(context, MemberNames.TrackVersion.toString(), trackversion);
	}

	/**
	 * @return value of CanhaveComponents
	 */
	public final java.lang.String getCanhaveComponents()
	{
		return getCanhaveComponents(getContext());
	}

	/**
	 * @param context
	 * @return value of CanhaveComponents
	 */
	public final java.lang.String getCanhaveComponents(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CanhaveComponents.toString());
	}

	/**
	 * Set value of CanhaveComponents
	 * @param canhavecomponents
	 */
	public final void setCanhaveComponents(java.lang.String canhavecomponents)
	{
		setCanhaveComponents(getContext(), canhavecomponents);
	}

	/**
	 * Set value of CanhaveComponents
	 * @param context
	 * @param canhavecomponents
	 */
	public final void setCanhaveComponents(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String canhavecomponents)
	{
		getMendixObject().setValue(context, MemberNames.CanhaveComponents.toString(), canhavecomponents);
	}

	/**
	 * @return value of MinimumOnStock
	 */
	public final java.lang.String getMinimumOnStock()
	{
		return getMinimumOnStock(getContext());
	}

	/**
	 * @param context
	 * @return value of MinimumOnStock
	 */
	public final java.lang.String getMinimumOnStock(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MinimumOnStock.toString());
	}

	/**
	 * Set value of MinimumOnStock
	 * @param minimumonstock
	 */
	public final void setMinimumOnStock(java.lang.String minimumonstock)
	{
		setMinimumOnStock(getContext(), minimumonstock);
	}

	/**
	 * Set value of MinimumOnStock
	 * @param context
	 * @param minimumonstock
	 */
	public final void setMinimumOnStock(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String minimumonstock)
	{
		getMendixObject().setValue(context, MemberNames.MinimumOnStock.toString(), minimumonstock);
	}

	/**
	 * @return value of TargetValue
	 */
	public final java.lang.String getTargetValue()
	{
		return getTargetValue(getContext());
	}

	/**
	 * @param context
	 * @return value of TargetValue
	 */
	public final java.lang.String getTargetValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TargetValue.toString());
	}

	/**
	 * Set value of TargetValue
	 * @param targetvalue
	 */
	public final void setTargetValue(java.lang.String targetvalue)
	{
		setTargetValue(getContext(), targetvalue);
	}

	/**
	 * Set value of TargetValue
	 * @param context
	 * @param targetvalue
	 */
	public final void setTargetValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String targetvalue)
	{
		getMendixObject().setValue(context, MemberNames.TargetValue.toString(), targetvalue);
	}

	/**
	 * @return value of MTBF
	 */
	public final java.lang.String getMTBF()
	{
		return getMTBF(getContext());
	}

	/**
	 * @param context
	 * @return value of MTBF
	 */
	public final java.lang.String getMTBF(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MTBF.toString());
	}

	/**
	 * Set value of MTBF
	 * @param mtbf
	 */
	public final void setMTBF(java.lang.String mtbf)
	{
		setMTBF(getContext(), mtbf);
	}

	/**
	 * Set value of MTBF
	 * @param context
	 * @param mtbf
	 */
	public final void setMTBF(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mtbf)
	{
		getMendixObject().setValue(context, MemberNames.MTBF.toString(), mtbf);
	}

	/**
	 * @return value of SalesVendorID
	 */
	public final java.lang.String getSalesVendorID()
	{
		return getSalesVendorID(getContext());
	}

	/**
	 * @param context
	 * @return value of SalesVendorID
	 */
	public final java.lang.String getSalesVendorID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SalesVendorID.toString());
	}

	/**
	 * Set value of SalesVendorID
	 * @param salesvendorid
	 */
	public final void setSalesVendorID(java.lang.String salesvendorid)
	{
		setSalesVendorID(getContext(), salesvendorid);
	}

	/**
	 * Set value of SalesVendorID
	 * @param context
	 * @param salesvendorid
	 */
	public final void setSalesVendorID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String salesvendorid)
	{
		getMendixObject().setValue(context, MemberNames.SalesVendorID.toString(), salesvendorid);
	}

	/**
	 * @return value of SalesVendorDescription
	 */
	public final java.lang.String getSalesVendorDescription()
	{
		return getSalesVendorDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of SalesVendorDescription
	 */
	public final java.lang.String getSalesVendorDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SalesVendorDescription.toString());
	}

	/**
	 * Set value of SalesVendorDescription
	 * @param salesvendordescription
	 */
	public final void setSalesVendorDescription(java.lang.String salesvendordescription)
	{
		setSalesVendorDescription(getContext(), salesvendordescription);
	}

	/**
	 * Set value of SalesVendorDescription
	 * @param context
	 * @param salesvendordescription
	 */
	public final void setSalesVendorDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String salesvendordescription)
	{
		getMendixObject().setValue(context, MemberNames.SalesVendorDescription.toString(), salesvendordescription);
	}

	/**
	 * @return value of ServiceVendorID
	 */
	public final java.lang.String getServiceVendorID()
	{
		return getServiceVendorID(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceVendorID
	 */
	public final java.lang.String getServiceVendorID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ServiceVendorID.toString());
	}

	/**
	 * Set value of ServiceVendorID
	 * @param servicevendorid
	 */
	public final void setServiceVendorID(java.lang.String servicevendorid)
	{
		setServiceVendorID(getContext(), servicevendorid);
	}

	/**
	 * Set value of ServiceVendorID
	 * @param context
	 * @param servicevendorid
	 */
	public final void setServiceVendorID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String servicevendorid)
	{
		getMendixObject().setValue(context, MemberNames.ServiceVendorID.toString(), servicevendorid);
	}

	/**
	 * @return value of Note
	 */
	public final java.lang.String getNote()
	{
		return getNote(getContext());
	}

	/**
	 * @param context
	 * @return value of Note
	 */
	public final java.lang.String getNote(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Note.toString());
	}

	/**
	 * Set value of Note
	 * @param note
	 */
	public final void setNote(java.lang.String note)
	{
		setNote(getContext(), note);
	}

	/**
	 * Set value of Note
	 * @param context
	 * @param note
	 */
	public final void setNote(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String note)
	{
		getMendixObject().setValue(context, MemberNames.Note.toString(), note);
	}

	/**
	 * @return value of ObsolescenceDate
	 */
	public final java.util.Date getObsolescenceDate()
	{
		return getObsolescenceDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ObsolescenceDate
	 */
	public final java.util.Date getObsolescenceDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ObsolescenceDate.toString());
	}

	/**
	 * Set value of ObsolescenceDate
	 * @param obsolescencedate
	 */
	public final void setObsolescenceDate(java.util.Date obsolescencedate)
	{
		setObsolescenceDate(getContext(), obsolescencedate);
	}

	/**
	 * Set value of ObsolescenceDate
	 * @param context
	 * @param obsolescencedate
	 */
	public final void setObsolescenceDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date obsolescencedate)
	{
		getMendixObject().setValue(context, MemberNames.ObsolescenceDate.toString(), obsolescencedate);
	}

	/**
	 * @return value of EndOfServiceDate
	 */
	public final java.util.Date getEndOfServiceDate()
	{
		return getEndOfServiceDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EndOfServiceDate
	 */
	public final java.util.Date getEndOfServiceDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndOfServiceDate.toString());
	}

	/**
	 * Set value of EndOfServiceDate
	 * @param endofservicedate
	 */
	public final void setEndOfServiceDate(java.util.Date endofservicedate)
	{
		setEndOfServiceDate(getContext(), endofservicedate);
	}

	/**
	 * Set value of EndOfServiceDate
	 * @param context
	 * @param endofservicedate
	 */
	public final void setEndOfServiceDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date endofservicedate)
	{
		getMendixObject().setValue(context, MemberNames.EndOfServiceDate.toString(), endofservicedate);
	}

	/**
	 * @return value of EndOfServiceNote
	 */
	public final java.lang.String getEndOfServiceNote()
	{
		return getEndOfServiceNote(getContext());
	}

	/**
	 * @param context
	 * @return value of EndOfServiceNote
	 */
	public final java.lang.String getEndOfServiceNote(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EndOfServiceNote.toString());
	}

	/**
	 * Set value of EndOfServiceNote
	 * @param endofservicenote
	 */
	public final void setEndOfServiceNote(java.lang.String endofservicenote)
	{
		setEndOfServiceNote(getContext(), endofservicenote);
	}

	/**
	 * Set value of EndOfServiceNote
	 * @param context
	 * @param endofservicenote
	 */
	public final void setEndOfServiceNote(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String endofservicenote)
	{
		getMendixObject().setValue(context, MemberNames.EndOfServiceNote.toString(), endofservicenote);
	}

	/**
	 * @return value of Picture
	 */
	public final java.lang.String getPicture()
	{
		return getPicture(getContext());
	}

	/**
	 * @param context
	 * @return value of Picture
	 */
	public final java.lang.String getPicture(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Picture.toString());
	}

	/**
	 * Set value of Picture
	 * @param picture
	 */
	public final void setPicture(java.lang.String picture)
	{
		setPicture(getContext(), picture);
	}

	/**
	 * Set value of Picture
	 * @param context
	 * @param picture
	 */
	public final void setPicture(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String picture)
	{
		getMendixObject().setValue(context, MemberNames.Picture.toString(), picture);
	}

	/**
	 * @return value of Inactive
	 */
	public final java.lang.Boolean getInactive()
	{
		return getInactive(getContext());
	}

	/**
	 * @param context
	 * @return value of Inactive
	 */
	public final java.lang.Boolean getInactive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Inactive.toString());
	}

	/**
	 * Set value of Inactive
	 * @param inactive
	 */
	public final void setInactive(java.lang.Boolean inactive)
	{
		setInactive(getContext(), inactive);
	}

	/**
	 * Set value of Inactive
	 * @param context
	 * @param inactive
	 */
	public final void setInactive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean inactive)
	{
		getMendixObject().setValue(context, MemberNames.Inactive.toString(), inactive);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sdemigration.proxies.CIType that = (sdemigration.proxies.CIType) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SDEMigration.CIType";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
