// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sdemigration.proxies;

public class WorkorderICT extends sdemigration.proxies.SDEObject
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SDEMigration.WorkorderICT";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Sequence("Sequence"),
		Hdnum("Hdnum"),
		Change("Change"),
		Description("Description"),
		Result("Result"),
		Information("Information"),
		Category("Category"),
		CreationDate("CreationDate"),
		TargetDate("TargetDate"),
		CompletionDate("CompletionDate"),
		Group("Group"),
		StaffMember("StaffMember"),
		Supplier("Supplier"),
		ReferenceNumber("ReferenceNumber"),
		Status("Status"),
		Inactive("Inactive"),
		CreatedBy("CreatedBy"),
		OpenClosed("OpenClosed"),
		processed("processed"),
		SDEObject_MigrationItemRun("SDEMigration.SDEObject_MigrationItemRun"),
		IncomingRequest_SDEObject("InterfaceRequests.IncomingRequest_SDEObject");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkorderICT(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SDEMigration.WorkorderICT"));
	}

	protected WorkorderICT(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workorderICTMendixObject)
	{
		super(context, workorderICTMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("SDEMigration.WorkorderICT", workorderICTMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SDEMigration.WorkorderICT");
	}

	/**
	 * @deprecated Use 'WorkorderICT.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static sdemigration.proxies.WorkorderICT initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sdemigration.proxies.WorkorderICT.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static sdemigration.proxies.WorkorderICT initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sdemigration.proxies.WorkorderICT(context, mendixObject);
	}

	public static sdemigration.proxies.WorkorderICT load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sdemigration.proxies.WorkorderICT.initialize(context, mendixObject);
	}

	public static java.util.List<sdemigration.proxies.WorkorderICT> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<sdemigration.proxies.WorkorderICT> result = new java.util.ArrayList<sdemigration.proxies.WorkorderICT>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//SDEMigration.WorkorderICT" + xpathConstraint))
			result.add(sdemigration.proxies.WorkorderICT.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Sequence
	 */
	public final java.lang.String getSequence()
	{
		return getSequence(getContext());
	}

	/**
	 * @param context
	 * @return value of Sequence
	 */
	public final java.lang.String getSequence(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sequence.toString());
	}

	/**
	 * Set value of Sequence
	 * @param sequence
	 */
	public final void setSequence(java.lang.String sequence)
	{
		setSequence(getContext(), sequence);
	}

	/**
	 * Set value of Sequence
	 * @param context
	 * @param sequence
	 */
	public final void setSequence(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sequence)
	{
		getMendixObject().setValue(context, MemberNames.Sequence.toString(), sequence);
	}

	/**
	 * @return value of Hdnum
	 */
	public final java.lang.String getHdnum()
	{
		return getHdnum(getContext());
	}

	/**
	 * @param context
	 * @return value of Hdnum
	 */
	public final java.lang.String getHdnum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Hdnum.toString());
	}

	/**
	 * Set value of Hdnum
	 * @param hdnum
	 */
	public final void setHdnum(java.lang.String hdnum)
	{
		setHdnum(getContext(), hdnum);
	}

	/**
	 * Set value of Hdnum
	 * @param context
	 * @param hdnum
	 */
	public final void setHdnum(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String hdnum)
	{
		getMendixObject().setValue(context, MemberNames.Hdnum.toString(), hdnum);
	}

	/**
	 * @return value of Change
	 */
	public final java.lang.String getChange()
	{
		return getChange(getContext());
	}

	/**
	 * @param context
	 * @return value of Change
	 */
	public final java.lang.String getChange(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Change.toString());
	}

	/**
	 * Set value of Change
	 * @param change
	 */
	public final void setChange(java.lang.String change)
	{
		setChange(getContext(), change);
	}

	/**
	 * Set value of Change
	 * @param context
	 * @param change
	 */
	public final void setChange(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String change)
	{
		getMendixObject().setValue(context, MemberNames.Change.toString(), change);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Result
	 */
	public final java.lang.String getResult()
	{
		return getResult(getContext());
	}

	/**
	 * @param context
	 * @return value of Result
	 */
	public final java.lang.String getResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Result.toString());
	}

	/**
	 * Set value of Result
	 * @param result
	 */
	public final void setResult(java.lang.String result)
	{
		setResult(getContext(), result);
	}

	/**
	 * Set value of Result
	 * @param context
	 * @param result
	 */
	public final void setResult(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String result)
	{
		getMendixObject().setValue(context, MemberNames.Result.toString(), result);
	}

	/**
	 * @return value of Information
	 */
	public final java.lang.String getInformation()
	{
		return getInformation(getContext());
	}

	/**
	 * @param context
	 * @return value of Information
	 */
	public final java.lang.String getInformation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Information.toString());
	}

	/**
	 * Set value of Information
	 * @param information
	 */
	public final void setInformation(java.lang.String information)
	{
		setInformation(getContext(), information);
	}

	/**
	 * Set value of Information
	 * @param context
	 * @param information
	 */
	public final void setInformation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String information)
	{
		getMendixObject().setValue(context, MemberNames.Information.toString(), information);
	}

	/**
	 * @return value of Category
	 */
	public final java.lang.String getCategory()
	{
		return getCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of Category
	 */
	public final java.lang.String getCategory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Category.toString());
	}

	/**
	 * Set value of Category
	 * @param category
	 */
	public final void setCategory(java.lang.String category)
	{
		setCategory(getContext(), category);
	}

	/**
	 * Set value of Category
	 * @param context
	 * @param category
	 */
	public final void setCategory(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String category)
	{
		getMendixObject().setValue(context, MemberNames.Category.toString(), category);
	}

	/**
	 * @return value of CreationDate
	 */
	public final java.util.Date getCreationDate()
	{
		return getCreationDate(getContext());
	}

	/**
	 * @param context
	 * @return value of CreationDate
	 */
	public final java.util.Date getCreationDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CreationDate.toString());
	}

	/**
	 * Set value of CreationDate
	 * @param creationdate
	 */
	public final void setCreationDate(java.util.Date creationdate)
	{
		setCreationDate(getContext(), creationdate);
	}

	/**
	 * Set value of CreationDate
	 * @param context
	 * @param creationdate
	 */
	public final void setCreationDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date creationdate)
	{
		getMendixObject().setValue(context, MemberNames.CreationDate.toString(), creationdate);
	}

	/**
	 * @return value of TargetDate
	 */
	public final java.util.Date getTargetDate()
	{
		return getTargetDate(getContext());
	}

	/**
	 * @param context
	 * @return value of TargetDate
	 */
	public final java.util.Date getTargetDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.TargetDate.toString());
	}

	/**
	 * Set value of TargetDate
	 * @param targetdate
	 */
	public final void setTargetDate(java.util.Date targetdate)
	{
		setTargetDate(getContext(), targetdate);
	}

	/**
	 * Set value of TargetDate
	 * @param context
	 * @param targetdate
	 */
	public final void setTargetDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date targetdate)
	{
		getMendixObject().setValue(context, MemberNames.TargetDate.toString(), targetdate);
	}

	/**
	 * @return value of CompletionDate
	 */
	public final java.util.Date getCompletionDate()
	{
		return getCompletionDate(getContext());
	}

	/**
	 * @param context
	 * @return value of CompletionDate
	 */
	public final java.util.Date getCompletionDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CompletionDate.toString());
	}

	/**
	 * Set value of CompletionDate
	 * @param completiondate
	 */
	public final void setCompletionDate(java.util.Date completiondate)
	{
		setCompletionDate(getContext(), completiondate);
	}

	/**
	 * Set value of CompletionDate
	 * @param context
	 * @param completiondate
	 */
	public final void setCompletionDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date completiondate)
	{
		getMendixObject().setValue(context, MemberNames.CompletionDate.toString(), completiondate);
	}

	/**
	 * @return value of Group
	 */
	public final java.lang.String getGroup()
	{
		return getGroup(getContext());
	}

	/**
	 * @param context
	 * @return value of Group
	 */
	public final java.lang.String getGroup(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Group.toString());
	}

	/**
	 * Set value of Group
	 * @param group
	 */
	public final void setGroup(java.lang.String group)
	{
		setGroup(getContext(), group);
	}

	/**
	 * Set value of Group
	 * @param context
	 * @param group
	 */
	public final void setGroup(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String group)
	{
		getMendixObject().setValue(context, MemberNames.Group.toString(), group);
	}

	/**
	 * @return value of StaffMember
	 */
	public final java.lang.String getStaffMember()
	{
		return getStaffMember(getContext());
	}

	/**
	 * @param context
	 * @return value of StaffMember
	 */
	public final java.lang.String getStaffMember(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StaffMember.toString());
	}

	/**
	 * Set value of StaffMember
	 * @param staffmember
	 */
	public final void setStaffMember(java.lang.String staffmember)
	{
		setStaffMember(getContext(), staffmember);
	}

	/**
	 * Set value of StaffMember
	 * @param context
	 * @param staffmember
	 */
	public final void setStaffMember(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String staffmember)
	{
		getMendixObject().setValue(context, MemberNames.StaffMember.toString(), staffmember);
	}

	/**
	 * @return value of Supplier
	 */
	public final java.lang.String getSupplier()
	{
		return getSupplier(getContext());
	}

	/**
	 * @param context
	 * @return value of Supplier
	 */
	public final java.lang.String getSupplier(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Supplier.toString());
	}

	/**
	 * Set value of Supplier
	 * @param supplier
	 */
	public final void setSupplier(java.lang.String supplier)
	{
		setSupplier(getContext(), supplier);
	}

	/**
	 * Set value of Supplier
	 * @param context
	 * @param supplier
	 */
	public final void setSupplier(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String supplier)
	{
		getMendixObject().setValue(context, MemberNames.Supplier.toString(), supplier);
	}

	/**
	 * @return value of ReferenceNumber
	 */
	public final java.lang.String getReferenceNumber()
	{
		return getReferenceNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of ReferenceNumber
	 */
	public final java.lang.String getReferenceNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReferenceNumber.toString());
	}

	/**
	 * Set value of ReferenceNumber
	 * @param referencenumber
	 */
	public final void setReferenceNumber(java.lang.String referencenumber)
	{
		setReferenceNumber(getContext(), referencenumber);
	}

	/**
	 * Set value of ReferenceNumber
	 * @param context
	 * @param referencenumber
	 */
	public final void setReferenceNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String referencenumber)
	{
		getMendixObject().setValue(context, MemberNames.ReferenceNumber.toString(), referencenumber);
	}

	/**
	 * @return value of Status
	 */
	public final java.lang.String getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final java.lang.String getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Status.toString());
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(java.lang.String status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String status)
	{
		getMendixObject().setValue(context, MemberNames.Status.toString(), status);
	}

	/**
	 * @return value of Inactive
	 */
	public final java.lang.Boolean getInactive()
	{
		return getInactive(getContext());
	}

	/**
	 * @param context
	 * @return value of Inactive
	 */
	public final java.lang.Boolean getInactive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Inactive.toString());
	}

	/**
	 * Set value of Inactive
	 * @param inactive
	 */
	public final void setInactive(java.lang.Boolean inactive)
	{
		setInactive(getContext(), inactive);
	}

	/**
	 * Set value of Inactive
	 * @param context
	 * @param inactive
	 */
	public final void setInactive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean inactive)
	{
		getMendixObject().setValue(context, MemberNames.Inactive.toString(), inactive);
	}

	/**
	 * @return value of CreatedBy
	 */
	public final java.lang.String getCreatedBy()
	{
		return getCreatedBy(getContext());
	}

	/**
	 * @param context
	 * @return value of CreatedBy
	 */
	public final java.lang.String getCreatedBy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CreatedBy.toString());
	}

	/**
	 * Set value of CreatedBy
	 * @param createdby
	 */
	public final void setCreatedBy(java.lang.String createdby)
	{
		setCreatedBy(getContext(), createdby);
	}

	/**
	 * Set value of CreatedBy
	 * @param context
	 * @param createdby
	 */
	public final void setCreatedBy(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String createdby)
	{
		getMendixObject().setValue(context, MemberNames.CreatedBy.toString(), createdby);
	}

	/**
	 * @return value of OpenClosed
	 */
	public final java.lang.String getOpenClosed()
	{
		return getOpenClosed(getContext());
	}

	/**
	 * @param context
	 * @return value of OpenClosed
	 */
	public final java.lang.String getOpenClosed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OpenClosed.toString());
	}

	/**
	 * Set value of OpenClosed
	 * @param openclosed
	 */
	public final void setOpenClosed(java.lang.String openclosed)
	{
		setOpenClosed(getContext(), openclosed);
	}

	/**
	 * Set value of OpenClosed
	 * @param context
	 * @param openclosed
	 */
	public final void setOpenClosed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String openclosed)
	{
		getMendixObject().setValue(context, MemberNames.OpenClosed.toString(), openclosed);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sdemigration.proxies.WorkorderICT that = (sdemigration.proxies.WorkorderICT) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SDEMigration.WorkorderICT";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
