// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package interfacenotes.proxies;

public class NoteResponse extends interfaceshared.proxies.ResponseExpertDesk
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "InterfaceNotes.NoteResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ResponseCode("ResponseCode"),
		ResponseMessage("ResponseMessage"),
		NoteResponse_Note("InterfaceNotes.NoteResponse_Note"),
		NoteResponse_NotesResponse("InterfaceNotes.NoteResponse_NotesResponse"),
		NoteResponse_NoteResponsesContainerExpertDesk("InterfaceNotes.NoteResponse_NoteResponsesContainerExpertDesk"),
		NotesContainerExpertDesk_NoteResponse("InterfaceNotes.NotesContainerExpertDesk_NoteResponse"),
		NoteResponse_RequestResponse("InterfaceNotes.NoteResponse_RequestResponse"),
		NoteResponse_RequestResponseTask("InterfaceNotes.NoteResponse_RequestResponseTask"),
		ProcessingAttempt_Response("InterfaceShared.ProcessingAttempt_Response"),
		IncomingMessage_SynchronousResponse("InterfaceShared.IncomingMessage_SynchronousResponse");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public NoteResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "InterfaceNotes.NoteResponse"));
	}

	protected NoteResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject noteResponseMendixObject)
	{
		super(context, noteResponseMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("InterfaceNotes.NoteResponse", noteResponseMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a InterfaceNotes.NoteResponse");
	}

	/**
	 * @deprecated Use 'NoteResponse.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static interfacenotes.proxies.NoteResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return interfacenotes.proxies.NoteResponse.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static interfacenotes.proxies.NoteResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new interfacenotes.proxies.NoteResponse(context, mendixObject);
	}

	public static interfacenotes.proxies.NoteResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return interfacenotes.proxies.NoteResponse.initialize(context, mendixObject);
	}

	public static java.util.List<interfacenotes.proxies.NoteResponse> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<interfacenotes.proxies.NoteResponse> result = new java.util.ArrayList<interfacenotes.proxies.NoteResponse>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//InterfaceNotes.NoteResponse" + xpathConstraint))
			result.add(interfacenotes.proxies.NoteResponse.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of NoteResponse_Note
	 */
	public final interfacenotes.proxies.Note getNoteResponse_Note() throws com.mendix.core.CoreException
	{
		return getNoteResponse_Note(getContext());
	}

	/**
	 * @param context
	 * @return value of NoteResponse_Note
	 */
	public final interfacenotes.proxies.Note getNoteResponse_Note(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacenotes.proxies.Note result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NoteResponse_Note.toString());
		if (identifier != null)
			result = interfacenotes.proxies.Note.load(context, identifier);
		return result;
	}

	/**
	 * Set value of NoteResponse_Note
	 * @param noteresponse_note
	 */
	public final void setNoteResponse_Note(interfacenotes.proxies.Note noteresponse_note)
	{
		setNoteResponse_Note(getContext(), noteresponse_note);
	}

	/**
	 * Set value of NoteResponse_Note
	 * @param context
	 * @param noteresponse_note
	 */
	public final void setNoteResponse_Note(com.mendix.systemwideinterfaces.core.IContext context, interfacenotes.proxies.Note noteresponse_note)
	{
		if (noteresponse_note == null)
			getMendixObject().setValue(context, MemberNames.NoteResponse_Note.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.NoteResponse_Note.toString(), noteresponse_note.getMendixObject().getId());
	}

	/**
	 * @return value of NoteResponse_NotesResponse
	 */
	public final interfacenotes.proxies.NotesResponse getNoteResponse_NotesResponse() throws com.mendix.core.CoreException
	{
		return getNoteResponse_NotesResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of NoteResponse_NotesResponse
	 */
	public final interfacenotes.proxies.NotesResponse getNoteResponse_NotesResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacenotes.proxies.NotesResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NoteResponse_NotesResponse.toString());
		if (identifier != null)
			result = interfacenotes.proxies.NotesResponse.load(context, identifier);
		return result;
	}

	/**
	 * Set value of NoteResponse_NotesResponse
	 * @param noteresponse_notesresponse
	 */
	public final void setNoteResponse_NotesResponse(interfacenotes.proxies.NotesResponse noteresponse_notesresponse)
	{
		setNoteResponse_NotesResponse(getContext(), noteresponse_notesresponse);
	}

	/**
	 * Set value of NoteResponse_NotesResponse
	 * @param context
	 * @param noteresponse_notesresponse
	 */
	public final void setNoteResponse_NotesResponse(com.mendix.systemwideinterfaces.core.IContext context, interfacenotes.proxies.NotesResponse noteresponse_notesresponse)
	{
		if (noteresponse_notesresponse == null)
			getMendixObject().setValue(context, MemberNames.NoteResponse_NotesResponse.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.NoteResponse_NotesResponse.toString(), noteresponse_notesresponse.getMendixObject().getId());
	}

	/**
	 * @return value of NoteResponse_NoteResponsesContainerExpertDesk
	 */
	public final interfacenotes.proxies.NoteResponsesContainerExpertDesk getNoteResponse_NoteResponsesContainerExpertDesk() throws com.mendix.core.CoreException
	{
		return getNoteResponse_NoteResponsesContainerExpertDesk(getContext());
	}

	/**
	 * @param context
	 * @return value of NoteResponse_NoteResponsesContainerExpertDesk
	 */
	public final interfacenotes.proxies.NoteResponsesContainerExpertDesk getNoteResponse_NoteResponsesContainerExpertDesk(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacenotes.proxies.NoteResponsesContainerExpertDesk result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NoteResponse_NoteResponsesContainerExpertDesk.toString());
		if (identifier != null)
			result = interfacenotes.proxies.NoteResponsesContainerExpertDesk.load(context, identifier);
		return result;
	}

	/**
	 * Set value of NoteResponse_NoteResponsesContainerExpertDesk
	 * @param noteresponse_noteresponsescontainerexpertdesk
	 */
	public final void setNoteResponse_NoteResponsesContainerExpertDesk(interfacenotes.proxies.NoteResponsesContainerExpertDesk noteresponse_noteresponsescontainerexpertdesk)
	{
		setNoteResponse_NoteResponsesContainerExpertDesk(getContext(), noteresponse_noteresponsescontainerexpertdesk);
	}

	/**
	 * Set value of NoteResponse_NoteResponsesContainerExpertDesk
	 * @param context
	 * @param noteresponse_noteresponsescontainerexpertdesk
	 */
	public final void setNoteResponse_NoteResponsesContainerExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, interfacenotes.proxies.NoteResponsesContainerExpertDesk noteresponse_noteresponsescontainerexpertdesk)
	{
		if (noteresponse_noteresponsescontainerexpertdesk == null)
			getMendixObject().setValue(context, MemberNames.NoteResponse_NoteResponsesContainerExpertDesk.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.NoteResponse_NoteResponsesContainerExpertDesk.toString(), noteresponse_noteresponsescontainerexpertdesk.getMendixObject().getId());
	}

	/**
	 * @return value of NotesContainerExpertDesk_NoteResponse
	 */
	public final interfacenotes.proxies.NotesContainerExpertDesk getNotesContainerExpertDesk_NoteResponse() throws com.mendix.core.CoreException
	{
		return getNotesContainerExpertDesk_NoteResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of NotesContainerExpertDesk_NoteResponse
	 */
	public final interfacenotes.proxies.NotesContainerExpertDesk getNotesContainerExpertDesk_NoteResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacenotes.proxies.NotesContainerExpertDesk result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NotesContainerExpertDesk_NoteResponse.toString());
		if (identifier != null)
			result = interfacenotes.proxies.NotesContainerExpertDesk.load(context, identifier);
		return result;
	}

	/**
	 * Set value of NotesContainerExpertDesk_NoteResponse
	 * @param notescontainerexpertdesk_noteresponse
	 */
	public final void setNotesContainerExpertDesk_NoteResponse(interfacenotes.proxies.NotesContainerExpertDesk notescontainerexpertdesk_noteresponse)
	{
		setNotesContainerExpertDesk_NoteResponse(getContext(), notescontainerexpertdesk_noteresponse);
	}

	/**
	 * Set value of NotesContainerExpertDesk_NoteResponse
	 * @param context
	 * @param notescontainerexpertdesk_noteresponse
	 */
	public final void setNotesContainerExpertDesk_NoteResponse(com.mendix.systemwideinterfaces.core.IContext context, interfacenotes.proxies.NotesContainerExpertDesk notescontainerexpertdesk_noteresponse)
	{
		if (notescontainerexpertdesk_noteresponse == null)
			getMendixObject().setValue(context, MemberNames.NotesContainerExpertDesk_NoteResponse.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.NotesContainerExpertDesk_NoteResponse.toString(), notescontainerexpertdesk_noteresponse.getMendixObject().getId());
	}

	/**
	 * @return value of NoteResponse_RequestResponse
	 */
	public final interfacerequests.proxies.RequestResponse getNoteResponse_RequestResponse() throws com.mendix.core.CoreException
	{
		return getNoteResponse_RequestResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of NoteResponse_RequestResponse
	 */
	public final interfacerequests.proxies.RequestResponse getNoteResponse_RequestResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacerequests.proxies.RequestResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NoteResponse_RequestResponse.toString());
		if (identifier != null)
			result = interfacerequests.proxies.RequestResponse.load(context, identifier);
		return result;
	}

	/**
	 * Set value of NoteResponse_RequestResponse
	 * @param noteresponse_requestresponse
	 */
	public final void setNoteResponse_RequestResponse(interfacerequests.proxies.RequestResponse noteresponse_requestresponse)
	{
		setNoteResponse_RequestResponse(getContext(), noteresponse_requestresponse);
	}

	/**
	 * Set value of NoteResponse_RequestResponse
	 * @param context
	 * @param noteresponse_requestresponse
	 */
	public final void setNoteResponse_RequestResponse(com.mendix.systemwideinterfaces.core.IContext context, interfacerequests.proxies.RequestResponse noteresponse_requestresponse)
	{
		if (noteresponse_requestresponse == null)
			getMendixObject().setValue(context, MemberNames.NoteResponse_RequestResponse.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.NoteResponse_RequestResponse.toString(), noteresponse_requestresponse.getMendixObject().getId());
	}

	/**
	 * @return value of NoteResponse_RequestResponseTask
	 */
	public final interfacerequests.proxies.TaskResponse getNoteResponse_RequestResponseTask() throws com.mendix.core.CoreException
	{
		return getNoteResponse_RequestResponseTask(getContext());
	}

	/**
	 * @param context
	 * @return value of NoteResponse_RequestResponseTask
	 */
	public final interfacerequests.proxies.TaskResponse getNoteResponse_RequestResponseTask(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacerequests.proxies.TaskResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NoteResponse_RequestResponseTask.toString());
		if (identifier != null)
			result = interfacerequests.proxies.TaskResponse.load(context, identifier);
		return result;
	}

	/**
	 * Set value of NoteResponse_RequestResponseTask
	 * @param noteresponse_requestresponsetask
	 */
	public final void setNoteResponse_RequestResponseTask(interfacerequests.proxies.TaskResponse noteresponse_requestresponsetask)
	{
		setNoteResponse_RequestResponseTask(getContext(), noteresponse_requestresponsetask);
	}

	/**
	 * Set value of NoteResponse_RequestResponseTask
	 * @param context
	 * @param noteresponse_requestresponsetask
	 */
	public final void setNoteResponse_RequestResponseTask(com.mendix.systemwideinterfaces.core.IContext context, interfacerequests.proxies.TaskResponse noteresponse_requestresponsetask)
	{
		if (noteresponse_requestresponsetask == null)
			getMendixObject().setValue(context, MemberNames.NoteResponse_RequestResponseTask.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.NoteResponse_RequestResponseTask.toString(), noteresponse_requestresponsetask.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final interfacenotes.proxies.NoteResponse that = (interfacenotes.proxies.NoteResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "InterfaceNotes.NoteResponse";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
