// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package interfacenotes.proxies;

/**
 * User is a string because the information is historic and you neither want to prevent deletion of a person, nor do you want a cascaded delete to a note.
 */
public class Note extends interfaceshared.proxies.AuditableEntity
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "InterfaceNotes.Note";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NoteGUID("NoteGUID"),
		NoteText("NoteText"),
		User("User"),
		DateString("DateString"),
		Date("Date"),
		PublicAvailable("PublicAvailable"),
		Note_IncomingNotes("InterfaceNotes.Note_IncomingNotes"),
		NoteResponseGUID_NotesContainerExpertDesk("InterfaceNotes.NoteResponseGUID_NotesContainerExpertDesk"),
		Note_NotesContainerExpertDesk("InterfaceNotes.Note_NotesContainerExpertDesk"),
		Note_IncomingRequest("InterfaceNotes.Note_IncomingRequest"),
		Note_Note("InterfaceNotes.Note_Note");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Note(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "InterfaceNotes.Note"));
	}

	protected Note(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject noteMendixObject)
	{
		super(context, noteMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("InterfaceNotes.Note", noteMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a InterfaceNotes.Note");
	}

	/**
	 * @deprecated Use 'Note.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static interfacenotes.proxies.Note initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return interfacenotes.proxies.Note.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static interfacenotes.proxies.Note initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new interfacenotes.proxies.Note(context, mendixObject);
	}

	public static interfacenotes.proxies.Note load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return interfacenotes.proxies.Note.initialize(context, mendixObject);
	}

	public static java.util.List<interfacenotes.proxies.Note> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<interfacenotes.proxies.Note> result = new java.util.ArrayList<interfacenotes.proxies.Note>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//InterfaceNotes.Note" + xpathConstraint))
			result.add(interfacenotes.proxies.Note.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of NoteGUID
	 */
	public final java.lang.String getNoteGUID()
	{
		return getNoteGUID(getContext());
	}

	/**
	 * @param context
	 * @return value of NoteGUID
	 */
	public final java.lang.String getNoteGUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NoteGUID.toString());
	}

	/**
	 * Set value of NoteGUID
	 * @param noteguid
	 */
	public final void setNoteGUID(java.lang.String noteguid)
	{
		setNoteGUID(getContext(), noteguid);
	}

	/**
	 * Set value of NoteGUID
	 * @param context
	 * @param noteguid
	 */
	public final void setNoteGUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String noteguid)
	{
		getMendixObject().setValue(context, MemberNames.NoteGUID.toString(), noteguid);
	}

	/**
	 * @return value of NoteText
	 */
	public final java.lang.String getNoteText()
	{
		return getNoteText(getContext());
	}

	/**
	 * @param context
	 * @return value of NoteText
	 */
	public final java.lang.String getNoteText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NoteText.toString());
	}

	/**
	 * Set value of NoteText
	 * @param notetext
	 */
	public final void setNoteText(java.lang.String notetext)
	{
		setNoteText(getContext(), notetext);
	}

	/**
	 * Set value of NoteText
	 * @param context
	 * @param notetext
	 */
	public final void setNoteText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String notetext)
	{
		getMendixObject().setValue(context, MemberNames.NoteText.toString(), notetext);
	}

	/**
	 * @return value of User
	 */
	public final java.lang.String getUser()
	{
		return getUser(getContext());
	}

	/**
	 * @param context
	 * @return value of User
	 */
	public final java.lang.String getUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.User.toString());
	}

	/**
	 * Set value of User
	 * @param user
	 */
	public final void setUser(java.lang.String user)
	{
		setUser(getContext(), user);
	}

	/**
	 * Set value of User
	 * @param context
	 * @param user
	 */
	public final void setUser(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String user)
	{
		getMendixObject().setValue(context, MemberNames.User.toString(), user);
	}

	/**
	 * @return value of DateString
	 */
	public final java.lang.String getDateString()
	{
		return getDateString(getContext());
	}

	/**
	 * @param context
	 * @return value of DateString
	 */
	public final java.lang.String getDateString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DateString.toString());
	}

	/**
	 * Set value of DateString
	 * @param datestring
	 */
	public final void setDateString(java.lang.String datestring)
	{
		setDateString(getContext(), datestring);
	}

	/**
	 * Set value of DateString
	 * @param context
	 * @param datestring
	 */
	public final void setDateString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String datestring)
	{
		getMendixObject().setValue(context, MemberNames.DateString.toString(), datestring);
	}

	/**
	 * @return value of Date
	 */
	public final java.util.Date getDate()
	{
		return getDate(getContext());
	}

	/**
	 * @param context
	 * @return value of Date
	 */
	public final java.util.Date getDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date.toString());
	}

	/**
	 * Set value of Date
	 * @param date
	 */
	public final void setDate(java.util.Date date)
	{
		setDate(getContext(), date);
	}

	/**
	 * Set value of Date
	 * @param context
	 * @param date
	 */
	public final void setDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date)
	{
		getMendixObject().setValue(context, MemberNames.Date.toString(), date);
	}

	/**
	 * @return value of PublicAvailable
	 */
	public final java.lang.Boolean getPublicAvailable()
	{
		return getPublicAvailable(getContext());
	}

	/**
	 * @param context
	 * @return value of PublicAvailable
	 */
	public final java.lang.Boolean getPublicAvailable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.PublicAvailable.toString());
	}

	/**
	 * Set value of PublicAvailable
	 * @param publicavailable
	 */
	public final void setPublicAvailable(java.lang.Boolean publicavailable)
	{
		setPublicAvailable(getContext(), publicavailable);
	}

	/**
	 * Set value of PublicAvailable
	 * @param context
	 * @param publicavailable
	 */
	public final void setPublicAvailable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean publicavailable)
	{
		getMendixObject().setValue(context, MemberNames.PublicAvailable.toString(), publicavailable);
	}

	/**
	 * @return value of Note_IncomingNotes
	 */
	public final interfacenotes.proxies.IncomingNotes getNote_IncomingNotes() throws com.mendix.core.CoreException
	{
		return getNote_IncomingNotes(getContext());
	}

	/**
	 * @param context
	 * @return value of Note_IncomingNotes
	 */
	public final interfacenotes.proxies.IncomingNotes getNote_IncomingNotes(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacenotes.proxies.IncomingNotes result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Note_IncomingNotes.toString());
		if (identifier != null)
			result = interfacenotes.proxies.IncomingNotes.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Note_IncomingNotes
	 * @param note_incomingnotes
	 */
	public final void setNote_IncomingNotes(interfacenotes.proxies.IncomingNotes note_incomingnotes)
	{
		setNote_IncomingNotes(getContext(), note_incomingnotes);
	}

	/**
	 * Set value of Note_IncomingNotes
	 * @param context
	 * @param note_incomingnotes
	 */
	public final void setNote_IncomingNotes(com.mendix.systemwideinterfaces.core.IContext context, interfacenotes.proxies.IncomingNotes note_incomingnotes)
	{
		if (note_incomingnotes == null)
			getMendixObject().setValue(context, MemberNames.Note_IncomingNotes.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Note_IncomingNotes.toString(), note_incomingnotes.getMendixObject().getId());
	}

	/**
	 * @return value of NoteResponseGUID_NotesContainerExpertDesk
	 */
	public final interfacenotes.proxies.NotesContainerExpertDesk getNoteResponseGUID_NotesContainerExpertDesk() throws com.mendix.core.CoreException
	{
		return getNoteResponseGUID_NotesContainerExpertDesk(getContext());
	}

	/**
	 * @param context
	 * @return value of NoteResponseGUID_NotesContainerExpertDesk
	 */
	public final interfacenotes.proxies.NotesContainerExpertDesk getNoteResponseGUID_NotesContainerExpertDesk(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacenotes.proxies.NotesContainerExpertDesk result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NoteResponseGUID_NotesContainerExpertDesk.toString());
		if (identifier != null)
			result = interfacenotes.proxies.NotesContainerExpertDesk.load(context, identifier);
		return result;
	}

	/**
	 * Set value of NoteResponseGUID_NotesContainerExpertDesk
	 * @param noteresponseguid_notescontainerexpertdesk
	 */
	public final void setNoteResponseGUID_NotesContainerExpertDesk(interfacenotes.proxies.NotesContainerExpertDesk noteresponseguid_notescontainerexpertdesk)
	{
		setNoteResponseGUID_NotesContainerExpertDesk(getContext(), noteresponseguid_notescontainerexpertdesk);
	}

	/**
	 * Set value of NoteResponseGUID_NotesContainerExpertDesk
	 * @param context
	 * @param noteresponseguid_notescontainerexpertdesk
	 */
	public final void setNoteResponseGUID_NotesContainerExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, interfacenotes.proxies.NotesContainerExpertDesk noteresponseguid_notescontainerexpertdesk)
	{
		if (noteresponseguid_notescontainerexpertdesk == null)
			getMendixObject().setValue(context, MemberNames.NoteResponseGUID_NotesContainerExpertDesk.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.NoteResponseGUID_NotesContainerExpertDesk.toString(), noteresponseguid_notescontainerexpertdesk.getMendixObject().getId());
	}

	/**
	 * @return value of Note_NotesContainerExpertDesk
	 */
	public final interfacenotes.proxies.NotesContainerExpertDesk getNote_NotesContainerExpertDesk() throws com.mendix.core.CoreException
	{
		return getNote_NotesContainerExpertDesk(getContext());
	}

	/**
	 * @param context
	 * @return value of Note_NotesContainerExpertDesk
	 */
	public final interfacenotes.proxies.NotesContainerExpertDesk getNote_NotesContainerExpertDesk(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacenotes.proxies.NotesContainerExpertDesk result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Note_NotesContainerExpertDesk.toString());
		if (identifier != null)
			result = interfacenotes.proxies.NotesContainerExpertDesk.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Note_NotesContainerExpertDesk
	 * @param note_notescontainerexpertdesk
	 */
	public final void setNote_NotesContainerExpertDesk(interfacenotes.proxies.NotesContainerExpertDesk note_notescontainerexpertdesk)
	{
		setNote_NotesContainerExpertDesk(getContext(), note_notescontainerexpertdesk);
	}

	/**
	 * Set value of Note_NotesContainerExpertDesk
	 * @param context
	 * @param note_notescontainerexpertdesk
	 */
	public final void setNote_NotesContainerExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, interfacenotes.proxies.NotesContainerExpertDesk note_notescontainerexpertdesk)
	{
		if (note_notescontainerexpertdesk == null)
			getMendixObject().setValue(context, MemberNames.Note_NotesContainerExpertDesk.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Note_NotesContainerExpertDesk.toString(), note_notescontainerexpertdesk.getMendixObject().getId());
	}

	/**
	 * @return value of Note_IncomingRequest
	 */
	public final interfacerequests.proxies.IncomingRequest getNote_IncomingRequest() throws com.mendix.core.CoreException
	{
		return getNote_IncomingRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of Note_IncomingRequest
	 */
	public final interfacerequests.proxies.IncomingRequest getNote_IncomingRequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacerequests.proxies.IncomingRequest result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Note_IncomingRequest.toString());
		if (identifier != null)
			result = interfacerequests.proxies.IncomingRequest.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Note_IncomingRequest
	 * @param note_incomingrequest
	 */
	public final void setNote_IncomingRequest(interfacerequests.proxies.IncomingRequest note_incomingrequest)
	{
		setNote_IncomingRequest(getContext(), note_incomingrequest);
	}

	/**
	 * Set value of Note_IncomingRequest
	 * @param context
	 * @param note_incomingrequest
	 */
	public final void setNote_IncomingRequest(com.mendix.systemwideinterfaces.core.IContext context, interfacerequests.proxies.IncomingRequest note_incomingrequest)
	{
		if (note_incomingrequest == null)
			getMendixObject().setValue(context, MemberNames.Note_IncomingRequest.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Note_IncomingRequest.toString(), note_incomingrequest.getMendixObject().getId());
	}

	/**
	 * @return value of Note_Note
	 */
	public final notes.proxies.Note getNote_Note() throws com.mendix.core.CoreException
	{
		return getNote_Note(getContext());
	}

	/**
	 * @param context
	 * @return value of Note_Note
	 */
	public final notes.proxies.Note getNote_Note(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		notes.proxies.Note result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Note_Note.toString());
		if (identifier != null)
			result = notes.proxies.Note.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Note_Note
	 * @param note_note
	 */
	public final void setNote_Note(notes.proxies.Note note_note)
	{
		setNote_Note(getContext(), note_note);
	}

	/**
	 * Set value of Note_Note
	 * @param context
	 * @param note_note
	 */
	public final void setNote_Note(com.mendix.systemwideinterfaces.core.IContext context, notes.proxies.Note note_note)
	{
		if (note_note == null)
			getMendixObject().setValue(context, MemberNames.Note_Note.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Note_Note.toString(), note_note.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final interfacenotes.proxies.Note that = (interfacenotes.proxies.Note) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "InterfaceNotes.Note";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
