// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package interfacenotes.proxies;

public class OutgoingNotesConfirmationMessageExpertDesk extends interfacenotes.proxies.OutgoingNotesConfirmation
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "InterfaceNotes.OutgoingNotesConfirmationMessageExpertDesk";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NextRetry("NextRetry"),
		RetryByHeartBeat("RetryByHeartBeat"),
		MessageID("MessageID"),
		MessageType("MessageType"),
		MessageDirection("MessageDirection"),
		Status("Status"),
		RetrievedInterfaceName("RetrievedInterfaceName"),
		CreatedByCustomMessage("CreatedByCustomMessage"),
		OutgoingNotesConfirmationExpertDesk_OutgoingNotesConfirmationMessageExpertDesk("InterfaceNotes.OutgoingNotesConfirmationExpertDesk_OutgoingNotesConfirmationMessageExpertDesk"),
		OutgoingNotesConfirmationMessageExpertDesk_MendixWebServiceHeader("InterfaceNotes.OutgoingNotesConfirmationMessageExpertDesk_MendixWebServiceHeader"),
		ProcessingAttempt_OutgoingConfirmation("InterfaceShared.ProcessingAttempt_OutgoingConfirmation"),
		InterfaceEvent_OutgoingMessage("InterfaceShared.InterfaceEvent_OutgoingMessage"),
		IncomingConfirmation_OutgoingMessage("InterfaceShared.IncomingConfirmation_OutgoingMessage"),
		OutgoingMessage_QueuedByOutgoingMessage("InterfaceShared.OutgoingMessage_QueuedByOutgoingMessage"),
		BooleanWrapper_Message("InterfaceShared.BooleanWrapper_Message"),
		Message_IndexData("InterfaceShared.Message_IndexData"),
		Message_InterfaceMessageConfiguration("InterfaceShared.Message_InterfaceMessageConfiguration"),
		Message_InterfaceConfiguration("InterfaceShared.Message_InterfaceConfiguration");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OutgoingNotesConfirmationMessageExpertDesk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "InterfaceNotes.OutgoingNotesConfirmationMessageExpertDesk"));
	}

	protected OutgoingNotesConfirmationMessageExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject outgoingNotesConfirmationMessageExpertDeskMendixObject)
	{
		super(context, outgoingNotesConfirmationMessageExpertDeskMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("InterfaceNotes.OutgoingNotesConfirmationMessageExpertDesk", outgoingNotesConfirmationMessageExpertDeskMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a InterfaceNotes.OutgoingNotesConfirmationMessageExpertDesk");
	}

	/**
	 * @deprecated Use 'OutgoingNotesConfirmationMessageExpertDesk.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static interfacenotes.proxies.OutgoingNotesConfirmationMessageExpertDesk initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return interfacenotes.proxies.OutgoingNotesConfirmationMessageExpertDesk.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static interfacenotes.proxies.OutgoingNotesConfirmationMessageExpertDesk initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new interfacenotes.proxies.OutgoingNotesConfirmationMessageExpertDesk(context, mendixObject);
	}

	public static interfacenotes.proxies.OutgoingNotesConfirmationMessageExpertDesk load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return interfacenotes.proxies.OutgoingNotesConfirmationMessageExpertDesk.initialize(context, mendixObject);
	}

	public static java.util.List<interfacenotes.proxies.OutgoingNotesConfirmationMessageExpertDesk> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<interfacenotes.proxies.OutgoingNotesConfirmationMessageExpertDesk> result = new java.util.ArrayList<interfacenotes.proxies.OutgoingNotesConfirmationMessageExpertDesk>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//InterfaceNotes.OutgoingNotesConfirmationMessageExpertDesk" + xpathConstraint))
			result.add(interfacenotes.proxies.OutgoingNotesConfirmationMessageExpertDesk.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of OutgoingNotesConfirmationExpertDesk_OutgoingNotesConfirmationMessageExpertDesk
	 */
	public final interfacenotes.proxies.OutgoingNotesConfirmationExpertDesk getOutgoingNotesConfirmationExpertDesk_OutgoingNotesConfirmationMessageExpertDesk() throws com.mendix.core.CoreException
	{
		return getOutgoingNotesConfirmationExpertDesk_OutgoingNotesConfirmationMessageExpertDesk(getContext());
	}

	/**
	 * @param context
	 * @return value of OutgoingNotesConfirmationExpertDesk_OutgoingNotesConfirmationMessageExpertDesk
	 */
	public final interfacenotes.proxies.OutgoingNotesConfirmationExpertDesk getOutgoingNotesConfirmationExpertDesk_OutgoingNotesConfirmationMessageExpertDesk(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacenotes.proxies.OutgoingNotesConfirmationExpertDesk result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OutgoingNotesConfirmationExpertDesk_OutgoingNotesConfirmationMessageExpertDesk.toString());
		if (identifier != null)
			result = interfacenotes.proxies.OutgoingNotesConfirmationExpertDesk.load(context, identifier);
		return result;
	}

	/**
	 * Set value of OutgoingNotesConfirmationExpertDesk_OutgoingNotesConfirmationMessageExpertDesk
	 * @param outgoingnotesconfirmationexpertdesk_outgoingnotesconfirmationmessageexpertdesk
	 */
	public final void setOutgoingNotesConfirmationExpertDesk_OutgoingNotesConfirmationMessageExpertDesk(interfacenotes.proxies.OutgoingNotesConfirmationExpertDesk outgoingnotesconfirmationexpertdesk_outgoingnotesconfirmationmessageexpertdesk)
	{
		setOutgoingNotesConfirmationExpertDesk_OutgoingNotesConfirmationMessageExpertDesk(getContext(), outgoingnotesconfirmationexpertdesk_outgoingnotesconfirmationmessageexpertdesk);
	}

	/**
	 * Set value of OutgoingNotesConfirmationExpertDesk_OutgoingNotesConfirmationMessageExpertDesk
	 * @param context
	 * @param outgoingnotesconfirmationexpertdesk_outgoingnotesconfirmationmessageexpertdesk
	 */
	public final void setOutgoingNotesConfirmationExpertDesk_OutgoingNotesConfirmationMessageExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, interfacenotes.proxies.OutgoingNotesConfirmationExpertDesk outgoingnotesconfirmationexpertdesk_outgoingnotesconfirmationmessageexpertdesk)
	{
		if (outgoingnotesconfirmationexpertdesk_outgoingnotesconfirmationmessageexpertdesk == null)
			getMendixObject().setValue(context, MemberNames.OutgoingNotesConfirmationExpertDesk_OutgoingNotesConfirmationMessageExpertDesk.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.OutgoingNotesConfirmationExpertDesk_OutgoingNotesConfirmationMessageExpertDesk.toString(), outgoingnotesconfirmationexpertdesk_outgoingnotesconfirmationmessageexpertdesk.getMendixObject().getId());
	}

	/**
	 * @return value of OutgoingNotesConfirmationMessageExpertDesk_MendixWebServiceHeader
	 */
	public final interfaceshared.proxies.MendixWebServiceHeader getOutgoingNotesConfirmationMessageExpertDesk_MendixWebServiceHeader() throws com.mendix.core.CoreException
	{
		return getOutgoingNotesConfirmationMessageExpertDesk_MendixWebServiceHeader(getContext());
	}

	/**
	 * @param context
	 * @return value of OutgoingNotesConfirmationMessageExpertDesk_MendixWebServiceHeader
	 */
	public final interfaceshared.proxies.MendixWebServiceHeader getOutgoingNotesConfirmationMessageExpertDesk_MendixWebServiceHeader(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceshared.proxies.MendixWebServiceHeader result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OutgoingNotesConfirmationMessageExpertDesk_MendixWebServiceHeader.toString());
		if (identifier != null)
			result = interfaceshared.proxies.MendixWebServiceHeader.load(context, identifier);
		return result;
	}

	/**
	 * Set value of OutgoingNotesConfirmationMessageExpertDesk_MendixWebServiceHeader
	 * @param outgoingnotesconfirmationmessageexpertdesk_mendixwebserviceheader
	 */
	public final void setOutgoingNotesConfirmationMessageExpertDesk_MendixWebServiceHeader(interfaceshared.proxies.MendixWebServiceHeader outgoingnotesconfirmationmessageexpertdesk_mendixwebserviceheader)
	{
		setOutgoingNotesConfirmationMessageExpertDesk_MendixWebServiceHeader(getContext(), outgoingnotesconfirmationmessageexpertdesk_mendixwebserviceheader);
	}

	/**
	 * Set value of OutgoingNotesConfirmationMessageExpertDesk_MendixWebServiceHeader
	 * @param context
	 * @param outgoingnotesconfirmationmessageexpertdesk_mendixwebserviceheader
	 */
	public final void setOutgoingNotesConfirmationMessageExpertDesk_MendixWebServiceHeader(com.mendix.systemwideinterfaces.core.IContext context, interfaceshared.proxies.MendixWebServiceHeader outgoingnotesconfirmationmessageexpertdesk_mendixwebserviceheader)
	{
		if (outgoingnotesconfirmationmessageexpertdesk_mendixwebserviceheader == null)
			getMendixObject().setValue(context, MemberNames.OutgoingNotesConfirmationMessageExpertDesk_MendixWebServiceHeader.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.OutgoingNotesConfirmationMessageExpertDesk_MendixWebServiceHeader.toString(), outgoingnotesconfirmationmessageexpertdesk_mendixwebserviceheader.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final interfacenotes.proxies.OutgoingNotesConfirmationMessageExpertDesk that = (interfacenotes.proxies.OutgoingNotesConfirmationMessageExpertDesk) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "InterfaceNotes.OutgoingNotesConfirmationMessageExpertDesk";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
