// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package interfacenotes.proxies;

public class OutgoingNotesExpertDesk extends interfaceshared.proxies.AuditableEntity
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "InterfaceNotes.OutgoingNotesExpertDesk";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MessageID("MessageID"),
		InterfaceName("InterfaceName"),
		ExternalReferenceID("ExternalReferenceID"),
		InternalReferenceID("InternalReferenceID"),
		OutgoingNotesExpertDesk_OutgoingNotesMessageExpertDesk("InterfaceNotes.OutgoingNotesExpertDesk_OutgoingNotesMessageExpertDesk"),
		NotesContainerExpertDesk_OutgoingNotesExpertDesk("InterfaceNotes.NotesContainerExpertDesk_OutgoingNotesExpertDesk");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OutgoingNotesExpertDesk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "InterfaceNotes.OutgoingNotesExpertDesk"));
	}

	protected OutgoingNotesExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject outgoingNotesExpertDeskMendixObject)
	{
		super(context, outgoingNotesExpertDeskMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("InterfaceNotes.OutgoingNotesExpertDesk", outgoingNotesExpertDeskMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a InterfaceNotes.OutgoingNotesExpertDesk");
	}

	/**
	 * @deprecated Use 'OutgoingNotesExpertDesk.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static interfacenotes.proxies.OutgoingNotesExpertDesk initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return interfacenotes.proxies.OutgoingNotesExpertDesk.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static interfacenotes.proxies.OutgoingNotesExpertDesk initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new interfacenotes.proxies.OutgoingNotesExpertDesk(context, mendixObject);
	}

	public static interfacenotes.proxies.OutgoingNotesExpertDesk load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return interfacenotes.proxies.OutgoingNotesExpertDesk.initialize(context, mendixObject);
	}

	public static java.util.List<interfacenotes.proxies.OutgoingNotesExpertDesk> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<interfacenotes.proxies.OutgoingNotesExpertDesk> result = new java.util.ArrayList<interfacenotes.proxies.OutgoingNotesExpertDesk>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//InterfaceNotes.OutgoingNotesExpertDesk" + xpathConstraint))
			result.add(interfacenotes.proxies.OutgoingNotesExpertDesk.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of MessageID
	 */
	public final java.lang.String getMessageID()
	{
		return getMessageID(getContext());
	}

	/**
	 * @param context
	 * @return value of MessageID
	 */
	public final java.lang.String getMessageID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MessageID.toString());
	}

	/**
	 * Set value of MessageID
	 * @param messageid
	 */
	public final void setMessageID(java.lang.String messageid)
	{
		setMessageID(getContext(), messageid);
	}

	/**
	 * Set value of MessageID
	 * @param context
	 * @param messageid
	 */
	public final void setMessageID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String messageid)
	{
		getMendixObject().setValue(context, MemberNames.MessageID.toString(), messageid);
	}

	/**
	 * @return value of InterfaceName
	 */
	public final java.lang.String getInterfaceName()
	{
		return getInterfaceName(getContext());
	}

	/**
	 * @param context
	 * @return value of InterfaceName
	 */
	public final java.lang.String getInterfaceName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InterfaceName.toString());
	}

	/**
	 * Set value of InterfaceName
	 * @param interfacename
	 */
	public final void setInterfaceName(java.lang.String interfacename)
	{
		setInterfaceName(getContext(), interfacename);
	}

	/**
	 * Set value of InterfaceName
	 * @param context
	 * @param interfacename
	 */
	public final void setInterfaceName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String interfacename)
	{
		getMendixObject().setValue(context, MemberNames.InterfaceName.toString(), interfacename);
	}

	/**
	 * @return value of ExternalReferenceID
	 */
	public final java.lang.String getExternalReferenceID()
	{
		return getExternalReferenceID(getContext());
	}

	/**
	 * @param context
	 * @return value of ExternalReferenceID
	 */
	public final java.lang.String getExternalReferenceID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExternalReferenceID.toString());
	}

	/**
	 * Set value of ExternalReferenceID
	 * @param externalreferenceid
	 */
	public final void setExternalReferenceID(java.lang.String externalreferenceid)
	{
		setExternalReferenceID(getContext(), externalreferenceid);
	}

	/**
	 * Set value of ExternalReferenceID
	 * @param context
	 * @param externalreferenceid
	 */
	public final void setExternalReferenceID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String externalreferenceid)
	{
		getMendixObject().setValue(context, MemberNames.ExternalReferenceID.toString(), externalreferenceid);
	}

	/**
	 * @return value of InternalReferenceID
	 */
	public final java.lang.String getInternalReferenceID()
	{
		return getInternalReferenceID(getContext());
	}

	/**
	 * @param context
	 * @return value of InternalReferenceID
	 */
	public final java.lang.String getInternalReferenceID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InternalReferenceID.toString());
	}

	/**
	 * Set value of InternalReferenceID
	 * @param internalreferenceid
	 */
	public final void setInternalReferenceID(java.lang.String internalreferenceid)
	{
		setInternalReferenceID(getContext(), internalreferenceid);
	}

	/**
	 * Set value of InternalReferenceID
	 * @param context
	 * @param internalreferenceid
	 */
	public final void setInternalReferenceID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String internalreferenceid)
	{
		getMendixObject().setValue(context, MemberNames.InternalReferenceID.toString(), internalreferenceid);
	}

	/**
	 * @return value of OutgoingNotesExpertDesk_OutgoingNotesMessageExpertDesk
	 */
	public final interfacenotes.proxies.OutgoingNotesMessageExpertDesk getOutgoingNotesExpertDesk_OutgoingNotesMessageExpertDesk() throws com.mendix.core.CoreException
	{
		return getOutgoingNotesExpertDesk_OutgoingNotesMessageExpertDesk(getContext());
	}

	/**
	 * @param context
	 * @return value of OutgoingNotesExpertDesk_OutgoingNotesMessageExpertDesk
	 */
	public final interfacenotes.proxies.OutgoingNotesMessageExpertDesk getOutgoingNotesExpertDesk_OutgoingNotesMessageExpertDesk(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacenotes.proxies.OutgoingNotesMessageExpertDesk result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OutgoingNotesExpertDesk_OutgoingNotesMessageExpertDesk.toString());
		if (identifier != null)
			result = interfacenotes.proxies.OutgoingNotesMessageExpertDesk.load(context, identifier);
		return result;
	}

	/**
	 * Set value of OutgoingNotesExpertDesk_OutgoingNotesMessageExpertDesk
	 * @param outgoingnotesexpertdesk_outgoingnotesmessageexpertdesk
	 */
	public final void setOutgoingNotesExpertDesk_OutgoingNotesMessageExpertDesk(interfacenotes.proxies.OutgoingNotesMessageExpertDesk outgoingnotesexpertdesk_outgoingnotesmessageexpertdesk)
	{
		setOutgoingNotesExpertDesk_OutgoingNotesMessageExpertDesk(getContext(), outgoingnotesexpertdesk_outgoingnotesmessageexpertdesk);
	}

	/**
	 * Set value of OutgoingNotesExpertDesk_OutgoingNotesMessageExpertDesk
	 * @param context
	 * @param outgoingnotesexpertdesk_outgoingnotesmessageexpertdesk
	 */
	public final void setOutgoingNotesExpertDesk_OutgoingNotesMessageExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, interfacenotes.proxies.OutgoingNotesMessageExpertDesk outgoingnotesexpertdesk_outgoingnotesmessageexpertdesk)
	{
		if (outgoingnotesexpertdesk_outgoingnotesmessageexpertdesk == null)
			getMendixObject().setValue(context, MemberNames.OutgoingNotesExpertDesk_OutgoingNotesMessageExpertDesk.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.OutgoingNotesExpertDesk_OutgoingNotesMessageExpertDesk.toString(), outgoingnotesexpertdesk_outgoingnotesmessageexpertdesk.getMendixObject().getId());
	}

	/**
	 * @return value of NotesContainerExpertDesk_OutgoingNotesExpertDesk
	 */
	public final interfacenotes.proxies.NotesContainerExpertDesk getNotesContainerExpertDesk_OutgoingNotesExpertDesk() throws com.mendix.core.CoreException
	{
		return getNotesContainerExpertDesk_OutgoingNotesExpertDesk(getContext());
	}

	/**
	 * @param context
	 * @return value of NotesContainerExpertDesk_OutgoingNotesExpertDesk
	 */
	public final interfacenotes.proxies.NotesContainerExpertDesk getNotesContainerExpertDesk_OutgoingNotesExpertDesk(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacenotes.proxies.NotesContainerExpertDesk result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NotesContainerExpertDesk_OutgoingNotesExpertDesk.toString());
		if (identifier != null)
			result = interfacenotes.proxies.NotesContainerExpertDesk.load(context, identifier);
		return result;
	}

	/**
	 * Set value of NotesContainerExpertDesk_OutgoingNotesExpertDesk
	 * @param notescontainerexpertdesk_outgoingnotesexpertdesk
	 */
	public final void setNotesContainerExpertDesk_OutgoingNotesExpertDesk(interfacenotes.proxies.NotesContainerExpertDesk notescontainerexpertdesk_outgoingnotesexpertdesk)
	{
		setNotesContainerExpertDesk_OutgoingNotesExpertDesk(getContext(), notescontainerexpertdesk_outgoingnotesexpertdesk);
	}

	/**
	 * Set value of NotesContainerExpertDesk_OutgoingNotesExpertDesk
	 * @param context
	 * @param notescontainerexpertdesk_outgoingnotesexpertdesk
	 */
	public final void setNotesContainerExpertDesk_OutgoingNotesExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, interfacenotes.proxies.NotesContainerExpertDesk notescontainerexpertdesk_outgoingnotesexpertdesk)
	{
		if (notescontainerexpertdesk_outgoingnotesexpertdesk == null)
			getMendixObject().setValue(context, MemberNames.NotesContainerExpertDesk_OutgoingNotesExpertDesk.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.NotesContainerExpertDesk_OutgoingNotesExpertDesk.toString(), notescontainerexpertdesk_outgoingnotesexpertdesk.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final interfacenotes.proxies.OutgoingNotesExpertDesk that = (interfacenotes.proxies.OutgoingNotesExpertDesk) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "InterfaceNotes.OutgoingNotesExpertDesk";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
