// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package personaldashboard.proxies;

public class DashboardPreferenceItem
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dashboardPreferenceItemMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PersonalDashboard.DashboardPreferenceItem";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ColumnNumber("ColumnNumber"),
		IsEmpty("IsEmpty"),
		RowNumber("RowNumber"),
		FormPath("FormPath"),
		Section("Section"),
		Label("Label"),
		DashboardPreferenceItem_DashBoardConfiguration("PersonalDashboard.DashboardPreferenceItem_DashBoardConfiguration"),
		DashboardPreferenceItem_Account("PersonalDashboard.DashboardPreferenceItem_Account"),
		DashboardPreferenceItem_QueryProxy("PersonalDashboard.DashboardPreferenceItem_QueryProxy");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DashboardPreferenceItem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PersonalDashboard.DashboardPreferenceItem"));
	}

	protected DashboardPreferenceItem(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dashboardPreferenceItemMendixObject)
	{
		if (dashboardPreferenceItemMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PersonalDashboard.DashboardPreferenceItem", dashboardPreferenceItemMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PersonalDashboard.DashboardPreferenceItem");

		this.dashboardPreferenceItemMendixObject = dashboardPreferenceItemMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DashboardPreferenceItem.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static personaldashboard.proxies.DashboardPreferenceItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return personaldashboard.proxies.DashboardPreferenceItem.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static personaldashboard.proxies.DashboardPreferenceItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new personaldashboard.proxies.DashboardPreferenceItem(context, mendixObject);
	}

	public static personaldashboard.proxies.DashboardPreferenceItem load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return personaldashboard.proxies.DashboardPreferenceItem.initialize(context, mendixObject);
	}

	public static java.util.List<personaldashboard.proxies.DashboardPreferenceItem> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<personaldashboard.proxies.DashboardPreferenceItem> result = new java.util.ArrayList<personaldashboard.proxies.DashboardPreferenceItem>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PersonalDashboard.DashboardPreferenceItem" + xpathConstraint))
			result.add(personaldashboard.proxies.DashboardPreferenceItem.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ColumnNumber
	 */
	public final java.lang.Integer getColumnNumber()
	{
		return getColumnNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of ColumnNumber
	 */
	public final java.lang.Integer getColumnNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ColumnNumber.toString());
	}

	/**
	 * Set value of ColumnNumber
	 * @param columnnumber
	 */
	public final void setColumnNumber(java.lang.Integer columnnumber)
	{
		setColumnNumber(getContext(), columnnumber);
	}

	/**
	 * Set value of ColumnNumber
	 * @param context
	 * @param columnnumber
	 */
	public final void setColumnNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer columnnumber)
	{
		getMendixObject().setValue(context, MemberNames.ColumnNumber.toString(), columnnumber);
	}

	/**
	 * @return value of IsEmpty
	 */
	public final java.lang.Boolean getIsEmpty()
	{
		return getIsEmpty(getContext());
	}

	/**
	 * @param context
	 * @return value of IsEmpty
	 */
	public final java.lang.Boolean getIsEmpty(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsEmpty.toString());
	}

	/**
	 * Set value of IsEmpty
	 * @param isempty
	 */
	public final void setIsEmpty(java.lang.Boolean isempty)
	{
		setIsEmpty(getContext(), isempty);
	}

	/**
	 * Set value of IsEmpty
	 * @param context
	 * @param isempty
	 */
	public final void setIsEmpty(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isempty)
	{
		getMendixObject().setValue(context, MemberNames.IsEmpty.toString(), isempty);
	}

	/**
	 * @return value of RowNumber
	 */
	public final java.lang.Integer getRowNumber()
	{
		return getRowNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of RowNumber
	 */
	public final java.lang.Integer getRowNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.RowNumber.toString());
	}

	/**
	 * Set value of RowNumber
	 * @param rownumber
	 */
	public final void setRowNumber(java.lang.Integer rownumber)
	{
		setRowNumber(getContext(), rownumber);
	}

	/**
	 * Set value of RowNumber
	 * @param context
	 * @param rownumber
	 */
	public final void setRowNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer rownumber)
	{
		getMendixObject().setValue(context, MemberNames.RowNumber.toString(), rownumber);
	}

	/**
	 * @return value of FormPath
	 */
	public final java.lang.String getFormPath()
	{
		return getFormPath(getContext());
	}

	/**
	 * @param context
	 * @return value of FormPath
	 */
	public final java.lang.String getFormPath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FormPath.toString());
	}

	/**
	 * Set value of FormPath
	 * @param formpath
	 */
	public final void setFormPath(java.lang.String formpath)
	{
		setFormPath(getContext(), formpath);
	}

	/**
	 * Set value of FormPath
	 * @param context
	 * @param formpath
	 */
	public final void setFormPath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String formpath)
	{
		getMendixObject().setValue(context, MemberNames.FormPath.toString(), formpath);
	}

	/**
	 * Set value of Section
	 * @param section
	 */
	public final personaldashboard.proxies.PreferenceItemSection getSection()
	{
		return getSection(getContext());
	}

	/**
	 * @param context
	 * @return value of Section
	 */
	public final personaldashboard.proxies.PreferenceItemSection getSection(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Section.toString());
		if (obj == null)
			return null;

		return personaldashboard.proxies.PreferenceItemSection.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Section
	 * @param section
	 */
	public final void setSection(personaldashboard.proxies.PreferenceItemSection section)
	{
		setSection(getContext(), section);
	}

	/**
	 * Set value of Section
	 * @param context
	 * @param section
	 */
	public final void setSection(com.mendix.systemwideinterfaces.core.IContext context, personaldashboard.proxies.PreferenceItemSection section)
	{
		if (section != null)
			getMendixObject().setValue(context, MemberNames.Section.toString(), section.toString());
		else
			getMendixObject().setValue(context, MemberNames.Section.toString(), null);
	}

	/**
	 * @return value of Label
	 */
	public final java.lang.String getLabel()
	{
		return getLabel(getContext());
	}

	/**
	 * @param context
	 * @return value of Label
	 */
	public final java.lang.String getLabel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Label.toString());
	}

	/**
	 * Set value of Label
	 * @param label
	 */
	public final void setLabel(java.lang.String label)
	{
		setLabel(getContext(), label);
	}

	/**
	 * Set value of Label
	 * @param context
	 * @param label
	 */
	public final void setLabel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String label)
	{
		getMendixObject().setValue(context, MemberNames.Label.toString(), label);
	}

	/**
	 * @return value of DashboardPreferenceItem_DashBoardConfiguration
	 */
	public final personaldashboard.proxies.DashBoardConfiguration getDashboardPreferenceItem_DashBoardConfiguration() throws com.mendix.core.CoreException
	{
		return getDashboardPreferenceItem_DashBoardConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of DashboardPreferenceItem_DashBoardConfiguration
	 */
	public final personaldashboard.proxies.DashBoardConfiguration getDashboardPreferenceItem_DashBoardConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		personaldashboard.proxies.DashBoardConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DashboardPreferenceItem_DashBoardConfiguration.toString());
		if (identifier != null)
			result = personaldashboard.proxies.DashBoardConfiguration.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DashboardPreferenceItem_DashBoardConfiguration
	 * @param dashboardpreferenceitem_dashboardconfiguration
	 */
	public final void setDashboardPreferenceItem_DashBoardConfiguration(personaldashboard.proxies.DashBoardConfiguration dashboardpreferenceitem_dashboardconfiguration)
	{
		setDashboardPreferenceItem_DashBoardConfiguration(getContext(), dashboardpreferenceitem_dashboardconfiguration);
	}

	/**
	 * Set value of DashboardPreferenceItem_DashBoardConfiguration
	 * @param context
	 * @param dashboardpreferenceitem_dashboardconfiguration
	 */
	public final void setDashboardPreferenceItem_DashBoardConfiguration(com.mendix.systemwideinterfaces.core.IContext context, personaldashboard.proxies.DashBoardConfiguration dashboardpreferenceitem_dashboardconfiguration)
	{
		if (dashboardpreferenceitem_dashboardconfiguration == null)
			getMendixObject().setValue(context, MemberNames.DashboardPreferenceItem_DashBoardConfiguration.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DashboardPreferenceItem_DashBoardConfiguration.toString(), dashboardpreferenceitem_dashboardconfiguration.getMendixObject().getId());
	}

	/**
	 * @return value of DashboardPreferenceItem_Account
	 */
	public final mendix.proxies.Account getDashboardPreferenceItem_Account() throws com.mendix.core.CoreException
	{
		return getDashboardPreferenceItem_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of DashboardPreferenceItem_Account
	 */
	public final mendix.proxies.Account getDashboardPreferenceItem_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mendix.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DashboardPreferenceItem_Account.toString());
		if (identifier != null)
			result = mendix.proxies.Account.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DashboardPreferenceItem_Account
	 * @param dashboardpreferenceitem_account
	 */
	public final void setDashboardPreferenceItem_Account(mendix.proxies.Account dashboardpreferenceitem_account)
	{
		setDashboardPreferenceItem_Account(getContext(), dashboardpreferenceitem_account);
	}

	/**
	 * Set value of DashboardPreferenceItem_Account
	 * @param context
	 * @param dashboardpreferenceitem_account
	 */
	public final void setDashboardPreferenceItem_Account(com.mendix.systemwideinterfaces.core.IContext context, mendix.proxies.Account dashboardpreferenceitem_account)
	{
		if (dashboardpreferenceitem_account == null)
			getMendixObject().setValue(context, MemberNames.DashboardPreferenceItem_Account.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DashboardPreferenceItem_Account.toString(), dashboardpreferenceitem_account.getMendixObject().getId());
	}

	/**
	 * @return value of DashboardPreferenceItem_QueryProxy
	 */
	public final queryrequests.proxies.QueryProxy getDashboardPreferenceItem_QueryProxy() throws com.mendix.core.CoreException
	{
		return getDashboardPreferenceItem_QueryProxy(getContext());
	}

	/**
	 * @param context
	 * @return value of DashboardPreferenceItem_QueryProxy
	 */
	public final queryrequests.proxies.QueryProxy getDashboardPreferenceItem_QueryProxy(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		queryrequests.proxies.QueryProxy result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DashboardPreferenceItem_QueryProxy.toString());
		if (identifier != null)
			result = queryrequests.proxies.QueryProxy.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DashboardPreferenceItem_QueryProxy
	 * @param dashboardpreferenceitem_queryproxy
	 */
	public final void setDashboardPreferenceItem_QueryProxy(queryrequests.proxies.QueryProxy dashboardpreferenceitem_queryproxy)
	{
		setDashboardPreferenceItem_QueryProxy(getContext(), dashboardpreferenceitem_queryproxy);
	}

	/**
	 * Set value of DashboardPreferenceItem_QueryProxy
	 * @param context
	 * @param dashboardpreferenceitem_queryproxy
	 */
	public final void setDashboardPreferenceItem_QueryProxy(com.mendix.systemwideinterfaces.core.IContext context, queryrequests.proxies.QueryProxy dashboardpreferenceitem_queryproxy)
	{
		if (dashboardpreferenceitem_queryproxy == null)
			getMendixObject().setValue(context, MemberNames.DashboardPreferenceItem_QueryProxy.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DashboardPreferenceItem_QueryProxy.toString(), dashboardpreferenceitem_queryproxy.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dashboardPreferenceItemMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final personaldashboard.proxies.DashboardPreferenceItem that = (personaldashboard.proxies.DashboardPreferenceItem) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PersonalDashboard.DashboardPreferenceItem";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
