// This file was generated by Mendix Modeler 7.7.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package personaldashboard.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the PersonalDashboard module
	public static void clearAllConfig(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "PersonalDashboard.ClearAllConfig", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static personaldashboard.proxies.DashboardPreferenceItem createEmptyTile(IContext context, java.lang.Long _columnNumber, java.lang.Long _rowNumber, mendix.proxies.Account _account, personaldashboard.proxies.PreferenceItemSection _section)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ColumnNumber", _columnNumber);
			params.put("RowNumber", _rowNumber);
			params.put("Account", _account == null ? null : _account.getMendixObject());
			params.put("Section", _section == null ? null : _section.name());
			IMendixObject result = (IMendixObject)Core.execute(context, "PersonalDashboard.CreateEmptyTile", params);
			return result == null ? null : personaldashboard.proxies.DashboardPreferenceItem.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void drillDownStartPanel(IContext context, queryrequests.proxies.QueryPanel _queryPanel)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("QueryPanel", _queryPanel == null ? null : _queryPanel.getMendixObject());
			Core.execute(context, "PersonalDashboard.DrillDownStartPanel", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static changecalendar.proxies.ChangeCalendar dS_GetChangeCalendar(IContext context, personaldashboard.proxies.DashboardPreferenceItem _dashBoardPreferenceItem)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DashBoardPreferenceItem", _dashBoardPreferenceItem == null ? null : _dashBoardPreferenceItem.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "PersonalDashboard.DS_GetChangeCalendar", params);
			return result == null ? null : changecalendar.proxies.ChangeCalendar.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static queryrequests.proxies.QueryPanel dS_GetQueryPanelCustomQuery(IContext context, personaldashboard.proxies.DashboardPreferenceItem _customQueryDashboardPreferenceItem)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("CustomQueryDashboardPreferenceItem", _customQueryDashboardPreferenceItem == null ? null : _customQueryDashboardPreferenceItem.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "PersonalDashboard.DS_GetQueryPanelCustomQuery", params);
			return result == null ? null : queryrequests.proxies.QueryPanel.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void initDashBoardConfiguration(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "PersonalDashboard.InitDashBoardConfiguration", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_AddItemHeaderFullWidth(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "PersonalDashboard.IVK_AddItemHeaderFullWidth", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_AddItemMiddleCol1(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "PersonalDashboard.IVK_AddItemMiddleCol1", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_AddItemMiddleCol2(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "PersonalDashboard.IVK_AddItemMiddleCol2", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_ChangeSnippetQuery(IContext context, personaldashboard.proxies.DashboardPreferenceItem _dashBoardPreferenceItem)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DashBoardPreferenceItem", _dashBoardPreferenceItem == null ? null : _dashBoardPreferenceItem.getMendixObject());
			Core.execute(context, "PersonalDashboard.IVK_ChangeSnippetQuery", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_RemoveDashboardPreferenceItem(IContext context, personaldashboard.proxies.DashboardPreferenceItem _dashboardPreferenceItem)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DashboardPreferenceItem", _dashboardPreferenceItem == null ? null : _dashboardPreferenceItem.getMendixObject());
			Core.execute(context, "PersonalDashboard.IVK_RemoveDashboardPreferenceItem", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_SelectCustomQuery(IContext context, queryrequests.proxies.QueryProxy _queryProxy, personaldashboard.proxies.DashboardPreferenceItem _dashboardPreferenceItem)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("QueryProxy", _queryProxy == null ? null : _queryProxy.getMendixObject());
			params.put("DashboardPreferenceItem", _dashboardPreferenceItem == null ? null : _dashboardPreferenceItem.getMendixObject());
			Core.execute(context, "PersonalDashboard.IVK_SelectCustomQuery", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void selectTile(IContext context, personaldashboard.proxies.DashBoardConfiguration _dashBoardConfiguration, personaldashboard.proxies.DashboardPreferenceItem _dashboardPreferenceItem)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("DashBoardConfiguration", _dashBoardConfiguration == null ? null : _dashBoardConfiguration.getMendixObject());
			params.put("DashboardPreferenceItem", _dashboardPreferenceItem == null ? null : _dashboardPreferenceItem.getMendixObject());
			Core.execute(context, "PersonalDashboard.SelectTile", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void setEmptyTileContents(IContext context, personaldashboard.proxies.DashboardPreferenceItem _emptyPreferenceItem)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("EmptyPreferenceItem", _emptyPreferenceItem == null ? null : _emptyPreferenceItem.getMendixObject());
			Core.execute(context, "PersonalDashboard.SetEmptyTileContents", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void showPersonalDashboard(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "PersonalDashboard.ShowPersonalDashboard", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static queryrequests.proxies.QueryPanel sub_ReturnWorkingQueryPanel(IContext context, queryrequests.proxies.QueryPanel _existingQueryPanel, queryrequests.proxies.QueryProxy _queryProxy)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ExistingQueryPanel", _existingQueryPanel == null ? null : _existingQueryPanel.getMendixObject());
			params.put("QueryProxy", _queryProxy == null ? null : _queryProxy.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "PersonalDashboard.Sub_ReturnWorkingQueryPanel", params);
			return result == null ? null : queryrequests.proxies.QueryPanel.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}