// This file was generated by Mendix Modeler 7.7.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowexecution.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the WorkflowExecution module

	public static java.lang.Long getMaxLevelOfSubWorkflows()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("WorkflowExecution.MaxLevelOfSubWorkflows");
	}

	public static java.lang.Long getMaxNodeVisitCounter()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("WorkflowExecution.MaxNodeVisitCounter");
	}

	public static java.lang.Long getTimeOutDaysCheck()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("WorkflowExecution.TimeOutDaysCheck");
	}
}