// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package workflowtemplate.actions;

import com.mendix.systemwideinterfaces.core.IMendixObject;
import nl.mansystems.workflow.Create_WorkflowTemplateChart;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class Create_WorkflowChart extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __RelatedChartXML;
	private fusionchartsplus.proxies.ChartXML RelatedChartXML;
	private java.util.List<IMendixObject> __LinkList;
	private java.util.List<workflowtemplate.proxies.Link> LinkList;
	private java.util.List<IMendixObject> __NodeList;
	private java.util.List<workflowtemplate.proxies.Node> NodeList;
	private IMendixObject __StartWorkflow;
	private workflowtemplate.proxies.Workflow StartWorkflow;
	private java.lang.Long MaxOrder;

	public Create_WorkflowChart(IContext context, IMendixObject RelatedChartXML, java.util.List<IMendixObject> LinkList, java.util.List<IMendixObject> NodeList, IMendixObject StartWorkflow, java.lang.Long MaxOrder)
	{
		super(context);
		this.__RelatedChartXML = RelatedChartXML;
		this.__LinkList = LinkList;
		this.__NodeList = NodeList;
		this.__StartWorkflow = StartWorkflow;
		this.MaxOrder = MaxOrder;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		this.RelatedChartXML = __RelatedChartXML == null ? null : fusionchartsplus.proxies.ChartXML.initialize(getContext(), __RelatedChartXML);

		this.LinkList = new java.util.ArrayList<workflowtemplate.proxies.Link>();
		if (__LinkList != null)
			for (IMendixObject __LinkListElement : __LinkList)
				this.LinkList.add(workflowtemplate.proxies.Link.initialize(getContext(), __LinkListElement));

		this.NodeList = new java.util.ArrayList<workflowtemplate.proxies.Node>();
		if (__NodeList != null)
			for (IMendixObject __NodeListElement : __NodeList)
				this.NodeList.add(workflowtemplate.proxies.Node.initialize(getContext(), __NodeListElement));

		this.StartWorkflow = __StartWorkflow == null ? null : workflowtemplate.proxies.Workflow.initialize(getContext(), __StartWorkflow);

		// BEGIN USER CODE
		nl.mansystems.workflow.Create_WorkflowTemplateChart wtc = new Create_WorkflowTemplateChart(this.getContext(), RelatedChartXML, LinkList, NodeList, StartWorkflow, MaxOrder);
		return wtc.executeAction();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "Create_WorkflowChart";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
