// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package slm.proxies;

public class SPAttribute
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sPAttributeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SLM.SPAttribute";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		CODE("CODE"),
		FieldType("FieldType"),
		Value_String("Value_String"),
		Value_StringLong("Value_StringLong"),
		Value_Integer("Value_Integer"),
		Value_Float("Value_Float"),
		Value_DateTime("Value_DateTime"),
		Value_Date("Value_Date"),
		Value_Boolean("Value_Boolean"),
		Value_Currency("Value_Currency"),
		ImportExport_Value("ImportExport_Value"),
		RequireOnCreate("RequireOnCreate"),
		RequireOnSolve("RequireOnSolve"),
		RequireOnClose("RequireOnClose"),
		IsImport("IsImport"),
		SPAttribute_SPScreenBlock("SLM.SPAttribute_SPScreenBlock"),
		SPAttribute_SPAttributeValue_SelectedDropDown("SLM.SPAttribute_SPAttributeValue_SelectedDropDown"),
		SPAttribute_SPAttributeValue_SelectedRadio("SLM.SPAttribute_SPAttributeValue_SelectedRadio"),
		SPAttribute_SPDefinitionAttribute("SLM.SPAttribute_SPDefinitionAttribute");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SPAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SLM.SPAttribute"));
	}

	protected SPAttribute(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sPAttributeMendixObject)
	{
		if (sPAttributeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("SLM.SPAttribute", sPAttributeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SLM.SPAttribute");

		this.sPAttributeMendixObject = sPAttributeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SPAttribute.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static slm.proxies.SPAttribute initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return slm.proxies.SPAttribute.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static slm.proxies.SPAttribute initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new slm.proxies.SPAttribute(context, mendixObject);
	}

	public static slm.proxies.SPAttribute load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return slm.proxies.SPAttribute.initialize(context, mendixObject);
	}

	public static java.util.List<slm.proxies.SPAttribute> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<slm.proxies.SPAttribute> result = new java.util.ArrayList<slm.proxies.SPAttribute>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//SLM.SPAttribute" + xpathConstraint))
			result.add(slm.proxies.SPAttribute.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of CODE
	 */
	public final java.lang.String getCODE()
	{
		return getCODE(getContext());
	}

	/**
	 * @param context
	 * @return value of CODE
	 */
	public final java.lang.String getCODE(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CODE.toString());
	}

	/**
	 * Set value of CODE
	 * @param code
	 */
	public final void setCODE(java.lang.String code)
	{
		setCODE(getContext(), code);
	}

	/**
	 * Set value of CODE
	 * @param context
	 * @param code
	 */
	public final void setCODE(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String code)
	{
		getMendixObject().setValue(context, MemberNames.CODE.toString(), code);
	}

	/**
	 * Set value of FieldType
	 * @param fieldtype
	 */
	public final slm.proxies.AttributeTypeEnum getFieldType()
	{
		return getFieldType(getContext());
	}

	/**
	 * @param context
	 * @return value of FieldType
	 */
	public final slm.proxies.AttributeTypeEnum getFieldType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.FieldType.toString());
		if (obj == null)
			return null;

		return slm.proxies.AttributeTypeEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of FieldType
	 * @param fieldtype
	 */
	public final void setFieldType(slm.proxies.AttributeTypeEnum fieldtype)
	{
		setFieldType(getContext(), fieldtype);
	}

	/**
	 * Set value of FieldType
	 * @param context
	 * @param fieldtype
	 */
	public final void setFieldType(com.mendix.systemwideinterfaces.core.IContext context, slm.proxies.AttributeTypeEnum fieldtype)
	{
		if (fieldtype != null)
			getMendixObject().setValue(context, MemberNames.FieldType.toString(), fieldtype.toString());
		else
			getMendixObject().setValue(context, MemberNames.FieldType.toString(), null);
	}

	/**
	 * @return value of Value_String
	 */
	public final java.lang.String getValue_String()
	{
		return getValue_String(getContext());
	}

	/**
	 * @param context
	 * @return value of Value_String
	 */
	public final java.lang.String getValue_String(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value_String.toString());
	}

	/**
	 * Set value of Value_String
	 * @param value_string
	 */
	public final void setValue_String(java.lang.String value_string)
	{
		setValue_String(getContext(), value_string);
	}

	/**
	 * Set value of Value_String
	 * @param context
	 * @param value_string
	 */
	public final void setValue_String(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value_string)
	{
		getMendixObject().setValue(context, MemberNames.Value_String.toString(), value_string);
	}

	/**
	 * @return value of Value_StringLong
	 */
	public final java.lang.String getValue_StringLong()
	{
		return getValue_StringLong(getContext());
	}

	/**
	 * @param context
	 * @return value of Value_StringLong
	 */
	public final java.lang.String getValue_StringLong(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value_StringLong.toString());
	}

	/**
	 * Set value of Value_StringLong
	 * @param value_stringlong
	 */
	public final void setValue_StringLong(java.lang.String value_stringlong)
	{
		setValue_StringLong(getContext(), value_stringlong);
	}

	/**
	 * Set value of Value_StringLong
	 * @param context
	 * @param value_stringlong
	 */
	public final void setValue_StringLong(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value_stringlong)
	{
		getMendixObject().setValue(context, MemberNames.Value_StringLong.toString(), value_stringlong);
	}

	/**
	 * @return value of Value_Integer
	 */
	public final java.lang.Integer getValue_Integer()
	{
		return getValue_Integer(getContext());
	}

	/**
	 * @param context
	 * @return value of Value_Integer
	 */
	public final java.lang.Integer getValue_Integer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Value_Integer.toString());
	}

	/**
	 * Set value of Value_Integer
	 * @param value_integer
	 */
	public final void setValue_Integer(java.lang.Integer value_integer)
	{
		setValue_Integer(getContext(), value_integer);
	}

	/**
	 * Set value of Value_Integer
	 * @param context
	 * @param value_integer
	 */
	public final void setValue_Integer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer value_integer)
	{
		getMendixObject().setValue(context, MemberNames.Value_Integer.toString(), value_integer);
	}

	/**
	 * @return value of Value_Float
	 */
	public final java.lang.Double getValue_Float()
	{
		return getValue_Float(getContext());
	}

	/**
	 * @param context
	 * @return value of Value_Float
	 */
	public final java.lang.Double getValue_Float(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Double) getMendixObject().getValue(context, MemberNames.Value_Float.toString());
	}

	/**
	 * Set value of Value_Float
	 * @param value_float
	 */
	public final void setValue_Float(java.lang.Double value_float)
	{
		setValue_Float(getContext(), value_float);
	}

	/**
	 * Set value of Value_Float
	 * @param context
	 * @param value_float
	 */
	public final void setValue_Float(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Double value_float)
	{
		getMendixObject().setValue(context, MemberNames.Value_Float.toString(), value_float);
	}

	/**
	 * @return value of Value_DateTime
	 */
	public final java.util.Date getValue_DateTime()
	{
		return getValue_DateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of Value_DateTime
	 */
	public final java.util.Date getValue_DateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Value_DateTime.toString());
	}

	/**
	 * Set value of Value_DateTime
	 * @param value_datetime
	 */
	public final void setValue_DateTime(java.util.Date value_datetime)
	{
		setValue_DateTime(getContext(), value_datetime);
	}

	/**
	 * Set value of Value_DateTime
	 * @param context
	 * @param value_datetime
	 */
	public final void setValue_DateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date value_datetime)
	{
		getMendixObject().setValue(context, MemberNames.Value_DateTime.toString(), value_datetime);
	}

	/**
	 * @return value of Value_Date
	 */
	public final java.util.Date getValue_Date()
	{
		return getValue_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Value_Date
	 */
	public final java.util.Date getValue_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Value_Date.toString());
	}

	/**
	 * Set value of Value_Date
	 * @param value_date
	 */
	public final void setValue_Date(java.util.Date value_date)
	{
		setValue_Date(getContext(), value_date);
	}

	/**
	 * Set value of Value_Date
	 * @param context
	 * @param value_date
	 */
	public final void setValue_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date value_date)
	{
		getMendixObject().setValue(context, MemberNames.Value_Date.toString(), value_date);
	}

	/**
	 * @return value of Value_Boolean
	 */
	public final java.lang.Boolean getValue_Boolean()
	{
		return getValue_Boolean(getContext());
	}

	/**
	 * @param context
	 * @return value of Value_Boolean
	 */
	public final java.lang.Boolean getValue_Boolean(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Value_Boolean.toString());
	}

	/**
	 * Set value of Value_Boolean
	 * @param value_boolean
	 */
	public final void setValue_Boolean(java.lang.Boolean value_boolean)
	{
		setValue_Boolean(getContext(), value_boolean);
	}

	/**
	 * Set value of Value_Boolean
	 * @param context
	 * @param value_boolean
	 */
	public final void setValue_Boolean(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean value_boolean)
	{
		getMendixObject().setValue(context, MemberNames.Value_Boolean.toString(), value_boolean);
	}

	/**
	 * @return value of Value_Currency
	 */
	public final java.math.BigDecimal getValue_Currency()
	{
		return getValue_Currency(getContext());
	}

	/**
	 * @param context
	 * @return value of Value_Currency
	 */
	public final java.math.BigDecimal getValue_Currency(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Value_Currency.toString());
	}

	/**
	 * Set value of Value_Currency
	 * @param value_currency
	 */
	public final void setValue_Currency(java.math.BigDecimal value_currency)
	{
		setValue_Currency(getContext(), value_currency);
	}

	/**
	 * Set value of Value_Currency
	 * @param context
	 * @param value_currency
	 */
	public final void setValue_Currency(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal value_currency)
	{
		getMendixObject().setValue(context, MemberNames.Value_Currency.toString(), value_currency);
	}

	/**
	 * @return value of ImportExport_Value
	 */
	public final java.lang.String getImportExport_Value()
	{
		return getImportExport_Value(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportExport_Value
	 */
	public final java.lang.String getImportExport_Value(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ImportExport_Value.toString());
	}

	/**
	 * Set value of ImportExport_Value
	 * @param importexport_value
	 */
	public final void setImportExport_Value(java.lang.String importexport_value)
	{
		setImportExport_Value(getContext(), importexport_value);
	}

	/**
	 * Set value of ImportExport_Value
	 * @param context
	 * @param importexport_value
	 */
	public final void setImportExport_Value(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String importexport_value)
	{
		getMendixObject().setValue(context, MemberNames.ImportExport_Value.toString(), importexport_value);
	}

	/**
	 * @return value of RequireOnCreate
	 */
	public final java.lang.Boolean getRequireOnCreate()
	{
		return getRequireOnCreate(getContext());
	}

	/**
	 * @param context
	 * @return value of RequireOnCreate
	 */
	public final java.lang.Boolean getRequireOnCreate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.RequireOnCreate.toString());
	}

	/**
	 * Set value of RequireOnCreate
	 * @param requireoncreate
	 */
	public final void setRequireOnCreate(java.lang.Boolean requireoncreate)
	{
		setRequireOnCreate(getContext(), requireoncreate);
	}

	/**
	 * Set value of RequireOnCreate
	 * @param context
	 * @param requireoncreate
	 */
	public final void setRequireOnCreate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean requireoncreate)
	{
		getMendixObject().setValue(context, MemberNames.RequireOnCreate.toString(), requireoncreate);
	}

	/**
	 * @return value of RequireOnSolve
	 */
	public final java.lang.Boolean getRequireOnSolve()
	{
		return getRequireOnSolve(getContext());
	}

	/**
	 * @param context
	 * @return value of RequireOnSolve
	 */
	public final java.lang.Boolean getRequireOnSolve(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.RequireOnSolve.toString());
	}

	/**
	 * Set value of RequireOnSolve
	 * @param requireonsolve
	 */
	public final void setRequireOnSolve(java.lang.Boolean requireonsolve)
	{
		setRequireOnSolve(getContext(), requireonsolve);
	}

	/**
	 * Set value of RequireOnSolve
	 * @param context
	 * @param requireonsolve
	 */
	public final void setRequireOnSolve(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean requireonsolve)
	{
		getMendixObject().setValue(context, MemberNames.RequireOnSolve.toString(), requireonsolve);
	}

	/**
	 * @return value of RequireOnClose
	 */
	public final java.lang.Boolean getRequireOnClose()
	{
		return getRequireOnClose(getContext());
	}

	/**
	 * @param context
	 * @return value of RequireOnClose
	 */
	public final java.lang.Boolean getRequireOnClose(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.RequireOnClose.toString());
	}

	/**
	 * Set value of RequireOnClose
	 * @param requireonclose
	 */
	public final void setRequireOnClose(java.lang.Boolean requireonclose)
	{
		setRequireOnClose(getContext(), requireonclose);
	}

	/**
	 * Set value of RequireOnClose
	 * @param context
	 * @param requireonclose
	 */
	public final void setRequireOnClose(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean requireonclose)
	{
		getMendixObject().setValue(context, MemberNames.RequireOnClose.toString(), requireonclose);
	}

	/**
	 * @return value of IsImport
	 */
	public final java.lang.Boolean getIsImport()
	{
		return getIsImport(getContext());
	}

	/**
	 * @param context
	 * @return value of IsImport
	 */
	public final java.lang.Boolean getIsImport(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsImport.toString());
	}

	/**
	 * Set value of IsImport
	 * @param isimport
	 */
	public final void setIsImport(java.lang.Boolean isimport)
	{
		setIsImport(getContext(), isimport);
	}

	/**
	 * Set value of IsImport
	 * @param context
	 * @param isimport
	 */
	public final void setIsImport(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isimport)
	{
		getMendixObject().setValue(context, MemberNames.IsImport.toString(), isimport);
	}

	/**
	 * @return value of SPAttribute_SPScreenBlock
	 */
	public final slm.proxies.SPScreenBlock getSPAttribute_SPScreenBlock() throws com.mendix.core.CoreException
	{
		return getSPAttribute_SPScreenBlock(getContext());
	}

	/**
	 * @param context
	 * @return value of SPAttribute_SPScreenBlock
	 */
	public final slm.proxies.SPScreenBlock getSPAttribute_SPScreenBlock(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		slm.proxies.SPScreenBlock result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SPAttribute_SPScreenBlock.toString());
		if (identifier != null)
			result = slm.proxies.SPScreenBlock.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SPAttribute_SPScreenBlock
	 * @param spattribute_spscreenblock
	 */
	public final void setSPAttribute_SPScreenBlock(slm.proxies.SPScreenBlock spattribute_spscreenblock)
	{
		setSPAttribute_SPScreenBlock(getContext(), spattribute_spscreenblock);
	}

	/**
	 * Set value of SPAttribute_SPScreenBlock
	 * @param context
	 * @param spattribute_spscreenblock
	 */
	public final void setSPAttribute_SPScreenBlock(com.mendix.systemwideinterfaces.core.IContext context, slm.proxies.SPScreenBlock spattribute_spscreenblock)
	{
		if (spattribute_spscreenblock == null)
			getMendixObject().setValue(context, MemberNames.SPAttribute_SPScreenBlock.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SPAttribute_SPScreenBlock.toString(), spattribute_spscreenblock.getMendixObject().getId());
	}

	/**
	 * @return value of SPAttribute_SPAttributeValue_SelectedDropDown
	 */
	public final slm.proxies.SPAttributeValue getSPAttribute_SPAttributeValue_SelectedDropDown() throws com.mendix.core.CoreException
	{
		return getSPAttribute_SPAttributeValue_SelectedDropDown(getContext());
	}

	/**
	 * @param context
	 * @return value of SPAttribute_SPAttributeValue_SelectedDropDown
	 */
	public final slm.proxies.SPAttributeValue getSPAttribute_SPAttributeValue_SelectedDropDown(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		slm.proxies.SPAttributeValue result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SPAttribute_SPAttributeValue_SelectedDropDown.toString());
		if (identifier != null)
			result = slm.proxies.SPAttributeValue.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SPAttribute_SPAttributeValue_SelectedDropDown
	 * @param spattribute_spattributevalue_selecteddropdown
	 */
	public final void setSPAttribute_SPAttributeValue_SelectedDropDown(slm.proxies.SPAttributeValue spattribute_spattributevalue_selecteddropdown)
	{
		setSPAttribute_SPAttributeValue_SelectedDropDown(getContext(), spattribute_spattributevalue_selecteddropdown);
	}

	/**
	 * Set value of SPAttribute_SPAttributeValue_SelectedDropDown
	 * @param context
	 * @param spattribute_spattributevalue_selecteddropdown
	 */
	public final void setSPAttribute_SPAttributeValue_SelectedDropDown(com.mendix.systemwideinterfaces.core.IContext context, slm.proxies.SPAttributeValue spattribute_spattributevalue_selecteddropdown)
	{
		if (spattribute_spattributevalue_selecteddropdown == null)
			getMendixObject().setValue(context, MemberNames.SPAttribute_SPAttributeValue_SelectedDropDown.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SPAttribute_SPAttributeValue_SelectedDropDown.toString(), spattribute_spattributevalue_selecteddropdown.getMendixObject().getId());
	}

	/**
	 * @return value of SPAttribute_SPAttributeValue_SelectedRadio
	 */
	public final slm.proxies.SPAttributeValue getSPAttribute_SPAttributeValue_SelectedRadio() throws com.mendix.core.CoreException
	{
		return getSPAttribute_SPAttributeValue_SelectedRadio(getContext());
	}

	/**
	 * @param context
	 * @return value of SPAttribute_SPAttributeValue_SelectedRadio
	 */
	public final slm.proxies.SPAttributeValue getSPAttribute_SPAttributeValue_SelectedRadio(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		slm.proxies.SPAttributeValue result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SPAttribute_SPAttributeValue_SelectedRadio.toString());
		if (identifier != null)
			result = slm.proxies.SPAttributeValue.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SPAttribute_SPAttributeValue_SelectedRadio
	 * @param spattribute_spattributevalue_selectedradio
	 */
	public final void setSPAttribute_SPAttributeValue_SelectedRadio(slm.proxies.SPAttributeValue spattribute_spattributevalue_selectedradio)
	{
		setSPAttribute_SPAttributeValue_SelectedRadio(getContext(), spattribute_spattributevalue_selectedradio);
	}

	/**
	 * Set value of SPAttribute_SPAttributeValue_SelectedRadio
	 * @param context
	 * @param spattribute_spattributevalue_selectedradio
	 */
	public final void setSPAttribute_SPAttributeValue_SelectedRadio(com.mendix.systemwideinterfaces.core.IContext context, slm.proxies.SPAttributeValue spattribute_spattributevalue_selectedradio)
	{
		if (spattribute_spattributevalue_selectedradio == null)
			getMendixObject().setValue(context, MemberNames.SPAttribute_SPAttributeValue_SelectedRadio.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SPAttribute_SPAttributeValue_SelectedRadio.toString(), spattribute_spattributevalue_selectedradio.getMendixObject().getId());
	}

	/**
	 * @return value of SPAttribute_SPDefinitionAttribute
	 */
	public final slm.proxies.SPDefinitionAttribute getSPAttribute_SPDefinitionAttribute() throws com.mendix.core.CoreException
	{
		return getSPAttribute_SPDefinitionAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of SPAttribute_SPDefinitionAttribute
	 */
	public final slm.proxies.SPDefinitionAttribute getSPAttribute_SPDefinitionAttribute(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		slm.proxies.SPDefinitionAttribute result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SPAttribute_SPDefinitionAttribute.toString());
		if (identifier != null)
			result = slm.proxies.SPDefinitionAttribute.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SPAttribute_SPDefinitionAttribute
	 * @param spattribute_spdefinitionattribute
	 */
	public final void setSPAttribute_SPDefinitionAttribute(slm.proxies.SPDefinitionAttribute spattribute_spdefinitionattribute)
	{
		setSPAttribute_SPDefinitionAttribute(getContext(), spattribute_spdefinitionattribute);
	}

	/**
	 * Set value of SPAttribute_SPDefinitionAttribute
	 * @param context
	 * @param spattribute_spdefinitionattribute
	 */
	public final void setSPAttribute_SPDefinitionAttribute(com.mendix.systemwideinterfaces.core.IContext context, slm.proxies.SPDefinitionAttribute spattribute_spdefinitionattribute)
	{
		if (spattribute_spdefinitionattribute == null)
			getMendixObject().setValue(context, MemberNames.SPAttribute_SPDefinitionAttribute.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SPAttribute_SPDefinitionAttribute.toString(), spattribute_spdefinitionattribute.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sPAttributeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final slm.proxies.SPAttribute that = (slm.proxies.SPAttribute) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SLM.SPAttribute";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
