// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package scheduling.proxies;

public enum ScheduleOnDays
{
	Day(new java.lang.String[][] { new java.lang.String[] { "en_US", "Day" }, new java.lang.String[] { "nl_NL", "Dag" }, new java.lang.String[] { "de_DE", "Tag " } }),
	Weekday(new java.lang.String[][] { new java.lang.String[] { "en_US", "Weekday" }, new java.lang.String[] { "nl_NL", "Weekdag " }, new java.lang.String[] { "de_DE", "Wochentag" } }),
	WeekendDay(new java.lang.String[][] { new java.lang.String[] { "en_US", "Weekendday" }, new java.lang.String[] { "nl_NL", "Weekenddag" }, new java.lang.String[] { "de_DE", "Wochenendtag" } }),
	Monday(new java.lang.String[][] { new java.lang.String[] { "en_US", "Monday" }, new java.lang.String[] { "nl_NL", "Maandag" }, new java.lang.String[] { "de_DE", "Montag" } }),
	Tuesday(new java.lang.String[][] { new java.lang.String[] { "en_US", "Tuesday" }, new java.lang.String[] { "nl_NL", "Dinsdag" }, new java.lang.String[] { "de_DE", "Dienstag" } }),
	Wednesday(new java.lang.String[][] { new java.lang.String[] { "en_US", "Wednesday" }, new java.lang.String[] { "nl_NL", "Woensdag  " }, new java.lang.String[] { "de_DE", "Mittwoch" } }),
	Thursday(new java.lang.String[][] { new java.lang.String[] { "en_US", "Thursday" }, new java.lang.String[] { "nl_NL", "Donderdag" }, new java.lang.String[] { "de_DE", "Donnerstag" } }),
	Friday(new java.lang.String[][] { new java.lang.String[] { "en_US", "Friday" }, new java.lang.String[] { "nl_NL", "Vrijdag" }, new java.lang.String[] { "de_DE", "Freitag" } }),
	Saturday(new java.lang.String[][] { new java.lang.String[] { "en_US", "Saturday" }, new java.lang.String[] { "nl_NL", "Zaterdag" }, new java.lang.String[] { "de_DE", "Samstag" } }),
	Sunday(new java.lang.String[][] { new java.lang.String[] { "en_US", "Sunday" }, new java.lang.String[] { "nl_NL", "Zondag" }, new java.lang.String[] { "de_DE", "Sonntag" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private ScheduleOnDays(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
