// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package notes.proxies;

/**
 * User is a string because the information is historic and you neither want to prevent deletion of a person, nor do you want a cascaded delete to a note.
 */
public class Note
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject noteMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Notes.Note";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NoteText("NoteText"),
		NoteTextShort("NoteTextShort"),
		User("User"),
		Date("Date"),
		NoteType("NoteType"),
		PublicAvailable("PublicAvailable"),
		SearchNoteTypeTicketTask("SearchNoteTypeTicketTask"),
		InterfaceGUID("InterfaceGUID"),
		CreatedExternally("CreatedExternally"),
		Note_Note("InterfaceNotes.Note_Note"),
		Note_Request("Notes.Note_Request"),
		Note_Task("Notes.Note_Task"),
		Note_ConfigurationItem("Notes.Note_ConfigurationItem"),
		Note_InitiatingInterfaceConfiguration("Notes.Note_InitiatingInterfaceConfiguration"),
		Note_TempEventInitiatingProcessingAttempt("Notes.Note_TempEventInitiatingProcessingAttempt"),
		ActivityStream_Note("Process.ActivityStream_Note");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Note(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Notes.Note"));
	}

	protected Note(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject noteMendixObject)
	{
		if (noteMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Notes.Note", noteMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Notes.Note");

		this.noteMendixObject = noteMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Note.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static notes.proxies.Note initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return notes.proxies.Note.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static notes.proxies.Note initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new notes.proxies.Note(context, mendixObject);
	}

	public static notes.proxies.Note load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return notes.proxies.Note.initialize(context, mendixObject);
	}

	public static java.util.List<notes.proxies.Note> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<notes.proxies.Note> result = new java.util.ArrayList<notes.proxies.Note>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Notes.Note" + xpathConstraint))
			result.add(notes.proxies.Note.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of NoteText
	 */
	public final java.lang.String getNoteText()
	{
		return getNoteText(getContext());
	}

	/**
	 * @param context
	 * @return value of NoteText
	 */
	public final java.lang.String getNoteText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NoteText.toString());
	}

	/**
	 * Set value of NoteText
	 * @param notetext
	 */
	public final void setNoteText(java.lang.String notetext)
	{
		setNoteText(getContext(), notetext);
	}

	/**
	 * Set value of NoteText
	 * @param context
	 * @param notetext
	 */
	public final void setNoteText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String notetext)
	{
		getMendixObject().setValue(context, MemberNames.NoteText.toString(), notetext);
	}

	/**
	 * @return value of NoteTextShort
	 */
	public final java.lang.String getNoteTextShort()
	{
		return getNoteTextShort(getContext());
	}

	/**
	 * @param context
	 * @return value of NoteTextShort
	 */
	public final java.lang.String getNoteTextShort(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NoteTextShort.toString());
	}

	/**
	 * Set value of NoteTextShort
	 * @param notetextshort
	 */
	public final void setNoteTextShort(java.lang.String notetextshort)
	{
		setNoteTextShort(getContext(), notetextshort);
	}

	/**
	 * Set value of NoteTextShort
	 * @param context
	 * @param notetextshort
	 */
	public final void setNoteTextShort(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String notetextshort)
	{
		getMendixObject().setValue(context, MemberNames.NoteTextShort.toString(), notetextshort);
	}

	/**
	 * @return value of User
	 */
	public final java.lang.String getUser()
	{
		return getUser(getContext());
	}

	/**
	 * @param context
	 * @return value of User
	 */
	public final java.lang.String getUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.User.toString());
	}

	/**
	 * Set value of User
	 * @param user
	 */
	public final void setUser(java.lang.String user)
	{
		setUser(getContext(), user);
	}

	/**
	 * Set value of User
	 * @param context
	 * @param user
	 */
	public final void setUser(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String user)
	{
		getMendixObject().setValue(context, MemberNames.User.toString(), user);
	}

	/**
	 * @return value of Date
	 */
	public final java.util.Date getDate()
	{
		return getDate(getContext());
	}

	/**
	 * @param context
	 * @return value of Date
	 */
	public final java.util.Date getDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date.toString());
	}

	/**
	 * Set value of Date
	 * @param date
	 */
	public final void setDate(java.util.Date date)
	{
		setDate(getContext(), date);
	}

	/**
	 * Set value of Date
	 * @param context
	 * @param date
	 */
	public final void setDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date)
	{
		getMendixObject().setValue(context, MemberNames.Date.toString(), date);
	}

	/**
	 * Set value of NoteType
	 * @param notetype
	 */
	public final notes.proxies.NoteType getNoteType()
	{
		return getNoteType(getContext());
	}

	/**
	 * @param context
	 * @return value of NoteType
	 */
	public final notes.proxies.NoteType getNoteType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.NoteType.toString());
		if (obj == null)
			return null;

		return notes.proxies.NoteType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of NoteType
	 * @param notetype
	 */
	public final void setNoteType(notes.proxies.NoteType notetype)
	{
		setNoteType(getContext(), notetype);
	}

	/**
	 * Set value of NoteType
	 * @param context
	 * @param notetype
	 */
	public final void setNoteType(com.mendix.systemwideinterfaces.core.IContext context, notes.proxies.NoteType notetype)
	{
		if (notetype != null)
			getMendixObject().setValue(context, MemberNames.NoteType.toString(), notetype.toString());
		else
			getMendixObject().setValue(context, MemberNames.NoteType.toString(), null);
	}

	/**
	 * @return value of PublicAvailable
	 */
	public final java.lang.Boolean getPublicAvailable()
	{
		return getPublicAvailable(getContext());
	}

	/**
	 * @param context
	 * @return value of PublicAvailable
	 */
	public final java.lang.Boolean getPublicAvailable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.PublicAvailable.toString());
	}

	/**
	 * Set value of PublicAvailable
	 * @param publicavailable
	 */
	public final void setPublicAvailable(java.lang.Boolean publicavailable)
	{
		setPublicAvailable(getContext(), publicavailable);
	}

	/**
	 * Set value of PublicAvailable
	 * @param context
	 * @param publicavailable
	 */
	public final void setPublicAvailable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean publicavailable)
	{
		getMendixObject().setValue(context, MemberNames.PublicAvailable.toString(), publicavailable);
	}

	/**
	 * Set value of SearchNoteTypeTicketTask
	 * @param searchnotetypetickettask
	 */
	public final notes.proxies.NoteType_TicketTask getSearchNoteTypeTicketTask()
	{
		return getSearchNoteTypeTicketTask(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchNoteTypeTicketTask
	 */
	public final notes.proxies.NoteType_TicketTask getSearchNoteTypeTicketTask(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SearchNoteTypeTicketTask.toString());
		if (obj == null)
			return null;

		return notes.proxies.NoteType_TicketTask.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of SearchNoteTypeTicketTask
	 * @param searchnotetypetickettask
	 */
	public final void setSearchNoteTypeTicketTask(notes.proxies.NoteType_TicketTask searchnotetypetickettask)
	{
		setSearchNoteTypeTicketTask(getContext(), searchnotetypetickettask);
	}

	/**
	 * Set value of SearchNoteTypeTicketTask
	 * @param context
	 * @param searchnotetypetickettask
	 */
	public final void setSearchNoteTypeTicketTask(com.mendix.systemwideinterfaces.core.IContext context, notes.proxies.NoteType_TicketTask searchnotetypetickettask)
	{
		if (searchnotetypetickettask != null)
			getMendixObject().setValue(context, MemberNames.SearchNoteTypeTicketTask.toString(), searchnotetypetickettask.toString());
		else
			getMendixObject().setValue(context, MemberNames.SearchNoteTypeTicketTask.toString(), null);
	}

	/**
	 * @return value of InterfaceGUID
	 */
	public final java.lang.String getInterfaceGUID()
	{
		return getInterfaceGUID(getContext());
	}

	/**
	 * @param context
	 * @return value of InterfaceGUID
	 */
	public final java.lang.String getInterfaceGUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InterfaceGUID.toString());
	}

	/**
	 * Set value of InterfaceGUID
	 * @param interfaceguid
	 */
	public final void setInterfaceGUID(java.lang.String interfaceguid)
	{
		setInterfaceGUID(getContext(), interfaceguid);
	}

	/**
	 * Set value of InterfaceGUID
	 * @param context
	 * @param interfaceguid
	 */
	public final void setInterfaceGUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String interfaceguid)
	{
		getMendixObject().setValue(context, MemberNames.InterfaceGUID.toString(), interfaceguid);
	}

	/**
	 * @return value of CreatedExternally
	 */
	public final java.lang.Boolean getCreatedExternally()
	{
		return getCreatedExternally(getContext());
	}

	/**
	 * @param context
	 * @return value of CreatedExternally
	 */
	public final java.lang.Boolean getCreatedExternally(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CreatedExternally.toString());
	}

	/**
	 * Set value of CreatedExternally
	 * @param createdexternally
	 */
	public final void setCreatedExternally(java.lang.Boolean createdexternally)
	{
		setCreatedExternally(getContext(), createdexternally);
	}

	/**
	 * Set value of CreatedExternally
	 * @param context
	 * @param createdexternally
	 */
	public final void setCreatedExternally(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean createdexternally)
	{
		getMendixObject().setValue(context, MemberNames.CreatedExternally.toString(), createdexternally);
	}

	/**
	 * @return value of Note_Note
	 */
	public final interfacenotes.proxies.Note getNote_Note() throws com.mendix.core.CoreException
	{
		return getNote_Note(getContext());
	}

	/**
	 * @param context
	 * @return value of Note_Note
	 */
	public final interfacenotes.proxies.Note getNote_Note(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacenotes.proxies.Note result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Note_Note.toString());
		if (identifier != null)
			result = interfacenotes.proxies.Note.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Note_Note
	 * @param note_note
	 */
	public final void setNote_Note(interfacenotes.proxies.Note note_note)
	{
		setNote_Note(getContext(), note_note);
	}

	/**
	 * Set value of Note_Note
	 * @param context
	 * @param note_note
	 */
	public final void setNote_Note(com.mendix.systemwideinterfaces.core.IContext context, interfacenotes.proxies.Note note_note)
	{
		if (note_note == null)
			getMendixObject().setValue(context, MemberNames.Note_Note.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Note_Note.toString(), note_note.getMendixObject().getId());
	}

	/**
	 * @return value of Note_Request
	 */
	public final process.proxies.Request getNote_Request() throws com.mendix.core.CoreException
	{
		return getNote_Request(getContext());
	}

	/**
	 * @param context
	 * @return value of Note_Request
	 */
	public final process.proxies.Request getNote_Request(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		process.proxies.Request result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Note_Request.toString());
		if (identifier != null)
			result = process.proxies.Request.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Note_Request
	 * @param note_request
	 */
	public final void setNote_Request(process.proxies.Request note_request)
	{
		setNote_Request(getContext(), note_request);
	}

	/**
	 * Set value of Note_Request
	 * @param context
	 * @param note_request
	 */
	public final void setNote_Request(com.mendix.systemwideinterfaces.core.IContext context, process.proxies.Request note_request)
	{
		if (note_request == null)
			getMendixObject().setValue(context, MemberNames.Note_Request.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Note_Request.toString(), note_request.getMendixObject().getId());
	}

	/**
	 * @return value of Note_Task
	 */
	public final process.proxies.Task getNote_Task() throws com.mendix.core.CoreException
	{
		return getNote_Task(getContext());
	}

	/**
	 * @param context
	 * @return value of Note_Task
	 */
	public final process.proxies.Task getNote_Task(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		process.proxies.Task result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Note_Task.toString());
		if (identifier != null)
			result = process.proxies.Task.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Note_Task
	 * @param note_task
	 */
	public final void setNote_Task(process.proxies.Task note_task)
	{
		setNote_Task(getContext(), note_task);
	}

	/**
	 * Set value of Note_Task
	 * @param context
	 * @param note_task
	 */
	public final void setNote_Task(com.mendix.systemwideinterfaces.core.IContext context, process.proxies.Task note_task)
	{
		if (note_task == null)
			getMendixObject().setValue(context, MemberNames.Note_Task.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Note_Task.toString(), note_task.getMendixObject().getId());
	}

	/**
	 * @return value of Note_ConfigurationItem
	 */
	public final cmdb.proxies.ConfigurationItem getNote_ConfigurationItem() throws com.mendix.core.CoreException
	{
		return getNote_ConfigurationItem(getContext());
	}

	/**
	 * @param context
	 * @return value of Note_ConfigurationItem
	 */
	public final cmdb.proxies.ConfigurationItem getNote_ConfigurationItem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmdb.proxies.ConfigurationItem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Note_ConfigurationItem.toString());
		if (identifier != null)
			result = cmdb.proxies.ConfigurationItem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Note_ConfigurationItem
	 * @param note_configurationitem
	 */
	public final void setNote_ConfigurationItem(cmdb.proxies.ConfigurationItem note_configurationitem)
	{
		setNote_ConfigurationItem(getContext(), note_configurationitem);
	}

	/**
	 * Set value of Note_ConfigurationItem
	 * @param context
	 * @param note_configurationitem
	 */
	public final void setNote_ConfigurationItem(com.mendix.systemwideinterfaces.core.IContext context, cmdb.proxies.ConfigurationItem note_configurationitem)
	{
		if (note_configurationitem == null)
			getMendixObject().setValue(context, MemberNames.Note_ConfigurationItem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Note_ConfigurationItem.toString(), note_configurationitem.getMendixObject().getId());
	}

	/**
	 * @return value of Note_InitiatingInterfaceConfiguration
	 */
	public final interfaceconfiguration.proxies.InterfaceConfiguration getNote_InitiatingInterfaceConfiguration() throws com.mendix.core.CoreException
	{
		return getNote_InitiatingInterfaceConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of Note_InitiatingInterfaceConfiguration
	 */
	public final interfaceconfiguration.proxies.InterfaceConfiguration getNote_InitiatingInterfaceConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceconfiguration.proxies.InterfaceConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Note_InitiatingInterfaceConfiguration.toString());
		if (identifier != null)
			result = interfaceconfiguration.proxies.InterfaceConfiguration.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Note_InitiatingInterfaceConfiguration
	 * @param note_initiatinginterfaceconfiguration
	 */
	public final void setNote_InitiatingInterfaceConfiguration(interfaceconfiguration.proxies.InterfaceConfiguration note_initiatinginterfaceconfiguration)
	{
		setNote_InitiatingInterfaceConfiguration(getContext(), note_initiatinginterfaceconfiguration);
	}

	/**
	 * Set value of Note_InitiatingInterfaceConfiguration
	 * @param context
	 * @param note_initiatinginterfaceconfiguration
	 */
	public final void setNote_InitiatingInterfaceConfiguration(com.mendix.systemwideinterfaces.core.IContext context, interfaceconfiguration.proxies.InterfaceConfiguration note_initiatinginterfaceconfiguration)
	{
		if (note_initiatinginterfaceconfiguration == null)
			getMendixObject().setValue(context, MemberNames.Note_InitiatingInterfaceConfiguration.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Note_InitiatingInterfaceConfiguration.toString(), note_initiatinginterfaceconfiguration.getMendixObject().getId());
	}

	/**
	 * @return value of Note_TempEventInitiatingProcessingAttempt
	 */
	public final interfaceshared.proxies.ProcessingAttempt getNote_TempEventInitiatingProcessingAttempt() throws com.mendix.core.CoreException
	{
		return getNote_TempEventInitiatingProcessingAttempt(getContext());
	}

	/**
	 * @param context
	 * @return value of Note_TempEventInitiatingProcessingAttempt
	 */
	public final interfaceshared.proxies.ProcessingAttempt getNote_TempEventInitiatingProcessingAttempt(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceshared.proxies.ProcessingAttempt result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Note_TempEventInitiatingProcessingAttempt.toString());
		if (identifier != null)
			result = interfaceshared.proxies.ProcessingAttempt.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Note_TempEventInitiatingProcessingAttempt
	 * @param note_tempeventinitiatingprocessingattempt
	 */
	public final void setNote_TempEventInitiatingProcessingAttempt(interfaceshared.proxies.ProcessingAttempt note_tempeventinitiatingprocessingattempt)
	{
		setNote_TempEventInitiatingProcessingAttempt(getContext(), note_tempeventinitiatingprocessingattempt);
	}

	/**
	 * Set value of Note_TempEventInitiatingProcessingAttempt
	 * @param context
	 * @param note_tempeventinitiatingprocessingattempt
	 */
	public final void setNote_TempEventInitiatingProcessingAttempt(com.mendix.systemwideinterfaces.core.IContext context, interfaceshared.proxies.ProcessingAttempt note_tempeventinitiatingprocessingattempt)
	{
		if (note_tempeventinitiatingprocessingattempt == null)
			getMendixObject().setValue(context, MemberNames.Note_TempEventInitiatingProcessingAttempt.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Note_TempEventInitiatingProcessingAttempt.toString(), note_tempeventinitiatingprocessingattempt.getMendixObject().getId());
	}

	/**
	 * @return value of ActivityStream_Note
	 */
	public final process.proxies.ActivityStream getActivityStream_Note() throws com.mendix.core.CoreException
	{
		return getActivityStream_Note(getContext());
	}

	/**
	 * @param context
	 * @return value of ActivityStream_Note
	 */
	public final process.proxies.ActivityStream getActivityStream_Note(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		process.proxies.ActivityStream result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ActivityStream_Note.toString());
		if (identifier != null)
			result = process.proxies.ActivityStream.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ActivityStream_Note
	 * @param activitystream_note
	 */
	public final void setActivityStream_Note(process.proxies.ActivityStream activitystream_note)
	{
		setActivityStream_Note(getContext(), activitystream_note);
	}

	/**
	 * Set value of ActivityStream_Note
	 * @param context
	 * @param activitystream_note
	 */
	public final void setActivityStream_Note(com.mendix.systemwideinterfaces.core.IContext context, process.proxies.ActivityStream activitystream_note)
	{
		if (activitystream_note == null)
			getMendixObject().setValue(context, MemberNames.ActivityStream_Note.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ActivityStream_Note.toString(), activitystream_note.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return noteMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final notes.proxies.Note that = (notes.proxies.Note) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Notes.Note";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
