// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fusionchartsplus.proxies;

/**
 * Divisional Lines are horizontal or vertical lines running through the canvas. Each divisional line signfies a smaller unit of the entire axis thus aiding the users in interpreting the chart.
 */
public class DivisionalLines
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject divisionalLinesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "FusionChartsPlus.DivisionalLines";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		numdivLines("numdivLines"),
		divlinecolor("divlinecolor"),
		divLineThickness("divLineThickness"),
		divLineAlpha("divLineAlpha"),
		showDivLineValue("showDivLineValue"),
		showAlternateHGridColor("showAlternateHGridColor"),
		alternateHGridColor("alternateHGridColor"),
		alternateHGridAlpha("alternateHGridAlpha"),
		numVDivLines("numVDivLines"),
		VDivlinecolor("VDivlinecolor"),
		VDivLineThickness("VDivLineThickness"),
		VDivLineAlpha("VDivLineAlpha"),
		showAlternateVGridColor("showAlternateVGridColor"),
		alternateVGridColor("alternateVGridColor"),
		alternateVGridAlpha("alternateVGridAlpha"),
		DivisionalLines_Graph("FusionChartsPlus.DivisionalLines_Graph");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DivisionalLines(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "FusionChartsPlus.DivisionalLines"));
	}

	protected DivisionalLines(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject divisionalLinesMendixObject)
	{
		if (divisionalLinesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("FusionChartsPlus.DivisionalLines", divisionalLinesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a FusionChartsPlus.DivisionalLines");

		this.divisionalLinesMendixObject = divisionalLinesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DivisionalLines.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static fusionchartsplus.proxies.DivisionalLines initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return fusionchartsplus.proxies.DivisionalLines.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static fusionchartsplus.proxies.DivisionalLines initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fusionchartsplus.proxies.DivisionalLines(context, mendixObject);
	}

	public static fusionchartsplus.proxies.DivisionalLines load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fusionchartsplus.proxies.DivisionalLines.initialize(context, mendixObject);
	}

	public static java.util.List<fusionchartsplus.proxies.DivisionalLines> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<fusionchartsplus.proxies.DivisionalLines> result = new java.util.ArrayList<fusionchartsplus.proxies.DivisionalLines>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//FusionChartsPlus.DivisionalLines" + xpathConstraint))
			result.add(fusionchartsplus.proxies.DivisionalLines.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of numdivLines
	 */
	public final java.lang.String getnumdivLines()
	{
		return getnumdivLines(getContext());
	}

	/**
	 * @param context
	 * @return value of numdivLines
	 */
	public final java.lang.String getnumdivLines(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.numdivLines.toString());
	}

	/**
	 * Set value of numdivLines
	 * @param numdivlines
	 */
	public final void setnumdivLines(java.lang.String numdivlines)
	{
		setnumdivLines(getContext(), numdivlines);
	}

	/**
	 * Set value of numdivLines
	 * @param context
	 * @param numdivlines
	 */
	public final void setnumdivLines(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String numdivlines)
	{
		getMendixObject().setValue(context, MemberNames.numdivLines.toString(), numdivlines);
	}

	/**
	 * @return value of divlinecolor
	 */
	public final java.lang.String getdivlinecolor()
	{
		return getdivlinecolor(getContext());
	}

	/**
	 * @param context
	 * @return value of divlinecolor
	 */
	public final java.lang.String getdivlinecolor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.divlinecolor.toString());
	}

	/**
	 * Set value of divlinecolor
	 * @param divlinecolor
	 */
	public final void setdivlinecolor(java.lang.String divlinecolor)
	{
		setdivlinecolor(getContext(), divlinecolor);
	}

	/**
	 * Set value of divlinecolor
	 * @param context
	 * @param divlinecolor
	 */
	public final void setdivlinecolor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String divlinecolor)
	{
		getMendixObject().setValue(context, MemberNames.divlinecolor.toString(), divlinecolor);
	}

	/**
	 * @return value of divLineThickness
	 */
	public final java.lang.String getdivLineThickness()
	{
		return getdivLineThickness(getContext());
	}

	/**
	 * @param context
	 * @return value of divLineThickness
	 */
	public final java.lang.String getdivLineThickness(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.divLineThickness.toString());
	}

	/**
	 * Set value of divLineThickness
	 * @param divlinethickness
	 */
	public final void setdivLineThickness(java.lang.String divlinethickness)
	{
		setdivLineThickness(getContext(), divlinethickness);
	}

	/**
	 * Set value of divLineThickness
	 * @param context
	 * @param divlinethickness
	 */
	public final void setdivLineThickness(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String divlinethickness)
	{
		getMendixObject().setValue(context, MemberNames.divLineThickness.toString(), divlinethickness);
	}

	/**
	 * @return value of divLineAlpha
	 */
	public final java.lang.String getdivLineAlpha()
	{
		return getdivLineAlpha(getContext());
	}

	/**
	 * @param context
	 * @return value of divLineAlpha
	 */
	public final java.lang.String getdivLineAlpha(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.divLineAlpha.toString());
	}

	/**
	 * Set value of divLineAlpha
	 * @param divlinealpha
	 */
	public final void setdivLineAlpha(java.lang.String divlinealpha)
	{
		setdivLineAlpha(getContext(), divlinealpha);
	}

	/**
	 * Set value of divLineAlpha
	 * @param context
	 * @param divlinealpha
	 */
	public final void setdivLineAlpha(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String divlinealpha)
	{
		getMendixObject().setValue(context, MemberNames.divLineAlpha.toString(), divlinealpha);
	}

	/**
	 * @return value of showDivLineValue
	 */
	public final java.lang.Boolean getshowDivLineValue()
	{
		return getshowDivLineValue(getContext());
	}

	/**
	 * @param context
	 * @return value of showDivLineValue
	 */
	public final java.lang.Boolean getshowDivLineValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.showDivLineValue.toString());
	}

	/**
	 * Set value of showDivLineValue
	 * @param showdivlinevalue
	 */
	public final void setshowDivLineValue(java.lang.Boolean showdivlinevalue)
	{
		setshowDivLineValue(getContext(), showdivlinevalue);
	}

	/**
	 * Set value of showDivLineValue
	 * @param context
	 * @param showdivlinevalue
	 */
	public final void setshowDivLineValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showdivlinevalue)
	{
		getMendixObject().setValue(context, MemberNames.showDivLineValue.toString(), showdivlinevalue);
	}

	/**
	 * @return value of showAlternateHGridColor
	 */
	public final java.lang.Boolean getshowAlternateHGridColor()
	{
		return getshowAlternateHGridColor(getContext());
	}

	/**
	 * @param context
	 * @return value of showAlternateHGridColor
	 */
	public final java.lang.Boolean getshowAlternateHGridColor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.showAlternateHGridColor.toString());
	}

	/**
	 * Set value of showAlternateHGridColor
	 * @param showalternatehgridcolor
	 */
	public final void setshowAlternateHGridColor(java.lang.Boolean showalternatehgridcolor)
	{
		setshowAlternateHGridColor(getContext(), showalternatehgridcolor);
	}

	/**
	 * Set value of showAlternateHGridColor
	 * @param context
	 * @param showalternatehgridcolor
	 */
	public final void setshowAlternateHGridColor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showalternatehgridcolor)
	{
		getMendixObject().setValue(context, MemberNames.showAlternateHGridColor.toString(), showalternatehgridcolor);
	}

	/**
	 * @return value of alternateHGridColor
	 */
	public final java.lang.String getalternateHGridColor()
	{
		return getalternateHGridColor(getContext());
	}

	/**
	 * @param context
	 * @return value of alternateHGridColor
	 */
	public final java.lang.String getalternateHGridColor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.alternateHGridColor.toString());
	}

	/**
	 * Set value of alternateHGridColor
	 * @param alternatehgridcolor
	 */
	public final void setalternateHGridColor(java.lang.String alternatehgridcolor)
	{
		setalternateHGridColor(getContext(), alternatehgridcolor);
	}

	/**
	 * Set value of alternateHGridColor
	 * @param context
	 * @param alternatehgridcolor
	 */
	public final void setalternateHGridColor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String alternatehgridcolor)
	{
		getMendixObject().setValue(context, MemberNames.alternateHGridColor.toString(), alternatehgridcolor);
	}

	/**
	 * @return value of alternateHGridAlpha
	 */
	public final java.lang.String getalternateHGridAlpha()
	{
		return getalternateHGridAlpha(getContext());
	}

	/**
	 * @param context
	 * @return value of alternateHGridAlpha
	 */
	public final java.lang.String getalternateHGridAlpha(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.alternateHGridAlpha.toString());
	}

	/**
	 * Set value of alternateHGridAlpha
	 * @param alternatehgridalpha
	 */
	public final void setalternateHGridAlpha(java.lang.String alternatehgridalpha)
	{
		setalternateHGridAlpha(getContext(), alternatehgridalpha);
	}

	/**
	 * Set value of alternateHGridAlpha
	 * @param context
	 * @param alternatehgridalpha
	 */
	public final void setalternateHGridAlpha(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String alternatehgridalpha)
	{
		getMendixObject().setValue(context, MemberNames.alternateHGridAlpha.toString(), alternatehgridalpha);
	}

	/**
	 * @return value of numVDivLines
	 */
	public final java.lang.String getnumVDivLines()
	{
		return getnumVDivLines(getContext());
	}

	/**
	 * @param context
	 * @return value of numVDivLines
	 */
	public final java.lang.String getnumVDivLines(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.numVDivLines.toString());
	}

	/**
	 * Set value of numVDivLines
	 * @param numvdivlines
	 */
	public final void setnumVDivLines(java.lang.String numvdivlines)
	{
		setnumVDivLines(getContext(), numvdivlines);
	}

	/**
	 * Set value of numVDivLines
	 * @param context
	 * @param numvdivlines
	 */
	public final void setnumVDivLines(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String numvdivlines)
	{
		getMendixObject().setValue(context, MemberNames.numVDivLines.toString(), numvdivlines);
	}

	/**
	 * @return value of VDivlinecolor
	 */
	public final java.lang.String getVDivlinecolor()
	{
		return getVDivlinecolor(getContext());
	}

	/**
	 * @param context
	 * @return value of VDivlinecolor
	 */
	public final java.lang.String getVDivlinecolor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.VDivlinecolor.toString());
	}

	/**
	 * Set value of VDivlinecolor
	 * @param vdivlinecolor
	 */
	public final void setVDivlinecolor(java.lang.String vdivlinecolor)
	{
		setVDivlinecolor(getContext(), vdivlinecolor);
	}

	/**
	 * Set value of VDivlinecolor
	 * @param context
	 * @param vdivlinecolor
	 */
	public final void setVDivlinecolor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String vdivlinecolor)
	{
		getMendixObject().setValue(context, MemberNames.VDivlinecolor.toString(), vdivlinecolor);
	}

	/**
	 * @return value of VDivLineThickness
	 */
	public final java.lang.String getVDivLineThickness()
	{
		return getVDivLineThickness(getContext());
	}

	/**
	 * @param context
	 * @return value of VDivLineThickness
	 */
	public final java.lang.String getVDivLineThickness(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.VDivLineThickness.toString());
	}

	/**
	 * Set value of VDivLineThickness
	 * @param vdivlinethickness
	 */
	public final void setVDivLineThickness(java.lang.String vdivlinethickness)
	{
		setVDivLineThickness(getContext(), vdivlinethickness);
	}

	/**
	 * Set value of VDivLineThickness
	 * @param context
	 * @param vdivlinethickness
	 */
	public final void setVDivLineThickness(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String vdivlinethickness)
	{
		getMendixObject().setValue(context, MemberNames.VDivLineThickness.toString(), vdivlinethickness);
	}

	/**
	 * @return value of VDivLineAlpha
	 */
	public final java.lang.String getVDivLineAlpha()
	{
		return getVDivLineAlpha(getContext());
	}

	/**
	 * @param context
	 * @return value of VDivLineAlpha
	 */
	public final java.lang.String getVDivLineAlpha(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.VDivLineAlpha.toString());
	}

	/**
	 * Set value of VDivLineAlpha
	 * @param vdivlinealpha
	 */
	public final void setVDivLineAlpha(java.lang.String vdivlinealpha)
	{
		setVDivLineAlpha(getContext(), vdivlinealpha);
	}

	/**
	 * Set value of VDivLineAlpha
	 * @param context
	 * @param vdivlinealpha
	 */
	public final void setVDivLineAlpha(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String vdivlinealpha)
	{
		getMendixObject().setValue(context, MemberNames.VDivLineAlpha.toString(), vdivlinealpha);
	}

	/**
	 * @return value of showAlternateVGridColor
	 */
	public final java.lang.Boolean getshowAlternateVGridColor()
	{
		return getshowAlternateVGridColor(getContext());
	}

	/**
	 * @param context
	 * @return value of showAlternateVGridColor
	 */
	public final java.lang.Boolean getshowAlternateVGridColor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.showAlternateVGridColor.toString());
	}

	/**
	 * Set value of showAlternateVGridColor
	 * @param showalternatevgridcolor
	 */
	public final void setshowAlternateVGridColor(java.lang.Boolean showalternatevgridcolor)
	{
		setshowAlternateVGridColor(getContext(), showalternatevgridcolor);
	}

	/**
	 * Set value of showAlternateVGridColor
	 * @param context
	 * @param showalternatevgridcolor
	 */
	public final void setshowAlternateVGridColor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showalternatevgridcolor)
	{
		getMendixObject().setValue(context, MemberNames.showAlternateVGridColor.toString(), showalternatevgridcolor);
	}

	/**
	 * @return value of alternateVGridColor
	 */
	public final java.lang.String getalternateVGridColor()
	{
		return getalternateVGridColor(getContext());
	}

	/**
	 * @param context
	 * @return value of alternateVGridColor
	 */
	public final java.lang.String getalternateVGridColor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.alternateVGridColor.toString());
	}

	/**
	 * Set value of alternateVGridColor
	 * @param alternatevgridcolor
	 */
	public final void setalternateVGridColor(java.lang.String alternatevgridcolor)
	{
		setalternateVGridColor(getContext(), alternatevgridcolor);
	}

	/**
	 * Set value of alternateVGridColor
	 * @param context
	 * @param alternatevgridcolor
	 */
	public final void setalternateVGridColor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String alternatevgridcolor)
	{
		getMendixObject().setValue(context, MemberNames.alternateVGridColor.toString(), alternatevgridcolor);
	}

	/**
	 * @return value of alternateVGridAlpha
	 */
	public final java.lang.Integer getalternateVGridAlpha()
	{
		return getalternateVGridAlpha(getContext());
	}

	/**
	 * @param context
	 * @return value of alternateVGridAlpha
	 */
	public final java.lang.Integer getalternateVGridAlpha(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.alternateVGridAlpha.toString());
	}

	/**
	 * Set value of alternateVGridAlpha
	 * @param alternatevgridalpha
	 */
	public final void setalternateVGridAlpha(java.lang.Integer alternatevgridalpha)
	{
		setalternateVGridAlpha(getContext(), alternatevgridalpha);
	}

	/**
	 * Set value of alternateVGridAlpha
	 * @param context
	 * @param alternatevgridalpha
	 */
	public final void setalternateVGridAlpha(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer alternatevgridalpha)
	{
		getMendixObject().setValue(context, MemberNames.alternateVGridAlpha.toString(), alternatevgridalpha);
	}

	/**
	 * @return value of DivisionalLines_Graph
	 */
	public final fusionchartsplus.proxies.Graph getDivisionalLines_Graph() throws com.mendix.core.CoreException
	{
		return getDivisionalLines_Graph(getContext());
	}

	/**
	 * @param context
	 * @return value of DivisionalLines_Graph
	 */
	public final fusionchartsplus.proxies.Graph getDivisionalLines_Graph(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		fusionchartsplus.proxies.Graph result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DivisionalLines_Graph.toString());
		if (identifier != null)
			result = fusionchartsplus.proxies.Graph.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DivisionalLines_Graph
	 * @param divisionallines_graph
	 */
	public final void setDivisionalLines_Graph(fusionchartsplus.proxies.Graph divisionallines_graph)
	{
		setDivisionalLines_Graph(getContext(), divisionallines_graph);
	}

	/**
	 * Set value of DivisionalLines_Graph
	 * @param context
	 * @param divisionallines_graph
	 */
	public final void setDivisionalLines_Graph(com.mendix.systemwideinterfaces.core.IContext context, fusionchartsplus.proxies.Graph divisionallines_graph)
	{
		if (divisionallines_graph == null)
			getMendixObject().setValue(context, MemberNames.DivisionalLines_Graph.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DivisionalLines_Graph.toString(), divisionallines_graph.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return divisionalLinesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fusionchartsplus.proxies.DivisionalLines that = (fusionchartsplus.proxies.DivisionalLines) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "FusionChartsPlus.DivisionalLines";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
