// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package fusionchartsplus.proxies;

public class GraphDataSet
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject graphDataSetMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "FusionChartsPlus.GraphDataSet";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		seriesName("seriesName"),
		color("color"),
		GraphDataSet_GraphSet("FusionChartsPlus.GraphDataSet_GraphSet");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GraphDataSet(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "FusionChartsPlus.GraphDataSet"));
	}

	protected GraphDataSet(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject graphDataSetMendixObject)
	{
		if (graphDataSetMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("FusionChartsPlus.GraphDataSet", graphDataSetMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a FusionChartsPlus.GraphDataSet");

		this.graphDataSetMendixObject = graphDataSetMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'GraphDataSet.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static fusionchartsplus.proxies.GraphDataSet initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return fusionchartsplus.proxies.GraphDataSet.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static fusionchartsplus.proxies.GraphDataSet initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new fusionchartsplus.proxies.GraphDataSet(context, mendixObject);
	}

	public static fusionchartsplus.proxies.GraphDataSet load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return fusionchartsplus.proxies.GraphDataSet.initialize(context, mendixObject);
	}

	public static java.util.List<fusionchartsplus.proxies.GraphDataSet> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<fusionchartsplus.proxies.GraphDataSet> result = new java.util.ArrayList<fusionchartsplus.proxies.GraphDataSet>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//FusionChartsPlus.GraphDataSet" + xpathConstraint))
			result.add(fusionchartsplus.proxies.GraphDataSet.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of seriesName
	 */
	public final java.lang.String getseriesName()
	{
		return getseriesName(getContext());
	}

	/**
	 * @param context
	 * @return value of seriesName
	 */
	public final java.lang.String getseriesName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.seriesName.toString());
	}

	/**
	 * Set value of seriesName
	 * @param seriesname
	 */
	public final void setseriesName(java.lang.String seriesname)
	{
		setseriesName(getContext(), seriesname);
	}

	/**
	 * Set value of seriesName
	 * @param context
	 * @param seriesname
	 */
	public final void setseriesName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String seriesname)
	{
		getMendixObject().setValue(context, MemberNames.seriesName.toString(), seriesname);
	}

	/**
	 * @return value of color
	 */
	public final java.lang.String getcolor()
	{
		return getcolor(getContext());
	}

	/**
	 * @param context
	 * @return value of color
	 */
	public final java.lang.String getcolor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.color.toString());
	}

	/**
	 * Set value of color
	 * @param color
	 */
	public final void setcolor(java.lang.String color)
	{
		setcolor(getContext(), color);
	}

	/**
	 * Set value of color
	 * @param context
	 * @param color
	 */
	public final void setcolor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String color)
	{
		getMendixObject().setValue(context, MemberNames.color.toString(), color);
	}

	/**
	 * @return value of GraphDataSet_GraphSet
	 */
	public final java.util.List<fusionchartsplus.proxies.GraphSet> getGraphDataSet_GraphSet() throws com.mendix.core.CoreException
	{
		return getGraphDataSet_GraphSet(getContext());
	}

	/**
	 * @param context
	 * @return value of GraphDataSet_GraphSet
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<fusionchartsplus.proxies.GraphSet> getGraphDataSet_GraphSet(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<fusionchartsplus.proxies.GraphSet> result = new java.util.ArrayList<fusionchartsplus.proxies.GraphSet>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.GraphDataSet_GraphSet.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(fusionchartsplus.proxies.GraphSet.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of GraphDataSet_GraphSet
	 * @param graphdataset_graphset
	 */
	public final void setGraphDataSet_GraphSet(java.util.List<fusionchartsplus.proxies.GraphSet> graphdataset_graphset)
	{
		setGraphDataSet_GraphSet(getContext(), graphdataset_graphset);
	}

	/**
	 * Set value of GraphDataSet_GraphSet
	 * @param context
	 * @param graphdataset_graphset
	 */
	public final void setGraphDataSet_GraphSet(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<fusionchartsplus.proxies.GraphSet> graphdataset_graphset)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (fusionchartsplus.proxies.GraphSet proxyObject : graphdataset_graphset)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.GraphDataSet_GraphSet.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return graphDataSetMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final fusionchartsplus.proxies.GraphDataSet that = (fusionchartsplus.proxies.GraphDataSet) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "FusionChartsPlus.GraphDataSet";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
