// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testcases.proxies;

public class TableEntry
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject tableEntryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestCases.TableEntry";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		TableEntry_Table("TestCases.TableEntry_Table"),
		TableEntry_TestCaseStep("TestCases.TableEntry_TestCaseStep");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TableEntry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TestCases.TableEntry"));
	}

	protected TableEntry(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject tableEntryMendixObject)
	{
		if (tableEntryMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TestCases.TableEntry", tableEntryMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TestCases.TableEntry");

		this.tableEntryMendixObject = tableEntryMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TableEntry.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static testcases.proxies.TableEntry initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testcases.proxies.TableEntry.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static testcases.proxies.TableEntry initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("TestCases.TestCaseTableEntry", mendixObject.getType()))
			return testcases.proxies.TestCaseTableEntry.initialize(context, mendixObject);

		return new testcases.proxies.TableEntry(context, mendixObject);
	}

	public static testcases.proxies.TableEntry load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testcases.proxies.TableEntry.initialize(context, mendixObject);
	}

	public static java.util.List<? extends testcases.proxies.TableEntry> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<testcases.proxies.TableEntry> result = new java.util.ArrayList<testcases.proxies.TableEntry>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TestCases.TableEntry" + xpathConstraint))
			result.add(testcases.proxies.TableEntry.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of TableEntry_Table
	 */
	public final testcases.proxies.Table getTableEntry_Table() throws com.mendix.core.CoreException
	{
		return getTableEntry_Table(getContext());
	}

	/**
	 * @param context
	 * @return value of TableEntry_Table
	 */
	public final testcases.proxies.Table getTableEntry_Table(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testcases.proxies.Table result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TableEntry_Table.toString());
		if (identifier != null)
			result = testcases.proxies.Table.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TableEntry_Table
	 * @param tableentry_table
	 */
	public final void setTableEntry_Table(testcases.proxies.Table tableentry_table)
	{
		setTableEntry_Table(getContext(), tableentry_table);
	}

	/**
	 * Set value of TableEntry_Table
	 * @param context
	 * @param tableentry_table
	 */
	public final void setTableEntry_Table(com.mendix.systemwideinterfaces.core.IContext context, testcases.proxies.Table tableentry_table)
	{
		if (tableentry_table == null)
			getMendixObject().setValue(context, MemberNames.TableEntry_Table.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TableEntry_Table.toString(), tableentry_table.getMendixObject().getId());
	}

	/**
	 * @return value of TableEntry_TestCaseStep
	 */
	public final testcases.proxies.TestCaseStep getTableEntry_TestCaseStep() throws com.mendix.core.CoreException
	{
		return getTableEntry_TestCaseStep(getContext());
	}

	/**
	 * @param context
	 * @return value of TableEntry_TestCaseStep
	 */
	public final testcases.proxies.TestCaseStep getTableEntry_TestCaseStep(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testcases.proxies.TestCaseStep result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TableEntry_TestCaseStep.toString());
		if (identifier != null)
			result = testcases.proxies.TestCaseStep.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TableEntry_TestCaseStep
	 * @param tableentry_testcasestep
	 */
	public final void setTableEntry_TestCaseStep(testcases.proxies.TestCaseStep tableentry_testcasestep)
	{
		setTableEntry_TestCaseStep(getContext(), tableentry_testcasestep);
	}

	/**
	 * Set value of TableEntry_TestCaseStep
	 * @param context
	 * @param tableentry_testcasestep
	 */
	public final void setTableEntry_TestCaseStep(com.mendix.systemwideinterfaces.core.IContext context, testcases.proxies.TestCaseStep tableentry_testcasestep)
	{
		if (tableentry_testcasestep == null)
			getMendixObject().setValue(context, MemberNames.TableEntry_TestCaseStep.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TableEntry_TestCaseStep.toString(), tableentry_testcasestep.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return tableEntryMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testcases.proxies.TableEntry that = (testcases.proxies.TableEntry) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TestCases.TableEntry";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
