// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testcases.proxies;

public class TestStep
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject testStepMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestCases.TestStep";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Step("Step"),
		Action("Action"),
		Result("Result"),
		testresult("testresult"),
		relatedIssue("relatedIssue"),
		testStopsHere("testStopsHere"),
		HasChecks("HasChecks"),
		TestStep_Test("TestCases.TestStep_Test"),
		Issue_TestStep("TestCases.Issue_TestStep"),
		TestStep_Form("TestCases.TestStep_Form");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TestStep(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TestCases.TestStep"));
	}

	protected TestStep(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testStepMendixObject)
	{
		if (testStepMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TestCases.TestStep", testStepMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TestCases.TestStep");

		this.testStepMendixObject = testStepMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TestStep.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static testcases.proxies.TestStep initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testcases.proxies.TestStep.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static testcases.proxies.TestStep initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testcases.proxies.TestStep(context, mendixObject);
	}

	public static testcases.proxies.TestStep load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testcases.proxies.TestStep.initialize(context, mendixObject);
	}

	public static java.util.List<testcases.proxies.TestStep> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<testcases.proxies.TestStep> result = new java.util.ArrayList<testcases.proxies.TestStep>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TestCases.TestStep" + xpathConstraint))
			result.add(testcases.proxies.TestStep.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Step
	 */
	public final java.lang.Integer getStep()
	{
		return getStep(getContext());
	}

	/**
	 * @param context
	 * @return value of Step
	 */
	public final java.lang.Integer getStep(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Step.toString());
	}

	/**
	 * Set value of Step
	 * @param step
	 */
	public final void setStep(java.lang.Integer step)
	{
		setStep(getContext(), step);
	}

	/**
	 * Set value of Step
	 * @param context
	 * @param step
	 */
	public final void setStep(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer step)
	{
		getMendixObject().setValue(context, MemberNames.Step.toString(), step);
	}

	/**
	 * @return value of Action
	 */
	public final java.lang.String getAction()
	{
		return getAction(getContext());
	}

	/**
	 * @param context
	 * @return value of Action
	 */
	public final java.lang.String getAction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Action.toString());
	}

	/**
	 * Set value of Action
	 * @param action
	 */
	public final void setAction(java.lang.String action)
	{
		setAction(getContext(), action);
	}

	/**
	 * Set value of Action
	 * @param context
	 * @param action
	 */
	public final void setAction(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String action)
	{
		getMendixObject().setValue(context, MemberNames.Action.toString(), action);
	}

	/**
	 * @return value of Result
	 */
	public final java.lang.String getResult()
	{
		return getResult(getContext());
	}

	/**
	 * @param context
	 * @return value of Result
	 */
	public final java.lang.String getResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Result.toString());
	}

	/**
	 * Set value of Result
	 * @param result
	 */
	public final void setResult(java.lang.String result)
	{
		setResult(getContext(), result);
	}

	/**
	 * Set value of Result
	 * @param context
	 * @param result
	 */
	public final void setResult(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String result)
	{
		getMendixObject().setValue(context, MemberNames.Result.toString(), result);
	}

	/**
	 * Set value of testresult
	 * @param testresult
	 */
	public final testcases.proxies.result gettestresult()
	{
		return gettestresult(getContext());
	}

	/**
	 * @param context
	 * @return value of testresult
	 */
	public final testcases.proxies.result gettestresult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.testresult.toString());
		if (obj == null)
			return null;

		return testcases.proxies.result.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of testresult
	 * @param testresult
	 */
	public final void settestresult(testcases.proxies.result testresult)
	{
		settestresult(getContext(), testresult);
	}

	/**
	 * Set value of testresult
	 * @param context
	 * @param testresult
	 */
	public final void settestresult(com.mendix.systemwideinterfaces.core.IContext context, testcases.proxies.result testresult)
	{
		if (testresult != null)
			getMendixObject().setValue(context, MemberNames.testresult.toString(), testresult.toString());
		else
			getMendixObject().setValue(context, MemberNames.testresult.toString(), null);
	}

	/**
	 * @return value of relatedIssue
	 */
	public final java.lang.Boolean getrelatedIssue()
	{
		return getrelatedIssue(getContext());
	}

	/**
	 * @param context
	 * @return value of relatedIssue
	 */
	public final java.lang.Boolean getrelatedIssue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.relatedIssue.toString());
	}

	/**
	 * Set value of relatedIssue
	 * @param relatedissue
	 */
	public final void setrelatedIssue(java.lang.Boolean relatedissue)
	{
		setrelatedIssue(getContext(), relatedissue);
	}

	/**
	 * Set value of relatedIssue
	 * @param context
	 * @param relatedissue
	 */
	public final void setrelatedIssue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean relatedissue)
	{
		getMendixObject().setValue(context, MemberNames.relatedIssue.toString(), relatedissue);
	}

	/**
	 * @return value of testStopsHere
	 */
	public final java.lang.Boolean gettestStopsHere()
	{
		return gettestStopsHere(getContext());
	}

	/**
	 * @param context
	 * @return value of testStopsHere
	 */
	public final java.lang.Boolean gettestStopsHere(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.testStopsHere.toString());
	}

	/**
	 * Set value of testStopsHere
	 * @param teststopshere
	 */
	public final void settestStopsHere(java.lang.Boolean teststopshere)
	{
		settestStopsHere(getContext(), teststopshere);
	}

	/**
	 * Set value of testStopsHere
	 * @param context
	 * @param teststopshere
	 */
	public final void settestStopsHere(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean teststopshere)
	{
		getMendixObject().setValue(context, MemberNames.testStopsHere.toString(), teststopshere);
	}

	/**
	 * @return value of HasChecks
	 */
	public final java.lang.Boolean getHasChecks()
	{
		return getHasChecks(getContext());
	}

	/**
	 * @param context
	 * @return value of HasChecks
	 */
	public final java.lang.Boolean getHasChecks(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasChecks.toString());
	}

	/**
	 * Set value of HasChecks
	 * @param haschecks
	 */
	public final void setHasChecks(java.lang.Boolean haschecks)
	{
		setHasChecks(getContext(), haschecks);
	}

	/**
	 * Set value of HasChecks
	 * @param context
	 * @param haschecks
	 */
	public final void setHasChecks(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean haschecks)
	{
		getMendixObject().setValue(context, MemberNames.HasChecks.toString(), haschecks);
	}

	/**
	 * @return value of TestStep_Test
	 */
	public final testcases.proxies.Test getTestStep_Test() throws com.mendix.core.CoreException
	{
		return getTestStep_Test(getContext());
	}

	/**
	 * @param context
	 * @return value of TestStep_Test
	 */
	public final testcases.proxies.Test getTestStep_Test(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testcases.proxies.Test result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TestStep_Test.toString());
		if (identifier != null)
			result = testcases.proxies.Test.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TestStep_Test
	 * @param teststep_test
	 */
	public final void setTestStep_Test(testcases.proxies.Test teststep_test)
	{
		setTestStep_Test(getContext(), teststep_test);
	}

	/**
	 * Set value of TestStep_Test
	 * @param context
	 * @param teststep_test
	 */
	public final void setTestStep_Test(com.mendix.systemwideinterfaces.core.IContext context, testcases.proxies.Test teststep_test)
	{
		if (teststep_test == null)
			getMendixObject().setValue(context, MemberNames.TestStep_Test.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TestStep_Test.toString(), teststep_test.getMendixObject().getId());
	}

	/**
	 * @return value of Issue_TestStep
	 */
	public final testcases.proxies.Issue getIssue_TestStep() throws com.mendix.core.CoreException
	{
		return getIssue_TestStep(getContext());
	}

	/**
	 * @param context
	 * @return value of Issue_TestStep
	 */
	public final testcases.proxies.Issue getIssue_TestStep(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testcases.proxies.Issue result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Issue_TestStep.toString());
		if (identifier != null)
			result = testcases.proxies.Issue.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Issue_TestStep
	 * @param issue_teststep
	 */
	public final void setIssue_TestStep(testcases.proxies.Issue issue_teststep)
	{
		setIssue_TestStep(getContext(), issue_teststep);
	}

	/**
	 * Set value of Issue_TestStep
	 * @param context
	 * @param issue_teststep
	 */
	public final void setIssue_TestStep(com.mendix.systemwideinterfaces.core.IContext context, testcases.proxies.Issue issue_teststep)
	{
		if (issue_teststep == null)
			getMendixObject().setValue(context, MemberNames.Issue_TestStep.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Issue_TestStep.toString(), issue_teststep.getMendixObject().getId());
	}

	/**
	 * @return value of TestStep_Form
	 */
	public final testcases.proxies.Form getTestStep_Form() throws com.mendix.core.CoreException
	{
		return getTestStep_Form(getContext());
	}

	/**
	 * @param context
	 * @return value of TestStep_Form
	 */
	public final testcases.proxies.Form getTestStep_Form(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testcases.proxies.Form result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TestStep_Form.toString());
		if (identifier != null)
			result = testcases.proxies.Form.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TestStep_Form
	 * @param teststep_form
	 */
	public final void setTestStep_Form(testcases.proxies.Form teststep_form)
	{
		setTestStep_Form(getContext(), teststep_form);
	}

	/**
	 * Set value of TestStep_Form
	 * @param context
	 * @param teststep_form
	 */
	public final void setTestStep_Form(com.mendix.systemwideinterfaces.core.IContext context, testcases.proxies.Form teststep_form)
	{
		if (teststep_form == null)
			getMendixObject().setValue(context, MemberNames.TestStep_Form.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TestStep_Form.toString(), teststep_form.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return testStepMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testcases.proxies.TestStep that = (testcases.proxies.TestStep) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TestCases.TestStep";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
