// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testcases.proxies;

public class TestPackage_Instance
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject testPackage_InstanceMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestCases.TestPackage_Instance";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		TestType("TestType"),
		PackageOrder("PackageOrder"),
		TestPackage_Instance_TestRun_Instance("TestCases.TestPackage_Instance_TestRun_Instance");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TestPackage_Instance(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TestCases.TestPackage_Instance"));
	}

	protected TestPackage_Instance(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testPackage_InstanceMendixObject)
	{
		if (testPackage_InstanceMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TestCases.TestPackage_Instance", testPackage_InstanceMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TestCases.TestPackage_Instance");

		this.testPackage_InstanceMendixObject = testPackage_InstanceMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TestPackage_Instance.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static testcases.proxies.TestPackage_Instance initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testcases.proxies.TestPackage_Instance.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static testcases.proxies.TestPackage_Instance initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testcases.proxies.TestPackage_Instance(context, mendixObject);
	}

	public static testcases.proxies.TestPackage_Instance load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testcases.proxies.TestPackage_Instance.initialize(context, mendixObject);
	}

	public static java.util.List<testcases.proxies.TestPackage_Instance> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<testcases.proxies.TestPackage_Instance> result = new java.util.ArrayList<testcases.proxies.TestPackage_Instance>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TestCases.TestPackage_Instance" + xpathConstraint))
			result.add(testcases.proxies.TestPackage_Instance.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * Set value of TestType
	 * @param testtype
	 */
	public final testcases.proxies.TestTypes getTestType()
	{
		return getTestType(getContext());
	}

	/**
	 * @param context
	 * @return value of TestType
	 */
	public final testcases.proxies.TestTypes getTestType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TestType.toString());
		if (obj == null)
			return null;

		return testcases.proxies.TestTypes.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TestType
	 * @param testtype
	 */
	public final void setTestType(testcases.proxies.TestTypes testtype)
	{
		setTestType(getContext(), testtype);
	}

	/**
	 * Set value of TestType
	 * @param context
	 * @param testtype
	 */
	public final void setTestType(com.mendix.systemwideinterfaces.core.IContext context, testcases.proxies.TestTypes testtype)
	{
		if (testtype != null)
			getMendixObject().setValue(context, MemberNames.TestType.toString(), testtype.toString());
		else
			getMendixObject().setValue(context, MemberNames.TestType.toString(), null);
	}

	/**
	 * @return value of PackageOrder
	 */
	public final java.lang.Integer getPackageOrder()
	{
		return getPackageOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of PackageOrder
	 */
	public final java.lang.Integer getPackageOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.PackageOrder.toString());
	}

	/**
	 * Set value of PackageOrder
	 * @param packageorder
	 */
	public final void setPackageOrder(java.lang.Integer packageorder)
	{
		setPackageOrder(getContext(), packageorder);
	}

	/**
	 * Set value of PackageOrder
	 * @param context
	 * @param packageorder
	 */
	public final void setPackageOrder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer packageorder)
	{
		getMendixObject().setValue(context, MemberNames.PackageOrder.toString(), packageorder);
	}

	/**
	 * @return value of TestPackage_Instance_TestRun_Instance
	 */
	public final testcases.proxies.TestRun_Instance getTestPackage_Instance_TestRun_Instance() throws com.mendix.core.CoreException
	{
		return getTestPackage_Instance_TestRun_Instance(getContext());
	}

	/**
	 * @param context
	 * @return value of TestPackage_Instance_TestRun_Instance
	 */
	public final testcases.proxies.TestRun_Instance getTestPackage_Instance_TestRun_Instance(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testcases.proxies.TestRun_Instance result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TestPackage_Instance_TestRun_Instance.toString());
		if (identifier != null)
			result = testcases.proxies.TestRun_Instance.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TestPackage_Instance_TestRun_Instance
	 * @param testpackage_instance_testrun_instance
	 */
	public final void setTestPackage_Instance_TestRun_Instance(testcases.proxies.TestRun_Instance testpackage_instance_testrun_instance)
	{
		setTestPackage_Instance_TestRun_Instance(getContext(), testpackage_instance_testrun_instance);
	}

	/**
	 * Set value of TestPackage_Instance_TestRun_Instance
	 * @param context
	 * @param testpackage_instance_testrun_instance
	 */
	public final void setTestPackage_Instance_TestRun_Instance(com.mendix.systemwideinterfaces.core.IContext context, testcases.proxies.TestRun_Instance testpackage_instance_testrun_instance)
	{
		if (testpackage_instance_testrun_instance == null)
			getMendixObject().setValue(context, MemberNames.TestPackage_Instance_TestRun_Instance.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TestPackage_Instance_TestRun_Instance.toString(), testpackage_instance_testrun_instance.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return testPackage_InstanceMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testcases.proxies.TestPackage_Instance that = (testcases.proxies.TestPackage_Instance) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TestCases.TestPackage_Instance";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
