// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testcases.proxies;

public enum TestTypes
{
	Admin_Test(new java.lang.String[][] { new java.lang.String[] { "en_US", "Admin Test" }, new java.lang.String[] { "nl_NL", "Admin test" } }),
	Data_Test(new java.lang.String[][] { new java.lang.String[] { "en_US", "Data Test" }, new java.lang.String[] { "nl_NL", "Datum test" } }),
	Unit_Test(new java.lang.String[][] { new java.lang.String[] { "en_US", "Unit Test" }, new java.lang.String[] { "nl_NL", "Unit test" } }),
	System_Test(new java.lang.String[][] { new java.lang.String[] { "en_US", "System Test" }, new java.lang.String[] { "nl_NL", "Systeem test" } }),
	Factory_Acceptance_Test(new java.lang.String[][] { new java.lang.String[] { "en_US", "Factory Acceptance Test" } }),
	Witness_Test(new java.lang.String[][] { new java.lang.String[] { "en_US", "Witness Test" }, new java.lang.String[] { "nl_NL", "Witness test" } }),
	User_Acceptance_Test(new java.lang.String[][] { new java.lang.String[] { "en_US", "User Acceptance Test" }, new java.lang.String[] { "nl_NL", "Gebruikers acceptatietest" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private TestTypes(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
