// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testcases.proxies;

public class TestAttachments extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestCases.TestAttachments";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		TestAttachments_Issue("TestCases.TestAttachments_Issue");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TestAttachments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TestCases.TestAttachments"));
	}

	protected TestAttachments(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testAttachmentsMendixObject)
	{
		super(context, testAttachmentsMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("TestCases.TestAttachments", testAttachmentsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TestCases.TestAttachments");
	}

	/**
	 * @deprecated Use 'TestAttachments.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static testcases.proxies.TestAttachments initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testcases.proxies.TestAttachments.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static testcases.proxies.TestAttachments initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testcases.proxies.TestAttachments(context, mendixObject);
	}

	public static testcases.proxies.TestAttachments load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testcases.proxies.TestAttachments.initialize(context, mendixObject);
	}

	public static java.util.List<testcases.proxies.TestAttachments> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<testcases.proxies.TestAttachments> result = new java.util.ArrayList<testcases.proxies.TestAttachments>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TestCases.TestAttachments" + xpathConstraint))
			result.add(testcases.proxies.TestAttachments.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of TestAttachments_Issue
	 */
	public final testcases.proxies.Issue getTestAttachments_Issue() throws com.mendix.core.CoreException
	{
		return getTestAttachments_Issue(getContext());
	}

	/**
	 * @param context
	 * @return value of TestAttachments_Issue
	 */
	public final testcases.proxies.Issue getTestAttachments_Issue(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testcases.proxies.Issue result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TestAttachments_Issue.toString());
		if (identifier != null)
			result = testcases.proxies.Issue.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TestAttachments_Issue
	 * @param testattachments_issue
	 */
	public final void setTestAttachments_Issue(testcases.proxies.Issue testattachments_issue)
	{
		setTestAttachments_Issue(getContext(), testattachments_issue);
	}

	/**
	 * Set value of TestAttachments_Issue
	 * @param context
	 * @param testattachments_issue
	 */
	public final void setTestAttachments_Issue(com.mendix.systemwideinterfaces.core.IContext context, testcases.proxies.Issue testattachments_issue)
	{
		if (testattachments_issue == null)
			getMendixObject().setValue(context, MemberNames.TestAttachments_Issue.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TestAttachments_Issue.toString(), testattachments_issue.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testcases.proxies.TestAttachments that = (testcases.proxies.TestAttachments) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TestCases.TestAttachments";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
