// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package expertdesk95layout.proxies;

public enum ActionMenuEnum
{
	Accept(new java.lang.String[][] { new java.lang.String[] { "en_US", "Accept" } }),
	Assign_to_person(new java.lang.String[][] { new java.lang.String[] { "en_US", "Assign to person" } }),
	Pause(new java.lang.String[][] { new java.lang.String[] { "en_US", "Pause" } }),
	Request_approval(new java.lang.String[][] { new java.lang.String[] { "en_US", "Request approval" } }),
	Start_workflow(new java.lang.String[][] { new java.lang.String[] { "en_US", "Start workflow" } }),
	Take_over(new java.lang.String[][] { new java.lang.String[] { "en_US", "Take over" } }),
	Waiting_for_customer(new java.lang.String[][] { new java.lang.String[] { "en_US", "Waiting for customer" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private ActionMenuEnum(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
