// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package expertdesk95layout.proxies;

public class ExampleEntity
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject exampleEntityMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ExpertDesk95Layout.ExampleEntity";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Action("Action"),
		TitlebarHeader("TitlebarHeader"),
		TitlebarSubheader("TitlebarSubheader"),
		RequestType("RequestType"),
		RequestListHeader("RequestListHeader"),
		ProgressAttribute("ProgressAttribute"),
		ExampleOrg("ExampleOrg"),
		ExampleRequester("ExampleRequester"),
		ExampleLocation("ExampleLocation"),
		ExampleState("ExampleState"),
		ExamplePhase("ExamplePhase"),
		ExampleProcess("ExampleProcess"),
		ExampleTicketID("ExampleTicketID"),
		ExampleNote("ExampleNote"),
		ExampleStateshort("ExampleStateshort"),
		ExampleTaskCounter("ExampleTaskCounter"),
		ExampleSubject("ExampleSubject"),
		ExampleDueDate("ExampleDueDate"),
		ExampleAssignee("ExampleAssignee"),
		ExampleCheckbox("ExampleCheckbox"),
		ExampleSolution("ExampleSolution");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ExampleEntity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ExpertDesk95Layout.ExampleEntity"));
	}

	protected ExampleEntity(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject exampleEntityMendixObject)
	{
		if (exampleEntityMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("ExpertDesk95Layout.ExampleEntity", exampleEntityMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ExpertDesk95Layout.ExampleEntity");

		this.exampleEntityMendixObject = exampleEntityMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ExampleEntity.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static expertdesk95layout.proxies.ExampleEntity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return expertdesk95layout.proxies.ExampleEntity.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static expertdesk95layout.proxies.ExampleEntity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new expertdesk95layout.proxies.ExampleEntity(context, mendixObject);
	}

	public static expertdesk95layout.proxies.ExampleEntity load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return expertdesk95layout.proxies.ExampleEntity.initialize(context, mendixObject);
	}

	public static java.util.List<expertdesk95layout.proxies.ExampleEntity> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<expertdesk95layout.proxies.ExampleEntity> result = new java.util.ArrayList<expertdesk95layout.proxies.ExampleEntity>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//ExpertDesk95Layout.ExampleEntity" + xpathConstraint))
			result.add(expertdesk95layout.proxies.ExampleEntity.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of Action
	 * @param action
	 */
	public final expertdesk95layout.proxies.ActionMenuEnum getAction()
	{
		return getAction(getContext());
	}

	/**
	 * @param context
	 * @return value of Action
	 */
	public final expertdesk95layout.proxies.ActionMenuEnum getAction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Action.toString());
		if (obj == null)
			return null;

		return expertdesk95layout.proxies.ActionMenuEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Action
	 * @param action
	 */
	public final void setAction(expertdesk95layout.proxies.ActionMenuEnum action)
	{
		setAction(getContext(), action);
	}

	/**
	 * Set value of Action
	 * @param context
	 * @param action
	 */
	public final void setAction(com.mendix.systemwideinterfaces.core.IContext context, expertdesk95layout.proxies.ActionMenuEnum action)
	{
		if (action != null)
			getMendixObject().setValue(context, MemberNames.Action.toString(), action.toString());
		else
			getMendixObject().setValue(context, MemberNames.Action.toString(), null);
	}

	/**
	 * @return value of TitlebarHeader
	 */
	public final java.lang.String getTitlebarHeader()
	{
		return getTitlebarHeader(getContext());
	}

	/**
	 * @param context
	 * @return value of TitlebarHeader
	 */
	public final java.lang.String getTitlebarHeader(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TitlebarHeader.toString());
	}

	/**
	 * Set value of TitlebarHeader
	 * @param titlebarheader
	 */
	public final void setTitlebarHeader(java.lang.String titlebarheader)
	{
		setTitlebarHeader(getContext(), titlebarheader);
	}

	/**
	 * Set value of TitlebarHeader
	 * @param context
	 * @param titlebarheader
	 */
	public final void setTitlebarHeader(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String titlebarheader)
	{
		getMendixObject().setValue(context, MemberNames.TitlebarHeader.toString(), titlebarheader);
	}

	/**
	 * @return value of TitlebarSubheader
	 */
	public final java.lang.String getTitlebarSubheader()
	{
		return getTitlebarSubheader(getContext());
	}

	/**
	 * @param context
	 * @return value of TitlebarSubheader
	 */
	public final java.lang.String getTitlebarSubheader(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TitlebarSubheader.toString());
	}

	/**
	 * Set value of TitlebarSubheader
	 * @param titlebarsubheader
	 */
	public final void setTitlebarSubheader(java.lang.String titlebarsubheader)
	{
		setTitlebarSubheader(getContext(), titlebarsubheader);
	}

	/**
	 * Set value of TitlebarSubheader
	 * @param context
	 * @param titlebarsubheader
	 */
	public final void setTitlebarSubheader(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String titlebarsubheader)
	{
		getMendixObject().setValue(context, MemberNames.TitlebarSubheader.toString(), titlebarsubheader);
	}

	/**
	 * Set value of RequestType
	 * @param requesttype
	 */
	public final expertdesk95layout.proxies.RequestTypeEnum getRequestType()
	{
		return getRequestType(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestType
	 */
	public final expertdesk95layout.proxies.RequestTypeEnum getRequestType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.RequestType.toString());
		if (obj == null)
			return null;

		return expertdesk95layout.proxies.RequestTypeEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of RequestType
	 * @param requesttype
	 */
	public final void setRequestType(expertdesk95layout.proxies.RequestTypeEnum requesttype)
	{
		setRequestType(getContext(), requesttype);
	}

	/**
	 * Set value of RequestType
	 * @param context
	 * @param requesttype
	 */
	public final void setRequestType(com.mendix.systemwideinterfaces.core.IContext context, expertdesk95layout.proxies.RequestTypeEnum requesttype)
	{
		if (requesttype != null)
			getMendixObject().setValue(context, MemberNames.RequestType.toString(), requesttype.toString());
		else
			getMendixObject().setValue(context, MemberNames.RequestType.toString(), null);
	}

	/**
	 * @return value of RequestListHeader
	 */
	public final java.lang.String getRequestListHeader()
	{
		return getRequestListHeader(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestListHeader
	 */
	public final java.lang.String getRequestListHeader(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RequestListHeader.toString());
	}

	/**
	 * Set value of RequestListHeader
	 * @param requestlistheader
	 */
	public final void setRequestListHeader(java.lang.String requestlistheader)
	{
		setRequestListHeader(getContext(), requestlistheader);
	}

	/**
	 * Set value of RequestListHeader
	 * @param context
	 * @param requestlistheader
	 */
	public final void setRequestListHeader(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String requestlistheader)
	{
		getMendixObject().setValue(context, MemberNames.RequestListHeader.toString(), requestlistheader);
	}

	/**
	 * @return value of ProgressAttribute
	 */
	public final java.lang.Integer getProgressAttribute()
	{
		return getProgressAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of ProgressAttribute
	 */
	public final java.lang.Integer getProgressAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ProgressAttribute.toString());
	}

	/**
	 * Set value of ProgressAttribute
	 * @param progressattribute
	 */
	public final void setProgressAttribute(java.lang.Integer progressattribute)
	{
		setProgressAttribute(getContext(), progressattribute);
	}

	/**
	 * Set value of ProgressAttribute
	 * @param context
	 * @param progressattribute
	 */
	public final void setProgressAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer progressattribute)
	{
		getMendixObject().setValue(context, MemberNames.ProgressAttribute.toString(), progressattribute);
	}

	/**
	 * @return value of ExampleOrg
	 */
	public final java.lang.String getExampleOrg()
	{
		return getExampleOrg(getContext());
	}

	/**
	 * @param context
	 * @return value of ExampleOrg
	 */
	public final java.lang.String getExampleOrg(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExampleOrg.toString());
	}

	/**
	 * Set value of ExampleOrg
	 * @param exampleorg
	 */
	public final void setExampleOrg(java.lang.String exampleorg)
	{
		setExampleOrg(getContext(), exampleorg);
	}

	/**
	 * Set value of ExampleOrg
	 * @param context
	 * @param exampleorg
	 */
	public final void setExampleOrg(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String exampleorg)
	{
		getMendixObject().setValue(context, MemberNames.ExampleOrg.toString(), exampleorg);
	}

	/**
	 * @return value of ExampleRequester
	 */
	public final java.lang.String getExampleRequester()
	{
		return getExampleRequester(getContext());
	}

	/**
	 * @param context
	 * @return value of ExampleRequester
	 */
	public final java.lang.String getExampleRequester(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExampleRequester.toString());
	}

	/**
	 * Set value of ExampleRequester
	 * @param examplerequester
	 */
	public final void setExampleRequester(java.lang.String examplerequester)
	{
		setExampleRequester(getContext(), examplerequester);
	}

	/**
	 * Set value of ExampleRequester
	 * @param context
	 * @param examplerequester
	 */
	public final void setExampleRequester(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String examplerequester)
	{
		getMendixObject().setValue(context, MemberNames.ExampleRequester.toString(), examplerequester);
	}

	/**
	 * @return value of ExampleLocation
	 */
	public final java.lang.String getExampleLocation()
	{
		return getExampleLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of ExampleLocation
	 */
	public final java.lang.String getExampleLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExampleLocation.toString());
	}

	/**
	 * Set value of ExampleLocation
	 * @param examplelocation
	 */
	public final void setExampleLocation(java.lang.String examplelocation)
	{
		setExampleLocation(getContext(), examplelocation);
	}

	/**
	 * Set value of ExampleLocation
	 * @param context
	 * @param examplelocation
	 */
	public final void setExampleLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String examplelocation)
	{
		getMendixObject().setValue(context, MemberNames.ExampleLocation.toString(), examplelocation);
	}

	/**
	 * @return value of ExampleState
	 */
	public final java.lang.String getExampleState()
	{
		return getExampleState(getContext());
	}

	/**
	 * @param context
	 * @return value of ExampleState
	 */
	public final java.lang.String getExampleState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExampleState.toString());
	}

	/**
	 * Set value of ExampleState
	 * @param examplestate
	 */
	public final void setExampleState(java.lang.String examplestate)
	{
		setExampleState(getContext(), examplestate);
	}

	/**
	 * Set value of ExampleState
	 * @param context
	 * @param examplestate
	 */
	public final void setExampleState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String examplestate)
	{
		getMendixObject().setValue(context, MemberNames.ExampleState.toString(), examplestate);
	}

	/**
	 * @return value of ExamplePhase
	 */
	public final java.lang.String getExamplePhase()
	{
		return getExamplePhase(getContext());
	}

	/**
	 * @param context
	 * @return value of ExamplePhase
	 */
	public final java.lang.String getExamplePhase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExamplePhase.toString());
	}

	/**
	 * Set value of ExamplePhase
	 * @param examplephase
	 */
	public final void setExamplePhase(java.lang.String examplephase)
	{
		setExamplePhase(getContext(), examplephase);
	}

	/**
	 * Set value of ExamplePhase
	 * @param context
	 * @param examplephase
	 */
	public final void setExamplePhase(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String examplephase)
	{
		getMendixObject().setValue(context, MemberNames.ExamplePhase.toString(), examplephase);
	}

	/**
	 * @return value of ExampleProcess
	 */
	public final java.lang.String getExampleProcess()
	{
		return getExampleProcess(getContext());
	}

	/**
	 * @param context
	 * @return value of ExampleProcess
	 */
	public final java.lang.String getExampleProcess(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExampleProcess.toString());
	}

	/**
	 * Set value of ExampleProcess
	 * @param exampleprocess
	 */
	public final void setExampleProcess(java.lang.String exampleprocess)
	{
		setExampleProcess(getContext(), exampleprocess);
	}

	/**
	 * Set value of ExampleProcess
	 * @param context
	 * @param exampleprocess
	 */
	public final void setExampleProcess(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String exampleprocess)
	{
		getMendixObject().setValue(context, MemberNames.ExampleProcess.toString(), exampleprocess);
	}

	/**
	 * @return value of ExampleTicketID
	 */
	public final java.lang.String getExampleTicketID()
	{
		return getExampleTicketID(getContext());
	}

	/**
	 * @param context
	 * @return value of ExampleTicketID
	 */
	public final java.lang.String getExampleTicketID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExampleTicketID.toString());
	}

	/**
	 * Set value of ExampleTicketID
	 * @param exampleticketid
	 */
	public final void setExampleTicketID(java.lang.String exampleticketid)
	{
		setExampleTicketID(getContext(), exampleticketid);
	}

	/**
	 * Set value of ExampleTicketID
	 * @param context
	 * @param exampleticketid
	 */
	public final void setExampleTicketID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String exampleticketid)
	{
		getMendixObject().setValue(context, MemberNames.ExampleTicketID.toString(), exampleticketid);
	}

	/**
	 * @return value of ExampleNote
	 */
	public final java.lang.String getExampleNote()
	{
		return getExampleNote(getContext());
	}

	/**
	 * @param context
	 * @return value of ExampleNote
	 */
	public final java.lang.String getExampleNote(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExampleNote.toString());
	}

	/**
	 * Set value of ExampleNote
	 * @param examplenote
	 */
	public final void setExampleNote(java.lang.String examplenote)
	{
		setExampleNote(getContext(), examplenote);
	}

	/**
	 * Set value of ExampleNote
	 * @param context
	 * @param examplenote
	 */
	public final void setExampleNote(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String examplenote)
	{
		getMendixObject().setValue(context, MemberNames.ExampleNote.toString(), examplenote);
	}

	/**
	 * @return value of ExampleStateshort
	 */
	public final java.lang.String getExampleStateshort()
	{
		return getExampleStateshort(getContext());
	}

	/**
	 * @param context
	 * @return value of ExampleStateshort
	 */
	public final java.lang.String getExampleStateshort(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExampleStateshort.toString());
	}

	/**
	 * Set value of ExampleStateshort
	 * @param examplestateshort
	 */
	public final void setExampleStateshort(java.lang.String examplestateshort)
	{
		setExampleStateshort(getContext(), examplestateshort);
	}

	/**
	 * Set value of ExampleStateshort
	 * @param context
	 * @param examplestateshort
	 */
	public final void setExampleStateshort(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String examplestateshort)
	{
		getMendixObject().setValue(context, MemberNames.ExampleStateshort.toString(), examplestateshort);
	}

	/**
	 * @return value of ExampleTaskCounter
	 */
	public final java.lang.String getExampleTaskCounter()
	{
		return getExampleTaskCounter(getContext());
	}

	/**
	 * @param context
	 * @return value of ExampleTaskCounter
	 */
	public final java.lang.String getExampleTaskCounter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExampleTaskCounter.toString());
	}

	/**
	 * Set value of ExampleTaskCounter
	 * @param exampletaskcounter
	 */
	public final void setExampleTaskCounter(java.lang.String exampletaskcounter)
	{
		setExampleTaskCounter(getContext(), exampletaskcounter);
	}

	/**
	 * Set value of ExampleTaskCounter
	 * @param context
	 * @param exampletaskcounter
	 */
	public final void setExampleTaskCounter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String exampletaskcounter)
	{
		getMendixObject().setValue(context, MemberNames.ExampleTaskCounter.toString(), exampletaskcounter);
	}

	/**
	 * @return value of ExampleSubject
	 */
	public final java.lang.String getExampleSubject()
	{
		return getExampleSubject(getContext());
	}

	/**
	 * @param context
	 * @return value of ExampleSubject
	 */
	public final java.lang.String getExampleSubject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExampleSubject.toString());
	}

	/**
	 * Set value of ExampleSubject
	 * @param examplesubject
	 */
	public final void setExampleSubject(java.lang.String examplesubject)
	{
		setExampleSubject(getContext(), examplesubject);
	}

	/**
	 * Set value of ExampleSubject
	 * @param context
	 * @param examplesubject
	 */
	public final void setExampleSubject(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String examplesubject)
	{
		getMendixObject().setValue(context, MemberNames.ExampleSubject.toString(), examplesubject);
	}

	/**
	 * @return value of ExampleDueDate
	 */
	public final java.util.Date getExampleDueDate()
	{
		return getExampleDueDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ExampleDueDate
	 */
	public final java.util.Date getExampleDueDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ExampleDueDate.toString());
	}

	/**
	 * Set value of ExampleDueDate
	 * @param exampleduedate
	 */
	public final void setExampleDueDate(java.util.Date exampleduedate)
	{
		setExampleDueDate(getContext(), exampleduedate);
	}

	/**
	 * Set value of ExampleDueDate
	 * @param context
	 * @param exampleduedate
	 */
	public final void setExampleDueDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date exampleduedate)
	{
		getMendixObject().setValue(context, MemberNames.ExampleDueDate.toString(), exampleduedate);
	}

	/**
	 * @return value of ExampleAssignee
	 */
	public final java.lang.String getExampleAssignee()
	{
		return getExampleAssignee(getContext());
	}

	/**
	 * @param context
	 * @return value of ExampleAssignee
	 */
	public final java.lang.String getExampleAssignee(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExampleAssignee.toString());
	}

	/**
	 * Set value of ExampleAssignee
	 * @param exampleassignee
	 */
	public final void setExampleAssignee(java.lang.String exampleassignee)
	{
		setExampleAssignee(getContext(), exampleassignee);
	}

	/**
	 * Set value of ExampleAssignee
	 * @param context
	 * @param exampleassignee
	 */
	public final void setExampleAssignee(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String exampleassignee)
	{
		getMendixObject().setValue(context, MemberNames.ExampleAssignee.toString(), exampleassignee);
	}

	/**
	 * @return value of ExampleCheckbox
	 */
	public final java.lang.Boolean getExampleCheckbox()
	{
		return getExampleCheckbox(getContext());
	}

	/**
	 * @param context
	 * @return value of ExampleCheckbox
	 */
	public final java.lang.Boolean getExampleCheckbox(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ExampleCheckbox.toString());
	}

	/**
	 * Set value of ExampleCheckbox
	 * @param examplecheckbox
	 */
	public final void setExampleCheckbox(java.lang.Boolean examplecheckbox)
	{
		setExampleCheckbox(getContext(), examplecheckbox);
	}

	/**
	 * Set value of ExampleCheckbox
	 * @param context
	 * @param examplecheckbox
	 */
	public final void setExampleCheckbox(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean examplecheckbox)
	{
		getMendixObject().setValue(context, MemberNames.ExampleCheckbox.toString(), examplecheckbox);
	}

	/**
	 * @return value of ExampleSolution
	 */
	public final java.lang.String getExampleSolution()
	{
		return getExampleSolution(getContext());
	}

	/**
	 * @param context
	 * @return value of ExampleSolution
	 */
	public final java.lang.String getExampleSolution(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExampleSolution.toString());
	}

	/**
	 * Set value of ExampleSolution
	 * @param examplesolution
	 */
	public final void setExampleSolution(java.lang.String examplesolution)
	{
		setExampleSolution(getContext(), examplesolution);
	}

	/**
	 * Set value of ExampleSolution
	 * @param context
	 * @param examplesolution
	 */
	public final void setExampleSolution(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String examplesolution)
	{
		getMendixObject().setValue(context, MemberNames.ExampleSolution.toString(), examplesolution);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return exampleEntityMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final expertdesk95layout.proxies.ExampleEntity that = (expertdesk95layout.proxies.ExampleEntity) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ExpertDesk95Layout.ExampleEntity";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
