// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package advancedsearch.actions;

import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class IndexRequestList extends CustomJavaAction<java.lang.Boolean>
{
	private java.util.List<IMendixObject> __requestList;
	private java.util.List<process.proxies.Request> requestList;

	public IndexRequestList(IContext context, java.util.List<IMendixObject> requestList)
	{
		super(context);
		this.__requestList = requestList;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.requestList = new java.util.ArrayList<process.proxies.Request>();
		if (__requestList != null)
			for (IMendixObject __requestListElement : __requestList)
				this.requestList.add(process.proxies.Request.initialize(getContext(), __requestListElement));

		// BEGIN USER CODE
		return nl.mansystems.advancedsearch.IndexRequest.indexRequestList(this.getContext(), this, requestList);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "IndexRequestList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
