// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mendix.proxies;

public class AccountPreferences
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject accountPreferencesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Mendix.AccountPreferences";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PortalLandingPage("PortalLandingPage"),
		PortalRequestConfirmation("PortalRequestConfirmation"),
		PortalPanelPreference("PortalPanelPreference"),
		ProcessLandingPage("ProcessLandingPage"),
		RequestCreation("RequestCreation"),
		ShowTasks("ShowTasks"),
		StartPanelPreference("StartPanelPreference"),
		ProcessRequestConfirmation("ProcessRequestConfirmation"),
		ShowKnowledgeFavouritesOnly("ShowKnowledgeFavouritesOnly"),
		AccountPreferences_Account("Mendix.AccountPreferences_Account"),
		AccountPreferences_KnowledgeSearch("Mendix.AccountPreferences_KnowledgeSearch"),
		AccountPreferences_Request("Mendix.AccountPreferences_Request"),
		AccountPreferences_Knowledge("Mendix.AccountPreferences_Knowledge");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AccountPreferences(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Mendix.AccountPreferences"));
	}

	protected AccountPreferences(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject accountPreferencesMendixObject)
	{
		if (accountPreferencesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Mendix.AccountPreferences", accountPreferencesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Mendix.AccountPreferences");

		this.accountPreferencesMendixObject = accountPreferencesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AccountPreferences.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static mendix.proxies.AccountPreferences initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mendix.proxies.AccountPreferences.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mendix.proxies.AccountPreferences initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mendix.proxies.AccountPreferences(context, mendixObject);
	}

	public static mendix.proxies.AccountPreferences load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mendix.proxies.AccountPreferences.initialize(context, mendixObject);
	}

	public static java.util.List<mendix.proxies.AccountPreferences> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<mendix.proxies.AccountPreferences> result = new java.util.ArrayList<mendix.proxies.AccountPreferences>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Mendix.AccountPreferences" + xpathConstraint))
			result.add(mendix.proxies.AccountPreferences.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of PortalLandingPage
	 * @param portallandingpage
	 */
	public final mendix.proxies.LogonLandingPage getPortalLandingPage()
	{
		return getPortalLandingPage(getContext());
	}

	/**
	 * @param context
	 * @return value of PortalLandingPage
	 */
	public final mendix.proxies.LogonLandingPage getPortalLandingPage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.PortalLandingPage.toString());
		if (obj == null)
			return null;

		return mendix.proxies.LogonLandingPage.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of PortalLandingPage
	 * @param portallandingpage
	 */
	public final void setPortalLandingPage(mendix.proxies.LogonLandingPage portallandingpage)
	{
		setPortalLandingPage(getContext(), portallandingpage);
	}

	/**
	 * Set value of PortalLandingPage
	 * @param context
	 * @param portallandingpage
	 */
	public final void setPortalLandingPage(com.mendix.systemwideinterfaces.core.IContext context, mendix.proxies.LogonLandingPage portallandingpage)
	{
		if (portallandingpage != null)
			getMendixObject().setValue(context, MemberNames.PortalLandingPage.toString(), portallandingpage.toString());
		else
			getMendixObject().setValue(context, MemberNames.PortalLandingPage.toString(), null);
	}

	/**
	 * @return value of PortalRequestConfirmation
	 */
	public final java.lang.Boolean getPortalRequestConfirmation()
	{
		return getPortalRequestConfirmation(getContext());
	}

	/**
	 * @param context
	 * @return value of PortalRequestConfirmation
	 */
	public final java.lang.Boolean getPortalRequestConfirmation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.PortalRequestConfirmation.toString());
	}

	/**
	 * Set value of PortalRequestConfirmation
	 * @param portalrequestconfirmation
	 */
	public final void setPortalRequestConfirmation(java.lang.Boolean portalrequestconfirmation)
	{
		setPortalRequestConfirmation(getContext(), portalrequestconfirmation);
	}

	/**
	 * Set value of PortalRequestConfirmation
	 * @param context
	 * @param portalrequestconfirmation
	 */
	public final void setPortalRequestConfirmation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean portalrequestconfirmation)
	{
		getMendixObject().setValue(context, MemberNames.PortalRequestConfirmation.toString(), portalrequestconfirmation);
	}

	/**
	 * Set value of PortalPanelPreference
	 * @param portalpanelpreference
	 */
	public final mendix.proxies.StartPanelPreference getPortalPanelPreference()
	{
		return getPortalPanelPreference(getContext());
	}

	/**
	 * @param context
	 * @return value of PortalPanelPreference
	 */
	public final mendix.proxies.StartPanelPreference getPortalPanelPreference(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.PortalPanelPreference.toString());
		if (obj == null)
			return null;

		return mendix.proxies.StartPanelPreference.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of PortalPanelPreference
	 * @param portalpanelpreference
	 */
	public final void setPortalPanelPreference(mendix.proxies.StartPanelPreference portalpanelpreference)
	{
		setPortalPanelPreference(getContext(), portalpanelpreference);
	}

	/**
	 * Set value of PortalPanelPreference
	 * @param context
	 * @param portalpanelpreference
	 */
	public final void setPortalPanelPreference(com.mendix.systemwideinterfaces.core.IContext context, mendix.proxies.StartPanelPreference portalpanelpreference)
	{
		if (portalpanelpreference != null)
			getMendixObject().setValue(context, MemberNames.PortalPanelPreference.toString(), portalpanelpreference.toString());
		else
			getMendixObject().setValue(context, MemberNames.PortalPanelPreference.toString(), null);
	}

	/**
	 * Set value of ProcessLandingPage
	 * @param processlandingpage
	 */
	public final mendix.proxies.ProcessLogonLandingPage getProcessLandingPage()
	{
		return getProcessLandingPage(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessLandingPage
	 */
	public final mendix.proxies.ProcessLogonLandingPage getProcessLandingPage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ProcessLandingPage.toString());
		if (obj == null)
			return null;

		return mendix.proxies.ProcessLogonLandingPage.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ProcessLandingPage
	 * @param processlandingpage
	 */
	public final void setProcessLandingPage(mendix.proxies.ProcessLogonLandingPage processlandingpage)
	{
		setProcessLandingPage(getContext(), processlandingpage);
	}

	/**
	 * Set value of ProcessLandingPage
	 * @param context
	 * @param processlandingpage
	 */
	public final void setProcessLandingPage(com.mendix.systemwideinterfaces.core.IContext context, mendix.proxies.ProcessLogonLandingPage processlandingpage)
	{
		if (processlandingpage != null)
			getMendixObject().setValue(context, MemberNames.ProcessLandingPage.toString(), processlandingpage.toString());
		else
			getMendixObject().setValue(context, MemberNames.ProcessLandingPage.toString(), null);
	}

	/**
	 * Set value of RequestCreation
	 * @param requestcreation
	 */
	public final process.proxies.RequestCreation getRequestCreation()
	{
		return getRequestCreation(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestCreation
	 */
	public final process.proxies.RequestCreation getRequestCreation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.RequestCreation.toString());
		if (obj == null)
			return null;

		return process.proxies.RequestCreation.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of RequestCreation
	 * @param requestcreation
	 */
	public final void setRequestCreation(process.proxies.RequestCreation requestcreation)
	{
		setRequestCreation(getContext(), requestcreation);
	}

	/**
	 * Set value of RequestCreation
	 * @param context
	 * @param requestcreation
	 */
	public final void setRequestCreation(com.mendix.systemwideinterfaces.core.IContext context, process.proxies.RequestCreation requestcreation)
	{
		if (requestcreation != null)
			getMendixObject().setValue(context, MemberNames.RequestCreation.toString(), requestcreation.toString());
		else
			getMendixObject().setValue(context, MemberNames.RequestCreation.toString(), null);
	}

	/**
	 * Set value of ShowTasks
	 * @param showtasks
	 */
	public final process.proxies.SetShowTasksFunction getShowTasks()
	{
		return getShowTasks(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowTasks
	 */
	public final process.proxies.SetShowTasksFunction getShowTasks(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ShowTasks.toString());
		if (obj == null)
			return null;

		return process.proxies.SetShowTasksFunction.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ShowTasks
	 * @param showtasks
	 */
	public final void setShowTasks(process.proxies.SetShowTasksFunction showtasks)
	{
		setShowTasks(getContext(), showtasks);
	}

	/**
	 * Set value of ShowTasks
	 * @param context
	 * @param showtasks
	 */
	public final void setShowTasks(com.mendix.systemwideinterfaces.core.IContext context, process.proxies.SetShowTasksFunction showtasks)
	{
		if (showtasks != null)
			getMendixObject().setValue(context, MemberNames.ShowTasks.toString(), showtasks.toString());
		else
			getMendixObject().setValue(context, MemberNames.ShowTasks.toString(), null);
	}

	/**
	 * Set value of StartPanelPreference
	 * @param startpanelpreference
	 */
	public final mendix.proxies.StartPanelPreference getStartPanelPreference()
	{
		return getStartPanelPreference(getContext());
	}

	/**
	 * @param context
	 * @return value of StartPanelPreference
	 */
	public final mendix.proxies.StartPanelPreference getStartPanelPreference(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.StartPanelPreference.toString());
		if (obj == null)
			return null;

		return mendix.proxies.StartPanelPreference.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of StartPanelPreference
	 * @param startpanelpreference
	 */
	public final void setStartPanelPreference(mendix.proxies.StartPanelPreference startpanelpreference)
	{
		setStartPanelPreference(getContext(), startpanelpreference);
	}

	/**
	 * Set value of StartPanelPreference
	 * @param context
	 * @param startpanelpreference
	 */
	public final void setStartPanelPreference(com.mendix.systemwideinterfaces.core.IContext context, mendix.proxies.StartPanelPreference startpanelpreference)
	{
		if (startpanelpreference != null)
			getMendixObject().setValue(context, MemberNames.StartPanelPreference.toString(), startpanelpreference.toString());
		else
			getMendixObject().setValue(context, MemberNames.StartPanelPreference.toString(), null);
	}

	/**
	 * @return value of ProcessRequestConfirmation
	 */
	public final java.lang.Boolean getProcessRequestConfirmation()
	{
		return getProcessRequestConfirmation(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessRequestConfirmation
	 */
	public final java.lang.Boolean getProcessRequestConfirmation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ProcessRequestConfirmation.toString());
	}

	/**
	 * Set value of ProcessRequestConfirmation
	 * @param processrequestconfirmation
	 */
	public final void setProcessRequestConfirmation(java.lang.Boolean processrequestconfirmation)
	{
		setProcessRequestConfirmation(getContext(), processrequestconfirmation);
	}

	/**
	 * Set value of ProcessRequestConfirmation
	 * @param context
	 * @param processrequestconfirmation
	 */
	public final void setProcessRequestConfirmation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean processrequestconfirmation)
	{
		getMendixObject().setValue(context, MemberNames.ProcessRequestConfirmation.toString(), processrequestconfirmation);
	}

	/**
	 * @return value of ShowKnowledgeFavouritesOnly
	 */
	public final java.lang.Boolean getShowKnowledgeFavouritesOnly()
	{
		return getShowKnowledgeFavouritesOnly(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowKnowledgeFavouritesOnly
	 */
	public final java.lang.Boolean getShowKnowledgeFavouritesOnly(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowKnowledgeFavouritesOnly.toString());
	}

	/**
	 * Set value of ShowKnowledgeFavouritesOnly
	 * @param showknowledgefavouritesonly
	 */
	public final void setShowKnowledgeFavouritesOnly(java.lang.Boolean showknowledgefavouritesonly)
	{
		setShowKnowledgeFavouritesOnly(getContext(), showknowledgefavouritesonly);
	}

	/**
	 * Set value of ShowKnowledgeFavouritesOnly
	 * @param context
	 * @param showknowledgefavouritesonly
	 */
	public final void setShowKnowledgeFavouritesOnly(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showknowledgefavouritesonly)
	{
		getMendixObject().setValue(context, MemberNames.ShowKnowledgeFavouritesOnly.toString(), showknowledgefavouritesonly);
	}

	/**
	 * @return value of AccountPreferences_Account
	 */
	public final mendix.proxies.Account getAccountPreferences_Account() throws com.mendix.core.CoreException
	{
		return getAccountPreferences_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of AccountPreferences_Account
	 */
	public final mendix.proxies.Account getAccountPreferences_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mendix.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AccountPreferences_Account.toString());
		if (identifier != null)
			result = mendix.proxies.Account.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AccountPreferences_Account
	 * @param accountpreferences_account
	 */
	public final void setAccountPreferences_Account(mendix.proxies.Account accountpreferences_account)
	{
		setAccountPreferences_Account(getContext(), accountpreferences_account);
	}

	/**
	 * Set value of AccountPreferences_Account
	 * @param context
	 * @param accountpreferences_account
	 */
	public final void setAccountPreferences_Account(com.mendix.systemwideinterfaces.core.IContext context, mendix.proxies.Account accountpreferences_account)
	{
		if (accountpreferences_account == null)
			getMendixObject().setValue(context, MemberNames.AccountPreferences_Account.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AccountPreferences_Account.toString(), accountpreferences_account.getMendixObject().getId());
	}

	/**
	 * @return value of AccountPreferences_KnowledgeSearch
	 */
	public final mendix.proxies.KnowledgeSearch getAccountPreferences_KnowledgeSearch() throws com.mendix.core.CoreException
	{
		return getAccountPreferences_KnowledgeSearch(getContext());
	}

	/**
	 * @param context
	 * @return value of AccountPreferences_KnowledgeSearch
	 */
	public final mendix.proxies.KnowledgeSearch getAccountPreferences_KnowledgeSearch(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mendix.proxies.KnowledgeSearch result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AccountPreferences_KnowledgeSearch.toString());
		if (identifier != null)
			result = mendix.proxies.KnowledgeSearch.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AccountPreferences_KnowledgeSearch
	 * @param accountpreferences_knowledgesearch
	 */
	public final void setAccountPreferences_KnowledgeSearch(mendix.proxies.KnowledgeSearch accountpreferences_knowledgesearch)
	{
		setAccountPreferences_KnowledgeSearch(getContext(), accountpreferences_knowledgesearch);
	}

	/**
	 * Set value of AccountPreferences_KnowledgeSearch
	 * @param context
	 * @param accountpreferences_knowledgesearch
	 */
	public final void setAccountPreferences_KnowledgeSearch(com.mendix.systemwideinterfaces.core.IContext context, mendix.proxies.KnowledgeSearch accountpreferences_knowledgesearch)
	{
		if (accountpreferences_knowledgesearch == null)
			getMendixObject().setValue(context, MemberNames.AccountPreferences_KnowledgeSearch.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AccountPreferences_KnowledgeSearch.toString(), accountpreferences_knowledgesearch.getMendixObject().getId());
	}

	/**
	 * @return value of AccountPreferences_Request
	 */
	public final process.proxies.Request getAccountPreferences_Request() throws com.mendix.core.CoreException
	{
		return getAccountPreferences_Request(getContext());
	}

	/**
	 * @param context
	 * @return value of AccountPreferences_Request
	 */
	public final process.proxies.Request getAccountPreferences_Request(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		process.proxies.Request result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AccountPreferences_Request.toString());
		if (identifier != null)
			result = process.proxies.Request.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AccountPreferences_Request
	 * @param accountpreferences_request
	 */
	public final void setAccountPreferences_Request(process.proxies.Request accountpreferences_request)
	{
		setAccountPreferences_Request(getContext(), accountpreferences_request);
	}

	/**
	 * Set value of AccountPreferences_Request
	 * @param context
	 * @param accountpreferences_request
	 */
	public final void setAccountPreferences_Request(com.mendix.systemwideinterfaces.core.IContext context, process.proxies.Request accountpreferences_request)
	{
		if (accountpreferences_request == null)
			getMendixObject().setValue(context, MemberNames.AccountPreferences_Request.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AccountPreferences_Request.toString(), accountpreferences_request.getMendixObject().getId());
	}

	/**
	 * @return value of AccountPreferences_Knowledge
	 */
	public final java.util.List<knowledgemanagement.proxies.Knowledge> getAccountPreferences_Knowledge() throws com.mendix.core.CoreException
	{
		return getAccountPreferences_Knowledge(getContext());
	}

	/**
	 * @param context
	 * @return value of AccountPreferences_Knowledge
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<knowledgemanagement.proxies.Knowledge> getAccountPreferences_Knowledge(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<knowledgemanagement.proxies.Knowledge> result = new java.util.ArrayList<knowledgemanagement.proxies.Knowledge>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.AccountPreferences_Knowledge.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(knowledgemanagement.proxies.Knowledge.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of AccountPreferences_Knowledge
	 * @param accountpreferences_knowledge
	 */
	public final void setAccountPreferences_Knowledge(java.util.List<knowledgemanagement.proxies.Knowledge> accountpreferences_knowledge)
	{
		setAccountPreferences_Knowledge(getContext(), accountpreferences_knowledge);
	}

	/**
	 * Set value of AccountPreferences_Knowledge
	 * @param context
	 * @param accountpreferences_knowledge
	 */
	public final void setAccountPreferences_Knowledge(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<knowledgemanagement.proxies.Knowledge> accountpreferences_knowledge)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (knowledgemanagement.proxies.Knowledge proxyObject : accountpreferences_knowledge)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.AccountPreferences_Knowledge.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return accountPreferencesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mendix.proxies.AccountPreferences that = (mendix.proxies.AccountPreferences) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Mendix.AccountPreferences";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
