// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mendix.proxies;

public class Day
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dayMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Mendix.Day";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DayStart("DayStart"),
		DayEnd("DayEnd"),
		DayString("DayString"),
		DayNumber("DayNumber"),
		WeekString("WeekString"),
		MonthString("MonthString"),
		QuarterString("QuarterString"),
		YearString("YearString");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Day(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Mendix.Day"));
	}

	protected Day(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dayMendixObject)
	{
		if (dayMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Mendix.Day", dayMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Mendix.Day");

		this.dayMendixObject = dayMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Day.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static mendix.proxies.Day initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mendix.proxies.Day.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mendix.proxies.Day initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mendix.proxies.Day(context, mendixObject);
	}

	public static mendix.proxies.Day load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mendix.proxies.Day.initialize(context, mendixObject);
	}

	public static java.util.List<mendix.proxies.Day> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<mendix.proxies.Day> result = new java.util.ArrayList<mendix.proxies.Day>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Mendix.Day" + xpathConstraint))
			result.add(mendix.proxies.Day.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DayStart
	 */
	public final java.util.Date getDayStart()
	{
		return getDayStart(getContext());
	}

	/**
	 * @param context
	 * @return value of DayStart
	 */
	public final java.util.Date getDayStart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DayStart.toString());
	}

	/**
	 * Set value of DayStart
	 * @param daystart
	 */
	public final void setDayStart(java.util.Date daystart)
	{
		setDayStart(getContext(), daystart);
	}

	/**
	 * Set value of DayStart
	 * @param context
	 * @param daystart
	 */
	public final void setDayStart(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date daystart)
	{
		getMendixObject().setValue(context, MemberNames.DayStart.toString(), daystart);
	}

	/**
	 * @return value of DayEnd
	 */
	public final java.util.Date getDayEnd()
	{
		return getDayEnd(getContext());
	}

	/**
	 * @param context
	 * @return value of DayEnd
	 */
	public final java.util.Date getDayEnd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DayEnd.toString());
	}

	/**
	 * Set value of DayEnd
	 * @param dayend
	 */
	public final void setDayEnd(java.util.Date dayend)
	{
		setDayEnd(getContext(), dayend);
	}

	/**
	 * Set value of DayEnd
	 * @param context
	 * @param dayend
	 */
	public final void setDayEnd(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dayend)
	{
		getMendixObject().setValue(context, MemberNames.DayEnd.toString(), dayend);
	}

	/**
	 * @return value of DayString
	 */
	public final java.lang.String getDayString()
	{
		return getDayString(getContext());
	}

	/**
	 * @param context
	 * @return value of DayString
	 */
	public final java.lang.String getDayString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DayString.toString());
	}

	/**
	 * Set value of DayString
	 * @param daystring
	 */
	public final void setDayString(java.lang.String daystring)
	{
		setDayString(getContext(), daystring);
	}

	/**
	 * Set value of DayString
	 * @param context
	 * @param daystring
	 */
	public final void setDayString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String daystring)
	{
		getMendixObject().setValue(context, MemberNames.DayString.toString(), daystring);
	}

	/**
	 * @return value of DayNumber
	 */
	public final java.lang.Integer getDayNumber()
	{
		return getDayNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of DayNumber
	 */
	public final java.lang.Integer getDayNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.DayNumber.toString());
	}

	/**
	 * Set value of DayNumber
	 * @param daynumber
	 */
	public final void setDayNumber(java.lang.Integer daynumber)
	{
		setDayNumber(getContext(), daynumber);
	}

	/**
	 * Set value of DayNumber
	 * @param context
	 * @param daynumber
	 */
	public final void setDayNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer daynumber)
	{
		getMendixObject().setValue(context, MemberNames.DayNumber.toString(), daynumber);
	}

	/**
	 * @return value of WeekString
	 */
	public final java.lang.String getWeekString()
	{
		return getWeekString(getContext());
	}

	/**
	 * @param context
	 * @return value of WeekString
	 */
	public final java.lang.String getWeekString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WeekString.toString());
	}

	/**
	 * Set value of WeekString
	 * @param weekstring
	 */
	public final void setWeekString(java.lang.String weekstring)
	{
		setWeekString(getContext(), weekstring);
	}

	/**
	 * Set value of WeekString
	 * @param context
	 * @param weekstring
	 */
	public final void setWeekString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String weekstring)
	{
		getMendixObject().setValue(context, MemberNames.WeekString.toString(), weekstring);
	}

	/**
	 * @return value of MonthString
	 */
	public final java.lang.String getMonthString()
	{
		return getMonthString(getContext());
	}

	/**
	 * @param context
	 * @return value of MonthString
	 */
	public final java.lang.String getMonthString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MonthString.toString());
	}

	/**
	 * Set value of MonthString
	 * @param monthstring
	 */
	public final void setMonthString(java.lang.String monthstring)
	{
		setMonthString(getContext(), monthstring);
	}

	/**
	 * Set value of MonthString
	 * @param context
	 * @param monthstring
	 */
	public final void setMonthString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String monthstring)
	{
		getMendixObject().setValue(context, MemberNames.MonthString.toString(), monthstring);
	}

	/**
	 * @return value of QuarterString
	 */
	public final java.lang.String getQuarterString()
	{
		return getQuarterString(getContext());
	}

	/**
	 * @param context
	 * @return value of QuarterString
	 */
	public final java.lang.String getQuarterString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.QuarterString.toString());
	}

	/**
	 * Set value of QuarterString
	 * @param quarterstring
	 */
	public final void setQuarterString(java.lang.String quarterstring)
	{
		setQuarterString(getContext(), quarterstring);
	}

	/**
	 * Set value of QuarterString
	 * @param context
	 * @param quarterstring
	 */
	public final void setQuarterString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String quarterstring)
	{
		getMendixObject().setValue(context, MemberNames.QuarterString.toString(), quarterstring);
	}

	/**
	 * @return value of YearString
	 */
	public final java.lang.String getYearString()
	{
		return getYearString(getContext());
	}

	/**
	 * @param context
	 * @return value of YearString
	 */
	public final java.lang.String getYearString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.YearString.toString());
	}

	/**
	 * Set value of YearString
	 * @param yearstring
	 */
	public final void setYearString(java.lang.String yearstring)
	{
		setYearString(getContext(), yearstring);
	}

	/**
	 * Set value of YearString
	 * @param context
	 * @param yearstring
	 */
	public final void setYearString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String yearstring)
	{
		getMendixObject().setValue(context, MemberNames.YearString.toString(), yearstring);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dayMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mendix.proxies.Day that = (mendix.proxies.Day) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Mendix.Day";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
