// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mendix.proxies;

public class Month
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject monthMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Mendix.Month";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MonthStart("MonthStart"),
		MonthEnd("MonthEnd"),
		MonthString("MonthString"),
		YearString("YearString"),
		MonthNumber("MonthNumber");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Month(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Mendix.Month"));
	}

	protected Month(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject monthMendixObject)
	{
		if (monthMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Mendix.Month", monthMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Mendix.Month");

		this.monthMendixObject = monthMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Month.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static mendix.proxies.Month initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mendix.proxies.Month.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mendix.proxies.Month initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mendix.proxies.Month(context, mendixObject);
	}

	public static mendix.proxies.Month load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mendix.proxies.Month.initialize(context, mendixObject);
	}

	public static java.util.List<mendix.proxies.Month> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<mendix.proxies.Month> result = new java.util.ArrayList<mendix.proxies.Month>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Mendix.Month" + xpathConstraint))
			result.add(mendix.proxies.Month.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of MonthStart
	 */
	public final java.util.Date getMonthStart()
	{
		return getMonthStart(getContext());
	}

	/**
	 * @param context
	 * @return value of MonthStart
	 */
	public final java.util.Date getMonthStart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.MonthStart.toString());
	}

	/**
	 * Set value of MonthStart
	 * @param monthstart
	 */
	public final void setMonthStart(java.util.Date monthstart)
	{
		setMonthStart(getContext(), monthstart);
	}

	/**
	 * Set value of MonthStart
	 * @param context
	 * @param monthstart
	 */
	public final void setMonthStart(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date monthstart)
	{
		getMendixObject().setValue(context, MemberNames.MonthStart.toString(), monthstart);
	}

	/**
	 * @return value of MonthEnd
	 */
	public final java.util.Date getMonthEnd()
	{
		return getMonthEnd(getContext());
	}

	/**
	 * @param context
	 * @return value of MonthEnd
	 */
	public final java.util.Date getMonthEnd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.MonthEnd.toString());
	}

	/**
	 * Set value of MonthEnd
	 * @param monthend
	 */
	public final void setMonthEnd(java.util.Date monthend)
	{
		setMonthEnd(getContext(), monthend);
	}

	/**
	 * Set value of MonthEnd
	 * @param context
	 * @param monthend
	 */
	public final void setMonthEnd(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date monthend)
	{
		getMendixObject().setValue(context, MemberNames.MonthEnd.toString(), monthend);
	}

	/**
	 * @return value of MonthString
	 */
	public final java.lang.String getMonthString()
	{
		return getMonthString(getContext());
	}

	/**
	 * @param context
	 * @return value of MonthString
	 */
	public final java.lang.String getMonthString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MonthString.toString());
	}

	/**
	 * Set value of MonthString
	 * @param monthstring
	 */
	public final void setMonthString(java.lang.String monthstring)
	{
		setMonthString(getContext(), monthstring);
	}

	/**
	 * Set value of MonthString
	 * @param context
	 * @param monthstring
	 */
	public final void setMonthString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String monthstring)
	{
		getMendixObject().setValue(context, MemberNames.MonthString.toString(), monthstring);
	}

	/**
	 * @return value of YearString
	 */
	public final java.lang.String getYearString()
	{
		return getYearString(getContext());
	}

	/**
	 * @param context
	 * @return value of YearString
	 */
	public final java.lang.String getYearString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.YearString.toString());
	}

	/**
	 * Set value of YearString
	 * @param yearstring
	 */
	public final void setYearString(java.lang.String yearstring)
	{
		setYearString(getContext(), yearstring);
	}

	/**
	 * Set value of YearString
	 * @param context
	 * @param yearstring
	 */
	public final void setYearString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String yearstring)
	{
		getMendixObject().setValue(context, MemberNames.YearString.toString(), yearstring);
	}

	/**
	 * @return value of MonthNumber
	 */
	public final java.lang.Integer getMonthNumber()
	{
		return getMonthNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of MonthNumber
	 */
	public final java.lang.Integer getMonthNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MonthNumber.toString());
	}

	/**
	 * Set value of MonthNumber
	 * @param monthnumber
	 */
	public final void setMonthNumber(java.lang.Integer monthnumber)
	{
		setMonthNumber(getContext(), monthnumber);
	}

	/**
	 * Set value of MonthNumber
	 * @param context
	 * @param monthnumber
	 */
	public final void setMonthNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer monthnumber)
	{
		getMendixObject().setValue(context, MemberNames.MonthNumber.toString(), monthnumber);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return monthMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mendix.proxies.Month that = (mendix.proxies.Month) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Mendix.Month";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
