// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package serviceroutes.proxies;

public class Node
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject nodeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ServiceRoutes.Node";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NodeID("NodeID"),
		Name("Name"),
		NodeType("NodeType"),
		xPosition("xPosition"),
		yPosition("yPosition"),
		MinOrder("MinOrder"),
		MaxOrder("MaxOrder"),
		Process("Process"),
		Node_ServiceRouteGraph("ServiceRoutes.Node_ServiceRouteGraph"),
		Node_Contract("ServiceRoutes.Node_Contract"),
		Node_Service("ServiceRoutes.Node_Service"),
		Node_ConfigurationItem("ServiceRoutes.Node_ConfigurationItem");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Node(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ServiceRoutes.Node"));
	}

	protected Node(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject nodeMendixObject)
	{
		if (nodeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("ServiceRoutes.Node", nodeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ServiceRoutes.Node");

		this.nodeMendixObject = nodeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Node.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static serviceroutes.proxies.Node initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return serviceroutes.proxies.Node.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static serviceroutes.proxies.Node initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new serviceroutes.proxies.Node(context, mendixObject);
	}

	public static serviceroutes.proxies.Node load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return serviceroutes.proxies.Node.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of NodeID
	 */
	public final java.lang.Integer getNodeID()
	{
		return getNodeID(getContext());
	}

	/**
	 * @param context
	 * @return value of NodeID
	 */
	public final java.lang.Integer getNodeID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NodeID.toString());
	}

	/**
	 * Set value of NodeID
	 * @param nodeid
	 */
	public final void setNodeID(java.lang.Integer nodeid)
	{
		setNodeID(getContext(), nodeid);
	}

	/**
	 * Set value of NodeID
	 * @param context
	 * @param nodeid
	 */
	public final void setNodeID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer nodeid)
	{
		getMendixObject().setValue(context, MemberNames.NodeID.toString(), nodeid);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * Set value of NodeType
	 * @param nodetype
	 */
	public final serviceroutes.proxies.NodeTypeEnum getNodeType()
	{
		return getNodeType(getContext());
	}

	/**
	 * @param context
	 * @return value of NodeType
	 */
	public final serviceroutes.proxies.NodeTypeEnum getNodeType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.NodeType.toString());
		if (obj == null)
			return null;

		return serviceroutes.proxies.NodeTypeEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of NodeType
	 * @param nodetype
	 */
	public final void setNodeType(serviceroutes.proxies.NodeTypeEnum nodetype)
	{
		setNodeType(getContext(), nodetype);
	}

	/**
	 * Set value of NodeType
	 * @param context
	 * @param nodetype
	 */
	public final void setNodeType(com.mendix.systemwideinterfaces.core.IContext context, serviceroutes.proxies.NodeTypeEnum nodetype)
	{
		if (nodetype != null)
			getMendixObject().setValue(context, MemberNames.NodeType.toString(), nodetype.toString());
		else
			getMendixObject().setValue(context, MemberNames.NodeType.toString(), null);
	}

	/**
	 * @return value of xPosition
	 */
	public final java.lang.Integer getxPosition()
	{
		return getxPosition(getContext());
	}

	/**
	 * @param context
	 * @return value of xPosition
	 */
	public final java.lang.Integer getxPosition(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.xPosition.toString());
	}

	/**
	 * Set value of xPosition
	 * @param xposition
	 */
	public final void setxPosition(java.lang.Integer xposition)
	{
		setxPosition(getContext(), xposition);
	}

	/**
	 * Set value of xPosition
	 * @param context
	 * @param xposition
	 */
	public final void setxPosition(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer xposition)
	{
		getMendixObject().setValue(context, MemberNames.xPosition.toString(), xposition);
	}

	/**
	 * @return value of yPosition
	 */
	public final java.lang.Integer getyPosition()
	{
		return getyPosition(getContext());
	}

	/**
	 * @param context
	 * @return value of yPosition
	 */
	public final java.lang.Integer getyPosition(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.yPosition.toString());
	}

	/**
	 * Set value of yPosition
	 * @param yposition
	 */
	public final void setyPosition(java.lang.Integer yposition)
	{
		setyPosition(getContext(), yposition);
	}

	/**
	 * Set value of yPosition
	 * @param context
	 * @param yposition
	 */
	public final void setyPosition(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer yposition)
	{
		getMendixObject().setValue(context, MemberNames.yPosition.toString(), yposition);
	}

	/**
	 * @return value of MinOrder
	 */
	public final java.lang.Integer getMinOrder()
	{
		return getMinOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of MinOrder
	 */
	public final java.lang.Integer getMinOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MinOrder.toString());
	}

	/**
	 * Set value of MinOrder
	 * @param minorder
	 */
	public final void setMinOrder(java.lang.Integer minorder)
	{
		setMinOrder(getContext(), minorder);
	}

	/**
	 * Set value of MinOrder
	 * @param context
	 * @param minorder
	 */
	public final void setMinOrder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer minorder)
	{
		getMendixObject().setValue(context, MemberNames.MinOrder.toString(), minorder);
	}

	/**
	 * @return value of MaxOrder
	 */
	public final java.lang.Integer getMaxOrder()
	{
		return getMaxOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxOrder
	 */
	public final java.lang.Integer getMaxOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaxOrder.toString());
	}

	/**
	 * Set value of MaxOrder
	 * @param maxorder
	 */
	public final void setMaxOrder(java.lang.Integer maxorder)
	{
		setMaxOrder(getContext(), maxorder);
	}

	/**
	 * Set value of MaxOrder
	 * @param context
	 * @param maxorder
	 */
	public final void setMaxOrder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maxorder)
	{
		getMendixObject().setValue(context, MemberNames.MaxOrder.toString(), maxorder);
	}

	/**
	 * Set value of Process
	 * @param process
	 */
	public final slm.proxies.ProcessType getProcess()
	{
		return getProcess(getContext());
	}

	/**
	 * @param context
	 * @return value of Process
	 */
	public final slm.proxies.ProcessType getProcess(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Process.toString());
		if (obj == null)
			return null;

		return slm.proxies.ProcessType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Process
	 * @param process
	 */
	public final void setProcess(slm.proxies.ProcessType process)
	{
		setProcess(getContext(), process);
	}

	/**
	 * Set value of Process
	 * @param context
	 * @param process
	 */
	public final void setProcess(com.mendix.systemwideinterfaces.core.IContext context, slm.proxies.ProcessType process)
	{
		if (process != null)
			getMendixObject().setValue(context, MemberNames.Process.toString(), process.toString());
		else
			getMendixObject().setValue(context, MemberNames.Process.toString(), null);
	}

	/**
	 * @return value of Node_ServiceRouteGraph
	 */
	public final serviceroutes.proxies.ServiceRouteGraph getNode_ServiceRouteGraph() throws com.mendix.core.CoreException
	{
		return getNode_ServiceRouteGraph(getContext());
	}

	/**
	 * @param context
	 * @return value of Node_ServiceRouteGraph
	 */
	public final serviceroutes.proxies.ServiceRouteGraph getNode_ServiceRouteGraph(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		serviceroutes.proxies.ServiceRouteGraph result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Node_ServiceRouteGraph.toString());
		if (identifier != null)
			result = serviceroutes.proxies.ServiceRouteGraph.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Node_ServiceRouteGraph
	 * @param node_serviceroutegraph
	 */
	public final void setNode_ServiceRouteGraph(serviceroutes.proxies.ServiceRouteGraph node_serviceroutegraph)
	{
		setNode_ServiceRouteGraph(getContext(), node_serviceroutegraph);
	}

	/**
	 * Set value of Node_ServiceRouteGraph
	 * @param context
	 * @param node_serviceroutegraph
	 */
	public final void setNode_ServiceRouteGraph(com.mendix.systemwideinterfaces.core.IContext context, serviceroutes.proxies.ServiceRouteGraph node_serviceroutegraph)
	{
		if (node_serviceroutegraph == null)
			getMendixObject().setValue(context, MemberNames.Node_ServiceRouteGraph.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Node_ServiceRouteGraph.toString(), node_serviceroutegraph.getMendixObject().getId());
	}

	/**
	 * @return value of Node_Contract
	 */
	public final slm.proxies.Contract getNode_Contract() throws com.mendix.core.CoreException
	{
		return getNode_Contract(getContext());
	}

	/**
	 * @param context
	 * @return value of Node_Contract
	 */
	public final slm.proxies.Contract getNode_Contract(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		slm.proxies.Contract result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Node_Contract.toString());
		if (identifier != null)
			result = slm.proxies.Contract.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Node_Contract
	 * @param node_contract
	 */
	public final void setNode_Contract(slm.proxies.Contract node_contract)
	{
		setNode_Contract(getContext(), node_contract);
	}

	/**
	 * Set value of Node_Contract
	 * @param context
	 * @param node_contract
	 */
	public final void setNode_Contract(com.mendix.systemwideinterfaces.core.IContext context, slm.proxies.Contract node_contract)
	{
		if (node_contract == null)
			getMendixObject().setValue(context, MemberNames.Node_Contract.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Node_Contract.toString(), node_contract.getMendixObject().getId());
	}

	/**
	 * @return value of Node_Service
	 */
	public final slm.proxies.Service getNode_Service() throws com.mendix.core.CoreException
	{
		return getNode_Service(getContext());
	}

	/**
	 * @param context
	 * @return value of Node_Service
	 */
	public final slm.proxies.Service getNode_Service(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		slm.proxies.Service result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Node_Service.toString());
		if (identifier != null)
			result = slm.proxies.Service.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Node_Service
	 * @param node_service
	 */
	public final void setNode_Service(slm.proxies.Service node_service)
	{
		setNode_Service(getContext(), node_service);
	}

	/**
	 * Set value of Node_Service
	 * @param context
	 * @param node_service
	 */
	public final void setNode_Service(com.mendix.systemwideinterfaces.core.IContext context, slm.proxies.Service node_service)
	{
		if (node_service == null)
			getMendixObject().setValue(context, MemberNames.Node_Service.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Node_Service.toString(), node_service.getMendixObject().getId());
	}

	/**
	 * @return value of Node_ConfigurationItem
	 */
	public final cmdb.proxies.ConfigurationItem getNode_ConfigurationItem() throws com.mendix.core.CoreException
	{
		return getNode_ConfigurationItem(getContext());
	}

	/**
	 * @param context
	 * @return value of Node_ConfigurationItem
	 */
	public final cmdb.proxies.ConfigurationItem getNode_ConfigurationItem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmdb.proxies.ConfigurationItem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Node_ConfigurationItem.toString());
		if (identifier != null)
			result = cmdb.proxies.ConfigurationItem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Node_ConfigurationItem
	 * @param node_configurationitem
	 */
	public final void setNode_ConfigurationItem(cmdb.proxies.ConfigurationItem node_configurationitem)
	{
		setNode_ConfigurationItem(getContext(), node_configurationitem);
	}

	/**
	 * Set value of Node_ConfigurationItem
	 * @param context
	 * @param node_configurationitem
	 */
	public final void setNode_ConfigurationItem(com.mendix.systemwideinterfaces.core.IContext context, cmdb.proxies.ConfigurationItem node_configurationitem)
	{
		if (node_configurationitem == null)
			getMendixObject().setValue(context, MemberNames.Node_ConfigurationItem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Node_ConfigurationItem.toString(), node_configurationitem.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return nodeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final serviceroutes.proxies.Node that = (serviceroutes.proxies.Node) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ServiceRoutes.Node";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
