// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package interfaceshared.proxies;

public class DatabaseProcessingAttempt extends interfaceshared.proxies.ProcessingAttempt
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "InterfaceShared.DatabaseProcessingAttempt";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UU95_Processed("UU95_Processed"),
		ProcessAsynchronous("ProcessAsynchronous"),
		AsynchronousProcessingComplete("AsynchronousProcessingComplete"),
		AsynchronousConfirmationMessageProcessingComplete("AsynchronousConfirmationMessageProcessingComplete"),
		Successful("Successful"),
		ManualAttempt("ManualAttempt"),
		Log("Log"),
		ShowCritical("ShowCritical"),
		ShowError("ShowError"),
		ShowWarming("ShowWarming"),
		ShowInfo("ShowInfo"),
		ShowDebug("ShowDebug"),
		ShowTrace("ShowTrace"),
		ProcessingAttempt_OutgoingConfirmation("InterfaceShared.ProcessingAttempt_OutgoingConfirmation"),
		ProcessingAttempt_Response("InterfaceShared.ProcessingAttempt_Response"),
		Attempt_Message("InterfaceShared.Attempt_Message");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DatabaseProcessingAttempt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "InterfaceShared.DatabaseProcessingAttempt"));
	}

	protected DatabaseProcessingAttempt(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject databaseProcessingAttemptMendixObject)
	{
		super(context, databaseProcessingAttemptMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("InterfaceShared.DatabaseProcessingAttempt", databaseProcessingAttemptMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a InterfaceShared.DatabaseProcessingAttempt");
	}

	/**
	 * @deprecated Use 'DatabaseProcessingAttempt.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static interfaceshared.proxies.DatabaseProcessingAttempt initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return interfaceshared.proxies.DatabaseProcessingAttempt.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static interfaceshared.proxies.DatabaseProcessingAttempt initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new interfaceshared.proxies.DatabaseProcessingAttempt(context, mendixObject);
	}

	public static interfaceshared.proxies.DatabaseProcessingAttempt load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return interfaceshared.proxies.DatabaseProcessingAttempt.initialize(context, mendixObject);
	}

	public static java.util.List<interfaceshared.proxies.DatabaseProcessingAttempt> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<interfaceshared.proxies.DatabaseProcessingAttempt> result = new java.util.ArrayList<interfaceshared.proxies.DatabaseProcessingAttempt>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//InterfaceShared.DatabaseProcessingAttempt" + xpathConstraint))
			result.add(interfaceshared.proxies.DatabaseProcessingAttempt.initialize(context, obj));
		return result;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final interfaceshared.proxies.DatabaseProcessingAttempt that = (interfaceshared.proxies.DatabaseProcessingAttempt) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "InterfaceShared.DatabaseProcessingAttempt";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
