// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package interfaceshared.proxies;

public enum FieldCode
{
	Location(new java.lang.String[][] { new java.lang.String[] { "en_US", "Location" }, new java.lang.String[] { "de_DE", "Standort " }, new java.lang.String[] { "nl_NL", "Locatie" } }),
	CI(new java.lang.String[][] { new java.lang.String[] { "en_US", "CI" }, new java.lang.String[] { "de_DE", "CI   " }, new java.lang.String[] { "nl_NL", "CI" } }),
	Delivering_Organisation(new java.lang.String[][] { new java.lang.String[] { "en_US", "Delivering Organisation" }, new java.lang.String[] { "de_DE", "Zuliefernde Organisationen" }, new java.lang.String[] { "nl_NL", "Toegewezen groep" } }),
	Receiving_Organisation(new java.lang.String[][] { new java.lang.String[] { "en_US", "Receiving Organisation" }, new java.lang.String[] { "de_DE", "Empfangende Organisation " }, new java.lang.String[] { "nl_NL", "Ontvangende organisatie" } }),
	Impact(new java.lang.String[][] { new java.lang.String[] { "en_US", "Impact" }, new java.lang.String[] { "de_DE", "Auswirkung  " }, new java.lang.String[] { "nl_NL", "Impact" } }),
	Urgency(new java.lang.String[][] { new java.lang.String[] { "en_US", "Urgency" }, new java.lang.String[] { "de_DE", "Dringlichkeit" }, new java.lang.String[] { "nl_NL", "Urgentie" } }),
	Service(new java.lang.String[][] { new java.lang.String[] { "en_US", "Type" }, new java.lang.String[] { "de_DE", "Service" }, new java.lang.String[] { "nl_NL", "Type" } }),
	Service_Process(new java.lang.String[][] { new java.lang.String[] { "en_US", "Service Process" }, new java.lang.String[] { "de_DE", "Serviceprozess" }, new java.lang.String[] { "nl_NL", "Service proces" } }),
	Person(new java.lang.String[][] { new java.lang.String[] { "en_US", "Person" }, new java.lang.String[] { "de_DE", "Person   " }, new java.lang.String[] { "nl_NL", "Persoon" } }),
	Person_Caller(new java.lang.String[][] { new java.lang.String[] { "en_US", "Person Caller" }, new java.lang.String[] { "de_DE", "Melder Person" }, new java.lang.String[] { "nl_NL", "Persoon melder" } }),
	Opening_Category(new java.lang.String[][] { new java.lang.String[] { "en_US", "Subject" }, new java.lang.String[] { "de_DE", "Offene Kategorie" }, new java.lang.String[] { "nl_NL", "Subject" } }),
	Closing_Category(new java.lang.String[][] { new java.lang.String[] { "en_US", "Closure Category" }, new java.lang.String[] { "nl_NL", "Afsluit" } }),
	Customer_Satisfaction(new java.lang.String[][] { new java.lang.String[] { "en_US", "Customer Satisfaction" }, new java.lang.String[] { "de_DE", "Kundenzufriedenheit " }, new java.lang.String[] { "nl_NL", "Klanttevredenheid" } }),
	State(new java.lang.String[][] { new java.lang.String[] { "en_US", "State" }, new java.lang.String[] { "nl_NL", "Status" } }),
	Phase(new java.lang.String[][] { new java.lang.String[] { "en_US", "Phase" }, new java.lang.String[] { "nl_NL", "Fase" } }),
	Short_Description(new java.lang.String[][] { new java.lang.String[] { "en_US", "Short Description" }, new java.lang.String[] { "nl_NL", "Korte omschrijving" } }),
	Actual_End_Time(new java.lang.String[][] { new java.lang.String[] { "en_US", "Actual End Time" }, new java.lang.String[] { "nl_NL", "Werkelijke eindtijd" } }),
	Solution_Description(new java.lang.String[][] { new java.lang.String[] { "en_US", "Solution Description" }, new java.lang.String[] { "nl_NL", "Oplosomschrijving" } }),
	Assigned_Person(new java.lang.String[][] { new java.lang.String[] { "en_US", "Assigned Person" }, new java.lang.String[] { "nl_NL", "Toegwezen persoon" } }),
	CI_Type(new java.lang.String[][] { new java.lang.String[] { "en_US", "CI Type" }, new java.lang.String[] { "nl_NL", "CI type" } }),
	Country(new java.lang.String[][] { new java.lang.String[] { "en_US", "Country" }, new java.lang.String[] { "nl_NL", "Land" } }),
	Problem_Type(new java.lang.String[][] { new java.lang.String[] { "en_US", "Problem Type" }, new java.lang.String[] { "nl_NL", "Probleem type" } }),
	Reason(new java.lang.String[][] { new java.lang.String[] { "en_US", "Reason" }, new java.lang.String[] { "nl_NL", "Reden" } }),
	Change_Type(new java.lang.String[][] { new java.lang.String[] { "en_US", "Change Type" }, new java.lang.String[] { "nl_NL", "Wijzigngstype" } }),
	Customer_Wish_Date(new java.lang.String[][] { new java.lang.String[] { "en_US", "Customer Wish Date" }, new java.lang.String[] { "nl_NL", "Gewenste datum klant" } }),
	Customer_Wish_Date_Reason(new java.lang.String[][] { new java.lang.String[] { "en_US", "Customer Wish Date Reason" }, new java.lang.String[] { "nl_NL", "Klant wens datum reden" } }),
	Scheduled_Start(new java.lang.String[][] { new java.lang.String[] { "en_US", "Scheduled Start" }, new java.lang.String[] { "nl_NL", "Geplande starttijd" } }),
	Scheduled_End(new java.lang.String[][] { new java.lang.String[] { "en_US", "Scheduled End" }, new java.lang.String[] { "nl_NL", "Geplande eindtijd" } }),
	Wish_Date_Start(new java.lang.String[][] { new java.lang.String[] { "en_US", "Requested Start Date" }, new java.lang.String[] { "nl_NL", "Gewenste startdaum" } }),
	Wish_Date_End(new java.lang.String[][] { new java.lang.String[] { "en_US", "Requested End Date" }, new java.lang.String[] { "nl_NL", "Gewenste einddatum" } }),
	Detail_Description(new java.lang.String[][] { new java.lang.String[] { "en_US", "Detail Description" }, new java.lang.String[] { "nl_NL", "Gedetailleerde omschrijving" } }),
	Pause_Reason(new java.lang.String[][] { new java.lang.String[] { "en_US", "Pause Reason" }, new java.lang.String[] { "nl_NL", "Pauze reden" } }),
	String_Value(new java.lang.String[][] { new java.lang.String[] { "en_US", "String Value" }, new java.lang.String[] { "nl_NL", "String waarde" } }),
	Organisation(new java.lang.String[][] { new java.lang.String[] { "en_US", "Organisation" }, new java.lang.String[] { "nl_NL", "Organisatie" } }),
	Language(new java.lang.String[][] { new java.lang.String[] { "en_US", "Language" }, new java.lang.String[] { "nl_NL", "Taal" } }),
	Time_Zone(new java.lang.String[][] { new java.lang.String[] { "en_US", "Time Zone" }, new java.lang.String[] { "nl_NL", "Tijdzone" } }),
	Locations(new java.lang.String[][] { new java.lang.String[] { "en_US", "Locations" }, new java.lang.String[] { "nl_NL", "Lokaties" } }),
	Customers(new java.lang.String[][] { new java.lang.String[] { "en_US", "Customers" }, new java.lang.String[] { "nl_NL", "Klanten" } }),
	Business_Groups(new java.lang.String[][] { new java.lang.String[] { "en_US", "Business Groups" }, new java.lang.String[] { "nl_NL", "Zakengroepen" } }),
	IUP(new java.lang.String[][] { new java.lang.String[] { "en_US", "IUP" } }),
	Priority(new java.lang.String[][] { new java.lang.String[] { "en_US", "Priority" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private FieldCode(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
