// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package interfaceshared.proxies;

public class OutgoingHeartBeatResponseMessageExpertDesk extends interfaceshared.proxies.Response
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "InterfaceShared.OutgoingHeartBeatResponseMessageExpertDesk";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		OutgoingHeartBeatResponseExpertDesk_OutgoingHeartBeatResponseMessageExpertDesk("InterfaceShared.OutgoingHeartBeatResponseExpertDesk_OutgoingHeartBeatResponseMessageExpertDesk"),
		ProcessingAttempt_Response("InterfaceShared.ProcessingAttempt_Response"),
		IncomingMessage_SynchronousResponse("InterfaceShared.IncomingMessage_SynchronousResponse");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OutgoingHeartBeatResponseMessageExpertDesk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "InterfaceShared.OutgoingHeartBeatResponseMessageExpertDesk"));
	}

	protected OutgoingHeartBeatResponseMessageExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject outgoingHeartBeatResponseMessageExpertDeskMendixObject)
	{
		super(context, outgoingHeartBeatResponseMessageExpertDeskMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("InterfaceShared.OutgoingHeartBeatResponseMessageExpertDesk", outgoingHeartBeatResponseMessageExpertDeskMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a InterfaceShared.OutgoingHeartBeatResponseMessageExpertDesk");
	}

	/**
	 * @deprecated Use 'OutgoingHeartBeatResponseMessageExpertDesk.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static interfaceshared.proxies.OutgoingHeartBeatResponseMessageExpertDesk initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return interfaceshared.proxies.OutgoingHeartBeatResponseMessageExpertDesk.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static interfaceshared.proxies.OutgoingHeartBeatResponseMessageExpertDesk initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new interfaceshared.proxies.OutgoingHeartBeatResponseMessageExpertDesk(context, mendixObject);
	}

	public static interfaceshared.proxies.OutgoingHeartBeatResponseMessageExpertDesk load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return interfaceshared.proxies.OutgoingHeartBeatResponseMessageExpertDesk.initialize(context, mendixObject);
	}

	public static java.util.List<interfaceshared.proxies.OutgoingHeartBeatResponseMessageExpertDesk> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<interfaceshared.proxies.OutgoingHeartBeatResponseMessageExpertDesk> result = new java.util.ArrayList<interfaceshared.proxies.OutgoingHeartBeatResponseMessageExpertDesk>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//InterfaceShared.OutgoingHeartBeatResponseMessageExpertDesk" + xpathConstraint))
			result.add(interfaceshared.proxies.OutgoingHeartBeatResponseMessageExpertDesk.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of OutgoingHeartBeatResponseExpertDesk_OutgoingHeartBeatResponseMessageExpertDesk
	 */
	public final interfaceshared.proxies.OutgoingHeartBeatResponseExpertDesk getOutgoingHeartBeatResponseExpertDesk_OutgoingHeartBeatResponseMessageExpertDesk() throws com.mendix.core.CoreException
	{
		return getOutgoingHeartBeatResponseExpertDesk_OutgoingHeartBeatResponseMessageExpertDesk(getContext());
	}

	/**
	 * @param context
	 * @return value of OutgoingHeartBeatResponseExpertDesk_OutgoingHeartBeatResponseMessageExpertDesk
	 */
	public final interfaceshared.proxies.OutgoingHeartBeatResponseExpertDesk getOutgoingHeartBeatResponseExpertDesk_OutgoingHeartBeatResponseMessageExpertDesk(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceshared.proxies.OutgoingHeartBeatResponseExpertDesk result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OutgoingHeartBeatResponseExpertDesk_OutgoingHeartBeatResponseMessageExpertDesk.toString());
		if (identifier != null)
			result = interfaceshared.proxies.OutgoingHeartBeatResponseExpertDesk.load(context, identifier);
		return result;
	}

	/**
	 * Set value of OutgoingHeartBeatResponseExpertDesk_OutgoingHeartBeatResponseMessageExpertDesk
	 * @param outgoingheartbeatresponseexpertdesk_outgoingheartbeatresponsemessageexpertdesk
	 */
	public final void setOutgoingHeartBeatResponseExpertDesk_OutgoingHeartBeatResponseMessageExpertDesk(interfaceshared.proxies.OutgoingHeartBeatResponseExpertDesk outgoingheartbeatresponseexpertdesk_outgoingheartbeatresponsemessageexpertdesk)
	{
		setOutgoingHeartBeatResponseExpertDesk_OutgoingHeartBeatResponseMessageExpertDesk(getContext(), outgoingheartbeatresponseexpertdesk_outgoingheartbeatresponsemessageexpertdesk);
	}

	/**
	 * Set value of OutgoingHeartBeatResponseExpertDesk_OutgoingHeartBeatResponseMessageExpertDesk
	 * @param context
	 * @param outgoingheartbeatresponseexpertdesk_outgoingheartbeatresponsemessageexpertdesk
	 */
	public final void setOutgoingHeartBeatResponseExpertDesk_OutgoingHeartBeatResponseMessageExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, interfaceshared.proxies.OutgoingHeartBeatResponseExpertDesk outgoingheartbeatresponseexpertdesk_outgoingheartbeatresponsemessageexpertdesk)
	{
		if (outgoingheartbeatresponseexpertdesk_outgoingheartbeatresponsemessageexpertdesk == null)
			getMendixObject().setValue(context, MemberNames.OutgoingHeartBeatResponseExpertDesk_OutgoingHeartBeatResponseMessageExpertDesk.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.OutgoingHeartBeatResponseExpertDesk_OutgoingHeartBeatResponseMessageExpertDesk.toString(), outgoingheartbeatresponseexpertdesk_outgoingheartbeatresponsemessageexpertdesk.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final interfaceshared.proxies.OutgoingHeartBeatResponseMessageExpertDesk that = (interfaceshared.proxies.OutgoingHeartBeatResponseMessageExpertDesk) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "InterfaceShared.OutgoingHeartBeatResponseMessageExpertDesk";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
