// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package interfaceshared.proxies;

public class RepeatingStructureProcessingAttempt extends interfaceshared.proxies.ProcessingAttempt
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "InterfaceShared.RepeatingStructureProcessingAttempt";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RepeatingStructureType("RepeatingStructureType"),
		RepeatingStructureGUID("RepeatingStructureGUID"),
		UU95_Processed("UU95_Processed"),
		ProcessAsynchronous("ProcessAsynchronous"),
		AsynchronousProcessingComplete("AsynchronousProcessingComplete"),
		AsynchronousConfirmationMessageProcessingComplete("AsynchronousConfirmationMessageProcessingComplete"),
		Successful("Successful"),
		ManualAttempt("ManualAttempt"),
		Log("Log"),
		ShowCritical("ShowCritical"),
		ShowError("ShowError"),
		ShowWarming("ShowWarming"),
		ShowInfo("ShowInfo"),
		ShowDebug("ShowDebug"),
		ShowTrace("ShowTrace"),
		RepeatingStructureProcessingAttempt_ProcessingAttempt("InterfaceShared.RepeatingStructureProcessingAttempt_ProcessingAttempt"),
		RepeatingStructureProcessingAttempt_Note("InterfaceShared.RepeatingStructureProcessingAttempt_Note"),
		RepeatingStructureProcessingAttempt_AffectedCI("InterfaceShared.RepeatingStructureProcessingAttempt_AffectedCI"),
		RepeatingStructureProcessingAttempt_Attachment("InterfaceShared.RepeatingStructureProcessingAttempt_Attachment"),
		RepeatingStructureProcessingAttempt_Relation("InterfaceShared.RepeatingStructureProcessingAttempt_Relation"),
		RepeatingStructureProcessingAttempt_ExternalReference("InterfaceShared.RepeatingStructureProcessingAttempt_ExternalReference"),
		RepeatingStructureProcessingAttempt_DynamicAttribute("InterfaceShared.RepeatingStructureProcessingAttempt_DynamicAttribute"),
		RepeatingStructureProcessingAttempt_LDAPInbox("InterfaceShared.RepeatingStructureProcessingAttempt_LDAPInbox"),
		CurrentRepeatingStructureProcessingAttempt_LDAPInbox("InterfaceShared.CurrentRepeatingStructureProcessingAttempt_LDAPInbox"),
		ProcessingAttempt_OutgoingConfirmation("InterfaceShared.ProcessingAttempt_OutgoingConfirmation"),
		ProcessingAttempt_Response("InterfaceShared.ProcessingAttempt_Response"),
		Attempt_Message("InterfaceShared.Attempt_Message");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RepeatingStructureProcessingAttempt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "InterfaceShared.RepeatingStructureProcessingAttempt"));
	}

	protected RepeatingStructureProcessingAttempt(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject repeatingStructureProcessingAttemptMendixObject)
	{
		super(context, repeatingStructureProcessingAttemptMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("InterfaceShared.RepeatingStructureProcessingAttempt", repeatingStructureProcessingAttemptMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a InterfaceShared.RepeatingStructureProcessingAttempt");
	}

	/**
	 * @deprecated Use 'RepeatingStructureProcessingAttempt.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static interfaceshared.proxies.RepeatingStructureProcessingAttempt initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return interfaceshared.proxies.RepeatingStructureProcessingAttempt.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static interfaceshared.proxies.RepeatingStructureProcessingAttempt initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new interfaceshared.proxies.RepeatingStructureProcessingAttempt(context, mendixObject);
	}

	public static interfaceshared.proxies.RepeatingStructureProcessingAttempt load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return interfaceshared.proxies.RepeatingStructureProcessingAttempt.initialize(context, mendixObject);
	}

	public static java.util.List<interfaceshared.proxies.RepeatingStructureProcessingAttempt> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<interfaceshared.proxies.RepeatingStructureProcessingAttempt> result = new java.util.ArrayList<interfaceshared.proxies.RepeatingStructureProcessingAttempt>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//InterfaceShared.RepeatingStructureProcessingAttempt" + xpathConstraint))
			result.add(interfaceshared.proxies.RepeatingStructureProcessingAttempt.initialize(context, obj));
		return result;
	}

	/**
	 * Set value of RepeatingStructureType
	 * @param repeatingstructuretype
	 */
	public final interfaceshared.proxies.RepeatingStructuresType getRepeatingStructureType()
	{
		return getRepeatingStructureType(getContext());
	}

	/**
	 * @param context
	 * @return value of RepeatingStructureType
	 */
	public final interfaceshared.proxies.RepeatingStructuresType getRepeatingStructureType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.RepeatingStructureType.toString());
		if (obj == null)
			return null;

		return interfaceshared.proxies.RepeatingStructuresType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of RepeatingStructureType
	 * @param repeatingstructuretype
	 */
	public final void setRepeatingStructureType(interfaceshared.proxies.RepeatingStructuresType repeatingstructuretype)
	{
		setRepeatingStructureType(getContext(), repeatingstructuretype);
	}

	/**
	 * Set value of RepeatingStructureType
	 * @param context
	 * @param repeatingstructuretype
	 */
	public final void setRepeatingStructureType(com.mendix.systemwideinterfaces.core.IContext context, interfaceshared.proxies.RepeatingStructuresType repeatingstructuretype)
	{
		if (repeatingstructuretype != null)
			getMendixObject().setValue(context, MemberNames.RepeatingStructureType.toString(), repeatingstructuretype.toString());
		else
			getMendixObject().setValue(context, MemberNames.RepeatingStructureType.toString(), null);
	}

	/**
	 * @return value of RepeatingStructureGUID
	 */
	public final java.lang.String getRepeatingStructureGUID()
	{
		return getRepeatingStructureGUID(getContext());
	}

	/**
	 * @param context
	 * @return value of RepeatingStructureGUID
	 */
	public final java.lang.String getRepeatingStructureGUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RepeatingStructureGUID.toString());
	}

	/**
	 * Set value of RepeatingStructureGUID
	 * @param repeatingstructureguid
	 */
	public final void setRepeatingStructureGUID(java.lang.String repeatingstructureguid)
	{
		setRepeatingStructureGUID(getContext(), repeatingstructureguid);
	}

	/**
	 * Set value of RepeatingStructureGUID
	 * @param context
	 * @param repeatingstructureguid
	 */
	public final void setRepeatingStructureGUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String repeatingstructureguid)
	{
		getMendixObject().setValue(context, MemberNames.RepeatingStructureGUID.toString(), repeatingstructureguid);
	}

	/**
	 * @return value of RepeatingStructureProcessingAttempt_ProcessingAttempt
	 */
	public final interfaceshared.proxies.ProcessingAttempt getRepeatingStructureProcessingAttempt_ProcessingAttempt() throws com.mendix.core.CoreException
	{
		return getRepeatingStructureProcessingAttempt_ProcessingAttempt(getContext());
	}

	/**
	 * @param context
	 * @return value of RepeatingStructureProcessingAttempt_ProcessingAttempt
	 */
	public final interfaceshared.proxies.ProcessingAttempt getRepeatingStructureProcessingAttempt_ProcessingAttempt(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceshared.proxies.ProcessingAttempt result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RepeatingStructureProcessingAttempt_ProcessingAttempt.toString());
		if (identifier != null)
			result = interfaceshared.proxies.ProcessingAttempt.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RepeatingStructureProcessingAttempt_ProcessingAttempt
	 * @param repeatingstructureprocessingattempt_processingattempt
	 */
	public final void setRepeatingStructureProcessingAttempt_ProcessingAttempt(interfaceshared.proxies.ProcessingAttempt repeatingstructureprocessingattempt_processingattempt)
	{
		setRepeatingStructureProcessingAttempt_ProcessingAttempt(getContext(), repeatingstructureprocessingattempt_processingattempt);
	}

	/**
	 * Set value of RepeatingStructureProcessingAttempt_ProcessingAttempt
	 * @param context
	 * @param repeatingstructureprocessingattempt_processingattempt
	 */
	public final void setRepeatingStructureProcessingAttempt_ProcessingAttempt(com.mendix.systemwideinterfaces.core.IContext context, interfaceshared.proxies.ProcessingAttempt repeatingstructureprocessingattempt_processingattempt)
	{
		if (repeatingstructureprocessingattempt_processingattempt == null)
			getMendixObject().setValue(context, MemberNames.RepeatingStructureProcessingAttempt_ProcessingAttempt.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RepeatingStructureProcessingAttempt_ProcessingAttempt.toString(), repeatingstructureprocessingattempt_processingattempt.getMendixObject().getId());
	}

	/**
	 * @return value of RepeatingStructureProcessingAttempt_Note
	 */
	public final interfacenotes.proxies.Note getRepeatingStructureProcessingAttempt_Note() throws com.mendix.core.CoreException
	{
		return getRepeatingStructureProcessingAttempt_Note(getContext());
	}

	/**
	 * @param context
	 * @return value of RepeatingStructureProcessingAttempt_Note
	 */
	public final interfacenotes.proxies.Note getRepeatingStructureProcessingAttempt_Note(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacenotes.proxies.Note result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RepeatingStructureProcessingAttempt_Note.toString());
		if (identifier != null)
			result = interfacenotes.proxies.Note.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RepeatingStructureProcessingAttempt_Note
	 * @param repeatingstructureprocessingattempt_note
	 */
	public final void setRepeatingStructureProcessingAttempt_Note(interfacenotes.proxies.Note repeatingstructureprocessingattempt_note)
	{
		setRepeatingStructureProcessingAttempt_Note(getContext(), repeatingstructureprocessingattempt_note);
	}

	/**
	 * Set value of RepeatingStructureProcessingAttempt_Note
	 * @param context
	 * @param repeatingstructureprocessingattempt_note
	 */
	public final void setRepeatingStructureProcessingAttempt_Note(com.mendix.systemwideinterfaces.core.IContext context, interfacenotes.proxies.Note repeatingstructureprocessingattempt_note)
	{
		if (repeatingstructureprocessingattempt_note == null)
			getMendixObject().setValue(context, MemberNames.RepeatingStructureProcessingAttempt_Note.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RepeatingStructureProcessingAttempt_Note.toString(), repeatingstructureprocessingattempt_note.getMendixObject().getId());
	}

	/**
	 * @return value of RepeatingStructureProcessingAttempt_AffectedCI
	 */
	public final interfaceaffectedcis.proxies.AffectedCI getRepeatingStructureProcessingAttempt_AffectedCI() throws com.mendix.core.CoreException
	{
		return getRepeatingStructureProcessingAttempt_AffectedCI(getContext());
	}

	/**
	 * @param context
	 * @return value of RepeatingStructureProcessingAttempt_AffectedCI
	 */
	public final interfaceaffectedcis.proxies.AffectedCI getRepeatingStructureProcessingAttempt_AffectedCI(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceaffectedcis.proxies.AffectedCI result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RepeatingStructureProcessingAttempt_AffectedCI.toString());
		if (identifier != null)
			result = interfaceaffectedcis.proxies.AffectedCI.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RepeatingStructureProcessingAttempt_AffectedCI
	 * @param repeatingstructureprocessingattempt_affectedci
	 */
	public final void setRepeatingStructureProcessingAttempt_AffectedCI(interfaceaffectedcis.proxies.AffectedCI repeatingstructureprocessingattempt_affectedci)
	{
		setRepeatingStructureProcessingAttempt_AffectedCI(getContext(), repeatingstructureprocessingattempt_affectedci);
	}

	/**
	 * Set value of RepeatingStructureProcessingAttempt_AffectedCI
	 * @param context
	 * @param repeatingstructureprocessingattempt_affectedci
	 */
	public final void setRepeatingStructureProcessingAttempt_AffectedCI(com.mendix.systemwideinterfaces.core.IContext context, interfaceaffectedcis.proxies.AffectedCI repeatingstructureprocessingattempt_affectedci)
	{
		if (repeatingstructureprocessingattempt_affectedci == null)
			getMendixObject().setValue(context, MemberNames.RepeatingStructureProcessingAttempt_AffectedCI.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RepeatingStructureProcessingAttempt_AffectedCI.toString(), repeatingstructureprocessingattempt_affectedci.getMendixObject().getId());
	}

	/**
	 * @return value of RepeatingStructureProcessingAttempt_Attachment
	 */
	public final interfaceattachments.proxies.Attachment getRepeatingStructureProcessingAttempt_Attachment() throws com.mendix.core.CoreException
	{
		return getRepeatingStructureProcessingAttempt_Attachment(getContext());
	}

	/**
	 * @param context
	 * @return value of RepeatingStructureProcessingAttempt_Attachment
	 */
	public final interfaceattachments.proxies.Attachment getRepeatingStructureProcessingAttempt_Attachment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceattachments.proxies.Attachment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RepeatingStructureProcessingAttempt_Attachment.toString());
		if (identifier != null)
			result = interfaceattachments.proxies.Attachment.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RepeatingStructureProcessingAttempt_Attachment
	 * @param repeatingstructureprocessingattempt_attachment
	 */
	public final void setRepeatingStructureProcessingAttempt_Attachment(interfaceattachments.proxies.Attachment repeatingstructureprocessingattempt_attachment)
	{
		setRepeatingStructureProcessingAttempt_Attachment(getContext(), repeatingstructureprocessingattempt_attachment);
	}

	/**
	 * Set value of RepeatingStructureProcessingAttempt_Attachment
	 * @param context
	 * @param repeatingstructureprocessingattempt_attachment
	 */
	public final void setRepeatingStructureProcessingAttempt_Attachment(com.mendix.systemwideinterfaces.core.IContext context, interfaceattachments.proxies.Attachment repeatingstructureprocessingattempt_attachment)
	{
		if (repeatingstructureprocessingattempt_attachment == null)
			getMendixObject().setValue(context, MemberNames.RepeatingStructureProcessingAttempt_Attachment.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RepeatingStructureProcessingAttempt_Attachment.toString(), repeatingstructureprocessingattempt_attachment.getMendixObject().getId());
	}

	/**
	 * @return value of RepeatingStructureProcessingAttempt_Relation
	 */
	public final interfacerelations.proxies.Relation getRepeatingStructureProcessingAttempt_Relation() throws com.mendix.core.CoreException
	{
		return getRepeatingStructureProcessingAttempt_Relation(getContext());
	}

	/**
	 * @param context
	 * @return value of RepeatingStructureProcessingAttempt_Relation
	 */
	public final interfacerelations.proxies.Relation getRepeatingStructureProcessingAttempt_Relation(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacerelations.proxies.Relation result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RepeatingStructureProcessingAttempt_Relation.toString());
		if (identifier != null)
			result = interfacerelations.proxies.Relation.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RepeatingStructureProcessingAttempt_Relation
	 * @param repeatingstructureprocessingattempt_relation
	 */
	public final void setRepeatingStructureProcessingAttempt_Relation(interfacerelations.proxies.Relation repeatingstructureprocessingattempt_relation)
	{
		setRepeatingStructureProcessingAttempt_Relation(getContext(), repeatingstructureprocessingattempt_relation);
	}

	/**
	 * Set value of RepeatingStructureProcessingAttempt_Relation
	 * @param context
	 * @param repeatingstructureprocessingattempt_relation
	 */
	public final void setRepeatingStructureProcessingAttempt_Relation(com.mendix.systemwideinterfaces.core.IContext context, interfacerelations.proxies.Relation repeatingstructureprocessingattempt_relation)
	{
		if (repeatingstructureprocessingattempt_relation == null)
			getMendixObject().setValue(context, MemberNames.RepeatingStructureProcessingAttempt_Relation.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RepeatingStructureProcessingAttempt_Relation.toString(), repeatingstructureprocessingattempt_relation.getMendixObject().getId());
	}

	/**
	 * @return value of RepeatingStructureProcessingAttempt_ExternalReference
	 */
	public final interfaceexternalreferences.proxies.ExternalReference getRepeatingStructureProcessingAttempt_ExternalReference() throws com.mendix.core.CoreException
	{
		return getRepeatingStructureProcessingAttempt_ExternalReference(getContext());
	}

	/**
	 * @param context
	 * @return value of RepeatingStructureProcessingAttempt_ExternalReference
	 */
	public final interfaceexternalreferences.proxies.ExternalReference getRepeatingStructureProcessingAttempt_ExternalReference(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceexternalreferences.proxies.ExternalReference result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RepeatingStructureProcessingAttempt_ExternalReference.toString());
		if (identifier != null)
			result = interfaceexternalreferences.proxies.ExternalReference.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RepeatingStructureProcessingAttempt_ExternalReference
	 * @param repeatingstructureprocessingattempt_externalreference
	 */
	public final void setRepeatingStructureProcessingAttempt_ExternalReference(interfaceexternalreferences.proxies.ExternalReference repeatingstructureprocessingattempt_externalreference)
	{
		setRepeatingStructureProcessingAttempt_ExternalReference(getContext(), repeatingstructureprocessingattempt_externalreference);
	}

	/**
	 * Set value of RepeatingStructureProcessingAttempt_ExternalReference
	 * @param context
	 * @param repeatingstructureprocessingattempt_externalreference
	 */
	public final void setRepeatingStructureProcessingAttempt_ExternalReference(com.mendix.systemwideinterfaces.core.IContext context, interfaceexternalreferences.proxies.ExternalReference repeatingstructureprocessingattempt_externalreference)
	{
		if (repeatingstructureprocessingattempt_externalreference == null)
			getMendixObject().setValue(context, MemberNames.RepeatingStructureProcessingAttempt_ExternalReference.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RepeatingStructureProcessingAttempt_ExternalReference.toString(), repeatingstructureprocessingattempt_externalreference.getMendixObject().getId());
	}

	/**
	 * @return value of RepeatingStructureProcessingAttempt_DynamicAttribute
	 */
	public final interfacerequests.proxies.DynamicAttribute getRepeatingStructureProcessingAttempt_DynamicAttribute() throws com.mendix.core.CoreException
	{
		return getRepeatingStructureProcessingAttempt_DynamicAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of RepeatingStructureProcessingAttempt_DynamicAttribute
	 */
	public final interfacerequests.proxies.DynamicAttribute getRepeatingStructureProcessingAttempt_DynamicAttribute(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacerequests.proxies.DynamicAttribute result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RepeatingStructureProcessingAttempt_DynamicAttribute.toString());
		if (identifier != null)
			result = interfacerequests.proxies.DynamicAttribute.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RepeatingStructureProcessingAttempt_DynamicAttribute
	 * @param repeatingstructureprocessingattempt_dynamicattribute
	 */
	public final void setRepeatingStructureProcessingAttempt_DynamicAttribute(interfacerequests.proxies.DynamicAttribute repeatingstructureprocessingattempt_dynamicattribute)
	{
		setRepeatingStructureProcessingAttempt_DynamicAttribute(getContext(), repeatingstructureprocessingattempt_dynamicattribute);
	}

	/**
	 * Set value of RepeatingStructureProcessingAttempt_DynamicAttribute
	 * @param context
	 * @param repeatingstructureprocessingattempt_dynamicattribute
	 */
	public final void setRepeatingStructureProcessingAttempt_DynamicAttribute(com.mendix.systemwideinterfaces.core.IContext context, interfacerequests.proxies.DynamicAttribute repeatingstructureprocessingattempt_dynamicattribute)
	{
		if (repeatingstructureprocessingattempt_dynamicattribute == null)
			getMendixObject().setValue(context, MemberNames.RepeatingStructureProcessingAttempt_DynamicAttribute.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RepeatingStructureProcessingAttempt_DynamicAttribute.toString(), repeatingstructureprocessingattempt_dynamicattribute.getMendixObject().getId());
	}

	/**
	 * @return value of RepeatingStructureProcessingAttempt_LDAPInbox
	 */
	public final interfaceldap.proxies.LDAPInbox getRepeatingStructureProcessingAttempt_LDAPInbox() throws com.mendix.core.CoreException
	{
		return getRepeatingStructureProcessingAttempt_LDAPInbox(getContext());
	}

	/**
	 * @param context
	 * @return value of RepeatingStructureProcessingAttempt_LDAPInbox
	 */
	public final interfaceldap.proxies.LDAPInbox getRepeatingStructureProcessingAttempt_LDAPInbox(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceldap.proxies.LDAPInbox result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RepeatingStructureProcessingAttempt_LDAPInbox.toString());
		if (identifier != null)
			result = interfaceldap.proxies.LDAPInbox.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RepeatingStructureProcessingAttempt_LDAPInbox
	 * @param repeatingstructureprocessingattempt_ldapinbox
	 */
	public final void setRepeatingStructureProcessingAttempt_LDAPInbox(interfaceldap.proxies.LDAPInbox repeatingstructureprocessingattempt_ldapinbox)
	{
		setRepeatingStructureProcessingAttempt_LDAPInbox(getContext(), repeatingstructureprocessingattempt_ldapinbox);
	}

	/**
	 * Set value of RepeatingStructureProcessingAttempt_LDAPInbox
	 * @param context
	 * @param repeatingstructureprocessingattempt_ldapinbox
	 */
	public final void setRepeatingStructureProcessingAttempt_LDAPInbox(com.mendix.systemwideinterfaces.core.IContext context, interfaceldap.proxies.LDAPInbox repeatingstructureprocessingattempt_ldapinbox)
	{
		if (repeatingstructureprocessingattempt_ldapinbox == null)
			getMendixObject().setValue(context, MemberNames.RepeatingStructureProcessingAttempt_LDAPInbox.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RepeatingStructureProcessingAttempt_LDAPInbox.toString(), repeatingstructureprocessingattempt_ldapinbox.getMendixObject().getId());
	}

	/**
	 * @return value of CurrentRepeatingStructureProcessingAttempt_LDAPInbox
	 */
	public final interfaceldap.proxies.LDAPInbox getCurrentRepeatingStructureProcessingAttempt_LDAPInbox() throws com.mendix.core.CoreException
	{
		return getCurrentRepeatingStructureProcessingAttempt_LDAPInbox(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrentRepeatingStructureProcessingAttempt_LDAPInbox
	 */
	public final interfaceldap.proxies.LDAPInbox getCurrentRepeatingStructureProcessingAttempt_LDAPInbox(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceldap.proxies.LDAPInbox result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CurrentRepeatingStructureProcessingAttempt_LDAPInbox.toString());
		if (identifier != null)
			result = interfaceldap.proxies.LDAPInbox.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CurrentRepeatingStructureProcessingAttempt_LDAPInbox
	 * @param currentrepeatingstructureprocessingattempt_ldapinbox
	 */
	public final void setCurrentRepeatingStructureProcessingAttempt_LDAPInbox(interfaceldap.proxies.LDAPInbox currentrepeatingstructureprocessingattempt_ldapinbox)
	{
		setCurrentRepeatingStructureProcessingAttempt_LDAPInbox(getContext(), currentrepeatingstructureprocessingattempt_ldapinbox);
	}

	/**
	 * Set value of CurrentRepeatingStructureProcessingAttempt_LDAPInbox
	 * @param context
	 * @param currentrepeatingstructureprocessingattempt_ldapinbox
	 */
	public final void setCurrentRepeatingStructureProcessingAttempt_LDAPInbox(com.mendix.systemwideinterfaces.core.IContext context, interfaceldap.proxies.LDAPInbox currentrepeatingstructureprocessingattempt_ldapinbox)
	{
		if (currentrepeatingstructureprocessingattempt_ldapinbox == null)
			getMendixObject().setValue(context, MemberNames.CurrentRepeatingStructureProcessingAttempt_LDAPInbox.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CurrentRepeatingStructureProcessingAttempt_LDAPInbox.toString(), currentrepeatingstructureprocessingattempt_ldapinbox.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final interfaceshared.proxies.RepeatingStructureProcessingAttempt that = (interfaceshared.proxies.RepeatingStructureProcessingAttempt) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "InterfaceShared.RepeatingStructureProcessingAttempt";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
