// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package interfaceshared.proxies;

public enum RequestFieldCode
{
	Location(new java.lang.String[][] { new java.lang.String[] { "en_US", "Location" }, new java.lang.String[] { "de_DE", "Standort " }, new java.lang.String[] { "nl_NL", "Locatie" } }),
	CI(new java.lang.String[][] { new java.lang.String[] { "en_US", "CI" }, new java.lang.String[] { "de_DE", "CI   " }, new java.lang.String[] { "nl_NL", "CI" } }),
	Delivering_Organisation(new java.lang.String[][] { new java.lang.String[] { "en_US", "Delivering Organisation" }, new java.lang.String[] { "de_DE", "Zuliefernde Organisationen" }, new java.lang.String[] { "nl_NL", "Toegewezen groep" } }),
	Receiving_Organisation(new java.lang.String[][] { new java.lang.String[] { "en_US", "Receiving Organisation" }, new java.lang.String[] { "de_DE", "Empfangende Organisation " }, new java.lang.String[] { "nl_NL", "Ontvangende organisatie" } }),
	Impact(new java.lang.String[][] { new java.lang.String[] { "en_US", "Impact" }, new java.lang.String[] { "de_DE", "Auswirkung  " }, new java.lang.String[] { "nl_NL", "Impact" } }),
	Urgency(new java.lang.String[][] { new java.lang.String[] { "en_US", "Urgency" }, new java.lang.String[] { "de_DE", "Dringlichkeit" }, new java.lang.String[] { "nl_NL", "Urgentie" } }),
	Service(new java.lang.String[][] { new java.lang.String[] { "en_US", "Type" }, new java.lang.String[] { "de_DE", "Service" }, new java.lang.String[] { "nl_NL", "Type" } }),
	Service_Process(new java.lang.String[][] { new java.lang.String[] { "en_US", "Service Process" }, new java.lang.String[] { "de_DE", "Serviceprozess" }, new java.lang.String[] { "nl_NL", "Service proces" } }),
	Person(new java.lang.String[][] { new java.lang.String[] { "en_US", "Person" }, new java.lang.String[] { "de_DE", "Person   " }, new java.lang.String[] { "nl_NL", "Persoon" } }),
	Person_Caller(new java.lang.String[][] { new java.lang.String[] { "en_US", "Person Caller" }, new java.lang.String[] { "de_DE", "Melder Person" }, new java.lang.String[] { "nl_NL", "Persoon" } }),
	Opening_Category(new java.lang.String[][] { new java.lang.String[] { "en_US", "Subject" }, new java.lang.String[] { "de_DE", "Offene Kategorie" }, new java.lang.String[] { "nl_NL", "Subject" } }),
	Closing_Category(new java.lang.String[][] { new java.lang.String[] { "en_US", "Closure Category" }, new java.lang.String[] { "nl_NL", "Afsluit" } }),
	Customer_Satisfaction(new java.lang.String[][] { new java.lang.String[] { "en_US", "Customer Satisfaction" }, new java.lang.String[] { "de_DE", "Kundenzufriedenheit " }, new java.lang.String[] { "nl_NL", "Klanttevredenheid" } }),
	Assigned_Person(new java.lang.String[][] { new java.lang.String[] { "en_US", "Assigned Person" }, new java.lang.String[] { "nl_NL", "Toegwezen persoon" } }),
	CI_Type(new java.lang.String[][] { new java.lang.String[] { "en_US", "CI Type" }, new java.lang.String[] { "nl_NL", "CI type" } }),
	Country(new java.lang.String[][] { new java.lang.String[] { "en_US", "Country" }, new java.lang.String[] { "nl_NL", "Land" } }),
	Paused_Reason(new java.lang.String[][] { new java.lang.String[] { "en_US", "Paused Reason" }, new java.lang.String[] { "nl_NL", "Pauze reden" } }),
	IUP(new java.lang.String[][] { new java.lang.String[] { "en_US", "IUP" } }),
	Priority(new java.lang.String[][] { new java.lang.String[] { "en_US", "Priority" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private RequestFieldCode(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
