// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package interfaceconfiguration.proxies;

public class DefaultTableItem extends interfaceshared.proxies.AuditableEntity
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "InterfaceConfiguration.DefaultTableItem";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Value("Value"),
		CustomerSatisfactionEnum("CustomerSatisfactionEnum"),
		FieldCode("FieldCode"),
		CheckDefaultOnTranslationFail("CheckDefaultOnTranslationFail"),
		CheckDefaultOnEmptyValue("CheckDefaultOnEmptyValue"),
		Country("Country"),
		AssociatedEntry("AssociatedEntry"),
		RequestFieldCode("RequestFieldCode"),
		RequestUpdateFieldCode("RequestUpdateFieldCode"),
		ContractAspectTranslationFieldCode("ContractAspectTranslationFieldCode"),
		AffectedCIsFieldCode("AffectedCIsFieldCode"),
		DefaultTableItemType("DefaultTableItemType"),
		StringValue("StringValue"),
		LDAPAttributeFieldCode("LDAPAttributeFieldCode"),
		DefaultTableItem_InterfaceMessageConfiguration("InterfaceConfiguration.DefaultTableItem_InterfaceMessageConfiguration"),
		DefaultTableItem_LDAPImportType("InterfaceConfiguration.DefaultTableItem_LDAPImportType"),
		DefaultTableItem_Location("InterfaceConfiguration.DefaultTableItem_Location"),
		DefaultTableItem_Organisation("InterfaceConfiguration.DefaultTableItem_Organisation"),
		DefaultTableItem_IncidentOpeningCategory("InterfaceConfiguration.DefaultTableItem_IncidentOpeningCategory"),
		DefaultTableItem_ConfigurationItem("InterfaceConfiguration.DefaultTableItem_ConfigurationItem"),
		DefaultTableItem_Impact("InterfaceConfiguration.DefaultTableItem_Impact"),
		DefaultTableItem_Urgency("InterfaceConfiguration.DefaultTableItem_Urgency"),
		DefaultTableItem_Service("InterfaceConfiguration.DefaultTableItem_Service"),
		DefaultTableItem_Service_Process("InterfaceConfiguration.DefaultTableItem_Service_Process"),
		DefaultTableItem_Person("InterfaceConfiguration.DefaultTableItem_Person"),
		DefaultTableItem_State("InterfaceConfiguration.DefaultTableItem_State"),
		DefaultTableItem_Phase("InterfaceConfiguration.DefaultTableItem_Phase"),
		DefaultTableItem_ProblemOpeningCategory("InterfaceConfiguration.DefaultTableItem_ProblemOpeningCategory"),
		DefaultTableItem_ChangeOpeningCategory("InterfaceConfiguration.DefaultTableItem_ChangeOpeningCategory"),
		DefaultTableItem_OperationOpeningCategory("InterfaceConfiguration.DefaultTableItem_OperationOpeningCategory"),
		DefaultTableItem_DeliveryOpeningCategory("InterfaceConfiguration.DefaultTableItem_DeliveryOpeningCategory"),
		DefaultTableItem_ServiceRequestOpeningCategory("InterfaceConfiguration.DefaultTableItem_ServiceRequestOpeningCategory"),
		DefaultTableItem_IncidentClosureCategory("InterfaceConfiguration.DefaultTableItem_IncidentClosureCategory"),
		DefaultTableItem_ProblemClosureCategory("InterfaceConfiguration.DefaultTableItem_ProblemClosureCategory"),
		DefaultTableItem_ChangeClosureCategory("InterfaceConfiguration.DefaultTableItem_ChangeClosureCategory"),
		DefaultTableItem_OperationClosureCategory("InterfaceConfiguration.DefaultTableItem_OperationClosureCategory"),
		DefaultTableItem_DeliveryClosureCategory("InterfaceConfiguration.DefaultTableItem_DeliveryClosureCategory"),
		DefaultTableItem_ServiceRequestClosureCategory("InterfaceConfiguration.DefaultTableItem_ServiceRequestClosureCategory"),
		DefaultTableItem_CMDBType("InterfaceConfiguration.DefaultTableItem_CMDBType"),
		DefaultTableItem_PausedReasonDefinition("InterfaceConfiguration.DefaultTableItem_PausedReasonDefinition"),
		DefaultTableItem_Language("InterfaceConfiguration.DefaultTableItem_Language"),
		DefaultTableItem_Template("InterfaceConfiguration.DefaultTableItem_Template"),
		DefaultTableItem_UserRole("InterfaceConfiguration.DefaultTableItem_UserRole"),
		DefaultTableItem_TimeZone("InterfaceConfiguration.DefaultTableItem_TimeZone"),
		DefaultTableItem_Locations("InterfaceConfiguration.DefaultTableItem_Locations"),
		DefaultTableItem_Customers("InterfaceConfiguration.DefaultTableItem_Customers"),
		DefaultTableItem_BusinessGroups("InterfaceConfiguration.DefaultTableItem_BusinessGroups"),
		DefaultTableItem_IUP_Combination("InterfaceConfiguration.DefaultTableItem_IUP_Combination"),
		DefaultTableItem_Priority("InterfaceConfiguration.DefaultTableItem_Priority");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DefaultTableItem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "InterfaceConfiguration.DefaultTableItem"));
	}

	protected DefaultTableItem(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject defaultTableItemMendixObject)
	{
		super(context, defaultTableItemMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("InterfaceConfiguration.DefaultTableItem", defaultTableItemMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a InterfaceConfiguration.DefaultTableItem");
	}

	/**
	 * @deprecated Use 'DefaultTableItem.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static interfaceconfiguration.proxies.DefaultTableItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return interfaceconfiguration.proxies.DefaultTableItem.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static interfaceconfiguration.proxies.DefaultTableItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("InterfaceNAW.NAWDefaultTableItem", mendixObject.getType()))
			return interfacenaw.proxies.NAWDefaultTableItem.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("InterfaceConfiguration.TranslationTableItem", mendixObject.getType()))
			return interfaceconfiguration.proxies.TranslationTableItem.initialize(context, mendixObject);

		return new interfaceconfiguration.proxies.DefaultTableItem(context, mendixObject);
	}

	public static interfaceconfiguration.proxies.DefaultTableItem load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return interfaceconfiguration.proxies.DefaultTableItem.initialize(context, mendixObject);
	}

	public static java.util.List<? extends interfaceconfiguration.proxies.DefaultTableItem> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<interfaceconfiguration.proxies.DefaultTableItem> result = new java.util.ArrayList<interfaceconfiguration.proxies.DefaultTableItem>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//InterfaceConfiguration.DefaultTableItem" + xpathConstraint))
			result.add(interfaceconfiguration.proxies.DefaultTableItem.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Value
	 */
	public final java.lang.String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final java.lang.String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(java.lang.String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * Set value of CustomerSatisfactionEnum
	 * @param customersatisfactionenum
	 */
	public final process.proxies.ProcessSatisfaction getCustomerSatisfactionEnum()
	{
		return getCustomerSatisfactionEnum(getContext());
	}

	/**
	 * @param context
	 * @return value of CustomerSatisfactionEnum
	 */
	public final process.proxies.ProcessSatisfaction getCustomerSatisfactionEnum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.CustomerSatisfactionEnum.toString());
		if (obj == null)
			return null;

		return process.proxies.ProcessSatisfaction.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of CustomerSatisfactionEnum
	 * @param customersatisfactionenum
	 */
	public final void setCustomerSatisfactionEnum(process.proxies.ProcessSatisfaction customersatisfactionenum)
	{
		setCustomerSatisfactionEnum(getContext(), customersatisfactionenum);
	}

	/**
	 * Set value of CustomerSatisfactionEnum
	 * @param context
	 * @param customersatisfactionenum
	 */
	public final void setCustomerSatisfactionEnum(com.mendix.systemwideinterfaces.core.IContext context, process.proxies.ProcessSatisfaction customersatisfactionenum)
	{
		if (customersatisfactionenum != null)
			getMendixObject().setValue(context, MemberNames.CustomerSatisfactionEnum.toString(), customersatisfactionenum.toString());
		else
			getMendixObject().setValue(context, MemberNames.CustomerSatisfactionEnum.toString(), null);
	}

	/**
	 * Set value of FieldCode
	 * @param fieldcode
	 */
	public final interfaceshared.proxies.FieldCode getFieldCode()
	{
		return getFieldCode(getContext());
	}

	/**
	 * @param context
	 * @return value of FieldCode
	 */
	public final interfaceshared.proxies.FieldCode getFieldCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.FieldCode.toString());
		if (obj == null)
			return null;

		return interfaceshared.proxies.FieldCode.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of FieldCode
	 * @param fieldcode
	 */
	public final void setFieldCode(interfaceshared.proxies.FieldCode fieldcode)
	{
		setFieldCode(getContext(), fieldcode);
	}

	/**
	 * Set value of FieldCode
	 * @param context
	 * @param fieldcode
	 */
	public final void setFieldCode(com.mendix.systemwideinterfaces.core.IContext context, interfaceshared.proxies.FieldCode fieldcode)
	{
		if (fieldcode != null)
			getMendixObject().setValue(context, MemberNames.FieldCode.toString(), fieldcode.toString());
		else
			getMendixObject().setValue(context, MemberNames.FieldCode.toString(), null);
	}

	/**
	 * @return value of CheckDefaultOnTranslationFail
	 */
	public final java.lang.Boolean getCheckDefaultOnTranslationFail()
	{
		return getCheckDefaultOnTranslationFail(getContext());
	}

	/**
	 * @param context
	 * @return value of CheckDefaultOnTranslationFail
	 */
	public final java.lang.Boolean getCheckDefaultOnTranslationFail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CheckDefaultOnTranslationFail.toString());
	}

	/**
	 * Set value of CheckDefaultOnTranslationFail
	 * @param checkdefaultontranslationfail
	 */
	public final void setCheckDefaultOnTranslationFail(java.lang.Boolean checkdefaultontranslationfail)
	{
		setCheckDefaultOnTranslationFail(getContext(), checkdefaultontranslationfail);
	}

	/**
	 * Set value of CheckDefaultOnTranslationFail
	 * @param context
	 * @param checkdefaultontranslationfail
	 */
	public final void setCheckDefaultOnTranslationFail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean checkdefaultontranslationfail)
	{
		getMendixObject().setValue(context, MemberNames.CheckDefaultOnTranslationFail.toString(), checkdefaultontranslationfail);
	}

	/**
	 * @return value of CheckDefaultOnEmptyValue
	 */
	public final java.lang.Boolean getCheckDefaultOnEmptyValue()
	{
		return getCheckDefaultOnEmptyValue(getContext());
	}

	/**
	 * @param context
	 * @return value of CheckDefaultOnEmptyValue
	 */
	public final java.lang.Boolean getCheckDefaultOnEmptyValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CheckDefaultOnEmptyValue.toString());
	}

	/**
	 * Set value of CheckDefaultOnEmptyValue
	 * @param checkdefaultonemptyvalue
	 */
	public final void setCheckDefaultOnEmptyValue(java.lang.Boolean checkdefaultonemptyvalue)
	{
		setCheckDefaultOnEmptyValue(getContext(), checkdefaultonemptyvalue);
	}

	/**
	 * Set value of CheckDefaultOnEmptyValue
	 * @param context
	 * @param checkdefaultonemptyvalue
	 */
	public final void setCheckDefaultOnEmptyValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean checkdefaultonemptyvalue)
	{
		getMendixObject().setValue(context, MemberNames.CheckDefaultOnEmptyValue.toString(), checkdefaultonemptyvalue);
	}

	/**
	 * Set value of Country
	 * @param country
	 */
	public final nap.proxies.Countries getCountry()
	{
		return getCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of Country
	 */
	public final nap.proxies.Countries getCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Country.toString());
		if (obj == null)
			return null;

		return nap.proxies.Countries.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Country
	 * @param country
	 */
	public final void setCountry(nap.proxies.Countries country)
	{
		setCountry(getContext(), country);
	}

	/**
	 * Set value of Country
	 * @param context
	 * @param country
	 */
	public final void setCountry(com.mendix.systemwideinterfaces.core.IContext context, nap.proxies.Countries country)
	{
		if (country != null)
			getMendixObject().setValue(context, MemberNames.Country.toString(), country.toString());
		else
			getMendixObject().setValue(context, MemberNames.Country.toString(), null);
	}

	/**
	 * @return value of AssociatedEntry
	 */
	public final java.lang.String getAssociatedEntry()
	{
		return getAssociatedEntry(getContext());
	}

	/**
	 * @param context
	 * @return value of AssociatedEntry
	 */
	public final java.lang.String getAssociatedEntry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AssociatedEntry.toString());
	}

	/**
	 * Set value of AssociatedEntry
	 * @param associatedentry
	 */
	public final void setAssociatedEntry(java.lang.String associatedentry)
	{
		setAssociatedEntry(getContext(), associatedentry);
	}

	/**
	 * Set value of AssociatedEntry
	 * @param context
	 * @param associatedentry
	 */
	public final void setAssociatedEntry(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String associatedentry)
	{
		getMendixObject().setValue(context, MemberNames.AssociatedEntry.toString(), associatedentry);
	}

	/**
	 * Set value of RequestFieldCode
	 * @param requestfieldcode
	 */
	public final interfaceshared.proxies.RequestFieldCode getRequestFieldCode()
	{
		return getRequestFieldCode(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestFieldCode
	 */
	public final interfaceshared.proxies.RequestFieldCode getRequestFieldCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.RequestFieldCode.toString());
		if (obj == null)
			return null;

		return interfaceshared.proxies.RequestFieldCode.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of RequestFieldCode
	 * @param requestfieldcode
	 */
	public final void setRequestFieldCode(interfaceshared.proxies.RequestFieldCode requestfieldcode)
	{
		setRequestFieldCode(getContext(), requestfieldcode);
	}

	/**
	 * Set value of RequestFieldCode
	 * @param context
	 * @param requestfieldcode
	 */
	public final void setRequestFieldCode(com.mendix.systemwideinterfaces.core.IContext context, interfaceshared.proxies.RequestFieldCode requestfieldcode)
	{
		if (requestfieldcode != null)
			getMendixObject().setValue(context, MemberNames.RequestFieldCode.toString(), requestfieldcode.toString());
		else
			getMendixObject().setValue(context, MemberNames.RequestFieldCode.toString(), null);
	}

	/**
	 * Set value of RequestUpdateFieldCode
	 * @param requestupdatefieldcode
	 */
	public final interfaceshared.proxies.RequestUpdateFieldCode getRequestUpdateFieldCode()
	{
		return getRequestUpdateFieldCode(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestUpdateFieldCode
	 */
	public final interfaceshared.proxies.RequestUpdateFieldCode getRequestUpdateFieldCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.RequestUpdateFieldCode.toString());
		if (obj == null)
			return null;

		return interfaceshared.proxies.RequestUpdateFieldCode.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of RequestUpdateFieldCode
	 * @param requestupdatefieldcode
	 */
	public final void setRequestUpdateFieldCode(interfaceshared.proxies.RequestUpdateFieldCode requestupdatefieldcode)
	{
		setRequestUpdateFieldCode(getContext(), requestupdatefieldcode);
	}

	/**
	 * Set value of RequestUpdateFieldCode
	 * @param context
	 * @param requestupdatefieldcode
	 */
	public final void setRequestUpdateFieldCode(com.mendix.systemwideinterfaces.core.IContext context, interfaceshared.proxies.RequestUpdateFieldCode requestupdatefieldcode)
	{
		if (requestupdatefieldcode != null)
			getMendixObject().setValue(context, MemberNames.RequestUpdateFieldCode.toString(), requestupdatefieldcode.toString());
		else
			getMendixObject().setValue(context, MemberNames.RequestUpdateFieldCode.toString(), null);
	}

	/**
	 * Set value of ContractAspectTranslationFieldCode
	 * @param contractaspecttranslationfieldcode
	 */
	public final interfaceshared.proxies.ContractAspectUpdateFieldCode getContractAspectTranslationFieldCode()
	{
		return getContractAspectTranslationFieldCode(getContext());
	}

	/**
	 * @param context
	 * @return value of ContractAspectTranslationFieldCode
	 */
	public final interfaceshared.proxies.ContractAspectUpdateFieldCode getContractAspectTranslationFieldCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ContractAspectTranslationFieldCode.toString());
		if (obj == null)
			return null;

		return interfaceshared.proxies.ContractAspectUpdateFieldCode.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ContractAspectTranslationFieldCode
	 * @param contractaspecttranslationfieldcode
	 */
	public final void setContractAspectTranslationFieldCode(interfaceshared.proxies.ContractAspectUpdateFieldCode contractaspecttranslationfieldcode)
	{
		setContractAspectTranslationFieldCode(getContext(), contractaspecttranslationfieldcode);
	}

	/**
	 * Set value of ContractAspectTranslationFieldCode
	 * @param context
	 * @param contractaspecttranslationfieldcode
	 */
	public final void setContractAspectTranslationFieldCode(com.mendix.systemwideinterfaces.core.IContext context, interfaceshared.proxies.ContractAspectUpdateFieldCode contractaspecttranslationfieldcode)
	{
		if (contractaspecttranslationfieldcode != null)
			getMendixObject().setValue(context, MemberNames.ContractAspectTranslationFieldCode.toString(), contractaspecttranslationfieldcode.toString());
		else
			getMendixObject().setValue(context, MemberNames.ContractAspectTranslationFieldCode.toString(), null);
	}

	/**
	 * Set value of AffectedCIsFieldCode
	 * @param affectedcisfieldcode
	 */
	public final interfaceshared.proxies.AffectedCIFieldCode getAffectedCIsFieldCode()
	{
		return getAffectedCIsFieldCode(getContext());
	}

	/**
	 * @param context
	 * @return value of AffectedCIsFieldCode
	 */
	public final interfaceshared.proxies.AffectedCIFieldCode getAffectedCIsFieldCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.AffectedCIsFieldCode.toString());
		if (obj == null)
			return null;

		return interfaceshared.proxies.AffectedCIFieldCode.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of AffectedCIsFieldCode
	 * @param affectedcisfieldcode
	 */
	public final void setAffectedCIsFieldCode(interfaceshared.proxies.AffectedCIFieldCode affectedcisfieldcode)
	{
		setAffectedCIsFieldCode(getContext(), affectedcisfieldcode);
	}

	/**
	 * Set value of AffectedCIsFieldCode
	 * @param context
	 * @param affectedcisfieldcode
	 */
	public final void setAffectedCIsFieldCode(com.mendix.systemwideinterfaces.core.IContext context, interfaceshared.proxies.AffectedCIFieldCode affectedcisfieldcode)
	{
		if (affectedcisfieldcode != null)
			getMendixObject().setValue(context, MemberNames.AffectedCIsFieldCode.toString(), affectedcisfieldcode.toString());
		else
			getMendixObject().setValue(context, MemberNames.AffectedCIsFieldCode.toString(), null);
	}

	/**
	 * Set value of DefaultTableItemType
	 * @param defaulttableitemtype
	 */
	public final interfaceconfiguration.proxies.DefaultTableItemType getDefaultTableItemType()
	{
		return getDefaultTableItemType(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItemType
	 */
	public final interfaceconfiguration.proxies.DefaultTableItemType getDefaultTableItemType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.DefaultTableItemType.toString());
		if (obj == null)
			return null;

		return interfaceconfiguration.proxies.DefaultTableItemType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of DefaultTableItemType
	 * @param defaulttableitemtype
	 */
	public final void setDefaultTableItemType(interfaceconfiguration.proxies.DefaultTableItemType defaulttableitemtype)
	{
		setDefaultTableItemType(getContext(), defaulttableitemtype);
	}

	/**
	 * Set value of DefaultTableItemType
	 * @param context
	 * @param defaulttableitemtype
	 */
	public final void setDefaultTableItemType(com.mendix.systemwideinterfaces.core.IContext context, interfaceconfiguration.proxies.DefaultTableItemType defaulttableitemtype)
	{
		if (defaulttableitemtype != null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItemType.toString(), defaulttableitemtype.toString());
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItemType.toString(), null);
	}

	/**
	 * @return value of StringValue
	 */
	public final java.lang.String getStringValue()
	{
		return getStringValue(getContext());
	}

	/**
	 * @param context
	 * @return value of StringValue
	 */
	public final java.lang.String getStringValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StringValue.toString());
	}

	/**
	 * Set value of StringValue
	 * @param stringvalue
	 */
	public final void setStringValue(java.lang.String stringvalue)
	{
		setStringValue(getContext(), stringvalue);
	}

	/**
	 * Set value of StringValue
	 * @param context
	 * @param stringvalue
	 */
	public final void setStringValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String stringvalue)
	{
		getMendixObject().setValue(context, MemberNames.StringValue.toString(), stringvalue);
	}

	/**
	 * Set value of LDAPAttributeFieldCode
	 * @param ldapattributefieldcode
	 */
	public final interfaceshared.proxies.LDAPAttributeFieldCode getLDAPAttributeFieldCode()
	{
		return getLDAPAttributeFieldCode(getContext());
	}

	/**
	 * @param context
	 * @return value of LDAPAttributeFieldCode
	 */
	public final interfaceshared.proxies.LDAPAttributeFieldCode getLDAPAttributeFieldCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.LDAPAttributeFieldCode.toString());
		if (obj == null)
			return null;

		return interfaceshared.proxies.LDAPAttributeFieldCode.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of LDAPAttributeFieldCode
	 * @param ldapattributefieldcode
	 */
	public final void setLDAPAttributeFieldCode(interfaceshared.proxies.LDAPAttributeFieldCode ldapattributefieldcode)
	{
		setLDAPAttributeFieldCode(getContext(), ldapattributefieldcode);
	}

	/**
	 * Set value of LDAPAttributeFieldCode
	 * @param context
	 * @param ldapattributefieldcode
	 */
	public final void setLDAPAttributeFieldCode(com.mendix.systemwideinterfaces.core.IContext context, interfaceshared.proxies.LDAPAttributeFieldCode ldapattributefieldcode)
	{
		if (ldapattributefieldcode != null)
			getMendixObject().setValue(context, MemberNames.LDAPAttributeFieldCode.toString(), ldapattributefieldcode.toString());
		else
			getMendixObject().setValue(context, MemberNames.LDAPAttributeFieldCode.toString(), null);
	}

	/**
	 * @return value of DefaultTableItem_InterfaceMessageConfiguration
	 */
	public final interfaceconfiguration.proxies.InterfaceMessageConfiguration getDefaultTableItem_InterfaceMessageConfiguration() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_InterfaceMessageConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_InterfaceMessageConfiguration
	 */
	public final interfaceconfiguration.proxies.InterfaceMessageConfiguration getDefaultTableItem_InterfaceMessageConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceconfiguration.proxies.InterfaceMessageConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_InterfaceMessageConfiguration.toString());
		if (identifier != null)
			result = interfaceconfiguration.proxies.InterfaceMessageConfiguration.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_InterfaceMessageConfiguration
	 * @param defaulttableitem_interfacemessageconfiguration
	 */
	public final void setDefaultTableItem_InterfaceMessageConfiguration(interfaceconfiguration.proxies.InterfaceMessageConfiguration defaulttableitem_interfacemessageconfiguration)
	{
		setDefaultTableItem_InterfaceMessageConfiguration(getContext(), defaulttableitem_interfacemessageconfiguration);
	}

	/**
	 * Set value of DefaultTableItem_InterfaceMessageConfiguration
	 * @param context
	 * @param defaulttableitem_interfacemessageconfiguration
	 */
	public final void setDefaultTableItem_InterfaceMessageConfiguration(com.mendix.systemwideinterfaces.core.IContext context, interfaceconfiguration.proxies.InterfaceMessageConfiguration defaulttableitem_interfacemessageconfiguration)
	{
		if (defaulttableitem_interfacemessageconfiguration == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_InterfaceMessageConfiguration.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_InterfaceMessageConfiguration.toString(), defaulttableitem_interfacemessageconfiguration.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_LDAPImportType
	 */
	public final interfaceconfiguration.proxies.LDAPImportType getDefaultTableItem_LDAPImportType() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_LDAPImportType(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_LDAPImportType
	 */
	public final interfaceconfiguration.proxies.LDAPImportType getDefaultTableItem_LDAPImportType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceconfiguration.proxies.LDAPImportType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_LDAPImportType.toString());
		if (identifier != null)
			result = interfaceconfiguration.proxies.LDAPImportType.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_LDAPImportType
	 * @param defaulttableitem_ldapimporttype
	 */
	public final void setDefaultTableItem_LDAPImportType(interfaceconfiguration.proxies.LDAPImportType defaulttableitem_ldapimporttype)
	{
		setDefaultTableItem_LDAPImportType(getContext(), defaulttableitem_ldapimporttype);
	}

	/**
	 * Set value of DefaultTableItem_LDAPImportType
	 * @param context
	 * @param defaulttableitem_ldapimporttype
	 */
	public final void setDefaultTableItem_LDAPImportType(com.mendix.systemwideinterfaces.core.IContext context, interfaceconfiguration.proxies.LDAPImportType defaulttableitem_ldapimporttype)
	{
		if (defaulttableitem_ldapimporttype == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_LDAPImportType.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_LDAPImportType.toString(), defaulttableitem_ldapimporttype.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_Location
	 */
	public final nap.proxies.Location getDefaultTableItem_Location() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_Location(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_Location
	 */
	public final nap.proxies.Location getDefaultTableItem_Location(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		nap.proxies.Location result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_Location.toString());
		if (identifier != null)
			result = nap.proxies.Location.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_Location
	 * @param defaulttableitem_location
	 */
	public final void setDefaultTableItem_Location(nap.proxies.Location defaulttableitem_location)
	{
		setDefaultTableItem_Location(getContext(), defaulttableitem_location);
	}

	/**
	 * Set value of DefaultTableItem_Location
	 * @param context
	 * @param defaulttableitem_location
	 */
	public final void setDefaultTableItem_Location(com.mendix.systemwideinterfaces.core.IContext context, nap.proxies.Location defaulttableitem_location)
	{
		if (defaulttableitem_location == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_Location.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_Location.toString(), defaulttableitem_location.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_Organisation
	 */
	public final nap.proxies.Organisation getDefaultTableItem_Organisation() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_Organisation(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_Organisation
	 */
	public final nap.proxies.Organisation getDefaultTableItem_Organisation(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		nap.proxies.Organisation result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_Organisation.toString());
		if (identifier != null)
			result = nap.proxies.Organisation.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_Organisation
	 * @param defaulttableitem_organisation
	 */
	public final void setDefaultTableItem_Organisation(nap.proxies.Organisation defaulttableitem_organisation)
	{
		setDefaultTableItem_Organisation(getContext(), defaulttableitem_organisation);
	}

	/**
	 * Set value of DefaultTableItem_Organisation
	 * @param context
	 * @param defaulttableitem_organisation
	 */
	public final void setDefaultTableItem_Organisation(com.mendix.systemwideinterfaces.core.IContext context, nap.proxies.Organisation defaulttableitem_organisation)
	{
		if (defaulttableitem_organisation == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_Organisation.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_Organisation.toString(), defaulttableitem_organisation.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_IncidentOpeningCategory
	 */
	public final categories.proxies.Category getDefaultTableItem_IncidentOpeningCategory() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_IncidentOpeningCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_IncidentOpeningCategory
	 */
	public final categories.proxies.Category getDefaultTableItem_IncidentOpeningCategory(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		categories.proxies.Category result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_IncidentOpeningCategory.toString());
		if (identifier != null)
			result = categories.proxies.Category.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_IncidentOpeningCategory
	 * @param defaulttableitem_incidentopeningcategory
	 */
	public final void setDefaultTableItem_IncidentOpeningCategory(categories.proxies.Category defaulttableitem_incidentopeningcategory)
	{
		setDefaultTableItem_IncidentOpeningCategory(getContext(), defaulttableitem_incidentopeningcategory);
	}

	/**
	 * Set value of DefaultTableItem_IncidentOpeningCategory
	 * @param context
	 * @param defaulttableitem_incidentopeningcategory
	 */
	public final void setDefaultTableItem_IncidentOpeningCategory(com.mendix.systemwideinterfaces.core.IContext context, categories.proxies.Category defaulttableitem_incidentopeningcategory)
	{
		if (defaulttableitem_incidentopeningcategory == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_IncidentOpeningCategory.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_IncidentOpeningCategory.toString(), defaulttableitem_incidentopeningcategory.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_ConfigurationItem
	 */
	public final cmdb.proxies.ConfigurationItem getDefaultTableItem_ConfigurationItem() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_ConfigurationItem(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_ConfigurationItem
	 */
	public final cmdb.proxies.ConfigurationItem getDefaultTableItem_ConfigurationItem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmdb.proxies.ConfigurationItem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_ConfigurationItem.toString());
		if (identifier != null)
			result = cmdb.proxies.ConfigurationItem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_ConfigurationItem
	 * @param defaulttableitem_configurationitem
	 */
	public final void setDefaultTableItem_ConfigurationItem(cmdb.proxies.ConfigurationItem defaulttableitem_configurationitem)
	{
		setDefaultTableItem_ConfigurationItem(getContext(), defaulttableitem_configurationitem);
	}

	/**
	 * Set value of DefaultTableItem_ConfigurationItem
	 * @param context
	 * @param defaulttableitem_configurationitem
	 */
	public final void setDefaultTableItem_ConfigurationItem(com.mendix.systemwideinterfaces.core.IContext context, cmdb.proxies.ConfigurationItem defaulttableitem_configurationitem)
	{
		if (defaulttableitem_configurationitem == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_ConfigurationItem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_ConfigurationItem.toString(), defaulttableitem_configurationitem.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_Impact
	 */
	public final slm.proxies.Impact getDefaultTableItem_Impact() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_Impact(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_Impact
	 */
	public final slm.proxies.Impact getDefaultTableItem_Impact(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		slm.proxies.Impact result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_Impact.toString());
		if (identifier != null)
			result = slm.proxies.Impact.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_Impact
	 * @param defaulttableitem_impact
	 */
	public final void setDefaultTableItem_Impact(slm.proxies.Impact defaulttableitem_impact)
	{
		setDefaultTableItem_Impact(getContext(), defaulttableitem_impact);
	}

	/**
	 * Set value of DefaultTableItem_Impact
	 * @param context
	 * @param defaulttableitem_impact
	 */
	public final void setDefaultTableItem_Impact(com.mendix.systemwideinterfaces.core.IContext context, slm.proxies.Impact defaulttableitem_impact)
	{
		if (defaulttableitem_impact == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_Impact.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_Impact.toString(), defaulttableitem_impact.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_Urgency
	 */
	public final slm.proxies.Urgency getDefaultTableItem_Urgency() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_Urgency(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_Urgency
	 */
	public final slm.proxies.Urgency getDefaultTableItem_Urgency(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		slm.proxies.Urgency result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_Urgency.toString());
		if (identifier != null)
			result = slm.proxies.Urgency.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_Urgency
	 * @param defaulttableitem_urgency
	 */
	public final void setDefaultTableItem_Urgency(slm.proxies.Urgency defaulttableitem_urgency)
	{
		setDefaultTableItem_Urgency(getContext(), defaulttableitem_urgency);
	}

	/**
	 * Set value of DefaultTableItem_Urgency
	 * @param context
	 * @param defaulttableitem_urgency
	 */
	public final void setDefaultTableItem_Urgency(com.mendix.systemwideinterfaces.core.IContext context, slm.proxies.Urgency defaulttableitem_urgency)
	{
		if (defaulttableitem_urgency == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_Urgency.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_Urgency.toString(), defaulttableitem_urgency.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_Service
	 */
	public final slm.proxies.Service getDefaultTableItem_Service() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_Service(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_Service
	 */
	public final slm.proxies.Service getDefaultTableItem_Service(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		slm.proxies.Service result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_Service.toString());
		if (identifier != null)
			result = slm.proxies.Service.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_Service
	 * @param defaulttableitem_service
	 */
	public final void setDefaultTableItem_Service(slm.proxies.Service defaulttableitem_service)
	{
		setDefaultTableItem_Service(getContext(), defaulttableitem_service);
	}

	/**
	 * Set value of DefaultTableItem_Service
	 * @param context
	 * @param defaulttableitem_service
	 */
	public final void setDefaultTableItem_Service(com.mendix.systemwideinterfaces.core.IContext context, slm.proxies.Service defaulttableitem_service)
	{
		if (defaulttableitem_service == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_Service.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_Service.toString(), defaulttableitem_service.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_Service_Process
	 */
	public final slm.proxies.Service_Process getDefaultTableItem_Service_Process() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_Service_Process(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_Service_Process
	 */
	public final slm.proxies.Service_Process getDefaultTableItem_Service_Process(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		slm.proxies.Service_Process result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_Service_Process.toString());
		if (identifier != null)
			result = slm.proxies.Service_Process.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_Service_Process
	 * @param defaulttableitem_service_process
	 */
	public final void setDefaultTableItem_Service_Process(slm.proxies.Service_Process defaulttableitem_service_process)
	{
		setDefaultTableItem_Service_Process(getContext(), defaulttableitem_service_process);
	}

	/**
	 * Set value of DefaultTableItem_Service_Process
	 * @param context
	 * @param defaulttableitem_service_process
	 */
	public final void setDefaultTableItem_Service_Process(com.mendix.systemwideinterfaces.core.IContext context, slm.proxies.Service_Process defaulttableitem_service_process)
	{
		if (defaulttableitem_service_process == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_Service_Process.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_Service_Process.toString(), defaulttableitem_service_process.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_Person
	 */
	public final nap.proxies.Person getDefaultTableItem_Person() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_Person(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_Person
	 */
	public final nap.proxies.Person getDefaultTableItem_Person(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		nap.proxies.Person result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_Person.toString());
		if (identifier != null)
			result = nap.proxies.Person.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_Person
	 * @param defaulttableitem_person
	 */
	public final void setDefaultTableItem_Person(nap.proxies.Person defaulttableitem_person)
	{
		setDefaultTableItem_Person(getContext(), defaulttableitem_person);
	}

	/**
	 * Set value of DefaultTableItem_Person
	 * @param context
	 * @param defaulttableitem_person
	 */
	public final void setDefaultTableItem_Person(com.mendix.systemwideinterfaces.core.IContext context, nap.proxies.Person defaulttableitem_person)
	{
		if (defaulttableitem_person == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_Person.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_Person.toString(), defaulttableitem_person.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_State
	 */
	public final statetransition.proxies.State getDefaultTableItem_State() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_State(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_State
	 */
	public final statetransition.proxies.State getDefaultTableItem_State(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		statetransition.proxies.State result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_State.toString());
		if (identifier != null)
			result = statetransition.proxies.State.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_State
	 * @param defaulttableitem_state
	 */
	public final void setDefaultTableItem_State(statetransition.proxies.State defaulttableitem_state)
	{
		setDefaultTableItem_State(getContext(), defaulttableitem_state);
	}

	/**
	 * Set value of DefaultTableItem_State
	 * @param context
	 * @param defaulttableitem_state
	 */
	public final void setDefaultTableItem_State(com.mendix.systemwideinterfaces.core.IContext context, statetransition.proxies.State defaulttableitem_state)
	{
		if (defaulttableitem_state == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_State.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_State.toString(), defaulttableitem_state.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_Phase
	 */
	public final statetransition.proxies.Phase getDefaultTableItem_Phase() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_Phase(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_Phase
	 */
	public final statetransition.proxies.Phase getDefaultTableItem_Phase(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		statetransition.proxies.Phase result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_Phase.toString());
		if (identifier != null)
			result = statetransition.proxies.Phase.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_Phase
	 * @param defaulttableitem_phase
	 */
	public final void setDefaultTableItem_Phase(statetransition.proxies.Phase defaulttableitem_phase)
	{
		setDefaultTableItem_Phase(getContext(), defaulttableitem_phase);
	}

	/**
	 * Set value of DefaultTableItem_Phase
	 * @param context
	 * @param defaulttableitem_phase
	 */
	public final void setDefaultTableItem_Phase(com.mendix.systemwideinterfaces.core.IContext context, statetransition.proxies.Phase defaulttableitem_phase)
	{
		if (defaulttableitem_phase == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_Phase.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_Phase.toString(), defaulttableitem_phase.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_ProblemOpeningCategory
	 */
	public final categories.proxies.Category getDefaultTableItem_ProblemOpeningCategory() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_ProblemOpeningCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_ProblemOpeningCategory
	 */
	public final categories.proxies.Category getDefaultTableItem_ProblemOpeningCategory(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		categories.proxies.Category result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_ProblemOpeningCategory.toString());
		if (identifier != null)
			result = categories.proxies.Category.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_ProblemOpeningCategory
	 * @param defaulttableitem_problemopeningcategory
	 */
	public final void setDefaultTableItem_ProblemOpeningCategory(categories.proxies.Category defaulttableitem_problemopeningcategory)
	{
		setDefaultTableItem_ProblemOpeningCategory(getContext(), defaulttableitem_problemopeningcategory);
	}

	/**
	 * Set value of DefaultTableItem_ProblemOpeningCategory
	 * @param context
	 * @param defaulttableitem_problemopeningcategory
	 */
	public final void setDefaultTableItem_ProblemOpeningCategory(com.mendix.systemwideinterfaces.core.IContext context, categories.proxies.Category defaulttableitem_problemopeningcategory)
	{
		if (defaulttableitem_problemopeningcategory == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_ProblemOpeningCategory.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_ProblemOpeningCategory.toString(), defaulttableitem_problemopeningcategory.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_ChangeOpeningCategory
	 */
	public final categories.proxies.Category getDefaultTableItem_ChangeOpeningCategory() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_ChangeOpeningCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_ChangeOpeningCategory
	 */
	public final categories.proxies.Category getDefaultTableItem_ChangeOpeningCategory(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		categories.proxies.Category result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_ChangeOpeningCategory.toString());
		if (identifier != null)
			result = categories.proxies.Category.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_ChangeOpeningCategory
	 * @param defaulttableitem_changeopeningcategory
	 */
	public final void setDefaultTableItem_ChangeOpeningCategory(categories.proxies.Category defaulttableitem_changeopeningcategory)
	{
		setDefaultTableItem_ChangeOpeningCategory(getContext(), defaulttableitem_changeopeningcategory);
	}

	/**
	 * Set value of DefaultTableItem_ChangeOpeningCategory
	 * @param context
	 * @param defaulttableitem_changeopeningcategory
	 */
	public final void setDefaultTableItem_ChangeOpeningCategory(com.mendix.systemwideinterfaces.core.IContext context, categories.proxies.Category defaulttableitem_changeopeningcategory)
	{
		if (defaulttableitem_changeopeningcategory == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_ChangeOpeningCategory.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_ChangeOpeningCategory.toString(), defaulttableitem_changeopeningcategory.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_OperationOpeningCategory
	 */
	public final categories.proxies.Category getDefaultTableItem_OperationOpeningCategory() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_OperationOpeningCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_OperationOpeningCategory
	 */
	public final categories.proxies.Category getDefaultTableItem_OperationOpeningCategory(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		categories.proxies.Category result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_OperationOpeningCategory.toString());
		if (identifier != null)
			result = categories.proxies.Category.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_OperationOpeningCategory
	 * @param defaulttableitem_operationopeningcategory
	 */
	public final void setDefaultTableItem_OperationOpeningCategory(categories.proxies.Category defaulttableitem_operationopeningcategory)
	{
		setDefaultTableItem_OperationOpeningCategory(getContext(), defaulttableitem_operationopeningcategory);
	}

	/**
	 * Set value of DefaultTableItem_OperationOpeningCategory
	 * @param context
	 * @param defaulttableitem_operationopeningcategory
	 */
	public final void setDefaultTableItem_OperationOpeningCategory(com.mendix.systemwideinterfaces.core.IContext context, categories.proxies.Category defaulttableitem_operationopeningcategory)
	{
		if (defaulttableitem_operationopeningcategory == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_OperationOpeningCategory.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_OperationOpeningCategory.toString(), defaulttableitem_operationopeningcategory.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_DeliveryOpeningCategory
	 */
	public final categories.proxies.Category getDefaultTableItem_DeliveryOpeningCategory() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_DeliveryOpeningCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_DeliveryOpeningCategory
	 */
	public final categories.proxies.Category getDefaultTableItem_DeliveryOpeningCategory(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		categories.proxies.Category result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_DeliveryOpeningCategory.toString());
		if (identifier != null)
			result = categories.proxies.Category.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_DeliveryOpeningCategory
	 * @param defaulttableitem_deliveryopeningcategory
	 */
	public final void setDefaultTableItem_DeliveryOpeningCategory(categories.proxies.Category defaulttableitem_deliveryopeningcategory)
	{
		setDefaultTableItem_DeliveryOpeningCategory(getContext(), defaulttableitem_deliveryopeningcategory);
	}

	/**
	 * Set value of DefaultTableItem_DeliveryOpeningCategory
	 * @param context
	 * @param defaulttableitem_deliveryopeningcategory
	 */
	public final void setDefaultTableItem_DeliveryOpeningCategory(com.mendix.systemwideinterfaces.core.IContext context, categories.proxies.Category defaulttableitem_deliveryopeningcategory)
	{
		if (defaulttableitem_deliveryopeningcategory == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_DeliveryOpeningCategory.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_DeliveryOpeningCategory.toString(), defaulttableitem_deliveryopeningcategory.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_ServiceRequestOpeningCategory
	 */
	public final categories.proxies.Category getDefaultTableItem_ServiceRequestOpeningCategory() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_ServiceRequestOpeningCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_ServiceRequestOpeningCategory
	 */
	public final categories.proxies.Category getDefaultTableItem_ServiceRequestOpeningCategory(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		categories.proxies.Category result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_ServiceRequestOpeningCategory.toString());
		if (identifier != null)
			result = categories.proxies.Category.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_ServiceRequestOpeningCategory
	 * @param defaulttableitem_servicerequestopeningcategory
	 */
	public final void setDefaultTableItem_ServiceRequestOpeningCategory(categories.proxies.Category defaulttableitem_servicerequestopeningcategory)
	{
		setDefaultTableItem_ServiceRequestOpeningCategory(getContext(), defaulttableitem_servicerequestopeningcategory);
	}

	/**
	 * Set value of DefaultTableItem_ServiceRequestOpeningCategory
	 * @param context
	 * @param defaulttableitem_servicerequestopeningcategory
	 */
	public final void setDefaultTableItem_ServiceRequestOpeningCategory(com.mendix.systemwideinterfaces.core.IContext context, categories.proxies.Category defaulttableitem_servicerequestopeningcategory)
	{
		if (defaulttableitem_servicerequestopeningcategory == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_ServiceRequestOpeningCategory.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_ServiceRequestOpeningCategory.toString(), defaulttableitem_servicerequestopeningcategory.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_IncidentClosureCategory
	 */
	public final categories.proxies.Category getDefaultTableItem_IncidentClosureCategory() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_IncidentClosureCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_IncidentClosureCategory
	 */
	public final categories.proxies.Category getDefaultTableItem_IncidentClosureCategory(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		categories.proxies.Category result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_IncidentClosureCategory.toString());
		if (identifier != null)
			result = categories.proxies.Category.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_IncidentClosureCategory
	 * @param defaulttableitem_incidentclosurecategory
	 */
	public final void setDefaultTableItem_IncidentClosureCategory(categories.proxies.Category defaulttableitem_incidentclosurecategory)
	{
		setDefaultTableItem_IncidentClosureCategory(getContext(), defaulttableitem_incidentclosurecategory);
	}

	/**
	 * Set value of DefaultTableItem_IncidentClosureCategory
	 * @param context
	 * @param defaulttableitem_incidentclosurecategory
	 */
	public final void setDefaultTableItem_IncidentClosureCategory(com.mendix.systemwideinterfaces.core.IContext context, categories.proxies.Category defaulttableitem_incidentclosurecategory)
	{
		if (defaulttableitem_incidentclosurecategory == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_IncidentClosureCategory.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_IncidentClosureCategory.toString(), defaulttableitem_incidentclosurecategory.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_ProblemClosureCategory
	 */
	public final categories.proxies.Category getDefaultTableItem_ProblemClosureCategory() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_ProblemClosureCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_ProblemClosureCategory
	 */
	public final categories.proxies.Category getDefaultTableItem_ProblemClosureCategory(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		categories.proxies.Category result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_ProblemClosureCategory.toString());
		if (identifier != null)
			result = categories.proxies.Category.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_ProblemClosureCategory
	 * @param defaulttableitem_problemclosurecategory
	 */
	public final void setDefaultTableItem_ProblemClosureCategory(categories.proxies.Category defaulttableitem_problemclosurecategory)
	{
		setDefaultTableItem_ProblemClosureCategory(getContext(), defaulttableitem_problemclosurecategory);
	}

	/**
	 * Set value of DefaultTableItem_ProblemClosureCategory
	 * @param context
	 * @param defaulttableitem_problemclosurecategory
	 */
	public final void setDefaultTableItem_ProblemClosureCategory(com.mendix.systemwideinterfaces.core.IContext context, categories.proxies.Category defaulttableitem_problemclosurecategory)
	{
		if (defaulttableitem_problemclosurecategory == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_ProblemClosureCategory.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_ProblemClosureCategory.toString(), defaulttableitem_problemclosurecategory.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_ChangeClosureCategory
	 */
	public final categories.proxies.Category getDefaultTableItem_ChangeClosureCategory() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_ChangeClosureCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_ChangeClosureCategory
	 */
	public final categories.proxies.Category getDefaultTableItem_ChangeClosureCategory(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		categories.proxies.Category result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_ChangeClosureCategory.toString());
		if (identifier != null)
			result = categories.proxies.Category.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_ChangeClosureCategory
	 * @param defaulttableitem_changeclosurecategory
	 */
	public final void setDefaultTableItem_ChangeClosureCategory(categories.proxies.Category defaulttableitem_changeclosurecategory)
	{
		setDefaultTableItem_ChangeClosureCategory(getContext(), defaulttableitem_changeclosurecategory);
	}

	/**
	 * Set value of DefaultTableItem_ChangeClosureCategory
	 * @param context
	 * @param defaulttableitem_changeclosurecategory
	 */
	public final void setDefaultTableItem_ChangeClosureCategory(com.mendix.systemwideinterfaces.core.IContext context, categories.proxies.Category defaulttableitem_changeclosurecategory)
	{
		if (defaulttableitem_changeclosurecategory == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_ChangeClosureCategory.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_ChangeClosureCategory.toString(), defaulttableitem_changeclosurecategory.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_OperationClosureCategory
	 */
	public final categories.proxies.Category getDefaultTableItem_OperationClosureCategory() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_OperationClosureCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_OperationClosureCategory
	 */
	public final categories.proxies.Category getDefaultTableItem_OperationClosureCategory(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		categories.proxies.Category result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_OperationClosureCategory.toString());
		if (identifier != null)
			result = categories.proxies.Category.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_OperationClosureCategory
	 * @param defaulttableitem_operationclosurecategory
	 */
	public final void setDefaultTableItem_OperationClosureCategory(categories.proxies.Category defaulttableitem_operationclosurecategory)
	{
		setDefaultTableItem_OperationClosureCategory(getContext(), defaulttableitem_operationclosurecategory);
	}

	/**
	 * Set value of DefaultTableItem_OperationClosureCategory
	 * @param context
	 * @param defaulttableitem_operationclosurecategory
	 */
	public final void setDefaultTableItem_OperationClosureCategory(com.mendix.systemwideinterfaces.core.IContext context, categories.proxies.Category defaulttableitem_operationclosurecategory)
	{
		if (defaulttableitem_operationclosurecategory == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_OperationClosureCategory.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_OperationClosureCategory.toString(), defaulttableitem_operationclosurecategory.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_DeliveryClosureCategory
	 */
	public final categories.proxies.Category getDefaultTableItem_DeliveryClosureCategory() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_DeliveryClosureCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_DeliveryClosureCategory
	 */
	public final categories.proxies.Category getDefaultTableItem_DeliveryClosureCategory(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		categories.proxies.Category result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_DeliveryClosureCategory.toString());
		if (identifier != null)
			result = categories.proxies.Category.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_DeliveryClosureCategory
	 * @param defaulttableitem_deliveryclosurecategory
	 */
	public final void setDefaultTableItem_DeliveryClosureCategory(categories.proxies.Category defaulttableitem_deliveryclosurecategory)
	{
		setDefaultTableItem_DeliveryClosureCategory(getContext(), defaulttableitem_deliveryclosurecategory);
	}

	/**
	 * Set value of DefaultTableItem_DeliveryClosureCategory
	 * @param context
	 * @param defaulttableitem_deliveryclosurecategory
	 */
	public final void setDefaultTableItem_DeliveryClosureCategory(com.mendix.systemwideinterfaces.core.IContext context, categories.proxies.Category defaulttableitem_deliveryclosurecategory)
	{
		if (defaulttableitem_deliveryclosurecategory == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_DeliveryClosureCategory.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_DeliveryClosureCategory.toString(), defaulttableitem_deliveryclosurecategory.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_ServiceRequestClosureCategory
	 */
	public final categories.proxies.Category getDefaultTableItem_ServiceRequestClosureCategory() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_ServiceRequestClosureCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_ServiceRequestClosureCategory
	 */
	public final categories.proxies.Category getDefaultTableItem_ServiceRequestClosureCategory(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		categories.proxies.Category result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_ServiceRequestClosureCategory.toString());
		if (identifier != null)
			result = categories.proxies.Category.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_ServiceRequestClosureCategory
	 * @param defaulttableitem_servicerequestclosurecategory
	 */
	public final void setDefaultTableItem_ServiceRequestClosureCategory(categories.proxies.Category defaulttableitem_servicerequestclosurecategory)
	{
		setDefaultTableItem_ServiceRequestClosureCategory(getContext(), defaulttableitem_servicerequestclosurecategory);
	}

	/**
	 * Set value of DefaultTableItem_ServiceRequestClosureCategory
	 * @param context
	 * @param defaulttableitem_servicerequestclosurecategory
	 */
	public final void setDefaultTableItem_ServiceRequestClosureCategory(com.mendix.systemwideinterfaces.core.IContext context, categories.proxies.Category defaulttableitem_servicerequestclosurecategory)
	{
		if (defaulttableitem_servicerequestclosurecategory == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_ServiceRequestClosureCategory.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_ServiceRequestClosureCategory.toString(), defaulttableitem_servicerequestclosurecategory.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_CMDBType
	 */
	public final cmdb.proxies.CMDBType getDefaultTableItem_CMDBType() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_CMDBType(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_CMDBType
	 */
	public final cmdb.proxies.CMDBType getDefaultTableItem_CMDBType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmdb.proxies.CMDBType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_CMDBType.toString());
		if (identifier != null)
			result = cmdb.proxies.CMDBType.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_CMDBType
	 * @param defaulttableitem_cmdbtype
	 */
	public final void setDefaultTableItem_CMDBType(cmdb.proxies.CMDBType defaulttableitem_cmdbtype)
	{
		setDefaultTableItem_CMDBType(getContext(), defaulttableitem_cmdbtype);
	}

	/**
	 * Set value of DefaultTableItem_CMDBType
	 * @param context
	 * @param defaulttableitem_cmdbtype
	 */
	public final void setDefaultTableItem_CMDBType(com.mendix.systemwideinterfaces.core.IContext context, cmdb.proxies.CMDBType defaulttableitem_cmdbtype)
	{
		if (defaulttableitem_cmdbtype == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_CMDBType.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_CMDBType.toString(), defaulttableitem_cmdbtype.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_PausedReasonDefinition
	 */
	public final process.proxies.PausedReasonDefinition getDefaultTableItem_PausedReasonDefinition() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_PausedReasonDefinition(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_PausedReasonDefinition
	 */
	public final process.proxies.PausedReasonDefinition getDefaultTableItem_PausedReasonDefinition(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		process.proxies.PausedReasonDefinition result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_PausedReasonDefinition.toString());
		if (identifier != null)
			result = process.proxies.PausedReasonDefinition.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_PausedReasonDefinition
	 * @param defaulttableitem_pausedreasondefinition
	 */
	public final void setDefaultTableItem_PausedReasonDefinition(process.proxies.PausedReasonDefinition defaulttableitem_pausedreasondefinition)
	{
		setDefaultTableItem_PausedReasonDefinition(getContext(), defaulttableitem_pausedreasondefinition);
	}

	/**
	 * Set value of DefaultTableItem_PausedReasonDefinition
	 * @param context
	 * @param defaulttableitem_pausedreasondefinition
	 */
	public final void setDefaultTableItem_PausedReasonDefinition(com.mendix.systemwideinterfaces.core.IContext context, process.proxies.PausedReasonDefinition defaulttableitem_pausedreasondefinition)
	{
		if (defaulttableitem_pausedreasondefinition == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_PausedReasonDefinition.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_PausedReasonDefinition.toString(), defaulttableitem_pausedreasondefinition.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_Language
	 */
	public final system.proxies.Language getDefaultTableItem_Language() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_Language(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_Language
	 */
	public final system.proxies.Language getDefaultTableItem_Language(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Language result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_Language.toString());
		if (identifier != null)
			result = system.proxies.Language.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_Language
	 * @param defaulttableitem_language
	 */
	public final void setDefaultTableItem_Language(system.proxies.Language defaulttableitem_language)
	{
		setDefaultTableItem_Language(getContext(), defaulttableitem_language);
	}

	/**
	 * Set value of DefaultTableItem_Language
	 * @param context
	 * @param defaulttableitem_language
	 */
	public final void setDefaultTableItem_Language(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Language defaulttableitem_language)
	{
		if (defaulttableitem_language == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_Language.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_Language.toString(), defaulttableitem_language.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_Template
	 */
	public final java.util.List<roletemplates.proxies.Template> getDefaultTableItem_Template() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_Template(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_Template
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<roletemplates.proxies.Template> getDefaultTableItem_Template(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<roletemplates.proxies.Template> result = new java.util.ArrayList<roletemplates.proxies.Template>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.DefaultTableItem_Template.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(roletemplates.proxies.Template.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of DefaultTableItem_Template
	 * @param defaulttableitem_template
	 */
	public final void setDefaultTableItem_Template(java.util.List<roletemplates.proxies.Template> defaulttableitem_template)
	{
		setDefaultTableItem_Template(getContext(), defaulttableitem_template);
	}

	/**
	 * Set value of DefaultTableItem_Template
	 * @param context
	 * @param defaulttableitem_template
	 */
	public final void setDefaultTableItem_Template(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<roletemplates.proxies.Template> defaulttableitem_template)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (roletemplates.proxies.Template proxyObject : defaulttableitem_template)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.DefaultTableItem_Template.toString(), identifiers);
	}

	/**
	 * @return value of DefaultTableItem_UserRole
	 */
	public final java.util.List<system.proxies.UserRole> getDefaultTableItem_UserRole() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_UserRole(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_UserRole
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<system.proxies.UserRole> getDefaultTableItem_UserRole(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<system.proxies.UserRole> result = new java.util.ArrayList<system.proxies.UserRole>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.DefaultTableItem_UserRole.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(system.proxies.UserRole.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of DefaultTableItem_UserRole
	 * @param defaulttableitem_userrole
	 */
	public final void setDefaultTableItem_UserRole(java.util.List<system.proxies.UserRole> defaulttableitem_userrole)
	{
		setDefaultTableItem_UserRole(getContext(), defaulttableitem_userrole);
	}

	/**
	 * Set value of DefaultTableItem_UserRole
	 * @param context
	 * @param defaulttableitem_userrole
	 */
	public final void setDefaultTableItem_UserRole(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<system.proxies.UserRole> defaulttableitem_userrole)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (system.proxies.UserRole proxyObject : defaulttableitem_userrole)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.DefaultTableItem_UserRole.toString(), identifiers);
	}

	/**
	 * @return value of DefaultTableItem_TimeZone
	 */
	public final system.proxies.TimeZone getDefaultTableItem_TimeZone() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_TimeZone(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_TimeZone
	 */
	public final system.proxies.TimeZone getDefaultTableItem_TimeZone(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.TimeZone result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_TimeZone.toString());
		if (identifier != null)
			result = system.proxies.TimeZone.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_TimeZone
	 * @param defaulttableitem_timezone
	 */
	public final void setDefaultTableItem_TimeZone(system.proxies.TimeZone defaulttableitem_timezone)
	{
		setDefaultTableItem_TimeZone(getContext(), defaulttableitem_timezone);
	}

	/**
	 * Set value of DefaultTableItem_TimeZone
	 * @param context
	 * @param defaulttableitem_timezone
	 */
	public final void setDefaultTableItem_TimeZone(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.TimeZone defaulttableitem_timezone)
	{
		if (defaulttableitem_timezone == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_TimeZone.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_TimeZone.toString(), defaulttableitem_timezone.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_Locations
	 */
	public final java.util.List<nap.proxies.Location> getDefaultTableItem_Locations() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_Locations(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_Locations
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<nap.proxies.Location> getDefaultTableItem_Locations(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<nap.proxies.Location> result = new java.util.ArrayList<nap.proxies.Location>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.DefaultTableItem_Locations.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(nap.proxies.Location.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of DefaultTableItem_Locations
	 * @param defaulttableitem_locations
	 */
	public final void setDefaultTableItem_Locations(java.util.List<nap.proxies.Location> defaulttableitem_locations)
	{
		setDefaultTableItem_Locations(getContext(), defaulttableitem_locations);
	}

	/**
	 * Set value of DefaultTableItem_Locations
	 * @param context
	 * @param defaulttableitem_locations
	 */
	public final void setDefaultTableItem_Locations(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<nap.proxies.Location> defaulttableitem_locations)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (nap.proxies.Location proxyObject : defaulttableitem_locations)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.DefaultTableItem_Locations.toString(), identifiers);
	}

	/**
	 * @return value of DefaultTableItem_Customers
	 */
	public final java.util.List<nap.proxies.Customer> getDefaultTableItem_Customers() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_Customers(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_Customers
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<nap.proxies.Customer> getDefaultTableItem_Customers(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<nap.proxies.Customer> result = new java.util.ArrayList<nap.proxies.Customer>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.DefaultTableItem_Customers.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(nap.proxies.Customer.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of DefaultTableItem_Customers
	 * @param defaulttableitem_customers
	 */
	public final void setDefaultTableItem_Customers(java.util.List<nap.proxies.Customer> defaulttableitem_customers)
	{
		setDefaultTableItem_Customers(getContext(), defaulttableitem_customers);
	}

	/**
	 * Set value of DefaultTableItem_Customers
	 * @param context
	 * @param defaulttableitem_customers
	 */
	public final void setDefaultTableItem_Customers(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<nap.proxies.Customer> defaulttableitem_customers)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (nap.proxies.Customer proxyObject : defaulttableitem_customers)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.DefaultTableItem_Customers.toString(), identifiers);
	}

	/**
	 * @return value of DefaultTableItem_BusinessGroups
	 */
	public final java.util.List<nap.proxies.BusinessGroup> getDefaultTableItem_BusinessGroups() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_BusinessGroups(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_BusinessGroups
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<nap.proxies.BusinessGroup> getDefaultTableItem_BusinessGroups(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<nap.proxies.BusinessGroup> result = new java.util.ArrayList<nap.proxies.BusinessGroup>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.DefaultTableItem_BusinessGroups.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(nap.proxies.BusinessGroup.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of DefaultTableItem_BusinessGroups
	 * @param defaulttableitem_businessgroups
	 */
	public final void setDefaultTableItem_BusinessGroups(java.util.List<nap.proxies.BusinessGroup> defaulttableitem_businessgroups)
	{
		setDefaultTableItem_BusinessGroups(getContext(), defaulttableitem_businessgroups);
	}

	/**
	 * Set value of DefaultTableItem_BusinessGroups
	 * @param context
	 * @param defaulttableitem_businessgroups
	 */
	public final void setDefaultTableItem_BusinessGroups(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<nap.proxies.BusinessGroup> defaulttableitem_businessgroups)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (nap.proxies.BusinessGroup proxyObject : defaulttableitem_businessgroups)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.DefaultTableItem_BusinessGroups.toString(), identifiers);
	}

	/**
	 * @return value of DefaultTableItem_IUP_Combination
	 */
	public final slm.proxies.IUP_Combination getDefaultTableItem_IUP_Combination() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_IUP_Combination(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_IUP_Combination
	 */
	public final slm.proxies.IUP_Combination getDefaultTableItem_IUP_Combination(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		slm.proxies.IUP_Combination result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_IUP_Combination.toString());
		if (identifier != null)
			result = slm.proxies.IUP_Combination.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_IUP_Combination
	 * @param defaulttableitem_iup_combination
	 */
	public final void setDefaultTableItem_IUP_Combination(slm.proxies.IUP_Combination defaulttableitem_iup_combination)
	{
		setDefaultTableItem_IUP_Combination(getContext(), defaulttableitem_iup_combination);
	}

	/**
	 * Set value of DefaultTableItem_IUP_Combination
	 * @param context
	 * @param defaulttableitem_iup_combination
	 */
	public final void setDefaultTableItem_IUP_Combination(com.mendix.systemwideinterfaces.core.IContext context, slm.proxies.IUP_Combination defaulttableitem_iup_combination)
	{
		if (defaulttableitem_iup_combination == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_IUP_Combination.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_IUP_Combination.toString(), defaulttableitem_iup_combination.getMendixObject().getId());
	}

	/**
	 * @return value of DefaultTableItem_Priority
	 */
	public final slm.proxies.Priority getDefaultTableItem_Priority() throws com.mendix.core.CoreException
	{
		return getDefaultTableItem_Priority(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultTableItem_Priority
	 */
	public final slm.proxies.Priority getDefaultTableItem_Priority(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		slm.proxies.Priority result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefaultTableItem_Priority.toString());
		if (identifier != null)
			result = slm.proxies.Priority.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefaultTableItem_Priority
	 * @param defaulttableitem_priority
	 */
	public final void setDefaultTableItem_Priority(slm.proxies.Priority defaulttableitem_priority)
	{
		setDefaultTableItem_Priority(getContext(), defaulttableitem_priority);
	}

	/**
	 * Set value of DefaultTableItem_Priority
	 * @param context
	 * @param defaulttableitem_priority
	 */
	public final void setDefaultTableItem_Priority(com.mendix.systemwideinterfaces.core.IContext context, slm.proxies.Priority defaulttableitem_priority)
	{
		if (defaulttableitem_priority == null)
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_Priority.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefaultTableItem_Priority.toString(), defaulttableitem_priority.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final interfaceconfiguration.proxies.DefaultTableItem that = (interfaceconfiguration.proxies.DefaultTableItem) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "InterfaceConfiguration.DefaultTableItem";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
