// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package interfaceconfiguration.proxies;

public class InterfaceMonitoring
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject interfaceMonitoringMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "InterfaceConfiguration.InterfaceMonitoring";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MessageDirection("MessageDirection"),
		ShowNewRequest("ShowNewRequest"),
		ShowNewRequestConfirmation("ShowNewRequestConfirmation"),
		ShowAddUpdateDeleteAttachments("ShowAddUpdateDeleteAttachments"),
		ShowAddUpdateDeleteAttachmentsConfirmation("ShowAddUpdateDeleteAttachmentsConfirmation"),
		ShowAddNotes("ShowAddNotes"),
		ShowAddNotesConfirmation("ShowAddNotesConfirmation"),
		ShowAddUpdateDeleteRelations("ShowAddUpdateDeleteRelations"),
		ShowAddUpdateDeleteRelationsConfirmation("ShowAddUpdateDeleteRelationsConfirmation"),
		ShowAddUpdateDeleteExternalReferences("ShowAddUpdateDeleteExternalReferences"),
		ShowAddUpdateDeleteExternalReferencesConfirmation("ShowAddUpdateDeleteExternalReferencesConfirmation"),
		ShowAddUpdateDeleteAffectedCIs("ShowAddUpdateDeleteAffectedCIs"),
		ShowAddUpdateDeleteAffectedCIsConfirmation("ShowAddUpdateDeleteAffectedCIsConfirmation"),
		ShowContractAspectUpdate("ShowContractAspectUpdate"),
		ShowContractAspectUpdateConfirmation("ShowContractAspectUpdateConfirmation"),
		ShowRequestUpdate("ShowRequestUpdate"),
		ShowRequestUpdateConfirmation("ShowRequestUpdateConfirmation"),
		ShowHeartBeat("ShowHeartBeat"),
		ShowHeartBeatConfirmation("ShowHeartBeatConfirmation"),
		ShowLDAPImport("ShowLDAPImport"),
		FromDate("FromDate"),
		ToDate("ToDate"),
		ShowCritical("ShowCritical"),
		ShowError("ShowError"),
		ShowWarning("ShowWarning"),
		ShowInfo("ShowInfo"),
		ShowDebug("ShowDebug"),
		ShowTrace("ShowTrace"),
		ShowMessagesWithoutInterface("ShowMessagesWithoutInterface"),
		ShowMessagesWithInterface("ShowMessagesWithInterface"),
		MessagesSorting("MessagesSorting"),
		MessagesSortOrder("MessagesSortOrder"),
		ProcessingLogsSorting("ProcessingLogsSorting"),
		ProcessingLogsSortOrder("ProcessingLogsSortOrder"),
		ShowNotViewed("ShowNotViewed"),
		ShowViewed("ShowViewed"),
		ShowSolved("ShowSolved"),
		ShowIgnored("ShowIgnored"),
		MessagesChunkStart("MessagesChunkStart"),
		MessagesChunkStartShown("MessagesChunkStartShown"),
		MessagesChunkEnd("MessagesChunkEnd"),
		MessagesTotal("MessagesTotal"),
		MessagesFirstChunk("MessagesFirstChunk"),
		MessagesPreviousChunk("MessagesPreviousChunk"),
		MessagesNextChunk("MessagesNextChunk"),
		MessagesLastChunk("MessagesLastChunk"),
		MessagesIsFirstChunk("MessagesIsFirstChunk"),
		MessagesIsLastChunk("MessagesIsLastChunk"),
		ProcessingLogsChunkStart("ProcessingLogsChunkStart"),
		ProcessingLogsChunkStartShown("ProcessingLogsChunkStartShown"),
		ProcessingLogsChunkEnd("ProcessingLogsChunkEnd"),
		ProcessingLogsTotal("ProcessingLogsTotal"),
		ProcessingLogsFirstChunk("ProcessingLogsFirstChunk"),
		ProcessingLogsPreviousChunk("ProcessingLogsPreviousChunk"),
		ProcessingLogsNextChunk("ProcessingLogsNextChunk"),
		ProcessingLogsLastChunk("ProcessingLogsLastChunk"),
		ProcessingLogsIsFirstChunk("ProcessingLogsIsFirstChunk"),
		ProcessingLogsIsLastChunk("ProcessingLogsIsLastChunk"),
		MessageID("MessageID"),
		IndexSearchParam("IndexSearchParam"),
		MessageStatus("MessageStatus"),
		ShowCreatedByCustomMessage("ShowCreatedByCustomMessage"),
		InterfaceMonitoring_InterfaceConfiguration("InterfaceConfiguration.InterfaceMonitoring_InterfaceConfiguration"),
		UU95_InterfaceMonitoring_Message("InterfaceConfiguration.UU95_InterfaceMonitoring_Message"),
		InterfaceMonitoring_SearchParams("InterfaceConfiguration.InterfaceMonitoring_SearchParams");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public InterfaceMonitoring(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "InterfaceConfiguration.InterfaceMonitoring"));
	}

	protected InterfaceMonitoring(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject interfaceMonitoringMendixObject)
	{
		if (interfaceMonitoringMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("InterfaceConfiguration.InterfaceMonitoring", interfaceMonitoringMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a InterfaceConfiguration.InterfaceMonitoring");

		this.interfaceMonitoringMendixObject = interfaceMonitoringMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'InterfaceMonitoring.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static interfaceconfiguration.proxies.InterfaceMonitoring initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return interfaceconfiguration.proxies.InterfaceMonitoring.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static interfaceconfiguration.proxies.InterfaceMonitoring initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new interfaceconfiguration.proxies.InterfaceMonitoring(context, mendixObject);
	}

	public static interfaceconfiguration.proxies.InterfaceMonitoring load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return interfaceconfiguration.proxies.InterfaceMonitoring.initialize(context, mendixObject);
	}

	public static java.util.List<interfaceconfiguration.proxies.InterfaceMonitoring> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<interfaceconfiguration.proxies.InterfaceMonitoring> result = new java.util.ArrayList<interfaceconfiguration.proxies.InterfaceMonitoring>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//InterfaceConfiguration.InterfaceMonitoring" + xpathConstraint))
			result.add(interfaceconfiguration.proxies.InterfaceMonitoring.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of MessageDirection
	 * @param messagedirection
	 */
	public final interfaceshared.proxies.MessageDirection getMessageDirection()
	{
		return getMessageDirection(getContext());
	}

	/**
	 * @param context
	 * @return value of MessageDirection
	 */
	public final interfaceshared.proxies.MessageDirection getMessageDirection(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.MessageDirection.toString());
		if (obj == null)
			return null;

		return interfaceshared.proxies.MessageDirection.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of MessageDirection
	 * @param messagedirection
	 */
	public final void setMessageDirection(interfaceshared.proxies.MessageDirection messagedirection)
	{
		setMessageDirection(getContext(), messagedirection);
	}

	/**
	 * Set value of MessageDirection
	 * @param context
	 * @param messagedirection
	 */
	public final void setMessageDirection(com.mendix.systemwideinterfaces.core.IContext context, interfaceshared.proxies.MessageDirection messagedirection)
	{
		if (messagedirection != null)
			getMendixObject().setValue(context, MemberNames.MessageDirection.toString(), messagedirection.toString());
		else
			getMendixObject().setValue(context, MemberNames.MessageDirection.toString(), null);
	}

	/**
	 * @return value of ShowNewRequest
	 */
	public final java.lang.Boolean getShowNewRequest()
	{
		return getShowNewRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowNewRequest
	 */
	public final java.lang.Boolean getShowNewRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowNewRequest.toString());
	}

	/**
	 * Set value of ShowNewRequest
	 * @param shownewrequest
	 */
	public final void setShowNewRequest(java.lang.Boolean shownewrequest)
	{
		setShowNewRequest(getContext(), shownewrequest);
	}

	/**
	 * Set value of ShowNewRequest
	 * @param context
	 * @param shownewrequest
	 */
	public final void setShowNewRequest(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean shownewrequest)
	{
		getMendixObject().setValue(context, MemberNames.ShowNewRequest.toString(), shownewrequest);
	}

	/**
	 * @return value of ShowNewRequestConfirmation
	 */
	public final java.lang.Boolean getShowNewRequestConfirmation()
	{
		return getShowNewRequestConfirmation(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowNewRequestConfirmation
	 */
	public final java.lang.Boolean getShowNewRequestConfirmation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowNewRequestConfirmation.toString());
	}

	/**
	 * Set value of ShowNewRequestConfirmation
	 * @param shownewrequestconfirmation
	 */
	public final void setShowNewRequestConfirmation(java.lang.Boolean shownewrequestconfirmation)
	{
		setShowNewRequestConfirmation(getContext(), shownewrequestconfirmation);
	}

	/**
	 * Set value of ShowNewRequestConfirmation
	 * @param context
	 * @param shownewrequestconfirmation
	 */
	public final void setShowNewRequestConfirmation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean shownewrequestconfirmation)
	{
		getMendixObject().setValue(context, MemberNames.ShowNewRequestConfirmation.toString(), shownewrequestconfirmation);
	}

	/**
	 * @return value of ShowAddUpdateDeleteAttachments
	 */
	public final java.lang.Boolean getShowAddUpdateDeleteAttachments()
	{
		return getShowAddUpdateDeleteAttachments(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowAddUpdateDeleteAttachments
	 */
	public final java.lang.Boolean getShowAddUpdateDeleteAttachments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowAddUpdateDeleteAttachments.toString());
	}

	/**
	 * Set value of ShowAddUpdateDeleteAttachments
	 * @param showaddupdatedeleteattachments
	 */
	public final void setShowAddUpdateDeleteAttachments(java.lang.Boolean showaddupdatedeleteattachments)
	{
		setShowAddUpdateDeleteAttachments(getContext(), showaddupdatedeleteattachments);
	}

	/**
	 * Set value of ShowAddUpdateDeleteAttachments
	 * @param context
	 * @param showaddupdatedeleteattachments
	 */
	public final void setShowAddUpdateDeleteAttachments(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showaddupdatedeleteattachments)
	{
		getMendixObject().setValue(context, MemberNames.ShowAddUpdateDeleteAttachments.toString(), showaddupdatedeleteattachments);
	}

	/**
	 * @return value of ShowAddUpdateDeleteAttachmentsConfirmation
	 */
	public final java.lang.Boolean getShowAddUpdateDeleteAttachmentsConfirmation()
	{
		return getShowAddUpdateDeleteAttachmentsConfirmation(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowAddUpdateDeleteAttachmentsConfirmation
	 */
	public final java.lang.Boolean getShowAddUpdateDeleteAttachmentsConfirmation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowAddUpdateDeleteAttachmentsConfirmation.toString());
	}

	/**
	 * Set value of ShowAddUpdateDeleteAttachmentsConfirmation
	 * @param showaddupdatedeleteattachmentsconfirmation
	 */
	public final void setShowAddUpdateDeleteAttachmentsConfirmation(java.lang.Boolean showaddupdatedeleteattachmentsconfirmation)
	{
		setShowAddUpdateDeleteAttachmentsConfirmation(getContext(), showaddupdatedeleteattachmentsconfirmation);
	}

	/**
	 * Set value of ShowAddUpdateDeleteAttachmentsConfirmation
	 * @param context
	 * @param showaddupdatedeleteattachmentsconfirmation
	 */
	public final void setShowAddUpdateDeleteAttachmentsConfirmation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showaddupdatedeleteattachmentsconfirmation)
	{
		getMendixObject().setValue(context, MemberNames.ShowAddUpdateDeleteAttachmentsConfirmation.toString(), showaddupdatedeleteattachmentsconfirmation);
	}

	/**
	 * @return value of ShowAddNotes
	 */
	public final java.lang.Boolean getShowAddNotes()
	{
		return getShowAddNotes(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowAddNotes
	 */
	public final java.lang.Boolean getShowAddNotes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowAddNotes.toString());
	}

	/**
	 * Set value of ShowAddNotes
	 * @param showaddnotes
	 */
	public final void setShowAddNotes(java.lang.Boolean showaddnotes)
	{
		setShowAddNotes(getContext(), showaddnotes);
	}

	/**
	 * Set value of ShowAddNotes
	 * @param context
	 * @param showaddnotes
	 */
	public final void setShowAddNotes(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showaddnotes)
	{
		getMendixObject().setValue(context, MemberNames.ShowAddNotes.toString(), showaddnotes);
	}

	/**
	 * @return value of ShowAddNotesConfirmation
	 */
	public final java.lang.Boolean getShowAddNotesConfirmation()
	{
		return getShowAddNotesConfirmation(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowAddNotesConfirmation
	 */
	public final java.lang.Boolean getShowAddNotesConfirmation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowAddNotesConfirmation.toString());
	}

	/**
	 * Set value of ShowAddNotesConfirmation
	 * @param showaddnotesconfirmation
	 */
	public final void setShowAddNotesConfirmation(java.lang.Boolean showaddnotesconfirmation)
	{
		setShowAddNotesConfirmation(getContext(), showaddnotesconfirmation);
	}

	/**
	 * Set value of ShowAddNotesConfirmation
	 * @param context
	 * @param showaddnotesconfirmation
	 */
	public final void setShowAddNotesConfirmation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showaddnotesconfirmation)
	{
		getMendixObject().setValue(context, MemberNames.ShowAddNotesConfirmation.toString(), showaddnotesconfirmation);
	}

	/**
	 * @return value of ShowAddUpdateDeleteRelations
	 */
	public final java.lang.Boolean getShowAddUpdateDeleteRelations()
	{
		return getShowAddUpdateDeleteRelations(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowAddUpdateDeleteRelations
	 */
	public final java.lang.Boolean getShowAddUpdateDeleteRelations(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowAddUpdateDeleteRelations.toString());
	}

	/**
	 * Set value of ShowAddUpdateDeleteRelations
	 * @param showaddupdatedeleterelations
	 */
	public final void setShowAddUpdateDeleteRelations(java.lang.Boolean showaddupdatedeleterelations)
	{
		setShowAddUpdateDeleteRelations(getContext(), showaddupdatedeleterelations);
	}

	/**
	 * Set value of ShowAddUpdateDeleteRelations
	 * @param context
	 * @param showaddupdatedeleterelations
	 */
	public final void setShowAddUpdateDeleteRelations(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showaddupdatedeleterelations)
	{
		getMendixObject().setValue(context, MemberNames.ShowAddUpdateDeleteRelations.toString(), showaddupdatedeleterelations);
	}

	/**
	 * @return value of ShowAddUpdateDeleteRelationsConfirmation
	 */
	public final java.lang.Boolean getShowAddUpdateDeleteRelationsConfirmation()
	{
		return getShowAddUpdateDeleteRelationsConfirmation(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowAddUpdateDeleteRelationsConfirmation
	 */
	public final java.lang.Boolean getShowAddUpdateDeleteRelationsConfirmation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowAddUpdateDeleteRelationsConfirmation.toString());
	}

	/**
	 * Set value of ShowAddUpdateDeleteRelationsConfirmation
	 * @param showaddupdatedeleterelationsconfirmation
	 */
	public final void setShowAddUpdateDeleteRelationsConfirmation(java.lang.Boolean showaddupdatedeleterelationsconfirmation)
	{
		setShowAddUpdateDeleteRelationsConfirmation(getContext(), showaddupdatedeleterelationsconfirmation);
	}

	/**
	 * Set value of ShowAddUpdateDeleteRelationsConfirmation
	 * @param context
	 * @param showaddupdatedeleterelationsconfirmation
	 */
	public final void setShowAddUpdateDeleteRelationsConfirmation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showaddupdatedeleterelationsconfirmation)
	{
		getMendixObject().setValue(context, MemberNames.ShowAddUpdateDeleteRelationsConfirmation.toString(), showaddupdatedeleterelationsconfirmation);
	}

	/**
	 * @return value of ShowAddUpdateDeleteExternalReferences
	 */
	public final java.lang.Boolean getShowAddUpdateDeleteExternalReferences()
	{
		return getShowAddUpdateDeleteExternalReferences(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowAddUpdateDeleteExternalReferences
	 */
	public final java.lang.Boolean getShowAddUpdateDeleteExternalReferences(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowAddUpdateDeleteExternalReferences.toString());
	}

	/**
	 * Set value of ShowAddUpdateDeleteExternalReferences
	 * @param showaddupdatedeleteexternalreferences
	 */
	public final void setShowAddUpdateDeleteExternalReferences(java.lang.Boolean showaddupdatedeleteexternalreferences)
	{
		setShowAddUpdateDeleteExternalReferences(getContext(), showaddupdatedeleteexternalreferences);
	}

	/**
	 * Set value of ShowAddUpdateDeleteExternalReferences
	 * @param context
	 * @param showaddupdatedeleteexternalreferences
	 */
	public final void setShowAddUpdateDeleteExternalReferences(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showaddupdatedeleteexternalreferences)
	{
		getMendixObject().setValue(context, MemberNames.ShowAddUpdateDeleteExternalReferences.toString(), showaddupdatedeleteexternalreferences);
	}

	/**
	 * @return value of ShowAddUpdateDeleteExternalReferencesConfirmation
	 */
	public final java.lang.Boolean getShowAddUpdateDeleteExternalReferencesConfirmation()
	{
		return getShowAddUpdateDeleteExternalReferencesConfirmation(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowAddUpdateDeleteExternalReferencesConfirmation
	 */
	public final java.lang.Boolean getShowAddUpdateDeleteExternalReferencesConfirmation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowAddUpdateDeleteExternalReferencesConfirmation.toString());
	}

	/**
	 * Set value of ShowAddUpdateDeleteExternalReferencesConfirmation
	 * @param showaddupdatedeleteexternalreferencesconfirmation
	 */
	public final void setShowAddUpdateDeleteExternalReferencesConfirmation(java.lang.Boolean showaddupdatedeleteexternalreferencesconfirmation)
	{
		setShowAddUpdateDeleteExternalReferencesConfirmation(getContext(), showaddupdatedeleteexternalreferencesconfirmation);
	}

	/**
	 * Set value of ShowAddUpdateDeleteExternalReferencesConfirmation
	 * @param context
	 * @param showaddupdatedeleteexternalreferencesconfirmation
	 */
	public final void setShowAddUpdateDeleteExternalReferencesConfirmation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showaddupdatedeleteexternalreferencesconfirmation)
	{
		getMendixObject().setValue(context, MemberNames.ShowAddUpdateDeleteExternalReferencesConfirmation.toString(), showaddupdatedeleteexternalreferencesconfirmation);
	}

	/**
	 * @return value of ShowAddUpdateDeleteAffectedCIs
	 */
	public final java.lang.Boolean getShowAddUpdateDeleteAffectedCIs()
	{
		return getShowAddUpdateDeleteAffectedCIs(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowAddUpdateDeleteAffectedCIs
	 */
	public final java.lang.Boolean getShowAddUpdateDeleteAffectedCIs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowAddUpdateDeleteAffectedCIs.toString());
	}

	/**
	 * Set value of ShowAddUpdateDeleteAffectedCIs
	 * @param showaddupdatedeleteaffectedcis
	 */
	public final void setShowAddUpdateDeleteAffectedCIs(java.lang.Boolean showaddupdatedeleteaffectedcis)
	{
		setShowAddUpdateDeleteAffectedCIs(getContext(), showaddupdatedeleteaffectedcis);
	}

	/**
	 * Set value of ShowAddUpdateDeleteAffectedCIs
	 * @param context
	 * @param showaddupdatedeleteaffectedcis
	 */
	public final void setShowAddUpdateDeleteAffectedCIs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showaddupdatedeleteaffectedcis)
	{
		getMendixObject().setValue(context, MemberNames.ShowAddUpdateDeleteAffectedCIs.toString(), showaddupdatedeleteaffectedcis);
	}

	/**
	 * @return value of ShowAddUpdateDeleteAffectedCIsConfirmation
	 */
	public final java.lang.Boolean getShowAddUpdateDeleteAffectedCIsConfirmation()
	{
		return getShowAddUpdateDeleteAffectedCIsConfirmation(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowAddUpdateDeleteAffectedCIsConfirmation
	 */
	public final java.lang.Boolean getShowAddUpdateDeleteAffectedCIsConfirmation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowAddUpdateDeleteAffectedCIsConfirmation.toString());
	}

	/**
	 * Set value of ShowAddUpdateDeleteAffectedCIsConfirmation
	 * @param showaddupdatedeleteaffectedcisconfirmation
	 */
	public final void setShowAddUpdateDeleteAffectedCIsConfirmation(java.lang.Boolean showaddupdatedeleteaffectedcisconfirmation)
	{
		setShowAddUpdateDeleteAffectedCIsConfirmation(getContext(), showaddupdatedeleteaffectedcisconfirmation);
	}

	/**
	 * Set value of ShowAddUpdateDeleteAffectedCIsConfirmation
	 * @param context
	 * @param showaddupdatedeleteaffectedcisconfirmation
	 */
	public final void setShowAddUpdateDeleteAffectedCIsConfirmation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showaddupdatedeleteaffectedcisconfirmation)
	{
		getMendixObject().setValue(context, MemberNames.ShowAddUpdateDeleteAffectedCIsConfirmation.toString(), showaddupdatedeleteaffectedcisconfirmation);
	}

	/**
	 * @return value of ShowContractAspectUpdate
	 */
	public final java.lang.Boolean getShowContractAspectUpdate()
	{
		return getShowContractAspectUpdate(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowContractAspectUpdate
	 */
	public final java.lang.Boolean getShowContractAspectUpdate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowContractAspectUpdate.toString());
	}

	/**
	 * Set value of ShowContractAspectUpdate
	 * @param showcontractaspectupdate
	 */
	public final void setShowContractAspectUpdate(java.lang.Boolean showcontractaspectupdate)
	{
		setShowContractAspectUpdate(getContext(), showcontractaspectupdate);
	}

	/**
	 * Set value of ShowContractAspectUpdate
	 * @param context
	 * @param showcontractaspectupdate
	 */
	public final void setShowContractAspectUpdate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showcontractaspectupdate)
	{
		getMendixObject().setValue(context, MemberNames.ShowContractAspectUpdate.toString(), showcontractaspectupdate);
	}

	/**
	 * @return value of ShowContractAspectUpdateConfirmation
	 */
	public final java.lang.Boolean getShowContractAspectUpdateConfirmation()
	{
		return getShowContractAspectUpdateConfirmation(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowContractAspectUpdateConfirmation
	 */
	public final java.lang.Boolean getShowContractAspectUpdateConfirmation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowContractAspectUpdateConfirmation.toString());
	}

	/**
	 * Set value of ShowContractAspectUpdateConfirmation
	 * @param showcontractaspectupdateconfirmation
	 */
	public final void setShowContractAspectUpdateConfirmation(java.lang.Boolean showcontractaspectupdateconfirmation)
	{
		setShowContractAspectUpdateConfirmation(getContext(), showcontractaspectupdateconfirmation);
	}

	/**
	 * Set value of ShowContractAspectUpdateConfirmation
	 * @param context
	 * @param showcontractaspectupdateconfirmation
	 */
	public final void setShowContractAspectUpdateConfirmation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showcontractaspectupdateconfirmation)
	{
		getMendixObject().setValue(context, MemberNames.ShowContractAspectUpdateConfirmation.toString(), showcontractaspectupdateconfirmation);
	}

	/**
	 * @return value of ShowRequestUpdate
	 */
	public final java.lang.Boolean getShowRequestUpdate()
	{
		return getShowRequestUpdate(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowRequestUpdate
	 */
	public final java.lang.Boolean getShowRequestUpdate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowRequestUpdate.toString());
	}

	/**
	 * Set value of ShowRequestUpdate
	 * @param showrequestupdate
	 */
	public final void setShowRequestUpdate(java.lang.Boolean showrequestupdate)
	{
		setShowRequestUpdate(getContext(), showrequestupdate);
	}

	/**
	 * Set value of ShowRequestUpdate
	 * @param context
	 * @param showrequestupdate
	 */
	public final void setShowRequestUpdate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showrequestupdate)
	{
		getMendixObject().setValue(context, MemberNames.ShowRequestUpdate.toString(), showrequestupdate);
	}

	/**
	 * @return value of ShowRequestUpdateConfirmation
	 */
	public final java.lang.Boolean getShowRequestUpdateConfirmation()
	{
		return getShowRequestUpdateConfirmation(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowRequestUpdateConfirmation
	 */
	public final java.lang.Boolean getShowRequestUpdateConfirmation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowRequestUpdateConfirmation.toString());
	}

	/**
	 * Set value of ShowRequestUpdateConfirmation
	 * @param showrequestupdateconfirmation
	 */
	public final void setShowRequestUpdateConfirmation(java.lang.Boolean showrequestupdateconfirmation)
	{
		setShowRequestUpdateConfirmation(getContext(), showrequestupdateconfirmation);
	}

	/**
	 * Set value of ShowRequestUpdateConfirmation
	 * @param context
	 * @param showrequestupdateconfirmation
	 */
	public final void setShowRequestUpdateConfirmation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showrequestupdateconfirmation)
	{
		getMendixObject().setValue(context, MemberNames.ShowRequestUpdateConfirmation.toString(), showrequestupdateconfirmation);
	}

	/**
	 * @return value of ShowHeartBeat
	 */
	public final java.lang.Boolean getShowHeartBeat()
	{
		return getShowHeartBeat(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowHeartBeat
	 */
	public final java.lang.Boolean getShowHeartBeat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowHeartBeat.toString());
	}

	/**
	 * Set value of ShowHeartBeat
	 * @param showheartbeat
	 */
	public final void setShowHeartBeat(java.lang.Boolean showheartbeat)
	{
		setShowHeartBeat(getContext(), showheartbeat);
	}

	/**
	 * Set value of ShowHeartBeat
	 * @param context
	 * @param showheartbeat
	 */
	public final void setShowHeartBeat(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showheartbeat)
	{
		getMendixObject().setValue(context, MemberNames.ShowHeartBeat.toString(), showheartbeat);
	}

	/**
	 * @return value of ShowHeartBeatConfirmation
	 */
	public final java.lang.Boolean getShowHeartBeatConfirmation()
	{
		return getShowHeartBeatConfirmation(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowHeartBeatConfirmation
	 */
	public final java.lang.Boolean getShowHeartBeatConfirmation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowHeartBeatConfirmation.toString());
	}

	/**
	 * Set value of ShowHeartBeatConfirmation
	 * @param showheartbeatconfirmation
	 */
	public final void setShowHeartBeatConfirmation(java.lang.Boolean showheartbeatconfirmation)
	{
		setShowHeartBeatConfirmation(getContext(), showheartbeatconfirmation);
	}

	/**
	 * Set value of ShowHeartBeatConfirmation
	 * @param context
	 * @param showheartbeatconfirmation
	 */
	public final void setShowHeartBeatConfirmation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showheartbeatconfirmation)
	{
		getMendixObject().setValue(context, MemberNames.ShowHeartBeatConfirmation.toString(), showheartbeatconfirmation);
	}

	/**
	 * @return value of ShowLDAPImport
	 */
	public final java.lang.Boolean getShowLDAPImport()
	{
		return getShowLDAPImport(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowLDAPImport
	 */
	public final java.lang.Boolean getShowLDAPImport(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowLDAPImport.toString());
	}

	/**
	 * Set value of ShowLDAPImport
	 * @param showldapimport
	 */
	public final void setShowLDAPImport(java.lang.Boolean showldapimport)
	{
		setShowLDAPImport(getContext(), showldapimport);
	}

	/**
	 * Set value of ShowLDAPImport
	 * @param context
	 * @param showldapimport
	 */
	public final void setShowLDAPImport(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showldapimport)
	{
		getMendixObject().setValue(context, MemberNames.ShowLDAPImport.toString(), showldapimport);
	}

	/**
	 * @return value of FromDate
	 */
	public final java.util.Date getFromDate()
	{
		return getFromDate(getContext());
	}

	/**
	 * @param context
	 * @return value of FromDate
	 */
	public final java.util.Date getFromDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.FromDate.toString());
	}

	/**
	 * Set value of FromDate
	 * @param fromdate
	 */
	public final void setFromDate(java.util.Date fromdate)
	{
		setFromDate(getContext(), fromdate);
	}

	/**
	 * Set value of FromDate
	 * @param context
	 * @param fromdate
	 */
	public final void setFromDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date fromdate)
	{
		getMendixObject().setValue(context, MemberNames.FromDate.toString(), fromdate);
	}

	/**
	 * @return value of ToDate
	 */
	public final java.util.Date getToDate()
	{
		return getToDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ToDate
	 */
	public final java.util.Date getToDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ToDate.toString());
	}

	/**
	 * Set value of ToDate
	 * @param todate
	 */
	public final void setToDate(java.util.Date todate)
	{
		setToDate(getContext(), todate);
	}

	/**
	 * Set value of ToDate
	 * @param context
	 * @param todate
	 */
	public final void setToDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date todate)
	{
		getMendixObject().setValue(context, MemberNames.ToDate.toString(), todate);
	}

	/**
	 * @return value of ShowCritical
	 */
	public final java.lang.Boolean getShowCritical()
	{
		return getShowCritical(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowCritical
	 */
	public final java.lang.Boolean getShowCritical(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowCritical.toString());
	}

	/**
	 * Set value of ShowCritical
	 * @param showcritical
	 */
	public final void setShowCritical(java.lang.Boolean showcritical)
	{
		setShowCritical(getContext(), showcritical);
	}

	/**
	 * Set value of ShowCritical
	 * @param context
	 * @param showcritical
	 */
	public final void setShowCritical(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showcritical)
	{
		getMendixObject().setValue(context, MemberNames.ShowCritical.toString(), showcritical);
	}

	/**
	 * @return value of ShowError
	 */
	public final java.lang.Boolean getShowError()
	{
		return getShowError(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowError
	 */
	public final java.lang.Boolean getShowError(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowError.toString());
	}

	/**
	 * Set value of ShowError
	 * @param showerror
	 */
	public final void setShowError(java.lang.Boolean showerror)
	{
		setShowError(getContext(), showerror);
	}

	/**
	 * Set value of ShowError
	 * @param context
	 * @param showerror
	 */
	public final void setShowError(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showerror)
	{
		getMendixObject().setValue(context, MemberNames.ShowError.toString(), showerror);
	}

	/**
	 * @return value of ShowWarning
	 */
	public final java.lang.Boolean getShowWarning()
	{
		return getShowWarning(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowWarning
	 */
	public final java.lang.Boolean getShowWarning(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowWarning.toString());
	}

	/**
	 * Set value of ShowWarning
	 * @param showwarning
	 */
	public final void setShowWarning(java.lang.Boolean showwarning)
	{
		setShowWarning(getContext(), showwarning);
	}

	/**
	 * Set value of ShowWarning
	 * @param context
	 * @param showwarning
	 */
	public final void setShowWarning(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showwarning)
	{
		getMendixObject().setValue(context, MemberNames.ShowWarning.toString(), showwarning);
	}

	/**
	 * @return value of ShowInfo
	 */
	public final java.lang.Boolean getShowInfo()
	{
		return getShowInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowInfo
	 */
	public final java.lang.Boolean getShowInfo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowInfo.toString());
	}

	/**
	 * Set value of ShowInfo
	 * @param showinfo
	 */
	public final void setShowInfo(java.lang.Boolean showinfo)
	{
		setShowInfo(getContext(), showinfo);
	}

	/**
	 * Set value of ShowInfo
	 * @param context
	 * @param showinfo
	 */
	public final void setShowInfo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showinfo)
	{
		getMendixObject().setValue(context, MemberNames.ShowInfo.toString(), showinfo);
	}

	/**
	 * @return value of ShowDebug
	 */
	public final java.lang.Boolean getShowDebug()
	{
		return getShowDebug(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowDebug
	 */
	public final java.lang.Boolean getShowDebug(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowDebug.toString());
	}

	/**
	 * Set value of ShowDebug
	 * @param showdebug
	 */
	public final void setShowDebug(java.lang.Boolean showdebug)
	{
		setShowDebug(getContext(), showdebug);
	}

	/**
	 * Set value of ShowDebug
	 * @param context
	 * @param showdebug
	 */
	public final void setShowDebug(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showdebug)
	{
		getMendixObject().setValue(context, MemberNames.ShowDebug.toString(), showdebug);
	}

	/**
	 * @return value of ShowTrace
	 */
	public final java.lang.Boolean getShowTrace()
	{
		return getShowTrace(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowTrace
	 */
	public final java.lang.Boolean getShowTrace(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowTrace.toString());
	}

	/**
	 * Set value of ShowTrace
	 * @param showtrace
	 */
	public final void setShowTrace(java.lang.Boolean showtrace)
	{
		setShowTrace(getContext(), showtrace);
	}

	/**
	 * Set value of ShowTrace
	 * @param context
	 * @param showtrace
	 */
	public final void setShowTrace(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showtrace)
	{
		getMendixObject().setValue(context, MemberNames.ShowTrace.toString(), showtrace);
	}

	/**
	 * @return value of ShowMessagesWithoutInterface
	 */
	public final java.lang.Boolean getShowMessagesWithoutInterface()
	{
		return getShowMessagesWithoutInterface(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowMessagesWithoutInterface
	 */
	public final java.lang.Boolean getShowMessagesWithoutInterface(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowMessagesWithoutInterface.toString());
	}

	/**
	 * Set value of ShowMessagesWithoutInterface
	 * @param showmessageswithoutinterface
	 */
	public final void setShowMessagesWithoutInterface(java.lang.Boolean showmessageswithoutinterface)
	{
		setShowMessagesWithoutInterface(getContext(), showmessageswithoutinterface);
	}

	/**
	 * Set value of ShowMessagesWithoutInterface
	 * @param context
	 * @param showmessageswithoutinterface
	 */
	public final void setShowMessagesWithoutInterface(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showmessageswithoutinterface)
	{
		getMendixObject().setValue(context, MemberNames.ShowMessagesWithoutInterface.toString(), showmessageswithoutinterface);
	}

	/**
	 * @return value of ShowMessagesWithInterface
	 */
	public final java.lang.Boolean getShowMessagesWithInterface()
	{
		return getShowMessagesWithInterface(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowMessagesWithInterface
	 */
	public final java.lang.Boolean getShowMessagesWithInterface(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowMessagesWithInterface.toString());
	}

	/**
	 * Set value of ShowMessagesWithInterface
	 * @param showmessageswithinterface
	 */
	public final void setShowMessagesWithInterface(java.lang.Boolean showmessageswithinterface)
	{
		setShowMessagesWithInterface(getContext(), showmessageswithinterface);
	}

	/**
	 * Set value of ShowMessagesWithInterface
	 * @param context
	 * @param showmessageswithinterface
	 */
	public final void setShowMessagesWithInterface(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showmessageswithinterface)
	{
		getMendixObject().setValue(context, MemberNames.ShowMessagesWithInterface.toString(), showmessageswithinterface);
	}

	/**
	 * Set value of MessagesSorting
	 * @param messagessorting
	 */
	public final interfaceconfiguration.proxies.MessageSorting getMessagesSorting()
	{
		return getMessagesSorting(getContext());
	}

	/**
	 * @param context
	 * @return value of MessagesSorting
	 */
	public final interfaceconfiguration.proxies.MessageSorting getMessagesSorting(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.MessagesSorting.toString());
		if (obj == null)
			return null;

		return interfaceconfiguration.proxies.MessageSorting.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of MessagesSorting
	 * @param messagessorting
	 */
	public final void setMessagesSorting(interfaceconfiguration.proxies.MessageSorting messagessorting)
	{
		setMessagesSorting(getContext(), messagessorting);
	}

	/**
	 * Set value of MessagesSorting
	 * @param context
	 * @param messagessorting
	 */
	public final void setMessagesSorting(com.mendix.systemwideinterfaces.core.IContext context, interfaceconfiguration.proxies.MessageSorting messagessorting)
	{
		if (messagessorting != null)
			getMendixObject().setValue(context, MemberNames.MessagesSorting.toString(), messagessorting.toString());
		else
			getMendixObject().setValue(context, MemberNames.MessagesSorting.toString(), null);
	}

	/**
	 * Set value of MessagesSortOrder
	 * @param messagessortorder
	 */
	public final interfaceconfiguration.proxies.SortOrder getMessagesSortOrder()
	{
		return getMessagesSortOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of MessagesSortOrder
	 */
	public final interfaceconfiguration.proxies.SortOrder getMessagesSortOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.MessagesSortOrder.toString());
		if (obj == null)
			return null;

		return interfaceconfiguration.proxies.SortOrder.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of MessagesSortOrder
	 * @param messagessortorder
	 */
	public final void setMessagesSortOrder(interfaceconfiguration.proxies.SortOrder messagessortorder)
	{
		setMessagesSortOrder(getContext(), messagessortorder);
	}

	/**
	 * Set value of MessagesSortOrder
	 * @param context
	 * @param messagessortorder
	 */
	public final void setMessagesSortOrder(com.mendix.systemwideinterfaces.core.IContext context, interfaceconfiguration.proxies.SortOrder messagessortorder)
	{
		if (messagessortorder != null)
			getMendixObject().setValue(context, MemberNames.MessagesSortOrder.toString(), messagessortorder.toString());
		else
			getMendixObject().setValue(context, MemberNames.MessagesSortOrder.toString(), null);
	}

	/**
	 * Set value of ProcessingLogsSorting
	 * @param processinglogssorting
	 */
	public final interfaceconfiguration.proxies.ErrorSorting getProcessingLogsSorting()
	{
		return getProcessingLogsSorting(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessingLogsSorting
	 */
	public final interfaceconfiguration.proxies.ErrorSorting getProcessingLogsSorting(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ProcessingLogsSorting.toString());
		if (obj == null)
			return null;

		return interfaceconfiguration.proxies.ErrorSorting.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ProcessingLogsSorting
	 * @param processinglogssorting
	 */
	public final void setProcessingLogsSorting(interfaceconfiguration.proxies.ErrorSorting processinglogssorting)
	{
		setProcessingLogsSorting(getContext(), processinglogssorting);
	}

	/**
	 * Set value of ProcessingLogsSorting
	 * @param context
	 * @param processinglogssorting
	 */
	public final void setProcessingLogsSorting(com.mendix.systemwideinterfaces.core.IContext context, interfaceconfiguration.proxies.ErrorSorting processinglogssorting)
	{
		if (processinglogssorting != null)
			getMendixObject().setValue(context, MemberNames.ProcessingLogsSorting.toString(), processinglogssorting.toString());
		else
			getMendixObject().setValue(context, MemberNames.ProcessingLogsSorting.toString(), null);
	}

	/**
	 * Set value of ProcessingLogsSortOrder
	 * @param processinglogssortorder
	 */
	public final interfaceconfiguration.proxies.SortOrder getProcessingLogsSortOrder()
	{
		return getProcessingLogsSortOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessingLogsSortOrder
	 */
	public final interfaceconfiguration.proxies.SortOrder getProcessingLogsSortOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ProcessingLogsSortOrder.toString());
		if (obj == null)
			return null;

		return interfaceconfiguration.proxies.SortOrder.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ProcessingLogsSortOrder
	 * @param processinglogssortorder
	 */
	public final void setProcessingLogsSortOrder(interfaceconfiguration.proxies.SortOrder processinglogssortorder)
	{
		setProcessingLogsSortOrder(getContext(), processinglogssortorder);
	}

	/**
	 * Set value of ProcessingLogsSortOrder
	 * @param context
	 * @param processinglogssortorder
	 */
	public final void setProcessingLogsSortOrder(com.mendix.systemwideinterfaces.core.IContext context, interfaceconfiguration.proxies.SortOrder processinglogssortorder)
	{
		if (processinglogssortorder != null)
			getMendixObject().setValue(context, MemberNames.ProcessingLogsSortOrder.toString(), processinglogssortorder.toString());
		else
			getMendixObject().setValue(context, MemberNames.ProcessingLogsSortOrder.toString(), null);
	}

	/**
	 * @return value of ShowNotViewed
	 */
	public final java.lang.Boolean getShowNotViewed()
	{
		return getShowNotViewed(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowNotViewed
	 */
	public final java.lang.Boolean getShowNotViewed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowNotViewed.toString());
	}

	/**
	 * Set value of ShowNotViewed
	 * @param shownotviewed
	 */
	public final void setShowNotViewed(java.lang.Boolean shownotviewed)
	{
		setShowNotViewed(getContext(), shownotviewed);
	}

	/**
	 * Set value of ShowNotViewed
	 * @param context
	 * @param shownotviewed
	 */
	public final void setShowNotViewed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean shownotviewed)
	{
		getMendixObject().setValue(context, MemberNames.ShowNotViewed.toString(), shownotviewed);
	}

	/**
	 * @return value of ShowViewed
	 */
	public final java.lang.Boolean getShowViewed()
	{
		return getShowViewed(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowViewed
	 */
	public final java.lang.Boolean getShowViewed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowViewed.toString());
	}

	/**
	 * Set value of ShowViewed
	 * @param showviewed
	 */
	public final void setShowViewed(java.lang.Boolean showviewed)
	{
		setShowViewed(getContext(), showviewed);
	}

	/**
	 * Set value of ShowViewed
	 * @param context
	 * @param showviewed
	 */
	public final void setShowViewed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showviewed)
	{
		getMendixObject().setValue(context, MemberNames.ShowViewed.toString(), showviewed);
	}

	/**
	 * @return value of ShowSolved
	 */
	public final java.lang.Boolean getShowSolved()
	{
		return getShowSolved(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowSolved
	 */
	public final java.lang.Boolean getShowSolved(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowSolved.toString());
	}

	/**
	 * Set value of ShowSolved
	 * @param showsolved
	 */
	public final void setShowSolved(java.lang.Boolean showsolved)
	{
		setShowSolved(getContext(), showsolved);
	}

	/**
	 * Set value of ShowSolved
	 * @param context
	 * @param showsolved
	 */
	public final void setShowSolved(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showsolved)
	{
		getMendixObject().setValue(context, MemberNames.ShowSolved.toString(), showsolved);
	}

	/**
	 * @return value of ShowIgnored
	 */
	public final java.lang.Boolean getShowIgnored()
	{
		return getShowIgnored(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowIgnored
	 */
	public final java.lang.Boolean getShowIgnored(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowIgnored.toString());
	}

	/**
	 * Set value of ShowIgnored
	 * @param showignored
	 */
	public final void setShowIgnored(java.lang.Boolean showignored)
	{
		setShowIgnored(getContext(), showignored);
	}

	/**
	 * Set value of ShowIgnored
	 * @param context
	 * @param showignored
	 */
	public final void setShowIgnored(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showignored)
	{
		getMendixObject().setValue(context, MemberNames.ShowIgnored.toString(), showignored);
	}

	/**
	 * @return value of MessagesChunkStart
	 */
	public final java.lang.Integer getMessagesChunkStart()
	{
		return getMessagesChunkStart(getContext());
	}

	/**
	 * @param context
	 * @return value of MessagesChunkStart
	 */
	public final java.lang.Integer getMessagesChunkStart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MessagesChunkStart.toString());
	}

	/**
	 * Set value of MessagesChunkStart
	 * @param messageschunkstart
	 */
	public final void setMessagesChunkStart(java.lang.Integer messageschunkstart)
	{
		setMessagesChunkStart(getContext(), messageschunkstart);
	}

	/**
	 * Set value of MessagesChunkStart
	 * @param context
	 * @param messageschunkstart
	 */
	public final void setMessagesChunkStart(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer messageschunkstart)
	{
		getMendixObject().setValue(context, MemberNames.MessagesChunkStart.toString(), messageschunkstart);
	}

	/**
	 * @return value of MessagesChunkStartShown
	 */
	public final java.lang.Integer getMessagesChunkStartShown()
	{
		return getMessagesChunkStartShown(getContext());
	}

	/**
	 * @param context
	 * @return value of MessagesChunkStartShown
	 */
	public final java.lang.Integer getMessagesChunkStartShown(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MessagesChunkStartShown.toString());
	}

	/**
	 * Set value of MessagesChunkStartShown
	 * @param messageschunkstartshown
	 */
	public final void setMessagesChunkStartShown(java.lang.Integer messageschunkstartshown)
	{
		setMessagesChunkStartShown(getContext(), messageschunkstartshown);
	}

	/**
	 * Set value of MessagesChunkStartShown
	 * @param context
	 * @param messageschunkstartshown
	 */
	public final void setMessagesChunkStartShown(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer messageschunkstartshown)
	{
		getMendixObject().setValue(context, MemberNames.MessagesChunkStartShown.toString(), messageschunkstartshown);
	}

	/**
	 * @return value of MessagesChunkEnd
	 */
	public final java.lang.Integer getMessagesChunkEnd()
	{
		return getMessagesChunkEnd(getContext());
	}

	/**
	 * @param context
	 * @return value of MessagesChunkEnd
	 */
	public final java.lang.Integer getMessagesChunkEnd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MessagesChunkEnd.toString());
	}

	/**
	 * Set value of MessagesChunkEnd
	 * @param messageschunkend
	 */
	public final void setMessagesChunkEnd(java.lang.Integer messageschunkend)
	{
		setMessagesChunkEnd(getContext(), messageschunkend);
	}

	/**
	 * Set value of MessagesChunkEnd
	 * @param context
	 * @param messageschunkend
	 */
	public final void setMessagesChunkEnd(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer messageschunkend)
	{
		getMendixObject().setValue(context, MemberNames.MessagesChunkEnd.toString(), messageschunkend);
	}

	/**
	 * @return value of MessagesTotal
	 */
	public final java.lang.Integer getMessagesTotal()
	{
		return getMessagesTotal(getContext());
	}

	/**
	 * @param context
	 * @return value of MessagesTotal
	 */
	public final java.lang.Integer getMessagesTotal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MessagesTotal.toString());
	}

	/**
	 * Set value of MessagesTotal
	 * @param messagestotal
	 */
	public final void setMessagesTotal(java.lang.Integer messagestotal)
	{
		setMessagesTotal(getContext(), messagestotal);
	}

	/**
	 * Set value of MessagesTotal
	 * @param context
	 * @param messagestotal
	 */
	public final void setMessagesTotal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer messagestotal)
	{
		getMendixObject().setValue(context, MemberNames.MessagesTotal.toString(), messagestotal);
	}

	/**
	 * @return value of MessagesFirstChunk
	 */
	public final java.lang.Boolean getMessagesFirstChunk()
	{
		return getMessagesFirstChunk(getContext());
	}

	/**
	 * @param context
	 * @return value of MessagesFirstChunk
	 */
	public final java.lang.Boolean getMessagesFirstChunk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MessagesFirstChunk.toString());
	}

	/**
	 * Set value of MessagesFirstChunk
	 * @param messagesfirstchunk
	 */
	public final void setMessagesFirstChunk(java.lang.Boolean messagesfirstchunk)
	{
		setMessagesFirstChunk(getContext(), messagesfirstchunk);
	}

	/**
	 * Set value of MessagesFirstChunk
	 * @param context
	 * @param messagesfirstchunk
	 */
	public final void setMessagesFirstChunk(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean messagesfirstchunk)
	{
		getMendixObject().setValue(context, MemberNames.MessagesFirstChunk.toString(), messagesfirstchunk);
	}

	/**
	 * @return value of MessagesPreviousChunk
	 */
	public final java.lang.Boolean getMessagesPreviousChunk()
	{
		return getMessagesPreviousChunk(getContext());
	}

	/**
	 * @param context
	 * @return value of MessagesPreviousChunk
	 */
	public final java.lang.Boolean getMessagesPreviousChunk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MessagesPreviousChunk.toString());
	}

	/**
	 * Set value of MessagesPreviousChunk
	 * @param messagespreviouschunk
	 */
	public final void setMessagesPreviousChunk(java.lang.Boolean messagespreviouschunk)
	{
		setMessagesPreviousChunk(getContext(), messagespreviouschunk);
	}

	/**
	 * Set value of MessagesPreviousChunk
	 * @param context
	 * @param messagespreviouschunk
	 */
	public final void setMessagesPreviousChunk(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean messagespreviouschunk)
	{
		getMendixObject().setValue(context, MemberNames.MessagesPreviousChunk.toString(), messagespreviouschunk);
	}

	/**
	 * @return value of MessagesNextChunk
	 */
	public final java.lang.Boolean getMessagesNextChunk()
	{
		return getMessagesNextChunk(getContext());
	}

	/**
	 * @param context
	 * @return value of MessagesNextChunk
	 */
	public final java.lang.Boolean getMessagesNextChunk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MessagesNextChunk.toString());
	}

	/**
	 * Set value of MessagesNextChunk
	 * @param messagesnextchunk
	 */
	public final void setMessagesNextChunk(java.lang.Boolean messagesnextchunk)
	{
		setMessagesNextChunk(getContext(), messagesnextchunk);
	}

	/**
	 * Set value of MessagesNextChunk
	 * @param context
	 * @param messagesnextchunk
	 */
	public final void setMessagesNextChunk(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean messagesnextchunk)
	{
		getMendixObject().setValue(context, MemberNames.MessagesNextChunk.toString(), messagesnextchunk);
	}

	/**
	 * @return value of MessagesLastChunk
	 */
	public final java.lang.Boolean getMessagesLastChunk()
	{
		return getMessagesLastChunk(getContext());
	}

	/**
	 * @param context
	 * @return value of MessagesLastChunk
	 */
	public final java.lang.Boolean getMessagesLastChunk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MessagesLastChunk.toString());
	}

	/**
	 * Set value of MessagesLastChunk
	 * @param messageslastchunk
	 */
	public final void setMessagesLastChunk(java.lang.Boolean messageslastchunk)
	{
		setMessagesLastChunk(getContext(), messageslastchunk);
	}

	/**
	 * Set value of MessagesLastChunk
	 * @param context
	 * @param messageslastchunk
	 */
	public final void setMessagesLastChunk(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean messageslastchunk)
	{
		getMendixObject().setValue(context, MemberNames.MessagesLastChunk.toString(), messageslastchunk);
	}

	/**
	 * @return value of MessagesIsFirstChunk
	 */
	public final java.lang.Boolean getMessagesIsFirstChunk()
	{
		return getMessagesIsFirstChunk(getContext());
	}

	/**
	 * @param context
	 * @return value of MessagesIsFirstChunk
	 */
	public final java.lang.Boolean getMessagesIsFirstChunk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MessagesIsFirstChunk.toString());
	}

	/**
	 * Set value of MessagesIsFirstChunk
	 * @param messagesisfirstchunk
	 */
	public final void setMessagesIsFirstChunk(java.lang.Boolean messagesisfirstchunk)
	{
		setMessagesIsFirstChunk(getContext(), messagesisfirstchunk);
	}

	/**
	 * Set value of MessagesIsFirstChunk
	 * @param context
	 * @param messagesisfirstchunk
	 */
	public final void setMessagesIsFirstChunk(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean messagesisfirstchunk)
	{
		getMendixObject().setValue(context, MemberNames.MessagesIsFirstChunk.toString(), messagesisfirstchunk);
	}

	/**
	 * @return value of MessagesIsLastChunk
	 */
	public final java.lang.Boolean getMessagesIsLastChunk()
	{
		return getMessagesIsLastChunk(getContext());
	}

	/**
	 * @param context
	 * @return value of MessagesIsLastChunk
	 */
	public final java.lang.Boolean getMessagesIsLastChunk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MessagesIsLastChunk.toString());
	}

	/**
	 * Set value of MessagesIsLastChunk
	 * @param messagesislastchunk
	 */
	public final void setMessagesIsLastChunk(java.lang.Boolean messagesislastchunk)
	{
		setMessagesIsLastChunk(getContext(), messagesislastchunk);
	}

	/**
	 * Set value of MessagesIsLastChunk
	 * @param context
	 * @param messagesislastchunk
	 */
	public final void setMessagesIsLastChunk(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean messagesislastchunk)
	{
		getMendixObject().setValue(context, MemberNames.MessagesIsLastChunk.toString(), messagesislastchunk);
	}

	/**
	 * @return value of ProcessingLogsChunkStart
	 */
	public final java.lang.Integer getProcessingLogsChunkStart()
	{
		return getProcessingLogsChunkStart(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessingLogsChunkStart
	 */
	public final java.lang.Integer getProcessingLogsChunkStart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ProcessingLogsChunkStart.toString());
	}

	/**
	 * Set value of ProcessingLogsChunkStart
	 * @param processinglogschunkstart
	 */
	public final void setProcessingLogsChunkStart(java.lang.Integer processinglogschunkstart)
	{
		setProcessingLogsChunkStart(getContext(), processinglogschunkstart);
	}

	/**
	 * Set value of ProcessingLogsChunkStart
	 * @param context
	 * @param processinglogschunkstart
	 */
	public final void setProcessingLogsChunkStart(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer processinglogschunkstart)
	{
		getMendixObject().setValue(context, MemberNames.ProcessingLogsChunkStart.toString(), processinglogschunkstart);
	}

	/**
	 * @return value of ProcessingLogsChunkStartShown
	 */
	public final java.lang.Integer getProcessingLogsChunkStartShown()
	{
		return getProcessingLogsChunkStartShown(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessingLogsChunkStartShown
	 */
	public final java.lang.Integer getProcessingLogsChunkStartShown(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ProcessingLogsChunkStartShown.toString());
	}

	/**
	 * Set value of ProcessingLogsChunkStartShown
	 * @param processinglogschunkstartshown
	 */
	public final void setProcessingLogsChunkStartShown(java.lang.Integer processinglogschunkstartshown)
	{
		setProcessingLogsChunkStartShown(getContext(), processinglogschunkstartshown);
	}

	/**
	 * Set value of ProcessingLogsChunkStartShown
	 * @param context
	 * @param processinglogschunkstartshown
	 */
	public final void setProcessingLogsChunkStartShown(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer processinglogschunkstartshown)
	{
		getMendixObject().setValue(context, MemberNames.ProcessingLogsChunkStartShown.toString(), processinglogschunkstartshown);
	}

	/**
	 * @return value of ProcessingLogsChunkEnd
	 */
	public final java.lang.Integer getProcessingLogsChunkEnd()
	{
		return getProcessingLogsChunkEnd(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessingLogsChunkEnd
	 */
	public final java.lang.Integer getProcessingLogsChunkEnd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ProcessingLogsChunkEnd.toString());
	}

	/**
	 * Set value of ProcessingLogsChunkEnd
	 * @param processinglogschunkend
	 */
	public final void setProcessingLogsChunkEnd(java.lang.Integer processinglogschunkend)
	{
		setProcessingLogsChunkEnd(getContext(), processinglogschunkend);
	}

	/**
	 * Set value of ProcessingLogsChunkEnd
	 * @param context
	 * @param processinglogschunkend
	 */
	public final void setProcessingLogsChunkEnd(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer processinglogschunkend)
	{
		getMendixObject().setValue(context, MemberNames.ProcessingLogsChunkEnd.toString(), processinglogschunkend);
	}

	/**
	 * @return value of ProcessingLogsTotal
	 */
	public final java.lang.Integer getProcessingLogsTotal()
	{
		return getProcessingLogsTotal(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessingLogsTotal
	 */
	public final java.lang.Integer getProcessingLogsTotal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ProcessingLogsTotal.toString());
	}

	/**
	 * Set value of ProcessingLogsTotal
	 * @param processinglogstotal
	 */
	public final void setProcessingLogsTotal(java.lang.Integer processinglogstotal)
	{
		setProcessingLogsTotal(getContext(), processinglogstotal);
	}

	/**
	 * Set value of ProcessingLogsTotal
	 * @param context
	 * @param processinglogstotal
	 */
	public final void setProcessingLogsTotal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer processinglogstotal)
	{
		getMendixObject().setValue(context, MemberNames.ProcessingLogsTotal.toString(), processinglogstotal);
	}

	/**
	 * @return value of ProcessingLogsFirstChunk
	 */
	public final java.lang.Boolean getProcessingLogsFirstChunk()
	{
		return getProcessingLogsFirstChunk(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessingLogsFirstChunk
	 */
	public final java.lang.Boolean getProcessingLogsFirstChunk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ProcessingLogsFirstChunk.toString());
	}

	/**
	 * Set value of ProcessingLogsFirstChunk
	 * @param processinglogsfirstchunk
	 */
	public final void setProcessingLogsFirstChunk(java.lang.Boolean processinglogsfirstchunk)
	{
		setProcessingLogsFirstChunk(getContext(), processinglogsfirstchunk);
	}

	/**
	 * Set value of ProcessingLogsFirstChunk
	 * @param context
	 * @param processinglogsfirstchunk
	 */
	public final void setProcessingLogsFirstChunk(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean processinglogsfirstchunk)
	{
		getMendixObject().setValue(context, MemberNames.ProcessingLogsFirstChunk.toString(), processinglogsfirstchunk);
	}

	/**
	 * @return value of ProcessingLogsPreviousChunk
	 */
	public final java.lang.Boolean getProcessingLogsPreviousChunk()
	{
		return getProcessingLogsPreviousChunk(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessingLogsPreviousChunk
	 */
	public final java.lang.Boolean getProcessingLogsPreviousChunk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ProcessingLogsPreviousChunk.toString());
	}

	/**
	 * Set value of ProcessingLogsPreviousChunk
	 * @param processinglogspreviouschunk
	 */
	public final void setProcessingLogsPreviousChunk(java.lang.Boolean processinglogspreviouschunk)
	{
		setProcessingLogsPreviousChunk(getContext(), processinglogspreviouschunk);
	}

	/**
	 * Set value of ProcessingLogsPreviousChunk
	 * @param context
	 * @param processinglogspreviouschunk
	 */
	public final void setProcessingLogsPreviousChunk(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean processinglogspreviouschunk)
	{
		getMendixObject().setValue(context, MemberNames.ProcessingLogsPreviousChunk.toString(), processinglogspreviouschunk);
	}

	/**
	 * @return value of ProcessingLogsNextChunk
	 */
	public final java.lang.Boolean getProcessingLogsNextChunk()
	{
		return getProcessingLogsNextChunk(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessingLogsNextChunk
	 */
	public final java.lang.Boolean getProcessingLogsNextChunk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ProcessingLogsNextChunk.toString());
	}

	/**
	 * Set value of ProcessingLogsNextChunk
	 * @param processinglogsnextchunk
	 */
	public final void setProcessingLogsNextChunk(java.lang.Boolean processinglogsnextchunk)
	{
		setProcessingLogsNextChunk(getContext(), processinglogsnextchunk);
	}

	/**
	 * Set value of ProcessingLogsNextChunk
	 * @param context
	 * @param processinglogsnextchunk
	 */
	public final void setProcessingLogsNextChunk(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean processinglogsnextchunk)
	{
		getMendixObject().setValue(context, MemberNames.ProcessingLogsNextChunk.toString(), processinglogsnextchunk);
	}

	/**
	 * @return value of ProcessingLogsLastChunk
	 */
	public final java.lang.Boolean getProcessingLogsLastChunk()
	{
		return getProcessingLogsLastChunk(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessingLogsLastChunk
	 */
	public final java.lang.Boolean getProcessingLogsLastChunk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ProcessingLogsLastChunk.toString());
	}

	/**
	 * Set value of ProcessingLogsLastChunk
	 * @param processinglogslastchunk
	 */
	public final void setProcessingLogsLastChunk(java.lang.Boolean processinglogslastchunk)
	{
		setProcessingLogsLastChunk(getContext(), processinglogslastchunk);
	}

	/**
	 * Set value of ProcessingLogsLastChunk
	 * @param context
	 * @param processinglogslastchunk
	 */
	public final void setProcessingLogsLastChunk(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean processinglogslastchunk)
	{
		getMendixObject().setValue(context, MemberNames.ProcessingLogsLastChunk.toString(), processinglogslastchunk);
	}

	/**
	 * @return value of ProcessingLogsIsFirstChunk
	 */
	public final java.lang.Boolean getProcessingLogsIsFirstChunk()
	{
		return getProcessingLogsIsFirstChunk(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessingLogsIsFirstChunk
	 */
	public final java.lang.Boolean getProcessingLogsIsFirstChunk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ProcessingLogsIsFirstChunk.toString());
	}

	/**
	 * Set value of ProcessingLogsIsFirstChunk
	 * @param processinglogsisfirstchunk
	 */
	public final void setProcessingLogsIsFirstChunk(java.lang.Boolean processinglogsisfirstchunk)
	{
		setProcessingLogsIsFirstChunk(getContext(), processinglogsisfirstchunk);
	}

	/**
	 * Set value of ProcessingLogsIsFirstChunk
	 * @param context
	 * @param processinglogsisfirstchunk
	 */
	public final void setProcessingLogsIsFirstChunk(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean processinglogsisfirstchunk)
	{
		getMendixObject().setValue(context, MemberNames.ProcessingLogsIsFirstChunk.toString(), processinglogsisfirstchunk);
	}

	/**
	 * @return value of ProcessingLogsIsLastChunk
	 */
	public final java.lang.Boolean getProcessingLogsIsLastChunk()
	{
		return getProcessingLogsIsLastChunk(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessingLogsIsLastChunk
	 */
	public final java.lang.Boolean getProcessingLogsIsLastChunk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ProcessingLogsIsLastChunk.toString());
	}

	/**
	 * Set value of ProcessingLogsIsLastChunk
	 * @param processinglogsislastchunk
	 */
	public final void setProcessingLogsIsLastChunk(java.lang.Boolean processinglogsislastchunk)
	{
		setProcessingLogsIsLastChunk(getContext(), processinglogsislastchunk);
	}

	/**
	 * Set value of ProcessingLogsIsLastChunk
	 * @param context
	 * @param processinglogsislastchunk
	 */
	public final void setProcessingLogsIsLastChunk(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean processinglogsislastchunk)
	{
		getMendixObject().setValue(context, MemberNames.ProcessingLogsIsLastChunk.toString(), processinglogsislastchunk);
	}

	/**
	 * @return value of MessageID
	 */
	public final java.lang.String getMessageID()
	{
		return getMessageID(getContext());
	}

	/**
	 * @param context
	 * @return value of MessageID
	 */
	public final java.lang.String getMessageID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MessageID.toString());
	}

	/**
	 * Set value of MessageID
	 * @param messageid
	 */
	public final void setMessageID(java.lang.String messageid)
	{
		setMessageID(getContext(), messageid);
	}

	/**
	 * Set value of MessageID
	 * @param context
	 * @param messageid
	 */
	public final void setMessageID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String messageid)
	{
		getMendixObject().setValue(context, MemberNames.MessageID.toString(), messageid);
	}

	/**
	 * @return value of IndexSearchParam
	 */
	public final java.lang.String getIndexSearchParam()
	{
		return getIndexSearchParam(getContext());
	}

	/**
	 * @param context
	 * @return value of IndexSearchParam
	 */
	public final java.lang.String getIndexSearchParam(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IndexSearchParam.toString());
	}

	/**
	 * Set value of IndexSearchParam
	 * @param indexsearchparam
	 */
	public final void setIndexSearchParam(java.lang.String indexsearchparam)
	{
		setIndexSearchParam(getContext(), indexsearchparam);
	}

	/**
	 * Set value of IndexSearchParam
	 * @param context
	 * @param indexsearchparam
	 */
	public final void setIndexSearchParam(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String indexsearchparam)
	{
		getMendixObject().setValue(context, MemberNames.IndexSearchParam.toString(), indexsearchparam);
	}

	/**
	 * Set value of MessageStatus
	 * @param messagestatus
	 */
	public final interfaceshared.proxies.MessageStatus getMessageStatus()
	{
		return getMessageStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of MessageStatus
	 */
	public final interfaceshared.proxies.MessageStatus getMessageStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.MessageStatus.toString());
		if (obj == null)
			return null;

		return interfaceshared.proxies.MessageStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of MessageStatus
	 * @param messagestatus
	 */
	public final void setMessageStatus(interfaceshared.proxies.MessageStatus messagestatus)
	{
		setMessageStatus(getContext(), messagestatus);
	}

	/**
	 * Set value of MessageStatus
	 * @param context
	 * @param messagestatus
	 */
	public final void setMessageStatus(com.mendix.systemwideinterfaces.core.IContext context, interfaceshared.proxies.MessageStatus messagestatus)
	{
		if (messagestatus != null)
			getMendixObject().setValue(context, MemberNames.MessageStatus.toString(), messagestatus.toString());
		else
			getMendixObject().setValue(context, MemberNames.MessageStatus.toString(), null);
	}

	/**
	 * @return value of ShowCreatedByCustomMessage
	 */
	public final java.lang.Boolean getShowCreatedByCustomMessage()
	{
		return getShowCreatedByCustomMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowCreatedByCustomMessage
	 */
	public final java.lang.Boolean getShowCreatedByCustomMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowCreatedByCustomMessage.toString());
	}

	/**
	 * Set value of ShowCreatedByCustomMessage
	 * @param showcreatedbycustommessage
	 */
	public final void setShowCreatedByCustomMessage(java.lang.Boolean showcreatedbycustommessage)
	{
		setShowCreatedByCustomMessage(getContext(), showcreatedbycustommessage);
	}

	/**
	 * Set value of ShowCreatedByCustomMessage
	 * @param context
	 * @param showcreatedbycustommessage
	 */
	public final void setShowCreatedByCustomMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showcreatedbycustommessage)
	{
		getMendixObject().setValue(context, MemberNames.ShowCreatedByCustomMessage.toString(), showcreatedbycustommessage);
	}

	/**
	 * @return value of InterfaceMonitoring_InterfaceConfiguration
	 */
	public final interfaceconfiguration.proxies.InterfaceConfiguration getInterfaceMonitoring_InterfaceConfiguration() throws com.mendix.core.CoreException
	{
		return getInterfaceMonitoring_InterfaceConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of InterfaceMonitoring_InterfaceConfiguration
	 */
	public final interfaceconfiguration.proxies.InterfaceConfiguration getInterfaceMonitoring_InterfaceConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceconfiguration.proxies.InterfaceConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.InterfaceMonitoring_InterfaceConfiguration.toString());
		if (identifier != null)
			result = interfaceconfiguration.proxies.InterfaceConfiguration.load(context, identifier);
		return result;
	}

	/**
	 * Set value of InterfaceMonitoring_InterfaceConfiguration
	 * @param interfacemonitoring_interfaceconfiguration
	 */
	public final void setInterfaceMonitoring_InterfaceConfiguration(interfaceconfiguration.proxies.InterfaceConfiguration interfacemonitoring_interfaceconfiguration)
	{
		setInterfaceMonitoring_InterfaceConfiguration(getContext(), interfacemonitoring_interfaceconfiguration);
	}

	/**
	 * Set value of InterfaceMonitoring_InterfaceConfiguration
	 * @param context
	 * @param interfacemonitoring_interfaceconfiguration
	 */
	public final void setInterfaceMonitoring_InterfaceConfiguration(com.mendix.systemwideinterfaces.core.IContext context, interfaceconfiguration.proxies.InterfaceConfiguration interfacemonitoring_interfaceconfiguration)
	{
		if (interfacemonitoring_interfaceconfiguration == null)
			getMendixObject().setValue(context, MemberNames.InterfaceMonitoring_InterfaceConfiguration.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.InterfaceMonitoring_InterfaceConfiguration.toString(), interfacemonitoring_interfaceconfiguration.getMendixObject().getId());
	}

	/**
	 * @return value of UU95_InterfaceMonitoring_Message
	 */
	public final java.util.List<interfaceshared.proxies.Message> getUU95_InterfaceMonitoring_Message() throws com.mendix.core.CoreException
	{
		return getUU95_InterfaceMonitoring_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of UU95_InterfaceMonitoring_Message
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<interfaceshared.proxies.Message> getUU95_InterfaceMonitoring_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<interfaceshared.proxies.Message> result = new java.util.ArrayList<interfaceshared.proxies.Message>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.UU95_InterfaceMonitoring_Message.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(interfaceshared.proxies.Message.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of UU95_InterfaceMonitoring_Message
	 * @param uu95_interfacemonitoring_message
	 */
	public final void setUU95_InterfaceMonitoring_Message(java.util.List<interfaceshared.proxies.Message> uu95_interfacemonitoring_message)
	{
		setUU95_InterfaceMonitoring_Message(getContext(), uu95_interfacemonitoring_message);
	}

	/**
	 * Set value of UU95_InterfaceMonitoring_Message
	 * @param context
	 * @param uu95_interfacemonitoring_message
	 */
	public final void setUU95_InterfaceMonitoring_Message(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<interfaceshared.proxies.Message> uu95_interfacemonitoring_message)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (interfaceshared.proxies.Message proxyObject : uu95_interfacemonitoring_message)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.UU95_InterfaceMonitoring_Message.toString(), identifiers);
	}

	/**
	 * @return value of InterfaceMonitoring_SearchParams
	 */
	public final advancedsearch.proxies.SearchParams getInterfaceMonitoring_SearchParams() throws com.mendix.core.CoreException
	{
		return getInterfaceMonitoring_SearchParams(getContext());
	}

	/**
	 * @param context
	 * @return value of InterfaceMonitoring_SearchParams
	 */
	public final advancedsearch.proxies.SearchParams getInterfaceMonitoring_SearchParams(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		advancedsearch.proxies.SearchParams result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.InterfaceMonitoring_SearchParams.toString());
		if (identifier != null)
			result = advancedsearch.proxies.SearchParams.load(context, identifier);
		return result;
	}

	/**
	 * Set value of InterfaceMonitoring_SearchParams
	 * @param interfacemonitoring_searchparams
	 */
	public final void setInterfaceMonitoring_SearchParams(advancedsearch.proxies.SearchParams interfacemonitoring_searchparams)
	{
		setInterfaceMonitoring_SearchParams(getContext(), interfacemonitoring_searchparams);
	}

	/**
	 * Set value of InterfaceMonitoring_SearchParams
	 * @param context
	 * @param interfacemonitoring_searchparams
	 */
	public final void setInterfaceMonitoring_SearchParams(com.mendix.systemwideinterfaces.core.IContext context, advancedsearch.proxies.SearchParams interfacemonitoring_searchparams)
	{
		if (interfacemonitoring_searchparams == null)
			getMendixObject().setValue(context, MemberNames.InterfaceMonitoring_SearchParams.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.InterfaceMonitoring_SearchParams.toString(), interfacemonitoring_searchparams.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return interfaceMonitoringMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final interfaceconfiguration.proxies.InterfaceMonitoring that = (interfaceconfiguration.proxies.InterfaceMonitoring) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "InterfaceConfiguration.InterfaceMonitoring";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
