// This file was generated by Mendix Modeler 7.7.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emailplus.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the EmailPlus module

	public static boolean getAccountGetsHostnameAttached()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("EmailPlus.AccountGetsHostnameAttached");
	}

	public static boolean getDebugJavaMail()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("EmailPlus.DebugJavaMail");
	}

	/**
	* 1048576=1MB, 33554432=32MB
	*/
	public static java.lang.Long getIMAPFetchSize()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("EmailPlus.IMAPFetchSize");
	}

	public static java.lang.Long getMaxSendEmailRetryCount()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("EmailPlus.MaxSendEmailRetryCount");
	}

	public static java.lang.Long getSendEmailRetryMinutes()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("EmailPlus.SendEmailRetryMinutes");
	}

	public static boolean getUseIncomingEmail()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("EmailPlus.UseIncomingEmail");
	}

	public static boolean getUseOutgoingEmail()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("EmailPlus.UseOutgoingEmail");
	}
}