// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package interfacerequests.proxies;

public class DynamicAttributeResponsesContainerExpertDesk
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dynamicAttributeResponsesContainerExpertDeskMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "InterfaceRequests.DynamicAttributeResponsesContainerExpertDesk";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DynamicAttributeResponsesContainerExpertDesk_TaskResponse("InterfaceRequests.DynamicAttributeResponsesContainerExpertDesk_TaskResponse"),
		DynamicAttributeResponsesContainerExpertDesk_RequestResponse("InterfaceRequests.DynamicAttributeResponsesContainerExpertDesk_RequestResponse"),
		UU95_DynamicAttributeResponsesContainerExpertDesk_RequestUpdateResponse("InterfaceRequests.UU95_DynamicAttributeResponsesContainerExpertDesk_RequestUpdateResponse");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DynamicAttributeResponsesContainerExpertDesk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "InterfaceRequests.DynamicAttributeResponsesContainerExpertDesk"));
	}

	protected DynamicAttributeResponsesContainerExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dynamicAttributeResponsesContainerExpertDeskMendixObject)
	{
		if (dynamicAttributeResponsesContainerExpertDeskMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("InterfaceRequests.DynamicAttributeResponsesContainerExpertDesk", dynamicAttributeResponsesContainerExpertDeskMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a InterfaceRequests.DynamicAttributeResponsesContainerExpertDesk");

		this.dynamicAttributeResponsesContainerExpertDeskMendixObject = dynamicAttributeResponsesContainerExpertDeskMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DynamicAttributeResponsesContainerExpertDesk.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static interfacerequests.proxies.DynamicAttributeResponsesContainerExpertDesk initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return interfacerequests.proxies.DynamicAttributeResponsesContainerExpertDesk.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static interfacerequests.proxies.DynamicAttributeResponsesContainerExpertDesk initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new interfacerequests.proxies.DynamicAttributeResponsesContainerExpertDesk(context, mendixObject);
	}

	public static interfacerequests.proxies.DynamicAttributeResponsesContainerExpertDesk load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return interfacerequests.proxies.DynamicAttributeResponsesContainerExpertDesk.initialize(context, mendixObject);
	}

	public static java.util.List<interfacerequests.proxies.DynamicAttributeResponsesContainerExpertDesk> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<interfacerequests.proxies.DynamicAttributeResponsesContainerExpertDesk> result = new java.util.ArrayList<interfacerequests.proxies.DynamicAttributeResponsesContainerExpertDesk>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//InterfaceRequests.DynamicAttributeResponsesContainerExpertDesk" + xpathConstraint))
			result.add(interfacerequests.proxies.DynamicAttributeResponsesContainerExpertDesk.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DynamicAttributeResponsesContainerExpertDesk_TaskResponse
	 */
	public final interfacerequests.proxies.TaskResponse getDynamicAttributeResponsesContainerExpertDesk_TaskResponse() throws com.mendix.core.CoreException
	{
		return getDynamicAttributeResponsesContainerExpertDesk_TaskResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of DynamicAttributeResponsesContainerExpertDesk_TaskResponse
	 */
	public final interfacerequests.proxies.TaskResponse getDynamicAttributeResponsesContainerExpertDesk_TaskResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacerequests.proxies.TaskResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DynamicAttributeResponsesContainerExpertDesk_TaskResponse.toString());
		if (identifier != null)
			result = interfacerequests.proxies.TaskResponse.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DynamicAttributeResponsesContainerExpertDesk_TaskResponse
	 * @param dynamicattributeresponsescontainerexpertdesk_taskresponse
	 */
	public final void setDynamicAttributeResponsesContainerExpertDesk_TaskResponse(interfacerequests.proxies.TaskResponse dynamicattributeresponsescontainerexpertdesk_taskresponse)
	{
		setDynamicAttributeResponsesContainerExpertDesk_TaskResponse(getContext(), dynamicattributeresponsescontainerexpertdesk_taskresponse);
	}

	/**
	 * Set value of DynamicAttributeResponsesContainerExpertDesk_TaskResponse
	 * @param context
	 * @param dynamicattributeresponsescontainerexpertdesk_taskresponse
	 */
	public final void setDynamicAttributeResponsesContainerExpertDesk_TaskResponse(com.mendix.systemwideinterfaces.core.IContext context, interfacerequests.proxies.TaskResponse dynamicattributeresponsescontainerexpertdesk_taskresponse)
	{
		if (dynamicattributeresponsescontainerexpertdesk_taskresponse == null)
			getMendixObject().setValue(context, MemberNames.DynamicAttributeResponsesContainerExpertDesk_TaskResponse.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DynamicAttributeResponsesContainerExpertDesk_TaskResponse.toString(), dynamicattributeresponsescontainerexpertdesk_taskresponse.getMendixObject().getId());
	}

	/**
	 * @return value of DynamicAttributeResponsesContainerExpertDesk_RequestResponse
	 */
	public final interfacerequests.proxies.RequestResponse getDynamicAttributeResponsesContainerExpertDesk_RequestResponse() throws com.mendix.core.CoreException
	{
		return getDynamicAttributeResponsesContainerExpertDesk_RequestResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of DynamicAttributeResponsesContainerExpertDesk_RequestResponse
	 */
	public final interfacerequests.proxies.RequestResponse getDynamicAttributeResponsesContainerExpertDesk_RequestResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacerequests.proxies.RequestResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DynamicAttributeResponsesContainerExpertDesk_RequestResponse.toString());
		if (identifier != null)
			result = interfacerequests.proxies.RequestResponse.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DynamicAttributeResponsesContainerExpertDesk_RequestResponse
	 * @param dynamicattributeresponsescontainerexpertdesk_requestresponse
	 */
	public final void setDynamicAttributeResponsesContainerExpertDesk_RequestResponse(interfacerequests.proxies.RequestResponse dynamicattributeresponsescontainerexpertdesk_requestresponse)
	{
		setDynamicAttributeResponsesContainerExpertDesk_RequestResponse(getContext(), dynamicattributeresponsescontainerexpertdesk_requestresponse);
	}

	/**
	 * Set value of DynamicAttributeResponsesContainerExpertDesk_RequestResponse
	 * @param context
	 * @param dynamicattributeresponsescontainerexpertdesk_requestresponse
	 */
	public final void setDynamicAttributeResponsesContainerExpertDesk_RequestResponse(com.mendix.systemwideinterfaces.core.IContext context, interfacerequests.proxies.RequestResponse dynamicattributeresponsescontainerexpertdesk_requestresponse)
	{
		if (dynamicattributeresponsescontainerexpertdesk_requestresponse == null)
			getMendixObject().setValue(context, MemberNames.DynamicAttributeResponsesContainerExpertDesk_RequestResponse.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DynamicAttributeResponsesContainerExpertDesk_RequestResponse.toString(), dynamicattributeresponsescontainerexpertdesk_requestresponse.getMendixObject().getId());
	}

	/**
	 * @return value of UU95_DynamicAttributeResponsesContainerExpertDesk_RequestUpdateResponse
	 */
	public final interfacerequestupdate.proxies.RequestUpdateResponse getUU95_DynamicAttributeResponsesContainerExpertDesk_RequestUpdateResponse() throws com.mendix.core.CoreException
	{
		return getUU95_DynamicAttributeResponsesContainerExpertDesk_RequestUpdateResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of UU95_DynamicAttributeResponsesContainerExpertDesk_RequestUpdateResponse
	 */
	public final interfacerequestupdate.proxies.RequestUpdateResponse getUU95_DynamicAttributeResponsesContainerExpertDesk_RequestUpdateResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacerequestupdate.proxies.RequestUpdateResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UU95_DynamicAttributeResponsesContainerExpertDesk_RequestUpdateResponse.toString());
		if (identifier != null)
			result = interfacerequestupdate.proxies.RequestUpdateResponse.load(context, identifier);
		return result;
	}

	/**
	 * Set value of UU95_DynamicAttributeResponsesContainerExpertDesk_RequestUpdateResponse
	 * @param uu95_dynamicattributeresponsescontainerexpertdesk_requestupdateresponse
	 */
	public final void setUU95_DynamicAttributeResponsesContainerExpertDesk_RequestUpdateResponse(interfacerequestupdate.proxies.RequestUpdateResponse uu95_dynamicattributeresponsescontainerexpertdesk_requestupdateresponse)
	{
		setUU95_DynamicAttributeResponsesContainerExpertDesk_RequestUpdateResponse(getContext(), uu95_dynamicattributeresponsescontainerexpertdesk_requestupdateresponse);
	}

	/**
	 * Set value of UU95_DynamicAttributeResponsesContainerExpertDesk_RequestUpdateResponse
	 * @param context
	 * @param uu95_dynamicattributeresponsescontainerexpertdesk_requestupdateresponse
	 */
	public final void setUU95_DynamicAttributeResponsesContainerExpertDesk_RequestUpdateResponse(com.mendix.systemwideinterfaces.core.IContext context, interfacerequestupdate.proxies.RequestUpdateResponse uu95_dynamicattributeresponsescontainerexpertdesk_requestupdateresponse)
	{
		if (uu95_dynamicattributeresponsescontainerexpertdesk_requestupdateresponse == null)
			getMendixObject().setValue(context, MemberNames.UU95_DynamicAttributeResponsesContainerExpertDesk_RequestUpdateResponse.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.UU95_DynamicAttributeResponsesContainerExpertDesk_RequestUpdateResponse.toString(), uu95_dynamicattributeresponsescontainerexpertdesk_requestupdateresponse.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dynamicAttributeResponsesContainerExpertDeskMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final interfacerequests.proxies.DynamicAttributeResponsesContainerExpertDesk that = (interfacerequests.proxies.DynamicAttributeResponsesContainerExpertDesk) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "InterfaceRequests.DynamicAttributeResponsesContainerExpertDesk";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
