// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package interfacerequests.proxies;

public class ServiceRequestSpecificFields extends interfaceshared.proxies.AuditableEntity
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "InterfaceRequests.ServiceRequestSpecificFields";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CustomerWishDateString("CustomerWishDateString"),
		CustomerWishDate("CustomerWishDate"),
		CustomerWishDateReason("CustomerWishDateReason"),
		IncomingRequest_ServiceRequestSpecificFields("InterfaceRequests.IncomingRequest_ServiceRequestSpecificFields"),
		ServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields("InterfaceRequests.ServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields"),
		IncomingRequestUpdate_ServiceRequestSpecificFields("InterfaceRequestUpdate.IncomingRequestUpdate_ServiceRequestSpecificFields");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ServiceRequestSpecificFields(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "InterfaceRequests.ServiceRequestSpecificFields"));
	}

	protected ServiceRequestSpecificFields(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject serviceRequestSpecificFieldsMendixObject)
	{
		super(context, serviceRequestSpecificFieldsMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("InterfaceRequests.ServiceRequestSpecificFields", serviceRequestSpecificFieldsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a InterfaceRequests.ServiceRequestSpecificFields");
	}

	/**
	 * @deprecated Use 'ServiceRequestSpecificFields.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static interfacerequests.proxies.ServiceRequestSpecificFields initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return interfacerequests.proxies.ServiceRequestSpecificFields.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static interfacerequests.proxies.ServiceRequestSpecificFields initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new interfacerequests.proxies.ServiceRequestSpecificFields(context, mendixObject);
	}

	public static interfacerequests.proxies.ServiceRequestSpecificFields load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return interfacerequests.proxies.ServiceRequestSpecificFields.initialize(context, mendixObject);
	}

	public static java.util.List<interfacerequests.proxies.ServiceRequestSpecificFields> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<interfacerequests.proxies.ServiceRequestSpecificFields> result = new java.util.ArrayList<interfacerequests.proxies.ServiceRequestSpecificFields>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//InterfaceRequests.ServiceRequestSpecificFields" + xpathConstraint))
			result.add(interfacerequests.proxies.ServiceRequestSpecificFields.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of CustomerWishDateString
	 */
	public final java.lang.String getCustomerWishDateString()
	{
		return getCustomerWishDateString(getContext());
	}

	/**
	 * @param context
	 * @return value of CustomerWishDateString
	 */
	public final java.lang.String getCustomerWishDateString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CustomerWishDateString.toString());
	}

	/**
	 * Set value of CustomerWishDateString
	 * @param customerwishdatestring
	 */
	public final void setCustomerWishDateString(java.lang.String customerwishdatestring)
	{
		setCustomerWishDateString(getContext(), customerwishdatestring);
	}

	/**
	 * Set value of CustomerWishDateString
	 * @param context
	 * @param customerwishdatestring
	 */
	public final void setCustomerWishDateString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customerwishdatestring)
	{
		getMendixObject().setValue(context, MemberNames.CustomerWishDateString.toString(), customerwishdatestring);
	}

	/**
	 * @return value of CustomerWishDate
	 */
	public final java.util.Date getCustomerWishDate()
	{
		return getCustomerWishDate(getContext());
	}

	/**
	 * @param context
	 * @return value of CustomerWishDate
	 */
	public final java.util.Date getCustomerWishDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CustomerWishDate.toString());
	}

	/**
	 * Set value of CustomerWishDate
	 * @param customerwishdate
	 */
	public final void setCustomerWishDate(java.util.Date customerwishdate)
	{
		setCustomerWishDate(getContext(), customerwishdate);
	}

	/**
	 * Set value of CustomerWishDate
	 * @param context
	 * @param customerwishdate
	 */
	public final void setCustomerWishDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date customerwishdate)
	{
		getMendixObject().setValue(context, MemberNames.CustomerWishDate.toString(), customerwishdate);
	}

	/**
	 * @return value of CustomerWishDateReason
	 */
	public final java.lang.String getCustomerWishDateReason()
	{
		return getCustomerWishDateReason(getContext());
	}

	/**
	 * @param context
	 * @return value of CustomerWishDateReason
	 */
	public final java.lang.String getCustomerWishDateReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CustomerWishDateReason.toString());
	}

	/**
	 * Set value of CustomerWishDateReason
	 * @param customerwishdatereason
	 */
	public final void setCustomerWishDateReason(java.lang.String customerwishdatereason)
	{
		setCustomerWishDateReason(getContext(), customerwishdatereason);
	}

	/**
	 * Set value of CustomerWishDateReason
	 * @param context
	 * @param customerwishdatereason
	 */
	public final void setCustomerWishDateReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customerwishdatereason)
	{
		getMendixObject().setValue(context, MemberNames.CustomerWishDateReason.toString(), customerwishdatereason);
	}

	/**
	 * @return value of IncomingRequest_ServiceRequestSpecificFields
	 */
	public final interfacerequests.proxies.IncomingRequest getIncomingRequest_ServiceRequestSpecificFields() throws com.mendix.core.CoreException
	{
		return getIncomingRequest_ServiceRequestSpecificFields(getContext());
	}

	/**
	 * @param context
	 * @return value of IncomingRequest_ServiceRequestSpecificFields
	 */
	public final interfacerequests.proxies.IncomingRequest getIncomingRequest_ServiceRequestSpecificFields(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacerequests.proxies.IncomingRequest result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.IncomingRequest_ServiceRequestSpecificFields.toString());
		if (identifier != null)
			result = interfacerequests.proxies.IncomingRequest.load(context, identifier);
		return result;
	}

	/**
	 * Set value of IncomingRequest_ServiceRequestSpecificFields
	 * @param incomingrequest_servicerequestspecificfields
	 */
	public final void setIncomingRequest_ServiceRequestSpecificFields(interfacerequests.proxies.IncomingRequest incomingrequest_servicerequestspecificfields)
	{
		setIncomingRequest_ServiceRequestSpecificFields(getContext(), incomingrequest_servicerequestspecificfields);
	}

	/**
	 * Set value of IncomingRequest_ServiceRequestSpecificFields
	 * @param context
	 * @param incomingrequest_servicerequestspecificfields
	 */
	public final void setIncomingRequest_ServiceRequestSpecificFields(com.mendix.systemwideinterfaces.core.IContext context, interfacerequests.proxies.IncomingRequest incomingrequest_servicerequestspecificfields)
	{
		if (incomingrequest_servicerequestspecificfields == null)
			getMendixObject().setValue(context, MemberNames.IncomingRequest_ServiceRequestSpecificFields.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.IncomingRequest_ServiceRequestSpecificFields.toString(), incomingrequest_servicerequestspecificfields.getMendixObject().getId());
	}

	/**
	 * @return value of ServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields
	 */
	public final interfacerequests.proxies.ServiceRequestSpecificFieldsContainerExpertDesk getServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields() throws com.mendix.core.CoreException
	{
		return getServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields
	 */
	public final interfacerequests.proxies.ServiceRequestSpecificFieldsContainerExpertDesk getServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacerequests.proxies.ServiceRequestSpecificFieldsContainerExpertDesk result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields.toString());
		if (identifier != null)
			result = interfacerequests.proxies.ServiceRequestSpecificFieldsContainerExpertDesk.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields
	 * @param servicerequestspecificfieldscontainerexpertdesk_servicerequestspecificfields
	 */
	public final void setServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields(interfacerequests.proxies.ServiceRequestSpecificFieldsContainerExpertDesk servicerequestspecificfieldscontainerexpertdesk_servicerequestspecificfields)
	{
		setServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields(getContext(), servicerequestspecificfieldscontainerexpertdesk_servicerequestspecificfields);
	}

	/**
	 * Set value of ServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields
	 * @param context
	 * @param servicerequestspecificfieldscontainerexpertdesk_servicerequestspecificfields
	 */
	public final void setServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields(com.mendix.systemwideinterfaces.core.IContext context, interfacerequests.proxies.ServiceRequestSpecificFieldsContainerExpertDesk servicerequestspecificfieldscontainerexpertdesk_servicerequestspecificfields)
	{
		if (servicerequestspecificfieldscontainerexpertdesk_servicerequestspecificfields == null)
			getMendixObject().setValue(context, MemberNames.ServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields.toString(), servicerequestspecificfieldscontainerexpertdesk_servicerequestspecificfields.getMendixObject().getId());
	}

	/**
	 * @return value of IncomingRequestUpdate_ServiceRequestSpecificFields
	 */
	public final interfacerequestupdate.proxies.IncomingRequestUpdate getIncomingRequestUpdate_ServiceRequestSpecificFields() throws com.mendix.core.CoreException
	{
		return getIncomingRequestUpdate_ServiceRequestSpecificFields(getContext());
	}

	/**
	 * @param context
	 * @return value of IncomingRequestUpdate_ServiceRequestSpecificFields
	 */
	public final interfacerequestupdate.proxies.IncomingRequestUpdate getIncomingRequestUpdate_ServiceRequestSpecificFields(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacerequestupdate.proxies.IncomingRequestUpdate result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.IncomingRequestUpdate_ServiceRequestSpecificFields.toString());
		if (identifier != null)
			result = interfacerequestupdate.proxies.IncomingRequestUpdate.load(context, identifier);
		return result;
	}

	/**
	 * Set value of IncomingRequestUpdate_ServiceRequestSpecificFields
	 * @param incomingrequestupdate_servicerequestspecificfields
	 */
	public final void setIncomingRequestUpdate_ServiceRequestSpecificFields(interfacerequestupdate.proxies.IncomingRequestUpdate incomingrequestupdate_servicerequestspecificfields)
	{
		setIncomingRequestUpdate_ServiceRequestSpecificFields(getContext(), incomingrequestupdate_servicerequestspecificfields);
	}

	/**
	 * Set value of IncomingRequestUpdate_ServiceRequestSpecificFields
	 * @param context
	 * @param incomingrequestupdate_servicerequestspecificfields
	 */
	public final void setIncomingRequestUpdate_ServiceRequestSpecificFields(com.mendix.systemwideinterfaces.core.IContext context, interfacerequestupdate.proxies.IncomingRequestUpdate incomingrequestupdate_servicerequestspecificfields)
	{
		if (incomingrequestupdate_servicerequestspecificfields == null)
			getMendixObject().setValue(context, MemberNames.IncomingRequestUpdate_ServiceRequestSpecificFields.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.IncomingRequestUpdate_ServiceRequestSpecificFields.toString(), incomingrequestupdate_servicerequestspecificfields.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final interfacerequests.proxies.ServiceRequestSpecificFields that = (interfacerequests.proxies.ServiceRequestSpecificFields) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "InterfaceRequests.ServiceRequestSpecificFields";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
