// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package interfacerequests.proxies;

public class ServiceRequestSpecificFieldsContainerExpertDesk
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject serviceRequestSpecificFieldsContainerExpertDeskMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "InterfaceRequests.ServiceRequestSpecificFieldsContainerExpertDesk";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields("InterfaceRequests.ServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields"),
		ServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestExpertDesk("InterfaceRequests.ServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestExpertDesk"),
		ServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestUpdateExpertDesk("InterfaceRequests.ServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestUpdateExpertDesk");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ServiceRequestSpecificFieldsContainerExpertDesk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "InterfaceRequests.ServiceRequestSpecificFieldsContainerExpertDesk"));
	}

	protected ServiceRequestSpecificFieldsContainerExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject serviceRequestSpecificFieldsContainerExpertDeskMendixObject)
	{
		if (serviceRequestSpecificFieldsContainerExpertDeskMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("InterfaceRequests.ServiceRequestSpecificFieldsContainerExpertDesk", serviceRequestSpecificFieldsContainerExpertDeskMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a InterfaceRequests.ServiceRequestSpecificFieldsContainerExpertDesk");

		this.serviceRequestSpecificFieldsContainerExpertDeskMendixObject = serviceRequestSpecificFieldsContainerExpertDeskMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ServiceRequestSpecificFieldsContainerExpertDesk.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static interfacerequests.proxies.ServiceRequestSpecificFieldsContainerExpertDesk initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return interfacerequests.proxies.ServiceRequestSpecificFieldsContainerExpertDesk.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static interfacerequests.proxies.ServiceRequestSpecificFieldsContainerExpertDesk initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new interfacerequests.proxies.ServiceRequestSpecificFieldsContainerExpertDesk(context, mendixObject);
	}

	public static interfacerequests.proxies.ServiceRequestSpecificFieldsContainerExpertDesk load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return interfacerequests.proxies.ServiceRequestSpecificFieldsContainerExpertDesk.initialize(context, mendixObject);
	}

	public static java.util.List<interfacerequests.proxies.ServiceRequestSpecificFieldsContainerExpertDesk> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<interfacerequests.proxies.ServiceRequestSpecificFieldsContainerExpertDesk> result = new java.util.ArrayList<interfacerequests.proxies.ServiceRequestSpecificFieldsContainerExpertDesk>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//InterfaceRequests.ServiceRequestSpecificFieldsContainerExpertDesk" + xpathConstraint))
			result.add(interfacerequests.proxies.ServiceRequestSpecificFieldsContainerExpertDesk.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields
	 */
	public final interfacerequests.proxies.ServiceRequestSpecificFields getServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields() throws com.mendix.core.CoreException
	{
		return getServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields
	 */
	public final interfacerequests.proxies.ServiceRequestSpecificFields getServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacerequests.proxies.ServiceRequestSpecificFields result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields.toString());
		if (identifier != null)
			result = interfacerequests.proxies.ServiceRequestSpecificFields.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields
	 * @param servicerequestspecificfieldscontainerexpertdesk_servicerequestspecificfields
	 */
	public final void setServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields(interfacerequests.proxies.ServiceRequestSpecificFields servicerequestspecificfieldscontainerexpertdesk_servicerequestspecificfields)
	{
		setServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields(getContext(), servicerequestspecificfieldscontainerexpertdesk_servicerequestspecificfields);
	}

	/**
	 * Set value of ServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields
	 * @param context
	 * @param servicerequestspecificfieldscontainerexpertdesk_servicerequestspecificfields
	 */
	public final void setServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields(com.mendix.systemwideinterfaces.core.IContext context, interfacerequests.proxies.ServiceRequestSpecificFields servicerequestspecificfieldscontainerexpertdesk_servicerequestspecificfields)
	{
		if (servicerequestspecificfieldscontainerexpertdesk_servicerequestspecificfields == null)
			getMendixObject().setValue(context, MemberNames.ServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ServiceRequestSpecificFieldsContainerExpertDesk_ServiceRequestSpecificFields.toString(), servicerequestspecificfieldscontainerexpertdesk_servicerequestspecificfields.getMendixObject().getId());
	}

	/**
	 * @return value of ServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestExpertDesk
	 */
	public final interfacerequests.proxies.OutgoingRequestExpertDesk getServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestExpertDesk() throws com.mendix.core.CoreException
	{
		return getServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestExpertDesk(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestExpertDesk
	 */
	public final interfacerequests.proxies.OutgoingRequestExpertDesk getServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestExpertDesk(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacerequests.proxies.OutgoingRequestExpertDesk result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestExpertDesk.toString());
		if (identifier != null)
			result = interfacerequests.proxies.OutgoingRequestExpertDesk.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestExpertDesk
	 * @param servicerequestspecificfieldscontainerexpertdesk_outgoingrequestexpertdesk
	 */
	public final void setServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestExpertDesk(interfacerequests.proxies.OutgoingRequestExpertDesk servicerequestspecificfieldscontainerexpertdesk_outgoingrequestexpertdesk)
	{
		setServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestExpertDesk(getContext(), servicerequestspecificfieldscontainerexpertdesk_outgoingrequestexpertdesk);
	}

	/**
	 * Set value of ServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestExpertDesk
	 * @param context
	 * @param servicerequestspecificfieldscontainerexpertdesk_outgoingrequestexpertdesk
	 */
	public final void setServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, interfacerequests.proxies.OutgoingRequestExpertDesk servicerequestspecificfieldscontainerexpertdesk_outgoingrequestexpertdesk)
	{
		if (servicerequestspecificfieldscontainerexpertdesk_outgoingrequestexpertdesk == null)
			getMendixObject().setValue(context, MemberNames.ServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestExpertDesk.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestExpertDesk.toString(), servicerequestspecificfieldscontainerexpertdesk_outgoingrequestexpertdesk.getMendixObject().getId());
	}

	/**
	 * @return value of ServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestUpdateExpertDesk
	 */
	public final interfacerequestupdate.proxies.OutgoingRequestUpdateExpertDesk getServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestUpdateExpertDesk() throws com.mendix.core.CoreException
	{
		return getServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestUpdateExpertDesk(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestUpdateExpertDesk
	 */
	public final interfacerequestupdate.proxies.OutgoingRequestUpdateExpertDesk getServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestUpdateExpertDesk(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacerequestupdate.proxies.OutgoingRequestUpdateExpertDesk result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestUpdateExpertDesk.toString());
		if (identifier != null)
			result = interfacerequestupdate.proxies.OutgoingRequestUpdateExpertDesk.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestUpdateExpertDesk
	 * @param servicerequestspecificfieldscontainerexpertdesk_outgoingrequestupdateexpertdesk
	 */
	public final void setServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestUpdateExpertDesk(interfacerequestupdate.proxies.OutgoingRequestUpdateExpertDesk servicerequestspecificfieldscontainerexpertdesk_outgoingrequestupdateexpertdesk)
	{
		setServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestUpdateExpertDesk(getContext(), servicerequestspecificfieldscontainerexpertdesk_outgoingrequestupdateexpertdesk);
	}

	/**
	 * Set value of ServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestUpdateExpertDesk
	 * @param context
	 * @param servicerequestspecificfieldscontainerexpertdesk_outgoingrequestupdateexpertdesk
	 */
	public final void setServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestUpdateExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, interfacerequestupdate.proxies.OutgoingRequestUpdateExpertDesk servicerequestspecificfieldscontainerexpertdesk_outgoingrequestupdateexpertdesk)
	{
		if (servicerequestspecificfieldscontainerexpertdesk_outgoingrequestupdateexpertdesk == null)
			getMendixObject().setValue(context, MemberNames.ServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestUpdateExpertDesk.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ServiceRequestSpecificFieldsContainerExpertDesk_OutgoingRequestUpdateExpertDesk.toString(), servicerequestspecificfieldscontainerexpertdesk_outgoingrequestupdateexpertdesk.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return serviceRequestSpecificFieldsContainerExpertDeskMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final interfacerequests.proxies.ServiceRequestSpecificFieldsContainerExpertDesk that = (interfacerequests.proxies.ServiceRequestSpecificFieldsContainerExpertDesk) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "InterfaceRequests.ServiceRequestSpecificFieldsContainerExpertDesk";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
