// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package reporting.proxies;

public class ImpactFilter extends reporting.proxies.ReportFilter
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Reporting.ImpactFilter";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FilterType("FilterType"),
		ReadableString("ReadableString"),
		Editable("Editable"),
		IsDefault("IsDefault"),
		IsCopyOfDefault("IsCopyOfDefault"),
		FilterID("FilterID"),
		FilterDefinitionName("FilterDefinitionName"),
		ImpactFilter_Impacts("Reporting.ImpactFilter_Impacts"),
		ReportFilter_ReportSelect("Reporting.ReportFilter_ReportSelect"),
		ReportFilter_Definition("Reporting.ReportFilter_Definition"),
		ReportFilter_User("Reporting.ReportFilter_User");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ImpactFilter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Reporting.ImpactFilter"));
	}

	protected ImpactFilter(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject impactFilterMendixObject)
	{
		super(context, impactFilterMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Reporting.ImpactFilter", impactFilterMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Reporting.ImpactFilter");
	}

	/**
	 * @deprecated Use 'ImpactFilter.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static reporting.proxies.ImpactFilter initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return reporting.proxies.ImpactFilter.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static reporting.proxies.ImpactFilter initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new reporting.proxies.ImpactFilter(context, mendixObject);
	}

	public static reporting.proxies.ImpactFilter load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return reporting.proxies.ImpactFilter.initialize(context, mendixObject);
	}

	public static java.util.List<reporting.proxies.ImpactFilter> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<reporting.proxies.ImpactFilter> result = new java.util.ArrayList<reporting.proxies.ImpactFilter>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Reporting.ImpactFilter" + xpathConstraint))
			result.add(reporting.proxies.ImpactFilter.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of ImpactFilter_Impacts
	 */
	public final java.util.List<slm.proxies.Impact> getImpactFilter_Impacts() throws com.mendix.core.CoreException
	{
		return getImpactFilter_Impacts(getContext());
	}

	/**
	 * @param context
	 * @return value of ImpactFilter_Impacts
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<slm.proxies.Impact> getImpactFilter_Impacts(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<slm.proxies.Impact> result = new java.util.ArrayList<slm.proxies.Impact>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.ImpactFilter_Impacts.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(slm.proxies.Impact.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of ImpactFilter_Impacts
	 * @param impactfilter_impacts
	 */
	public final void setImpactFilter_Impacts(java.util.List<slm.proxies.Impact> impactfilter_impacts)
	{
		setImpactFilter_Impacts(getContext(), impactfilter_impacts);
	}

	/**
	 * Set value of ImpactFilter_Impacts
	 * @param context
	 * @param impactfilter_impacts
	 */
	public final void setImpactFilter_Impacts(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<slm.proxies.Impact> impactfilter_impacts)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (slm.proxies.Impact proxyObject : impactfilter_impacts)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.ImpactFilter_Impacts.toString(), identifiers);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final reporting.proxies.ImpactFilter that = (reporting.proxies.ImpactFilter) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Reporting.ImpactFilter";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
