// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package reporting.proxies;

public class ReportGroup
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reportGroupMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Reporting.ReportGroup";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		PeriodColumn("PeriodColumn"),
		TimePeriod("TimePeriod"),
		OQLJoinString("OQLJoinString"),
		OQLGroupString("OQLGroupString"),
		OQLSelectString("OQLSelectString"),
		OQLOrderByString("OQLOrderByString"),
		DrillDownOQL("DrillDownOQL"),
		DrillDownOQLEmpty("DrillDownOQLEmpty"),
		ReportGroup_ReportQuery("Reporting.ReportGroup_ReportQuery");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReportGroup(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Reporting.ReportGroup"));
	}

	protected ReportGroup(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reportGroupMendixObject)
	{
		if (reportGroupMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Reporting.ReportGroup", reportGroupMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Reporting.ReportGroup");

		this.reportGroupMendixObject = reportGroupMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ReportGroup.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static reporting.proxies.ReportGroup initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return reporting.proxies.ReportGroup.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static reporting.proxies.ReportGroup initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new reporting.proxies.ReportGroup(context, mendixObject);
	}

	public static reporting.proxies.ReportGroup load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return reporting.proxies.ReportGroup.initialize(context, mendixObject);
	}

	public static java.util.List<reporting.proxies.ReportGroup> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<reporting.proxies.ReportGroup> result = new java.util.ArrayList<reporting.proxies.ReportGroup>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Reporting.ReportGroup" + xpathConstraint))
			result.add(reporting.proxies.ReportGroup.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of PeriodColumn
	 */
	public final java.lang.String getPeriodColumn()
	{
		return getPeriodColumn(getContext());
	}

	/**
	 * @param context
	 * @return value of PeriodColumn
	 */
	public final java.lang.String getPeriodColumn(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PeriodColumn.toString());
	}

	/**
	 * Set value of PeriodColumn
	 * @param periodcolumn
	 */
	public final void setPeriodColumn(java.lang.String periodcolumn)
	{
		setPeriodColumn(getContext(), periodcolumn);
	}

	/**
	 * Set value of PeriodColumn
	 * @param context
	 * @param periodcolumn
	 */
	public final void setPeriodColumn(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String periodcolumn)
	{
		getMendixObject().setValue(context, MemberNames.PeriodColumn.toString(), periodcolumn);
	}

	/**
	 * Set value of TimePeriod
	 * @param timeperiod
	 */
	public final reporting.proxies.TimePeriodEnum getTimePeriod()
	{
		return getTimePeriod(getContext());
	}

	/**
	 * @param context
	 * @return value of TimePeriod
	 */
	public final reporting.proxies.TimePeriodEnum getTimePeriod(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TimePeriod.toString());
		if (obj == null)
			return null;

		return reporting.proxies.TimePeriodEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TimePeriod
	 * @param timeperiod
	 */
	public final void setTimePeriod(reporting.proxies.TimePeriodEnum timeperiod)
	{
		setTimePeriod(getContext(), timeperiod);
	}

	/**
	 * Set value of TimePeriod
	 * @param context
	 * @param timeperiod
	 */
	public final void setTimePeriod(com.mendix.systemwideinterfaces.core.IContext context, reporting.proxies.TimePeriodEnum timeperiod)
	{
		if (timeperiod != null)
			getMendixObject().setValue(context, MemberNames.TimePeriod.toString(), timeperiod.toString());
		else
			getMendixObject().setValue(context, MemberNames.TimePeriod.toString(), null);
	}

	/**
	 * @return value of OQLJoinString
	 */
	public final java.lang.String getOQLJoinString()
	{
		return getOQLJoinString(getContext());
	}

	/**
	 * @param context
	 * @return value of OQLJoinString
	 */
	public final java.lang.String getOQLJoinString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OQLJoinString.toString());
	}

	/**
	 * Set value of OQLJoinString
	 * @param oqljoinstring
	 */
	public final void setOQLJoinString(java.lang.String oqljoinstring)
	{
		setOQLJoinString(getContext(), oqljoinstring);
	}

	/**
	 * Set value of OQLJoinString
	 * @param context
	 * @param oqljoinstring
	 */
	public final void setOQLJoinString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String oqljoinstring)
	{
		getMendixObject().setValue(context, MemberNames.OQLJoinString.toString(), oqljoinstring);
	}

	/**
	 * @return value of OQLGroupString
	 */
	public final java.lang.String getOQLGroupString()
	{
		return getOQLGroupString(getContext());
	}

	/**
	 * @param context
	 * @return value of OQLGroupString
	 */
	public final java.lang.String getOQLGroupString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OQLGroupString.toString());
	}

	/**
	 * Set value of OQLGroupString
	 * @param oqlgroupstring
	 */
	public final void setOQLGroupString(java.lang.String oqlgroupstring)
	{
		setOQLGroupString(getContext(), oqlgroupstring);
	}

	/**
	 * Set value of OQLGroupString
	 * @param context
	 * @param oqlgroupstring
	 */
	public final void setOQLGroupString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String oqlgroupstring)
	{
		getMendixObject().setValue(context, MemberNames.OQLGroupString.toString(), oqlgroupstring);
	}

	/**
	 * @return value of OQLSelectString
	 */
	public final java.lang.String getOQLSelectString()
	{
		return getOQLSelectString(getContext());
	}

	/**
	 * @param context
	 * @return value of OQLSelectString
	 */
	public final java.lang.String getOQLSelectString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OQLSelectString.toString());
	}

	/**
	 * Set value of OQLSelectString
	 * @param oqlselectstring
	 */
	public final void setOQLSelectString(java.lang.String oqlselectstring)
	{
		setOQLSelectString(getContext(), oqlselectstring);
	}

	/**
	 * Set value of OQLSelectString
	 * @param context
	 * @param oqlselectstring
	 */
	public final void setOQLSelectString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String oqlselectstring)
	{
		getMendixObject().setValue(context, MemberNames.OQLSelectString.toString(), oqlselectstring);
	}

	/**
	 * @return value of OQLOrderByString
	 */
	public final java.lang.String getOQLOrderByString()
	{
		return getOQLOrderByString(getContext());
	}

	/**
	 * @param context
	 * @return value of OQLOrderByString
	 */
	public final java.lang.String getOQLOrderByString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OQLOrderByString.toString());
	}

	/**
	 * Set value of OQLOrderByString
	 * @param oqlorderbystring
	 */
	public final void setOQLOrderByString(java.lang.String oqlorderbystring)
	{
		setOQLOrderByString(getContext(), oqlorderbystring);
	}

	/**
	 * Set value of OQLOrderByString
	 * @param context
	 * @param oqlorderbystring
	 */
	public final void setOQLOrderByString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String oqlorderbystring)
	{
		getMendixObject().setValue(context, MemberNames.OQLOrderByString.toString(), oqlorderbystring);
	}

	/**
	 * @return value of DrillDownOQL
	 */
	public final java.lang.String getDrillDownOQL()
	{
		return getDrillDownOQL(getContext());
	}

	/**
	 * @param context
	 * @return value of DrillDownOQL
	 */
	public final java.lang.String getDrillDownOQL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DrillDownOQL.toString());
	}

	/**
	 * Set value of DrillDownOQL
	 * @param drilldownoql
	 */
	public final void setDrillDownOQL(java.lang.String drilldownoql)
	{
		setDrillDownOQL(getContext(), drilldownoql);
	}

	/**
	 * Set value of DrillDownOQL
	 * @param context
	 * @param drilldownoql
	 */
	public final void setDrillDownOQL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String drilldownoql)
	{
		getMendixObject().setValue(context, MemberNames.DrillDownOQL.toString(), drilldownoql);
	}

	/**
	 * @return value of DrillDownOQLEmpty
	 */
	public final java.lang.String getDrillDownOQLEmpty()
	{
		return getDrillDownOQLEmpty(getContext());
	}

	/**
	 * @param context
	 * @return value of DrillDownOQLEmpty
	 */
	public final java.lang.String getDrillDownOQLEmpty(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DrillDownOQLEmpty.toString());
	}

	/**
	 * Set value of DrillDownOQLEmpty
	 * @param drilldownoqlempty
	 */
	public final void setDrillDownOQLEmpty(java.lang.String drilldownoqlempty)
	{
		setDrillDownOQLEmpty(getContext(), drilldownoqlempty);
	}

	/**
	 * Set value of DrillDownOQLEmpty
	 * @param context
	 * @param drilldownoqlempty
	 */
	public final void setDrillDownOQLEmpty(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String drilldownoqlempty)
	{
		getMendixObject().setValue(context, MemberNames.DrillDownOQLEmpty.toString(), drilldownoqlempty);
	}

	/**
	 * @return value of ReportGroup_ReportQuery
	 */
	public final reporting.proxies.ReportQuery getReportGroup_ReportQuery() throws com.mendix.core.CoreException
	{
		return getReportGroup_ReportQuery(getContext());
	}

	/**
	 * @param context
	 * @return value of ReportGroup_ReportQuery
	 */
	public final reporting.proxies.ReportQuery getReportGroup_ReportQuery(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		reporting.proxies.ReportQuery result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReportGroup_ReportQuery.toString());
		if (identifier != null)
			result = reporting.proxies.ReportQuery.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ReportGroup_ReportQuery
	 * @param reportgroup_reportquery
	 */
	public final void setReportGroup_ReportQuery(reporting.proxies.ReportQuery reportgroup_reportquery)
	{
		setReportGroup_ReportQuery(getContext(), reportgroup_reportquery);
	}

	/**
	 * Set value of ReportGroup_ReportQuery
	 * @param context
	 * @param reportgroup_reportquery
	 */
	public final void setReportGroup_ReportQuery(com.mendix.systemwideinterfaces.core.IContext context, reporting.proxies.ReportQuery reportgroup_reportquery)
	{
		if (reportgroup_reportquery == null)
			getMendixObject().setValue(context, MemberNames.ReportGroup_ReportQuery.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ReportGroup_ReportQuery.toString(), reportgroup_reportquery.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reportGroupMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final reporting.proxies.ReportGroup that = (reporting.proxies.ReportGroup) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Reporting.ReportGroup";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
