// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package process.proxies;

public class CheckTaskCounter
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject checkTaskCounterMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Process.CheckTaskCounter";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CheckTaskCounter_TaskCounter("Process.CheckTaskCounter_TaskCounter");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CheckTaskCounter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Process.CheckTaskCounter"));
	}

	protected CheckTaskCounter(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject checkTaskCounterMendixObject)
	{
		if (checkTaskCounterMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Process.CheckTaskCounter", checkTaskCounterMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Process.CheckTaskCounter");

		this.checkTaskCounterMendixObject = checkTaskCounterMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CheckTaskCounter.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static process.proxies.CheckTaskCounter initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return process.proxies.CheckTaskCounter.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static process.proxies.CheckTaskCounter initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new process.proxies.CheckTaskCounter(context, mendixObject);
	}

	public static process.proxies.CheckTaskCounter load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return process.proxies.CheckTaskCounter.initialize(context, mendixObject);
	}

	public static java.util.List<process.proxies.CheckTaskCounter> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<process.proxies.CheckTaskCounter> result = new java.util.ArrayList<process.proxies.CheckTaskCounter>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Process.CheckTaskCounter" + xpathConstraint))
			result.add(process.proxies.CheckTaskCounter.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CheckTaskCounter_TaskCounter
	 */
	public final process.proxies.TaskCounter getCheckTaskCounter_TaskCounter() throws com.mendix.core.CoreException
	{
		return getCheckTaskCounter_TaskCounter(getContext());
	}

	/**
	 * @param context
	 * @return value of CheckTaskCounter_TaskCounter
	 */
	public final process.proxies.TaskCounter getCheckTaskCounter_TaskCounter(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		process.proxies.TaskCounter result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CheckTaskCounter_TaskCounter.toString());
		if (identifier != null)
			result = process.proxies.TaskCounter.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CheckTaskCounter_TaskCounter
	 * @param checktaskcounter_taskcounter
	 */
	public final void setCheckTaskCounter_TaskCounter(process.proxies.TaskCounter checktaskcounter_taskcounter)
	{
		setCheckTaskCounter_TaskCounter(getContext(), checktaskcounter_taskcounter);
	}

	/**
	 * Set value of CheckTaskCounter_TaskCounter
	 * @param context
	 * @param checktaskcounter_taskcounter
	 */
	public final void setCheckTaskCounter_TaskCounter(com.mendix.systemwideinterfaces.core.IContext context, process.proxies.TaskCounter checktaskcounter_taskcounter)
	{
		if (checktaskcounter_taskcounter == null)
			getMendixObject().setValue(context, MemberNames.CheckTaskCounter_TaskCounter.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CheckTaskCounter_TaskCounter.toString(), checktaskcounter_taskcounter.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return checkTaskCounterMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final process.proxies.CheckTaskCounter that = (process.proxies.CheckTaskCounter) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Process.CheckTaskCounter";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
