// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package process.proxies;

public class Dummy_Matching_View
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dummy_Matching_ViewMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Process.Dummy_Matching_View";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CorrelationMessage("CorrelationMessage"),
		ShowMessageField("ShowMessageField"),
		UserHasWritePermissions("UserHasWritePermissions"),
		Dummy_Matching_View_Request("Process.Dummy_Matching_View_Request"),
		Dummy_Matching_View_Matching_Requests("Process.Dummy_Matching_View_Matching_Requests");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Dummy_Matching_View(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Process.Dummy_Matching_View"));
	}

	protected Dummy_Matching_View(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dummy_Matching_ViewMendixObject)
	{
		if (dummy_Matching_ViewMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Process.Dummy_Matching_View", dummy_Matching_ViewMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Process.Dummy_Matching_View");

		this.dummy_Matching_ViewMendixObject = dummy_Matching_ViewMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Dummy_Matching_View.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static process.proxies.Dummy_Matching_View initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return process.proxies.Dummy_Matching_View.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static process.proxies.Dummy_Matching_View initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new process.proxies.Dummy_Matching_View(context, mendixObject);
	}

	public static process.proxies.Dummy_Matching_View load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return process.proxies.Dummy_Matching_View.initialize(context, mendixObject);
	}

	public static java.util.List<process.proxies.Dummy_Matching_View> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<process.proxies.Dummy_Matching_View> result = new java.util.ArrayList<process.proxies.Dummy_Matching_View>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Process.Dummy_Matching_View" + xpathConstraint))
			result.add(process.proxies.Dummy_Matching_View.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CorrelationMessage
	 */
	public final java.lang.String getCorrelationMessage()
	{
		return getCorrelationMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of CorrelationMessage
	 */
	public final java.lang.String getCorrelationMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CorrelationMessage.toString());
	}

	/**
	 * Set value of CorrelationMessage
	 * @param correlationmessage
	 */
	public final void setCorrelationMessage(java.lang.String correlationmessage)
	{
		setCorrelationMessage(getContext(), correlationmessage);
	}

	/**
	 * Set value of CorrelationMessage
	 * @param context
	 * @param correlationmessage
	 */
	public final void setCorrelationMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String correlationmessage)
	{
		getMendixObject().setValue(context, MemberNames.CorrelationMessage.toString(), correlationmessage);
	}

	/**
	 * @return value of ShowMessageField
	 */
	public final java.lang.Boolean getShowMessageField()
	{
		return getShowMessageField(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowMessageField
	 */
	public final java.lang.Boolean getShowMessageField(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowMessageField.toString());
	}

	/**
	 * Set value of ShowMessageField
	 * @param showmessagefield
	 */
	public final void setShowMessageField(java.lang.Boolean showmessagefield)
	{
		setShowMessageField(getContext(), showmessagefield);
	}

	/**
	 * Set value of ShowMessageField
	 * @param context
	 * @param showmessagefield
	 */
	public final void setShowMessageField(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showmessagefield)
	{
		getMendixObject().setValue(context, MemberNames.ShowMessageField.toString(), showmessagefield);
	}

	/**
	 * @return value of UserHasWritePermissions
	 */
	public final java.lang.Boolean getUserHasWritePermissions()
	{
		return getUserHasWritePermissions(getContext());
	}

	/**
	 * @param context
	 * @return value of UserHasWritePermissions
	 */
	public final java.lang.Boolean getUserHasWritePermissions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UserHasWritePermissions.toString());
	}

	/**
	 * Set value of UserHasWritePermissions
	 * @param userhaswritepermissions
	 */
	public final void setUserHasWritePermissions(java.lang.Boolean userhaswritepermissions)
	{
		setUserHasWritePermissions(getContext(), userhaswritepermissions);
	}

	/**
	 * Set value of UserHasWritePermissions
	 * @param context
	 * @param userhaswritepermissions
	 */
	public final void setUserHasWritePermissions(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean userhaswritepermissions)
	{
		getMendixObject().setValue(context, MemberNames.UserHasWritePermissions.toString(), userhaswritepermissions);
	}

	/**
	 * @return value of Dummy_Matching_View_Request
	 */
	public final process.proxies.Request getDummy_Matching_View_Request() throws com.mendix.core.CoreException
	{
		return getDummy_Matching_View_Request(getContext());
	}

	/**
	 * @param context
	 * @return value of Dummy_Matching_View_Request
	 */
	public final process.proxies.Request getDummy_Matching_View_Request(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		process.proxies.Request result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Dummy_Matching_View_Request.toString());
		if (identifier != null)
			result = process.proxies.Request.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Dummy_Matching_View_Request
	 * @param dummy_matching_view_request
	 */
	public final void setDummy_Matching_View_Request(process.proxies.Request dummy_matching_view_request)
	{
		setDummy_Matching_View_Request(getContext(), dummy_matching_view_request);
	}

	/**
	 * Set value of Dummy_Matching_View_Request
	 * @param context
	 * @param dummy_matching_view_request
	 */
	public final void setDummy_Matching_View_Request(com.mendix.systemwideinterfaces.core.IContext context, process.proxies.Request dummy_matching_view_request)
	{
		if (dummy_matching_view_request == null)
			getMendixObject().setValue(context, MemberNames.Dummy_Matching_View_Request.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Dummy_Matching_View_Request.toString(), dummy_matching_view_request.getMendixObject().getId());
	}

	/**
	 * @return value of Dummy_Matching_View_Matching_Requests
	 */
	public final java.util.List<process.proxies.Request> getDummy_Matching_View_Matching_Requests() throws com.mendix.core.CoreException
	{
		return getDummy_Matching_View_Matching_Requests(getContext());
	}

	/**
	 * @param context
	 * @return value of Dummy_Matching_View_Matching_Requests
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<process.proxies.Request> getDummy_Matching_View_Matching_Requests(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<process.proxies.Request> result = new java.util.ArrayList<process.proxies.Request>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Dummy_Matching_View_Matching_Requests.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(process.proxies.Request.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Dummy_Matching_View_Matching_Requests
	 * @param dummy_matching_view_matching_requests
	 */
	public final void setDummy_Matching_View_Matching_Requests(java.util.List<process.proxies.Request> dummy_matching_view_matching_requests)
	{
		setDummy_Matching_View_Matching_Requests(getContext(), dummy_matching_view_matching_requests);
	}

	/**
	 * Set value of Dummy_Matching_View_Matching_Requests
	 * @param context
	 * @param dummy_matching_view_matching_requests
	 */
	public final void setDummy_Matching_View_Matching_Requests(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<process.proxies.Request> dummy_matching_view_matching_requests)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (process.proxies.Request proxyObject : dummy_matching_view_matching_requests)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Dummy_Matching_View_Matching_Requests.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dummy_Matching_ViewMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final process.proxies.Dummy_Matching_View that = (process.proxies.Dummy_Matching_View) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Process.Dummy_Matching_View";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
