// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package process.proxies;

public enum FirstLine
{
	FirstLine(new java.lang.String[][] { new java.lang.String[] { "en_US", "First Line" }, new java.lang.String[] { "nl_NL", "Eerste lijn" }, new java.lang.String[] { "de_DE", "Erste Linie" } }),
	Not_FirstLine(new java.lang.String[][] { new java.lang.String[] { "en_US", "Not First Line" }, new java.lang.String[] { "nl_NL", "Niet eerste lijn" }, new java.lang.String[] { "de_DE", "Nicht erster Linie" } }),
	Unkown(new java.lang.String[][] { new java.lang.String[] { "en_US", "Unknown" }, new java.lang.String[] { "nl_NL", "Onbekend" }, new java.lang.String[] { "de_DE", "Unbekannt" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private FirstLine(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
