// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package process.proxies;

public enum RequiredFieldsForProcess
{
	ActualEndTime(new java.lang.String[][] { new java.lang.String[] { "en_US", "Actual End Time" }, new java.lang.String[] { "nl_NL", "Werkelijke eindtijd" }, new java.lang.String[] { "de_DE", "Tatsächliche Endzeit" } }),
	Satisfaction(new java.lang.String[][] { new java.lang.String[] { "en_US", "Satisfaction" }, new java.lang.String[] { "nl_NL", "Tevredenheid" }, new java.lang.String[] { "de_DE", "Zufriedenheit" } }),
	SolutionDescription(new java.lang.String[][] { new java.lang.String[] { "en_US", "Solution Description" }, new java.lang.String[] { "nl_NL", "Oplosomschrijving" }, new java.lang.String[] { "de_DE", "Beschreibung Lösung" } }),
	ClosureCategory(new java.lang.String[][] { new java.lang.String[] { "en_US", "Closure Category" }, new java.lang.String[] { "nl_NL", "Afsluitcategorie" }, new java.lang.String[] { "de_DE", "Abschlusskategorie" } }),
	OpeningCategory(new java.lang.String[][] { new java.lang.String[] { "en_US", "Subject" }, new java.lang.String[] { "nl_NL", "Subject" }, new java.lang.String[] { "de_DE", "Offene Kategorie" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private RequiredFieldsForProcess(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
