// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package process.proxies;

public class RequestSnapShot
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject requestSnapShotMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Process.RequestSnapShot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ShortDescription("ShortDescription"),
		ShortDescriptionChanged("ShortDescriptionChanged"),
		DetailDescription("DetailDescription"),
		DetailDescriptionChanged("DetailDescriptionChanged"),
		DetailDescriptionNoHTML("DetailDescriptionNoHTML"),
		DetailDescriptionNoHTMLChanged("DetailDescriptionNoHTMLChanged"),
		SolutionDescription("SolutionDescription"),
		SolutionDescriptionChanged("SolutionDescriptionChanged"),
		ActualEndTime("ActualEndTime"),
		ActualEndTimeChanged("ActualEndTimeChanged"),
		CustomerSatisfaction("CustomerSatisfaction"),
		CustomerSatisfactionChanged("CustomerSatisfactionChanged"),
		ScheduledStart("ScheduledStart"),
		ScheduledStartChanged("ScheduledStartChanged"),
		ScheduledEnd("ScheduledEnd"),
		ScheduledEndChanged("ScheduledEndChanged"),
		WishDateStart("WishDateStart"),
		WishDateStartChanged("WishDateStartChanged"),
		WishDateEnd("WishDateEnd"),
		WishDateEndChanged("WishDateEndChanged"),
		OpeningCategoryChanged("OpeningCategoryChanged"),
		ClosureCategoryChanged("ClosureCategoryChanged"),
		RequestEvent_RequestSnapShot("Process.RequestEvent_RequestSnapShot"),
		RequestSnapShot_OpeningCategory("Process.RequestSnapShot_OpeningCategory"),
		RequestSnapShot_ClosureCategory("Process.RequestSnapShot_ClosureCategory");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RequestSnapShot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Process.RequestSnapShot"));
	}

	protected RequestSnapShot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject requestSnapShotMendixObject)
	{
		if (requestSnapShotMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Process.RequestSnapShot", requestSnapShotMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Process.RequestSnapShot");

		this.requestSnapShotMendixObject = requestSnapShotMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'RequestSnapShot.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static process.proxies.RequestSnapShot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return process.proxies.RequestSnapShot.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static process.proxies.RequestSnapShot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("Process.ChangeSnapShot", mendixObject.getType()))
			return process.proxies.ChangeSnapShot.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("Process.DeliverySnapShot", mendixObject.getType()))
			return process.proxies.DeliverySnapShot.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("Process.IncidentSnapShot", mendixObject.getType()))
			return process.proxies.IncidentSnapShot.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("Process.ProblemSnapShot", mendixObject.getType()))
			return process.proxies.ProblemSnapShot.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("Process.ServiceRequestSnapShot", mendixObject.getType()))
			return process.proxies.ServiceRequestSnapShot.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("Process.TaskSnapShot", mendixObject.getType()))
			return process.proxies.TaskSnapShot.initialize(context, mendixObject);

		return new process.proxies.RequestSnapShot(context, mendixObject);
	}

	public static process.proxies.RequestSnapShot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return process.proxies.RequestSnapShot.initialize(context, mendixObject);
	}

	public static java.util.List<? extends process.proxies.RequestSnapShot> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<process.proxies.RequestSnapShot> result = new java.util.ArrayList<process.proxies.RequestSnapShot>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Process.RequestSnapShot" + xpathConstraint))
			result.add(process.proxies.RequestSnapShot.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ShortDescription
	 */
	public final java.lang.String getShortDescription()
	{
		return getShortDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of ShortDescription
	 */
	public final java.lang.String getShortDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ShortDescription.toString());
	}

	/**
	 * Set value of ShortDescription
	 * @param shortdescription
	 */
	public final void setShortDescription(java.lang.String shortdescription)
	{
		setShortDescription(getContext(), shortdescription);
	}

	/**
	 * Set value of ShortDescription
	 * @param context
	 * @param shortdescription
	 */
	public final void setShortDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String shortdescription)
	{
		getMendixObject().setValue(context, MemberNames.ShortDescription.toString(), shortdescription);
	}

	/**
	 * @return value of ShortDescriptionChanged
	 */
	public final java.lang.Boolean getShortDescriptionChanged()
	{
		return getShortDescriptionChanged(getContext());
	}

	/**
	 * @param context
	 * @return value of ShortDescriptionChanged
	 */
	public final java.lang.Boolean getShortDescriptionChanged(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShortDescriptionChanged.toString());
	}

	/**
	 * Set value of ShortDescriptionChanged
	 * @param shortdescriptionchanged
	 */
	public final void setShortDescriptionChanged(java.lang.Boolean shortdescriptionchanged)
	{
		setShortDescriptionChanged(getContext(), shortdescriptionchanged);
	}

	/**
	 * Set value of ShortDescriptionChanged
	 * @param context
	 * @param shortdescriptionchanged
	 */
	public final void setShortDescriptionChanged(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean shortdescriptionchanged)
	{
		getMendixObject().setValue(context, MemberNames.ShortDescriptionChanged.toString(), shortdescriptionchanged);
	}

	/**
	 * @return value of DetailDescription
	 */
	public final java.lang.String getDetailDescription()
	{
		return getDetailDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of DetailDescription
	 */
	public final java.lang.String getDetailDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DetailDescription.toString());
	}

	/**
	 * Set value of DetailDescription
	 * @param detaildescription
	 */
	public final void setDetailDescription(java.lang.String detaildescription)
	{
		setDetailDescription(getContext(), detaildescription);
	}

	/**
	 * Set value of DetailDescription
	 * @param context
	 * @param detaildescription
	 */
	public final void setDetailDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String detaildescription)
	{
		getMendixObject().setValue(context, MemberNames.DetailDescription.toString(), detaildescription);
	}

	/**
	 * @return value of DetailDescriptionChanged
	 */
	public final java.lang.Boolean getDetailDescriptionChanged()
	{
		return getDetailDescriptionChanged(getContext());
	}

	/**
	 * @param context
	 * @return value of DetailDescriptionChanged
	 */
	public final java.lang.Boolean getDetailDescriptionChanged(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.DetailDescriptionChanged.toString());
	}

	/**
	 * Set value of DetailDescriptionChanged
	 * @param detaildescriptionchanged
	 */
	public final void setDetailDescriptionChanged(java.lang.Boolean detaildescriptionchanged)
	{
		setDetailDescriptionChanged(getContext(), detaildescriptionchanged);
	}

	/**
	 * Set value of DetailDescriptionChanged
	 * @param context
	 * @param detaildescriptionchanged
	 */
	public final void setDetailDescriptionChanged(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean detaildescriptionchanged)
	{
		getMendixObject().setValue(context, MemberNames.DetailDescriptionChanged.toString(), detaildescriptionchanged);
	}

	/**
	 * @return value of DetailDescriptionNoHTML
	 */
	public final java.lang.String getDetailDescriptionNoHTML()
	{
		return getDetailDescriptionNoHTML(getContext());
	}

	/**
	 * @param context
	 * @return value of DetailDescriptionNoHTML
	 */
	public final java.lang.String getDetailDescriptionNoHTML(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DetailDescriptionNoHTML.toString());
	}

	/**
	 * Set value of DetailDescriptionNoHTML
	 * @param detaildescriptionnohtml
	 */
	public final void setDetailDescriptionNoHTML(java.lang.String detaildescriptionnohtml)
	{
		setDetailDescriptionNoHTML(getContext(), detaildescriptionnohtml);
	}

	/**
	 * Set value of DetailDescriptionNoHTML
	 * @param context
	 * @param detaildescriptionnohtml
	 */
	public final void setDetailDescriptionNoHTML(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String detaildescriptionnohtml)
	{
		getMendixObject().setValue(context, MemberNames.DetailDescriptionNoHTML.toString(), detaildescriptionnohtml);
	}

	/**
	 * @return value of DetailDescriptionNoHTMLChanged
	 */
	public final java.lang.Boolean getDetailDescriptionNoHTMLChanged()
	{
		return getDetailDescriptionNoHTMLChanged(getContext());
	}

	/**
	 * @param context
	 * @return value of DetailDescriptionNoHTMLChanged
	 */
	public final java.lang.Boolean getDetailDescriptionNoHTMLChanged(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.DetailDescriptionNoHTMLChanged.toString());
	}

	/**
	 * Set value of DetailDescriptionNoHTMLChanged
	 * @param detaildescriptionnohtmlchanged
	 */
	public final void setDetailDescriptionNoHTMLChanged(java.lang.Boolean detaildescriptionnohtmlchanged)
	{
		setDetailDescriptionNoHTMLChanged(getContext(), detaildescriptionnohtmlchanged);
	}

	/**
	 * Set value of DetailDescriptionNoHTMLChanged
	 * @param context
	 * @param detaildescriptionnohtmlchanged
	 */
	public final void setDetailDescriptionNoHTMLChanged(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean detaildescriptionnohtmlchanged)
	{
		getMendixObject().setValue(context, MemberNames.DetailDescriptionNoHTMLChanged.toString(), detaildescriptionnohtmlchanged);
	}

	/**
	 * @return value of SolutionDescription
	 */
	public final java.lang.String getSolutionDescription()
	{
		return getSolutionDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of SolutionDescription
	 */
	public final java.lang.String getSolutionDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SolutionDescription.toString());
	}

	/**
	 * Set value of SolutionDescription
	 * @param solutiondescription
	 */
	public final void setSolutionDescription(java.lang.String solutiondescription)
	{
		setSolutionDescription(getContext(), solutiondescription);
	}

	/**
	 * Set value of SolutionDescription
	 * @param context
	 * @param solutiondescription
	 */
	public final void setSolutionDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String solutiondescription)
	{
		getMendixObject().setValue(context, MemberNames.SolutionDescription.toString(), solutiondescription);
	}

	/**
	 * @return value of SolutionDescriptionChanged
	 */
	public final java.lang.Boolean getSolutionDescriptionChanged()
	{
		return getSolutionDescriptionChanged(getContext());
	}

	/**
	 * @param context
	 * @return value of SolutionDescriptionChanged
	 */
	public final java.lang.Boolean getSolutionDescriptionChanged(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SolutionDescriptionChanged.toString());
	}

	/**
	 * Set value of SolutionDescriptionChanged
	 * @param solutiondescriptionchanged
	 */
	public final void setSolutionDescriptionChanged(java.lang.Boolean solutiondescriptionchanged)
	{
		setSolutionDescriptionChanged(getContext(), solutiondescriptionchanged);
	}

	/**
	 * Set value of SolutionDescriptionChanged
	 * @param context
	 * @param solutiondescriptionchanged
	 */
	public final void setSolutionDescriptionChanged(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean solutiondescriptionchanged)
	{
		getMendixObject().setValue(context, MemberNames.SolutionDescriptionChanged.toString(), solutiondescriptionchanged);
	}

	/**
	 * @return value of ActualEndTime
	 */
	public final java.util.Date getActualEndTime()
	{
		return getActualEndTime(getContext());
	}

	/**
	 * @param context
	 * @return value of ActualEndTime
	 */
	public final java.util.Date getActualEndTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ActualEndTime.toString());
	}

	/**
	 * Set value of ActualEndTime
	 * @param actualendtime
	 */
	public final void setActualEndTime(java.util.Date actualendtime)
	{
		setActualEndTime(getContext(), actualendtime);
	}

	/**
	 * Set value of ActualEndTime
	 * @param context
	 * @param actualendtime
	 */
	public final void setActualEndTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date actualendtime)
	{
		getMendixObject().setValue(context, MemberNames.ActualEndTime.toString(), actualendtime);
	}

	/**
	 * @return value of ActualEndTimeChanged
	 */
	public final java.lang.Boolean getActualEndTimeChanged()
	{
		return getActualEndTimeChanged(getContext());
	}

	/**
	 * @param context
	 * @return value of ActualEndTimeChanged
	 */
	public final java.lang.Boolean getActualEndTimeChanged(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ActualEndTimeChanged.toString());
	}

	/**
	 * Set value of ActualEndTimeChanged
	 * @param actualendtimechanged
	 */
	public final void setActualEndTimeChanged(java.lang.Boolean actualendtimechanged)
	{
		setActualEndTimeChanged(getContext(), actualendtimechanged);
	}

	/**
	 * Set value of ActualEndTimeChanged
	 * @param context
	 * @param actualendtimechanged
	 */
	public final void setActualEndTimeChanged(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean actualendtimechanged)
	{
		getMendixObject().setValue(context, MemberNames.ActualEndTimeChanged.toString(), actualendtimechanged);
	}

	/**
	 * Set value of CustomerSatisfaction
	 * @param customersatisfaction
	 */
	public final process.proxies.ProcessSatisfaction getCustomerSatisfaction()
	{
		return getCustomerSatisfaction(getContext());
	}

	/**
	 * @param context
	 * @return value of CustomerSatisfaction
	 */
	public final process.proxies.ProcessSatisfaction getCustomerSatisfaction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.CustomerSatisfaction.toString());
		if (obj == null)
			return null;

		return process.proxies.ProcessSatisfaction.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of CustomerSatisfaction
	 * @param customersatisfaction
	 */
	public final void setCustomerSatisfaction(process.proxies.ProcessSatisfaction customersatisfaction)
	{
		setCustomerSatisfaction(getContext(), customersatisfaction);
	}

	/**
	 * Set value of CustomerSatisfaction
	 * @param context
	 * @param customersatisfaction
	 */
	public final void setCustomerSatisfaction(com.mendix.systemwideinterfaces.core.IContext context, process.proxies.ProcessSatisfaction customersatisfaction)
	{
		if (customersatisfaction != null)
			getMendixObject().setValue(context, MemberNames.CustomerSatisfaction.toString(), customersatisfaction.toString());
		else
			getMendixObject().setValue(context, MemberNames.CustomerSatisfaction.toString(), null);
	}

	/**
	 * @return value of CustomerSatisfactionChanged
	 */
	public final java.lang.Boolean getCustomerSatisfactionChanged()
	{
		return getCustomerSatisfactionChanged(getContext());
	}

	/**
	 * @param context
	 * @return value of CustomerSatisfactionChanged
	 */
	public final java.lang.Boolean getCustomerSatisfactionChanged(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CustomerSatisfactionChanged.toString());
	}

	/**
	 * Set value of CustomerSatisfactionChanged
	 * @param customersatisfactionchanged
	 */
	public final void setCustomerSatisfactionChanged(java.lang.Boolean customersatisfactionchanged)
	{
		setCustomerSatisfactionChanged(getContext(), customersatisfactionchanged);
	}

	/**
	 * Set value of CustomerSatisfactionChanged
	 * @param context
	 * @param customersatisfactionchanged
	 */
	public final void setCustomerSatisfactionChanged(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean customersatisfactionchanged)
	{
		getMendixObject().setValue(context, MemberNames.CustomerSatisfactionChanged.toString(), customersatisfactionchanged);
	}

	/**
	 * @return value of ScheduledStart
	 */
	public final java.util.Date getScheduledStart()
	{
		return getScheduledStart(getContext());
	}

	/**
	 * @param context
	 * @return value of ScheduledStart
	 */
	public final java.util.Date getScheduledStart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ScheduledStart.toString());
	}

	/**
	 * Set value of ScheduledStart
	 * @param scheduledstart
	 */
	public final void setScheduledStart(java.util.Date scheduledstart)
	{
		setScheduledStart(getContext(), scheduledstart);
	}

	/**
	 * Set value of ScheduledStart
	 * @param context
	 * @param scheduledstart
	 */
	public final void setScheduledStart(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date scheduledstart)
	{
		getMendixObject().setValue(context, MemberNames.ScheduledStart.toString(), scheduledstart);
	}

	/**
	 * @return value of ScheduledStartChanged
	 */
	public final java.lang.Boolean getScheduledStartChanged()
	{
		return getScheduledStartChanged(getContext());
	}

	/**
	 * @param context
	 * @return value of ScheduledStartChanged
	 */
	public final java.lang.Boolean getScheduledStartChanged(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ScheduledStartChanged.toString());
	}

	/**
	 * Set value of ScheduledStartChanged
	 * @param scheduledstartchanged
	 */
	public final void setScheduledStartChanged(java.lang.Boolean scheduledstartchanged)
	{
		setScheduledStartChanged(getContext(), scheduledstartchanged);
	}

	/**
	 * Set value of ScheduledStartChanged
	 * @param context
	 * @param scheduledstartchanged
	 */
	public final void setScheduledStartChanged(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean scheduledstartchanged)
	{
		getMendixObject().setValue(context, MemberNames.ScheduledStartChanged.toString(), scheduledstartchanged);
	}

	/**
	 * @return value of ScheduledEnd
	 */
	public final java.util.Date getScheduledEnd()
	{
		return getScheduledEnd(getContext());
	}

	/**
	 * @param context
	 * @return value of ScheduledEnd
	 */
	public final java.util.Date getScheduledEnd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ScheduledEnd.toString());
	}

	/**
	 * Set value of ScheduledEnd
	 * @param scheduledend
	 */
	public final void setScheduledEnd(java.util.Date scheduledend)
	{
		setScheduledEnd(getContext(), scheduledend);
	}

	/**
	 * Set value of ScheduledEnd
	 * @param context
	 * @param scheduledend
	 */
	public final void setScheduledEnd(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date scheduledend)
	{
		getMendixObject().setValue(context, MemberNames.ScheduledEnd.toString(), scheduledend);
	}

	/**
	 * @return value of ScheduledEndChanged
	 */
	public final java.lang.Boolean getScheduledEndChanged()
	{
		return getScheduledEndChanged(getContext());
	}

	/**
	 * @param context
	 * @return value of ScheduledEndChanged
	 */
	public final java.lang.Boolean getScheduledEndChanged(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ScheduledEndChanged.toString());
	}

	/**
	 * Set value of ScheduledEndChanged
	 * @param scheduledendchanged
	 */
	public final void setScheduledEndChanged(java.lang.Boolean scheduledendchanged)
	{
		setScheduledEndChanged(getContext(), scheduledendchanged);
	}

	/**
	 * Set value of ScheduledEndChanged
	 * @param context
	 * @param scheduledendchanged
	 */
	public final void setScheduledEndChanged(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean scheduledendchanged)
	{
		getMendixObject().setValue(context, MemberNames.ScheduledEndChanged.toString(), scheduledendchanged);
	}

	/**
	 * @return value of WishDateStart
	 */
	public final java.util.Date getWishDateStart()
	{
		return getWishDateStart(getContext());
	}

	/**
	 * @param context
	 * @return value of WishDateStart
	 */
	public final java.util.Date getWishDateStart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.WishDateStart.toString());
	}

	/**
	 * Set value of WishDateStart
	 * @param wishdatestart
	 */
	public final void setWishDateStart(java.util.Date wishdatestart)
	{
		setWishDateStart(getContext(), wishdatestart);
	}

	/**
	 * Set value of WishDateStart
	 * @param context
	 * @param wishdatestart
	 */
	public final void setWishDateStart(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date wishdatestart)
	{
		getMendixObject().setValue(context, MemberNames.WishDateStart.toString(), wishdatestart);
	}

	/**
	 * @return value of WishDateStartChanged
	 */
	public final java.lang.Boolean getWishDateStartChanged()
	{
		return getWishDateStartChanged(getContext());
	}

	/**
	 * @param context
	 * @return value of WishDateStartChanged
	 */
	public final java.lang.Boolean getWishDateStartChanged(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.WishDateStartChanged.toString());
	}

	/**
	 * Set value of WishDateStartChanged
	 * @param wishdatestartchanged
	 */
	public final void setWishDateStartChanged(java.lang.Boolean wishdatestartchanged)
	{
		setWishDateStartChanged(getContext(), wishdatestartchanged);
	}

	/**
	 * Set value of WishDateStartChanged
	 * @param context
	 * @param wishdatestartchanged
	 */
	public final void setWishDateStartChanged(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean wishdatestartchanged)
	{
		getMendixObject().setValue(context, MemberNames.WishDateStartChanged.toString(), wishdatestartchanged);
	}

	/**
	 * @return value of WishDateEnd
	 */
	public final java.util.Date getWishDateEnd()
	{
		return getWishDateEnd(getContext());
	}

	/**
	 * @param context
	 * @return value of WishDateEnd
	 */
	public final java.util.Date getWishDateEnd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.WishDateEnd.toString());
	}

	/**
	 * Set value of WishDateEnd
	 * @param wishdateend
	 */
	public final void setWishDateEnd(java.util.Date wishdateend)
	{
		setWishDateEnd(getContext(), wishdateend);
	}

	/**
	 * Set value of WishDateEnd
	 * @param context
	 * @param wishdateend
	 */
	public final void setWishDateEnd(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date wishdateend)
	{
		getMendixObject().setValue(context, MemberNames.WishDateEnd.toString(), wishdateend);
	}

	/**
	 * @return value of WishDateEndChanged
	 */
	public final java.lang.Boolean getWishDateEndChanged()
	{
		return getWishDateEndChanged(getContext());
	}

	/**
	 * @param context
	 * @return value of WishDateEndChanged
	 */
	public final java.lang.Boolean getWishDateEndChanged(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.WishDateEndChanged.toString());
	}

	/**
	 * Set value of WishDateEndChanged
	 * @param wishdateendchanged
	 */
	public final void setWishDateEndChanged(java.lang.Boolean wishdateendchanged)
	{
		setWishDateEndChanged(getContext(), wishdateendchanged);
	}

	/**
	 * Set value of WishDateEndChanged
	 * @param context
	 * @param wishdateendchanged
	 */
	public final void setWishDateEndChanged(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean wishdateendchanged)
	{
		getMendixObject().setValue(context, MemberNames.WishDateEndChanged.toString(), wishdateendchanged);
	}

	/**
	 * @return value of OpeningCategoryChanged
	 */
	public final java.lang.Boolean getOpeningCategoryChanged()
	{
		return getOpeningCategoryChanged(getContext());
	}

	/**
	 * @param context
	 * @return value of OpeningCategoryChanged
	 */
	public final java.lang.Boolean getOpeningCategoryChanged(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.OpeningCategoryChanged.toString());
	}

	/**
	 * Set value of OpeningCategoryChanged
	 * @param openingcategorychanged
	 */
	public final void setOpeningCategoryChanged(java.lang.Boolean openingcategorychanged)
	{
		setOpeningCategoryChanged(getContext(), openingcategorychanged);
	}

	/**
	 * Set value of OpeningCategoryChanged
	 * @param context
	 * @param openingcategorychanged
	 */
	public final void setOpeningCategoryChanged(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean openingcategorychanged)
	{
		getMendixObject().setValue(context, MemberNames.OpeningCategoryChanged.toString(), openingcategorychanged);
	}

	/**
	 * @return value of ClosureCategoryChanged
	 */
	public final java.lang.Boolean getClosureCategoryChanged()
	{
		return getClosureCategoryChanged(getContext());
	}

	/**
	 * @param context
	 * @return value of ClosureCategoryChanged
	 */
	public final java.lang.Boolean getClosureCategoryChanged(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ClosureCategoryChanged.toString());
	}

	/**
	 * Set value of ClosureCategoryChanged
	 * @param closurecategorychanged
	 */
	public final void setClosureCategoryChanged(java.lang.Boolean closurecategorychanged)
	{
		setClosureCategoryChanged(getContext(), closurecategorychanged);
	}

	/**
	 * Set value of ClosureCategoryChanged
	 * @param context
	 * @param closurecategorychanged
	 */
	public final void setClosureCategoryChanged(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean closurecategorychanged)
	{
		getMendixObject().setValue(context, MemberNames.ClosureCategoryChanged.toString(), closurecategorychanged);
	}

	/**
	 * @return value of RequestEvent_RequestSnapShot
	 */
	public final process.proxies.RequestEvent getRequestEvent_RequestSnapShot() throws com.mendix.core.CoreException
	{
		return getRequestEvent_RequestSnapShot(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestEvent_RequestSnapShot
	 */
	public final process.proxies.RequestEvent getRequestEvent_RequestSnapShot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		process.proxies.RequestEvent result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestEvent_RequestSnapShot.toString());
		if (identifier != null)
			result = process.proxies.RequestEvent.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RequestEvent_RequestSnapShot
	 * @param requestevent_requestsnapshot
	 */
	public final void setRequestEvent_RequestSnapShot(process.proxies.RequestEvent requestevent_requestsnapshot)
	{
		setRequestEvent_RequestSnapShot(getContext(), requestevent_requestsnapshot);
	}

	/**
	 * Set value of RequestEvent_RequestSnapShot
	 * @param context
	 * @param requestevent_requestsnapshot
	 */
	public final void setRequestEvent_RequestSnapShot(com.mendix.systemwideinterfaces.core.IContext context, process.proxies.RequestEvent requestevent_requestsnapshot)
	{
		if (requestevent_requestsnapshot == null)
			getMendixObject().setValue(context, MemberNames.RequestEvent_RequestSnapShot.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RequestEvent_RequestSnapShot.toString(), requestevent_requestsnapshot.getMendixObject().getId());
	}

	/**
	 * @return value of RequestSnapShot_OpeningCategory
	 */
	public final categories.proxies.Category getRequestSnapShot_OpeningCategory() throws com.mendix.core.CoreException
	{
		return getRequestSnapShot_OpeningCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestSnapShot_OpeningCategory
	 */
	public final categories.proxies.Category getRequestSnapShot_OpeningCategory(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		categories.proxies.Category result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestSnapShot_OpeningCategory.toString());
		if (identifier != null)
			result = categories.proxies.Category.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RequestSnapShot_OpeningCategory
	 * @param requestsnapshot_openingcategory
	 */
	public final void setRequestSnapShot_OpeningCategory(categories.proxies.Category requestsnapshot_openingcategory)
	{
		setRequestSnapShot_OpeningCategory(getContext(), requestsnapshot_openingcategory);
	}

	/**
	 * Set value of RequestSnapShot_OpeningCategory
	 * @param context
	 * @param requestsnapshot_openingcategory
	 */
	public final void setRequestSnapShot_OpeningCategory(com.mendix.systemwideinterfaces.core.IContext context, categories.proxies.Category requestsnapshot_openingcategory)
	{
		if (requestsnapshot_openingcategory == null)
			getMendixObject().setValue(context, MemberNames.RequestSnapShot_OpeningCategory.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RequestSnapShot_OpeningCategory.toString(), requestsnapshot_openingcategory.getMendixObject().getId());
	}

	/**
	 * @return value of RequestSnapShot_ClosureCategory
	 */
	public final categories.proxies.Category getRequestSnapShot_ClosureCategory() throws com.mendix.core.CoreException
	{
		return getRequestSnapShot_ClosureCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestSnapShot_ClosureCategory
	 */
	public final categories.proxies.Category getRequestSnapShot_ClosureCategory(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		categories.proxies.Category result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestSnapShot_ClosureCategory.toString());
		if (identifier != null)
			result = categories.proxies.Category.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RequestSnapShot_ClosureCategory
	 * @param requestsnapshot_closurecategory
	 */
	public final void setRequestSnapShot_ClosureCategory(categories.proxies.Category requestsnapshot_closurecategory)
	{
		setRequestSnapShot_ClosureCategory(getContext(), requestsnapshot_closurecategory);
	}

	/**
	 * Set value of RequestSnapShot_ClosureCategory
	 * @param context
	 * @param requestsnapshot_closurecategory
	 */
	public final void setRequestSnapShot_ClosureCategory(com.mendix.systemwideinterfaces.core.IContext context, categories.proxies.Category requestsnapshot_closurecategory)
	{
		if (requestsnapshot_closurecategory == null)
			getMendixObject().setValue(context, MemberNames.RequestSnapShot_ClosureCategory.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RequestSnapShot_ClosureCategory.toString(), requestsnapshot_closurecategory.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return requestSnapShotMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final process.proxies.RequestSnapShot that = (process.proxies.RequestSnapShot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Process.RequestSnapShot";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
