// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package process.proxies;

public class RequestSLMAspectAudit
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject requestSLMAspectAuditMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Process.RequestSLMAspectAudit";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AutoID("AutoID"),
		InitialAudit("InitialAudit"),
		ContractNameHistoric("ContractNameHistoric"),
		ServiceProcessHistoric("ServiceProcessHistoric"),
		ServiceHistoric("ServiceHistoric"),
		CIHistoric("CIHistoric"),
		IUPCombinationHistoric("IUPCombinationHistoric"),
		ImpactHistoric("ImpactHistoric"),
		UrgencyHistoric("UrgencyHistoric"),
		PriorityHistoric("PriorityHistoric"),
		CommitmentHistoric("CommitmentHistoric"),
		HolidaysHistoric("HolidaysHistoric"),
		BusinessTimeHistoric("BusinessTimeHistoric"),
		ProcessType("ProcessType"),
		MatrixHistoric("MatrixHistoric"),
		DurationInBusinessHours("DurationInBusinessHours"),
		DurationInBusinessHoursStr("DurationInBusinessHoursStr"),
		SLAEndTimeHistoric("SLAEndTimeHistoric"),
		SLAResponseTimeHistoric("SLAResponseTimeHistoric"),
		StartTime("StartTime"),
		StopTime("StopTime"),
		PersonHistoric("PersonHistoric"),
		NewSLAEndTime("NewSLAEndTime"),
		NewSLAResponseTime("NewSLAResponseTime"),
		CreateTimeHistoric("CreateTimeHistoric"),
		NewCreateTime("NewCreateTime"),
		RequestSLMAspectAudit_Request("Process.RequestSLMAspectAudit_Request"),
		RequestSLMAspectAudit_ActivityStream("Process.RequestSLMAspectAudit_ActivityStream"),
		RequestSLMAspectAudit_Contract("Process.RequestSLMAspectAudit_Contract"),
		RequestSLMAspectAudit_Impact("Process.RequestSLMAspectAudit_Impact"),
		RequestSLMAspectAudit_Urgency("Process.RequestSLMAspectAudit_Urgency"),
		RequestSLMAspectAudit_Priority("Process.RequestSLMAspectAudit_Priority"),
		RequestSLMAspectAudit_IUP_Combination("Process.RequestSLMAspectAudit_IUP_Combination"),
		RequestSLMAspectAudit_Service_Process("Process.RequestSLMAspectAudit_Service_Process"),
		RequestSLMAspectAudit_Service("Process.RequestSLMAspectAudit_Service"),
		RequestSLMAspectAudit_Commitment("Process.RequestSLMAspectAudit_Commitment"),
		RequestSLMAspectAudit_ConfigurationItem("Process.RequestSLMAspectAudit_ConfigurationItem"),
		RequestSLMAspectAudit_Holidays_Group("Process.RequestSLMAspectAudit_Holidays_Group"),
		RequestSLMAspectAudit_Business_Time_Group("Process.RequestSLMAspectAudit_Business_Time_Group"),
		RequestSLMAspectAudit_Matrix("Process.RequestSLMAspectAudit_Matrix"),
		RequestSLMAspectAudit_Person("Process.RequestSLMAspectAudit_Person");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RequestSLMAspectAudit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Process.RequestSLMAspectAudit"));
	}

	protected RequestSLMAspectAudit(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject requestSLMAspectAuditMendixObject)
	{
		if (requestSLMAspectAuditMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Process.RequestSLMAspectAudit", requestSLMAspectAuditMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Process.RequestSLMAspectAudit");

		this.requestSLMAspectAuditMendixObject = requestSLMAspectAuditMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'RequestSLMAspectAudit.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static process.proxies.RequestSLMAspectAudit initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return process.proxies.RequestSLMAspectAudit.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static process.proxies.RequestSLMAspectAudit initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new process.proxies.RequestSLMAspectAudit(context, mendixObject);
	}

	public static process.proxies.RequestSLMAspectAudit load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return process.proxies.RequestSLMAspectAudit.initialize(context, mendixObject);
	}

	public static java.util.List<process.proxies.RequestSLMAspectAudit> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<process.proxies.RequestSLMAspectAudit> result = new java.util.ArrayList<process.proxies.RequestSLMAspectAudit>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Process.RequestSLMAspectAudit" + xpathConstraint))
			result.add(process.proxies.RequestSLMAspectAudit.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of AutoID
	 */
	public final java.lang.Long getAutoID()
	{
		return getAutoID(getContext());
	}

	/**
	 * @param context
	 * @return value of AutoID
	 */
	public final java.lang.Long getAutoID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.AutoID.toString());
	}

	/**
	 * Set value of AutoID
	 * @param autoid
	 */
	public final void setAutoID(java.lang.Long autoid)
	{
		setAutoID(getContext(), autoid);
	}

	/**
	 * Set value of AutoID
	 * @param context
	 * @param autoid
	 */
	public final void setAutoID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long autoid)
	{
		getMendixObject().setValue(context, MemberNames.AutoID.toString(), autoid);
	}

	/**
	 * @return value of InitialAudit
	 */
	public final java.lang.Boolean getInitialAudit()
	{
		return getInitialAudit(getContext());
	}

	/**
	 * @param context
	 * @return value of InitialAudit
	 */
	public final java.lang.Boolean getInitialAudit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.InitialAudit.toString());
	}

	/**
	 * Set value of InitialAudit
	 * @param initialaudit
	 */
	public final void setInitialAudit(java.lang.Boolean initialaudit)
	{
		setInitialAudit(getContext(), initialaudit);
	}

	/**
	 * Set value of InitialAudit
	 * @param context
	 * @param initialaudit
	 */
	public final void setInitialAudit(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean initialaudit)
	{
		getMendixObject().setValue(context, MemberNames.InitialAudit.toString(), initialaudit);
	}

	/**
	 * @return value of ContractNameHistoric
	 */
	public final java.lang.String getContractNameHistoric()
	{
		return getContractNameHistoric(getContext());
	}

	/**
	 * @param context
	 * @return value of ContractNameHistoric
	 */
	public final java.lang.String getContractNameHistoric(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContractNameHistoric.toString());
	}

	/**
	 * Set value of ContractNameHistoric
	 * @param contractnamehistoric
	 */
	public final void setContractNameHistoric(java.lang.String contractnamehistoric)
	{
		setContractNameHistoric(getContext(), contractnamehistoric);
	}

	/**
	 * Set value of ContractNameHistoric
	 * @param context
	 * @param contractnamehistoric
	 */
	public final void setContractNameHistoric(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String contractnamehistoric)
	{
		getMendixObject().setValue(context, MemberNames.ContractNameHistoric.toString(), contractnamehistoric);
	}

	/**
	 * @return value of ServiceProcessHistoric
	 */
	public final java.lang.String getServiceProcessHistoric()
	{
		return getServiceProcessHistoric(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceProcessHistoric
	 */
	public final java.lang.String getServiceProcessHistoric(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ServiceProcessHistoric.toString());
	}

	/**
	 * Set value of ServiceProcessHistoric
	 * @param serviceprocesshistoric
	 */
	public final void setServiceProcessHistoric(java.lang.String serviceprocesshistoric)
	{
		setServiceProcessHistoric(getContext(), serviceprocesshistoric);
	}

	/**
	 * Set value of ServiceProcessHistoric
	 * @param context
	 * @param serviceprocesshistoric
	 */
	public final void setServiceProcessHistoric(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String serviceprocesshistoric)
	{
		getMendixObject().setValue(context, MemberNames.ServiceProcessHistoric.toString(), serviceprocesshistoric);
	}

	/**
	 * @return value of ServiceHistoric
	 */
	public final java.lang.String getServiceHistoric()
	{
		return getServiceHistoric(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceHistoric
	 */
	public final java.lang.String getServiceHistoric(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ServiceHistoric.toString());
	}

	/**
	 * Set value of ServiceHistoric
	 * @param servicehistoric
	 */
	public final void setServiceHistoric(java.lang.String servicehistoric)
	{
		setServiceHistoric(getContext(), servicehistoric);
	}

	/**
	 * Set value of ServiceHistoric
	 * @param context
	 * @param servicehistoric
	 */
	public final void setServiceHistoric(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String servicehistoric)
	{
		getMendixObject().setValue(context, MemberNames.ServiceHistoric.toString(), servicehistoric);
	}

	/**
	 * @return value of CIHistoric
	 */
	public final java.lang.String getCIHistoric()
	{
		return getCIHistoric(getContext());
	}

	/**
	 * @param context
	 * @return value of CIHistoric
	 */
	public final java.lang.String getCIHistoric(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CIHistoric.toString());
	}

	/**
	 * Set value of CIHistoric
	 * @param cihistoric
	 */
	public final void setCIHistoric(java.lang.String cihistoric)
	{
		setCIHistoric(getContext(), cihistoric);
	}

	/**
	 * Set value of CIHistoric
	 * @param context
	 * @param cihistoric
	 */
	public final void setCIHistoric(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cihistoric)
	{
		getMendixObject().setValue(context, MemberNames.CIHistoric.toString(), cihistoric);
	}

	/**
	 * @return value of IUPCombinationHistoric
	 */
	public final java.lang.String getIUPCombinationHistoric()
	{
		return getIUPCombinationHistoric(getContext());
	}

	/**
	 * @param context
	 * @return value of IUPCombinationHistoric
	 */
	public final java.lang.String getIUPCombinationHistoric(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IUPCombinationHistoric.toString());
	}

	/**
	 * Set value of IUPCombinationHistoric
	 * @param iupcombinationhistoric
	 */
	public final void setIUPCombinationHistoric(java.lang.String iupcombinationhistoric)
	{
		setIUPCombinationHistoric(getContext(), iupcombinationhistoric);
	}

	/**
	 * Set value of IUPCombinationHistoric
	 * @param context
	 * @param iupcombinationhistoric
	 */
	public final void setIUPCombinationHistoric(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String iupcombinationhistoric)
	{
		getMendixObject().setValue(context, MemberNames.IUPCombinationHistoric.toString(), iupcombinationhistoric);
	}

	/**
	 * @return value of ImpactHistoric
	 */
	public final java.lang.String getImpactHistoric()
	{
		return getImpactHistoric(getContext());
	}

	/**
	 * @param context
	 * @return value of ImpactHistoric
	 */
	public final java.lang.String getImpactHistoric(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ImpactHistoric.toString());
	}

	/**
	 * Set value of ImpactHistoric
	 * @param impacthistoric
	 */
	public final void setImpactHistoric(java.lang.String impacthistoric)
	{
		setImpactHistoric(getContext(), impacthistoric);
	}

	/**
	 * Set value of ImpactHistoric
	 * @param context
	 * @param impacthistoric
	 */
	public final void setImpactHistoric(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String impacthistoric)
	{
		getMendixObject().setValue(context, MemberNames.ImpactHistoric.toString(), impacthistoric);
	}

	/**
	 * @return value of UrgencyHistoric
	 */
	public final java.lang.String getUrgencyHistoric()
	{
		return getUrgencyHistoric(getContext());
	}

	/**
	 * @param context
	 * @return value of UrgencyHistoric
	 */
	public final java.lang.String getUrgencyHistoric(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UrgencyHistoric.toString());
	}

	/**
	 * Set value of UrgencyHistoric
	 * @param urgencyhistoric
	 */
	public final void setUrgencyHistoric(java.lang.String urgencyhistoric)
	{
		setUrgencyHistoric(getContext(), urgencyhistoric);
	}

	/**
	 * Set value of UrgencyHistoric
	 * @param context
	 * @param urgencyhistoric
	 */
	public final void setUrgencyHistoric(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String urgencyhistoric)
	{
		getMendixObject().setValue(context, MemberNames.UrgencyHistoric.toString(), urgencyhistoric);
	}

	/**
	 * @return value of PriorityHistoric
	 */
	public final java.lang.String getPriorityHistoric()
	{
		return getPriorityHistoric(getContext());
	}

	/**
	 * @param context
	 * @return value of PriorityHistoric
	 */
	public final java.lang.String getPriorityHistoric(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PriorityHistoric.toString());
	}

	/**
	 * Set value of PriorityHistoric
	 * @param priorityhistoric
	 */
	public final void setPriorityHistoric(java.lang.String priorityhistoric)
	{
		setPriorityHistoric(getContext(), priorityhistoric);
	}

	/**
	 * Set value of PriorityHistoric
	 * @param context
	 * @param priorityhistoric
	 */
	public final void setPriorityHistoric(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String priorityhistoric)
	{
		getMendixObject().setValue(context, MemberNames.PriorityHistoric.toString(), priorityhistoric);
	}

	/**
	 * @return value of CommitmentHistoric
	 */
	public final java.lang.String getCommitmentHistoric()
	{
		return getCommitmentHistoric(getContext());
	}

	/**
	 * @param context
	 * @return value of CommitmentHistoric
	 */
	public final java.lang.String getCommitmentHistoric(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CommitmentHistoric.toString());
	}

	/**
	 * Set value of CommitmentHistoric
	 * @param commitmenthistoric
	 */
	public final void setCommitmentHistoric(java.lang.String commitmenthistoric)
	{
		setCommitmentHistoric(getContext(), commitmenthistoric);
	}

	/**
	 * Set value of CommitmentHistoric
	 * @param context
	 * @param commitmenthistoric
	 */
	public final void setCommitmentHistoric(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String commitmenthistoric)
	{
		getMendixObject().setValue(context, MemberNames.CommitmentHistoric.toString(), commitmenthistoric);
	}

	/**
	 * @return value of HolidaysHistoric
	 */
	public final java.lang.String getHolidaysHistoric()
	{
		return getHolidaysHistoric(getContext());
	}

	/**
	 * @param context
	 * @return value of HolidaysHistoric
	 */
	public final java.lang.String getHolidaysHistoric(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HolidaysHistoric.toString());
	}

	/**
	 * Set value of HolidaysHistoric
	 * @param holidayshistoric
	 */
	public final void setHolidaysHistoric(java.lang.String holidayshistoric)
	{
		setHolidaysHistoric(getContext(), holidayshistoric);
	}

	/**
	 * Set value of HolidaysHistoric
	 * @param context
	 * @param holidayshistoric
	 */
	public final void setHolidaysHistoric(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String holidayshistoric)
	{
		getMendixObject().setValue(context, MemberNames.HolidaysHistoric.toString(), holidayshistoric);
	}

	/**
	 * @return value of BusinessTimeHistoric
	 */
	public final java.lang.String getBusinessTimeHistoric()
	{
		return getBusinessTimeHistoric(getContext());
	}

	/**
	 * @param context
	 * @return value of BusinessTimeHistoric
	 */
	public final java.lang.String getBusinessTimeHistoric(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BusinessTimeHistoric.toString());
	}

	/**
	 * Set value of BusinessTimeHistoric
	 * @param businesstimehistoric
	 */
	public final void setBusinessTimeHistoric(java.lang.String businesstimehistoric)
	{
		setBusinessTimeHistoric(getContext(), businesstimehistoric);
	}

	/**
	 * Set value of BusinessTimeHistoric
	 * @param context
	 * @param businesstimehistoric
	 */
	public final void setBusinessTimeHistoric(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String businesstimehistoric)
	{
		getMendixObject().setValue(context, MemberNames.BusinessTimeHistoric.toString(), businesstimehistoric);
	}

	/**
	 * @return value of ProcessType
	 */
	public final java.lang.String getProcessType()
	{
		return getProcessType(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessType
	 */
	public final java.lang.String getProcessType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProcessType.toString());
	}

	/**
	 * Set value of ProcessType
	 * @param processtype
	 */
	public final void setProcessType(java.lang.String processtype)
	{
		setProcessType(getContext(), processtype);
	}

	/**
	 * Set value of ProcessType
	 * @param context
	 * @param processtype
	 */
	public final void setProcessType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String processtype)
	{
		getMendixObject().setValue(context, MemberNames.ProcessType.toString(), processtype);
	}

	/**
	 * @return value of MatrixHistoric
	 */
	public final java.lang.String getMatrixHistoric()
	{
		return getMatrixHistoric(getContext());
	}

	/**
	 * @param context
	 * @return value of MatrixHistoric
	 */
	public final java.lang.String getMatrixHistoric(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MatrixHistoric.toString());
	}

	/**
	 * Set value of MatrixHistoric
	 * @param matrixhistoric
	 */
	public final void setMatrixHistoric(java.lang.String matrixhistoric)
	{
		setMatrixHistoric(getContext(), matrixhistoric);
	}

	/**
	 * Set value of MatrixHistoric
	 * @param context
	 * @param matrixhistoric
	 */
	public final void setMatrixHistoric(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String matrixhistoric)
	{
		getMendixObject().setValue(context, MemberNames.MatrixHistoric.toString(), matrixhistoric);
	}

	/**
	 * @return value of DurationInBusinessHours
	 */
	public final java.lang.Integer getDurationInBusinessHours()
	{
		return getDurationInBusinessHours(getContext());
	}

	/**
	 * @param context
	 * @return value of DurationInBusinessHours
	 */
	public final java.lang.Integer getDurationInBusinessHours(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.DurationInBusinessHours.toString());
	}

	/**
	 * Set value of DurationInBusinessHours
	 * @param durationinbusinesshours
	 */
	public final void setDurationInBusinessHours(java.lang.Integer durationinbusinesshours)
	{
		setDurationInBusinessHours(getContext(), durationinbusinesshours);
	}

	/**
	 * Set value of DurationInBusinessHours
	 * @param context
	 * @param durationinbusinesshours
	 */
	public final void setDurationInBusinessHours(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer durationinbusinesshours)
	{
		getMendixObject().setValue(context, MemberNames.DurationInBusinessHours.toString(), durationinbusinesshours);
	}

	/**
	 * @return value of DurationInBusinessHoursStr
	 */
	public final java.lang.String getDurationInBusinessHoursStr()
	{
		return getDurationInBusinessHoursStr(getContext());
	}

	/**
	 * @param context
	 * @return value of DurationInBusinessHoursStr
	 */
	public final java.lang.String getDurationInBusinessHoursStr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DurationInBusinessHoursStr.toString());
	}

	/**
	 * Set value of DurationInBusinessHoursStr
	 * @param durationinbusinesshoursstr
	 */
	public final void setDurationInBusinessHoursStr(java.lang.String durationinbusinesshoursstr)
	{
		setDurationInBusinessHoursStr(getContext(), durationinbusinesshoursstr);
	}

	/**
	 * Set value of DurationInBusinessHoursStr
	 * @param context
	 * @param durationinbusinesshoursstr
	 */
	public final void setDurationInBusinessHoursStr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String durationinbusinesshoursstr)
	{
		getMendixObject().setValue(context, MemberNames.DurationInBusinessHoursStr.toString(), durationinbusinesshoursstr);
	}

	/**
	 * @return value of SLAEndTimeHistoric
	 */
	public final java.util.Date getSLAEndTimeHistoric()
	{
		return getSLAEndTimeHistoric(getContext());
	}

	/**
	 * @param context
	 * @return value of SLAEndTimeHistoric
	 */
	public final java.util.Date getSLAEndTimeHistoric(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.SLAEndTimeHistoric.toString());
	}

	/**
	 * Set value of SLAEndTimeHistoric
	 * @param slaendtimehistoric
	 */
	public final void setSLAEndTimeHistoric(java.util.Date slaendtimehistoric)
	{
		setSLAEndTimeHistoric(getContext(), slaendtimehistoric);
	}

	/**
	 * Set value of SLAEndTimeHistoric
	 * @param context
	 * @param slaendtimehistoric
	 */
	public final void setSLAEndTimeHistoric(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date slaendtimehistoric)
	{
		getMendixObject().setValue(context, MemberNames.SLAEndTimeHistoric.toString(), slaendtimehistoric);
	}

	/**
	 * @return value of SLAResponseTimeHistoric
	 */
	public final java.util.Date getSLAResponseTimeHistoric()
	{
		return getSLAResponseTimeHistoric(getContext());
	}

	/**
	 * @param context
	 * @return value of SLAResponseTimeHistoric
	 */
	public final java.util.Date getSLAResponseTimeHistoric(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.SLAResponseTimeHistoric.toString());
	}

	/**
	 * Set value of SLAResponseTimeHistoric
	 * @param slaresponsetimehistoric
	 */
	public final void setSLAResponseTimeHistoric(java.util.Date slaresponsetimehistoric)
	{
		setSLAResponseTimeHistoric(getContext(), slaresponsetimehistoric);
	}

	/**
	 * Set value of SLAResponseTimeHistoric
	 * @param context
	 * @param slaresponsetimehistoric
	 */
	public final void setSLAResponseTimeHistoric(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date slaresponsetimehistoric)
	{
		getMendixObject().setValue(context, MemberNames.SLAResponseTimeHistoric.toString(), slaresponsetimehistoric);
	}

	/**
	 * @return value of StartTime
	 */
	public final java.util.Date getStartTime()
	{
		return getStartTime(getContext());
	}

	/**
	 * @param context
	 * @return value of StartTime
	 */
	public final java.util.Date getStartTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartTime.toString());
	}

	/**
	 * Set value of StartTime
	 * @param starttime
	 */
	public final void setStartTime(java.util.Date starttime)
	{
		setStartTime(getContext(), starttime);
	}

	/**
	 * Set value of StartTime
	 * @param context
	 * @param starttime
	 */
	public final void setStartTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date starttime)
	{
		getMendixObject().setValue(context, MemberNames.StartTime.toString(), starttime);
	}

	/**
	 * @return value of StopTime
	 */
	public final java.util.Date getStopTime()
	{
		return getStopTime(getContext());
	}

	/**
	 * @param context
	 * @return value of StopTime
	 */
	public final java.util.Date getStopTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StopTime.toString());
	}

	/**
	 * Set value of StopTime
	 * @param stoptime
	 */
	public final void setStopTime(java.util.Date stoptime)
	{
		setStopTime(getContext(), stoptime);
	}

	/**
	 * Set value of StopTime
	 * @param context
	 * @param stoptime
	 */
	public final void setStopTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date stoptime)
	{
		getMendixObject().setValue(context, MemberNames.StopTime.toString(), stoptime);
	}

	/**
	 * @return value of PersonHistoric
	 */
	public final java.lang.String getPersonHistoric()
	{
		return getPersonHistoric(getContext());
	}

	/**
	 * @param context
	 * @return value of PersonHistoric
	 */
	public final java.lang.String getPersonHistoric(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PersonHistoric.toString());
	}

	/**
	 * Set value of PersonHistoric
	 * @param personhistoric
	 */
	public final void setPersonHistoric(java.lang.String personhistoric)
	{
		setPersonHistoric(getContext(), personhistoric);
	}

	/**
	 * Set value of PersonHistoric
	 * @param context
	 * @param personhistoric
	 */
	public final void setPersonHistoric(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String personhistoric)
	{
		getMendixObject().setValue(context, MemberNames.PersonHistoric.toString(), personhistoric);
	}

	/**
	 * @return value of NewSLAEndTime
	 */
	public final java.util.Date getNewSLAEndTime()
	{
		return getNewSLAEndTime(getContext());
	}

	/**
	 * @param context
	 * @return value of NewSLAEndTime
	 */
	public final java.util.Date getNewSLAEndTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.NewSLAEndTime.toString());
	}

	/**
	 * Set value of NewSLAEndTime
	 * @param newslaendtime
	 */
	public final void setNewSLAEndTime(java.util.Date newslaendtime)
	{
		setNewSLAEndTime(getContext(), newslaendtime);
	}

	/**
	 * Set value of NewSLAEndTime
	 * @param context
	 * @param newslaendtime
	 */
	public final void setNewSLAEndTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date newslaendtime)
	{
		getMendixObject().setValue(context, MemberNames.NewSLAEndTime.toString(), newslaendtime);
	}

	/**
	 * @return value of NewSLAResponseTime
	 */
	public final java.util.Date getNewSLAResponseTime()
	{
		return getNewSLAResponseTime(getContext());
	}

	/**
	 * @param context
	 * @return value of NewSLAResponseTime
	 */
	public final java.util.Date getNewSLAResponseTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.NewSLAResponseTime.toString());
	}

	/**
	 * Set value of NewSLAResponseTime
	 * @param newslaresponsetime
	 */
	public final void setNewSLAResponseTime(java.util.Date newslaresponsetime)
	{
		setNewSLAResponseTime(getContext(), newslaresponsetime);
	}

	/**
	 * Set value of NewSLAResponseTime
	 * @param context
	 * @param newslaresponsetime
	 */
	public final void setNewSLAResponseTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date newslaresponsetime)
	{
		getMendixObject().setValue(context, MemberNames.NewSLAResponseTime.toString(), newslaresponsetime);
	}

	/**
	 * @return value of CreateTimeHistoric
	 */
	public final java.util.Date getCreateTimeHistoric()
	{
		return getCreateTimeHistoric(getContext());
	}

	/**
	 * @param context
	 * @return value of CreateTimeHistoric
	 */
	public final java.util.Date getCreateTimeHistoric(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CreateTimeHistoric.toString());
	}

	/**
	 * Set value of CreateTimeHistoric
	 * @param createtimehistoric
	 */
	public final void setCreateTimeHistoric(java.util.Date createtimehistoric)
	{
		setCreateTimeHistoric(getContext(), createtimehistoric);
	}

	/**
	 * Set value of CreateTimeHistoric
	 * @param context
	 * @param createtimehistoric
	 */
	public final void setCreateTimeHistoric(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date createtimehistoric)
	{
		getMendixObject().setValue(context, MemberNames.CreateTimeHistoric.toString(), createtimehistoric);
	}

	/**
	 * @return value of NewCreateTime
	 */
	public final java.util.Date getNewCreateTime()
	{
		return getNewCreateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of NewCreateTime
	 */
	public final java.util.Date getNewCreateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.NewCreateTime.toString());
	}

	/**
	 * Set value of NewCreateTime
	 * @param newcreatetime
	 */
	public final void setNewCreateTime(java.util.Date newcreatetime)
	{
		setNewCreateTime(getContext(), newcreatetime);
	}

	/**
	 * Set value of NewCreateTime
	 * @param context
	 * @param newcreatetime
	 */
	public final void setNewCreateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date newcreatetime)
	{
		getMendixObject().setValue(context, MemberNames.NewCreateTime.toString(), newcreatetime);
	}

	/**
	 * @return value of RequestSLMAspectAudit_Request
	 */
	public final process.proxies.Request getRequestSLMAspectAudit_Request() throws com.mendix.core.CoreException
	{
		return getRequestSLMAspectAudit_Request(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestSLMAspectAudit_Request
	 */
	public final process.proxies.Request getRequestSLMAspectAudit_Request(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		process.proxies.Request result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestSLMAspectAudit_Request.toString());
		if (identifier != null)
			result = process.proxies.Request.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RequestSLMAspectAudit_Request
	 * @param requestslmaspectaudit_request
	 */
	public final void setRequestSLMAspectAudit_Request(process.proxies.Request requestslmaspectaudit_request)
	{
		setRequestSLMAspectAudit_Request(getContext(), requestslmaspectaudit_request);
	}

	/**
	 * Set value of RequestSLMAspectAudit_Request
	 * @param context
	 * @param requestslmaspectaudit_request
	 */
	public final void setRequestSLMAspectAudit_Request(com.mendix.systemwideinterfaces.core.IContext context, process.proxies.Request requestslmaspectaudit_request)
	{
		if (requestslmaspectaudit_request == null)
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_Request.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_Request.toString(), requestslmaspectaudit_request.getMendixObject().getId());
	}

	/**
	 * @return value of RequestSLMAspectAudit_ActivityStream
	 */
	public final process.proxies.ActivityStream getRequestSLMAspectAudit_ActivityStream() throws com.mendix.core.CoreException
	{
		return getRequestSLMAspectAudit_ActivityStream(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestSLMAspectAudit_ActivityStream
	 */
	public final process.proxies.ActivityStream getRequestSLMAspectAudit_ActivityStream(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		process.proxies.ActivityStream result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestSLMAspectAudit_ActivityStream.toString());
		if (identifier != null)
			result = process.proxies.ActivityStream.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RequestSLMAspectAudit_ActivityStream
	 * @param requestslmaspectaudit_activitystream
	 */
	public final void setRequestSLMAspectAudit_ActivityStream(process.proxies.ActivityStream requestslmaspectaudit_activitystream)
	{
		setRequestSLMAspectAudit_ActivityStream(getContext(), requestslmaspectaudit_activitystream);
	}

	/**
	 * Set value of RequestSLMAspectAudit_ActivityStream
	 * @param context
	 * @param requestslmaspectaudit_activitystream
	 */
	public final void setRequestSLMAspectAudit_ActivityStream(com.mendix.systemwideinterfaces.core.IContext context, process.proxies.ActivityStream requestslmaspectaudit_activitystream)
	{
		if (requestslmaspectaudit_activitystream == null)
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_ActivityStream.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_ActivityStream.toString(), requestslmaspectaudit_activitystream.getMendixObject().getId());
	}

	/**
	 * @return value of RequestSLMAspectAudit_Contract
	 */
	public final slm.proxies.Contract getRequestSLMAspectAudit_Contract() throws com.mendix.core.CoreException
	{
		return getRequestSLMAspectAudit_Contract(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestSLMAspectAudit_Contract
	 */
	public final slm.proxies.Contract getRequestSLMAspectAudit_Contract(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		slm.proxies.Contract result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestSLMAspectAudit_Contract.toString());
		if (identifier != null)
			result = slm.proxies.Contract.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RequestSLMAspectAudit_Contract
	 * @param requestslmaspectaudit_contract
	 */
	public final void setRequestSLMAspectAudit_Contract(slm.proxies.Contract requestslmaspectaudit_contract)
	{
		setRequestSLMAspectAudit_Contract(getContext(), requestslmaspectaudit_contract);
	}

	/**
	 * Set value of RequestSLMAspectAudit_Contract
	 * @param context
	 * @param requestslmaspectaudit_contract
	 */
	public final void setRequestSLMAspectAudit_Contract(com.mendix.systemwideinterfaces.core.IContext context, slm.proxies.Contract requestslmaspectaudit_contract)
	{
		if (requestslmaspectaudit_contract == null)
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_Contract.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_Contract.toString(), requestslmaspectaudit_contract.getMendixObject().getId());
	}

	/**
	 * @return value of RequestSLMAspectAudit_Impact
	 */
	public final slm.proxies.Impact getRequestSLMAspectAudit_Impact() throws com.mendix.core.CoreException
	{
		return getRequestSLMAspectAudit_Impact(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestSLMAspectAudit_Impact
	 */
	public final slm.proxies.Impact getRequestSLMAspectAudit_Impact(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		slm.proxies.Impact result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestSLMAspectAudit_Impact.toString());
		if (identifier != null)
			result = slm.proxies.Impact.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RequestSLMAspectAudit_Impact
	 * @param requestslmaspectaudit_impact
	 */
	public final void setRequestSLMAspectAudit_Impact(slm.proxies.Impact requestslmaspectaudit_impact)
	{
		setRequestSLMAspectAudit_Impact(getContext(), requestslmaspectaudit_impact);
	}

	/**
	 * Set value of RequestSLMAspectAudit_Impact
	 * @param context
	 * @param requestslmaspectaudit_impact
	 */
	public final void setRequestSLMAspectAudit_Impact(com.mendix.systemwideinterfaces.core.IContext context, slm.proxies.Impact requestslmaspectaudit_impact)
	{
		if (requestslmaspectaudit_impact == null)
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_Impact.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_Impact.toString(), requestslmaspectaudit_impact.getMendixObject().getId());
	}

	/**
	 * @return value of RequestSLMAspectAudit_Urgency
	 */
	public final slm.proxies.Urgency getRequestSLMAspectAudit_Urgency() throws com.mendix.core.CoreException
	{
		return getRequestSLMAspectAudit_Urgency(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestSLMAspectAudit_Urgency
	 */
	public final slm.proxies.Urgency getRequestSLMAspectAudit_Urgency(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		slm.proxies.Urgency result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestSLMAspectAudit_Urgency.toString());
		if (identifier != null)
			result = slm.proxies.Urgency.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RequestSLMAspectAudit_Urgency
	 * @param requestslmaspectaudit_urgency
	 */
	public final void setRequestSLMAspectAudit_Urgency(slm.proxies.Urgency requestslmaspectaudit_urgency)
	{
		setRequestSLMAspectAudit_Urgency(getContext(), requestslmaspectaudit_urgency);
	}

	/**
	 * Set value of RequestSLMAspectAudit_Urgency
	 * @param context
	 * @param requestslmaspectaudit_urgency
	 */
	public final void setRequestSLMAspectAudit_Urgency(com.mendix.systemwideinterfaces.core.IContext context, slm.proxies.Urgency requestslmaspectaudit_urgency)
	{
		if (requestslmaspectaudit_urgency == null)
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_Urgency.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_Urgency.toString(), requestslmaspectaudit_urgency.getMendixObject().getId());
	}

	/**
	 * @return value of RequestSLMAspectAudit_Priority
	 */
	public final slm.proxies.Priority getRequestSLMAspectAudit_Priority() throws com.mendix.core.CoreException
	{
		return getRequestSLMAspectAudit_Priority(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestSLMAspectAudit_Priority
	 */
	public final slm.proxies.Priority getRequestSLMAspectAudit_Priority(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		slm.proxies.Priority result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestSLMAspectAudit_Priority.toString());
		if (identifier != null)
			result = slm.proxies.Priority.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RequestSLMAspectAudit_Priority
	 * @param requestslmaspectaudit_priority
	 */
	public final void setRequestSLMAspectAudit_Priority(slm.proxies.Priority requestslmaspectaudit_priority)
	{
		setRequestSLMAspectAudit_Priority(getContext(), requestslmaspectaudit_priority);
	}

	/**
	 * Set value of RequestSLMAspectAudit_Priority
	 * @param context
	 * @param requestslmaspectaudit_priority
	 */
	public final void setRequestSLMAspectAudit_Priority(com.mendix.systemwideinterfaces.core.IContext context, slm.proxies.Priority requestslmaspectaudit_priority)
	{
		if (requestslmaspectaudit_priority == null)
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_Priority.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_Priority.toString(), requestslmaspectaudit_priority.getMendixObject().getId());
	}

	/**
	 * @return value of RequestSLMAspectAudit_IUP_Combination
	 */
	public final slm.proxies.IUP_Combination getRequestSLMAspectAudit_IUP_Combination() throws com.mendix.core.CoreException
	{
		return getRequestSLMAspectAudit_IUP_Combination(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestSLMAspectAudit_IUP_Combination
	 */
	public final slm.proxies.IUP_Combination getRequestSLMAspectAudit_IUP_Combination(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		slm.proxies.IUP_Combination result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestSLMAspectAudit_IUP_Combination.toString());
		if (identifier != null)
			result = slm.proxies.IUP_Combination.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RequestSLMAspectAudit_IUP_Combination
	 * @param requestslmaspectaudit_iup_combination
	 */
	public final void setRequestSLMAspectAudit_IUP_Combination(slm.proxies.IUP_Combination requestslmaspectaudit_iup_combination)
	{
		setRequestSLMAspectAudit_IUP_Combination(getContext(), requestslmaspectaudit_iup_combination);
	}

	/**
	 * Set value of RequestSLMAspectAudit_IUP_Combination
	 * @param context
	 * @param requestslmaspectaudit_iup_combination
	 */
	public final void setRequestSLMAspectAudit_IUP_Combination(com.mendix.systemwideinterfaces.core.IContext context, slm.proxies.IUP_Combination requestslmaspectaudit_iup_combination)
	{
		if (requestslmaspectaudit_iup_combination == null)
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_IUP_Combination.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_IUP_Combination.toString(), requestslmaspectaudit_iup_combination.getMendixObject().getId());
	}

	/**
	 * @return value of RequestSLMAspectAudit_Service_Process
	 */
	public final slm.proxies.Service_Process getRequestSLMAspectAudit_Service_Process() throws com.mendix.core.CoreException
	{
		return getRequestSLMAspectAudit_Service_Process(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestSLMAspectAudit_Service_Process
	 */
	public final slm.proxies.Service_Process getRequestSLMAspectAudit_Service_Process(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		slm.proxies.Service_Process result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestSLMAspectAudit_Service_Process.toString());
		if (identifier != null)
			result = slm.proxies.Service_Process.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RequestSLMAspectAudit_Service_Process
	 * @param requestslmaspectaudit_service_process
	 */
	public final void setRequestSLMAspectAudit_Service_Process(slm.proxies.Service_Process requestslmaspectaudit_service_process)
	{
		setRequestSLMAspectAudit_Service_Process(getContext(), requestslmaspectaudit_service_process);
	}

	/**
	 * Set value of RequestSLMAspectAudit_Service_Process
	 * @param context
	 * @param requestslmaspectaudit_service_process
	 */
	public final void setRequestSLMAspectAudit_Service_Process(com.mendix.systemwideinterfaces.core.IContext context, slm.proxies.Service_Process requestslmaspectaudit_service_process)
	{
		if (requestslmaspectaudit_service_process == null)
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_Service_Process.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_Service_Process.toString(), requestslmaspectaudit_service_process.getMendixObject().getId());
	}

	/**
	 * @return value of RequestSLMAspectAudit_Service
	 */
	public final slm.proxies.Service getRequestSLMAspectAudit_Service() throws com.mendix.core.CoreException
	{
		return getRequestSLMAspectAudit_Service(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestSLMAspectAudit_Service
	 */
	public final slm.proxies.Service getRequestSLMAspectAudit_Service(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		slm.proxies.Service result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestSLMAspectAudit_Service.toString());
		if (identifier != null)
			result = slm.proxies.Service.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RequestSLMAspectAudit_Service
	 * @param requestslmaspectaudit_service
	 */
	public final void setRequestSLMAspectAudit_Service(slm.proxies.Service requestslmaspectaudit_service)
	{
		setRequestSLMAspectAudit_Service(getContext(), requestslmaspectaudit_service);
	}

	/**
	 * Set value of RequestSLMAspectAudit_Service
	 * @param context
	 * @param requestslmaspectaudit_service
	 */
	public final void setRequestSLMAspectAudit_Service(com.mendix.systemwideinterfaces.core.IContext context, slm.proxies.Service requestslmaspectaudit_service)
	{
		if (requestslmaspectaudit_service == null)
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_Service.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_Service.toString(), requestslmaspectaudit_service.getMendixObject().getId());
	}

	/**
	 * @return value of RequestSLMAspectAudit_Commitment
	 */
	public final slm_notifications.proxies.Commitment getRequestSLMAspectAudit_Commitment() throws com.mendix.core.CoreException
	{
		return getRequestSLMAspectAudit_Commitment(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestSLMAspectAudit_Commitment
	 */
	public final slm_notifications.proxies.Commitment getRequestSLMAspectAudit_Commitment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		slm_notifications.proxies.Commitment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestSLMAspectAudit_Commitment.toString());
		if (identifier != null)
			result = slm_notifications.proxies.Commitment.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RequestSLMAspectAudit_Commitment
	 * @param requestslmaspectaudit_commitment
	 */
	public final void setRequestSLMAspectAudit_Commitment(slm_notifications.proxies.Commitment requestslmaspectaudit_commitment)
	{
		setRequestSLMAspectAudit_Commitment(getContext(), requestslmaspectaudit_commitment);
	}

	/**
	 * Set value of RequestSLMAspectAudit_Commitment
	 * @param context
	 * @param requestslmaspectaudit_commitment
	 */
	public final void setRequestSLMAspectAudit_Commitment(com.mendix.systemwideinterfaces.core.IContext context, slm_notifications.proxies.Commitment requestslmaspectaudit_commitment)
	{
		if (requestslmaspectaudit_commitment == null)
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_Commitment.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_Commitment.toString(), requestslmaspectaudit_commitment.getMendixObject().getId());
	}

	/**
	 * @return value of RequestSLMAspectAudit_ConfigurationItem
	 */
	public final cmdb.proxies.ConfigurationItem getRequestSLMAspectAudit_ConfigurationItem() throws com.mendix.core.CoreException
	{
		return getRequestSLMAspectAudit_ConfigurationItem(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestSLMAspectAudit_ConfigurationItem
	 */
	public final cmdb.proxies.ConfigurationItem getRequestSLMAspectAudit_ConfigurationItem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmdb.proxies.ConfigurationItem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestSLMAspectAudit_ConfigurationItem.toString());
		if (identifier != null)
			result = cmdb.proxies.ConfigurationItem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RequestSLMAspectAudit_ConfigurationItem
	 * @param requestslmaspectaudit_configurationitem
	 */
	public final void setRequestSLMAspectAudit_ConfigurationItem(cmdb.proxies.ConfigurationItem requestslmaspectaudit_configurationitem)
	{
		setRequestSLMAspectAudit_ConfigurationItem(getContext(), requestslmaspectaudit_configurationitem);
	}

	/**
	 * Set value of RequestSLMAspectAudit_ConfigurationItem
	 * @param context
	 * @param requestslmaspectaudit_configurationitem
	 */
	public final void setRequestSLMAspectAudit_ConfigurationItem(com.mendix.systemwideinterfaces.core.IContext context, cmdb.proxies.ConfigurationItem requestslmaspectaudit_configurationitem)
	{
		if (requestslmaspectaudit_configurationitem == null)
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_ConfigurationItem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_ConfigurationItem.toString(), requestslmaspectaudit_configurationitem.getMendixObject().getId());
	}

	/**
	 * @return value of RequestSLMAspectAudit_Holidays_Group
	 */
	public final businesshours.proxies.Holidays_Group getRequestSLMAspectAudit_Holidays_Group() throws com.mendix.core.CoreException
	{
		return getRequestSLMAspectAudit_Holidays_Group(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestSLMAspectAudit_Holidays_Group
	 */
	public final businesshours.proxies.Holidays_Group getRequestSLMAspectAudit_Holidays_Group(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		businesshours.proxies.Holidays_Group result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestSLMAspectAudit_Holidays_Group.toString());
		if (identifier != null)
			result = businesshours.proxies.Holidays_Group.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RequestSLMAspectAudit_Holidays_Group
	 * @param requestslmaspectaudit_holidays_group
	 */
	public final void setRequestSLMAspectAudit_Holidays_Group(businesshours.proxies.Holidays_Group requestslmaspectaudit_holidays_group)
	{
		setRequestSLMAspectAudit_Holidays_Group(getContext(), requestslmaspectaudit_holidays_group);
	}

	/**
	 * Set value of RequestSLMAspectAudit_Holidays_Group
	 * @param context
	 * @param requestslmaspectaudit_holidays_group
	 */
	public final void setRequestSLMAspectAudit_Holidays_Group(com.mendix.systemwideinterfaces.core.IContext context, businesshours.proxies.Holidays_Group requestslmaspectaudit_holidays_group)
	{
		if (requestslmaspectaudit_holidays_group == null)
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_Holidays_Group.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_Holidays_Group.toString(), requestslmaspectaudit_holidays_group.getMendixObject().getId());
	}

	/**
	 * @return value of RequestSLMAspectAudit_Business_Time_Group
	 */
	public final businesshours.proxies.Business_Time_Group getRequestSLMAspectAudit_Business_Time_Group() throws com.mendix.core.CoreException
	{
		return getRequestSLMAspectAudit_Business_Time_Group(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestSLMAspectAudit_Business_Time_Group
	 */
	public final businesshours.proxies.Business_Time_Group getRequestSLMAspectAudit_Business_Time_Group(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		businesshours.proxies.Business_Time_Group result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestSLMAspectAudit_Business_Time_Group.toString());
		if (identifier != null)
			result = businesshours.proxies.Business_Time_Group.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RequestSLMAspectAudit_Business_Time_Group
	 * @param requestslmaspectaudit_business_time_group
	 */
	public final void setRequestSLMAspectAudit_Business_Time_Group(businesshours.proxies.Business_Time_Group requestslmaspectaudit_business_time_group)
	{
		setRequestSLMAspectAudit_Business_Time_Group(getContext(), requestslmaspectaudit_business_time_group);
	}

	/**
	 * Set value of RequestSLMAspectAudit_Business_Time_Group
	 * @param context
	 * @param requestslmaspectaudit_business_time_group
	 */
	public final void setRequestSLMAspectAudit_Business_Time_Group(com.mendix.systemwideinterfaces.core.IContext context, businesshours.proxies.Business_Time_Group requestslmaspectaudit_business_time_group)
	{
		if (requestslmaspectaudit_business_time_group == null)
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_Business_Time_Group.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_Business_Time_Group.toString(), requestslmaspectaudit_business_time_group.getMendixObject().getId());
	}

	/**
	 * @return value of RequestSLMAspectAudit_Matrix
	 */
	public final statetransition.proxies.Matrix getRequestSLMAspectAudit_Matrix() throws com.mendix.core.CoreException
	{
		return getRequestSLMAspectAudit_Matrix(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestSLMAspectAudit_Matrix
	 */
	public final statetransition.proxies.Matrix getRequestSLMAspectAudit_Matrix(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		statetransition.proxies.Matrix result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestSLMAspectAudit_Matrix.toString());
		if (identifier != null)
			result = statetransition.proxies.Matrix.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RequestSLMAspectAudit_Matrix
	 * @param requestslmaspectaudit_matrix
	 */
	public final void setRequestSLMAspectAudit_Matrix(statetransition.proxies.Matrix requestslmaspectaudit_matrix)
	{
		setRequestSLMAspectAudit_Matrix(getContext(), requestslmaspectaudit_matrix);
	}

	/**
	 * Set value of RequestSLMAspectAudit_Matrix
	 * @param context
	 * @param requestslmaspectaudit_matrix
	 */
	public final void setRequestSLMAspectAudit_Matrix(com.mendix.systemwideinterfaces.core.IContext context, statetransition.proxies.Matrix requestslmaspectaudit_matrix)
	{
		if (requestslmaspectaudit_matrix == null)
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_Matrix.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_Matrix.toString(), requestslmaspectaudit_matrix.getMendixObject().getId());
	}

	/**
	 * @return value of RequestSLMAspectAudit_Person
	 */
	public final nap.proxies.Person getRequestSLMAspectAudit_Person() throws com.mendix.core.CoreException
	{
		return getRequestSLMAspectAudit_Person(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestSLMAspectAudit_Person
	 */
	public final nap.proxies.Person getRequestSLMAspectAudit_Person(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		nap.proxies.Person result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestSLMAspectAudit_Person.toString());
		if (identifier != null)
			result = nap.proxies.Person.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RequestSLMAspectAudit_Person
	 * @param requestslmaspectaudit_person
	 */
	public final void setRequestSLMAspectAudit_Person(nap.proxies.Person requestslmaspectaudit_person)
	{
		setRequestSLMAspectAudit_Person(getContext(), requestslmaspectaudit_person);
	}

	/**
	 * Set value of RequestSLMAspectAudit_Person
	 * @param context
	 * @param requestslmaspectaudit_person
	 */
	public final void setRequestSLMAspectAudit_Person(com.mendix.systemwideinterfaces.core.IContext context, nap.proxies.Person requestslmaspectaudit_person)
	{
		if (requestslmaspectaudit_person == null)
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_Person.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RequestSLMAspectAudit_Person.toString(), requestslmaspectaudit_person.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return requestSLMAspectAuditMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final process.proxies.RequestSLMAspectAudit that = (process.proxies.RequestSLMAspectAudit) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Process.RequestSLMAspectAudit";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
