// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package process.proxies;

public enum RequestCreation
{
	New_Request(new java.lang.String[][] { new java.lang.String[] { "en_US", "New Request" }, new java.lang.String[] { "nl_NL", "Nieuw verzoek" }, new java.lang.String[] { "de_DE", "Neuer Request" } }),
	Accepted_Request(new java.lang.String[][] { new java.lang.String[] { "en_US", "Accepted Request" }, new java.lang.String[] { "nl_NL", "Geaccepteerd verzoek" }, new java.lang.String[] { "de_DE", "Anfrage akzeptieren" } }),
	Closed_Request(new java.lang.String[][] { new java.lang.String[] { "en_US", "Closed Request" }, new java.lang.String[] { "nl_NL", "Gesloten verzoek" }, new java.lang.String[] { "de_DE", "Geschlossene Anfrage" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private RequestCreation(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
