// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package process.proxies;

public class RequestEventDelayedInterfaceHandling
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject requestEventDelayedInterfaceHandlingMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Process.RequestEventDelayedInterfaceHandling";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Handled("Handled"),
		RequestEventDelayedInterfaceHandling_RequestEvent("Process.RequestEventDelayedInterfaceHandling_RequestEvent"),
		RequestEventDelayedInterfaceHandling_ExternalReference("Process.RequestEventDelayedInterfaceHandling_ExternalReference"),
		RequestEventDelayedInterfaceHandling_ResultingRequestEvent("Process.RequestEventDelayedInterfaceHandling_ResultingRequestEvent"),
		RequestEventDelayedInterfaceHandling_InterfaceConfiguration("Process.RequestEventDelayedInterfaceHandling_InterfaceConfiguration"),
		RequestEventDelayedInterfaceHandling_TriggerSetup("Process.RequestEventDelayedInterfaceHandling_TriggerSetup");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RequestEventDelayedInterfaceHandling(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Process.RequestEventDelayedInterfaceHandling"));
	}

	protected RequestEventDelayedInterfaceHandling(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject requestEventDelayedInterfaceHandlingMendixObject)
	{
		if (requestEventDelayedInterfaceHandlingMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Process.RequestEventDelayedInterfaceHandling", requestEventDelayedInterfaceHandlingMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Process.RequestEventDelayedInterfaceHandling");

		this.requestEventDelayedInterfaceHandlingMendixObject = requestEventDelayedInterfaceHandlingMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'RequestEventDelayedInterfaceHandling.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static process.proxies.RequestEventDelayedInterfaceHandling initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return process.proxies.RequestEventDelayedInterfaceHandling.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static process.proxies.RequestEventDelayedInterfaceHandling initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new process.proxies.RequestEventDelayedInterfaceHandling(context, mendixObject);
	}

	public static process.proxies.RequestEventDelayedInterfaceHandling load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return process.proxies.RequestEventDelayedInterfaceHandling.initialize(context, mendixObject);
	}

	public static java.util.List<process.proxies.RequestEventDelayedInterfaceHandling> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<process.proxies.RequestEventDelayedInterfaceHandling> result = new java.util.ArrayList<process.proxies.RequestEventDelayedInterfaceHandling>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Process.RequestEventDelayedInterfaceHandling" + xpathConstraint))
			result.add(process.proxies.RequestEventDelayedInterfaceHandling.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Handled
	 */
	public final java.lang.Boolean getHandled()
	{
		return getHandled(getContext());
	}

	/**
	 * @param context
	 * @return value of Handled
	 */
	public final java.lang.Boolean getHandled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Handled.toString());
	}

	/**
	 * Set value of Handled
	 * @param handled
	 */
	public final void setHandled(java.lang.Boolean handled)
	{
		setHandled(getContext(), handled);
	}

	/**
	 * Set value of Handled
	 * @param context
	 * @param handled
	 */
	public final void setHandled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean handled)
	{
		getMendixObject().setValue(context, MemberNames.Handled.toString(), handled);
	}

	/**
	 * @return value of RequestEventDelayedInterfaceHandling_RequestEvent
	 */
	public final process.proxies.RequestEvent getRequestEventDelayedInterfaceHandling_RequestEvent() throws com.mendix.core.CoreException
	{
		return getRequestEventDelayedInterfaceHandling_RequestEvent(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestEventDelayedInterfaceHandling_RequestEvent
	 */
	public final process.proxies.RequestEvent getRequestEventDelayedInterfaceHandling_RequestEvent(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		process.proxies.RequestEvent result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestEventDelayedInterfaceHandling_RequestEvent.toString());
		if (identifier != null)
			result = process.proxies.RequestEvent.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RequestEventDelayedInterfaceHandling_RequestEvent
	 * @param requesteventdelayedinterfacehandling_requestevent
	 */
	public final void setRequestEventDelayedInterfaceHandling_RequestEvent(process.proxies.RequestEvent requesteventdelayedinterfacehandling_requestevent)
	{
		setRequestEventDelayedInterfaceHandling_RequestEvent(getContext(), requesteventdelayedinterfacehandling_requestevent);
	}

	/**
	 * Set value of RequestEventDelayedInterfaceHandling_RequestEvent
	 * @param context
	 * @param requesteventdelayedinterfacehandling_requestevent
	 */
	public final void setRequestEventDelayedInterfaceHandling_RequestEvent(com.mendix.systemwideinterfaces.core.IContext context, process.proxies.RequestEvent requesteventdelayedinterfacehandling_requestevent)
	{
		if (requesteventdelayedinterfacehandling_requestevent == null)
			getMendixObject().setValue(context, MemberNames.RequestEventDelayedInterfaceHandling_RequestEvent.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RequestEventDelayedInterfaceHandling_RequestEvent.toString(), requesteventdelayedinterfacehandling_requestevent.getMendixObject().getId());
	}

	/**
	 * @return value of RequestEventDelayedInterfaceHandling_ExternalReference
	 */
	public final process.proxies.ExternalReference getRequestEventDelayedInterfaceHandling_ExternalReference() throws com.mendix.core.CoreException
	{
		return getRequestEventDelayedInterfaceHandling_ExternalReference(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestEventDelayedInterfaceHandling_ExternalReference
	 */
	public final process.proxies.ExternalReference getRequestEventDelayedInterfaceHandling_ExternalReference(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		process.proxies.ExternalReference result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestEventDelayedInterfaceHandling_ExternalReference.toString());
		if (identifier != null)
			result = process.proxies.ExternalReference.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RequestEventDelayedInterfaceHandling_ExternalReference
	 * @param requesteventdelayedinterfacehandling_externalreference
	 */
	public final void setRequestEventDelayedInterfaceHandling_ExternalReference(process.proxies.ExternalReference requesteventdelayedinterfacehandling_externalreference)
	{
		setRequestEventDelayedInterfaceHandling_ExternalReference(getContext(), requesteventdelayedinterfacehandling_externalreference);
	}

	/**
	 * Set value of RequestEventDelayedInterfaceHandling_ExternalReference
	 * @param context
	 * @param requesteventdelayedinterfacehandling_externalreference
	 */
	public final void setRequestEventDelayedInterfaceHandling_ExternalReference(com.mendix.systemwideinterfaces.core.IContext context, process.proxies.ExternalReference requesteventdelayedinterfacehandling_externalreference)
	{
		if (requesteventdelayedinterfacehandling_externalreference == null)
			getMendixObject().setValue(context, MemberNames.RequestEventDelayedInterfaceHandling_ExternalReference.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RequestEventDelayedInterfaceHandling_ExternalReference.toString(), requesteventdelayedinterfacehandling_externalreference.getMendixObject().getId());
	}

	/**
	 * @return value of RequestEventDelayedInterfaceHandling_ResultingRequestEvent
	 */
	public final process.proxies.RequestEvent getRequestEventDelayedInterfaceHandling_ResultingRequestEvent() throws com.mendix.core.CoreException
	{
		return getRequestEventDelayedInterfaceHandling_ResultingRequestEvent(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestEventDelayedInterfaceHandling_ResultingRequestEvent
	 */
	public final process.proxies.RequestEvent getRequestEventDelayedInterfaceHandling_ResultingRequestEvent(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		process.proxies.RequestEvent result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestEventDelayedInterfaceHandling_ResultingRequestEvent.toString());
		if (identifier != null)
			result = process.proxies.RequestEvent.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RequestEventDelayedInterfaceHandling_ResultingRequestEvent
	 * @param requesteventdelayedinterfacehandling_resultingrequestevent
	 */
	public final void setRequestEventDelayedInterfaceHandling_ResultingRequestEvent(process.proxies.RequestEvent requesteventdelayedinterfacehandling_resultingrequestevent)
	{
		setRequestEventDelayedInterfaceHandling_ResultingRequestEvent(getContext(), requesteventdelayedinterfacehandling_resultingrequestevent);
	}

	/**
	 * Set value of RequestEventDelayedInterfaceHandling_ResultingRequestEvent
	 * @param context
	 * @param requesteventdelayedinterfacehandling_resultingrequestevent
	 */
	public final void setRequestEventDelayedInterfaceHandling_ResultingRequestEvent(com.mendix.systemwideinterfaces.core.IContext context, process.proxies.RequestEvent requesteventdelayedinterfacehandling_resultingrequestevent)
	{
		if (requesteventdelayedinterfacehandling_resultingrequestevent == null)
			getMendixObject().setValue(context, MemberNames.RequestEventDelayedInterfaceHandling_ResultingRequestEvent.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RequestEventDelayedInterfaceHandling_ResultingRequestEvent.toString(), requesteventdelayedinterfacehandling_resultingrequestevent.getMendixObject().getId());
	}

	/**
	 * @return value of RequestEventDelayedInterfaceHandling_InterfaceConfiguration
	 */
	public final interfaceconfiguration.proxies.InterfaceConfiguration getRequestEventDelayedInterfaceHandling_InterfaceConfiguration() throws com.mendix.core.CoreException
	{
		return getRequestEventDelayedInterfaceHandling_InterfaceConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestEventDelayedInterfaceHandling_InterfaceConfiguration
	 */
	public final interfaceconfiguration.proxies.InterfaceConfiguration getRequestEventDelayedInterfaceHandling_InterfaceConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceconfiguration.proxies.InterfaceConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestEventDelayedInterfaceHandling_InterfaceConfiguration.toString());
		if (identifier != null)
			result = interfaceconfiguration.proxies.InterfaceConfiguration.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RequestEventDelayedInterfaceHandling_InterfaceConfiguration
	 * @param requesteventdelayedinterfacehandling_interfaceconfiguration
	 */
	public final void setRequestEventDelayedInterfaceHandling_InterfaceConfiguration(interfaceconfiguration.proxies.InterfaceConfiguration requesteventdelayedinterfacehandling_interfaceconfiguration)
	{
		setRequestEventDelayedInterfaceHandling_InterfaceConfiguration(getContext(), requesteventdelayedinterfacehandling_interfaceconfiguration);
	}

	/**
	 * Set value of RequestEventDelayedInterfaceHandling_InterfaceConfiguration
	 * @param context
	 * @param requesteventdelayedinterfacehandling_interfaceconfiguration
	 */
	public final void setRequestEventDelayedInterfaceHandling_InterfaceConfiguration(com.mendix.systemwideinterfaces.core.IContext context, interfaceconfiguration.proxies.InterfaceConfiguration requesteventdelayedinterfacehandling_interfaceconfiguration)
	{
		if (requesteventdelayedinterfacehandling_interfaceconfiguration == null)
			getMendixObject().setValue(context, MemberNames.RequestEventDelayedInterfaceHandling_InterfaceConfiguration.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RequestEventDelayedInterfaceHandling_InterfaceConfiguration.toString(), requesteventdelayedinterfacehandling_interfaceconfiguration.getMendixObject().getId());
	}

	/**
	 * @return value of RequestEventDelayedInterfaceHandling_TriggerSetup
	 */
	public final trigger.proxies.TriggerSetup getRequestEventDelayedInterfaceHandling_TriggerSetup() throws com.mendix.core.CoreException
	{
		return getRequestEventDelayedInterfaceHandling_TriggerSetup(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestEventDelayedInterfaceHandling_TriggerSetup
	 */
	public final trigger.proxies.TriggerSetup getRequestEventDelayedInterfaceHandling_TriggerSetup(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		trigger.proxies.TriggerSetup result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RequestEventDelayedInterfaceHandling_TriggerSetup.toString());
		if (identifier != null)
			result = trigger.proxies.TriggerSetup.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RequestEventDelayedInterfaceHandling_TriggerSetup
	 * @param requesteventdelayedinterfacehandling_triggersetup
	 */
	public final void setRequestEventDelayedInterfaceHandling_TriggerSetup(trigger.proxies.TriggerSetup requesteventdelayedinterfacehandling_triggersetup)
	{
		setRequestEventDelayedInterfaceHandling_TriggerSetup(getContext(), requesteventdelayedinterfacehandling_triggersetup);
	}

	/**
	 * Set value of RequestEventDelayedInterfaceHandling_TriggerSetup
	 * @param context
	 * @param requesteventdelayedinterfacehandling_triggersetup
	 */
	public final void setRequestEventDelayedInterfaceHandling_TriggerSetup(com.mendix.systemwideinterfaces.core.IContext context, trigger.proxies.TriggerSetup requesteventdelayedinterfacehandling_triggersetup)
	{
		if (requesteventdelayedinterfacehandling_triggersetup == null)
			getMendixObject().setValue(context, MemberNames.RequestEventDelayedInterfaceHandling_TriggerSetup.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RequestEventDelayedInterfaceHandling_TriggerSetup.toString(), requesteventdelayedinterfacehandling_triggersetup.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return requestEventDelayedInterfaceHandlingMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final process.proxies.RequestEventDelayedInterfaceHandling that = (process.proxies.RequestEventDelayedInterfaceHandling) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Process.RequestEventDelayedInterfaceHandling";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
