// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package statetransitiongraph.proxies;

public class PhasesInMatrix
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject phasesInMatrixMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "StateTransitionGraph.PhasesInMatrix";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Attribute("Attribute"),
		PhasesInMatrix_Matrix("StateTransitionGraph.PhasesInMatrix_Matrix"),
		PhasesInMatrix_Phase("StateTransitionGraph.PhasesInMatrix_Phase");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PhasesInMatrix(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "StateTransitionGraph.PhasesInMatrix"));
	}

	protected PhasesInMatrix(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject phasesInMatrixMendixObject)
	{
		if (phasesInMatrixMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("StateTransitionGraph.PhasesInMatrix", phasesInMatrixMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a StateTransitionGraph.PhasesInMatrix");

		this.phasesInMatrixMendixObject = phasesInMatrixMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PhasesInMatrix.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static statetransitiongraph.proxies.PhasesInMatrix initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return statetransitiongraph.proxies.PhasesInMatrix.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static statetransitiongraph.proxies.PhasesInMatrix initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new statetransitiongraph.proxies.PhasesInMatrix(context, mendixObject);
	}

	public static statetransitiongraph.proxies.PhasesInMatrix load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return statetransitiongraph.proxies.PhasesInMatrix.initialize(context, mendixObject);
	}

	public static java.util.List<statetransitiongraph.proxies.PhasesInMatrix> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<statetransitiongraph.proxies.PhasesInMatrix> result = new java.util.ArrayList<statetransitiongraph.proxies.PhasesInMatrix>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//StateTransitionGraph.PhasesInMatrix" + xpathConstraint))
			result.add(statetransitiongraph.proxies.PhasesInMatrix.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Attribute
	 */
	public final java.lang.Long getAttribute()
	{
		return getAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of Attribute
	 */
	public final java.lang.Long getAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Attribute.toString());
	}

	/**
	 * Set value of Attribute
	 * @param attribute
	 */
	public final void setAttribute(java.lang.Long attribute)
	{
		setAttribute(getContext(), attribute);
	}

	/**
	 * Set value of Attribute
	 * @param context
	 * @param attribute
	 */
	public final void setAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long attribute)
	{
		getMendixObject().setValue(context, MemberNames.Attribute.toString(), attribute);
	}

	/**
	 * @return value of PhasesInMatrix_Matrix
	 */
	public final statetransition.proxies.Matrix getPhasesInMatrix_Matrix() throws com.mendix.core.CoreException
	{
		return getPhasesInMatrix_Matrix(getContext());
	}

	/**
	 * @param context
	 * @return value of PhasesInMatrix_Matrix
	 */
	public final statetransition.proxies.Matrix getPhasesInMatrix_Matrix(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		statetransition.proxies.Matrix result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PhasesInMatrix_Matrix.toString());
		if (identifier != null)
			result = statetransition.proxies.Matrix.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PhasesInMatrix_Matrix
	 * @param phasesinmatrix_matrix
	 */
	public final void setPhasesInMatrix_Matrix(statetransition.proxies.Matrix phasesinmatrix_matrix)
	{
		setPhasesInMatrix_Matrix(getContext(), phasesinmatrix_matrix);
	}

	/**
	 * Set value of PhasesInMatrix_Matrix
	 * @param context
	 * @param phasesinmatrix_matrix
	 */
	public final void setPhasesInMatrix_Matrix(com.mendix.systemwideinterfaces.core.IContext context, statetransition.proxies.Matrix phasesinmatrix_matrix)
	{
		if (phasesinmatrix_matrix == null)
			getMendixObject().setValue(context, MemberNames.PhasesInMatrix_Matrix.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PhasesInMatrix_Matrix.toString(), phasesinmatrix_matrix.getMendixObject().getId());
	}

	/**
	 * @return value of PhasesInMatrix_Phase
	 */
	public final statetransition.proxies.Phase getPhasesInMatrix_Phase() throws com.mendix.core.CoreException
	{
		return getPhasesInMatrix_Phase(getContext());
	}

	/**
	 * @param context
	 * @return value of PhasesInMatrix_Phase
	 */
	public final statetransition.proxies.Phase getPhasesInMatrix_Phase(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		statetransition.proxies.Phase result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PhasesInMatrix_Phase.toString());
		if (identifier != null)
			result = statetransition.proxies.Phase.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PhasesInMatrix_Phase
	 * @param phasesinmatrix_phase
	 */
	public final void setPhasesInMatrix_Phase(statetransition.proxies.Phase phasesinmatrix_phase)
	{
		setPhasesInMatrix_Phase(getContext(), phasesinmatrix_phase);
	}

	/**
	 * Set value of PhasesInMatrix_Phase
	 * @param context
	 * @param phasesinmatrix_phase
	 */
	public final void setPhasesInMatrix_Phase(com.mendix.systemwideinterfaces.core.IContext context, statetransition.proxies.Phase phasesinmatrix_phase)
	{
		if (phasesinmatrix_phase == null)
			getMendixObject().setValue(context, MemberNames.PhasesInMatrix_Phase.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PhasesInMatrix_Phase.toString(), phasesinmatrix_phase.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return phasesInMatrixMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final statetransitiongraph.proxies.PhasesInMatrix that = (statetransitiongraph.proxies.PhasesInMatrix) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "StateTransitionGraph.PhasesInMatrix";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
