// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package replacement.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

public class ValidateString extends CustomJavaAction<java.lang.String>
{
	private java.lang.String SourceString;
	private java.util.List<IMendixObject> __MendixEntityList;
	private java.util.List<metamodel.proxies.MendixEntity> MendixEntityList;
	private java.lang.String ReplacementCodes;
	private java.lang.String CustomErrorMessage;

	public ValidateString(IContext context, java.lang.String SourceString, java.util.List<IMendixObject> MendixEntityList, java.lang.String ReplacementCodes, java.lang.String CustomErrorMessage)
	{
		super(context);
		this.SourceString = SourceString;
		this.__MendixEntityList = MendixEntityList;
		this.ReplacementCodes = ReplacementCodes;
		this.CustomErrorMessage = CustomErrorMessage;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		this.MendixEntityList = new java.util.ArrayList<metamodel.proxies.MendixEntity>();
		if (__MendixEntityList != null)
			for (IMendixObject __MendixEntityListElement : __MendixEntityList)
				this.MendixEntityList.add(metamodel.proxies.MendixEntity.initialize(getContext(), __MendixEntityListElement));

		// BEGIN USER CODE
		IContext context = this.getContext();
		
		String startSep = (String) Core.getConfiguration().getConstantValue("Replacement.StartSeparator");
		String stopSep = (String) Core.getConfiguration().getConstantValue("Replacement.StopSeparator");
		if (startSep==null) startSep="##";
		if (stopSep==null) stopSep="##";
		
		return nl.mansystems.replacement.Replacement.validateString(context, SourceString, startSep, stopSep, MendixEntityList, ReplacementCodes, CustomErrorMessage);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "ValidateString";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
