// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package interfaceldap.proxies;

public class PersonLDAPObjectClass
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject personLDAPObjectClassMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "InterfaceLDAP.PersonLDAPObjectClass";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ClassName("ClassName"),
		PersonLDAPObjectClass_PersonLDAPInbox("InterfaceLDAP.PersonLDAPObjectClass_PersonLDAPInbox");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PersonLDAPObjectClass(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "InterfaceLDAP.PersonLDAPObjectClass"));
	}

	protected PersonLDAPObjectClass(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject personLDAPObjectClassMendixObject)
	{
		if (personLDAPObjectClassMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("InterfaceLDAP.PersonLDAPObjectClass", personLDAPObjectClassMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a InterfaceLDAP.PersonLDAPObjectClass");

		this.personLDAPObjectClassMendixObject = personLDAPObjectClassMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PersonLDAPObjectClass.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static interfaceldap.proxies.PersonLDAPObjectClass initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return interfaceldap.proxies.PersonLDAPObjectClass.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static interfaceldap.proxies.PersonLDAPObjectClass initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new interfaceldap.proxies.PersonLDAPObjectClass(context, mendixObject);
	}

	public static interfaceldap.proxies.PersonLDAPObjectClass load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return interfaceldap.proxies.PersonLDAPObjectClass.initialize(context, mendixObject);
	}

	public static java.util.List<interfaceldap.proxies.PersonLDAPObjectClass> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<interfaceldap.proxies.PersonLDAPObjectClass> result = new java.util.ArrayList<interfaceldap.proxies.PersonLDAPObjectClass>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//InterfaceLDAP.PersonLDAPObjectClass" + xpathConstraint))
			result.add(interfaceldap.proxies.PersonLDAPObjectClass.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ClassName
	 */
	public final java.lang.String getClassName()
	{
		return getClassName(getContext());
	}

	/**
	 * @param context
	 * @return value of ClassName
	 */
	public final java.lang.String getClassName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ClassName.toString());
	}

	/**
	 * Set value of ClassName
	 * @param classname
	 */
	public final void setClassName(java.lang.String classname)
	{
		setClassName(getContext(), classname);
	}

	/**
	 * Set value of ClassName
	 * @param context
	 * @param classname
	 */
	public final void setClassName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String classname)
	{
		getMendixObject().setValue(context, MemberNames.ClassName.toString(), classname);
	}

	/**
	 * @return value of PersonLDAPObjectClass_PersonLDAPInbox
	 */
	public final interfaceldap.proxies.PersonLDAPInbox getPersonLDAPObjectClass_PersonLDAPInbox() throws com.mendix.core.CoreException
	{
		return getPersonLDAPObjectClass_PersonLDAPInbox(getContext());
	}

	/**
	 * @param context
	 * @return value of PersonLDAPObjectClass_PersonLDAPInbox
	 */
	public final interfaceldap.proxies.PersonLDAPInbox getPersonLDAPObjectClass_PersonLDAPInbox(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceldap.proxies.PersonLDAPInbox result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PersonLDAPObjectClass_PersonLDAPInbox.toString());
		if (identifier != null)
			result = interfaceldap.proxies.PersonLDAPInbox.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PersonLDAPObjectClass_PersonLDAPInbox
	 * @param personldapobjectclass_personldapinbox
	 */
	public final void setPersonLDAPObjectClass_PersonLDAPInbox(interfaceldap.proxies.PersonLDAPInbox personldapobjectclass_personldapinbox)
	{
		setPersonLDAPObjectClass_PersonLDAPInbox(getContext(), personldapobjectclass_personldapinbox);
	}

	/**
	 * Set value of PersonLDAPObjectClass_PersonLDAPInbox
	 * @param context
	 * @param personldapobjectclass_personldapinbox
	 */
	public final void setPersonLDAPObjectClass_PersonLDAPInbox(com.mendix.systemwideinterfaces.core.IContext context, interfaceldap.proxies.PersonLDAPInbox personldapobjectclass_personldapinbox)
	{
		if (personldapobjectclass_personldapinbox == null)
			getMendixObject().setValue(context, MemberNames.PersonLDAPObjectClass_PersonLDAPInbox.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PersonLDAPObjectClass_PersonLDAPInbox.toString(), personldapobjectclass_personldapinbox.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return personLDAPObjectClassMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final interfaceldap.proxies.PersonLDAPObjectClass that = (interfaceldap.proxies.PersonLDAPObjectClass) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "InterfaceLDAP.PersonLDAPObjectClass";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
