// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package interfaceldap.proxies;

public class PersonLDAPGroup
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject personLDAPGroupMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "InterfaceLDAP.PersonLDAPGroup";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		GroupName("GroupName"),
		PersonLDAPGroup_PersonLDAPInbox("InterfaceLDAP.PersonLDAPGroup_PersonLDAPInbox");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PersonLDAPGroup(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "InterfaceLDAP.PersonLDAPGroup"));
	}

	protected PersonLDAPGroup(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject personLDAPGroupMendixObject)
	{
		if (personLDAPGroupMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("InterfaceLDAP.PersonLDAPGroup", personLDAPGroupMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a InterfaceLDAP.PersonLDAPGroup");

		this.personLDAPGroupMendixObject = personLDAPGroupMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PersonLDAPGroup.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static interfaceldap.proxies.PersonLDAPGroup initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return interfaceldap.proxies.PersonLDAPGroup.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static interfaceldap.proxies.PersonLDAPGroup initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new interfaceldap.proxies.PersonLDAPGroup(context, mendixObject);
	}

	public static interfaceldap.proxies.PersonLDAPGroup load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return interfaceldap.proxies.PersonLDAPGroup.initialize(context, mendixObject);
	}

	public static java.util.List<interfaceldap.proxies.PersonLDAPGroup> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<interfaceldap.proxies.PersonLDAPGroup> result = new java.util.ArrayList<interfaceldap.proxies.PersonLDAPGroup>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//InterfaceLDAP.PersonLDAPGroup" + xpathConstraint))
			result.add(interfaceldap.proxies.PersonLDAPGroup.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of GroupName
	 */
	public final java.lang.String getGroupName()
	{
		return getGroupName(getContext());
	}

	/**
	 * @param context
	 * @return value of GroupName
	 */
	public final java.lang.String getGroupName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GroupName.toString());
	}

	/**
	 * Set value of GroupName
	 * @param groupname
	 */
	public final void setGroupName(java.lang.String groupname)
	{
		setGroupName(getContext(), groupname);
	}

	/**
	 * Set value of GroupName
	 * @param context
	 * @param groupname
	 */
	public final void setGroupName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String groupname)
	{
		getMendixObject().setValue(context, MemberNames.GroupName.toString(), groupname);
	}

	/**
	 * @return value of PersonLDAPGroup_PersonLDAPInbox
	 */
	public final interfaceldap.proxies.PersonLDAPInbox getPersonLDAPGroup_PersonLDAPInbox() throws com.mendix.core.CoreException
	{
		return getPersonLDAPGroup_PersonLDAPInbox(getContext());
	}

	/**
	 * @param context
	 * @return value of PersonLDAPGroup_PersonLDAPInbox
	 */
	public final interfaceldap.proxies.PersonLDAPInbox getPersonLDAPGroup_PersonLDAPInbox(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceldap.proxies.PersonLDAPInbox result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PersonLDAPGroup_PersonLDAPInbox.toString());
		if (identifier != null)
			result = interfaceldap.proxies.PersonLDAPInbox.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PersonLDAPGroup_PersonLDAPInbox
	 * @param personldapgroup_personldapinbox
	 */
	public final void setPersonLDAPGroup_PersonLDAPInbox(interfaceldap.proxies.PersonLDAPInbox personldapgroup_personldapinbox)
	{
		setPersonLDAPGroup_PersonLDAPInbox(getContext(), personldapgroup_personldapinbox);
	}

	/**
	 * Set value of PersonLDAPGroup_PersonLDAPInbox
	 * @param context
	 * @param personldapgroup_personldapinbox
	 */
	public final void setPersonLDAPGroup_PersonLDAPInbox(com.mendix.systemwideinterfaces.core.IContext context, interfaceldap.proxies.PersonLDAPInbox personldapgroup_personldapinbox)
	{
		if (personldapgroup_personldapinbox == null)
			getMendixObject().setValue(context, MemberNames.PersonLDAPGroup_PersonLDAPInbox.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PersonLDAPGroup_PersonLDAPInbox.toString(), personldapgroup_personldapinbox.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return personLDAPGroupMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final interfaceldap.proxies.PersonLDAPGroup that = (interfaceldap.proxies.PersonLDAPGroup) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "InterfaceLDAP.PersonLDAPGroup";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
