// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package scheduling.actions;

import java.io.InputStream;
import process.proxies.RequestAttachment;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

public class CopyTemplateRequestAttachmentToRequestAttachment extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __ParameterRequestTemplateAttachment;
	private scheduling.proxies.TemplateRequestAttachment ParameterRequestTemplateAttachment;

	public CopyTemplateRequestAttachmentToRequestAttachment(IContext context, IMendixObject ParameterRequestTemplateAttachment)
	{
		super(context);
		this.__ParameterRequestTemplateAttachment = ParameterRequestTemplateAttachment;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.ParameterRequestTemplateAttachment = __ParameterRequestTemplateAttachment == null ? null : scheduling.proxies.TemplateRequestAttachment.initialize(getContext(), __ParameterRequestTemplateAttachment);

		// BEGIN USER CODE
		IContext context = this.getContext();

		Core.getLogger("Process").trace("Copying RequestTemplateAttachment " + ParameterRequestTemplateAttachment.getName(context));
		RequestAttachment requestAttachment = new RequestAttachment(context);
		InputStream inputStream = Core.getFileDocumentContent(context, ParameterRequestTemplateAttachment.getMendixObject());
		Core.storeFileDocumentContent(context, requestAttachment.getMendixObject(), inputStream);
		requestAttachment.setName(ParameterRequestTemplateAttachment.getName(context));
		requestAttachment.setDescription(ParameterRequestTemplateAttachment.getDescription(context));
		requestAttachment.setAttachmentName(ParameterRequestTemplateAttachment.getAttachmentName(context));
		Core.commit(context, requestAttachment.getMendixObject());
		return requestAttachment.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "CopyTemplateRequestAttachmentToRequestAttachment";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
