// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package queryrequests.proxies;

/**
 * #218361 - Made persistent for the grid to be able to chunk the data
 */
public class SearchContainer
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject searchContainerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "QueryRequests.SearchContainer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SearchString("SearchString"),
		UU95_TypeReference("UU95_TypeReference"),
		UU95_HelperTypeReference("UU95_HelperTypeReference"),
		UserID("UserID"),
		QueryPart_Entity("QueryRequests.QueryPart_Entity"),
		UU95_SearchContainer_Person("QueryRequests.UU95_SearchContainer_Person");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SearchContainer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "QueryRequests.SearchContainer"));
	}

	protected SearchContainer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject searchContainerMendixObject)
	{
		if (searchContainerMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("QueryRequests.SearchContainer", searchContainerMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a QueryRequests.SearchContainer");

		this.searchContainerMendixObject = searchContainerMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SearchContainer.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static queryrequests.proxies.SearchContainer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return queryrequests.proxies.SearchContainer.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static queryrequests.proxies.SearchContainer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new queryrequests.proxies.SearchContainer(context, mendixObject);
	}

	public static queryrequests.proxies.SearchContainer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return queryrequests.proxies.SearchContainer.initialize(context, mendixObject);
	}

	public static java.util.List<queryrequests.proxies.SearchContainer> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<queryrequests.proxies.SearchContainer> result = new java.util.ArrayList<queryrequests.proxies.SearchContainer>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//QueryRequests.SearchContainer" + xpathConstraint))
			result.add(queryrequests.proxies.SearchContainer.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of SearchString
	 */
	public final java.lang.String getSearchString()
	{
		return getSearchString(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchString
	 */
	public final java.lang.String getSearchString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SearchString.toString());
	}

	/**
	 * Set value of SearchString
	 * @param searchstring
	 */
	public final void setSearchString(java.lang.String searchstring)
	{
		setSearchString(getContext(), searchstring);
	}

	/**
	 * Set value of SearchString
	 * @param context
	 * @param searchstring
	 */
	public final void setSearchString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String searchstring)
	{
		getMendixObject().setValue(context, MemberNames.SearchString.toString(), searchstring);
	}

	/**
	 * Set value of UU95_TypeReference
	 * @param uu95_typereference
	 */
	public final metamodel.proxies.PrimitiveTypeEnum getUU95_TypeReference()
	{
		return getUU95_TypeReference(getContext());
	}

	/**
	 * @param context
	 * @return value of UU95_TypeReference
	 */
	public final metamodel.proxies.PrimitiveTypeEnum getUU95_TypeReference(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.UU95_TypeReference.toString());
		if (obj == null)
			return null;

		return metamodel.proxies.PrimitiveTypeEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of UU95_TypeReference
	 * @param uu95_typereference
	 */
	public final void setUU95_TypeReference(metamodel.proxies.PrimitiveTypeEnum uu95_typereference)
	{
		setUU95_TypeReference(getContext(), uu95_typereference);
	}

	/**
	 * Set value of UU95_TypeReference
	 * @param context
	 * @param uu95_typereference
	 */
	public final void setUU95_TypeReference(com.mendix.systemwideinterfaces.core.IContext context, metamodel.proxies.PrimitiveTypeEnum uu95_typereference)
	{
		if (uu95_typereference != null)
			getMendixObject().setValue(context, MemberNames.UU95_TypeReference.toString(), uu95_typereference.toString());
		else
			getMendixObject().setValue(context, MemberNames.UU95_TypeReference.toString(), null);
	}

	/**
	 * Set value of UU95_HelperTypeReference
	 * @param uu95_helpertypereference
	 */
	public final metamodel.proxies.PrimitiveTypeEnum getUU95_HelperTypeReference()
	{
		return getUU95_HelperTypeReference(getContext());
	}

	/**
	 * @param context
	 * @return value of UU95_HelperTypeReference
	 */
	public final metamodel.proxies.PrimitiveTypeEnum getUU95_HelperTypeReference(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.UU95_HelperTypeReference.toString());
		if (obj == null)
			return null;

		return metamodel.proxies.PrimitiveTypeEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of UU95_HelperTypeReference
	 * @param uu95_helpertypereference
	 */
	public final void setUU95_HelperTypeReference(metamodel.proxies.PrimitiveTypeEnum uu95_helpertypereference)
	{
		setUU95_HelperTypeReference(getContext(), uu95_helpertypereference);
	}

	/**
	 * Set value of UU95_HelperTypeReference
	 * @param context
	 * @param uu95_helpertypereference
	 */
	public final void setUU95_HelperTypeReference(com.mendix.systemwideinterfaces.core.IContext context, metamodel.proxies.PrimitiveTypeEnum uu95_helpertypereference)
	{
		if (uu95_helpertypereference != null)
			getMendixObject().setValue(context, MemberNames.UU95_HelperTypeReference.toString(), uu95_helpertypereference.toString());
		else
			getMendixObject().setValue(context, MemberNames.UU95_HelperTypeReference.toString(), null);
	}

	/**
	 * @return value of UserID
	 */
	public final java.lang.String getUserID()
	{
		return getUserID(getContext());
	}

	/**
	 * @param context
	 * @return value of UserID
	 */
	public final java.lang.String getUserID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserID.toString());
	}

	/**
	 * Set value of UserID
	 * @param userid
	 */
	public final void setUserID(java.lang.String userid)
	{
		setUserID(getContext(), userid);
	}

	/**
	 * Set value of UserID
	 * @param context
	 * @param userid
	 */
	public final void setUserID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String userid)
	{
		getMendixObject().setValue(context, MemberNames.UserID.toString(), userid);
	}

	/**
	 * @return value of QueryPart_Entity
	 */
	public final queryrequests.proxies.QueryPart getQueryPart_Entity() throws com.mendix.core.CoreException
	{
		return getQueryPart_Entity(getContext());
	}

	/**
	 * @param context
	 * @return value of QueryPart_Entity
	 */
	public final queryrequests.proxies.QueryPart getQueryPart_Entity(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		queryrequests.proxies.QueryPart result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.QueryPart_Entity.toString());
		if (identifier != null)
			result = queryrequests.proxies.QueryPart.load(context, identifier);
		return result;
	}

	/**
	 * Set value of QueryPart_Entity
	 * @param querypart_entity
	 */
	public final void setQueryPart_Entity(queryrequests.proxies.QueryPart querypart_entity)
	{
		setQueryPart_Entity(getContext(), querypart_entity);
	}

	/**
	 * Set value of QueryPart_Entity
	 * @param context
	 * @param querypart_entity
	 */
	public final void setQueryPart_Entity(com.mendix.systemwideinterfaces.core.IContext context, queryrequests.proxies.QueryPart querypart_entity)
	{
		if (querypart_entity == null)
			getMendixObject().setValue(context, MemberNames.QueryPart_Entity.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.QueryPart_Entity.toString(), querypart_entity.getMendixObject().getId());
	}

	/**
	 * @return value of UU95_SearchContainer_Person
	 */
	public final nap.proxies.Person getUU95_SearchContainer_Person() throws com.mendix.core.CoreException
	{
		return getUU95_SearchContainer_Person(getContext());
	}

	/**
	 * @param context
	 * @return value of UU95_SearchContainer_Person
	 */
	public final nap.proxies.Person getUU95_SearchContainer_Person(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		nap.proxies.Person result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UU95_SearchContainer_Person.toString());
		if (identifier != null)
			result = nap.proxies.Person.load(context, identifier);
		return result;
	}

	/**
	 * Set value of UU95_SearchContainer_Person
	 * @param uu95_searchcontainer_person
	 */
	public final void setUU95_SearchContainer_Person(nap.proxies.Person uu95_searchcontainer_person)
	{
		setUU95_SearchContainer_Person(getContext(), uu95_searchcontainer_person);
	}

	/**
	 * Set value of UU95_SearchContainer_Person
	 * @param context
	 * @param uu95_searchcontainer_person
	 */
	public final void setUU95_SearchContainer_Person(com.mendix.systemwideinterfaces.core.IContext context, nap.proxies.Person uu95_searchcontainer_person)
	{
		if (uu95_searchcontainer_person == null)
			getMendixObject().setValue(context, MemberNames.UU95_SearchContainer_Person.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.UU95_SearchContainer_Person.toString(), uu95_searchcontainer_person.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return searchContainerMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final queryrequests.proxies.SearchContainer that = (queryrequests.proxies.SearchContainer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "QueryRequests.SearchContainer";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
