// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package customlvnl.proxies;

public class ImportLog
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject importLogMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CustomLVNL.ImportLog";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ProcessDate("ProcessDate"),
		StatusNote("StatusNote"),
		ProcessStatus("ProcessStatus"),
		Number("Number"),
		Validated("Validated"),
		Processed("Processed"),
		ImportType("ImportType"),
		ImportLog_ImportRun("CustomLVNL.ImportLog_ImportRun");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ImportLog(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CustomLVNL.ImportLog"));
	}

	protected ImportLog(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject importLogMendixObject)
	{
		if (importLogMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("CustomLVNL.ImportLog", importLogMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CustomLVNL.ImportLog");

		this.importLogMendixObject = importLogMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ImportLog.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static customlvnl.proxies.ImportLog initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return customlvnl.proxies.ImportLog.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static customlvnl.proxies.ImportLog initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("CustomLVNL.AttributeImport", mendixObject.getType()))
			return customlvnl.proxies.AttributeImport.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("CustomLVNL.CIImport", mendixObject.getType()))
			return customlvnl.proxies.CIImport.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("CustomLVNL.CITYpeOrganizationImport", mendixObject.getType()))
			return customlvnl.proxies.CITYpeOrganizationImport.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("CustomLVNL.CITypeImport", mendixObject.getType()))
			return customlvnl.proxies.CITypeImport.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("CustomLVNL.NotesImport", mendixObject.getType()))
			return customlvnl.proxies.NotesImport.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("CustomLVNL.OrganizationPeopleImport", mendixObject.getType()))
			return customlvnl.proxies.OrganizationPeopleImport.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("CustomLVNL.RelationsImport", mendixObject.getType()))
			return customlvnl.proxies.RelationsImport.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("CustomLVNL.SupposedSystemImport", mendixObject.getType()))
			return customlvnl.proxies.SupposedSystemImport.initialize(context, mendixObject);

		return new customlvnl.proxies.ImportLog(context, mendixObject);
	}

	public static customlvnl.proxies.ImportLog load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return customlvnl.proxies.ImportLog.initialize(context, mendixObject);
	}

	public static java.util.List<? extends customlvnl.proxies.ImportLog> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<customlvnl.proxies.ImportLog> result = new java.util.ArrayList<customlvnl.proxies.ImportLog>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CustomLVNL.ImportLog" + xpathConstraint))
			result.add(customlvnl.proxies.ImportLog.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ProcessDate
	 */
	public final java.util.Date getProcessDate()
	{
		return getProcessDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessDate
	 */
	public final java.util.Date getProcessDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ProcessDate.toString());
	}

	/**
	 * Set value of ProcessDate
	 * @param processdate
	 */
	public final void setProcessDate(java.util.Date processdate)
	{
		setProcessDate(getContext(), processdate);
	}

	/**
	 * Set value of ProcessDate
	 * @param context
	 * @param processdate
	 */
	public final void setProcessDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date processdate)
	{
		getMendixObject().setValue(context, MemberNames.ProcessDate.toString(), processdate);
	}

	/**
	 * @return value of StatusNote
	 */
	public final java.lang.String getStatusNote()
	{
		return getStatusNote(getContext());
	}

	/**
	 * @param context
	 * @return value of StatusNote
	 */
	public final java.lang.String getStatusNote(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StatusNote.toString());
	}

	/**
	 * Set value of StatusNote
	 * @param statusnote
	 */
	public final void setStatusNote(java.lang.String statusnote)
	{
		setStatusNote(getContext(), statusnote);
	}

	/**
	 * Set value of StatusNote
	 * @param context
	 * @param statusnote
	 */
	public final void setStatusNote(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String statusnote)
	{
		getMendixObject().setValue(context, MemberNames.StatusNote.toString(), statusnote);
	}

	/**
	 * Set value of ProcessStatus
	 * @param processstatus
	 */
	public final customlvnl.proxies.ProcessStatus getProcessStatus()
	{
		return getProcessStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessStatus
	 */
	public final customlvnl.proxies.ProcessStatus getProcessStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ProcessStatus.toString());
		if (obj == null)
			return null;

		return customlvnl.proxies.ProcessStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ProcessStatus
	 * @param processstatus
	 */
	public final void setProcessStatus(customlvnl.proxies.ProcessStatus processstatus)
	{
		setProcessStatus(getContext(), processstatus);
	}

	/**
	 * Set value of ProcessStatus
	 * @param context
	 * @param processstatus
	 */
	public final void setProcessStatus(com.mendix.systemwideinterfaces.core.IContext context, customlvnl.proxies.ProcessStatus processstatus)
	{
		if (processstatus != null)
			getMendixObject().setValue(context, MemberNames.ProcessStatus.toString(), processstatus.toString());
		else
			getMendixObject().setValue(context, MemberNames.ProcessStatus.toString(), null);
	}

	/**
	 * @return value of Number
	 */
	public final java.lang.Long getNumber()
	{
		return getNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Number
	 */
	public final java.lang.Long getNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Number.toString());
	}

	/**
	 * Set value of Number
	 * @param number
	 */
	public final void setNumber(java.lang.Long number)
	{
		setNumber(getContext(), number);
	}

	/**
	 * Set value of Number
	 * @param context
	 * @param number
	 */
	public final void setNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long number)
	{
		getMendixObject().setValue(context, MemberNames.Number.toString(), number);
	}

	/**
	 * @return value of Validated
	 */
	public final java.lang.Boolean getValidated()
	{
		return getValidated(getContext());
	}

	/**
	 * @param context
	 * @return value of Validated
	 */
	public final java.lang.Boolean getValidated(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Validated.toString());
	}

	/**
	 * Set value of Validated
	 * @param validated
	 */
	public final void setValidated(java.lang.Boolean validated)
	{
		setValidated(getContext(), validated);
	}

	/**
	 * Set value of Validated
	 * @param context
	 * @param validated
	 */
	public final void setValidated(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean validated)
	{
		getMendixObject().setValue(context, MemberNames.Validated.toString(), validated);
	}

	/**
	 * @return value of Processed
	 */
	public final java.lang.Boolean getProcessed()
	{
		return getProcessed(getContext());
	}

	/**
	 * @param context
	 * @return value of Processed
	 */
	public final java.lang.Boolean getProcessed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Processed.toString());
	}

	/**
	 * Set value of Processed
	 * @param processed
	 */
	public final void setProcessed(java.lang.Boolean processed)
	{
		setProcessed(getContext(), processed);
	}

	/**
	 * Set value of Processed
	 * @param context
	 * @param processed
	 */
	public final void setProcessed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean processed)
	{
		getMendixObject().setValue(context, MemberNames.Processed.toString(), processed);
	}

	/**
	 * Set value of ImportType
	 * @param importtype
	 */
	public final customlvnl.proxies.ImportType getImportType()
	{
		return getImportType(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportType
	 */
	public final customlvnl.proxies.ImportType getImportType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ImportType.toString());
		if (obj == null)
			return null;

		return customlvnl.proxies.ImportType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ImportType
	 * @param importtype
	 */
	public final void setImportType(customlvnl.proxies.ImportType importtype)
	{
		setImportType(getContext(), importtype);
	}

	/**
	 * Set value of ImportType
	 * @param context
	 * @param importtype
	 */
	public final void setImportType(com.mendix.systemwideinterfaces.core.IContext context, customlvnl.proxies.ImportType importtype)
	{
		if (importtype != null)
			getMendixObject().setValue(context, MemberNames.ImportType.toString(), importtype.toString());
		else
			getMendixObject().setValue(context, MemberNames.ImportType.toString(), null);
	}

	/**
	 * @return value of ImportLog_ImportRun
	 */
	public final customlvnl.proxies.ImportRun getImportLog_ImportRun() throws com.mendix.core.CoreException
	{
		return getImportLog_ImportRun(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportLog_ImportRun
	 */
	public final customlvnl.proxies.ImportRun getImportLog_ImportRun(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		customlvnl.proxies.ImportRun result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ImportLog_ImportRun.toString());
		if (identifier != null)
			result = customlvnl.proxies.ImportRun.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ImportLog_ImportRun
	 * @param importlog_importrun
	 */
	public final void setImportLog_ImportRun(customlvnl.proxies.ImportRun importlog_importrun)
	{
		setImportLog_ImportRun(getContext(), importlog_importrun);
	}

	/**
	 * Set value of ImportLog_ImportRun
	 * @param context
	 * @param importlog_importrun
	 */
	public final void setImportLog_ImportRun(com.mendix.systemwideinterfaces.core.IContext context, customlvnl.proxies.ImportRun importlog_importrun)
	{
		if (importlog_importrun == null)
			getMendixObject().setValue(context, MemberNames.ImportLog_ImportRun.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ImportLog_ImportRun.toString(), importlog_importrun.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return importLogMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final customlvnl.proxies.ImportLog that = (customlvnl.proxies.ImportLog) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CustomLVNL.ImportLog";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
