// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package customlvnl.proxies;

/**
 * 1179278: Filter on Person in reporting module
 */
public class PersonFilter extends reporting.proxies.ReportFilter
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CustomLVNL.PersonFilter";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FilterType("FilterType"),
		ReadableString("ReadableString"),
		Editable("Editable"),
		IsDefault("IsDefault"),
		IsCopyOfDefault("IsCopyOfDefault"),
		FilterID("FilterID"),
		FilterDefinitionName("FilterDefinitionName"),
		PersonFilter_Person("CustomLVNL.PersonFilter_Person"),
		ReportFilter_ReportSelect("Reporting.ReportFilter_ReportSelect"),
		ReportFilter_Definition("Reporting.ReportFilter_Definition"),
		ReportFilter_User("Reporting.ReportFilter_User");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PersonFilter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CustomLVNL.PersonFilter"));
	}

	protected PersonFilter(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject personFilterMendixObject)
	{
		super(context, personFilterMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("CustomLVNL.PersonFilter", personFilterMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CustomLVNL.PersonFilter");
	}

	/**
	 * @deprecated Use 'PersonFilter.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static customlvnl.proxies.PersonFilter initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return customlvnl.proxies.PersonFilter.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static customlvnl.proxies.PersonFilter initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new customlvnl.proxies.PersonFilter(context, mendixObject);
	}

	public static customlvnl.proxies.PersonFilter load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return customlvnl.proxies.PersonFilter.initialize(context, mendixObject);
	}

	public static java.util.List<customlvnl.proxies.PersonFilter> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<customlvnl.proxies.PersonFilter> result = new java.util.ArrayList<customlvnl.proxies.PersonFilter>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CustomLVNL.PersonFilter" + xpathConstraint))
			result.add(customlvnl.proxies.PersonFilter.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of PersonFilter_Person
	 */
	public final java.util.List<nap.proxies.Person> getPersonFilter_Person() throws com.mendix.core.CoreException
	{
		return getPersonFilter_Person(getContext());
	}

	/**
	 * @param context
	 * @return value of PersonFilter_Person
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<nap.proxies.Person> getPersonFilter_Person(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<nap.proxies.Person> result = new java.util.ArrayList<nap.proxies.Person>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.PersonFilter_Person.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(nap.proxies.Person.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of PersonFilter_Person
	 * @param personfilter_person
	 */
	public final void setPersonFilter_Person(java.util.List<nap.proxies.Person> personfilter_person)
	{
		setPersonFilter_Person(getContext(), personfilter_person);
	}

	/**
	 * Set value of PersonFilter_Person
	 * @param context
	 * @param personfilter_person
	 */
	public final void setPersonFilter_Person(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<nap.proxies.Person> personfilter_person)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (nap.proxies.Person proxyObject : personfilter_person)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.PersonFilter_Person.toString(), identifiers);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final customlvnl.proxies.PersonFilter that = (customlvnl.proxies.PersonFilter) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CustomLVNL.PersonFilter";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
