// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package customlvnl.proxies;

public class RelationsImport extends customlvnl.proxies.ImportLog
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CustomLVNL.RelationsImport";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CIName("CIName"),
		CIType("CIType"),
		RelatedCIName("RelatedCIName"),
		RelatedCIType("RelatedCIType"),
		RelationType("RelationType"),
		Delete("Delete"),
		ProcessDate("ProcessDate"),
		StatusNote("StatusNote"),
		ProcessStatus("ProcessStatus"),
		Number("Number"),
		Validated("Validated"),
		Processed("Processed"),
		ImportType("ImportType"),
		RelationsImport_CIImport("CustomLVNL.RelationsImport_CIImport"),
		ImportLog_ImportRun("CustomLVNL.ImportLog_ImportRun");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RelationsImport(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CustomLVNL.RelationsImport"));
	}

	protected RelationsImport(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject relationsImportMendixObject)
	{
		super(context, relationsImportMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("CustomLVNL.RelationsImport", relationsImportMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CustomLVNL.RelationsImport");
	}

	/**
	 * @deprecated Use 'RelationsImport.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static customlvnl.proxies.RelationsImport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return customlvnl.proxies.RelationsImport.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static customlvnl.proxies.RelationsImport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new customlvnl.proxies.RelationsImport(context, mendixObject);
	}

	public static customlvnl.proxies.RelationsImport load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return customlvnl.proxies.RelationsImport.initialize(context, mendixObject);
	}

	public static java.util.List<customlvnl.proxies.RelationsImport> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<customlvnl.proxies.RelationsImport> result = new java.util.ArrayList<customlvnl.proxies.RelationsImport>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CustomLVNL.RelationsImport" + xpathConstraint))
			result.add(customlvnl.proxies.RelationsImport.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of CIName
	 */
	public final java.lang.String getCIName()
	{
		return getCIName(getContext());
	}

	/**
	 * @param context
	 * @return value of CIName
	 */
	public final java.lang.String getCIName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CIName.toString());
	}

	/**
	 * Set value of CIName
	 * @param ciname
	 */
	public final void setCIName(java.lang.String ciname)
	{
		setCIName(getContext(), ciname);
	}

	/**
	 * Set value of CIName
	 * @param context
	 * @param ciname
	 */
	public final void setCIName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ciname)
	{
		getMendixObject().setValue(context, MemberNames.CIName.toString(), ciname);
	}

	/**
	 * @return value of CIType
	 */
	public final java.lang.String getCIType()
	{
		return getCIType(getContext());
	}

	/**
	 * @param context
	 * @return value of CIType
	 */
	public final java.lang.String getCIType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CIType.toString());
	}

	/**
	 * Set value of CIType
	 * @param citype
	 */
	public final void setCIType(java.lang.String citype)
	{
		setCIType(getContext(), citype);
	}

	/**
	 * Set value of CIType
	 * @param context
	 * @param citype
	 */
	public final void setCIType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String citype)
	{
		getMendixObject().setValue(context, MemberNames.CIType.toString(), citype);
	}

	/**
	 * @return value of RelatedCIName
	 */
	public final java.lang.String getRelatedCIName()
	{
		return getRelatedCIName(getContext());
	}

	/**
	 * @param context
	 * @return value of RelatedCIName
	 */
	public final java.lang.String getRelatedCIName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RelatedCIName.toString());
	}

	/**
	 * Set value of RelatedCIName
	 * @param relatedciname
	 */
	public final void setRelatedCIName(java.lang.String relatedciname)
	{
		setRelatedCIName(getContext(), relatedciname);
	}

	/**
	 * Set value of RelatedCIName
	 * @param context
	 * @param relatedciname
	 */
	public final void setRelatedCIName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String relatedciname)
	{
		getMendixObject().setValue(context, MemberNames.RelatedCIName.toString(), relatedciname);
	}

	/**
	 * @return value of RelatedCIType
	 */
	public final java.lang.String getRelatedCIType()
	{
		return getRelatedCIType(getContext());
	}

	/**
	 * @param context
	 * @return value of RelatedCIType
	 */
	public final java.lang.String getRelatedCIType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RelatedCIType.toString());
	}

	/**
	 * Set value of RelatedCIType
	 * @param relatedcitype
	 */
	public final void setRelatedCIType(java.lang.String relatedcitype)
	{
		setRelatedCIType(getContext(), relatedcitype);
	}

	/**
	 * Set value of RelatedCIType
	 * @param context
	 * @param relatedcitype
	 */
	public final void setRelatedCIType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String relatedcitype)
	{
		getMendixObject().setValue(context, MemberNames.RelatedCIType.toString(), relatedcitype);
	}

	/**
	 * @return value of RelationType
	 */
	public final java.lang.String getRelationType()
	{
		return getRelationType(getContext());
	}

	/**
	 * @param context
	 * @return value of RelationType
	 */
	public final java.lang.String getRelationType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RelationType.toString());
	}

	/**
	 * Set value of RelationType
	 * @param relationtype
	 */
	public final void setRelationType(java.lang.String relationtype)
	{
		setRelationType(getContext(), relationtype);
	}

	/**
	 * Set value of RelationType
	 * @param context
	 * @param relationtype
	 */
	public final void setRelationType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String relationtype)
	{
		getMendixObject().setValue(context, MemberNames.RelationType.toString(), relationtype);
	}

	/**
	 * @return value of Delete
	 */
	public final java.lang.String getDelete()
	{
		return getDelete(getContext());
	}

	/**
	 * @param context
	 * @return value of Delete
	 */
	public final java.lang.String getDelete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Delete.toString());
	}

	/**
	 * Set value of Delete
	 * @param delete
	 */
	public final void setDelete(java.lang.String delete)
	{
		setDelete(getContext(), delete);
	}

	/**
	 * Set value of Delete
	 * @param context
	 * @param delete
	 */
	public final void setDelete(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String delete)
	{
		getMendixObject().setValue(context, MemberNames.Delete.toString(), delete);
	}

	/**
	 * @return value of RelationsImport_CIImport
	 */
	public final customlvnl.proxies.CIImport getRelationsImport_CIImport() throws com.mendix.core.CoreException
	{
		return getRelationsImport_CIImport(getContext());
	}

	/**
	 * @param context
	 * @return value of RelationsImport_CIImport
	 */
	public final customlvnl.proxies.CIImport getRelationsImport_CIImport(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		customlvnl.proxies.CIImport result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RelationsImport_CIImport.toString());
		if (identifier != null)
			result = customlvnl.proxies.CIImport.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RelationsImport_CIImport
	 * @param relationsimport_ciimport
	 */
	public final void setRelationsImport_CIImport(customlvnl.proxies.CIImport relationsimport_ciimport)
	{
		setRelationsImport_CIImport(getContext(), relationsimport_ciimport);
	}

	/**
	 * Set value of RelationsImport_CIImport
	 * @param context
	 * @param relationsimport_ciimport
	 */
	public final void setRelationsImport_CIImport(com.mendix.systemwideinterfaces.core.IContext context, customlvnl.proxies.CIImport relationsimport_ciimport)
	{
		if (relationsimport_ciimport == null)
			getMendixObject().setValue(context, MemberNames.RelationsImport_CIImport.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RelationsImport_CIImport.toString(), relationsimport_ciimport.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final customlvnl.proxies.RelationsImport that = (customlvnl.proxies.RelationsImport) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CustomLVNL.RelationsImport";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
