// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package importexport.proxies;

public class ImportExportSetting extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ImportExport.ImportExportSetting";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Description("Description"),
		FileType("FileType"),
		ServerFolder("ServerFolder"),
		ImportType("ImportType"),
		ImportCreate("ImportCreate"),
		ImportUpdate("ImportUpdate"),
		DumpDate("DumpDate"),
		ShowAdvancedOptions("ShowAdvancedOptions"),
		ImportTestRun("ImportTestRun"),
		UseZip("UseZip"),
		UseDirectMendixIDs("UseDirectMendixIDs"),
		UseTranslatedMendixIDs("UseTranslatedMendixIDs"),
		ReferencesInline("ReferencesInline"),
		ImportReferenceSetInline("ImportReferenceSetInline"),
		ReferenceOrSetBothAsChild("ReferenceOrSetBothAsChild"),
		ImportNonDelayedRelations("ImportNonDelayedRelations"),
		ImportDelayedRelations("ImportDelayedRelations"),
		ImportMetaModelOnly("ImportMetaModelOnly"),
		ImportSkipMetaModel("ImportSkipMetaModel"),
		ImportFailAndStopOnErrors("ImportFailAndStopOnErrors"),
		SetDataAccess("SetDataAccess"),
		CommitWithoutEvents("CommitWithoutEvents"),
		TempOverruleImportUser("TempOverruleImportUser"),
		UseAction("UseAction"),
		UserAttributesAndReferencesOnly("UserAttributesAndReferencesOnly"),
		ExportTypeForInheritance("ExportTypeForInheritance"),
		ExportInheritedRecords("ExportInheritedRecords"),
		ExportEmptySheet("ExportEmptySheet"),
		SuppressFileNotFoundWarnings("SuppressFileNotFoundWarnings"),
		ExportRelatedLevels("ExportRelatedLevels"),
		UnlimitedStringExcelSize("UnlimitedStringExcelSize"),
		wsLanguageCode("wsLanguageCode"),
		wsTimeZone("wsTimeZone"),
		wsDateTimeFormat("wsDateTimeFormat"),
		wsUser("wsUser"),
		wsDescription("wsDescription"),
		ExportInStream("ExportInStream"),
		ExportInStreamZipTempFiles("ExportInStreamZipTempFiles"),
		LimitRows("LimitRows"),
		StartRow("StartRow"),
		EndRow("EndRow"),
		ImportCommitToDatabasePerRow("ImportCommitToDatabasePerRow"),
		ImportCommitToDatabasePerRowNumber("ImportCommitToDatabasePerRowNumber"),
		SelectIndividualFiles("SelectIndividualFiles"),
		IsSystemAdmin("IsSystemAdmin"),
		LogLevel("LogLevel"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		ImportExportSetting_DataPatchSet("ImportExport.ImportExportSetting_DataPatchSet"),
		ImportExportSetting_Domain("ImportExport.ImportExportSetting_Domain"),
		ImportExportSetting_Label("ImportExport.ImportExportSetting_Label"),
		ImportExportSetting_User("ImportExport.ImportExportSetting_User"),
		ImportExportSetting_Language("ImportExport.ImportExportSetting_Language"),
		ImportExportSetting_TimeZone("ImportExport.ImportExportSetting_TimeZone"),
		ImportExportSetting_DateTimeFormat("ImportExport.ImportExportSetting_DateTimeFormat"),
		ImportExportSetting_ToServer("ImportExport.ImportExportSetting_ToServer"),
		ImportExportSetting_MendixEntities("ImportExport.ImportExportSetting_MendixEntities");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ImportExportSetting(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ImportExport.ImportExportSetting"));
	}

	protected ImportExportSetting(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject importExportSettingMendixObject)
	{
		super(context, importExportSettingMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("ImportExport.ImportExportSetting", importExportSettingMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ImportExport.ImportExportSetting");
	}

	/**
	 * @deprecated Use 'ImportExportSetting.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static importexport.proxies.ImportExportSetting initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return importexport.proxies.ImportExportSetting.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static importexport.proxies.ImportExportSetting initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new importexport.proxies.ImportExportSetting(context, mendixObject);
	}

	public static importexport.proxies.ImportExportSetting load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return importexport.proxies.ImportExportSetting.initialize(context, mendixObject);
	}

	public static java.util.List<importexport.proxies.ImportExportSetting> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<importexport.proxies.ImportExportSetting> result = new java.util.ArrayList<importexport.proxies.ImportExportSetting>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//ImportExport.ImportExportSetting" + xpathConstraint))
			result.add(importexport.proxies.ImportExportSetting.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * Set value of FileType
	 * @param filetype
	 */
	public final importexport.proxies.FileTypeEnum getFileType()
	{
		return getFileType(getContext());
	}

	/**
	 * @param context
	 * @return value of FileType
	 */
	public final importexport.proxies.FileTypeEnum getFileType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.FileType.toString());
		if (obj == null)
			return null;

		return importexport.proxies.FileTypeEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of FileType
	 * @param filetype
	 */
	public final void setFileType(importexport.proxies.FileTypeEnum filetype)
	{
		setFileType(getContext(), filetype);
	}

	/**
	 * Set value of FileType
	 * @param context
	 * @param filetype
	 */
	public final void setFileType(com.mendix.systemwideinterfaces.core.IContext context, importexport.proxies.FileTypeEnum filetype)
	{
		if (filetype != null)
			getMendixObject().setValue(context, MemberNames.FileType.toString(), filetype.toString());
		else
			getMendixObject().setValue(context, MemberNames.FileType.toString(), null);
	}

	/**
	 * @return value of ServerFolder
	 */
	public final java.lang.String getServerFolder()
	{
		return getServerFolder(getContext());
	}

	/**
	 * @param context
	 * @return value of ServerFolder
	 */
	public final java.lang.String getServerFolder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ServerFolder.toString());
	}

	/**
	 * Set value of ServerFolder
	 * @param serverfolder
	 */
	public final void setServerFolder(java.lang.String serverfolder)
	{
		setServerFolder(getContext(), serverfolder);
	}

	/**
	 * Set value of ServerFolder
	 * @param context
	 * @param serverfolder
	 */
	public final void setServerFolder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String serverfolder)
	{
		getMendixObject().setValue(context, MemberNames.ServerFolder.toString(), serverfolder);
	}

	/**
	 * Set value of ImportType
	 * @param importtype
	 */
	public final importexport.proxies.ImportTypeEnum getImportType()
	{
		return getImportType(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportType
	 */
	public final importexport.proxies.ImportTypeEnum getImportType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ImportType.toString());
		if (obj == null)
			return null;

		return importexport.proxies.ImportTypeEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ImportType
	 * @param importtype
	 */
	public final void setImportType(importexport.proxies.ImportTypeEnum importtype)
	{
		setImportType(getContext(), importtype);
	}

	/**
	 * Set value of ImportType
	 * @param context
	 * @param importtype
	 */
	public final void setImportType(com.mendix.systemwideinterfaces.core.IContext context, importexport.proxies.ImportTypeEnum importtype)
	{
		if (importtype != null)
			getMendixObject().setValue(context, MemberNames.ImportType.toString(), importtype.toString());
		else
			getMendixObject().setValue(context, MemberNames.ImportType.toString(), null);
	}

	/**
	 * @return value of ImportCreate
	 */
	public final java.lang.Boolean getImportCreate()
	{
		return getImportCreate(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportCreate
	 */
	public final java.lang.Boolean getImportCreate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ImportCreate.toString());
	}

	/**
	 * Set value of ImportCreate
	 * @param importcreate
	 */
	public final void setImportCreate(java.lang.Boolean importcreate)
	{
		setImportCreate(getContext(), importcreate);
	}

	/**
	 * Set value of ImportCreate
	 * @param context
	 * @param importcreate
	 */
	public final void setImportCreate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean importcreate)
	{
		getMendixObject().setValue(context, MemberNames.ImportCreate.toString(), importcreate);
	}

	/**
	 * @return value of ImportUpdate
	 */
	public final java.lang.Boolean getImportUpdate()
	{
		return getImportUpdate(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportUpdate
	 */
	public final java.lang.Boolean getImportUpdate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ImportUpdate.toString());
	}

	/**
	 * Set value of ImportUpdate
	 * @param importupdate
	 */
	public final void setImportUpdate(java.lang.Boolean importupdate)
	{
		setImportUpdate(getContext(), importupdate);
	}

	/**
	 * Set value of ImportUpdate
	 * @param context
	 * @param importupdate
	 */
	public final void setImportUpdate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean importupdate)
	{
		getMendixObject().setValue(context, MemberNames.ImportUpdate.toString(), importupdate);
	}

	/**
	 * @return value of DumpDate
	 */
	public final java.util.Date getDumpDate()
	{
		return getDumpDate(getContext());
	}

	/**
	 * @param context
	 * @return value of DumpDate
	 */
	public final java.util.Date getDumpDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DumpDate.toString());
	}

	/**
	 * Set value of DumpDate
	 * @param dumpdate
	 */
	public final void setDumpDate(java.util.Date dumpdate)
	{
		setDumpDate(getContext(), dumpdate);
	}

	/**
	 * Set value of DumpDate
	 * @param context
	 * @param dumpdate
	 */
	public final void setDumpDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dumpdate)
	{
		getMendixObject().setValue(context, MemberNames.DumpDate.toString(), dumpdate);
	}

	/**
	 * @return value of ShowAdvancedOptions
	 */
	public final java.lang.Boolean getShowAdvancedOptions()
	{
		return getShowAdvancedOptions(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowAdvancedOptions
	 */
	public final java.lang.Boolean getShowAdvancedOptions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowAdvancedOptions.toString());
	}

	/**
	 * Set value of ShowAdvancedOptions
	 * @param showadvancedoptions
	 */
	public final void setShowAdvancedOptions(java.lang.Boolean showadvancedoptions)
	{
		setShowAdvancedOptions(getContext(), showadvancedoptions);
	}

	/**
	 * Set value of ShowAdvancedOptions
	 * @param context
	 * @param showadvancedoptions
	 */
	public final void setShowAdvancedOptions(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showadvancedoptions)
	{
		getMendixObject().setValue(context, MemberNames.ShowAdvancedOptions.toString(), showadvancedoptions);
	}

	/**
	 * @return value of ImportTestRun
	 */
	public final java.lang.Boolean getImportTestRun()
	{
		return getImportTestRun(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportTestRun
	 */
	public final java.lang.Boolean getImportTestRun(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ImportTestRun.toString());
	}

	/**
	 * Set value of ImportTestRun
	 * @param importtestrun
	 */
	public final void setImportTestRun(java.lang.Boolean importtestrun)
	{
		setImportTestRun(getContext(), importtestrun);
	}

	/**
	 * Set value of ImportTestRun
	 * @param context
	 * @param importtestrun
	 */
	public final void setImportTestRun(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean importtestrun)
	{
		getMendixObject().setValue(context, MemberNames.ImportTestRun.toString(), importtestrun);
	}

	/**
	 * @return value of UseZip
	 */
	public final java.lang.Boolean getUseZip()
	{
		return getUseZip(getContext());
	}

	/**
	 * @param context
	 * @return value of UseZip
	 */
	public final java.lang.Boolean getUseZip(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UseZip.toString());
	}

	/**
	 * Set value of UseZip
	 * @param usezip
	 */
	public final void setUseZip(java.lang.Boolean usezip)
	{
		setUseZip(getContext(), usezip);
	}

	/**
	 * Set value of UseZip
	 * @param context
	 * @param usezip
	 */
	public final void setUseZip(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean usezip)
	{
		getMendixObject().setValue(context, MemberNames.UseZip.toString(), usezip);
	}

	/**
	 * @return value of UseDirectMendixIDs
	 */
	public final java.lang.Boolean getUseDirectMendixIDs()
	{
		return getUseDirectMendixIDs(getContext());
	}

	/**
	 * @param context
	 * @return value of UseDirectMendixIDs
	 */
	public final java.lang.Boolean getUseDirectMendixIDs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UseDirectMendixIDs.toString());
	}

	/**
	 * Set value of UseDirectMendixIDs
	 * @param usedirectmendixids
	 */
	public final void setUseDirectMendixIDs(java.lang.Boolean usedirectmendixids)
	{
		setUseDirectMendixIDs(getContext(), usedirectmendixids);
	}

	/**
	 * Set value of UseDirectMendixIDs
	 * @param context
	 * @param usedirectmendixids
	 */
	public final void setUseDirectMendixIDs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean usedirectmendixids)
	{
		getMendixObject().setValue(context, MemberNames.UseDirectMendixIDs.toString(), usedirectmendixids);
	}

	/**
	 * @return value of UseTranslatedMendixIDs
	 */
	public final java.lang.Boolean getUseTranslatedMendixIDs()
	{
		return getUseTranslatedMendixIDs(getContext());
	}

	/**
	 * @param context
	 * @return value of UseTranslatedMendixIDs
	 */
	public final java.lang.Boolean getUseTranslatedMendixIDs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UseTranslatedMendixIDs.toString());
	}

	/**
	 * Set value of UseTranslatedMendixIDs
	 * @param usetranslatedmendixids
	 */
	public final void setUseTranslatedMendixIDs(java.lang.Boolean usetranslatedmendixids)
	{
		setUseTranslatedMendixIDs(getContext(), usetranslatedmendixids);
	}

	/**
	 * Set value of UseTranslatedMendixIDs
	 * @param context
	 * @param usetranslatedmendixids
	 */
	public final void setUseTranslatedMendixIDs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean usetranslatedmendixids)
	{
		getMendixObject().setValue(context, MemberNames.UseTranslatedMendixIDs.toString(), usetranslatedmendixids);
	}

	/**
	 * @return value of ReferencesInline
	 */
	public final java.lang.Boolean getReferencesInline()
	{
		return getReferencesInline(getContext());
	}

	/**
	 * @param context
	 * @return value of ReferencesInline
	 */
	public final java.lang.Boolean getReferencesInline(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ReferencesInline.toString());
	}

	/**
	 * Set value of ReferencesInline
	 * @param referencesinline
	 */
	public final void setReferencesInline(java.lang.Boolean referencesinline)
	{
		setReferencesInline(getContext(), referencesinline);
	}

	/**
	 * Set value of ReferencesInline
	 * @param context
	 * @param referencesinline
	 */
	public final void setReferencesInline(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean referencesinline)
	{
		getMendixObject().setValue(context, MemberNames.ReferencesInline.toString(), referencesinline);
	}

	/**
	 * @return value of ImportReferenceSetInline
	 */
	public final java.lang.Boolean getImportReferenceSetInline()
	{
		return getImportReferenceSetInline(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportReferenceSetInline
	 */
	public final java.lang.Boolean getImportReferenceSetInline(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ImportReferenceSetInline.toString());
	}

	/**
	 * Set value of ImportReferenceSetInline
	 * @param importreferencesetinline
	 */
	public final void setImportReferenceSetInline(java.lang.Boolean importreferencesetinline)
	{
		setImportReferenceSetInline(getContext(), importreferencesetinline);
	}

	/**
	 * Set value of ImportReferenceSetInline
	 * @param context
	 * @param importreferencesetinline
	 */
	public final void setImportReferenceSetInline(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean importreferencesetinline)
	{
		getMendixObject().setValue(context, MemberNames.ImportReferenceSetInline.toString(), importreferencesetinline);
	}

	/**
	 * @return value of ReferenceOrSetBothAsChild
	 */
	public final java.lang.Boolean getReferenceOrSetBothAsChild()
	{
		return getReferenceOrSetBothAsChild(getContext());
	}

	/**
	 * @param context
	 * @return value of ReferenceOrSetBothAsChild
	 */
	public final java.lang.Boolean getReferenceOrSetBothAsChild(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ReferenceOrSetBothAsChild.toString());
	}

	/**
	 * Set value of ReferenceOrSetBothAsChild
	 * @param referenceorsetbothaschild
	 */
	public final void setReferenceOrSetBothAsChild(java.lang.Boolean referenceorsetbothaschild)
	{
		setReferenceOrSetBothAsChild(getContext(), referenceorsetbothaschild);
	}

	/**
	 * Set value of ReferenceOrSetBothAsChild
	 * @param context
	 * @param referenceorsetbothaschild
	 */
	public final void setReferenceOrSetBothAsChild(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean referenceorsetbothaschild)
	{
		getMendixObject().setValue(context, MemberNames.ReferenceOrSetBothAsChild.toString(), referenceorsetbothaschild);
	}

	/**
	 * @return value of ImportNonDelayedRelations
	 */
	public final java.lang.Boolean getImportNonDelayedRelations()
	{
		return getImportNonDelayedRelations(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportNonDelayedRelations
	 */
	public final java.lang.Boolean getImportNonDelayedRelations(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ImportNonDelayedRelations.toString());
	}

	/**
	 * Set value of ImportNonDelayedRelations
	 * @param importnondelayedrelations
	 */
	public final void setImportNonDelayedRelations(java.lang.Boolean importnondelayedrelations)
	{
		setImportNonDelayedRelations(getContext(), importnondelayedrelations);
	}

	/**
	 * Set value of ImportNonDelayedRelations
	 * @param context
	 * @param importnondelayedrelations
	 */
	public final void setImportNonDelayedRelations(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean importnondelayedrelations)
	{
		getMendixObject().setValue(context, MemberNames.ImportNonDelayedRelations.toString(), importnondelayedrelations);
	}

	/**
	 * @return value of ImportDelayedRelations
	 */
	public final java.lang.Boolean getImportDelayedRelations()
	{
		return getImportDelayedRelations(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportDelayedRelations
	 */
	public final java.lang.Boolean getImportDelayedRelations(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ImportDelayedRelations.toString());
	}

	/**
	 * Set value of ImportDelayedRelations
	 * @param importdelayedrelations
	 */
	public final void setImportDelayedRelations(java.lang.Boolean importdelayedrelations)
	{
		setImportDelayedRelations(getContext(), importdelayedrelations);
	}

	/**
	 * Set value of ImportDelayedRelations
	 * @param context
	 * @param importdelayedrelations
	 */
	public final void setImportDelayedRelations(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean importdelayedrelations)
	{
		getMendixObject().setValue(context, MemberNames.ImportDelayedRelations.toString(), importdelayedrelations);
	}

	/**
	 * @return value of ImportMetaModelOnly
	 */
	public final java.lang.Boolean getImportMetaModelOnly()
	{
		return getImportMetaModelOnly(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportMetaModelOnly
	 */
	public final java.lang.Boolean getImportMetaModelOnly(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ImportMetaModelOnly.toString());
	}

	/**
	 * Set value of ImportMetaModelOnly
	 * @param importmetamodelonly
	 */
	public final void setImportMetaModelOnly(java.lang.Boolean importmetamodelonly)
	{
		setImportMetaModelOnly(getContext(), importmetamodelonly);
	}

	/**
	 * Set value of ImportMetaModelOnly
	 * @param context
	 * @param importmetamodelonly
	 */
	public final void setImportMetaModelOnly(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean importmetamodelonly)
	{
		getMendixObject().setValue(context, MemberNames.ImportMetaModelOnly.toString(), importmetamodelonly);
	}

	/**
	 * @return value of ImportSkipMetaModel
	 */
	public final java.lang.Boolean getImportSkipMetaModel()
	{
		return getImportSkipMetaModel(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportSkipMetaModel
	 */
	public final java.lang.Boolean getImportSkipMetaModel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ImportSkipMetaModel.toString());
	}

	/**
	 * Set value of ImportSkipMetaModel
	 * @param importskipmetamodel
	 */
	public final void setImportSkipMetaModel(java.lang.Boolean importskipmetamodel)
	{
		setImportSkipMetaModel(getContext(), importskipmetamodel);
	}

	/**
	 * Set value of ImportSkipMetaModel
	 * @param context
	 * @param importskipmetamodel
	 */
	public final void setImportSkipMetaModel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean importskipmetamodel)
	{
		getMendixObject().setValue(context, MemberNames.ImportSkipMetaModel.toString(), importskipmetamodel);
	}

	/**
	 * @return value of ImportFailAndStopOnErrors
	 */
	public final java.lang.Boolean getImportFailAndStopOnErrors()
	{
		return getImportFailAndStopOnErrors(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportFailAndStopOnErrors
	 */
	public final java.lang.Boolean getImportFailAndStopOnErrors(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ImportFailAndStopOnErrors.toString());
	}

	/**
	 * Set value of ImportFailAndStopOnErrors
	 * @param importfailandstoponerrors
	 */
	public final void setImportFailAndStopOnErrors(java.lang.Boolean importfailandstoponerrors)
	{
		setImportFailAndStopOnErrors(getContext(), importfailandstoponerrors);
	}

	/**
	 * Set value of ImportFailAndStopOnErrors
	 * @param context
	 * @param importfailandstoponerrors
	 */
	public final void setImportFailAndStopOnErrors(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean importfailandstoponerrors)
	{
		getMendixObject().setValue(context, MemberNames.ImportFailAndStopOnErrors.toString(), importfailandstoponerrors);
	}

	/**
	 * @return value of SetDataAccess
	 */
	public final java.lang.Boolean getSetDataAccess()
	{
		return getSetDataAccess(getContext());
	}

	/**
	 * @param context
	 * @return value of SetDataAccess
	 */
	public final java.lang.Boolean getSetDataAccess(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SetDataAccess.toString());
	}

	/**
	 * Set value of SetDataAccess
	 * @param setdataaccess
	 */
	public final void setSetDataAccess(java.lang.Boolean setdataaccess)
	{
		setSetDataAccess(getContext(), setdataaccess);
	}

	/**
	 * Set value of SetDataAccess
	 * @param context
	 * @param setdataaccess
	 */
	public final void setSetDataAccess(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean setdataaccess)
	{
		getMendixObject().setValue(context, MemberNames.SetDataAccess.toString(), setdataaccess);
	}

	/**
	 * @return value of CommitWithoutEvents
	 */
	public final java.lang.Boolean getCommitWithoutEvents()
	{
		return getCommitWithoutEvents(getContext());
	}

	/**
	 * @param context
	 * @return value of CommitWithoutEvents
	 */
	public final java.lang.Boolean getCommitWithoutEvents(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CommitWithoutEvents.toString());
	}

	/**
	 * Set value of CommitWithoutEvents
	 * @param commitwithoutevents
	 */
	public final void setCommitWithoutEvents(java.lang.Boolean commitwithoutevents)
	{
		setCommitWithoutEvents(getContext(), commitwithoutevents);
	}

	/**
	 * Set value of CommitWithoutEvents
	 * @param context
	 * @param commitwithoutevents
	 */
	public final void setCommitWithoutEvents(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean commitwithoutevents)
	{
		getMendixObject().setValue(context, MemberNames.CommitWithoutEvents.toString(), commitwithoutevents);
	}

	/**
	 * @return value of TempOverruleImportUser
	 */
	public final java.lang.Boolean getTempOverruleImportUser()
	{
		return getTempOverruleImportUser(getContext());
	}

	/**
	 * @param context
	 * @return value of TempOverruleImportUser
	 */
	public final java.lang.Boolean getTempOverruleImportUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.TempOverruleImportUser.toString());
	}

	/**
	 * Set value of TempOverruleImportUser
	 * @param tempoverruleimportuser
	 */
	public final void setTempOverruleImportUser(java.lang.Boolean tempoverruleimportuser)
	{
		setTempOverruleImportUser(getContext(), tempoverruleimportuser);
	}

	/**
	 * Set value of TempOverruleImportUser
	 * @param context
	 * @param tempoverruleimportuser
	 */
	public final void setTempOverruleImportUser(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean tempoverruleimportuser)
	{
		getMendixObject().setValue(context, MemberNames.TempOverruleImportUser.toString(), tempoverruleimportuser);
	}

	/**
	 * @return value of UseAction
	 */
	public final java.lang.Boolean getUseAction()
	{
		return getUseAction(getContext());
	}

	/**
	 * @param context
	 * @return value of UseAction
	 */
	public final java.lang.Boolean getUseAction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UseAction.toString());
	}

	/**
	 * Set value of UseAction
	 * @param useaction
	 */
	public final void setUseAction(java.lang.Boolean useaction)
	{
		setUseAction(getContext(), useaction);
	}

	/**
	 * Set value of UseAction
	 * @param context
	 * @param useaction
	 */
	public final void setUseAction(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean useaction)
	{
		getMendixObject().setValue(context, MemberNames.UseAction.toString(), useaction);
	}

	/**
	 * @return value of UserAttributesAndReferencesOnly
	 */
	public final java.lang.Boolean getUserAttributesAndReferencesOnly()
	{
		return getUserAttributesAndReferencesOnly(getContext());
	}

	/**
	 * @param context
	 * @return value of UserAttributesAndReferencesOnly
	 */
	public final java.lang.Boolean getUserAttributesAndReferencesOnly(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UserAttributesAndReferencesOnly.toString());
	}

	/**
	 * Set value of UserAttributesAndReferencesOnly
	 * @param userattributesandreferencesonly
	 */
	public final void setUserAttributesAndReferencesOnly(java.lang.Boolean userattributesandreferencesonly)
	{
		setUserAttributesAndReferencesOnly(getContext(), userattributesandreferencesonly);
	}

	/**
	 * Set value of UserAttributesAndReferencesOnly
	 * @param context
	 * @param userattributesandreferencesonly
	 */
	public final void setUserAttributesAndReferencesOnly(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean userattributesandreferencesonly)
	{
		getMendixObject().setValue(context, MemberNames.UserAttributesAndReferencesOnly.toString(), userattributesandreferencesonly);
	}

	/**
	 * Set value of ExportTypeForInheritance
	 * @param exporttypeforinheritance
	 */
	public final importexport.proxies.ExportTypeForInheritanceEnum getExportTypeForInheritance()
	{
		return getExportTypeForInheritance(getContext());
	}

	/**
	 * @param context
	 * @return value of ExportTypeForInheritance
	 */
	public final importexport.proxies.ExportTypeForInheritanceEnum getExportTypeForInheritance(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ExportTypeForInheritance.toString());
		if (obj == null)
			return null;

		return importexport.proxies.ExportTypeForInheritanceEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ExportTypeForInheritance
	 * @param exporttypeforinheritance
	 */
	public final void setExportTypeForInheritance(importexport.proxies.ExportTypeForInheritanceEnum exporttypeforinheritance)
	{
		setExportTypeForInheritance(getContext(), exporttypeforinheritance);
	}

	/**
	 * Set value of ExportTypeForInheritance
	 * @param context
	 * @param exporttypeforinheritance
	 */
	public final void setExportTypeForInheritance(com.mendix.systemwideinterfaces.core.IContext context, importexport.proxies.ExportTypeForInheritanceEnum exporttypeforinheritance)
	{
		if (exporttypeforinheritance != null)
			getMendixObject().setValue(context, MemberNames.ExportTypeForInheritance.toString(), exporttypeforinheritance.toString());
		else
			getMendixObject().setValue(context, MemberNames.ExportTypeForInheritance.toString(), null);
	}

	/**
	 * @return value of ExportInheritedRecords
	 */
	public final java.lang.Boolean getExportInheritedRecords()
	{
		return getExportInheritedRecords(getContext());
	}

	/**
	 * @param context
	 * @return value of ExportInheritedRecords
	 */
	public final java.lang.Boolean getExportInheritedRecords(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ExportInheritedRecords.toString());
	}

	/**
	 * Set value of ExportInheritedRecords
	 * @param exportinheritedrecords
	 */
	public final void setExportInheritedRecords(java.lang.Boolean exportinheritedrecords)
	{
		setExportInheritedRecords(getContext(), exportinheritedrecords);
	}

	/**
	 * Set value of ExportInheritedRecords
	 * @param context
	 * @param exportinheritedrecords
	 */
	public final void setExportInheritedRecords(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean exportinheritedrecords)
	{
		getMendixObject().setValue(context, MemberNames.ExportInheritedRecords.toString(), exportinheritedrecords);
	}

	/**
	 * @return value of ExportEmptySheet
	 */
	public final java.lang.Boolean getExportEmptySheet()
	{
		return getExportEmptySheet(getContext());
	}

	/**
	 * @param context
	 * @return value of ExportEmptySheet
	 */
	public final java.lang.Boolean getExportEmptySheet(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ExportEmptySheet.toString());
	}

	/**
	 * Set value of ExportEmptySheet
	 * @param exportemptysheet
	 */
	public final void setExportEmptySheet(java.lang.Boolean exportemptysheet)
	{
		setExportEmptySheet(getContext(), exportemptysheet);
	}

	/**
	 * Set value of ExportEmptySheet
	 * @param context
	 * @param exportemptysheet
	 */
	public final void setExportEmptySheet(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean exportemptysheet)
	{
		getMendixObject().setValue(context, MemberNames.ExportEmptySheet.toString(), exportemptysheet);
	}

	/**
	 * @return value of SuppressFileNotFoundWarnings
	 */
	public final java.lang.Boolean getSuppressFileNotFoundWarnings()
	{
		return getSuppressFileNotFoundWarnings(getContext());
	}

	/**
	 * @param context
	 * @return value of SuppressFileNotFoundWarnings
	 */
	public final java.lang.Boolean getSuppressFileNotFoundWarnings(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SuppressFileNotFoundWarnings.toString());
	}

	/**
	 * Set value of SuppressFileNotFoundWarnings
	 * @param suppressfilenotfoundwarnings
	 */
	public final void setSuppressFileNotFoundWarnings(java.lang.Boolean suppressfilenotfoundwarnings)
	{
		setSuppressFileNotFoundWarnings(getContext(), suppressfilenotfoundwarnings);
	}

	/**
	 * Set value of SuppressFileNotFoundWarnings
	 * @param context
	 * @param suppressfilenotfoundwarnings
	 */
	public final void setSuppressFileNotFoundWarnings(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean suppressfilenotfoundwarnings)
	{
		getMendixObject().setValue(context, MemberNames.SuppressFileNotFoundWarnings.toString(), suppressfilenotfoundwarnings);
	}

	/**
	 * @return value of ExportRelatedLevels
	 */
	public final java.lang.Integer getExportRelatedLevels()
	{
		return getExportRelatedLevels(getContext());
	}

	/**
	 * @param context
	 * @return value of ExportRelatedLevels
	 */
	public final java.lang.Integer getExportRelatedLevels(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ExportRelatedLevels.toString());
	}

	/**
	 * Set value of ExportRelatedLevels
	 * @param exportrelatedlevels
	 */
	public final void setExportRelatedLevels(java.lang.Integer exportrelatedlevels)
	{
		setExportRelatedLevels(getContext(), exportrelatedlevels);
	}

	/**
	 * Set value of ExportRelatedLevels
	 * @param context
	 * @param exportrelatedlevels
	 */
	public final void setExportRelatedLevels(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer exportrelatedlevels)
	{
		getMendixObject().setValue(context, MemberNames.ExportRelatedLevels.toString(), exportrelatedlevels);
	}

	/**
	 * @return value of UnlimitedStringExcelSize
	 */
	public final java.lang.Integer getUnlimitedStringExcelSize()
	{
		return getUnlimitedStringExcelSize(getContext());
	}

	/**
	 * @param context
	 * @return value of UnlimitedStringExcelSize
	 */
	public final java.lang.Integer getUnlimitedStringExcelSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.UnlimitedStringExcelSize.toString());
	}

	/**
	 * Set value of UnlimitedStringExcelSize
	 * @param unlimitedstringexcelsize
	 */
	public final void setUnlimitedStringExcelSize(java.lang.Integer unlimitedstringexcelsize)
	{
		setUnlimitedStringExcelSize(getContext(), unlimitedstringexcelsize);
	}

	/**
	 * Set value of UnlimitedStringExcelSize
	 * @param context
	 * @param unlimitedstringexcelsize
	 */
	public final void setUnlimitedStringExcelSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer unlimitedstringexcelsize)
	{
		getMendixObject().setValue(context, MemberNames.UnlimitedStringExcelSize.toString(), unlimitedstringexcelsize);
	}

	/**
	 * @return value of wsLanguageCode
	 */
	public final java.lang.String getwsLanguageCode()
	{
		return getwsLanguageCode(getContext());
	}

	/**
	 * @param context
	 * @return value of wsLanguageCode
	 */
	public final java.lang.String getwsLanguageCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.wsLanguageCode.toString());
	}

	/**
	 * Set value of wsLanguageCode
	 * @param wslanguagecode
	 */
	public final void setwsLanguageCode(java.lang.String wslanguagecode)
	{
		setwsLanguageCode(getContext(), wslanguagecode);
	}

	/**
	 * Set value of wsLanguageCode
	 * @param context
	 * @param wslanguagecode
	 */
	public final void setwsLanguageCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String wslanguagecode)
	{
		getMendixObject().setValue(context, MemberNames.wsLanguageCode.toString(), wslanguagecode);
	}

	/**
	 * @return value of wsTimeZone
	 */
	public final java.lang.String getwsTimeZone()
	{
		return getwsTimeZone(getContext());
	}

	/**
	 * @param context
	 * @return value of wsTimeZone
	 */
	public final java.lang.String getwsTimeZone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.wsTimeZone.toString());
	}

	/**
	 * Set value of wsTimeZone
	 * @param wstimezone
	 */
	public final void setwsTimeZone(java.lang.String wstimezone)
	{
		setwsTimeZone(getContext(), wstimezone);
	}

	/**
	 * Set value of wsTimeZone
	 * @param context
	 * @param wstimezone
	 */
	public final void setwsTimeZone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String wstimezone)
	{
		getMendixObject().setValue(context, MemberNames.wsTimeZone.toString(), wstimezone);
	}

	/**
	 * @return value of wsDateTimeFormat
	 */
	public final java.lang.String getwsDateTimeFormat()
	{
		return getwsDateTimeFormat(getContext());
	}

	/**
	 * @param context
	 * @return value of wsDateTimeFormat
	 */
	public final java.lang.String getwsDateTimeFormat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.wsDateTimeFormat.toString());
	}

	/**
	 * Set value of wsDateTimeFormat
	 * @param wsdatetimeformat
	 */
	public final void setwsDateTimeFormat(java.lang.String wsdatetimeformat)
	{
		setwsDateTimeFormat(getContext(), wsdatetimeformat);
	}

	/**
	 * Set value of wsDateTimeFormat
	 * @param context
	 * @param wsdatetimeformat
	 */
	public final void setwsDateTimeFormat(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String wsdatetimeformat)
	{
		getMendixObject().setValue(context, MemberNames.wsDateTimeFormat.toString(), wsdatetimeformat);
	}

	/**
	 * @return value of wsUser
	 */
	public final java.lang.String getwsUser()
	{
		return getwsUser(getContext());
	}

	/**
	 * @param context
	 * @return value of wsUser
	 */
	public final java.lang.String getwsUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.wsUser.toString());
	}

	/**
	 * Set value of wsUser
	 * @param wsuser
	 */
	public final void setwsUser(java.lang.String wsuser)
	{
		setwsUser(getContext(), wsuser);
	}

	/**
	 * Set value of wsUser
	 * @param context
	 * @param wsuser
	 */
	public final void setwsUser(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String wsuser)
	{
		getMendixObject().setValue(context, MemberNames.wsUser.toString(), wsuser);
	}

	/**
	 * @return value of wsDescription
	 */
	public final java.lang.String getwsDescription()
	{
		return getwsDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of wsDescription
	 */
	public final java.lang.String getwsDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.wsDescription.toString());
	}

	/**
	 * Set value of wsDescription
	 * @param wsdescription
	 */
	public final void setwsDescription(java.lang.String wsdescription)
	{
		setwsDescription(getContext(), wsdescription);
	}

	/**
	 * Set value of wsDescription
	 * @param context
	 * @param wsdescription
	 */
	public final void setwsDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String wsdescription)
	{
		getMendixObject().setValue(context, MemberNames.wsDescription.toString(), wsdescription);
	}

	/**
	 * @return value of ExportInStream
	 */
	public final java.lang.Boolean getExportInStream()
	{
		return getExportInStream(getContext());
	}

	/**
	 * @param context
	 * @return value of ExportInStream
	 */
	public final java.lang.Boolean getExportInStream(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ExportInStream.toString());
	}

	/**
	 * Set value of ExportInStream
	 * @param exportinstream
	 */
	public final void setExportInStream(java.lang.Boolean exportinstream)
	{
		setExportInStream(getContext(), exportinstream);
	}

	/**
	 * Set value of ExportInStream
	 * @param context
	 * @param exportinstream
	 */
	public final void setExportInStream(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean exportinstream)
	{
		getMendixObject().setValue(context, MemberNames.ExportInStream.toString(), exportinstream);
	}

	/**
	 * @return value of ExportInStreamZipTempFiles
	 */
	public final java.lang.Boolean getExportInStreamZipTempFiles()
	{
		return getExportInStreamZipTempFiles(getContext());
	}

	/**
	 * @param context
	 * @return value of ExportInStreamZipTempFiles
	 */
	public final java.lang.Boolean getExportInStreamZipTempFiles(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ExportInStreamZipTempFiles.toString());
	}

	/**
	 * Set value of ExportInStreamZipTempFiles
	 * @param exportinstreamziptempfiles
	 */
	public final void setExportInStreamZipTempFiles(java.lang.Boolean exportinstreamziptempfiles)
	{
		setExportInStreamZipTempFiles(getContext(), exportinstreamziptempfiles);
	}

	/**
	 * Set value of ExportInStreamZipTempFiles
	 * @param context
	 * @param exportinstreamziptempfiles
	 */
	public final void setExportInStreamZipTempFiles(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean exportinstreamziptempfiles)
	{
		getMendixObject().setValue(context, MemberNames.ExportInStreamZipTempFiles.toString(), exportinstreamziptempfiles);
	}

	/**
	 * @return value of LimitRows
	 */
	public final java.lang.Boolean getLimitRows()
	{
		return getLimitRows(getContext());
	}

	/**
	 * @param context
	 * @return value of LimitRows
	 */
	public final java.lang.Boolean getLimitRows(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.LimitRows.toString());
	}

	/**
	 * Set value of LimitRows
	 * @param limitrows
	 */
	public final void setLimitRows(java.lang.Boolean limitrows)
	{
		setLimitRows(getContext(), limitrows);
	}

	/**
	 * Set value of LimitRows
	 * @param context
	 * @param limitrows
	 */
	public final void setLimitRows(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean limitrows)
	{
		getMendixObject().setValue(context, MemberNames.LimitRows.toString(), limitrows);
	}

	/**
	 * @return value of StartRow
	 */
	public final java.lang.Integer getStartRow()
	{
		return getStartRow(getContext());
	}

	/**
	 * @param context
	 * @return value of StartRow
	 */
	public final java.lang.Integer getStartRow(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.StartRow.toString());
	}

	/**
	 * Set value of StartRow
	 * @param startrow
	 */
	public final void setStartRow(java.lang.Integer startrow)
	{
		setStartRow(getContext(), startrow);
	}

	/**
	 * Set value of StartRow
	 * @param context
	 * @param startrow
	 */
	public final void setStartRow(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer startrow)
	{
		getMendixObject().setValue(context, MemberNames.StartRow.toString(), startrow);
	}

	/**
	 * @return value of EndRow
	 */
	public final java.lang.Integer getEndRow()
	{
		return getEndRow(getContext());
	}

	/**
	 * @param context
	 * @return value of EndRow
	 */
	public final java.lang.Integer getEndRow(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EndRow.toString());
	}

	/**
	 * Set value of EndRow
	 * @param endrow
	 */
	public final void setEndRow(java.lang.Integer endrow)
	{
		setEndRow(getContext(), endrow);
	}

	/**
	 * Set value of EndRow
	 * @param context
	 * @param endrow
	 */
	public final void setEndRow(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer endrow)
	{
		getMendixObject().setValue(context, MemberNames.EndRow.toString(), endrow);
	}

	/**
	 * @return value of ImportCommitToDatabasePerRow
	 */
	public final java.lang.Boolean getImportCommitToDatabasePerRow()
	{
		return getImportCommitToDatabasePerRow(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportCommitToDatabasePerRow
	 */
	public final java.lang.Boolean getImportCommitToDatabasePerRow(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ImportCommitToDatabasePerRow.toString());
	}

	/**
	 * Set value of ImportCommitToDatabasePerRow
	 * @param importcommittodatabaseperrow
	 */
	public final void setImportCommitToDatabasePerRow(java.lang.Boolean importcommittodatabaseperrow)
	{
		setImportCommitToDatabasePerRow(getContext(), importcommittodatabaseperrow);
	}

	/**
	 * Set value of ImportCommitToDatabasePerRow
	 * @param context
	 * @param importcommittodatabaseperrow
	 */
	public final void setImportCommitToDatabasePerRow(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean importcommittodatabaseperrow)
	{
		getMendixObject().setValue(context, MemberNames.ImportCommitToDatabasePerRow.toString(), importcommittodatabaseperrow);
	}

	/**
	 * @return value of ImportCommitToDatabasePerRowNumber
	 */
	public final java.lang.Integer getImportCommitToDatabasePerRowNumber()
	{
		return getImportCommitToDatabasePerRowNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportCommitToDatabasePerRowNumber
	 */
	public final java.lang.Integer getImportCommitToDatabasePerRowNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ImportCommitToDatabasePerRowNumber.toString());
	}

	/**
	 * Set value of ImportCommitToDatabasePerRowNumber
	 * @param importcommittodatabaseperrownumber
	 */
	public final void setImportCommitToDatabasePerRowNumber(java.lang.Integer importcommittodatabaseperrownumber)
	{
		setImportCommitToDatabasePerRowNumber(getContext(), importcommittodatabaseperrownumber);
	}

	/**
	 * Set value of ImportCommitToDatabasePerRowNumber
	 * @param context
	 * @param importcommittodatabaseperrownumber
	 */
	public final void setImportCommitToDatabasePerRowNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer importcommittodatabaseperrownumber)
	{
		getMendixObject().setValue(context, MemberNames.ImportCommitToDatabasePerRowNumber.toString(), importcommittodatabaseperrownumber);
	}

	/**
	 * @return value of SelectIndividualFiles
	 */
	public final java.lang.Boolean getSelectIndividualFiles()
	{
		return getSelectIndividualFiles(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectIndividualFiles
	 */
	public final java.lang.Boolean getSelectIndividualFiles(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SelectIndividualFiles.toString());
	}

	/**
	 * Set value of SelectIndividualFiles
	 * @param selectindividualfiles
	 */
	public final void setSelectIndividualFiles(java.lang.Boolean selectindividualfiles)
	{
		setSelectIndividualFiles(getContext(), selectindividualfiles);
	}

	/**
	 * Set value of SelectIndividualFiles
	 * @param context
	 * @param selectindividualfiles
	 */
	public final void setSelectIndividualFiles(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean selectindividualfiles)
	{
		getMendixObject().setValue(context, MemberNames.SelectIndividualFiles.toString(), selectindividualfiles);
	}

	/**
	 * @return value of IsSystemAdmin
	 */
	public final java.lang.Boolean getIsSystemAdmin()
	{
		return getIsSystemAdmin(getContext());
	}

	/**
	 * @param context
	 * @return value of IsSystemAdmin
	 */
	public final java.lang.Boolean getIsSystemAdmin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsSystemAdmin.toString());
	}

	/**
	 * Set value of IsSystemAdmin
	 * @param issystemadmin
	 */
	public final void setIsSystemAdmin(java.lang.Boolean issystemadmin)
	{
		setIsSystemAdmin(getContext(), issystemadmin);
	}

	/**
	 * Set value of IsSystemAdmin
	 * @param context
	 * @param issystemadmin
	 */
	public final void setIsSystemAdmin(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean issystemadmin)
	{
		getMendixObject().setValue(context, MemberNames.IsSystemAdmin.toString(), issystemadmin);
	}

	/**
	 * Set value of LogLevel
	 * @param loglevel
	 */
	public final importexport.proxies.LogLevel getLogLevel()
	{
		return getLogLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of LogLevel
	 */
	public final importexport.proxies.LogLevel getLogLevel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.LogLevel.toString());
		if (obj == null)
			return null;

		return importexport.proxies.LogLevel.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of LogLevel
	 * @param loglevel
	 */
	public final void setLogLevel(importexport.proxies.LogLevel loglevel)
	{
		setLogLevel(getContext(), loglevel);
	}

	/**
	 * Set value of LogLevel
	 * @param context
	 * @param loglevel
	 */
	public final void setLogLevel(com.mendix.systemwideinterfaces.core.IContext context, importexport.proxies.LogLevel loglevel)
	{
		if (loglevel != null)
			getMendixObject().setValue(context, MemberNames.LogLevel.toString(), loglevel.toString());
		else
			getMendixObject().setValue(context, MemberNames.LogLevel.toString(), null);
	}

	/**
	 * @return value of ImportExportSetting_DataPatchSet
	 */
	public final importexport.proxies.DataPatchSet getImportExportSetting_DataPatchSet() throws com.mendix.core.CoreException
	{
		return getImportExportSetting_DataPatchSet(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportExportSetting_DataPatchSet
	 */
	public final importexport.proxies.DataPatchSet getImportExportSetting_DataPatchSet(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		importexport.proxies.DataPatchSet result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ImportExportSetting_DataPatchSet.toString());
		if (identifier != null)
			result = importexport.proxies.DataPatchSet.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ImportExportSetting_DataPatchSet
	 * @param importexportsetting_datapatchset
	 */
	public final void setImportExportSetting_DataPatchSet(importexport.proxies.DataPatchSet importexportsetting_datapatchset)
	{
		setImportExportSetting_DataPatchSet(getContext(), importexportsetting_datapatchset);
	}

	/**
	 * Set value of ImportExportSetting_DataPatchSet
	 * @param context
	 * @param importexportsetting_datapatchset
	 */
	public final void setImportExportSetting_DataPatchSet(com.mendix.systemwideinterfaces.core.IContext context, importexport.proxies.DataPatchSet importexportsetting_datapatchset)
	{
		if (importexportsetting_datapatchset == null)
			getMendixObject().setValue(context, MemberNames.ImportExportSetting_DataPatchSet.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ImportExportSetting_DataPatchSet.toString(), importexportsetting_datapatchset.getMendixObject().getId());
	}

	/**
	 * @return value of ImportExportSetting_Domain
	 */
	public final da.proxies.Domain getImportExportSetting_Domain() throws com.mendix.core.CoreException
	{
		return getImportExportSetting_Domain(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportExportSetting_Domain
	 */
	public final da.proxies.Domain getImportExportSetting_Domain(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		da.proxies.Domain result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ImportExportSetting_Domain.toString());
		if (identifier != null)
			result = da.proxies.Domain.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ImportExportSetting_Domain
	 * @param importexportsetting_domain
	 */
	public final void setImportExportSetting_Domain(da.proxies.Domain importexportsetting_domain)
	{
		setImportExportSetting_Domain(getContext(), importexportsetting_domain);
	}

	/**
	 * Set value of ImportExportSetting_Domain
	 * @param context
	 * @param importexportsetting_domain
	 */
	public final void setImportExportSetting_Domain(com.mendix.systemwideinterfaces.core.IContext context, da.proxies.Domain importexportsetting_domain)
	{
		if (importexportsetting_domain == null)
			getMendixObject().setValue(context, MemberNames.ImportExportSetting_Domain.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ImportExportSetting_Domain.toString(), importexportsetting_domain.getMendixObject().getId());
	}

	/**
	 * @return value of ImportExportSetting_Label
	 */
	public final java.util.List<da.proxies.Label> getImportExportSetting_Label() throws com.mendix.core.CoreException
	{
		return getImportExportSetting_Label(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportExportSetting_Label
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<da.proxies.Label> getImportExportSetting_Label(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<da.proxies.Label> result = new java.util.ArrayList<da.proxies.Label>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.ImportExportSetting_Label.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(da.proxies.Label.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of ImportExportSetting_Label
	 * @param importexportsetting_label
	 */
	public final void setImportExportSetting_Label(java.util.List<da.proxies.Label> importexportsetting_label)
	{
		setImportExportSetting_Label(getContext(), importexportsetting_label);
	}

	/**
	 * Set value of ImportExportSetting_Label
	 * @param context
	 * @param importexportsetting_label
	 */
	public final void setImportExportSetting_Label(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<da.proxies.Label> importexportsetting_label)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (da.proxies.Label proxyObject : importexportsetting_label)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.ImportExportSetting_Label.toString(), identifiers);
	}

	/**
	 * @return value of ImportExportSetting_User
	 */
	public final system.proxies.User getImportExportSetting_User() throws com.mendix.core.CoreException
	{
		return getImportExportSetting_User(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportExportSetting_User
	 */
	public final system.proxies.User getImportExportSetting_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ImportExportSetting_User.toString());
		if (identifier != null)
			result = system.proxies.User.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ImportExportSetting_User
	 * @param importexportsetting_user
	 */
	public final void setImportExportSetting_User(system.proxies.User importexportsetting_user)
	{
		setImportExportSetting_User(getContext(), importexportsetting_user);
	}

	/**
	 * Set value of ImportExportSetting_User
	 * @param context
	 * @param importexportsetting_user
	 */
	public final void setImportExportSetting_User(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.User importexportsetting_user)
	{
		if (importexportsetting_user == null)
			getMendixObject().setValue(context, MemberNames.ImportExportSetting_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ImportExportSetting_User.toString(), importexportsetting_user.getMendixObject().getId());
	}

	/**
	 * @return value of ImportExportSetting_Language
	 */
	public final system.proxies.Language getImportExportSetting_Language() throws com.mendix.core.CoreException
	{
		return getImportExportSetting_Language(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportExportSetting_Language
	 */
	public final system.proxies.Language getImportExportSetting_Language(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Language result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ImportExportSetting_Language.toString());
		if (identifier != null)
			result = system.proxies.Language.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ImportExportSetting_Language
	 * @param importexportsetting_language
	 */
	public final void setImportExportSetting_Language(system.proxies.Language importexportsetting_language)
	{
		setImportExportSetting_Language(getContext(), importexportsetting_language);
	}

	/**
	 * Set value of ImportExportSetting_Language
	 * @param context
	 * @param importexportsetting_language
	 */
	public final void setImportExportSetting_Language(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Language importexportsetting_language)
	{
		if (importexportsetting_language == null)
			getMendixObject().setValue(context, MemberNames.ImportExportSetting_Language.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ImportExportSetting_Language.toString(), importexportsetting_language.getMendixObject().getId());
	}

	/**
	 * @return value of ImportExportSetting_TimeZone
	 */
	public final system.proxies.TimeZone getImportExportSetting_TimeZone() throws com.mendix.core.CoreException
	{
		return getImportExportSetting_TimeZone(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportExportSetting_TimeZone
	 */
	public final system.proxies.TimeZone getImportExportSetting_TimeZone(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.TimeZone result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ImportExportSetting_TimeZone.toString());
		if (identifier != null)
			result = system.proxies.TimeZone.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ImportExportSetting_TimeZone
	 * @param importexportsetting_timezone
	 */
	public final void setImportExportSetting_TimeZone(system.proxies.TimeZone importexportsetting_timezone)
	{
		setImportExportSetting_TimeZone(getContext(), importexportsetting_timezone);
	}

	/**
	 * Set value of ImportExportSetting_TimeZone
	 * @param context
	 * @param importexportsetting_timezone
	 */
	public final void setImportExportSetting_TimeZone(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.TimeZone importexportsetting_timezone)
	{
		if (importexportsetting_timezone == null)
			getMendixObject().setValue(context, MemberNames.ImportExportSetting_TimeZone.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ImportExportSetting_TimeZone.toString(), importexportsetting_timezone.getMendixObject().getId());
	}

	/**
	 * @return value of ImportExportSetting_DateTimeFormat
	 */
	public final mendix.proxies.DateTimeFormat getImportExportSetting_DateTimeFormat() throws com.mendix.core.CoreException
	{
		return getImportExportSetting_DateTimeFormat(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportExportSetting_DateTimeFormat
	 */
	public final mendix.proxies.DateTimeFormat getImportExportSetting_DateTimeFormat(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mendix.proxies.DateTimeFormat result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ImportExportSetting_DateTimeFormat.toString());
		if (identifier != null)
			result = mendix.proxies.DateTimeFormat.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ImportExportSetting_DateTimeFormat
	 * @param importexportsetting_datetimeformat
	 */
	public final void setImportExportSetting_DateTimeFormat(mendix.proxies.DateTimeFormat importexportsetting_datetimeformat)
	{
		setImportExportSetting_DateTimeFormat(getContext(), importexportsetting_datetimeformat);
	}

	/**
	 * Set value of ImportExportSetting_DateTimeFormat
	 * @param context
	 * @param importexportsetting_datetimeformat
	 */
	public final void setImportExportSetting_DateTimeFormat(com.mendix.systemwideinterfaces.core.IContext context, mendix.proxies.DateTimeFormat importexportsetting_datetimeformat)
	{
		if (importexportsetting_datetimeformat == null)
			getMendixObject().setValue(context, MemberNames.ImportExportSetting_DateTimeFormat.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ImportExportSetting_DateTimeFormat.toString(), importexportsetting_datetimeformat.getMendixObject().getId());
	}

	/**
	 * @return value of ImportExportSetting_ToServer
	 */
	public final mendix.proxies.Server getImportExportSetting_ToServer() throws com.mendix.core.CoreException
	{
		return getImportExportSetting_ToServer(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportExportSetting_ToServer
	 */
	public final mendix.proxies.Server getImportExportSetting_ToServer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mendix.proxies.Server result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ImportExportSetting_ToServer.toString());
		if (identifier != null)
			result = mendix.proxies.Server.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ImportExportSetting_ToServer
	 * @param importexportsetting_toserver
	 */
	public final void setImportExportSetting_ToServer(mendix.proxies.Server importexportsetting_toserver)
	{
		setImportExportSetting_ToServer(getContext(), importexportsetting_toserver);
	}

	/**
	 * Set value of ImportExportSetting_ToServer
	 * @param context
	 * @param importexportsetting_toserver
	 */
	public final void setImportExportSetting_ToServer(com.mendix.systemwideinterfaces.core.IContext context, mendix.proxies.Server importexportsetting_toserver)
	{
		if (importexportsetting_toserver == null)
			getMendixObject().setValue(context, MemberNames.ImportExportSetting_ToServer.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ImportExportSetting_ToServer.toString(), importexportsetting_toserver.getMendixObject().getId());
	}

	/**
	 * @return value of ImportExportSetting_MendixEntities
	 */
	public final java.util.List<metamodel.proxies.MendixEntity> getImportExportSetting_MendixEntities() throws com.mendix.core.CoreException
	{
		return getImportExportSetting_MendixEntities(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportExportSetting_MendixEntities
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<metamodel.proxies.MendixEntity> getImportExportSetting_MendixEntities(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<metamodel.proxies.MendixEntity> result = new java.util.ArrayList<metamodel.proxies.MendixEntity>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.ImportExportSetting_MendixEntities.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(metamodel.proxies.MendixEntity.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of ImportExportSetting_MendixEntities
	 * @param importexportsetting_mendixentities
	 */
	public final void setImportExportSetting_MendixEntities(java.util.List<metamodel.proxies.MendixEntity> importexportsetting_mendixentities)
	{
		setImportExportSetting_MendixEntities(getContext(), importexportsetting_mendixentities);
	}

	/**
	 * Set value of ImportExportSetting_MendixEntities
	 * @param context
	 * @param importexportsetting_mendixentities
	 */
	public final void setImportExportSetting_MendixEntities(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<metamodel.proxies.MendixEntity> importexportsetting_mendixentities)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (metamodel.proxies.MendixEntity proxyObject : importexportsetting_mendixentities)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.ImportExportSetting_MendixEntities.toString(), identifiers);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final importexport.proxies.ImportExportSetting that = (importexport.proxies.ImportExportSetting) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ImportExport.ImportExportSetting";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
