// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package importexport.proxies;

public class JobFile extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ImportExport.JobFile";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		JobFile_Job("ImportExport.JobFile_Job");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public JobFile(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ImportExport.JobFile"));
	}

	protected JobFile(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject jobFileMendixObject)
	{
		super(context, jobFileMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("ImportExport.JobFile", jobFileMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ImportExport.JobFile");
	}

	/**
	 * @deprecated Use 'JobFile.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static importexport.proxies.JobFile initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return importexport.proxies.JobFile.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static importexport.proxies.JobFile initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new importexport.proxies.JobFile(context, mendixObject);
	}

	public static importexport.proxies.JobFile load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return importexport.proxies.JobFile.initialize(context, mendixObject);
	}

	public static java.util.List<importexport.proxies.JobFile> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<importexport.proxies.JobFile> result = new java.util.ArrayList<importexport.proxies.JobFile>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//ImportExport.JobFile" + xpathConstraint))
			result.add(importexport.proxies.JobFile.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of JobFile_Job
	 */
	public final importexport.proxies.Job getJobFile_Job() throws com.mendix.core.CoreException
	{
		return getJobFile_Job(getContext());
	}

	/**
	 * @param context
	 * @return value of JobFile_Job
	 */
	public final importexport.proxies.Job getJobFile_Job(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		importexport.proxies.Job result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.JobFile_Job.toString());
		if (identifier != null)
			result = importexport.proxies.Job.load(context, identifier);
		return result;
	}

	/**
	 * Set value of JobFile_Job
	 * @param jobfile_job
	 */
	public final void setJobFile_Job(importexport.proxies.Job jobfile_job)
	{
		setJobFile_Job(getContext(), jobfile_job);
	}

	/**
	 * Set value of JobFile_Job
	 * @param context
	 * @param jobfile_job
	 */
	public final void setJobFile_Job(com.mendix.systemwideinterfaces.core.IContext context, importexport.proxies.Job jobfile_job)
	{
		if (jobfile_job == null)
			getMendixObject().setValue(context, MemberNames.JobFile_Job.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.JobFile_Job.toString(), jobfile_job.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final importexport.proxies.JobFile that = (importexport.proxies.JobFile) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ImportExport.JobFile";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
