// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package interfaceexternalreferences.proxies;

public class ExternalReferencesContainerExpertDesk
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject externalReferencesContainerExpertDeskMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "InterfaceExternalReferences.ExternalReferencesContainerExpertDesk";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ExternalReferenceResponseGUID_ExternalReferencesContainerExpertDesk("InterfaceExternalReferences.ExternalReferenceResponseGUID_ExternalReferencesContainerExpertDesk"),
		ExternalReferencesContainerExpertDesk_ExternalReferenceResponse("InterfaceExternalReferences.ExternalReferencesContainerExpertDesk_ExternalReferenceResponse"),
		ExternalReferencesContainerExpertDesk_OutgoingExternalReferencesExpertDesk("InterfaceExternalReferences.ExternalReferencesContainerExpertDesk_OutgoingExternalReferencesExpertDesk"),
		ExternalReferencesContainerExpertDesk_OutgoingRequestExpertDesk("InterfaceExternalReferences.ExternalReferencesContainerExpertDesk_OutgoingRequestExpertDesk");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ExternalReferencesContainerExpertDesk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "InterfaceExternalReferences.ExternalReferencesContainerExpertDesk"));
	}

	protected ExternalReferencesContainerExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject externalReferencesContainerExpertDeskMendixObject)
	{
		if (externalReferencesContainerExpertDeskMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("InterfaceExternalReferences.ExternalReferencesContainerExpertDesk", externalReferencesContainerExpertDeskMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a InterfaceExternalReferences.ExternalReferencesContainerExpertDesk");

		this.externalReferencesContainerExpertDeskMendixObject = externalReferencesContainerExpertDeskMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ExternalReferencesContainerExpertDesk.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static interfaceexternalreferences.proxies.ExternalReferencesContainerExpertDesk initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return interfaceexternalreferences.proxies.ExternalReferencesContainerExpertDesk.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static interfaceexternalreferences.proxies.ExternalReferencesContainerExpertDesk initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new interfaceexternalreferences.proxies.ExternalReferencesContainerExpertDesk(context, mendixObject);
	}

	public static interfaceexternalreferences.proxies.ExternalReferencesContainerExpertDesk load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return interfaceexternalreferences.proxies.ExternalReferencesContainerExpertDesk.initialize(context, mendixObject);
	}

	public static java.util.List<interfaceexternalreferences.proxies.ExternalReferencesContainerExpertDesk> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<interfaceexternalreferences.proxies.ExternalReferencesContainerExpertDesk> result = new java.util.ArrayList<interfaceexternalreferences.proxies.ExternalReferencesContainerExpertDesk>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//InterfaceExternalReferences.ExternalReferencesContainerExpertDesk" + xpathConstraint))
			result.add(interfaceexternalreferences.proxies.ExternalReferencesContainerExpertDesk.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ExternalReferenceResponseGUID_ExternalReferencesContainerExpertDesk
	 */
	public final interfaceexternalreferences.proxies.ExternalReference getExternalReferenceResponseGUID_ExternalReferencesContainerExpertDesk() throws com.mendix.core.CoreException
	{
		return getExternalReferenceResponseGUID_ExternalReferencesContainerExpertDesk(getContext());
	}

	/**
	 * @param context
	 * @return value of ExternalReferenceResponseGUID_ExternalReferencesContainerExpertDesk
	 */
	public final interfaceexternalreferences.proxies.ExternalReference getExternalReferenceResponseGUID_ExternalReferencesContainerExpertDesk(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceexternalreferences.proxies.ExternalReference result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ExternalReferenceResponseGUID_ExternalReferencesContainerExpertDesk.toString());
		if (identifier != null)
			result = interfaceexternalreferences.proxies.ExternalReference.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ExternalReferenceResponseGUID_ExternalReferencesContainerExpertDesk
	 * @param externalreferenceresponseguid_externalreferencescontainerexpertdesk
	 */
	public final void setExternalReferenceResponseGUID_ExternalReferencesContainerExpertDesk(interfaceexternalreferences.proxies.ExternalReference externalreferenceresponseguid_externalreferencescontainerexpertdesk)
	{
		setExternalReferenceResponseGUID_ExternalReferencesContainerExpertDesk(getContext(), externalreferenceresponseguid_externalreferencescontainerexpertdesk);
	}

	/**
	 * Set value of ExternalReferenceResponseGUID_ExternalReferencesContainerExpertDesk
	 * @param context
	 * @param externalreferenceresponseguid_externalreferencescontainerexpertdesk
	 */
	public final void setExternalReferenceResponseGUID_ExternalReferencesContainerExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, interfaceexternalreferences.proxies.ExternalReference externalreferenceresponseguid_externalreferencescontainerexpertdesk)
	{
		if (externalreferenceresponseguid_externalreferencescontainerexpertdesk == null)
			getMendixObject().setValue(context, MemberNames.ExternalReferenceResponseGUID_ExternalReferencesContainerExpertDesk.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ExternalReferenceResponseGUID_ExternalReferencesContainerExpertDesk.toString(), externalreferenceresponseguid_externalreferencescontainerexpertdesk.getMendixObject().getId());
	}

	/**
	 * @return value of ExternalReferencesContainerExpertDesk_ExternalReferenceResponse
	 */
	public final interfaceexternalreferences.proxies.ExternalReferenceResponse getExternalReferencesContainerExpertDesk_ExternalReferenceResponse() throws com.mendix.core.CoreException
	{
		return getExternalReferencesContainerExpertDesk_ExternalReferenceResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of ExternalReferencesContainerExpertDesk_ExternalReferenceResponse
	 */
	public final interfaceexternalreferences.proxies.ExternalReferenceResponse getExternalReferencesContainerExpertDesk_ExternalReferenceResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceexternalreferences.proxies.ExternalReferenceResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ExternalReferencesContainerExpertDesk_ExternalReferenceResponse.toString());
		if (identifier != null)
			result = interfaceexternalreferences.proxies.ExternalReferenceResponse.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ExternalReferencesContainerExpertDesk_ExternalReferenceResponse
	 * @param externalreferencescontainerexpertdesk_externalreferenceresponse
	 */
	public final void setExternalReferencesContainerExpertDesk_ExternalReferenceResponse(interfaceexternalreferences.proxies.ExternalReferenceResponse externalreferencescontainerexpertdesk_externalreferenceresponse)
	{
		setExternalReferencesContainerExpertDesk_ExternalReferenceResponse(getContext(), externalreferencescontainerexpertdesk_externalreferenceresponse);
	}

	/**
	 * Set value of ExternalReferencesContainerExpertDesk_ExternalReferenceResponse
	 * @param context
	 * @param externalreferencescontainerexpertdesk_externalreferenceresponse
	 */
	public final void setExternalReferencesContainerExpertDesk_ExternalReferenceResponse(com.mendix.systemwideinterfaces.core.IContext context, interfaceexternalreferences.proxies.ExternalReferenceResponse externalreferencescontainerexpertdesk_externalreferenceresponse)
	{
		if (externalreferencescontainerexpertdesk_externalreferenceresponse == null)
			getMendixObject().setValue(context, MemberNames.ExternalReferencesContainerExpertDesk_ExternalReferenceResponse.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ExternalReferencesContainerExpertDesk_ExternalReferenceResponse.toString(), externalreferencescontainerexpertdesk_externalreferenceresponse.getMendixObject().getId());
	}

	/**
	 * @return value of ExternalReferencesContainerExpertDesk_OutgoingExternalReferencesExpertDesk
	 */
	public final interfaceexternalreferences.proxies.OutgoingExternalReferencesExpertDesk getExternalReferencesContainerExpertDesk_OutgoingExternalReferencesExpertDesk() throws com.mendix.core.CoreException
	{
		return getExternalReferencesContainerExpertDesk_OutgoingExternalReferencesExpertDesk(getContext());
	}

	/**
	 * @param context
	 * @return value of ExternalReferencesContainerExpertDesk_OutgoingExternalReferencesExpertDesk
	 */
	public final interfaceexternalreferences.proxies.OutgoingExternalReferencesExpertDesk getExternalReferencesContainerExpertDesk_OutgoingExternalReferencesExpertDesk(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceexternalreferences.proxies.OutgoingExternalReferencesExpertDesk result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ExternalReferencesContainerExpertDesk_OutgoingExternalReferencesExpertDesk.toString());
		if (identifier != null)
			result = interfaceexternalreferences.proxies.OutgoingExternalReferencesExpertDesk.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ExternalReferencesContainerExpertDesk_OutgoingExternalReferencesExpertDesk
	 * @param externalreferencescontainerexpertdesk_outgoingexternalreferencesexpertdesk
	 */
	public final void setExternalReferencesContainerExpertDesk_OutgoingExternalReferencesExpertDesk(interfaceexternalreferences.proxies.OutgoingExternalReferencesExpertDesk externalreferencescontainerexpertdesk_outgoingexternalreferencesexpertdesk)
	{
		setExternalReferencesContainerExpertDesk_OutgoingExternalReferencesExpertDesk(getContext(), externalreferencescontainerexpertdesk_outgoingexternalreferencesexpertdesk);
	}

	/**
	 * Set value of ExternalReferencesContainerExpertDesk_OutgoingExternalReferencesExpertDesk
	 * @param context
	 * @param externalreferencescontainerexpertdesk_outgoingexternalreferencesexpertdesk
	 */
	public final void setExternalReferencesContainerExpertDesk_OutgoingExternalReferencesExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, interfaceexternalreferences.proxies.OutgoingExternalReferencesExpertDesk externalreferencescontainerexpertdesk_outgoingexternalreferencesexpertdesk)
	{
		if (externalreferencescontainerexpertdesk_outgoingexternalreferencesexpertdesk == null)
			getMendixObject().setValue(context, MemberNames.ExternalReferencesContainerExpertDesk_OutgoingExternalReferencesExpertDesk.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ExternalReferencesContainerExpertDesk_OutgoingExternalReferencesExpertDesk.toString(), externalreferencescontainerexpertdesk_outgoingexternalreferencesexpertdesk.getMendixObject().getId());
	}

	/**
	 * @return value of ExternalReferencesContainerExpertDesk_OutgoingRequestExpertDesk
	 */
	public final interfacerequests.proxies.OutgoingRequestExpertDesk getExternalReferencesContainerExpertDesk_OutgoingRequestExpertDesk() throws com.mendix.core.CoreException
	{
		return getExternalReferencesContainerExpertDesk_OutgoingRequestExpertDesk(getContext());
	}

	/**
	 * @param context
	 * @return value of ExternalReferencesContainerExpertDesk_OutgoingRequestExpertDesk
	 */
	public final interfacerequests.proxies.OutgoingRequestExpertDesk getExternalReferencesContainerExpertDesk_OutgoingRequestExpertDesk(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacerequests.proxies.OutgoingRequestExpertDesk result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ExternalReferencesContainerExpertDesk_OutgoingRequestExpertDesk.toString());
		if (identifier != null)
			result = interfacerequests.proxies.OutgoingRequestExpertDesk.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ExternalReferencesContainerExpertDesk_OutgoingRequestExpertDesk
	 * @param externalreferencescontainerexpertdesk_outgoingrequestexpertdesk
	 */
	public final void setExternalReferencesContainerExpertDesk_OutgoingRequestExpertDesk(interfacerequests.proxies.OutgoingRequestExpertDesk externalreferencescontainerexpertdesk_outgoingrequestexpertdesk)
	{
		setExternalReferencesContainerExpertDesk_OutgoingRequestExpertDesk(getContext(), externalreferencescontainerexpertdesk_outgoingrequestexpertdesk);
	}

	/**
	 * Set value of ExternalReferencesContainerExpertDesk_OutgoingRequestExpertDesk
	 * @param context
	 * @param externalreferencescontainerexpertdesk_outgoingrequestexpertdesk
	 */
	public final void setExternalReferencesContainerExpertDesk_OutgoingRequestExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, interfacerequests.proxies.OutgoingRequestExpertDesk externalreferencescontainerexpertdesk_outgoingrequestexpertdesk)
	{
		if (externalreferencescontainerexpertdesk_outgoingrequestexpertdesk == null)
			getMendixObject().setValue(context, MemberNames.ExternalReferencesContainerExpertDesk_OutgoingRequestExpertDesk.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ExternalReferencesContainerExpertDesk_OutgoingRequestExpertDesk.toString(), externalreferencescontainerexpertdesk_outgoingrequestexpertdesk.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return externalReferencesContainerExpertDeskMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final interfaceexternalreferences.proxies.ExternalReferencesContainerExpertDesk that = (interfaceexternalreferences.proxies.ExternalReferencesContainerExpertDesk) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "InterfaceExternalReferences.ExternalReferencesContainerExpertDesk";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
