// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package servicecatalogue.proxies;

public class Delivery
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject deliveryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ServiceCatalogue.Delivery";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DeliveryDate("DeliveryDate"),
		DeliveryStatus("DeliveryStatus"),
		DeliveryClosed("DeliveryClosed"),
		ValidRecord("ValidRecord"),
		Delivery_Request("ServiceCatalogue.Delivery_Request"),
		Delivery_SRM_Request("ServiceCatalogue.Delivery_SRM_Request");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Delivery(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ServiceCatalogue.Delivery"));
	}

	protected Delivery(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject deliveryMendixObject)
	{
		if (deliveryMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("ServiceCatalogue.Delivery", deliveryMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ServiceCatalogue.Delivery");

		this.deliveryMendixObject = deliveryMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Delivery.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static servicecatalogue.proxies.Delivery initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return servicecatalogue.proxies.Delivery.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static servicecatalogue.proxies.Delivery initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new servicecatalogue.proxies.Delivery(context, mendixObject);
	}

	public static servicecatalogue.proxies.Delivery load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return servicecatalogue.proxies.Delivery.initialize(context, mendixObject);
	}

	public static java.util.List<servicecatalogue.proxies.Delivery> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<servicecatalogue.proxies.Delivery> result = new java.util.ArrayList<servicecatalogue.proxies.Delivery>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//ServiceCatalogue.Delivery" + xpathConstraint))
			result.add(servicecatalogue.proxies.Delivery.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DeliveryDate
	 */
	public final java.util.Date getDeliveryDate()
	{
		return getDeliveryDate(getContext());
	}

	/**
	 * @param context
	 * @return value of DeliveryDate
	 */
	public final java.util.Date getDeliveryDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DeliveryDate.toString());
	}

	/**
	 * Set value of DeliveryDate
	 * @param deliverydate
	 */
	public final void setDeliveryDate(java.util.Date deliverydate)
	{
		setDeliveryDate(getContext(), deliverydate);
	}

	/**
	 * Set value of DeliveryDate
	 * @param context
	 * @param deliverydate
	 */
	public final void setDeliveryDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date deliverydate)
	{
		getMendixObject().setValue(context, MemberNames.DeliveryDate.toString(), deliverydate);
	}

	/**
	 * Set value of DeliveryStatus
	 * @param deliverystatus
	 */
	public final servicecatalogue.proxies.DeliveryState getDeliveryStatus()
	{
		return getDeliveryStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of DeliveryStatus
	 */
	public final servicecatalogue.proxies.DeliveryState getDeliveryStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.DeliveryStatus.toString());
		if (obj == null)
			return null;

		return servicecatalogue.proxies.DeliveryState.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of DeliveryStatus
	 * @param deliverystatus
	 */
	public final void setDeliveryStatus(servicecatalogue.proxies.DeliveryState deliverystatus)
	{
		setDeliveryStatus(getContext(), deliverystatus);
	}

	/**
	 * Set value of DeliveryStatus
	 * @param context
	 * @param deliverystatus
	 */
	public final void setDeliveryStatus(com.mendix.systemwideinterfaces.core.IContext context, servicecatalogue.proxies.DeliveryState deliverystatus)
	{
		if (deliverystatus != null)
			getMendixObject().setValue(context, MemberNames.DeliveryStatus.toString(), deliverystatus.toString());
		else
			getMendixObject().setValue(context, MemberNames.DeliveryStatus.toString(), null);
	}

	/**
	 * @return value of DeliveryClosed
	 */
	public final java.lang.Boolean getDeliveryClosed()
	{
		return getDeliveryClosed(getContext());
	}

	/**
	 * @param context
	 * @return value of DeliveryClosed
	 */
	public final java.lang.Boolean getDeliveryClosed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.DeliveryClosed.toString());
	}

	/**
	 * Set value of DeliveryClosed
	 * @param deliveryclosed
	 */
	public final void setDeliveryClosed(java.lang.Boolean deliveryclosed)
	{
		setDeliveryClosed(getContext(), deliveryclosed);
	}

	/**
	 * Set value of DeliveryClosed
	 * @param context
	 * @param deliveryclosed
	 */
	public final void setDeliveryClosed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean deliveryclosed)
	{
		getMendixObject().setValue(context, MemberNames.DeliveryClosed.toString(), deliveryclosed);
	}

	/**
	 * @return value of ValidRecord
	 */
	public final java.lang.Boolean getValidRecord()
	{
		return getValidRecord(getContext());
	}

	/**
	 * @param context
	 * @return value of ValidRecord
	 */
	public final java.lang.Boolean getValidRecord(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ValidRecord.toString());
	}

	/**
	 * Set value of ValidRecord
	 * @param validrecord
	 */
	public final void setValidRecord(java.lang.Boolean validrecord)
	{
		setValidRecord(getContext(), validrecord);
	}

	/**
	 * Set value of ValidRecord
	 * @param context
	 * @param validrecord
	 */
	public final void setValidRecord(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean validrecord)
	{
		getMendixObject().setValue(context, MemberNames.ValidRecord.toString(), validrecord);
	}

	/**
	 * @return value of Delivery_Request
	 */
	public final process.proxies.Request getDelivery_Request() throws com.mendix.core.CoreException
	{
		return getDelivery_Request(getContext());
	}

	/**
	 * @param context
	 * @return value of Delivery_Request
	 */
	public final process.proxies.Request getDelivery_Request(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		process.proxies.Request result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Delivery_Request.toString());
		if (identifier != null)
			result = process.proxies.Request.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Delivery_Request
	 * @param delivery_request
	 */
	public final void setDelivery_Request(process.proxies.Request delivery_request)
	{
		setDelivery_Request(getContext(), delivery_request);
	}

	/**
	 * Set value of Delivery_Request
	 * @param context
	 * @param delivery_request
	 */
	public final void setDelivery_Request(com.mendix.systemwideinterfaces.core.IContext context, process.proxies.Request delivery_request)
	{
		if (delivery_request == null)
			getMendixObject().setValue(context, MemberNames.Delivery_Request.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Delivery_Request.toString(), delivery_request.getMendixObject().getId());
	}

	/**
	 * @return value of Delivery_SRM_Request
	 */
	public final process.proxies.Request getDelivery_SRM_Request() throws com.mendix.core.CoreException
	{
		return getDelivery_SRM_Request(getContext());
	}

	/**
	 * @param context
	 * @return value of Delivery_SRM_Request
	 */
	public final process.proxies.Request getDelivery_SRM_Request(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		process.proxies.Request result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Delivery_SRM_Request.toString());
		if (identifier != null)
			result = process.proxies.Request.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Delivery_SRM_Request
	 * @param delivery_srm_request
	 */
	public final void setDelivery_SRM_Request(process.proxies.Request delivery_srm_request)
	{
		setDelivery_SRM_Request(getContext(), delivery_srm_request);
	}

	/**
	 * Set value of Delivery_SRM_Request
	 * @param context
	 * @param delivery_srm_request
	 */
	public final void setDelivery_SRM_Request(com.mendix.systemwideinterfaces.core.IContext context, process.proxies.Request delivery_srm_request)
	{
		if (delivery_srm_request == null)
			getMendixObject().setValue(context, MemberNames.Delivery_SRM_Request.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Delivery_SRM_Request.toString(), delivery_srm_request.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return deliveryMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final servicecatalogue.proxies.Delivery that = (servicecatalogue.proxies.Delivery) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ServiceCatalogue.Delivery";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
