// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package servicecatalogue.proxies;

public class ShoppingCartCI_Instantiated
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject shoppingCartCI_InstantiatedMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ServiceCatalogue.ShoppingCartCI_Instantiated";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Order("Order"),
		ShoppingCartCI_Instantiated_ShoppingCartCI("ServiceCatalogue.ShoppingCartCI_Instantiated_ShoppingCartCI"),
		ShoppingCartCI_Instantiated_ConfigurationItem("ServiceCatalogue.ShoppingCartCI_Instantiated_ConfigurationItem");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ShoppingCartCI_Instantiated(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ServiceCatalogue.ShoppingCartCI_Instantiated"));
	}

	protected ShoppingCartCI_Instantiated(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject shoppingCartCI_InstantiatedMendixObject)
	{
		if (shoppingCartCI_InstantiatedMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("ServiceCatalogue.ShoppingCartCI_Instantiated", shoppingCartCI_InstantiatedMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ServiceCatalogue.ShoppingCartCI_Instantiated");

		this.shoppingCartCI_InstantiatedMendixObject = shoppingCartCI_InstantiatedMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ShoppingCartCI_Instantiated.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static servicecatalogue.proxies.ShoppingCartCI_Instantiated initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return servicecatalogue.proxies.ShoppingCartCI_Instantiated.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static servicecatalogue.proxies.ShoppingCartCI_Instantiated initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new servicecatalogue.proxies.ShoppingCartCI_Instantiated(context, mendixObject);
	}

	public static servicecatalogue.proxies.ShoppingCartCI_Instantiated load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return servicecatalogue.proxies.ShoppingCartCI_Instantiated.initialize(context, mendixObject);
	}

	public static java.util.List<servicecatalogue.proxies.ShoppingCartCI_Instantiated> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<servicecatalogue.proxies.ShoppingCartCI_Instantiated> result = new java.util.ArrayList<servicecatalogue.proxies.ShoppingCartCI_Instantiated>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//ServiceCatalogue.ShoppingCartCI_Instantiated" + xpathConstraint))
			result.add(servicecatalogue.proxies.ShoppingCartCI_Instantiated.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Order
	 */
	public final java.lang.Integer getOrder()
	{
		return getOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of Order
	 */
	public final java.lang.Integer getOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Order.toString());
	}

	/**
	 * Set value of Order
	 * @param order
	 */
	public final void setOrder(java.lang.Integer order)
	{
		setOrder(getContext(), order);
	}

	/**
	 * Set value of Order
	 * @param context
	 * @param order
	 */
	public final void setOrder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer order)
	{
		getMendixObject().setValue(context, MemberNames.Order.toString(), order);
	}

	/**
	 * @return value of ShoppingCartCI_Instantiated_ShoppingCartCI
	 */
	public final servicecatalogue.proxies.ShoppingCartCI getShoppingCartCI_Instantiated_ShoppingCartCI() throws com.mendix.core.CoreException
	{
		return getShoppingCartCI_Instantiated_ShoppingCartCI(getContext());
	}

	/**
	 * @param context
	 * @return value of ShoppingCartCI_Instantiated_ShoppingCartCI
	 */
	public final servicecatalogue.proxies.ShoppingCartCI getShoppingCartCI_Instantiated_ShoppingCartCI(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		servicecatalogue.proxies.ShoppingCartCI result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ShoppingCartCI_Instantiated_ShoppingCartCI.toString());
		if (identifier != null)
			result = servicecatalogue.proxies.ShoppingCartCI.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ShoppingCartCI_Instantiated_ShoppingCartCI
	 * @param shoppingcartci_instantiated_shoppingcartci
	 */
	public final void setShoppingCartCI_Instantiated_ShoppingCartCI(servicecatalogue.proxies.ShoppingCartCI shoppingcartci_instantiated_shoppingcartci)
	{
		setShoppingCartCI_Instantiated_ShoppingCartCI(getContext(), shoppingcartci_instantiated_shoppingcartci);
	}

	/**
	 * Set value of ShoppingCartCI_Instantiated_ShoppingCartCI
	 * @param context
	 * @param shoppingcartci_instantiated_shoppingcartci
	 */
	public final void setShoppingCartCI_Instantiated_ShoppingCartCI(com.mendix.systemwideinterfaces.core.IContext context, servicecatalogue.proxies.ShoppingCartCI shoppingcartci_instantiated_shoppingcartci)
	{
		if (shoppingcartci_instantiated_shoppingcartci == null)
			getMendixObject().setValue(context, MemberNames.ShoppingCartCI_Instantiated_ShoppingCartCI.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ShoppingCartCI_Instantiated_ShoppingCartCI.toString(), shoppingcartci_instantiated_shoppingcartci.getMendixObject().getId());
	}

	/**
	 * @return value of ShoppingCartCI_Instantiated_ConfigurationItem
	 */
	public final cmdb.proxies.ConfigurationItem getShoppingCartCI_Instantiated_ConfigurationItem() throws com.mendix.core.CoreException
	{
		return getShoppingCartCI_Instantiated_ConfigurationItem(getContext());
	}

	/**
	 * @param context
	 * @return value of ShoppingCartCI_Instantiated_ConfigurationItem
	 */
	public final cmdb.proxies.ConfigurationItem getShoppingCartCI_Instantiated_ConfigurationItem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmdb.proxies.ConfigurationItem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ShoppingCartCI_Instantiated_ConfigurationItem.toString());
		if (identifier != null)
			result = cmdb.proxies.ConfigurationItem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ShoppingCartCI_Instantiated_ConfigurationItem
	 * @param shoppingcartci_instantiated_configurationitem
	 */
	public final void setShoppingCartCI_Instantiated_ConfigurationItem(cmdb.proxies.ConfigurationItem shoppingcartci_instantiated_configurationitem)
	{
		setShoppingCartCI_Instantiated_ConfigurationItem(getContext(), shoppingcartci_instantiated_configurationitem);
	}

	/**
	 * Set value of ShoppingCartCI_Instantiated_ConfigurationItem
	 * @param context
	 * @param shoppingcartci_instantiated_configurationitem
	 */
	public final void setShoppingCartCI_Instantiated_ConfigurationItem(com.mendix.systemwideinterfaces.core.IContext context, cmdb.proxies.ConfigurationItem shoppingcartci_instantiated_configurationitem)
	{
		if (shoppingcartci_instantiated_configurationitem == null)
			getMendixObject().setValue(context, MemberNames.ShoppingCartCI_Instantiated_ConfigurationItem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ShoppingCartCI_Instantiated_ConfigurationItem.toString(), shoppingcartci_instantiated_configurationitem.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return shoppingCartCI_InstantiatedMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final servicecatalogue.proxies.ShoppingCartCI_Instantiated that = (servicecatalogue.proxies.ShoppingCartCI_Instantiated) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ServiceCatalogue.ShoppingCartCI_Instantiated";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
