// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cmdb.proxies;

public class AttributeValue
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject attributeValueMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CMDB.AttributeValue";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Value("Value"),
		Active("Active"),
		AttributeValueChanged("AttributeValueChanged"),
		AttributeValue_CIDefinitionAttribute("CMDB.AttributeValue_CIDefinitionAttribute"),
		CIDefinitionAttribute_DefaultAttributeValue("CMDB.CIDefinitionAttribute_DefaultAttributeValue"),
		AttributeValue_CIDefinitionAttribute_Temp("CMDB.AttributeValue_CIDefinitionAttribute_Temp");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AttributeValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CMDB.AttributeValue"));
	}

	protected AttributeValue(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject attributeValueMendixObject)
	{
		if (attributeValueMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("CMDB.AttributeValue", attributeValueMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CMDB.AttributeValue");

		this.attributeValueMendixObject = attributeValueMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AttributeValue.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static cmdb.proxies.AttributeValue initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return cmdb.proxies.AttributeValue.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static cmdb.proxies.AttributeValue initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new cmdb.proxies.AttributeValue(context, mendixObject);
	}

	public static cmdb.proxies.AttributeValue load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return cmdb.proxies.AttributeValue.initialize(context, mendixObject);
	}

	public static java.util.List<cmdb.proxies.AttributeValue> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<cmdb.proxies.AttributeValue> result = new java.util.ArrayList<cmdb.proxies.AttributeValue>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CMDB.AttributeValue" + xpathConstraint))
			result.add(cmdb.proxies.AttributeValue.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Value
	 */
	public final java.lang.String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final java.lang.String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(java.lang.String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive()
	{
		return getActive(getContext());
	}

	/**
	 * @param context
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Active.toString());
	}

	/**
	 * Set value of Active
	 * @param active
	 */
	public final void setActive(java.lang.Boolean active)
	{
		setActive(getContext(), active);
	}

	/**
	 * Set value of Active
	 * @param context
	 * @param active
	 */
	public final void setActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean active)
	{
		getMendixObject().setValue(context, MemberNames.Active.toString(), active);
	}

	/**
	 * @return value of AttributeValueChanged
	 */
	public final java.lang.Boolean getAttributeValueChanged()
	{
		return getAttributeValueChanged(getContext());
	}

	/**
	 * @param context
	 * @return value of AttributeValueChanged
	 */
	public final java.lang.Boolean getAttributeValueChanged(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AttributeValueChanged.toString());
	}

	/**
	 * Set value of AttributeValueChanged
	 * @param attributevaluechanged
	 */
	public final void setAttributeValueChanged(java.lang.Boolean attributevaluechanged)
	{
		setAttributeValueChanged(getContext(), attributevaluechanged);
	}

	/**
	 * Set value of AttributeValueChanged
	 * @param context
	 * @param attributevaluechanged
	 */
	public final void setAttributeValueChanged(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean attributevaluechanged)
	{
		getMendixObject().setValue(context, MemberNames.AttributeValueChanged.toString(), attributevaluechanged);
	}

	/**
	 * @return value of AttributeValue_CIDefinitionAttribute
	 */
	public final cmdb.proxies.CIDefinitionAttribute getAttributeValue_CIDefinitionAttribute() throws com.mendix.core.CoreException
	{
		return getAttributeValue_CIDefinitionAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of AttributeValue_CIDefinitionAttribute
	 */
	public final cmdb.proxies.CIDefinitionAttribute getAttributeValue_CIDefinitionAttribute(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmdb.proxies.CIDefinitionAttribute result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AttributeValue_CIDefinitionAttribute.toString());
		if (identifier != null)
			result = cmdb.proxies.CIDefinitionAttribute.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AttributeValue_CIDefinitionAttribute
	 * @param attributevalue_cidefinitionattribute
	 */
	public final void setAttributeValue_CIDefinitionAttribute(cmdb.proxies.CIDefinitionAttribute attributevalue_cidefinitionattribute)
	{
		setAttributeValue_CIDefinitionAttribute(getContext(), attributevalue_cidefinitionattribute);
	}

	/**
	 * Set value of AttributeValue_CIDefinitionAttribute
	 * @param context
	 * @param attributevalue_cidefinitionattribute
	 */
	public final void setAttributeValue_CIDefinitionAttribute(com.mendix.systemwideinterfaces.core.IContext context, cmdb.proxies.CIDefinitionAttribute attributevalue_cidefinitionattribute)
	{
		if (attributevalue_cidefinitionattribute == null)
			getMendixObject().setValue(context, MemberNames.AttributeValue_CIDefinitionAttribute.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AttributeValue_CIDefinitionAttribute.toString(), attributevalue_cidefinitionattribute.getMendixObject().getId());
	}

	/**
	 * @return value of CIDefinitionAttribute_DefaultAttributeValue
	 */
	public final cmdb.proxies.CIDefinitionAttribute getCIDefinitionAttribute_DefaultAttributeValue() throws com.mendix.core.CoreException
	{
		return getCIDefinitionAttribute_DefaultAttributeValue(getContext());
	}

	/**
	 * @param context
	 * @return value of CIDefinitionAttribute_DefaultAttributeValue
	 */
	public final cmdb.proxies.CIDefinitionAttribute getCIDefinitionAttribute_DefaultAttributeValue(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmdb.proxies.CIDefinitionAttribute result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CIDefinitionAttribute_DefaultAttributeValue.toString());
		if (identifier != null)
			result = cmdb.proxies.CIDefinitionAttribute.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CIDefinitionAttribute_DefaultAttributeValue
	 * @param cidefinitionattribute_defaultattributevalue
	 */
	public final void setCIDefinitionAttribute_DefaultAttributeValue(cmdb.proxies.CIDefinitionAttribute cidefinitionattribute_defaultattributevalue)
	{
		setCIDefinitionAttribute_DefaultAttributeValue(getContext(), cidefinitionattribute_defaultattributevalue);
	}

	/**
	 * Set value of CIDefinitionAttribute_DefaultAttributeValue
	 * @param context
	 * @param cidefinitionattribute_defaultattributevalue
	 */
	public final void setCIDefinitionAttribute_DefaultAttributeValue(com.mendix.systemwideinterfaces.core.IContext context, cmdb.proxies.CIDefinitionAttribute cidefinitionattribute_defaultattributevalue)
	{
		if (cidefinitionattribute_defaultattributevalue == null)
			getMendixObject().setValue(context, MemberNames.CIDefinitionAttribute_DefaultAttributeValue.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CIDefinitionAttribute_DefaultAttributeValue.toString(), cidefinitionattribute_defaultattributevalue.getMendixObject().getId());
	}

	/**
	 * @return value of AttributeValue_CIDefinitionAttribute_Temp
	 */
	public final cmdb.proxies.CIDefinitionAttribute getAttributeValue_CIDefinitionAttribute_Temp() throws com.mendix.core.CoreException
	{
		return getAttributeValue_CIDefinitionAttribute_Temp(getContext());
	}

	/**
	 * @param context
	 * @return value of AttributeValue_CIDefinitionAttribute_Temp
	 */
	public final cmdb.proxies.CIDefinitionAttribute getAttributeValue_CIDefinitionAttribute_Temp(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmdb.proxies.CIDefinitionAttribute result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AttributeValue_CIDefinitionAttribute_Temp.toString());
		if (identifier != null)
			result = cmdb.proxies.CIDefinitionAttribute.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AttributeValue_CIDefinitionAttribute_Temp
	 * @param attributevalue_cidefinitionattribute_temp
	 */
	public final void setAttributeValue_CIDefinitionAttribute_Temp(cmdb.proxies.CIDefinitionAttribute attributevalue_cidefinitionattribute_temp)
	{
		setAttributeValue_CIDefinitionAttribute_Temp(getContext(), attributevalue_cidefinitionattribute_temp);
	}

	/**
	 * Set value of AttributeValue_CIDefinitionAttribute_Temp
	 * @param context
	 * @param attributevalue_cidefinitionattribute_temp
	 */
	public final void setAttributeValue_CIDefinitionAttribute_Temp(com.mendix.systemwideinterfaces.core.IContext context, cmdb.proxies.CIDefinitionAttribute attributevalue_cidefinitionattribute_temp)
	{
		if (attributevalue_cidefinitionattribute_temp == null)
			getMendixObject().setValue(context, MemberNames.AttributeValue_CIDefinitionAttribute_Temp.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AttributeValue_CIDefinitionAttribute_Temp.toString(), attributevalue_cidefinitionattribute_temp.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return attributeValueMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final cmdb.proxies.AttributeValue that = (cmdb.proxies.AttributeValue) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CMDB.AttributeValue";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
