// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cmdb.proxies;

public class CIPersons_TypeDefault
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject cIPersons_TypeDefaultMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CMDB.CIPersons_TypeDefault";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CIPersons_TypeDefault_CIPersonTypes("CMDB.CIPersons_TypeDefault_CIPersonTypes"),
		CIPersons_TypeDefault_CMDBType("CMDB.CIPersons_TypeDefault_CMDBType"),
		CIPersons_TypeDefault_Organisation("CMDB.CIPersons_TypeDefault_Organisation");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CIPersons_TypeDefault(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CMDB.CIPersons_TypeDefault"));
	}

	protected CIPersons_TypeDefault(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cIPersons_TypeDefaultMendixObject)
	{
		if (cIPersons_TypeDefaultMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("CMDB.CIPersons_TypeDefault", cIPersons_TypeDefaultMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CMDB.CIPersons_TypeDefault");

		this.cIPersons_TypeDefaultMendixObject = cIPersons_TypeDefaultMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CIPersons_TypeDefault.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static cmdb.proxies.CIPersons_TypeDefault initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return cmdb.proxies.CIPersons_TypeDefault.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static cmdb.proxies.CIPersons_TypeDefault initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new cmdb.proxies.CIPersons_TypeDefault(context, mendixObject);
	}

	public static cmdb.proxies.CIPersons_TypeDefault load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return cmdb.proxies.CIPersons_TypeDefault.initialize(context, mendixObject);
	}

	public static java.util.List<cmdb.proxies.CIPersons_TypeDefault> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<cmdb.proxies.CIPersons_TypeDefault> result = new java.util.ArrayList<cmdb.proxies.CIPersons_TypeDefault>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CMDB.CIPersons_TypeDefault" + xpathConstraint))
			result.add(cmdb.proxies.CIPersons_TypeDefault.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CIPersons_TypeDefault_CIPersonTypes
	 */
	public final cmdb.proxies.CIPersonTypes getCIPersons_TypeDefault_CIPersonTypes() throws com.mendix.core.CoreException
	{
		return getCIPersons_TypeDefault_CIPersonTypes(getContext());
	}

	/**
	 * @param context
	 * @return value of CIPersons_TypeDefault_CIPersonTypes
	 */
	public final cmdb.proxies.CIPersonTypes getCIPersons_TypeDefault_CIPersonTypes(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmdb.proxies.CIPersonTypes result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CIPersons_TypeDefault_CIPersonTypes.toString());
		if (identifier != null)
			result = cmdb.proxies.CIPersonTypes.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CIPersons_TypeDefault_CIPersonTypes
	 * @param cipersons_typedefault_cipersontypes
	 */
	public final void setCIPersons_TypeDefault_CIPersonTypes(cmdb.proxies.CIPersonTypes cipersons_typedefault_cipersontypes)
	{
		setCIPersons_TypeDefault_CIPersonTypes(getContext(), cipersons_typedefault_cipersontypes);
	}

	/**
	 * Set value of CIPersons_TypeDefault_CIPersonTypes
	 * @param context
	 * @param cipersons_typedefault_cipersontypes
	 */
	public final void setCIPersons_TypeDefault_CIPersonTypes(com.mendix.systemwideinterfaces.core.IContext context, cmdb.proxies.CIPersonTypes cipersons_typedefault_cipersontypes)
	{
		if (cipersons_typedefault_cipersontypes == null)
			getMendixObject().setValue(context, MemberNames.CIPersons_TypeDefault_CIPersonTypes.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CIPersons_TypeDefault_CIPersonTypes.toString(), cipersons_typedefault_cipersontypes.getMendixObject().getId());
	}

	/**
	 * @return value of CIPersons_TypeDefault_CMDBType
	 */
	public final cmdb.proxies.CMDBType getCIPersons_TypeDefault_CMDBType() throws com.mendix.core.CoreException
	{
		return getCIPersons_TypeDefault_CMDBType(getContext());
	}

	/**
	 * @param context
	 * @return value of CIPersons_TypeDefault_CMDBType
	 */
	public final cmdb.proxies.CMDBType getCIPersons_TypeDefault_CMDBType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmdb.proxies.CMDBType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CIPersons_TypeDefault_CMDBType.toString());
		if (identifier != null)
			result = cmdb.proxies.CMDBType.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CIPersons_TypeDefault_CMDBType
	 * @param cipersons_typedefault_cmdbtype
	 */
	public final void setCIPersons_TypeDefault_CMDBType(cmdb.proxies.CMDBType cipersons_typedefault_cmdbtype)
	{
		setCIPersons_TypeDefault_CMDBType(getContext(), cipersons_typedefault_cmdbtype);
	}

	/**
	 * Set value of CIPersons_TypeDefault_CMDBType
	 * @param context
	 * @param cipersons_typedefault_cmdbtype
	 */
	public final void setCIPersons_TypeDefault_CMDBType(com.mendix.systemwideinterfaces.core.IContext context, cmdb.proxies.CMDBType cipersons_typedefault_cmdbtype)
	{
		if (cipersons_typedefault_cmdbtype == null)
			getMendixObject().setValue(context, MemberNames.CIPersons_TypeDefault_CMDBType.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CIPersons_TypeDefault_CMDBType.toString(), cipersons_typedefault_cmdbtype.getMendixObject().getId());
	}

	/**
	 * @return value of CIPersons_TypeDefault_Organisation
	 */
	public final nap.proxies.Organisation getCIPersons_TypeDefault_Organisation() throws com.mendix.core.CoreException
	{
		return getCIPersons_TypeDefault_Organisation(getContext());
	}

	/**
	 * @param context
	 * @return value of CIPersons_TypeDefault_Organisation
	 */
	public final nap.proxies.Organisation getCIPersons_TypeDefault_Organisation(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		nap.proxies.Organisation result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CIPersons_TypeDefault_Organisation.toString());
		if (identifier != null)
			result = nap.proxies.Organisation.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CIPersons_TypeDefault_Organisation
	 * @param cipersons_typedefault_organisation
	 */
	public final void setCIPersons_TypeDefault_Organisation(nap.proxies.Organisation cipersons_typedefault_organisation)
	{
		setCIPersons_TypeDefault_Organisation(getContext(), cipersons_typedefault_organisation);
	}

	/**
	 * Set value of CIPersons_TypeDefault_Organisation
	 * @param context
	 * @param cipersons_typedefault_organisation
	 */
	public final void setCIPersons_TypeDefault_Organisation(com.mendix.systemwideinterfaces.core.IContext context, nap.proxies.Organisation cipersons_typedefault_organisation)
	{
		if (cipersons_typedefault_organisation == null)
			getMendixObject().setValue(context, MemberNames.CIPersons_TypeDefault_Organisation.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CIPersons_TypeDefault_Organisation.toString(), cipersons_typedefault_organisation.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return cIPersons_TypeDefaultMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final cmdb.proxies.CIPersons_TypeDefault that = (cmdb.proxies.CIPersons_TypeDefault) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CMDB.CIPersons_TypeDefault";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
