// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cmdb.proxies;

public class CMDBType
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject cMDBTypeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CMDB.CMDBType";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Status("Status"),
		ActAsBaseCI("ActAsBaseCI"),
		HasGeneralization("HasGeneralization"),
		VersionDate("VersionDate"),
		CountNumberOfAttributes("CountNumberOfAttributes"),
		CountNumberOfRealtion("CountNumberOfRealtion"),
		CountNumberOfAttributesFoBaseCIType("CountNumberOfAttributesFoBaseCIType"),
		CopyHasGeneralization("CopyHasGeneralization"),
		InstantiateNumberFormat("InstantiateNumberFormat"),
		ImageString("ImageString"),
		Minimum("Minimum"),
		Target("Target"),
		Notes("Notes"),
		CountNumberOfCIs_Total("CountNumberOfCIs_Total"),
		CountNumberOfCIs_Operational("CountNumberOfCIs_Operational"),
		CountNumberOfCIs_Stock("CountNumberOfCIs_Stock"),
		SpareState("SpareState"),
		InterfaceGUID("InterfaceGUID"),
		MTBF("MTBF"),
		PricePerUnit("PricePerUnit"),
		ObsoleteDate("ObsoleteDate"),
		EndOfServiceDate("EndOfServiceDate"),
		EndOfServiceNote("EndOfServiceNote"),
		Level("Level"),
		Version("Version"),
		Description("Description"),
		Manufacturer("Manufacturer"),
		CITypeModel_CMDBModel("CMDB.CITypeModel_CMDBModel"),
		Generalization("CMDB.Generalization"),
		Copy_CMDBType("CMDB.Copy_CMDBType"),
		CMDBType_AlternateCMDBType("CMDB.CMDBType_AlternateCMDBType"),
		CMDBType_SupposedSystem("CMDB.CMDBType_SupposedSystem"),
		CMDBType_DataAccess("CMDB.CMDBType_DataAccess"),
		CMDBType_Category("CMDB.CMDBType_Category"),
		CMDBType_Inventory("CMDB.CMDBType_Inventory");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CMDBType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CMDB.CMDBType"));
	}

	protected CMDBType(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cMDBTypeMendixObject)
	{
		if (cMDBTypeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("CMDB.CMDBType", cMDBTypeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CMDB.CMDBType");

		this.cMDBTypeMendixObject = cMDBTypeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CMDBType.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static cmdb.proxies.CMDBType initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return cmdb.proxies.CMDBType.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static cmdb.proxies.CMDBType initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new cmdb.proxies.CMDBType(context, mendixObject);
	}

	public static cmdb.proxies.CMDBType load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return cmdb.proxies.CMDBType.initialize(context, mendixObject);
	}

	public static java.util.List<cmdb.proxies.CMDBType> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<cmdb.proxies.CMDBType> result = new java.util.ArrayList<cmdb.proxies.CMDBType>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CMDB.CMDBType" + xpathConstraint))
			result.add(cmdb.proxies.CMDBType.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final cmdb.proxies.StatusEnum getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final cmdb.proxies.StatusEnum getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null)
			return null;

		return cmdb.proxies.StatusEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(cmdb.proxies.StatusEnum status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, cmdb.proxies.StatusEnum status)
	{
		if (status != null)
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
	}

	/**
	 * @return value of ActAsBaseCI
	 */
	public final java.lang.Boolean getActAsBaseCI()
	{
		return getActAsBaseCI(getContext());
	}

	/**
	 * @param context
	 * @return value of ActAsBaseCI
	 */
	public final java.lang.Boolean getActAsBaseCI(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ActAsBaseCI.toString());
	}

	/**
	 * Set value of ActAsBaseCI
	 * @param actasbaseci
	 */
	public final void setActAsBaseCI(java.lang.Boolean actasbaseci)
	{
		setActAsBaseCI(getContext(), actasbaseci);
	}

	/**
	 * Set value of ActAsBaseCI
	 * @param context
	 * @param actasbaseci
	 */
	public final void setActAsBaseCI(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean actasbaseci)
	{
		getMendixObject().setValue(context, MemberNames.ActAsBaseCI.toString(), actasbaseci);
	}

	/**
	 * @return value of HasGeneralization
	 */
	public final java.lang.Boolean getHasGeneralization()
	{
		return getHasGeneralization(getContext());
	}

	/**
	 * @param context
	 * @return value of HasGeneralization
	 */
	public final java.lang.Boolean getHasGeneralization(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasGeneralization.toString());
	}

	/**
	 * Set value of HasGeneralization
	 * @param hasgeneralization
	 */
	public final void setHasGeneralization(java.lang.Boolean hasgeneralization)
	{
		setHasGeneralization(getContext(), hasgeneralization);
	}

	/**
	 * Set value of HasGeneralization
	 * @param context
	 * @param hasgeneralization
	 */
	public final void setHasGeneralization(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hasgeneralization)
	{
		getMendixObject().setValue(context, MemberNames.HasGeneralization.toString(), hasgeneralization);
	}

	/**
	 * @return value of VersionDate
	 */
	public final java.util.Date getVersionDate()
	{
		return getVersionDate(getContext());
	}

	/**
	 * @param context
	 * @return value of VersionDate
	 */
	public final java.util.Date getVersionDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.VersionDate.toString());
	}

	/**
	 * Set value of VersionDate
	 * @param versiondate
	 */
	public final void setVersionDate(java.util.Date versiondate)
	{
		setVersionDate(getContext(), versiondate);
	}

	/**
	 * Set value of VersionDate
	 * @param context
	 * @param versiondate
	 */
	public final void setVersionDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date versiondate)
	{
		getMendixObject().setValue(context, MemberNames.VersionDate.toString(), versiondate);
	}

	/**
	 * @return value of CountNumberOfAttributes
	 */
	public final java.lang.Integer getCountNumberOfAttributes()
	{
		return getCountNumberOfAttributes(getContext());
	}

	/**
	 * @param context
	 * @return value of CountNumberOfAttributes
	 */
	public final java.lang.Integer getCountNumberOfAttributes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CountNumberOfAttributes.toString());
	}

	/**
	 * Set value of CountNumberOfAttributes
	 * @param countnumberofattributes
	 */
	public final void setCountNumberOfAttributes(java.lang.Integer countnumberofattributes)
	{
		setCountNumberOfAttributes(getContext(), countnumberofattributes);
	}

	/**
	 * Set value of CountNumberOfAttributes
	 * @param context
	 * @param countnumberofattributes
	 */
	public final void setCountNumberOfAttributes(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer countnumberofattributes)
	{
		getMendixObject().setValue(context, MemberNames.CountNumberOfAttributes.toString(), countnumberofattributes);
	}

	/**
	 * @return value of CountNumberOfRealtion
	 */
	public final java.lang.Integer getCountNumberOfRealtion()
	{
		return getCountNumberOfRealtion(getContext());
	}

	/**
	 * @param context
	 * @return value of CountNumberOfRealtion
	 */
	public final java.lang.Integer getCountNumberOfRealtion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CountNumberOfRealtion.toString());
	}

	/**
	 * Set value of CountNumberOfRealtion
	 * @param countnumberofrealtion
	 */
	public final void setCountNumberOfRealtion(java.lang.Integer countnumberofrealtion)
	{
		setCountNumberOfRealtion(getContext(), countnumberofrealtion);
	}

	/**
	 * Set value of CountNumberOfRealtion
	 * @param context
	 * @param countnumberofrealtion
	 */
	public final void setCountNumberOfRealtion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer countnumberofrealtion)
	{
		getMendixObject().setValue(context, MemberNames.CountNumberOfRealtion.toString(), countnumberofrealtion);
	}

	/**
	 * @return value of CountNumberOfAttributesFoBaseCIType
	 */
	public final java.lang.Integer getCountNumberOfAttributesFoBaseCIType()
	{
		return getCountNumberOfAttributesFoBaseCIType(getContext());
	}

	/**
	 * @param context
	 * @return value of CountNumberOfAttributesFoBaseCIType
	 */
	public final java.lang.Integer getCountNumberOfAttributesFoBaseCIType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CountNumberOfAttributesFoBaseCIType.toString());
	}

	/**
	 * Set value of CountNumberOfAttributesFoBaseCIType
	 * @param countnumberofattributesfobasecitype
	 */
	public final void setCountNumberOfAttributesFoBaseCIType(java.lang.Integer countnumberofattributesfobasecitype)
	{
		setCountNumberOfAttributesFoBaseCIType(getContext(), countnumberofattributesfobasecitype);
	}

	/**
	 * Set value of CountNumberOfAttributesFoBaseCIType
	 * @param context
	 * @param countnumberofattributesfobasecitype
	 */
	public final void setCountNumberOfAttributesFoBaseCIType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer countnumberofattributesfobasecitype)
	{
		getMendixObject().setValue(context, MemberNames.CountNumberOfAttributesFoBaseCIType.toString(), countnumberofattributesfobasecitype);
	}

	/**
	 * @return value of CopyHasGeneralization
	 */
	public final java.lang.Boolean getCopyHasGeneralization()
	{
		return getCopyHasGeneralization(getContext());
	}

	/**
	 * @param context
	 * @return value of CopyHasGeneralization
	 */
	public final java.lang.Boolean getCopyHasGeneralization(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CopyHasGeneralization.toString());
	}

	/**
	 * Set value of CopyHasGeneralization
	 * @param copyhasgeneralization
	 */
	public final void setCopyHasGeneralization(java.lang.Boolean copyhasgeneralization)
	{
		setCopyHasGeneralization(getContext(), copyhasgeneralization);
	}

	/**
	 * Set value of CopyHasGeneralization
	 * @param context
	 * @param copyhasgeneralization
	 */
	public final void setCopyHasGeneralization(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean copyhasgeneralization)
	{
		getMendixObject().setValue(context, MemberNames.CopyHasGeneralization.toString(), copyhasgeneralization);
	}

	/**
	 * @return value of InstantiateNumberFormat
	 */
	public final java.lang.String getInstantiateNumberFormat()
	{
		return getInstantiateNumberFormat(getContext());
	}

	/**
	 * @param context
	 * @return value of InstantiateNumberFormat
	 */
	public final java.lang.String getInstantiateNumberFormat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InstantiateNumberFormat.toString());
	}

	/**
	 * Set value of InstantiateNumberFormat
	 * @param instantiatenumberformat
	 */
	public final void setInstantiateNumberFormat(java.lang.String instantiatenumberformat)
	{
		setInstantiateNumberFormat(getContext(), instantiatenumberformat);
	}

	/**
	 * Set value of InstantiateNumberFormat
	 * @param context
	 * @param instantiatenumberformat
	 */
	public final void setInstantiateNumberFormat(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instantiatenumberformat)
	{
		getMendixObject().setValue(context, MemberNames.InstantiateNumberFormat.toString(), instantiatenumberformat);
	}

	/**
	 * @return value of ImageString
	 */
	public final java.lang.String getImageString()
	{
		return getImageString(getContext());
	}

	/**
	 * @param context
	 * @return value of ImageString
	 */
	public final java.lang.String getImageString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ImageString.toString());
	}

	/**
	 * Set value of ImageString
	 * @param imagestring
	 */
	public final void setImageString(java.lang.String imagestring)
	{
		setImageString(getContext(), imagestring);
	}

	/**
	 * Set value of ImageString
	 * @param context
	 * @param imagestring
	 */
	public final void setImageString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String imagestring)
	{
		getMendixObject().setValue(context, MemberNames.ImageString.toString(), imagestring);
	}

	/**
	 * @return value of Minimum
	 */
	public final java.lang.Integer getMinimum()
	{
		return getMinimum(getContext());
	}

	/**
	 * @param context
	 * @return value of Minimum
	 */
	public final java.lang.Integer getMinimum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Minimum.toString());
	}

	/**
	 * Set value of Minimum
	 * @param minimum
	 */
	public final void setMinimum(java.lang.Integer minimum)
	{
		setMinimum(getContext(), minimum);
	}

	/**
	 * Set value of Minimum
	 * @param context
	 * @param minimum
	 */
	public final void setMinimum(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer minimum)
	{
		getMendixObject().setValue(context, MemberNames.Minimum.toString(), minimum);
	}

	/**
	 * @return value of Target
	 */
	public final java.lang.Integer getTarget()
	{
		return getTarget(getContext());
	}

	/**
	 * @param context
	 * @return value of Target
	 */
	public final java.lang.Integer getTarget(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Target.toString());
	}

	/**
	 * Set value of Target
	 * @param target
	 */
	public final void setTarget(java.lang.Integer target)
	{
		setTarget(getContext(), target);
	}

	/**
	 * Set value of Target
	 * @param context
	 * @param target
	 */
	public final void setTarget(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer target)
	{
		getMendixObject().setValue(context, MemberNames.Target.toString(), target);
	}

	/**
	 * @return value of Notes
	 */
	public final java.lang.String getNotes()
	{
		return getNotes(getContext());
	}

	/**
	 * @param context
	 * @return value of Notes
	 */
	public final java.lang.String getNotes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Notes.toString());
	}

	/**
	 * Set value of Notes
	 * @param notes
	 */
	public final void setNotes(java.lang.String notes)
	{
		setNotes(getContext(), notes);
	}

	/**
	 * Set value of Notes
	 * @param context
	 * @param notes
	 */
	public final void setNotes(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String notes)
	{
		getMendixObject().setValue(context, MemberNames.Notes.toString(), notes);
	}

	/**
	 * @return value of CountNumberOfCIs_Total
	 */
	public final java.lang.Integer getCountNumberOfCIs_Total()
	{
		return getCountNumberOfCIs_Total(getContext());
	}

	/**
	 * @param context
	 * @return value of CountNumberOfCIs_Total
	 */
	public final java.lang.Integer getCountNumberOfCIs_Total(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CountNumberOfCIs_Total.toString());
	}

	/**
	 * Set value of CountNumberOfCIs_Total
	 * @param countnumberofcis_total
	 */
	public final void setCountNumberOfCIs_Total(java.lang.Integer countnumberofcis_total)
	{
		setCountNumberOfCIs_Total(getContext(), countnumberofcis_total);
	}

	/**
	 * Set value of CountNumberOfCIs_Total
	 * @param context
	 * @param countnumberofcis_total
	 */
	public final void setCountNumberOfCIs_Total(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer countnumberofcis_total)
	{
		getMendixObject().setValue(context, MemberNames.CountNumberOfCIs_Total.toString(), countnumberofcis_total);
	}

	/**
	 * @return value of CountNumberOfCIs_Operational
	 */
	public final java.lang.Integer getCountNumberOfCIs_Operational()
	{
		return getCountNumberOfCIs_Operational(getContext());
	}

	/**
	 * @param context
	 * @return value of CountNumberOfCIs_Operational
	 */
	public final java.lang.Integer getCountNumberOfCIs_Operational(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CountNumberOfCIs_Operational.toString());
	}

	/**
	 * Set value of CountNumberOfCIs_Operational
	 * @param countnumberofcis_operational
	 */
	public final void setCountNumberOfCIs_Operational(java.lang.Integer countnumberofcis_operational)
	{
		setCountNumberOfCIs_Operational(getContext(), countnumberofcis_operational);
	}

	/**
	 * Set value of CountNumberOfCIs_Operational
	 * @param context
	 * @param countnumberofcis_operational
	 */
	public final void setCountNumberOfCIs_Operational(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer countnumberofcis_operational)
	{
		getMendixObject().setValue(context, MemberNames.CountNumberOfCIs_Operational.toString(), countnumberofcis_operational);
	}

	/**
	 * @return value of CountNumberOfCIs_Stock
	 */
	public final java.lang.Integer getCountNumberOfCIs_Stock()
	{
		return getCountNumberOfCIs_Stock(getContext());
	}

	/**
	 * @param context
	 * @return value of CountNumberOfCIs_Stock
	 */
	public final java.lang.Integer getCountNumberOfCIs_Stock(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CountNumberOfCIs_Stock.toString());
	}

	/**
	 * Set value of CountNumberOfCIs_Stock
	 * @param countnumberofcis_stock
	 */
	public final void setCountNumberOfCIs_Stock(java.lang.Integer countnumberofcis_stock)
	{
		setCountNumberOfCIs_Stock(getContext(), countnumberofcis_stock);
	}

	/**
	 * Set value of CountNumberOfCIs_Stock
	 * @param context
	 * @param countnumberofcis_stock
	 */
	public final void setCountNumberOfCIs_Stock(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer countnumberofcis_stock)
	{
		getMendixObject().setValue(context, MemberNames.CountNumberOfCIs_Stock.toString(), countnumberofcis_stock);
	}

	/**
	 * Set value of SpareState
	 * @param sparestate
	 */
	public final customlvnl.proxies.LowStockState getSpareState()
	{
		return getSpareState(getContext());
	}

	/**
	 * @param context
	 * @return value of SpareState
	 */
	public final customlvnl.proxies.LowStockState getSpareState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SpareState.toString());
		if (obj == null)
			return null;

		return customlvnl.proxies.LowStockState.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of SpareState
	 * @param sparestate
	 */
	public final void setSpareState(customlvnl.proxies.LowStockState sparestate)
	{
		setSpareState(getContext(), sparestate);
	}

	/**
	 * Set value of SpareState
	 * @param context
	 * @param sparestate
	 */
	public final void setSpareState(com.mendix.systemwideinterfaces.core.IContext context, customlvnl.proxies.LowStockState sparestate)
	{
		if (sparestate != null)
			getMendixObject().setValue(context, MemberNames.SpareState.toString(), sparestate.toString());
		else
			getMendixObject().setValue(context, MemberNames.SpareState.toString(), null);
	}

	/**
	 * @return value of InterfaceGUID
	 */
	public final java.lang.String getInterfaceGUID()
	{
		return getInterfaceGUID(getContext());
	}

	/**
	 * @param context
	 * @return value of InterfaceGUID
	 */
	public final java.lang.String getInterfaceGUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InterfaceGUID.toString());
	}

	/**
	 * Set value of InterfaceGUID
	 * @param interfaceguid
	 */
	public final void setInterfaceGUID(java.lang.String interfaceguid)
	{
		setInterfaceGUID(getContext(), interfaceguid);
	}

	/**
	 * Set value of InterfaceGUID
	 * @param context
	 * @param interfaceguid
	 */
	public final void setInterfaceGUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String interfaceguid)
	{
		getMendixObject().setValue(context, MemberNames.InterfaceGUID.toString(), interfaceguid);
	}

	/**
	 * @return value of MTBF
	 */
	public final java.lang.Integer getMTBF()
	{
		return getMTBF(getContext());
	}

	/**
	 * @param context
	 * @return value of MTBF
	 */
	public final java.lang.Integer getMTBF(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MTBF.toString());
	}

	/**
	 * Set value of MTBF
	 * @param mtbf
	 */
	public final void setMTBF(java.lang.Integer mtbf)
	{
		setMTBF(getContext(), mtbf);
	}

	/**
	 * Set value of MTBF
	 * @param context
	 * @param mtbf
	 */
	public final void setMTBF(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer mtbf)
	{
		getMendixObject().setValue(context, MemberNames.MTBF.toString(), mtbf);
	}

	/**
	 * @return value of PricePerUnit
	 */
	public final java.math.BigDecimal getPricePerUnit()
	{
		return getPricePerUnit(getContext());
	}

	/**
	 * @param context
	 * @return value of PricePerUnit
	 */
	public final java.math.BigDecimal getPricePerUnit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.PricePerUnit.toString());
	}

	/**
	 * Set value of PricePerUnit
	 * @param priceperunit
	 */
	public final void setPricePerUnit(java.math.BigDecimal priceperunit)
	{
		setPricePerUnit(getContext(), priceperunit);
	}

	/**
	 * Set value of PricePerUnit
	 * @param context
	 * @param priceperunit
	 */
	public final void setPricePerUnit(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal priceperunit)
	{
		getMendixObject().setValue(context, MemberNames.PricePerUnit.toString(), priceperunit);
	}

	/**
	 * @return value of ObsoleteDate
	 */
	public final java.util.Date getObsoleteDate()
	{
		return getObsoleteDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ObsoleteDate
	 */
	public final java.util.Date getObsoleteDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ObsoleteDate.toString());
	}

	/**
	 * Set value of ObsoleteDate
	 * @param obsoletedate
	 */
	public final void setObsoleteDate(java.util.Date obsoletedate)
	{
		setObsoleteDate(getContext(), obsoletedate);
	}

	/**
	 * Set value of ObsoleteDate
	 * @param context
	 * @param obsoletedate
	 */
	public final void setObsoleteDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date obsoletedate)
	{
		getMendixObject().setValue(context, MemberNames.ObsoleteDate.toString(), obsoletedate);
	}

	/**
	 * @return value of EndOfServiceDate
	 */
	public final java.util.Date getEndOfServiceDate()
	{
		return getEndOfServiceDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EndOfServiceDate
	 */
	public final java.util.Date getEndOfServiceDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndOfServiceDate.toString());
	}

	/**
	 * Set value of EndOfServiceDate
	 * @param endofservicedate
	 */
	public final void setEndOfServiceDate(java.util.Date endofservicedate)
	{
		setEndOfServiceDate(getContext(), endofservicedate);
	}

	/**
	 * Set value of EndOfServiceDate
	 * @param context
	 * @param endofservicedate
	 */
	public final void setEndOfServiceDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date endofservicedate)
	{
		getMendixObject().setValue(context, MemberNames.EndOfServiceDate.toString(), endofservicedate);
	}

	/**
	 * @return value of EndOfServiceNote
	 */
	public final java.lang.String getEndOfServiceNote()
	{
		return getEndOfServiceNote(getContext());
	}

	/**
	 * @param context
	 * @return value of EndOfServiceNote
	 */
	public final java.lang.String getEndOfServiceNote(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EndOfServiceNote.toString());
	}

	/**
	 * Set value of EndOfServiceNote
	 * @param endofservicenote
	 */
	public final void setEndOfServiceNote(java.lang.String endofservicenote)
	{
		setEndOfServiceNote(getContext(), endofservicenote);
	}

	/**
	 * Set value of EndOfServiceNote
	 * @param context
	 * @param endofservicenote
	 */
	public final void setEndOfServiceNote(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String endofservicenote)
	{
		getMendixObject().setValue(context, MemberNames.EndOfServiceNote.toString(), endofservicenote);
	}

	/**
	 * Set value of Level
	 * @param level
	 */
	public final customlvnl.proxies.CI_Level getLevel()
	{
		return getLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of Level
	 */
	public final customlvnl.proxies.CI_Level getLevel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Level.toString());
		if (obj == null)
			return null;

		return customlvnl.proxies.CI_Level.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Level
	 * @param level
	 */
	public final void setLevel(customlvnl.proxies.CI_Level level)
	{
		setLevel(getContext(), level);
	}

	/**
	 * Set value of Level
	 * @param context
	 * @param level
	 */
	public final void setLevel(com.mendix.systemwideinterfaces.core.IContext context, customlvnl.proxies.CI_Level level)
	{
		if (level != null)
			getMendixObject().setValue(context, MemberNames.Level.toString(), level.toString());
		else
			getMendixObject().setValue(context, MemberNames.Level.toString(), null);
	}

	/**
	 * @return value of Version
	 */
	public final java.lang.String getVersion()
	{
		return getVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of Version
	 */
	public final java.lang.String getVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Version.toString());
	}

	/**
	 * Set value of Version
	 * @param version
	 */
	public final void setVersion(java.lang.String version)
	{
		setVersion(getContext(), version);
	}

	/**
	 * Set value of Version
	 * @param context
	 * @param version
	 */
	public final void setVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String version)
	{
		getMendixObject().setValue(context, MemberNames.Version.toString(), version);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Manufacturer
	 */
	public final java.lang.String getManufacturer()
	{
		return getManufacturer(getContext());
	}

	/**
	 * @param context
	 * @return value of Manufacturer
	 */
	public final java.lang.String getManufacturer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Manufacturer.toString());
	}

	/**
	 * Set value of Manufacturer
	 * @param manufacturer
	 */
	public final void setManufacturer(java.lang.String manufacturer)
	{
		setManufacturer(getContext(), manufacturer);
	}

	/**
	 * Set value of Manufacturer
	 * @param context
	 * @param manufacturer
	 */
	public final void setManufacturer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String manufacturer)
	{
		getMendixObject().setValue(context, MemberNames.Manufacturer.toString(), manufacturer);
	}

	/**
	 * @return value of CITypeModel_CMDBModel
	 */
	public final cmdb.proxies.CMDBModel getCITypeModel_CMDBModel() throws com.mendix.core.CoreException
	{
		return getCITypeModel_CMDBModel(getContext());
	}

	/**
	 * @param context
	 * @return value of CITypeModel_CMDBModel
	 */
	public final cmdb.proxies.CMDBModel getCITypeModel_CMDBModel(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmdb.proxies.CMDBModel result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CITypeModel_CMDBModel.toString());
		if (identifier != null)
			result = cmdb.proxies.CMDBModel.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CITypeModel_CMDBModel
	 * @param citypemodel_cmdbmodel
	 */
	public final void setCITypeModel_CMDBModel(cmdb.proxies.CMDBModel citypemodel_cmdbmodel)
	{
		setCITypeModel_CMDBModel(getContext(), citypemodel_cmdbmodel);
	}

	/**
	 * Set value of CITypeModel_CMDBModel
	 * @param context
	 * @param citypemodel_cmdbmodel
	 */
	public final void setCITypeModel_CMDBModel(com.mendix.systemwideinterfaces.core.IContext context, cmdb.proxies.CMDBModel citypemodel_cmdbmodel)
	{
		if (citypemodel_cmdbmodel == null)
			getMendixObject().setValue(context, MemberNames.CITypeModel_CMDBModel.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CITypeModel_CMDBModel.toString(), citypemodel_cmdbmodel.getMendixObject().getId());
	}

	/**
	 * @return value of Generalization
	 */
	public final cmdb.proxies.CMDBType getGeneralization() throws com.mendix.core.CoreException
	{
		return getGeneralization(getContext());
	}

	/**
	 * @param context
	 * @return value of Generalization
	 */
	public final cmdb.proxies.CMDBType getGeneralization(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmdb.proxies.CMDBType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Generalization.toString());
		if (identifier != null)
			result = cmdb.proxies.CMDBType.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Generalization
	 * @param generalization
	 */
	public final void setGeneralization(cmdb.proxies.CMDBType generalization)
	{
		setGeneralization(getContext(), generalization);
	}

	/**
	 * Set value of Generalization
	 * @param context
	 * @param generalization
	 */
	public final void setGeneralization(com.mendix.systemwideinterfaces.core.IContext context, cmdb.proxies.CMDBType generalization)
	{
		if (generalization == null)
			getMendixObject().setValue(context, MemberNames.Generalization.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Generalization.toString(), generalization.getMendixObject().getId());
	}

	/**
	 * @return value of Copy_CMDBType
	 */
	public final cmdb.proxies.CMDBType getCopy_CMDBType() throws com.mendix.core.CoreException
	{
		return getCopy_CMDBType(getContext());
	}

	/**
	 * @param context
	 * @return value of Copy_CMDBType
	 */
	public final cmdb.proxies.CMDBType getCopy_CMDBType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmdb.proxies.CMDBType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Copy_CMDBType.toString());
		if (identifier != null)
			result = cmdb.proxies.CMDBType.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Copy_CMDBType
	 * @param copy_cmdbtype
	 */
	public final void setCopy_CMDBType(cmdb.proxies.CMDBType copy_cmdbtype)
	{
		setCopy_CMDBType(getContext(), copy_cmdbtype);
	}

	/**
	 * Set value of Copy_CMDBType
	 * @param context
	 * @param copy_cmdbtype
	 */
	public final void setCopy_CMDBType(com.mendix.systemwideinterfaces.core.IContext context, cmdb.proxies.CMDBType copy_cmdbtype)
	{
		if (copy_cmdbtype == null)
			getMendixObject().setValue(context, MemberNames.Copy_CMDBType.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Copy_CMDBType.toString(), copy_cmdbtype.getMendixObject().getId());
	}

	/**
	 * @return value of CMDBType_AlternateCMDBType
	 */
	public final cmdb.proxies.CMDBType getCMDBType_AlternateCMDBType() throws com.mendix.core.CoreException
	{
		return getCMDBType_AlternateCMDBType(getContext());
	}

	/**
	 * @param context
	 * @return value of CMDBType_AlternateCMDBType
	 */
	public final cmdb.proxies.CMDBType getCMDBType_AlternateCMDBType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmdb.proxies.CMDBType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CMDBType_AlternateCMDBType.toString());
		if (identifier != null)
			result = cmdb.proxies.CMDBType.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CMDBType_AlternateCMDBType
	 * @param cmdbtype_alternatecmdbtype
	 */
	public final void setCMDBType_AlternateCMDBType(cmdb.proxies.CMDBType cmdbtype_alternatecmdbtype)
	{
		setCMDBType_AlternateCMDBType(getContext(), cmdbtype_alternatecmdbtype);
	}

	/**
	 * Set value of CMDBType_AlternateCMDBType
	 * @param context
	 * @param cmdbtype_alternatecmdbtype
	 */
	public final void setCMDBType_AlternateCMDBType(com.mendix.systemwideinterfaces.core.IContext context, cmdb.proxies.CMDBType cmdbtype_alternatecmdbtype)
	{
		if (cmdbtype_alternatecmdbtype == null)
			getMendixObject().setValue(context, MemberNames.CMDBType_AlternateCMDBType.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CMDBType_AlternateCMDBType.toString(), cmdbtype_alternatecmdbtype.getMendixObject().getId());
	}

	/**
	 * @return value of CMDBType_SupposedSystem
	 */
	public final java.util.List<cmdb.proxies.ConfigurationItem> getCMDBType_SupposedSystem() throws com.mendix.core.CoreException
	{
		return getCMDBType_SupposedSystem(getContext());
	}

	/**
	 * @param context
	 * @return value of CMDBType_SupposedSystem
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<cmdb.proxies.ConfigurationItem> getCMDBType_SupposedSystem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<cmdb.proxies.ConfigurationItem> result = new java.util.ArrayList<cmdb.proxies.ConfigurationItem>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.CMDBType_SupposedSystem.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(cmdb.proxies.ConfigurationItem.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of CMDBType_SupposedSystem
	 * @param cmdbtype_supposedsystem
	 */
	public final void setCMDBType_SupposedSystem(java.util.List<cmdb.proxies.ConfigurationItem> cmdbtype_supposedsystem)
	{
		setCMDBType_SupposedSystem(getContext(), cmdbtype_supposedsystem);
	}

	/**
	 * Set value of CMDBType_SupposedSystem
	 * @param context
	 * @param cmdbtype_supposedsystem
	 */
	public final void setCMDBType_SupposedSystem(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<cmdb.proxies.ConfigurationItem> cmdbtype_supposedsystem)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (cmdb.proxies.ConfigurationItem proxyObject : cmdbtype_supposedsystem)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.CMDBType_SupposedSystem.toString(), identifiers);
	}

	/**
	 * @return value of CMDBType_DataAccess
	 */
	public final java.util.List<da.proxies.Label> getCMDBType_DataAccess() throws com.mendix.core.CoreException
	{
		return getCMDBType_DataAccess(getContext());
	}

	/**
	 * @param context
	 * @return value of CMDBType_DataAccess
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<da.proxies.Label> getCMDBType_DataAccess(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<da.proxies.Label> result = new java.util.ArrayList<da.proxies.Label>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.CMDBType_DataAccess.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(da.proxies.Label.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of CMDBType_DataAccess
	 * @param cmdbtype_dataaccess
	 */
	public final void setCMDBType_DataAccess(java.util.List<da.proxies.Label> cmdbtype_dataaccess)
	{
		setCMDBType_DataAccess(getContext(), cmdbtype_dataaccess);
	}

	/**
	 * Set value of CMDBType_DataAccess
	 * @param context
	 * @param cmdbtype_dataaccess
	 */
	public final void setCMDBType_DataAccess(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<da.proxies.Label> cmdbtype_dataaccess)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (da.proxies.Label proxyObject : cmdbtype_dataaccess)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.CMDBType_DataAccess.toString(), identifiers);
	}

	/**
	 * @return value of CMDBType_Category
	 */
	public final categories_cmdb.proxies.Category getCMDBType_Category() throws com.mendix.core.CoreException
	{
		return getCMDBType_Category(getContext());
	}

	/**
	 * @param context
	 * @return value of CMDBType_Category
	 */
	public final categories_cmdb.proxies.Category getCMDBType_Category(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		categories_cmdb.proxies.Category result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CMDBType_Category.toString());
		if (identifier != null)
			result = categories_cmdb.proxies.Category.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CMDBType_Category
	 * @param cmdbtype_category
	 */
	public final void setCMDBType_Category(categories_cmdb.proxies.Category cmdbtype_category)
	{
		setCMDBType_Category(getContext(), cmdbtype_category);
	}

	/**
	 * Set value of CMDBType_Category
	 * @param context
	 * @param cmdbtype_category
	 */
	public final void setCMDBType_Category(com.mendix.systemwideinterfaces.core.IContext context, categories_cmdb.proxies.Category cmdbtype_category)
	{
		if (cmdbtype_category == null)
			getMendixObject().setValue(context, MemberNames.CMDBType_Category.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CMDBType_Category.toString(), cmdbtype_category.getMendixObject().getId());
	}

	/**
	 * @return value of CMDBType_Inventory
	 */
	public final customlvnl.proxies.Inventory getCMDBType_Inventory() throws com.mendix.core.CoreException
	{
		return getCMDBType_Inventory(getContext());
	}

	/**
	 * @param context
	 * @return value of CMDBType_Inventory
	 */
	public final customlvnl.proxies.Inventory getCMDBType_Inventory(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		customlvnl.proxies.Inventory result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CMDBType_Inventory.toString());
		if (identifier != null)
			result = customlvnl.proxies.Inventory.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CMDBType_Inventory
	 * @param cmdbtype_inventory
	 */
	public final void setCMDBType_Inventory(customlvnl.proxies.Inventory cmdbtype_inventory)
	{
		setCMDBType_Inventory(getContext(), cmdbtype_inventory);
	}

	/**
	 * Set value of CMDBType_Inventory
	 * @param context
	 * @param cmdbtype_inventory
	 */
	public final void setCMDBType_Inventory(com.mendix.systemwideinterfaces.core.IContext context, customlvnl.proxies.Inventory cmdbtype_inventory)
	{
		if (cmdbtype_inventory == null)
			getMendixObject().setValue(context, MemberNames.CMDBType_Inventory.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CMDBType_Inventory.toString(), cmdbtype_inventory.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return cMDBTypeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final cmdb.proxies.CMDBType that = (cmdb.proxies.CMDBType) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CMDB.CMDBType";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
