// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cmdb.proxies;

public class CMDBAttachment extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CMDB.CMDBAttachment";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AttachmentName("AttachmentName"),
		AttachmentType("AttachmentType"),
		AttachmentSize("AttachmentSize"),
		InterfaceGUID("InterfaceGUID"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		CMDBAttachment_ConfigurationItem("CMDB.CMDBAttachment_ConfigurationItem");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CMDBAttachment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CMDB.CMDBAttachment"));
	}

	protected CMDBAttachment(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cMDBAttachmentMendixObject)
	{
		super(context, cMDBAttachmentMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("CMDB.CMDBAttachment", cMDBAttachmentMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CMDB.CMDBAttachment");
	}

	/**
	 * @deprecated Use 'CMDBAttachment.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static cmdb.proxies.CMDBAttachment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return cmdb.proxies.CMDBAttachment.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static cmdb.proxies.CMDBAttachment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new cmdb.proxies.CMDBAttachment(context, mendixObject);
	}

	public static cmdb.proxies.CMDBAttachment load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return cmdb.proxies.CMDBAttachment.initialize(context, mendixObject);
	}

	public static java.util.List<cmdb.proxies.CMDBAttachment> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<cmdb.proxies.CMDBAttachment> result = new java.util.ArrayList<cmdb.proxies.CMDBAttachment>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CMDB.CMDBAttachment" + xpathConstraint))
			result.add(cmdb.proxies.CMDBAttachment.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of AttachmentName
	 */
	public final java.lang.String getAttachmentName()
	{
		return getAttachmentName(getContext());
	}

	/**
	 * @param context
	 * @return value of AttachmentName
	 */
	public final java.lang.String getAttachmentName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AttachmentName.toString());
	}

	/**
	 * Set value of AttachmentName
	 * @param attachmentname
	 */
	public final void setAttachmentName(java.lang.String attachmentname)
	{
		setAttachmentName(getContext(), attachmentname);
	}

	/**
	 * Set value of AttachmentName
	 * @param context
	 * @param attachmentname
	 */
	public final void setAttachmentName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attachmentname)
	{
		getMendixObject().setValue(context, MemberNames.AttachmentName.toString(), attachmentname);
	}

	/**
	 * @return value of AttachmentType
	 */
	public final java.lang.String getAttachmentType()
	{
		return getAttachmentType(getContext());
	}

	/**
	 * @param context
	 * @return value of AttachmentType
	 */
	public final java.lang.String getAttachmentType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AttachmentType.toString());
	}

	/**
	 * Set value of AttachmentType
	 * @param attachmenttype
	 */
	public final void setAttachmentType(java.lang.String attachmenttype)
	{
		setAttachmentType(getContext(), attachmenttype);
	}

	/**
	 * Set value of AttachmentType
	 * @param context
	 * @param attachmenttype
	 */
	public final void setAttachmentType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attachmenttype)
	{
		getMendixObject().setValue(context, MemberNames.AttachmentType.toString(), attachmenttype);
	}

	/**
	 * @return value of AttachmentSize
	 */
	public final java.lang.Integer getAttachmentSize()
	{
		return getAttachmentSize(getContext());
	}

	/**
	 * @param context
	 * @return value of AttachmentSize
	 */
	public final java.lang.Integer getAttachmentSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.AttachmentSize.toString());
	}

	/**
	 * Set value of AttachmentSize
	 * @param attachmentsize
	 */
	public final void setAttachmentSize(java.lang.Integer attachmentsize)
	{
		setAttachmentSize(getContext(), attachmentsize);
	}

	/**
	 * Set value of AttachmentSize
	 * @param context
	 * @param attachmentsize
	 */
	public final void setAttachmentSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer attachmentsize)
	{
		getMendixObject().setValue(context, MemberNames.AttachmentSize.toString(), attachmentsize);
	}

	/**
	 * @return value of InterfaceGUID
	 */
	public final java.lang.String getInterfaceGUID()
	{
		return getInterfaceGUID(getContext());
	}

	/**
	 * @param context
	 * @return value of InterfaceGUID
	 */
	public final java.lang.String getInterfaceGUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InterfaceGUID.toString());
	}

	/**
	 * Set value of InterfaceGUID
	 * @param interfaceguid
	 */
	public final void setInterfaceGUID(java.lang.String interfaceguid)
	{
		setInterfaceGUID(getContext(), interfaceguid);
	}

	/**
	 * Set value of InterfaceGUID
	 * @param context
	 * @param interfaceguid
	 */
	public final void setInterfaceGUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String interfaceguid)
	{
		getMendixObject().setValue(context, MemberNames.InterfaceGUID.toString(), interfaceguid);
	}

	/**
	 * @return value of CMDBAttachment_ConfigurationItem
	 */
	public final cmdb.proxies.ConfigurationItem getCMDBAttachment_ConfigurationItem() throws com.mendix.core.CoreException
	{
		return getCMDBAttachment_ConfigurationItem(getContext());
	}

	/**
	 * @param context
	 * @return value of CMDBAttachment_ConfigurationItem
	 */
	public final cmdb.proxies.ConfigurationItem getCMDBAttachment_ConfigurationItem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmdb.proxies.ConfigurationItem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CMDBAttachment_ConfigurationItem.toString());
		if (identifier != null)
			result = cmdb.proxies.ConfigurationItem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CMDBAttachment_ConfigurationItem
	 * @param cmdbattachment_configurationitem
	 */
	public final void setCMDBAttachment_ConfigurationItem(cmdb.proxies.ConfigurationItem cmdbattachment_configurationitem)
	{
		setCMDBAttachment_ConfigurationItem(getContext(), cmdbattachment_configurationitem);
	}

	/**
	 * Set value of CMDBAttachment_ConfigurationItem
	 * @param context
	 * @param cmdbattachment_configurationitem
	 */
	public final void setCMDBAttachment_ConfigurationItem(com.mendix.systemwideinterfaces.core.IContext context, cmdb.proxies.ConfigurationItem cmdbattachment_configurationitem)
	{
		if (cmdbattachment_configurationitem == null)
			getMendixObject().setValue(context, MemberNames.CMDBAttachment_ConfigurationItem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CMDBAttachment_ConfigurationItem.toString(), cmdbattachment_configurationitem.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final cmdb.proxies.CMDBAttachment that = (cmdb.proxies.CMDBAttachment) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CMDB.CMDBAttachment";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
