// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cmdb.proxies;

public enum Confidentiality
{
	N_A(new java.lang.String[][] { new java.lang.String[] { "en_US", "N/A" }, new java.lang.String[] { "nl_NL", "N.v.t." }, new java.lang.String[] { "de_DE", "entfällt" } }),
	Low(new java.lang.String[][] { new java.lang.String[] { "en_US", "Low" }, new java.lang.String[] { "nl_NL", "Laag" }, new java.lang.String[] { "de_DE", "Niedrig" } }),
	Moderate(new java.lang.String[][] { new java.lang.String[] { "en_US", "Moderate" }, new java.lang.String[] { "nl_NL", "Matig" }, new java.lang.String[] { "de_DE", "Moderat" } }),
	High(new java.lang.String[][] { new java.lang.String[] { "en_US", "High" }, new java.lang.String[] { "nl_NL", "Hoog" }, new java.lang.String[] { "de_DE", "Hoch" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Confidentiality(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
