// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package slm.actions;

import java.util.Iterator;
import statetransition.proxies.State;
import cmdb.proxies.CMDBType;
import cmdb.proxies.ConfigurationItem;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import communitycommons.XPath;

public class GetContractAvailableCIsCount extends CustomJavaAction<java.lang.Long>
{
	private IMendixObject __ContractParameter1;
	private slm.proxies.Contract ContractParameter1;

	public GetContractAvailableCIsCount(IContext context, IMendixObject ContractParameter1)
	{
		super(context);
		this.__ContractParameter1 = ContractParameter1;
	}

	@Override
	public java.lang.Long executeAction() throws Exception
	{
		this.ContractParameter1 = __ContractParameter1 == null ? null : slm.proxies.Contract.initialize(getContext(), __ContractParameter1);

		// BEGIN USER CODE
		XPath<ConfigurationItem> configurationItemXPath = XPath.create(Core.createSystemContext(), ConfigurationItem.class);
		//Exclude all ConfigurationItem entries which are already related to the contract (from the user context)
		for(Iterator<ConfigurationItem> contractParameter1Iterator = ContractParameter1.getContract_ConfigurationItem().iterator(); contractParameter1Iterator.hasNext(); ){
			ConfigurationItem configurationItem = contractParameter1Iterator.next();
			configurationItemXPath.notEq(XPath.ID,configurationItem.getMendixObject().getId().toLong());
		}
		//Add search field content
		if(ContractParameter1.getSearchAvailableCIName() != null && !ContractParameter1.getSearchAvailableCIName().equals("")){
			configurationItemXPath.contains(ConfigurationItem.MemberNames.Name, ContractParameter1.getSearchAvailableCIName());
		}
		if(ContractParameter1.getSearchAvailableCITypeName() != null && !ContractParameter1.getSearchAvailableCITypeName().equals("")){
			configurationItemXPath.subconstraint(ConfigurationItem.MemberNames.ConfigurationItem_CMDBType, CMDBType.entityName).eq(CMDBType.MemberNames.Name, ContractParameter1.getSearchAvailableCITypeName()).close();
		}
		if(ContractParameter1.getSearchAvailableCIState() != null && !ContractParameter1.getSearchAvailableCIState().equals("")){
			configurationItemXPath.subconstraint(ConfigurationItem.MemberNames.ConfigurationItem_States, State.entityName).eq(State.MemberNames.Name, ContractParameter1.getSearchAvailableCIState()).close();
		}
		return configurationItemXPath.count();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetContractAvailableCIsCount";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
