// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package apmagent.actions;

import java.net.URLEncoder;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class EncodeURL extends CustomJavaAction<java.lang.String>
{
	private java.lang.String InputString;

	public EncodeURL(IContext context, java.lang.String InputString)
	{
		super(context);
		this.InputString = InputString;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (InputString==null) return "";
		return URLEncoder.encode(InputString, "UTF-8").replace("+", "%20");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "EncodeURL";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
