// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package apmagent.actions;

import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class ExecuteJDBCQueryToMetricList extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String StatementPar;
	private java.lang.String JDBCURL;
	private java.lang.String JDBCUser;
	private java.lang.String JDBCPassword;
	private java.lang.Long JDBCQueryTimeOut;
	private java.lang.Long JDBCQueryMaxRows;
	private java.lang.Boolean QueryUseFirstColumnInNamePar;
	private java.lang.String LicenseParameter;

	public ExecuteJDBCQueryToMetricList(IContext context, java.lang.String StatementPar, java.lang.String JDBCURL, java.lang.String JDBCUser, java.lang.String JDBCPassword, java.lang.Long JDBCQueryTimeOut, java.lang.Long JDBCQueryMaxRows, java.lang.Boolean QueryUseFirstColumnInNamePar, java.lang.String LicenseParameter)
	{
		super(context);
		this.StatementPar = StatementPar;
		this.JDBCURL = JDBCURL;
		this.JDBCUser = JDBCUser;
		this.JDBCPassword = JDBCPassword;
		this.JDBCQueryTimeOut = JDBCQueryTimeOut;
		this.JDBCQueryMaxRows = JDBCQueryMaxRows;
		this.QueryUseFirstColumnInNamePar = QueryUseFirstColumnInNamePar;
		this.LicenseParameter = LicenseParameter;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		return nl.mansystems.query.JDBCConnector.executeJDBCQueryToMetricList(LicenseParameter, this.getContext(), StatementPar, QueryUseFirstColumnInNamePar, JDBCURL, JDBCUser, JDBCPassword, JDBCQueryMaxRows, JDBCQueryTimeOut);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "ExecuteJDBCQueryToMetricList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
