// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package apmagent.actions;

import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class StartPrivateScheduledEvent extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String LicenseParameter;
	private java.lang.String NameParameter;
	private java.lang.String MicroflowName;
	private java.lang.Long FrequencyParameter;
	private java.lang.Long OffsetParameter;
	private IMendixObject AnyObjectParameter;

	public StartPrivateScheduledEvent(IContext context, java.lang.String LicenseParameter, java.lang.String NameParameter, java.lang.String MicroflowName, java.lang.Long FrequencyParameter, java.lang.Long OffsetParameter, IMendixObject AnyObjectParameter)
	{
		super(context);
		this.LicenseParameter = LicenseParameter;
		this.NameParameter = NameParameter;
		this.MicroflowName = MicroflowName;
		this.FrequencyParameter = FrequencyParameter;
		this.OffsetParameter = OffsetParameter;
		this.AnyObjectParameter = AnyObjectParameter;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		return nl.mansystems.shared.SharedFunctions.startScheduledEvent(LicenseParameter, NameParameter, MicroflowName, AnyObjectParameter, FrequencyParameter, OffsetParameter);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "StartPrivateScheduledEvent";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
