// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package apmagent.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class StopLog4jLogging extends CustomJavaAction<java.lang.Boolean>
{
	public StopLog4jLogging(IContext context)
	{
		super(context);
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			nl.mansystems.javaconsole.Log4JInterceptor.stop();
		} catch(NoClassDefFoundError e) {
			Core.getLogger("Log4JLogging").debug("On stop: Log4j not used",e);
		}
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "StopLog4jLogging";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
