// This file was generated by Mendix Modeler 7.7.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package requestanalysis.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the RequestAnalysis module
	public static void answerAnalysis(IContext context, requestanalysis.proxies.Analysis_Instance _analysis_Instance)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Analysis_Instance", _analysis_Instance == null ? null : _analysis_Instance.getMendixObject());
			Core.execute(context, "RequestAnalysis.AnswerAnalysis", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void answerQuestion(IContext context, requestanalysis.proxies.AnalysisQ_I _analysistQuestions_Instance)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("AnalysistQuestions_Instance", _analysistQuestions_Instance == null ? null : _analysistQuestions_Instance.getMendixObject());
			Core.execute(context, "RequestAnalysis.AnswerQuestion", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void apply_Action_Analysis(IContext context, requestanalysis.proxies.Analysis _analysis)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Analysis", _analysis == null ? null : _analysis.getMendixObject());
			Core.execute(context, "RequestAnalysis.Apply_Action_Analysis", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean bC_Analysis(IContext context, requestanalysis.proxies.Analysis _analysis)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Analysis", _analysis == null ? null : _analysis.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "RequestAnalysis.BC_Analysis", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void copyRequestAnalysis(IContext context, requestanalysis.proxies.Analysis _oldAnalysis)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("OldAnalysis", _oldAnalysis == null ? null : _oldAnalysis.getMendixObject());
			Core.execute(context, "RequestAnalysis.CopyRequestAnalysis", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void copyRequestAnalysisList(IContext context, java.util.List<requestanalysis.proxies.Analysis> _analysisList)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.ArrayList<IMendixObject> listparam_analysisList = null;
			if (_analysisList != null)
			{
				listparam_analysisList = new java.util.ArrayList<IMendixObject>();
				for (requestanalysis.proxies.Analysis obj : _analysisList)
					listparam_analysisList.add(obj.getMendixObject());
			}
			params.put("AnalysisList", listparam_analysisList);
			Core.execute(context, "RequestAnalysis.CopyRequestAnalysisList", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void createAnswerForAnalysis(IContext context, requestanalysis.proxies.Analysis _analysis)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Analysis", _analysis == null ? null : _analysis.getMendixObject());
			Core.execute(context, "RequestAnalysis.CreateAnswerForAnalysis", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	/**
	 * 3430
	 * Used If...Else Statement because string and getCaption cannot handle empty values.
	 */
	public static boolean parseAnswer(IContext context, requestanalysis.proxies.Answer _answer)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Answer", _answer == null ? null : _answer.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "RequestAnalysis.ParseAnswer", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void save_Action_Analysis(IContext context, requestanalysis.proxies.Analysis _analysis)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Analysis", _analysis == null ? null : _analysis.getMendixObject());
			Core.execute(context, "RequestAnalysis.Save_Action_Analysis", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}