// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package apmagent.proxies;

public enum MetricTypeEnum
{
	_Float(new java.lang.String[][] { new java.lang.String[] { "en_US", "Float" } }),
	_String(new java.lang.String[][] { new java.lang.String[] { "en_US", "String" } }),
	_Date(new java.lang.String[][] { new java.lang.String[] { "en_US", "Date" } }),
	_Boolean(new java.lang.String[][] { new java.lang.String[] { "en_US", "Boolean" } }),
	_Long(new java.lang.String[][] { new java.lang.String[] { "en_US", "Long" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private MetricTypeEnum(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
