// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package apmagent.proxies;

public class MetricTrigger
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject metricTriggerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "APMAgent.MetricTrigger";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Description("Description"),
		Enabled("Enabled"),
		CheckExpression("CheckExpression"),
		LastFired("LastFired"),
		CheckIteration("CheckIteration"),
		ActionRunMicroflow("ActionRunMicroflow"),
		ActionRunMicroflowName("ActionRunMicroflowName"),
		ActionTrapMessage("ActionTrapMessage"),
		ActionTrapMessageText("ActionTrapMessageText"),
		ActionHeapDump("ActionHeapDump"),
		TriggerContinuation("TriggerContinuation"),
		TriggerContinuationDelay("TriggerContinuationDelay"),
		TriggerContinuationPaused("TriggerContinuationPaused"),
		MetricTrigger_MetricCollectorItem("APMAgent.MetricTrigger_MetricCollectorItem");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MetricTrigger(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "APMAgent.MetricTrigger"));
	}

	protected MetricTrigger(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject metricTriggerMendixObject)
	{
		if (metricTriggerMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("APMAgent.MetricTrigger", metricTriggerMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a APMAgent.MetricTrigger");

		this.metricTriggerMendixObject = metricTriggerMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MetricTrigger.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static apmagent.proxies.MetricTrigger initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return apmagent.proxies.MetricTrigger.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static apmagent.proxies.MetricTrigger initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new apmagent.proxies.MetricTrigger(context, mendixObject);
	}

	public static apmagent.proxies.MetricTrigger load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return apmagent.proxies.MetricTrigger.initialize(context, mendixObject);
	}

	public static java.util.List<apmagent.proxies.MetricTrigger> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<apmagent.proxies.MetricTrigger> result = new java.util.ArrayList<apmagent.proxies.MetricTrigger>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//APMAgent.MetricTrigger" + xpathConstraint))
			result.add(apmagent.proxies.MetricTrigger.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Enabled
	 */
	public final java.lang.Boolean getEnabled()
	{
		return getEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of Enabled
	 */
	public final java.lang.Boolean getEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Enabled.toString());
	}

	/**
	 * Set value of Enabled
	 * @param enabled
	 */
	public final void setEnabled(java.lang.Boolean enabled)
	{
		setEnabled(getContext(), enabled);
	}

	/**
	 * Set value of Enabled
	 * @param context
	 * @param enabled
	 */
	public final void setEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean enabled)
	{
		getMendixObject().setValue(context, MemberNames.Enabled.toString(), enabled);
	}

	/**
	 * @return value of CheckExpression
	 */
	public final java.lang.String getCheckExpression()
	{
		return getCheckExpression(getContext());
	}

	/**
	 * @param context
	 * @return value of CheckExpression
	 */
	public final java.lang.String getCheckExpression(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CheckExpression.toString());
	}

	/**
	 * Set value of CheckExpression
	 * @param checkexpression
	 */
	public final void setCheckExpression(java.lang.String checkexpression)
	{
		setCheckExpression(getContext(), checkexpression);
	}

	/**
	 * Set value of CheckExpression
	 * @param context
	 * @param checkexpression
	 */
	public final void setCheckExpression(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String checkexpression)
	{
		getMendixObject().setValue(context, MemberNames.CheckExpression.toString(), checkexpression);
	}

	/**
	 * @return value of LastFired
	 */
	public final java.util.Date getLastFired()
	{
		return getLastFired(getContext());
	}

	/**
	 * @param context
	 * @return value of LastFired
	 */
	public final java.util.Date getLastFired(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastFired.toString());
	}

	/**
	 * Set value of LastFired
	 * @param lastfired
	 */
	public final void setLastFired(java.util.Date lastfired)
	{
		setLastFired(getContext(), lastfired);
	}

	/**
	 * Set value of LastFired
	 * @param context
	 * @param lastfired
	 */
	public final void setLastFired(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lastfired)
	{
		getMendixObject().setValue(context, MemberNames.LastFired.toString(), lastfired);
	}

	/**
	 * @return value of CheckIteration
	 */
	public final java.lang.Integer getCheckIteration()
	{
		return getCheckIteration(getContext());
	}

	/**
	 * @param context
	 * @return value of CheckIteration
	 */
	public final java.lang.Integer getCheckIteration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CheckIteration.toString());
	}

	/**
	 * Set value of CheckIteration
	 * @param checkiteration
	 */
	public final void setCheckIteration(java.lang.Integer checkiteration)
	{
		setCheckIteration(getContext(), checkiteration);
	}

	/**
	 * Set value of CheckIteration
	 * @param context
	 * @param checkiteration
	 */
	public final void setCheckIteration(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer checkiteration)
	{
		getMendixObject().setValue(context, MemberNames.CheckIteration.toString(), checkiteration);
	}

	/**
	 * @return value of ActionRunMicroflow
	 */
	public final java.lang.Boolean getActionRunMicroflow()
	{
		return getActionRunMicroflow(getContext());
	}

	/**
	 * @param context
	 * @return value of ActionRunMicroflow
	 */
	public final java.lang.Boolean getActionRunMicroflow(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ActionRunMicroflow.toString());
	}

	/**
	 * Set value of ActionRunMicroflow
	 * @param actionrunmicroflow
	 */
	public final void setActionRunMicroflow(java.lang.Boolean actionrunmicroflow)
	{
		setActionRunMicroflow(getContext(), actionrunmicroflow);
	}

	/**
	 * Set value of ActionRunMicroflow
	 * @param context
	 * @param actionrunmicroflow
	 */
	public final void setActionRunMicroflow(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean actionrunmicroflow)
	{
		getMendixObject().setValue(context, MemberNames.ActionRunMicroflow.toString(), actionrunmicroflow);
	}

	/**
	 * @return value of ActionRunMicroflowName
	 */
	public final java.lang.String getActionRunMicroflowName()
	{
		return getActionRunMicroflowName(getContext());
	}

	/**
	 * @param context
	 * @return value of ActionRunMicroflowName
	 */
	public final java.lang.String getActionRunMicroflowName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ActionRunMicroflowName.toString());
	}

	/**
	 * Set value of ActionRunMicroflowName
	 * @param actionrunmicroflowname
	 */
	public final void setActionRunMicroflowName(java.lang.String actionrunmicroflowname)
	{
		setActionRunMicroflowName(getContext(), actionrunmicroflowname);
	}

	/**
	 * Set value of ActionRunMicroflowName
	 * @param context
	 * @param actionrunmicroflowname
	 */
	public final void setActionRunMicroflowName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String actionrunmicroflowname)
	{
		getMendixObject().setValue(context, MemberNames.ActionRunMicroflowName.toString(), actionrunmicroflowname);
	}

	/**
	 * @return value of ActionTrapMessage
	 */
	public final java.lang.Boolean getActionTrapMessage()
	{
		return getActionTrapMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of ActionTrapMessage
	 */
	public final java.lang.Boolean getActionTrapMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ActionTrapMessage.toString());
	}

	/**
	 * Set value of ActionTrapMessage
	 * @param actiontrapmessage
	 */
	public final void setActionTrapMessage(java.lang.Boolean actiontrapmessage)
	{
		setActionTrapMessage(getContext(), actiontrapmessage);
	}

	/**
	 * Set value of ActionTrapMessage
	 * @param context
	 * @param actiontrapmessage
	 */
	public final void setActionTrapMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean actiontrapmessage)
	{
		getMendixObject().setValue(context, MemberNames.ActionTrapMessage.toString(), actiontrapmessage);
	}

	/**
	 * @return value of ActionTrapMessageText
	 */
	public final java.lang.String getActionTrapMessageText()
	{
		return getActionTrapMessageText(getContext());
	}

	/**
	 * @param context
	 * @return value of ActionTrapMessageText
	 */
	public final java.lang.String getActionTrapMessageText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ActionTrapMessageText.toString());
	}

	/**
	 * Set value of ActionTrapMessageText
	 * @param actiontrapmessagetext
	 */
	public final void setActionTrapMessageText(java.lang.String actiontrapmessagetext)
	{
		setActionTrapMessageText(getContext(), actiontrapmessagetext);
	}

	/**
	 * Set value of ActionTrapMessageText
	 * @param context
	 * @param actiontrapmessagetext
	 */
	public final void setActionTrapMessageText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String actiontrapmessagetext)
	{
		getMendixObject().setValue(context, MemberNames.ActionTrapMessageText.toString(), actiontrapmessagetext);
	}

	/**
	 * @return value of ActionHeapDump
	 */
	public final java.lang.Boolean getActionHeapDump()
	{
		return getActionHeapDump(getContext());
	}

	/**
	 * @param context
	 * @return value of ActionHeapDump
	 */
	public final java.lang.Boolean getActionHeapDump(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ActionHeapDump.toString());
	}

	/**
	 * Set value of ActionHeapDump
	 * @param actionheapdump
	 */
	public final void setActionHeapDump(java.lang.Boolean actionheapdump)
	{
		setActionHeapDump(getContext(), actionheapdump);
	}

	/**
	 * Set value of ActionHeapDump
	 * @param context
	 * @param actionheapdump
	 */
	public final void setActionHeapDump(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean actionheapdump)
	{
		getMendixObject().setValue(context, MemberNames.ActionHeapDump.toString(), actionheapdump);
	}

	/**
	 * Set value of TriggerContinuation
	 * @param triggercontinuation
	 */
	public final apmagent.proxies.TriggerContinuationEnum getTriggerContinuation()
	{
		return getTriggerContinuation(getContext());
	}

	/**
	 * @param context
	 * @return value of TriggerContinuation
	 */
	public final apmagent.proxies.TriggerContinuationEnum getTriggerContinuation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TriggerContinuation.toString());
		if (obj == null)
			return null;

		return apmagent.proxies.TriggerContinuationEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TriggerContinuation
	 * @param triggercontinuation
	 */
	public final void setTriggerContinuation(apmagent.proxies.TriggerContinuationEnum triggercontinuation)
	{
		setTriggerContinuation(getContext(), triggercontinuation);
	}

	/**
	 * Set value of TriggerContinuation
	 * @param context
	 * @param triggercontinuation
	 */
	public final void setTriggerContinuation(com.mendix.systemwideinterfaces.core.IContext context, apmagent.proxies.TriggerContinuationEnum triggercontinuation)
	{
		if (triggercontinuation != null)
			getMendixObject().setValue(context, MemberNames.TriggerContinuation.toString(), triggercontinuation.toString());
		else
			getMendixObject().setValue(context, MemberNames.TriggerContinuation.toString(), null);
	}

	/**
	 * @return value of TriggerContinuationDelay
	 */
	public final java.lang.Integer getTriggerContinuationDelay()
	{
		return getTriggerContinuationDelay(getContext());
	}

	/**
	 * @param context
	 * @return value of TriggerContinuationDelay
	 */
	public final java.lang.Integer getTriggerContinuationDelay(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TriggerContinuationDelay.toString());
	}

	/**
	 * Set value of TriggerContinuationDelay
	 * @param triggercontinuationdelay
	 */
	public final void setTriggerContinuationDelay(java.lang.Integer triggercontinuationdelay)
	{
		setTriggerContinuationDelay(getContext(), triggercontinuationdelay);
	}

	/**
	 * Set value of TriggerContinuationDelay
	 * @param context
	 * @param triggercontinuationdelay
	 */
	public final void setTriggerContinuationDelay(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer triggercontinuationdelay)
	{
		getMendixObject().setValue(context, MemberNames.TriggerContinuationDelay.toString(), triggercontinuationdelay);
	}

	/**
	 * @return value of TriggerContinuationPaused
	 */
	public final java.lang.Boolean getTriggerContinuationPaused()
	{
		return getTriggerContinuationPaused(getContext());
	}

	/**
	 * @param context
	 * @return value of TriggerContinuationPaused
	 */
	public final java.lang.Boolean getTriggerContinuationPaused(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.TriggerContinuationPaused.toString());
	}

	/**
	 * Set value of TriggerContinuationPaused
	 * @param triggercontinuationpaused
	 */
	public final void setTriggerContinuationPaused(java.lang.Boolean triggercontinuationpaused)
	{
		setTriggerContinuationPaused(getContext(), triggercontinuationpaused);
	}

	/**
	 * Set value of TriggerContinuationPaused
	 * @param context
	 * @param triggercontinuationpaused
	 */
	public final void setTriggerContinuationPaused(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean triggercontinuationpaused)
	{
		getMendixObject().setValue(context, MemberNames.TriggerContinuationPaused.toString(), triggercontinuationpaused);
	}

	/**
	 * @return value of MetricTrigger_MetricCollectorItem
	 */
	public final apmagent.proxies.MetricCollectorItem getMetricTrigger_MetricCollectorItem() throws com.mendix.core.CoreException
	{
		return getMetricTrigger_MetricCollectorItem(getContext());
	}

	/**
	 * @param context
	 * @return value of MetricTrigger_MetricCollectorItem
	 */
	public final apmagent.proxies.MetricCollectorItem getMetricTrigger_MetricCollectorItem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		apmagent.proxies.MetricCollectorItem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MetricTrigger_MetricCollectorItem.toString());
		if (identifier != null)
			result = apmagent.proxies.MetricCollectorItem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MetricTrigger_MetricCollectorItem
	 * @param metrictrigger_metriccollectoritem
	 */
	public final void setMetricTrigger_MetricCollectorItem(apmagent.proxies.MetricCollectorItem metrictrigger_metriccollectoritem)
	{
		setMetricTrigger_MetricCollectorItem(getContext(), metrictrigger_metriccollectoritem);
	}

	/**
	 * Set value of MetricTrigger_MetricCollectorItem
	 * @param context
	 * @param metrictrigger_metriccollectoritem
	 */
	public final void setMetricTrigger_MetricCollectorItem(com.mendix.systemwideinterfaces.core.IContext context, apmagent.proxies.MetricCollectorItem metrictrigger_metriccollectoritem)
	{
		if (metrictrigger_metriccollectoritem == null)
			getMendixObject().setValue(context, MemberNames.MetricTrigger_MetricCollectorItem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MetricTrigger_MetricCollectorItem.toString(), metrictrigger_metriccollectoritem.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return metricTriggerMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final apmagent.proxies.MetricTrigger that = (apmagent.proxies.MetricTrigger) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "APMAgent.MetricTrigger";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
