// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowshared.proxies;

public class WorkflowResult
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workflowResultMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "WorkflowShared.WorkflowResult";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Description("Description"),
		ResultType("ResultType");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkflowResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "WorkflowShared.WorkflowResult"));
	}

	protected WorkflowResult(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workflowResultMendixObject)
	{
		if (workflowResultMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("WorkflowShared.WorkflowResult", workflowResultMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a WorkflowShared.WorkflowResult");

		this.workflowResultMendixObject = workflowResultMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'WorkflowResult.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static workflowshared.proxies.WorkflowResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return workflowshared.proxies.WorkflowResult.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static workflowshared.proxies.WorkflowResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new workflowshared.proxies.WorkflowResult(context, mendixObject);
	}

	public static workflowshared.proxies.WorkflowResult load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return workflowshared.proxies.WorkflowResult.initialize(context, mendixObject);
	}

	public static java.util.List<workflowshared.proxies.WorkflowResult> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<workflowshared.proxies.WorkflowResult> result = new java.util.ArrayList<workflowshared.proxies.WorkflowResult>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//WorkflowShared.WorkflowResult" + xpathConstraint))
			result.add(workflowshared.proxies.WorkflowResult.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * Set value of ResultType
	 * @param resulttype
	 */
	public final workflowshared.proxies.WorkflowResultEnum getResultType()
	{
		return getResultType(getContext());
	}

	/**
	 * @param context
	 * @return value of ResultType
	 */
	public final workflowshared.proxies.WorkflowResultEnum getResultType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ResultType.toString());
		if (obj == null)
			return null;

		return workflowshared.proxies.WorkflowResultEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ResultType
	 * @param resulttype
	 */
	public final void setResultType(workflowshared.proxies.WorkflowResultEnum resulttype)
	{
		setResultType(getContext(), resulttype);
	}

	/**
	 * Set value of ResultType
	 * @param context
	 * @param resulttype
	 */
	public final void setResultType(com.mendix.systemwideinterfaces.core.IContext context, workflowshared.proxies.WorkflowResultEnum resulttype)
	{
		if (resulttype != null)
			getMendixObject().setValue(context, MemberNames.ResultType.toString(), resulttype.toString());
		else
			getMendixObject().setValue(context, MemberNames.ResultType.toString(), null);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workflowResultMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final workflowshared.proxies.WorkflowResult that = (workflowshared.proxies.WorkflowResult) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "WorkflowShared.WorkflowResult";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
