// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowshared.proxies;

public enum WorkflowResultEnum
{
	Succes(new java.lang.String[][] { new java.lang.String[] { "en_US", "Success" }, new java.lang.String[] { "de_DE", "Erfolg" }, new java.lang.String[] { "nl_NL", "Succes" } }),
	Failed(new java.lang.String[][] { new java.lang.String[] { "en_US", "Failed" }, new java.lang.String[] { "de_DE", "Fehlgeschlagen" }, new java.lang.String[] { "nl_NL", "Mislukt" } }),
	Cancelled(new java.lang.String[][] { new java.lang.String[] { "en_US", "Cancelled" }, new java.lang.String[] { "de_DE", "Annuliert" }, new java.lang.String[] { "nl_NL", "Geannuleerd" } }),
	TimeOut(new java.lang.String[][] { new java.lang.String[] { "en_US", "Time Out" }, new java.lang.String[] { "de_DE", "Zeitlimit" }, new java.lang.String[] { "nl_NL", "Time-out" } }),
	User_Defined(new java.lang.String[][] { new java.lang.String[] { "en_US", "User Defined" }, new java.lang.String[] { "de_DE", "Definierter Benutzer" }, new java.lang.String[] { "nl_NL", "Gedefinieerd door gebruiker" } }),
	Approval_Approved(new java.lang.String[][] { new java.lang.String[] { "en_US", "Approval Approved" }, new java.lang.String[] { "de_DE", "Abnahmen genehmigt" }, new java.lang.String[] { "nl_NL", "Goedkeuring goedgekeurd" } }),
	Approval_Rejected(new java.lang.String[][] { new java.lang.String[] { "en_US", "Approval Rejected" }, new java.lang.String[] { "de_DE", "Abnahme abgelehnt" }, new java.lang.String[] { "nl_NL", "Goedkeuring afgewezen" } }),
	Approval_Cancelled(new java.lang.String[][] { new java.lang.String[] { "en_US", "Approval Cancelled" }, new java.lang.String[] { "de_DE", "Abnahme abgebrochen" }, new java.lang.String[] { "nl_NL", "Goedkeuring geannuleerd" } }),
	Merge_Passed_And_Closed(new java.lang.String[][] { new java.lang.String[] { "en_US", "Merge Passed And Closed" }, new java.lang.String[] { "de_DE", "Merge gelungen und geschlossen" }, new java.lang.String[] { "nl_NL", "Merge uitgevoerd en afgesloten" } }),
	Merge_Passed_And_Open(new java.lang.String[][] { new java.lang.String[] { "en_US", "Merge Passed And Open" }, new java.lang.String[] { "de_DE", "Merge Verlaufen und Offen" }, new java.lang.String[] { "nl_NL", "Merge uitgevoerd en open" } }),
	Merge_Not_Passed(new java.lang.String[][] { new java.lang.String[] { "en_US", "Merge Not Passed" }, new java.lang.String[] { "de_DE", "Merge nicht gelungen" }, new java.lang.String[] { "nl_NL", "Merge niet uitgevoerd" } }),
	Other(new java.lang.String[][] { new java.lang.String[] { "en_US", "Other" }, new java.lang.String[] { "de_DE", "Andere " }, new java.lang.String[] { "nl_NL", "Anders" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private WorkflowResultEnum(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
