// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package da.proxies;

public class AutomaticDataAccess
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject automaticDataAccessMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DA.AutomaticDataAccess";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Order("Order"),
		Action("Action"),
		HasMultipleRelations("HasMultipleRelations"),
		SourceType("SourceType"),
		Active("Active"),
		RelationType("RelationType"),
		Description("Description"),
		AutomaticDataAccess_DataAccessEntityLink("DA.AutomaticDataAccess_DataAccessEntityLink"),
		AutomaticDataAccess_SourceEntity("DA.AutomaticDataAccess_SourceEntity"),
		AutomaticDataAccess_DestinationEntity("DA.AutomaticDataAccess_DestinationEntity"),
		AutomaticDataAccess_MendixRelation("DA.AutomaticDataAccess_MendixRelation");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AutomaticDataAccess(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DA.AutomaticDataAccess"));
	}

	protected AutomaticDataAccess(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject automaticDataAccessMendixObject)
	{
		if (automaticDataAccessMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DA.AutomaticDataAccess", automaticDataAccessMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DA.AutomaticDataAccess");

		this.automaticDataAccessMendixObject = automaticDataAccessMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AutomaticDataAccess.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static da.proxies.AutomaticDataAccess initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return da.proxies.AutomaticDataAccess.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static da.proxies.AutomaticDataAccess initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new da.proxies.AutomaticDataAccess(context, mendixObject);
	}

	public static da.proxies.AutomaticDataAccess load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return da.proxies.AutomaticDataAccess.initialize(context, mendixObject);
	}

	public static java.util.List<da.proxies.AutomaticDataAccess> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<da.proxies.AutomaticDataAccess> result = new java.util.ArrayList<da.proxies.AutomaticDataAccess>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DA.AutomaticDataAccess" + xpathConstraint))
			result.add(da.proxies.AutomaticDataAccess.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Order
	 */
	public final java.lang.Integer getOrder()
	{
		return getOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of Order
	 */
	public final java.lang.Integer getOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Order.toString());
	}

	/**
	 * Set value of Order
	 * @param order
	 */
	public final void setOrder(java.lang.Integer order)
	{
		setOrder(getContext(), order);
	}

	/**
	 * Set value of Order
	 * @param context
	 * @param order
	 */
	public final void setOrder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer order)
	{
		getMendixObject().setValue(context, MemberNames.Order.toString(), order);
	}

	/**
	 * Set value of Action
	 * @param action
	 */
	public final da.proxies.AutomaticDataAccessActionEnum getAction()
	{
		return getAction(getContext());
	}

	/**
	 * @param context
	 * @return value of Action
	 */
	public final da.proxies.AutomaticDataAccessActionEnum getAction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Action.toString());
		if (obj == null)
			return null;

		return da.proxies.AutomaticDataAccessActionEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Action
	 * @param action
	 */
	public final void setAction(da.proxies.AutomaticDataAccessActionEnum action)
	{
		setAction(getContext(), action);
	}

	/**
	 * Set value of Action
	 * @param context
	 * @param action
	 */
	public final void setAction(com.mendix.systemwideinterfaces.core.IContext context, da.proxies.AutomaticDataAccessActionEnum action)
	{
		if (action != null)
			getMendixObject().setValue(context, MemberNames.Action.toString(), action.toString());
		else
			getMendixObject().setValue(context, MemberNames.Action.toString(), null);
	}

	/**
	 * @return value of HasMultipleRelations
	 */
	public final java.lang.Boolean getHasMultipleRelations()
	{
		return getHasMultipleRelations(getContext());
	}

	/**
	 * @param context
	 * @return value of HasMultipleRelations
	 */
	public final java.lang.Boolean getHasMultipleRelations(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasMultipleRelations.toString());
	}

	/**
	 * Set value of HasMultipleRelations
	 * @param hasmultiplerelations
	 */
	public final void setHasMultipleRelations(java.lang.Boolean hasmultiplerelations)
	{
		setHasMultipleRelations(getContext(), hasmultiplerelations);
	}

	/**
	 * Set value of HasMultipleRelations
	 * @param context
	 * @param hasmultiplerelations
	 */
	public final void setHasMultipleRelations(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hasmultiplerelations)
	{
		getMendixObject().setValue(context, MemberNames.HasMultipleRelations.toString(), hasmultiplerelations);
	}

	/**
	 * Set value of SourceType
	 * @param sourcetype
	 */
	public final da.proxies.AutomaticDataAccessSourceEnum getSourceType()
	{
		return getSourceType(getContext());
	}

	/**
	 * @param context
	 * @return value of SourceType
	 */
	public final da.proxies.AutomaticDataAccessSourceEnum getSourceType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SourceType.toString());
		if (obj == null)
			return null;

		return da.proxies.AutomaticDataAccessSourceEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of SourceType
	 * @param sourcetype
	 */
	public final void setSourceType(da.proxies.AutomaticDataAccessSourceEnum sourcetype)
	{
		setSourceType(getContext(), sourcetype);
	}

	/**
	 * Set value of SourceType
	 * @param context
	 * @param sourcetype
	 */
	public final void setSourceType(com.mendix.systemwideinterfaces.core.IContext context, da.proxies.AutomaticDataAccessSourceEnum sourcetype)
	{
		if (sourcetype != null)
			getMendixObject().setValue(context, MemberNames.SourceType.toString(), sourcetype.toString());
		else
			getMendixObject().setValue(context, MemberNames.SourceType.toString(), null);
	}

	/**
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive()
	{
		return getActive(getContext());
	}

	/**
	 * @param context
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Active.toString());
	}

	/**
	 * Set value of Active
	 * @param active
	 */
	public final void setActive(java.lang.Boolean active)
	{
		setActive(getContext(), active);
	}

	/**
	 * Set value of Active
	 * @param context
	 * @param active
	 */
	public final void setActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean active)
	{
		getMendixObject().setValue(context, MemberNames.Active.toString(), active);
	}

	/**
	 * Set value of RelationType
	 * @param relationtype
	 */
	public final da.proxies.AutomaticDataAccessRelationEnum getRelationType()
	{
		return getRelationType(getContext());
	}

	/**
	 * @param context
	 * @return value of RelationType
	 */
	public final da.proxies.AutomaticDataAccessRelationEnum getRelationType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.RelationType.toString());
		if (obj == null)
			return null;

		return da.proxies.AutomaticDataAccessRelationEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of RelationType
	 * @param relationtype
	 */
	public final void setRelationType(da.proxies.AutomaticDataAccessRelationEnum relationtype)
	{
		setRelationType(getContext(), relationtype);
	}

	/**
	 * Set value of RelationType
	 * @param context
	 * @param relationtype
	 */
	public final void setRelationType(com.mendix.systemwideinterfaces.core.IContext context, da.proxies.AutomaticDataAccessRelationEnum relationtype)
	{
		if (relationtype != null)
			getMendixObject().setValue(context, MemberNames.RelationType.toString(), relationtype.toString());
		else
			getMendixObject().setValue(context, MemberNames.RelationType.toString(), null);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of AutomaticDataAccess_DataAccessEntityLink
	 */
	public final da.proxies.DataAccessEntityLink getAutomaticDataAccess_DataAccessEntityLink() throws com.mendix.core.CoreException
	{
		return getAutomaticDataAccess_DataAccessEntityLink(getContext());
	}

	/**
	 * @param context
	 * @return value of AutomaticDataAccess_DataAccessEntityLink
	 */
	public final da.proxies.DataAccessEntityLink getAutomaticDataAccess_DataAccessEntityLink(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		da.proxies.DataAccessEntityLink result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AutomaticDataAccess_DataAccessEntityLink.toString());
		if (identifier != null)
			result = da.proxies.DataAccessEntityLink.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AutomaticDataAccess_DataAccessEntityLink
	 * @param automaticdataaccess_dataaccessentitylink
	 */
	public final void setAutomaticDataAccess_DataAccessEntityLink(da.proxies.DataAccessEntityLink automaticdataaccess_dataaccessentitylink)
	{
		setAutomaticDataAccess_DataAccessEntityLink(getContext(), automaticdataaccess_dataaccessentitylink);
	}

	/**
	 * Set value of AutomaticDataAccess_DataAccessEntityLink
	 * @param context
	 * @param automaticdataaccess_dataaccessentitylink
	 */
	public final void setAutomaticDataAccess_DataAccessEntityLink(com.mendix.systemwideinterfaces.core.IContext context, da.proxies.DataAccessEntityLink automaticdataaccess_dataaccessentitylink)
	{
		if (automaticdataaccess_dataaccessentitylink == null)
			getMendixObject().setValue(context, MemberNames.AutomaticDataAccess_DataAccessEntityLink.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AutomaticDataAccess_DataAccessEntityLink.toString(), automaticdataaccess_dataaccessentitylink.getMendixObject().getId());
	}

	/**
	 * @return value of AutomaticDataAccess_SourceEntity
	 */
	public final metamodel.proxies.MendixEntity getAutomaticDataAccess_SourceEntity() throws com.mendix.core.CoreException
	{
		return getAutomaticDataAccess_SourceEntity(getContext());
	}

	/**
	 * @param context
	 * @return value of AutomaticDataAccess_SourceEntity
	 */
	public final metamodel.proxies.MendixEntity getAutomaticDataAccess_SourceEntity(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		metamodel.proxies.MendixEntity result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AutomaticDataAccess_SourceEntity.toString());
		if (identifier != null)
			result = metamodel.proxies.MendixEntity.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AutomaticDataAccess_SourceEntity
	 * @param automaticdataaccess_sourceentity
	 */
	public final void setAutomaticDataAccess_SourceEntity(metamodel.proxies.MendixEntity automaticdataaccess_sourceentity)
	{
		setAutomaticDataAccess_SourceEntity(getContext(), automaticdataaccess_sourceentity);
	}

	/**
	 * Set value of AutomaticDataAccess_SourceEntity
	 * @param context
	 * @param automaticdataaccess_sourceentity
	 */
	public final void setAutomaticDataAccess_SourceEntity(com.mendix.systemwideinterfaces.core.IContext context, metamodel.proxies.MendixEntity automaticdataaccess_sourceentity)
	{
		if (automaticdataaccess_sourceentity == null)
			getMendixObject().setValue(context, MemberNames.AutomaticDataAccess_SourceEntity.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AutomaticDataAccess_SourceEntity.toString(), automaticdataaccess_sourceentity.getMendixObject().getId());
	}

	/**
	 * @return value of AutomaticDataAccess_DestinationEntity
	 */
	public final metamodel.proxies.MendixEntity getAutomaticDataAccess_DestinationEntity() throws com.mendix.core.CoreException
	{
		return getAutomaticDataAccess_DestinationEntity(getContext());
	}

	/**
	 * @param context
	 * @return value of AutomaticDataAccess_DestinationEntity
	 */
	public final metamodel.proxies.MendixEntity getAutomaticDataAccess_DestinationEntity(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		metamodel.proxies.MendixEntity result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AutomaticDataAccess_DestinationEntity.toString());
		if (identifier != null)
			result = metamodel.proxies.MendixEntity.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AutomaticDataAccess_DestinationEntity
	 * @param automaticdataaccess_destinationentity
	 */
	public final void setAutomaticDataAccess_DestinationEntity(metamodel.proxies.MendixEntity automaticdataaccess_destinationentity)
	{
		setAutomaticDataAccess_DestinationEntity(getContext(), automaticdataaccess_destinationentity);
	}

	/**
	 * Set value of AutomaticDataAccess_DestinationEntity
	 * @param context
	 * @param automaticdataaccess_destinationentity
	 */
	public final void setAutomaticDataAccess_DestinationEntity(com.mendix.systemwideinterfaces.core.IContext context, metamodel.proxies.MendixEntity automaticdataaccess_destinationentity)
	{
		if (automaticdataaccess_destinationentity == null)
			getMendixObject().setValue(context, MemberNames.AutomaticDataAccess_DestinationEntity.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AutomaticDataAccess_DestinationEntity.toString(), automaticdataaccess_destinationentity.getMendixObject().getId());
	}

	/**
	 * @return value of AutomaticDataAccess_MendixRelation
	 */
	public final metamodel.proxies.MendixRelation getAutomaticDataAccess_MendixRelation() throws com.mendix.core.CoreException
	{
		return getAutomaticDataAccess_MendixRelation(getContext());
	}

	/**
	 * @param context
	 * @return value of AutomaticDataAccess_MendixRelation
	 */
	public final metamodel.proxies.MendixRelation getAutomaticDataAccess_MendixRelation(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		metamodel.proxies.MendixRelation result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AutomaticDataAccess_MendixRelation.toString());
		if (identifier != null)
			result = metamodel.proxies.MendixRelation.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AutomaticDataAccess_MendixRelation
	 * @param automaticdataaccess_mendixrelation
	 */
	public final void setAutomaticDataAccess_MendixRelation(metamodel.proxies.MendixRelation automaticdataaccess_mendixrelation)
	{
		setAutomaticDataAccess_MendixRelation(getContext(), automaticdataaccess_mendixrelation);
	}

	/**
	 * Set value of AutomaticDataAccess_MendixRelation
	 * @param context
	 * @param automaticdataaccess_mendixrelation
	 */
	public final void setAutomaticDataAccess_MendixRelation(com.mendix.systemwideinterfaces.core.IContext context, metamodel.proxies.MendixRelation automaticdataaccess_mendixrelation)
	{
		if (automaticdataaccess_mendixrelation == null)
			getMendixObject().setValue(context, MemberNames.AutomaticDataAccess_MendixRelation.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AutomaticDataAccess_MendixRelation.toString(), automaticdataaccess_mendixrelation.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return automaticDataAccessMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final da.proxies.AutomaticDataAccess that = (da.proxies.AutomaticDataAccess) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DA.AutomaticDataAccess";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
