// This file was generated by Mendix Modeler 7.7.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package interfaceshared.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the InterfaceShared module

	public static java.lang.String getDefaultDateTimeFormat()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("InterfaceShared.DefaultDateTimeFormat");
	}

	public static java.lang.String getDefaultFailCode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("InterfaceShared.DefaultFailCode");
	}

	public static java.lang.String getDefaultSuccessCode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("InterfaceShared.DefaultSuccessCode");
	}
}