// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cms.proxies;

public class StartPageData
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject startPageDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CMS.StartPageData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Data("Data"),
		Page("Page"),
		Position("Position"),
		UU95_StartPageData_Language("CMS.UU95_StartPageData_Language");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public StartPageData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CMS.StartPageData"));
	}

	protected StartPageData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject startPageDataMendixObject)
	{
		if (startPageDataMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("CMS.StartPageData", startPageDataMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CMS.StartPageData");

		this.startPageDataMendixObject = startPageDataMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'StartPageData.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static cms.proxies.StartPageData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return cms.proxies.StartPageData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static cms.proxies.StartPageData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new cms.proxies.StartPageData(context, mendixObject);
	}

	public static cms.proxies.StartPageData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return cms.proxies.StartPageData.initialize(context, mendixObject);
	}

	public static java.util.List<cms.proxies.StartPageData> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<cms.proxies.StartPageData> result = new java.util.ArrayList<cms.proxies.StartPageData>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CMS.StartPageData" + xpathConstraint))
			result.add(cms.proxies.StartPageData.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Data
	 */
	public final java.lang.String getData()
	{
		return getData(getContext());
	}

	/**
	 * @param context
	 * @return value of Data
	 */
	public final java.lang.String getData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Data.toString());
	}

	/**
	 * Set value of Data
	 * @param data
	 */
	public final void setData(java.lang.String data)
	{
		setData(getContext(), data);
	}

	/**
	 * Set value of Data
	 * @param context
	 * @param data
	 */
	public final void setData(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String data)
	{
		getMendixObject().setValue(context, MemberNames.Data.toString(), data);
	}

	/**
	 * Set value of Page
	 * @param page
	 */
	public final cms.proxies.CMSPages getPage()
	{
		return getPage(getContext());
	}

	/**
	 * @param context
	 * @return value of Page
	 */
	public final cms.proxies.CMSPages getPage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Page.toString());
		if (obj == null)
			return null;

		return cms.proxies.CMSPages.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Page
	 * @param page
	 */
	public final void setPage(cms.proxies.CMSPages page)
	{
		setPage(getContext(), page);
	}

	/**
	 * Set value of Page
	 * @param context
	 * @param page
	 */
	public final void setPage(com.mendix.systemwideinterfaces.core.IContext context, cms.proxies.CMSPages page)
	{
		if (page != null)
			getMendixObject().setValue(context, MemberNames.Page.toString(), page.toString());
		else
			getMendixObject().setValue(context, MemberNames.Page.toString(), null);
	}

	/**
	 * @return value of Position
	 */
	public final java.lang.String getPosition()
	{
		return getPosition(getContext());
	}

	/**
	 * @param context
	 * @return value of Position
	 */
	public final java.lang.String getPosition(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Position.toString());
	}

	/**
	 * Set value of Position
	 * @param position
	 */
	public final void setPosition(java.lang.String position)
	{
		setPosition(getContext(), position);
	}

	/**
	 * Set value of Position
	 * @param context
	 * @param position
	 */
	public final void setPosition(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String position)
	{
		getMendixObject().setValue(context, MemberNames.Position.toString(), position);
	}

	/**
	 * @return value of UU95_StartPageData_Language
	 */
	public final system.proxies.Language getUU95_StartPageData_Language() throws com.mendix.core.CoreException
	{
		return getUU95_StartPageData_Language(getContext());
	}

	/**
	 * @param context
	 * @return value of UU95_StartPageData_Language
	 */
	public final system.proxies.Language getUU95_StartPageData_Language(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Language result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UU95_StartPageData_Language.toString());
		if (identifier != null)
			result = system.proxies.Language.load(context, identifier);
		return result;
	}

	/**
	 * Set value of UU95_StartPageData_Language
	 * @param uu95_startpagedata_language
	 */
	public final void setUU95_StartPageData_Language(system.proxies.Language uu95_startpagedata_language)
	{
		setUU95_StartPageData_Language(getContext(), uu95_startpagedata_language);
	}

	/**
	 * Set value of UU95_StartPageData_Language
	 * @param context
	 * @param uu95_startpagedata_language
	 */
	public final void setUU95_StartPageData_Language(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Language uu95_startpagedata_language)
	{
		if (uu95_startpagedata_language == null)
			getMendixObject().setValue(context, MemberNames.UU95_StartPageData_Language.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.UU95_StartPageData_Language.toString(), uu95_startpagedata_language.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return startPageDataMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final cms.proxies.StartPageData that = (cms.proxies.StartPageData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CMS.StartPageData";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
