// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package interfaceattachments.proxies;

public class AttachmentsResponse extends interfaceshared.proxies.ResponseExpertDesk
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "InterfaceAttachments.AttachmentsResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ResponseCode("ResponseCode"),
		ResponseMessage("ResponseMessage"),
		UU95_AttachmentsResponse_IncomingAttachments("InterfaceAttachments.UU95_AttachmentsResponse_IncomingAttachments"),
		AttachmentsResponse_AttachmentsResponseContainerExperDesk("InterfaceAttachments.AttachmentsResponse_AttachmentsResponseContainerExperDesk"),
		AttachmentsResponse_IncomingAttachmentsConfirmation("InterfaceAttachments.AttachmentsResponse_IncomingAttachmentsConfirmation"),
		AttachmentsResponse_OutgoingAttachmentsResponseMessageExpertDesk("InterfaceAttachments.AttachmentsResponse_OutgoingAttachmentsResponseMessageExpertDesk"),
		AttachmentResponsesContainerExpertDesk_AttachmentsResponse("InterfaceAttachments.AttachmentResponsesContainerExpertDesk_AttachmentsResponse"),
		ProcessingAttempt_Response("InterfaceShared.ProcessingAttempt_Response"),
		IncomingMessage_SynchronousResponse("InterfaceShared.IncomingMessage_SynchronousResponse");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AttachmentsResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "InterfaceAttachments.AttachmentsResponse"));
	}

	protected AttachmentsResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject attachmentsResponseMendixObject)
	{
		super(context, attachmentsResponseMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("InterfaceAttachments.AttachmentsResponse", attachmentsResponseMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a InterfaceAttachments.AttachmentsResponse");
	}

	/**
	 * @deprecated Use 'AttachmentsResponse.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static interfaceattachments.proxies.AttachmentsResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return interfaceattachments.proxies.AttachmentsResponse.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static interfaceattachments.proxies.AttachmentsResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new interfaceattachments.proxies.AttachmentsResponse(context, mendixObject);
	}

	public static interfaceattachments.proxies.AttachmentsResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return interfaceattachments.proxies.AttachmentsResponse.initialize(context, mendixObject);
	}

	public static java.util.List<interfaceattachments.proxies.AttachmentsResponse> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<interfaceattachments.proxies.AttachmentsResponse> result = new java.util.ArrayList<interfaceattachments.proxies.AttachmentsResponse>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//InterfaceAttachments.AttachmentsResponse" + xpathConstraint))
			result.add(interfaceattachments.proxies.AttachmentsResponse.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of UU95_AttachmentsResponse_IncomingAttachments
	 */
	public final interfaceattachments.proxies.IncomingAttachments getUU95_AttachmentsResponse_IncomingAttachments() throws com.mendix.core.CoreException
	{
		return getUU95_AttachmentsResponse_IncomingAttachments(getContext());
	}

	/**
	 * @param context
	 * @return value of UU95_AttachmentsResponse_IncomingAttachments
	 */
	public final interfaceattachments.proxies.IncomingAttachments getUU95_AttachmentsResponse_IncomingAttachments(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceattachments.proxies.IncomingAttachments result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UU95_AttachmentsResponse_IncomingAttachments.toString());
		if (identifier != null)
			result = interfaceattachments.proxies.IncomingAttachments.load(context, identifier);
		return result;
	}

	/**
	 * Set value of UU95_AttachmentsResponse_IncomingAttachments
	 * @param uu95_attachmentsresponse_incomingattachments
	 */
	public final void setUU95_AttachmentsResponse_IncomingAttachments(interfaceattachments.proxies.IncomingAttachments uu95_attachmentsresponse_incomingattachments)
	{
		setUU95_AttachmentsResponse_IncomingAttachments(getContext(), uu95_attachmentsresponse_incomingattachments);
	}

	/**
	 * Set value of UU95_AttachmentsResponse_IncomingAttachments
	 * @param context
	 * @param uu95_attachmentsresponse_incomingattachments
	 */
	public final void setUU95_AttachmentsResponse_IncomingAttachments(com.mendix.systemwideinterfaces.core.IContext context, interfaceattachments.proxies.IncomingAttachments uu95_attachmentsresponse_incomingattachments)
	{
		if (uu95_attachmentsresponse_incomingattachments == null)
			getMendixObject().setValue(context, MemberNames.UU95_AttachmentsResponse_IncomingAttachments.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.UU95_AttachmentsResponse_IncomingAttachments.toString(), uu95_attachmentsresponse_incomingattachments.getMendixObject().getId());
	}

	/**
	 * @return value of AttachmentsResponse_AttachmentsResponseContainerExperDesk
	 */
	public final interfaceattachments.proxies.AttachmentsResponseContainerExperDesk getAttachmentsResponse_AttachmentsResponseContainerExperDesk() throws com.mendix.core.CoreException
	{
		return getAttachmentsResponse_AttachmentsResponseContainerExperDesk(getContext());
	}

	/**
	 * @param context
	 * @return value of AttachmentsResponse_AttachmentsResponseContainerExperDesk
	 */
	public final interfaceattachments.proxies.AttachmentsResponseContainerExperDesk getAttachmentsResponse_AttachmentsResponseContainerExperDesk(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceattachments.proxies.AttachmentsResponseContainerExperDesk result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AttachmentsResponse_AttachmentsResponseContainerExperDesk.toString());
		if (identifier != null)
			result = interfaceattachments.proxies.AttachmentsResponseContainerExperDesk.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AttachmentsResponse_AttachmentsResponseContainerExperDesk
	 * @param attachmentsresponse_attachmentsresponsecontainerexperdesk
	 */
	public final void setAttachmentsResponse_AttachmentsResponseContainerExperDesk(interfaceattachments.proxies.AttachmentsResponseContainerExperDesk attachmentsresponse_attachmentsresponsecontainerexperdesk)
	{
		setAttachmentsResponse_AttachmentsResponseContainerExperDesk(getContext(), attachmentsresponse_attachmentsresponsecontainerexperdesk);
	}

	/**
	 * Set value of AttachmentsResponse_AttachmentsResponseContainerExperDesk
	 * @param context
	 * @param attachmentsresponse_attachmentsresponsecontainerexperdesk
	 */
	public final void setAttachmentsResponse_AttachmentsResponseContainerExperDesk(com.mendix.systemwideinterfaces.core.IContext context, interfaceattachments.proxies.AttachmentsResponseContainerExperDesk attachmentsresponse_attachmentsresponsecontainerexperdesk)
	{
		if (attachmentsresponse_attachmentsresponsecontainerexperdesk == null)
			getMendixObject().setValue(context, MemberNames.AttachmentsResponse_AttachmentsResponseContainerExperDesk.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AttachmentsResponse_AttachmentsResponseContainerExperDesk.toString(), attachmentsresponse_attachmentsresponsecontainerexperdesk.getMendixObject().getId());
	}

	/**
	 * @return value of AttachmentsResponse_IncomingAttachmentsConfirmation
	 */
	public final interfaceattachments.proxies.IncomingAttachmentsConfirmation getAttachmentsResponse_IncomingAttachmentsConfirmation() throws com.mendix.core.CoreException
	{
		return getAttachmentsResponse_IncomingAttachmentsConfirmation(getContext());
	}

	/**
	 * @param context
	 * @return value of AttachmentsResponse_IncomingAttachmentsConfirmation
	 */
	public final interfaceattachments.proxies.IncomingAttachmentsConfirmation getAttachmentsResponse_IncomingAttachmentsConfirmation(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceattachments.proxies.IncomingAttachmentsConfirmation result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AttachmentsResponse_IncomingAttachmentsConfirmation.toString());
		if (identifier != null)
			result = interfaceattachments.proxies.IncomingAttachmentsConfirmation.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AttachmentsResponse_IncomingAttachmentsConfirmation
	 * @param attachmentsresponse_incomingattachmentsconfirmation
	 */
	public final void setAttachmentsResponse_IncomingAttachmentsConfirmation(interfaceattachments.proxies.IncomingAttachmentsConfirmation attachmentsresponse_incomingattachmentsconfirmation)
	{
		setAttachmentsResponse_IncomingAttachmentsConfirmation(getContext(), attachmentsresponse_incomingattachmentsconfirmation);
	}

	/**
	 * Set value of AttachmentsResponse_IncomingAttachmentsConfirmation
	 * @param context
	 * @param attachmentsresponse_incomingattachmentsconfirmation
	 */
	public final void setAttachmentsResponse_IncomingAttachmentsConfirmation(com.mendix.systemwideinterfaces.core.IContext context, interfaceattachments.proxies.IncomingAttachmentsConfirmation attachmentsresponse_incomingattachmentsconfirmation)
	{
		if (attachmentsresponse_incomingattachmentsconfirmation == null)
			getMendixObject().setValue(context, MemberNames.AttachmentsResponse_IncomingAttachmentsConfirmation.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AttachmentsResponse_IncomingAttachmentsConfirmation.toString(), attachmentsresponse_incomingattachmentsconfirmation.getMendixObject().getId());
	}

	/**
	 * @return value of AttachmentsResponse_OutgoingAttachmentsResponseMessageExpertDesk
	 */
	public final interfaceattachments.proxies.OutgoingAttachmentsResponseMessageExpertDesk getAttachmentsResponse_OutgoingAttachmentsResponseMessageExpertDesk() throws com.mendix.core.CoreException
	{
		return getAttachmentsResponse_OutgoingAttachmentsResponseMessageExpertDesk(getContext());
	}

	/**
	 * @param context
	 * @return value of AttachmentsResponse_OutgoingAttachmentsResponseMessageExpertDesk
	 */
	public final interfaceattachments.proxies.OutgoingAttachmentsResponseMessageExpertDesk getAttachmentsResponse_OutgoingAttachmentsResponseMessageExpertDesk(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceattachments.proxies.OutgoingAttachmentsResponseMessageExpertDesk result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AttachmentsResponse_OutgoingAttachmentsResponseMessageExpertDesk.toString());
		if (identifier != null)
			result = interfaceattachments.proxies.OutgoingAttachmentsResponseMessageExpertDesk.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AttachmentsResponse_OutgoingAttachmentsResponseMessageExpertDesk
	 * @param attachmentsresponse_outgoingattachmentsresponsemessageexpertdesk
	 */
	public final void setAttachmentsResponse_OutgoingAttachmentsResponseMessageExpertDesk(interfaceattachments.proxies.OutgoingAttachmentsResponseMessageExpertDesk attachmentsresponse_outgoingattachmentsresponsemessageexpertdesk)
	{
		setAttachmentsResponse_OutgoingAttachmentsResponseMessageExpertDesk(getContext(), attachmentsresponse_outgoingattachmentsresponsemessageexpertdesk);
	}

	/**
	 * Set value of AttachmentsResponse_OutgoingAttachmentsResponseMessageExpertDesk
	 * @param context
	 * @param attachmentsresponse_outgoingattachmentsresponsemessageexpertdesk
	 */
	public final void setAttachmentsResponse_OutgoingAttachmentsResponseMessageExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, interfaceattachments.proxies.OutgoingAttachmentsResponseMessageExpertDesk attachmentsresponse_outgoingattachmentsresponsemessageexpertdesk)
	{
		if (attachmentsresponse_outgoingattachmentsresponsemessageexpertdesk == null)
			getMendixObject().setValue(context, MemberNames.AttachmentsResponse_OutgoingAttachmentsResponseMessageExpertDesk.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AttachmentsResponse_OutgoingAttachmentsResponseMessageExpertDesk.toString(), attachmentsresponse_outgoingattachmentsresponsemessageexpertdesk.getMendixObject().getId());
	}

	/**
	 * @return value of AttachmentResponsesContainerExpertDesk_AttachmentsResponse
	 */
	public final interfaceattachments.proxies.AttachmentResponsesContainerExpertDesk getAttachmentResponsesContainerExpertDesk_AttachmentsResponse() throws com.mendix.core.CoreException
	{
		return getAttachmentResponsesContainerExpertDesk_AttachmentsResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of AttachmentResponsesContainerExpertDesk_AttachmentsResponse
	 */
	public final interfaceattachments.proxies.AttachmentResponsesContainerExpertDesk getAttachmentResponsesContainerExpertDesk_AttachmentsResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceattachments.proxies.AttachmentResponsesContainerExpertDesk result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AttachmentResponsesContainerExpertDesk_AttachmentsResponse.toString());
		if (identifier != null)
			result = interfaceattachments.proxies.AttachmentResponsesContainerExpertDesk.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AttachmentResponsesContainerExpertDesk_AttachmentsResponse
	 * @param attachmentresponsescontainerexpertdesk_attachmentsresponse
	 */
	public final void setAttachmentResponsesContainerExpertDesk_AttachmentsResponse(interfaceattachments.proxies.AttachmentResponsesContainerExpertDesk attachmentresponsescontainerexpertdesk_attachmentsresponse)
	{
		setAttachmentResponsesContainerExpertDesk_AttachmentsResponse(getContext(), attachmentresponsescontainerexpertdesk_attachmentsresponse);
	}

	/**
	 * Set value of AttachmentResponsesContainerExpertDesk_AttachmentsResponse
	 * @param context
	 * @param attachmentresponsescontainerexpertdesk_attachmentsresponse
	 */
	public final void setAttachmentResponsesContainerExpertDesk_AttachmentsResponse(com.mendix.systemwideinterfaces.core.IContext context, interfaceattachments.proxies.AttachmentResponsesContainerExpertDesk attachmentresponsescontainerexpertdesk_attachmentsresponse)
	{
		if (attachmentresponsescontainerexpertdesk_attachmentsresponse == null)
			getMendixObject().setValue(context, MemberNames.AttachmentResponsesContainerExpertDesk_AttachmentsResponse.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AttachmentResponsesContainerExpertDesk_AttachmentsResponse.toString(), attachmentresponsescontainerexpertdesk_attachmentsresponse.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final interfaceattachments.proxies.AttachmentsResponse that = (interfaceattachments.proxies.AttachmentsResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "InterfaceAttachments.AttachmentsResponse";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
