// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package interfaceattachments.proxies;

public class OutgoingAttachmentsConfirmationResponseExpertDesk extends interfaceshared.proxies.ResponseExpertDesk
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "InterfaceAttachments.OutgoingAttachmentsConfirmationResponseExpertDesk";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ResponseCode("ResponseCode"),
		ResponseMessage("ResponseMessage"),
		OutgoingAttachmentsConfirmationResponseExpertDesk_OutgoingAttachmentsConfirmationResponseMessageExpertDesk("InterfaceAttachments.OutgoingAttachmentsConfirmationResponseExpertDesk_OutgoingAttachmentsConfirmationResponseMessageExpertDesk"),
		ProcessingAttempt_Response("InterfaceShared.ProcessingAttempt_Response"),
		IncomingMessage_SynchronousResponse("InterfaceShared.IncomingMessage_SynchronousResponse");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OutgoingAttachmentsConfirmationResponseExpertDesk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "InterfaceAttachments.OutgoingAttachmentsConfirmationResponseExpertDesk"));
	}

	protected OutgoingAttachmentsConfirmationResponseExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject outgoingAttachmentsConfirmationResponseExpertDeskMendixObject)
	{
		super(context, outgoingAttachmentsConfirmationResponseExpertDeskMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("InterfaceAttachments.OutgoingAttachmentsConfirmationResponseExpertDesk", outgoingAttachmentsConfirmationResponseExpertDeskMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a InterfaceAttachments.OutgoingAttachmentsConfirmationResponseExpertDesk");
	}

	/**
	 * @deprecated Use 'OutgoingAttachmentsConfirmationResponseExpertDesk.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static interfaceattachments.proxies.OutgoingAttachmentsConfirmationResponseExpertDesk initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return interfaceattachments.proxies.OutgoingAttachmentsConfirmationResponseExpertDesk.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static interfaceattachments.proxies.OutgoingAttachmentsConfirmationResponseExpertDesk initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new interfaceattachments.proxies.OutgoingAttachmentsConfirmationResponseExpertDesk(context, mendixObject);
	}

	public static interfaceattachments.proxies.OutgoingAttachmentsConfirmationResponseExpertDesk load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return interfaceattachments.proxies.OutgoingAttachmentsConfirmationResponseExpertDesk.initialize(context, mendixObject);
	}

	public static java.util.List<interfaceattachments.proxies.OutgoingAttachmentsConfirmationResponseExpertDesk> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<interfaceattachments.proxies.OutgoingAttachmentsConfirmationResponseExpertDesk> result = new java.util.ArrayList<interfaceattachments.proxies.OutgoingAttachmentsConfirmationResponseExpertDesk>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//InterfaceAttachments.OutgoingAttachmentsConfirmationResponseExpertDesk" + xpathConstraint))
			result.add(interfaceattachments.proxies.OutgoingAttachmentsConfirmationResponseExpertDesk.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of OutgoingAttachmentsConfirmationResponseExpertDesk_OutgoingAttachmentsConfirmationResponseMessageExpertDesk
	 */
	public final interfaceattachments.proxies.OutgoingAttachmentsConfirmationResponseMessageExpertDesk getOutgoingAttachmentsConfirmationResponseExpertDesk_OutgoingAttachmentsConfirmationResponseMessageExpertDesk() throws com.mendix.core.CoreException
	{
		return getOutgoingAttachmentsConfirmationResponseExpertDesk_OutgoingAttachmentsConfirmationResponseMessageExpertDesk(getContext());
	}

	/**
	 * @param context
	 * @return value of OutgoingAttachmentsConfirmationResponseExpertDesk_OutgoingAttachmentsConfirmationResponseMessageExpertDesk
	 */
	public final interfaceattachments.proxies.OutgoingAttachmentsConfirmationResponseMessageExpertDesk getOutgoingAttachmentsConfirmationResponseExpertDesk_OutgoingAttachmentsConfirmationResponseMessageExpertDesk(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceattachments.proxies.OutgoingAttachmentsConfirmationResponseMessageExpertDesk result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OutgoingAttachmentsConfirmationResponseExpertDesk_OutgoingAttachmentsConfirmationResponseMessageExpertDesk.toString());
		if (identifier != null)
			result = interfaceattachments.proxies.OutgoingAttachmentsConfirmationResponseMessageExpertDesk.load(context, identifier);
		return result;
	}

	/**
	 * Set value of OutgoingAttachmentsConfirmationResponseExpertDesk_OutgoingAttachmentsConfirmationResponseMessageExpertDesk
	 * @param outgoingattachmentsconfirmationresponseexpertdesk_outgoingattachmentsconfirmationresponsemessageexpertdesk
	 */
	public final void setOutgoingAttachmentsConfirmationResponseExpertDesk_OutgoingAttachmentsConfirmationResponseMessageExpertDesk(interfaceattachments.proxies.OutgoingAttachmentsConfirmationResponseMessageExpertDesk outgoingattachmentsconfirmationresponseexpertdesk_outgoingattachmentsconfirmationresponsemessageexpertdesk)
	{
		setOutgoingAttachmentsConfirmationResponseExpertDesk_OutgoingAttachmentsConfirmationResponseMessageExpertDesk(getContext(), outgoingattachmentsconfirmationresponseexpertdesk_outgoingattachmentsconfirmationresponsemessageexpertdesk);
	}

	/**
	 * Set value of OutgoingAttachmentsConfirmationResponseExpertDesk_OutgoingAttachmentsConfirmationResponseMessageExpertDesk
	 * @param context
	 * @param outgoingattachmentsconfirmationresponseexpertdesk_outgoingattachmentsconfirmationresponsemessageexpertdesk
	 */
	public final void setOutgoingAttachmentsConfirmationResponseExpertDesk_OutgoingAttachmentsConfirmationResponseMessageExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, interfaceattachments.proxies.OutgoingAttachmentsConfirmationResponseMessageExpertDesk outgoingattachmentsconfirmationresponseexpertdesk_outgoingattachmentsconfirmationresponsemessageexpertdesk)
	{
		if (outgoingattachmentsconfirmationresponseexpertdesk_outgoingattachmentsconfirmationresponsemessageexpertdesk == null)
			getMendixObject().setValue(context, MemberNames.OutgoingAttachmentsConfirmationResponseExpertDesk_OutgoingAttachmentsConfirmationResponseMessageExpertDesk.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.OutgoingAttachmentsConfirmationResponseExpertDesk_OutgoingAttachmentsConfirmationResponseMessageExpertDesk.toString(), outgoingattachmentsconfirmationresponseexpertdesk_outgoingattachmentsconfirmationresponsemessageexpertdesk.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final interfaceattachments.proxies.OutgoingAttachmentsConfirmationResponseExpertDesk that = (interfaceattachments.proxies.OutgoingAttachmentsConfirmationResponseExpertDesk) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "InterfaceAttachments.OutgoingAttachmentsConfirmationResponseExpertDesk";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
