// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package interfacerequestupdate.proxies;

public class OutgoingRequestUpdateConfirmationMessageExpertDesk extends interfacerequestupdate.proxies.OutgoingRequestUpdateConfirmation
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "InterfaceRequestUpdate.OutgoingRequestUpdateConfirmationMessageExpertDesk";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NextRetry("NextRetry"),
		RetryByHeartBeat("RetryByHeartBeat"),
		MessageID("MessageID"),
		MessageType("MessageType"),
		MessageDirection("MessageDirection"),
		Status("Status"),
		RetrievedInterfaceName("RetrievedInterfaceName"),
		CreatedByCustomMessage("CreatedByCustomMessage"),
		OutgoingRequestUpdateConfirmationExpertDesk_OutgoingRequestUpdateConfirmationMessageExpertDesk("InterfaceRequestUpdate.OutgoingRequestUpdateConfirmationExpertDesk_OutgoingRequestUpdateConfirmationMessageExpertDesk"),
		OutgoingRequestUpdateConfirmationMessageExpertDesk_MendixWebServiceHeader("InterfaceRequestUpdate.OutgoingRequestUpdateConfirmationMessageExpertDesk_MendixWebServiceHeader"),
		ProcessingAttempt_OutgoingConfirmation("InterfaceShared.ProcessingAttempt_OutgoingConfirmation"),
		InterfaceEvent_OutgoingMessage("InterfaceShared.InterfaceEvent_OutgoingMessage"),
		IncomingConfirmation_OutgoingMessage("InterfaceShared.IncomingConfirmation_OutgoingMessage"),
		OutgoingMessage_QueuedByOutgoingMessage("InterfaceShared.OutgoingMessage_QueuedByOutgoingMessage"),
		BooleanWrapper_Message("InterfaceShared.BooleanWrapper_Message"),
		Message_IndexData("InterfaceShared.Message_IndexData"),
		Message_InterfaceMessageConfiguration("InterfaceShared.Message_InterfaceMessageConfiguration"),
		Message_InterfaceConfiguration("InterfaceShared.Message_InterfaceConfiguration");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OutgoingRequestUpdateConfirmationMessageExpertDesk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "InterfaceRequestUpdate.OutgoingRequestUpdateConfirmationMessageExpertDesk"));
	}

	protected OutgoingRequestUpdateConfirmationMessageExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject outgoingRequestUpdateConfirmationMessageExpertDeskMendixObject)
	{
		super(context, outgoingRequestUpdateConfirmationMessageExpertDeskMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("InterfaceRequestUpdate.OutgoingRequestUpdateConfirmationMessageExpertDesk", outgoingRequestUpdateConfirmationMessageExpertDeskMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a InterfaceRequestUpdate.OutgoingRequestUpdateConfirmationMessageExpertDesk");
	}

	/**
	 * @deprecated Use 'OutgoingRequestUpdateConfirmationMessageExpertDesk.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static interfacerequestupdate.proxies.OutgoingRequestUpdateConfirmationMessageExpertDesk initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return interfacerequestupdate.proxies.OutgoingRequestUpdateConfirmationMessageExpertDesk.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static interfacerequestupdate.proxies.OutgoingRequestUpdateConfirmationMessageExpertDesk initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new interfacerequestupdate.proxies.OutgoingRequestUpdateConfirmationMessageExpertDesk(context, mendixObject);
	}

	public static interfacerequestupdate.proxies.OutgoingRequestUpdateConfirmationMessageExpertDesk load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return interfacerequestupdate.proxies.OutgoingRequestUpdateConfirmationMessageExpertDesk.initialize(context, mendixObject);
	}

	public static java.util.List<interfacerequestupdate.proxies.OutgoingRequestUpdateConfirmationMessageExpertDesk> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<interfacerequestupdate.proxies.OutgoingRequestUpdateConfirmationMessageExpertDesk> result = new java.util.ArrayList<interfacerequestupdate.proxies.OutgoingRequestUpdateConfirmationMessageExpertDesk>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//InterfaceRequestUpdate.OutgoingRequestUpdateConfirmationMessageExpertDesk" + xpathConstraint))
			result.add(interfacerequestupdate.proxies.OutgoingRequestUpdateConfirmationMessageExpertDesk.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of OutgoingRequestUpdateConfirmationExpertDesk_OutgoingRequestUpdateConfirmationMessageExpertDesk
	 */
	public final interfacerequestupdate.proxies.OutgoingRequestUpdateConfirmationExpertDesk getOutgoingRequestUpdateConfirmationExpertDesk_OutgoingRequestUpdateConfirmationMessageExpertDesk() throws com.mendix.core.CoreException
	{
		return getOutgoingRequestUpdateConfirmationExpertDesk_OutgoingRequestUpdateConfirmationMessageExpertDesk(getContext());
	}

	/**
	 * @param context
	 * @return value of OutgoingRequestUpdateConfirmationExpertDesk_OutgoingRequestUpdateConfirmationMessageExpertDesk
	 */
	public final interfacerequestupdate.proxies.OutgoingRequestUpdateConfirmationExpertDesk getOutgoingRequestUpdateConfirmationExpertDesk_OutgoingRequestUpdateConfirmationMessageExpertDesk(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacerequestupdate.proxies.OutgoingRequestUpdateConfirmationExpertDesk result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OutgoingRequestUpdateConfirmationExpertDesk_OutgoingRequestUpdateConfirmationMessageExpertDesk.toString());
		if (identifier != null)
			result = interfacerequestupdate.proxies.OutgoingRequestUpdateConfirmationExpertDesk.load(context, identifier);
		return result;
	}

	/**
	 * Set value of OutgoingRequestUpdateConfirmationExpertDesk_OutgoingRequestUpdateConfirmationMessageExpertDesk
	 * @param outgoingrequestupdateconfirmationexpertdesk_outgoingrequestupdateconfirmationmessageexpertdesk
	 */
	public final void setOutgoingRequestUpdateConfirmationExpertDesk_OutgoingRequestUpdateConfirmationMessageExpertDesk(interfacerequestupdate.proxies.OutgoingRequestUpdateConfirmationExpertDesk outgoingrequestupdateconfirmationexpertdesk_outgoingrequestupdateconfirmationmessageexpertdesk)
	{
		setOutgoingRequestUpdateConfirmationExpertDesk_OutgoingRequestUpdateConfirmationMessageExpertDesk(getContext(), outgoingrequestupdateconfirmationexpertdesk_outgoingrequestupdateconfirmationmessageexpertdesk);
	}

	/**
	 * Set value of OutgoingRequestUpdateConfirmationExpertDesk_OutgoingRequestUpdateConfirmationMessageExpertDesk
	 * @param context
	 * @param outgoingrequestupdateconfirmationexpertdesk_outgoingrequestupdateconfirmationmessageexpertdesk
	 */
	public final void setOutgoingRequestUpdateConfirmationExpertDesk_OutgoingRequestUpdateConfirmationMessageExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, interfacerequestupdate.proxies.OutgoingRequestUpdateConfirmationExpertDesk outgoingrequestupdateconfirmationexpertdesk_outgoingrequestupdateconfirmationmessageexpertdesk)
	{
		if (outgoingrequestupdateconfirmationexpertdesk_outgoingrequestupdateconfirmationmessageexpertdesk == null)
			getMendixObject().setValue(context, MemberNames.OutgoingRequestUpdateConfirmationExpertDesk_OutgoingRequestUpdateConfirmationMessageExpertDesk.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.OutgoingRequestUpdateConfirmationExpertDesk_OutgoingRequestUpdateConfirmationMessageExpertDesk.toString(), outgoingrequestupdateconfirmationexpertdesk_outgoingrequestupdateconfirmationmessageexpertdesk.getMendixObject().getId());
	}

	/**
	 * @return value of OutgoingRequestUpdateConfirmationMessageExpertDesk_MendixWebServiceHeader
	 */
	public final interfaceshared.proxies.MendixWebServiceHeader getOutgoingRequestUpdateConfirmationMessageExpertDesk_MendixWebServiceHeader() throws com.mendix.core.CoreException
	{
		return getOutgoingRequestUpdateConfirmationMessageExpertDesk_MendixWebServiceHeader(getContext());
	}

	/**
	 * @param context
	 * @return value of OutgoingRequestUpdateConfirmationMessageExpertDesk_MendixWebServiceHeader
	 */
	public final interfaceshared.proxies.MendixWebServiceHeader getOutgoingRequestUpdateConfirmationMessageExpertDesk_MendixWebServiceHeader(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceshared.proxies.MendixWebServiceHeader result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OutgoingRequestUpdateConfirmationMessageExpertDesk_MendixWebServiceHeader.toString());
		if (identifier != null)
			result = interfaceshared.proxies.MendixWebServiceHeader.load(context, identifier);
		return result;
	}

	/**
	 * Set value of OutgoingRequestUpdateConfirmationMessageExpertDesk_MendixWebServiceHeader
	 * @param outgoingrequestupdateconfirmationmessageexpertdesk_mendixwebserviceheader
	 */
	public final void setOutgoingRequestUpdateConfirmationMessageExpertDesk_MendixWebServiceHeader(interfaceshared.proxies.MendixWebServiceHeader outgoingrequestupdateconfirmationmessageexpertdesk_mendixwebserviceheader)
	{
		setOutgoingRequestUpdateConfirmationMessageExpertDesk_MendixWebServiceHeader(getContext(), outgoingrequestupdateconfirmationmessageexpertdesk_mendixwebserviceheader);
	}

	/**
	 * Set value of OutgoingRequestUpdateConfirmationMessageExpertDesk_MendixWebServiceHeader
	 * @param context
	 * @param outgoingrequestupdateconfirmationmessageexpertdesk_mendixwebserviceheader
	 */
	public final void setOutgoingRequestUpdateConfirmationMessageExpertDesk_MendixWebServiceHeader(com.mendix.systemwideinterfaces.core.IContext context, interfaceshared.proxies.MendixWebServiceHeader outgoingrequestupdateconfirmationmessageexpertdesk_mendixwebserviceheader)
	{
		if (outgoingrequestupdateconfirmationmessageexpertdesk_mendixwebserviceheader == null)
			getMendixObject().setValue(context, MemberNames.OutgoingRequestUpdateConfirmationMessageExpertDesk_MendixWebServiceHeader.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.OutgoingRequestUpdateConfirmationMessageExpertDesk_MendixWebServiceHeader.toString(), outgoingrequestupdateconfirmationmessageexpertdesk_mendixwebserviceheader.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final interfacerequestupdate.proxies.OutgoingRequestUpdateConfirmationMessageExpertDesk that = (interfacerequestupdate.proxies.OutgoingRequestUpdateConfirmationMessageExpertDesk) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "InterfaceRequestUpdate.OutgoingRequestUpdateConfirmationMessageExpertDesk";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
