// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package interfacerequestupdate.proxies;

public class OutgoingRequestUpdateMessageExpertDesk extends interfacerequestupdate.proxies.OutgoingRequestUpdate
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "InterfaceRequestUpdate.OutgoingRequestUpdateMessageExpertDesk";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NextRetry("NextRetry"),
		RetryByHeartBeat("RetryByHeartBeat"),
		MessageID("MessageID"),
		MessageType("MessageType"),
		MessageDirection("MessageDirection"),
		Status("Status"),
		RetrievedInterfaceName("RetrievedInterfaceName"),
		CreatedByCustomMessage("CreatedByCustomMessage"),
		OutgoingRequestUpdateExpertDesk_OutgoingRequestUpdateMessageExpertDesk("InterfaceRequestUpdate.OutgoingRequestUpdateExpertDesk_OutgoingRequestUpdateMessageExpertDesk"),
		OutgoingRequestUpdateMessageExpertDesk_MendixWebServiceHeader("InterfaceRequestUpdate.OutgoingRequestUpdateMessageExpertDesk_MendixWebServiceHeader"),
		OutgoingRequestUpdate_Request("InterfaceRequestUpdate.OutgoingRequestUpdate_Request"),
		InterfaceEvent_OutgoingMessage("InterfaceShared.InterfaceEvent_OutgoingMessage"),
		IncomingConfirmation_OutgoingMessage("InterfaceShared.IncomingConfirmation_OutgoingMessage"),
		OutgoingMessage_QueuedByOutgoingMessage("InterfaceShared.OutgoingMessage_QueuedByOutgoingMessage"),
		BooleanWrapper_Message("InterfaceShared.BooleanWrapper_Message"),
		Message_IndexData("InterfaceShared.Message_IndexData"),
		Message_InterfaceMessageConfiguration("InterfaceShared.Message_InterfaceMessageConfiguration"),
		Message_InterfaceConfiguration("InterfaceShared.Message_InterfaceConfiguration");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OutgoingRequestUpdateMessageExpertDesk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "InterfaceRequestUpdate.OutgoingRequestUpdateMessageExpertDesk"));
	}

	protected OutgoingRequestUpdateMessageExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject outgoingRequestUpdateMessageExpertDeskMendixObject)
	{
		super(context, outgoingRequestUpdateMessageExpertDeskMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("InterfaceRequestUpdate.OutgoingRequestUpdateMessageExpertDesk", outgoingRequestUpdateMessageExpertDeskMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a InterfaceRequestUpdate.OutgoingRequestUpdateMessageExpertDesk");
	}

	/**
	 * @deprecated Use 'OutgoingRequestUpdateMessageExpertDesk.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static interfacerequestupdate.proxies.OutgoingRequestUpdateMessageExpertDesk initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return interfacerequestupdate.proxies.OutgoingRequestUpdateMessageExpertDesk.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static interfacerequestupdate.proxies.OutgoingRequestUpdateMessageExpertDesk initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new interfacerequestupdate.proxies.OutgoingRequestUpdateMessageExpertDesk(context, mendixObject);
	}

	public static interfacerequestupdate.proxies.OutgoingRequestUpdateMessageExpertDesk load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return interfacerequestupdate.proxies.OutgoingRequestUpdateMessageExpertDesk.initialize(context, mendixObject);
	}

	public static java.util.List<interfacerequestupdate.proxies.OutgoingRequestUpdateMessageExpertDesk> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<interfacerequestupdate.proxies.OutgoingRequestUpdateMessageExpertDesk> result = new java.util.ArrayList<interfacerequestupdate.proxies.OutgoingRequestUpdateMessageExpertDesk>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//InterfaceRequestUpdate.OutgoingRequestUpdateMessageExpertDesk" + xpathConstraint))
			result.add(interfacerequestupdate.proxies.OutgoingRequestUpdateMessageExpertDesk.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of OutgoingRequestUpdateExpertDesk_OutgoingRequestUpdateMessageExpertDesk
	 */
	public final interfacerequestupdate.proxies.OutgoingRequestUpdateExpertDesk getOutgoingRequestUpdateExpertDesk_OutgoingRequestUpdateMessageExpertDesk() throws com.mendix.core.CoreException
	{
		return getOutgoingRequestUpdateExpertDesk_OutgoingRequestUpdateMessageExpertDesk(getContext());
	}

	/**
	 * @param context
	 * @return value of OutgoingRequestUpdateExpertDesk_OutgoingRequestUpdateMessageExpertDesk
	 */
	public final interfacerequestupdate.proxies.OutgoingRequestUpdateExpertDesk getOutgoingRequestUpdateExpertDesk_OutgoingRequestUpdateMessageExpertDesk(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfacerequestupdate.proxies.OutgoingRequestUpdateExpertDesk result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OutgoingRequestUpdateExpertDesk_OutgoingRequestUpdateMessageExpertDesk.toString());
		if (identifier != null)
			result = interfacerequestupdate.proxies.OutgoingRequestUpdateExpertDesk.load(context, identifier);
		return result;
	}

	/**
	 * Set value of OutgoingRequestUpdateExpertDesk_OutgoingRequestUpdateMessageExpertDesk
	 * @param outgoingrequestupdateexpertdesk_outgoingrequestupdatemessageexpertdesk
	 */
	public final void setOutgoingRequestUpdateExpertDesk_OutgoingRequestUpdateMessageExpertDesk(interfacerequestupdate.proxies.OutgoingRequestUpdateExpertDesk outgoingrequestupdateexpertdesk_outgoingrequestupdatemessageexpertdesk)
	{
		setOutgoingRequestUpdateExpertDesk_OutgoingRequestUpdateMessageExpertDesk(getContext(), outgoingrequestupdateexpertdesk_outgoingrequestupdatemessageexpertdesk);
	}

	/**
	 * Set value of OutgoingRequestUpdateExpertDesk_OutgoingRequestUpdateMessageExpertDesk
	 * @param context
	 * @param outgoingrequestupdateexpertdesk_outgoingrequestupdatemessageexpertdesk
	 */
	public final void setOutgoingRequestUpdateExpertDesk_OutgoingRequestUpdateMessageExpertDesk(com.mendix.systemwideinterfaces.core.IContext context, interfacerequestupdate.proxies.OutgoingRequestUpdateExpertDesk outgoingrequestupdateexpertdesk_outgoingrequestupdatemessageexpertdesk)
	{
		if (outgoingrequestupdateexpertdesk_outgoingrequestupdatemessageexpertdesk == null)
			getMendixObject().setValue(context, MemberNames.OutgoingRequestUpdateExpertDesk_OutgoingRequestUpdateMessageExpertDesk.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.OutgoingRequestUpdateExpertDesk_OutgoingRequestUpdateMessageExpertDesk.toString(), outgoingrequestupdateexpertdesk_outgoingrequestupdatemessageexpertdesk.getMendixObject().getId());
	}

	/**
	 * @return value of OutgoingRequestUpdateMessageExpertDesk_MendixWebServiceHeader
	 */
	public final interfaceshared.proxies.MendixWebServiceHeader getOutgoingRequestUpdateMessageExpertDesk_MendixWebServiceHeader() throws com.mendix.core.CoreException
	{
		return getOutgoingRequestUpdateMessageExpertDesk_MendixWebServiceHeader(getContext());
	}

	/**
	 * @param context
	 * @return value of OutgoingRequestUpdateMessageExpertDesk_MendixWebServiceHeader
	 */
	public final interfaceshared.proxies.MendixWebServiceHeader getOutgoingRequestUpdateMessageExpertDesk_MendixWebServiceHeader(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		interfaceshared.proxies.MendixWebServiceHeader result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OutgoingRequestUpdateMessageExpertDesk_MendixWebServiceHeader.toString());
		if (identifier != null)
			result = interfaceshared.proxies.MendixWebServiceHeader.load(context, identifier);
		return result;
	}

	/**
	 * Set value of OutgoingRequestUpdateMessageExpertDesk_MendixWebServiceHeader
	 * @param outgoingrequestupdatemessageexpertdesk_mendixwebserviceheader
	 */
	public final void setOutgoingRequestUpdateMessageExpertDesk_MendixWebServiceHeader(interfaceshared.proxies.MendixWebServiceHeader outgoingrequestupdatemessageexpertdesk_mendixwebserviceheader)
	{
		setOutgoingRequestUpdateMessageExpertDesk_MendixWebServiceHeader(getContext(), outgoingrequestupdatemessageexpertdesk_mendixwebserviceheader);
	}

	/**
	 * Set value of OutgoingRequestUpdateMessageExpertDesk_MendixWebServiceHeader
	 * @param context
	 * @param outgoingrequestupdatemessageexpertdesk_mendixwebserviceheader
	 */
	public final void setOutgoingRequestUpdateMessageExpertDesk_MendixWebServiceHeader(com.mendix.systemwideinterfaces.core.IContext context, interfaceshared.proxies.MendixWebServiceHeader outgoingrequestupdatemessageexpertdesk_mendixwebserviceheader)
	{
		if (outgoingrequestupdatemessageexpertdesk_mendixwebserviceheader == null)
			getMendixObject().setValue(context, MemberNames.OutgoingRequestUpdateMessageExpertDesk_MendixWebServiceHeader.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.OutgoingRequestUpdateMessageExpertDesk_MendixWebServiceHeader.toString(), outgoingrequestupdatemessageexpertdesk_mendixwebserviceheader.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final interfacerequestupdate.proxies.OutgoingRequestUpdateMessageExpertDesk that = (interfacerequestupdate.proxies.OutgoingRequestUpdateMessageExpertDesk) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "InterfaceRequestUpdate.OutgoingRequestUpdateMessageExpertDesk";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
